### ISSUE TITLE
Improve error handling in egs/sre10/v1/local/prepare_for_eer.py

### ISSUE THREAD

**Issue by david-ryan-snyder** [kaldi-asr/kaldi#1015]
The script takes a trials list and a PLDA score file, and generates output for the binary compute-eer.

However, it currently just dies on bad input. Do more checking of arguments and inputs, and print an informative message on bad input. See other python scripts in Kaldi. Related to #1014.

**Comment by kkm000** [comment]
@david-ryan-snyder, is this still relevant?
