### ISSUE TITLE
Investigated cudaAtomicAdd() in forward-backward implementation

### ISSUE THREAD

**Issue by galv** [kaldi-asr/kaldi#1024]
The current atomic add implementation in chain/chain-kernels.cu uses cudaAtomicExch(). I suspect using cuda's existing built-in function cudaAtomicAdd() directly may be faster.

The task, which I'm taking, involves benchmarking the speed of the forward-backward implementation with both implementations of atomic addition.

**Comment by galv** [comment]
I can't self-assign this. Whoops. Well, I'm working on it.

**Comment by danpovey** [comment]
Sorry, only project members can self-assign, and I don't like having the
bulk of contributors as project members because it's hard to know where to
draw the line, it's a "long tail" of contributors with no natural cutoff
point.  So just a few admins are official project members.

**Comment by galv** [comment]
@danpovey I realize now that it's painful to get a large example to create a unit test "speed test" with without either hard-coding very large transitions, forward_transitions, and backward_transitions arrays or loading them in from disk (adding binary bloat). Do you consider it necessary to add a unit test of the speed of the forward backward computation, assuming that cudaAtomicAdd() does cause a speedup?

**Comment by galv** [comment]
Done by #1025
