### ISSUE TITLE
build issue with text-io

### ISSUE THREAD

**Issue by jaredmauch** [kaldi-asr/kaldi#1030]
The software will not build from source due to this typecast related issue.

<pre>
libtool: compile:  g++ -DHAVE_CONFIG_H -I./../include -MT text-io.lo -MD -MP -MF .deps/text-io.Tpo -c text-io.cc  -fPIC -DPIC -o .libs/text-io.o
text-io.cc: In function 'bool fst::script::WritePotentials(const string&, const std::vector<fst::script::WeightClass>&)':
text-io.cc:87:15: error: cannot convert 'std::ostream {aka std::basic_ostream<char>}' to 'bool' in initialization
   bool ret = *strm;
               ^~~~
Makefile:388: recipe for target 'text-io.lo' failed
</pre>

**Comment by danpovey** [comment]
I think this happens with an older gcc version, I recall someone else had
the same issue.  Update your gcc.

**Comment by danpovey** [comment]
Sorry, it's with a too-new gcc, 6.x

This issue is the same as Issue #941.

You can resolve it by changing the openfst version in tools/Makefile to
1.4.1.

**Comment by jtrmal** [comment]
I guess it could be replaced by strm.good()
y.

**Comment by danpovey** [comment]
Hm, that would make building Kaldi more painless as this compiler gets more common; we could extend our patch.  @jaredmauch, do you have time to test whether OpenFst builds if you change that line to
`bool ret = strm->good()`
?

**Comment by jtrmal** [comment]
actually, let me check on something -- good() might not be the right
function, as there are IIRC three state bits in ios base, so it's possible
good() is not doing exactly what is equivalent to (bool) cast

y.

**Comment by jtrmal** [comment]
Looking at this:
http://www.cplusplus.com/reference/ios/ios/operator_bool/

I think we want
bool ret = !strm->fail()

What do you think?

**Comment by danpovey** [comment]
That sounds plausible; in any case the difference will probably only matter in weird situations.
Not sure if you have time to modify our patching setup?  I know dealing with that stuff is a hassle, I always forget how to generate the patches.

**Comment by jtrmal** [comment]
yeah, ok, I will do it.
Not sure how to test it (except running the kaldi tests)
y.

**Comment by jtrmal** [comment]
should be addressed now by #1038
