### ISSUE TITLE
Modify TransitionModel for more compact chain-model graphs

### ISSUE THREAD

**Issue by danpovey** [kaldi-asr/kaldi#1031]
This is a rather complex and also high-impact issue which I would really appreciate being able to offload.    @francisr, would you be able to help with this?

In the chain model, we use a topology where the 1st transition of the state has a different pdf-id to the others.  Because the TransitionModel assumes a "HMM-like" model where the emissions are associated with the state, this cannot be implemented in the most natural way with 1 emitting state, and we need to do it with 2 emitting states.  This doubles the size of the graphs, and I just noticed that the chain-model graphs are actually only slightly smaller than the baseline graphs.  This is disappointing and will likely nearly double the graph-searsh computation time, not to mention memory.

I have been thinking about the best way to solve this, and it involves changes in the TransitionModel object.  I don't want to be too general here, because nobody really plays with this stuff much.  The minimal change is that instead of each state being associated with one pdf-class (in the prototype) or pdf-id (in the specific state, after clustering), each state will have, in general, two pdf-classes/pdf-ids; one for "forward transitions" and one for the self-loop.  Note that due to reordering (which is always used), the self-loop actually gets taken after the "forward transitions".  Obviously if we were designing this from scratch it wouldn't be designed this way, but there are historical reasons for the design.
# Changes to HmmTopology

 In the prototype topology format, the pdf-class of a state is specified using `<PdfClass> 0` and the like.  This format will be extended to support saying something like `<PdfClass> 0 <SelfLoopPdfClass> 1`.  If not specified (and for back compatibility in reading), the SelfLoopPdfClass will default to the same value as the PdfClass.  It will be required that in struct HmmState, the pdf_class and self_loop_pdf_class variables will either both be kNoPdf, or neither be kNoPdf (no mixing).  Check that the validation scripts in utils/ support this changed format.  The function NumPdfClasses() will need to be updated.   Documentation will need to be adjusted in doc/.  Note: after this change, the 'reordering' option in graph construction will no longer produce identical graphs with true vs. false.  Some documentation changes will be required.  But we always use 'true' in practice so this is not an issue of practical importance.
# Changes to TransitionModel

The 'triples' (phone, hmm-state, pdf-id) that the TransitionModel stores will need to be extended and renamed to be 'tuples' which are actually 4-tuples (phone, hmm-state, pdf-id, self-loop-pdf-id).  Obviously back compatibility needs to be considered in the reading code.  There may be some code that uses TransitionModel that needs to be changed slightly; you can let this be driven by compilation errors.

The function TransitionStateToPdf() will have to be removed from the interface (and the documentation) since this mapping is no longer unique.  This is OK since it was never used by external code.  
# Changes to chain code

The script in steps/nnet3/chain/gen_topo.pl should be updated to use the new, more compact form of the topology (with one emitting state with 2 different pdf-ids).

In chain-den-graph.cc there is the line
`bool reorder = false;`
and that should be changed to true (since it's no longer equivalent).  It was set to false because we found that that minimized the graph size.  But the reordered model will no longer be equivalent with the new topology, so we need to have it the same as we use in graph construction in test time (i.e. true).  Check, in building the chain model, that the number of states when building the denominator graph does not increase-- I am hoping that it will get smaller (due to the change to gen_topo.pl).
# Testing

You should make sure that some simple example scripts, like egs/rm/s5/run.sh, work after this change.  Then the real test is to make sure that the chain models work with this change and that the decoding graph in [whatever]/graph/HCLG.fst gets smaller; it should be about half the size.

**Comment by danpovey** [comment]
A second-order issue... previously in DenGraphMinimizeWrapper, I found that doing non-reversed minimization before reversed minimization produced a smaller graph (fewer states) than the other way round.  This may change when you modify the 'reverse' option to true.   You'd have to change the code inside the loop.

**Comment by danpovey** [comment]
It would probably be good to make sure that for models in which the pdf-class for the self-loop and non-self-loop arcs are the same, we write the models using the older format (`<Triples>` or whatever).  We'll need to be able to read this format regardless, for back compatiility.  This will ensure that if people have written code to parse the text format for some reason, it does not break.  It will likely be useful to add to the HmmTopology class a function  `bool IsHmm()` which will return true if for all the topologies, the self-loop and non-self-loop arcs have the same pdf-class.

**Comment by danpovey** [comment]
@francisr, let us know if you have time to do this (e.g. this week), otherwise I'll find someone else.

**Comment by francisr** [comment]
This would be a good improvement, but unfortunately I'm too busy at the moment.

**Comment by danpovey** [comment]
ok.  @naxingyu, do you have time?

**Comment by naxingyu** [comment]
Yes. I'll begin tomorrow.

**Comment by danpovey** [comment]
@naxingyu, have you made any progress on this?

**Comment by naxingyu** [comment]
I started coding yesterday，nothing to commit yet.

发自我的 iPhone

**Comment by naxingyu** [comment]
It seems difficult to keep back compatibility in reading code of binary models, since we are adding a member and in binary mode the members are read directly without tags. Any suggestion?

**Comment by naxingyu** [comment]
Oh I figure out what to do. Sorry.

**Comment by naxingyu** [comment]
hi Dan,
1. When modifying the binary reading code, it seems difficult to keep back compatibility, since the binary reading code work without tags. 
2. In the computing triples code, which is being modified to computing tuples, the pdf info is generated based on pdf_class. However, the new Tuple construction function require pdf_class and self_loop_pdf_class. It seems that I should modify the pdf related functions in ContextDependency class too.

**Comment by danpovey** [comment]
hi Dan,

> 1. When modifying the binary reading code, it seems difficult to keep back
> compatibility, since the binary reading code work without tags.
>
Please figure out a way to do this-- for instance, if you know that a
certain number is positive, you could use a negative number as a signal
that it wasn't the old format.  Probably the "new" format should have tags
even for the binary, if that's practical.


> 2. In the computing triples code, which is being modified to computing
> tuples, the pdf info is generated based on pdf_class. However, the new
> Tuple construction function require pdf_class and self_loop_pdf_class.
>
Yes.

It seems that I should modify the pdf related functions in
> ContextDependency class too.
>
Actually I don't think so.  The ContextDependency objects maps from
pdf_class and phonetic context to pdf.  The HmmTopology object is all about
the relationship between the topologies and the pdf_class.  The
self_loop_pdf_class is just a potentially different value of pdf_class.
E.g. a 3-state hmm will have 3 states with pdf-class = 0, 1, 2 and
self-loop-pdf-class = 0, 1, 2 (i.e. the same as the pdf-class for forward
transitions).  A chain-model HMM will have maybe pdf-class=0 and
self_loop_pdf_class=1, for one state.  But anyway, none of this should
affect the ContextDependency class.
Dan

**Comment by danpovey** [comment]
Bear in mind that pdf_class and self_loop_pdf_class are the same
"type" of index, they are all pdf_classes.  self_loop_pdf_class just
means "the pdf-class that we have on the self-loop of this HMM state".
It's not a different *type* of quantity.

**Comment by naxingyu** [comment]
In my understanding, a `triple` defines a physical HMM state that will consume one frame of acoustic feature. In `Triple`, the consumption can happen either in an outward transition or a self-loop transition, which share one `pdf_id`, but weighted by transition probabilities. If extended to `Tuple`, this complex still define a state, but consumes acoustics following the principle that the self-loop transition used `self_loop_pdf_id`, while the outward transitions share the `pdf_id`. And all the transition are still weighted by the transition probabilities. For instance, the current transition model of a normal HMM is 
```
Transition-state 2: phone = sil hmm-state = 1 pdf = 69
 Transition-id = 5 p = 0.835146 [self-loop]
 Transition-id = 6 p = 0.01 [1 -> 2]
 Transition-id = 7 p = 0.01 [1 -> 3]
 Transition-id = 8 p = 0.144859 [1 -> 4]
```
while in the new structure, this transition-state still contain four transition-ids, but defined as
```
Transition-state 2: phone = sil hmm-state = 1 pdf = 69 self-loop-pdf = 69
 Transition-id = 5 p = 0.835146 [self-loop]
 Transition-id = 6 p = 0.01 [1 -> 2]
 Transition-id = 7 p = 0.01 [1 -> 3]
 Transition-id = 8 p = 0.144859 [1 -> 4]
```
And a chain transition model will be defined as
```
Transition-state 2: phone = sil hmm-state = 1 pdf = 55 self-loop-pdf = 1
 Transition-id = 3 p = 0.5 [self-loop]
 Transition-id = 4 p = 0.5 [1 -> 2]
```
Now, if the above stands correct and the hmm-topology is modified as the requested way, the `pdf_info` used in [ComputeTriples](https://github.com/kaldi-asr/kaldi/blob/master/src/hmm/transition-model.cc#L34) would contain both pdf_class and self_loop_pdf_class, without knowing the differences. Therefore, the [iterated creation](https://github.com/kaldi-asr/kaldi/blob/master/src/hmm/transition-model.cc#L52) of `triples_` will create more transition-states than expected, unless there is a map from `self_loop_pdf_id` to the current `triple` so that not every iteration does a [push_back](https://github.com/kaldi-asr/kaldi/blob/master/src/hmm/transition-model.cc#L62).

Does it make sense? Please comment.

**Comment by danpovey** [comment]
In my understanding, a triple defines a physical HMM state that will
consume one frame of acoustic feature. In Triple, the consumption can
happen either in an outward transition or a self-loop transition, which
share one pdf_id, but weighted by transition probabilities. If extended to
Tuple, this complex still define a state, but consumes acoustics following
the principle that the self-loop transition used self_loop_pdf_id, while
the outward transitions share the pdf_id. And all the transition are still
weighted by the transition probabilities. For instance, the current
transition model of a normal HMM is

> Transition-state 2: phone = sil hmm-state = 1 pdf = 69
>  Transition-id = 5 p = 0.835146 [self-loop]
>  Transition-id = 6 p = 0.01 [1 -> 2]
>  Transition-id = 7 p = 0.01 [1 -> 3]
>  Transition-id = 8 p = 0.144859 [1 -> 4]
>
> while in the new structure, this transition-state still contain four
> transition-ids, but defined as
>
> Transition-state 2: phone = sil hmm-state = 1 pdf = 69 self-loop-pdf = 69
>  Transition-id = 5 p = 0.835146 [self-loop]
>  Transition-id = 6 p = 0.01 [1 -> 2]
>  Transition-id = 7 p = 0.01 [1 -> 3]
>  Transition-id = 8 p = 0.144859 [1 -> 4]
>
> And a chain transition model will be defined as
>
> Transition-state 2: phone = sil hmm-state = 1 pdf = 55 self-loop-pdf = 1
>  Transition-id = 3 p = 0.5 [self-loop]
>  Transition-id = 4 p = 0.5 [1 -> 2]
>
> Now, if the above stands correct and the hmm-topology is modified as the
> requested way, the pdf_info used in ComputeTriples
> <https://github.com/kaldi-asr/kaldi/blob/master/src/hmm/transition-model.cc#L34>
> would contain both pdf_class and self_loop_pdf_class, without knowing the
> differences. Therefore, the iterated creation
> <https://github.com/kaldi-asr/kaldi/blob/master/src/hmm/transition-model.cc#L52>
> of triples_ will create more transition-states than expected, unless
> there is a map from self_loop_pdf_id to the current triple so that not
> every iteration does a push_back
> <https://github.com/kaldi-asr/kaldi/blob/master/src/hmm/transition-model.cc#L62>
> .
>

The information output by ctx_dep.GetPdfInfo() is indexed by pdf_class, and
there is an assumption that the pdf_classes in a topology start with zero
and are contiguous (I believe this is checked in the HmmTopology class).

At this point we know nothing about the topology, and don't have to.  It's
a few lines later, when it says
```
for (int32 j = 0; j < static_cast<int32>(entry.size()); j++) {  // for each
state...
      int32 pdf_class = entry[j].pdf_class;
```
that you start worrying about the topology.. probably at this point you'd
need to think about the self-loop pdf class.
The pdf-classes are integers that define tying of pdfs... they used to
define tying of states, but after this change they will define tying of
arcs in the HMM topology, and the documentation will have to be updated.

I'm not sure if this answers your question.

Dan

**Comment by naxingyu** [comment]
Here, I will modify as something like
```
    for (int32 j = 0; j < static_cast<int32>(entry.size()); j++) {  // for each state...
      int32 pdf_class = entry[j].pdf_class, self_loop_pdf_class = entry[j].self_loop_pdf_class,;
      if (pdf_class != kNoPdf) {
        to_hmm_state_list[std::make_pair(phone, pdf_class)].push_back(j);
      }
      if (self_loop_pdf_class != pdf_class) {
        to_hmm_state_list[std::make_pair(phone, self_loop_pdf_class)].push_back(j);
      }
    }
```
The problem is, later when creating triples/tuples, `pdf_class` and `self_loop_pdf_class` are equally treated as pdf classes, in both to_hmm_state_list and pdf_info. There is no way to create a (phone, hmm_state, pdf, self_loop_pdf) tuple like that.

**Comment by danpovey** [comment]
Some of the data structures will have to change... definitely the triples
become 4-tuples.  Possibly the to_hmm_state_list pairs will become triples,
although I'm just looking at that snipped and don't remember what it is.

**Comment by naxingyu** [comment]
Yes, I was planning to do that two days ago but found that this loop
```
for (int32 pdf = 0; pdf < static_cast<int32>(pdf_info.size()); pdf++) {
```
is based on undistinguished pdf classes. Maybe I need to rewrite this loop using `to_hmm_state_list` as iterator...

**Comment by danpovey** [comment]
You might find it better to rewrite that function ComputeTriples() from
scratch.
Of course, the name would have to change to ComputeTuples().
Basically what it is doing is finding all the 4-tuples
(phone, hmm-state, pdf_class, self_loop_pdf_class)
can occur.
GetPdfInfo gives you a map from pdf -> (phone, pdf_class).
You could rework that into a vector<vector<vector<int32> > >
that is indexed [phone][pdf_class] and then gives you a list of possible
pdfs.

Then you could go:
  - for each phone
    - for each hmm-state for that phone
       - work out the list of possible pairs (pdf, self_loop_pdf)

Hm.  I see now that there is a problem, because if the pdf_class and the
self_loop_pdf_class are different then the only way to work out the list of
possible pairs is to enumerate all pairs of possibilities, which
"over-generates".  Let me think what to do.

**Comment by danpovey** [comment]
OK, I think I've figured out how to do it, but it's not very trivial or
pretty.

Firstly, for speed, if it's the case that the self_loop_pdf_class is always
the same as the pdf_class then you should do something equivalent to the
old code, calling GetPdfInfo.  The code in TransitionModel will have to be
in two branches, depending if the self_loop_pdf_class was always the same
as the pdf_class.  [Note: for testing purposes you can try taking the other
side of the  branch sometimes.]

Now, in the other side of the branch, we'll need to have a different
version of GetPdfInfo:

/// This function outputs information about what possible pdf-ids can
/// be generated for HMM-states; it is specialized for the case where
/// the self-loop pdf-class may be different from the forward-transition
/// pdf-class, so we are asking not about the set of possible pdf-ids
/// for a given (phone, pdf-class), but the set of possible ordered pairs
/// (forward-transition-pdf, self-loop-pdf) for a given (phone,
/// forward-transition-pdf-class, self-loop-pdf-class).
/// Note: 'phones' is a list of integer ids of phones, and
/// 'pdf-class-pairs', indexed by phone, is a list of pairs
/// (forward-transition-pdf-class, self-loop-pdf-class) that we can have for
/// that phone.
/// The output 'pdf_info' is indexed first by phone and then by the
/// same index that indexes each element of 'pdf_class_pairs',
/// and tells us for each pair in 'pdf_class_pairs', what is the
/// list of possible (forward-transition-pdf-id, self-loop-pdf-id) that
/// we can have.
/// This is less efficient than the other version of GetPdfInfo().
void ContextDependency::GetPdfInfo(
       const std::vector<int32> &phones,
       const std::vector<std::pair<int32, int32> > &pdf_class_pairs,
        std::vector<std::vector<std::pair<int32, int32> > > *pdf_info)
const;


Now, the obvious way to implement the above function is to enumerate
all the possible context-windows of phones; for each such window
and for each pdf-class pair we'd manually query the tree for what the
pdf is.
Of course, for triphone and above that's quite inefficient, and even more
so if we have things like tone and word-position-dependency.
It *is* possible to make it more efficient by being a bit more clever.
The MultiMap function allows you to query the tree with partial information
and get all possible values.  So, for instance, starting with the central
phone and the pdf-class you could call MultiMap() and get the set of
pdf-ids, and if you get more than one for a particular phone then you can
start off adding different values of the right context phone, then if there
are still multiple values, add the left context phone, and so on.   I
haven't thought through the details, but this kind of thing is definitely
possible.
Anyway in many cases of interest we'll be building left-biphone systems so
there won't be any problem with efficiency.




Dan

**Comment by naxingyu** [comment]
On 2016/10/9 12:30, Daniel Povey wrote:
> OK, I think I've figured out how to do it, but it's not very trivial or
> pretty.
>
> Firstly, for speed, if it's the case that the self_loop_pdf_class is 
> always
> the same as the pdf_class then you should do something equivalent to the
> old code, calling GetPdfInfo. The code in TransitionModel will have to be
> in two branches, depending if the self_loop_pdf_class was always the same
> as the pdf_class. [Note: for testing purposes you can try taking the other
> side of the branch sometimes.]
>
> Now, in the other side of the branch, we'll need to have a different
> version of GetPdfInfo:
>
> /// This function outputs information about what possible pdf-ids can
> /// be generated for HMM-states; it is specialized for the case where
> /// the self-loop pdf-class may be different from the forward-transition
> /// pdf-class, so we are asking not about the set of possible pdf-ids
> /// for a given (phone, pdf-class), but the set of possible ordered pairs
> /// (forward-transition-pdf, self-loop-pdf) for a given (phone,
> /// forward-transition-pdf-class, self-loop-pdf-class).
> /// Note: 'phones' is a list of integer ids of phones, and
> /// 'pdf-class-pairs', indexed by phone, is a list of pairs
> /// (forward-transition-pdf-class, self-loop-pdf-class) that we can 
> have for
> /// that phone.
> /// The output 'pdf_info' is indexed first by phone and then by the
> /// same index that indexes each element of 'pdf_class_pairs',
> /// and tells us for each pair in 'pdf_class_pairs', what is the
> /// list of possible (forward-transition-pdf-id, self-loop-pdf-id) that
> /// we can have.
> /// This is less efficient than the other version of GetPdfInfo().
> void ContextDependency::GetPdfInfo(
> const std::vector<int32> &phones,
> const std::vector<std::pair<int32, int32> > &pdf_class_pairs,
> std::vector<std::vector<std::pair<int32, int32> > > *pdf_info)
> const;
>
I think the later two parameters are
std::vector<std::vector<std::pair<int32, int32> > > &pdf_class_pairs
and
std::vector<std::vector<std::vector<std::pair<int32, int32> > > > *pdf_info.
The pdf_class_pairs is a phone-indexed list of lists of 
<forward_transition_pdf_class, self_loop_pdf_class> pairs, and the 
pdf_info is phone-indexed first, and each element is a list indexed by 
<forward_transition_pdf_class, self_loop_pdf_class> pair, which stores 
possible <forward_transition_pdf_id, self_loop_pdf_id> pairs.

Or, I'm thinking of defining pdf_info as
std::map<std::pair<int32, int32>, 
std::vector<std::vector<std::pair<int32, int32>>>>
which maps <forward_transition_pdf_id, self_loop_pdf_id> pair to 
phone-indexed lists of possible <forward_transition_pdf_class, 
self_loop_pdf_class> pairs that that pdf_id pair are derived from.

>
> Now, the obvious way to implement the above function is to enumerate
> all the possible context-windows of phones; for each such window
> and for each pdf-class pair we'd manually query the tree for what the
> pdf is.
I don't follow here. Why not query the pdf and self_loop_pdf separately 
using only the central phone? For each <forward_transition_pdf_class, 
self_loop_pdf_class> pair, call MultiMap twice to get a list of forward 
transition pdfs and a list of self loop pdfs. Is that doable?

Xingyu

> Of course, for triphone and above that's quite inefficient, and even more
> so if we have things like tone and word-position-dependency.
> It *is* possible to make it more efficient by being a bit more clever.
> The MultiMap function allows you to query the tree with partial 
> information
> and get all possible values. So, for instance, starting with the central
> phone and the pdf-class you could call MultiMap() and get the set of
> pdf-ids, and if you get more than one for a particular phone then you can
> start off adding different values of the right context phone, then if 
> there
> are still multiple values, add the left context phone, and so on. I
> haven't thought through the details, but this kind of thing is definitely
> possible.
> Anyway in many cases of interest we'll be building left-biphone systems so
> there won't be any problem with efficiency.
>
>
>
>
> Dan
>
>

**Comment by naxingyu** [comment]
OK. And it requires modifying the context dependency interface, right?

X.

**Comment by danpovey** [comment]
The only interface change required is the one we discussed about the 2nd
version of GetPdfInfo().
That stuff about progressively increasing the context and querying
MultiMap() multiple times would be done inside GetPdfInfo().. not
necessarily in the function, but interface-wise, there is no need to expose
this stuff.  But as a 1st pass and so as to do better regression testing it
might be a good thing just to get all the pairs by brute force, because
anyway our chain models tend to be left-biphone so in practice for now
there really isn't a problem.

**Comment by naxingyu** [comment]
Is this considered done?

**Comment by danpovey** [comment]
Yes-- thanks.  Closing.
