### ISSUE TITLE
nnet3-to-dot fails in descriptor parsing

### ISSUE THREAD

**Issue by vijayaditya** [kaldi-asr/kaldi#1054]
When `steps/nnet3/dot/nnet3_to_dot.py` was written nnet3 placed stringent constraints on the way in which descriptors could be ordered in the configs. But @danpovey removed these constraints and resolved any ordering issues in the C++ code. 

`steps/nnet3/dot/nnet3_to_dot.py` has not yet been updated to accept the wider range of descriptor strings.

Requires : python, nnet3 knowledge

**Comment by vijayaditya** [comment]
Actually I wonder if it would be easier to just write a C++ binary for this. This way we could just use the nnet3 library to traverse computation graph and convert it to a dot graph; rather than parsing nnet3-am-info output and trying to sync this parser with the C++ changes,

**Comment by danpovey** [comment]
I'd rather not bulk up the C++ code with nonessential things like this.
