### ISSUE TITLE
Add support for --{left,right}-context options in nnet3-chain-copy-egs

### ISSUE THREAD

**Issue by vijayaditya** [kaldi-asr/kaldi#1057]
We would like to support `--left-context` and `--right-context` options in `nnet3-chain-copy-egs` similar to `nnet3-copy-egs`. This is a minor task, suitable for anyone trying to start contributing to nnet3 code.

Required : C++

**Comment by allesover** [comment]
Hi, Vijay, I will try this.

**Comment by GaofengCheng** [comment]
@vijayaditya Vijay When I do this work， I find the "NnetExample" uses "vector<NnetIo> io" for both the input and output, but the "NnetchainExample" uses "vector<NnetIo> io" for input and "vector<NnetChainSupervision>" for the output. This because using different the training criterion .

**Comment by GaofengCheng** [comment]
@vijayaditya Vijay When I do this work， I find the "NnetExample" uses "vector io" for both the input and output, but the "NnetchainExample" uses "vector io" for input and "vector NnetChainSupervision" for the output. This because using different the training criterion .

**Comment by vijayaditya** [comment]
Yes.

--Vijay

**Comment by GaofengCheng** [comment]
done...

**Comment by vijayaditya** [comment]
Being addressed in #1078
