### ISSUE TITLE
Kaldi help- 

### ISSUE THREAD

**Issue by sreelakshmikr** [kaldi-asr/kaldi#1073]
Can't I train the system using one speaker??? I am getting the error as " Refusing to split data because number of speakers 1 is less than the number of output .scp files 20 at utils/split_scp.pl line 114, <I> line 156.
"
How can I solve this???
![screenshot from 2016-09-29 12 05 49](https://cloud.githubusercontent.com/assets/21353973/18943204/cd6b095a-863b-11e6-93fa-3928a341c591.png)

**Comment by sreelakshmikr** [comment]
Its 4 right now not 20.....

**Comment by jtrmal** [comment]
This is not the right place to seek help.
