### ISSUE TITLE
Extra check to L.fst and L_disambig.fst

### ISSUE THREAD

**Issue by danpovey** [kaldi-asr/kaldi#1074]
we should check in validate_lang.pl that L.fst and L_disambig.fst do not have cycles with only epsilons and/or disambig symbols on the inputs, similar to what utils/lang/check_g_properties.pl does.   (this will likely involve adding a script utils/lang_check_l_properties.pl).

**Comment by j24205** [comment]
How to create L_disambig.fst??

**Comment by danpovey** [comment]
prepare_lang.sh does that.  Go through any of the recipes or the kaldi for dummies tutorial.
