### ISSUE TITLE
Adding maxout for the Nnet3 neural component

### ISSUE THREAD

**Issue by GaofengCheng** [kaldi-asr/kaldi#1077]
Is anybody doing this ? If not,  maybe I can try it.

**Comment by vijayaditya** [comment]
Yes, that would be good. There is a max-pooling component used for processing convolutional outputs, so when designing this component try to if the maxpooling component can be a child class of the maxout component.

**Comment by danpovey** [comment]
Just a note RE child-classes-- please don't force it if it's not 100%
natural.  I prefer code that's simple and easy to understand, even if it's
a little bit longer.

BTW, this component exists in nnet2, I think, so porting to nnet3 should
not be that hard.

**Comment by vijayaditya** [comment]
OK, I will keep this in mind.
