### ISSUE TITLE
Efficient implementation of LSTM

### ISSUE THREAD

**Issue by danpovey** [kaldi-asr/kaldi#1089]
I have an idea for a more efficient implementation of LSTM in the nnet3 framework.
@kangshiyin, if you have time, you might be a good person to do the coding aspects this, since it involves CUDA.  But @vijayaditya will probably want to do the scripts, and he and others may also have comments on the idea more generally.

I am referring to the formulation of LSTMs in http://static.googleusercontent.com/media/research.google.com/en//pubs/archive/43905.pdf.  Although we are using LSTMP, it won't affect what goes below.
Suppose the cell dimension is C.  We can compute the following 4 C-dimensional quantities in a single affine operation (this is something Vijay has already done in something that was not checked in, I think):

```
   i_part = W_{ix} x_t + W_{im} m_{t-1} + b_i
   f_part = W_{fx} x_t + W_{fm} m_{t-1} + b_f
   c_part = W_{cx} x_t + W_{cm} m_{t-1} + b_c
   o_part = W_{cx} x_t + W_{om} m_{t-1} + b_o
```

We will create a component that has an input dimension of 5  C (consisting of all of the above quantities plus c_{t-1}), and outputs something of dimension 2 C, consisting of c_t and m_t.  The component will have parameters of dimension 3 C (consisting of the three diagonal weight matrices w_{ic}, w_{fc} and w_{oc}).  Writing the diagonal weight matrices in lower-case to emphasize their diagonal-ness and using `*` for elementwise product, the component will do the following computation... and note that some of the quantities it uses do not appear in the input or output, they are internal to the function:

```
 i_t = Sigmoid(i_part + w_{ic}*c_{t-1})
 f_t = Sigmoid(f_part + w_{fc}*c_{t-1})
 c_t = f_t*c_{t-1} + i_t * Tanh(c_part)
 o_t = Sigmoid(o_part + w_{oc}*c_t)
 m_t = o_t * Tanh(c_t)
# note: the outputs are just c_t and m_t.
```

A note on derivatives: it will be easiest for both the CUDA kernels and for the integration with the natural gradient code, if the derivatives w.r.t. the 3 C parameters are output into a matrix whose dimension is (the number of separate indexes for which this function is being applied) by (3C): that is, that the kernels will not be responsible for summing up the gradient across all elements of the minibatch, but just computing the parameter gradients as a matrix and outputting them into a temporary variable declared inside the Backprop function.

**Comment by danpovey** [comment]
sorry still editing

**Comment by kangshiyin** [comment]
I'm sorry I'm kind of busy this month.  I think I need some time to get myself more familiar with the nnet3 component design before I can do this. Currently I'm also working on the normalize component.

**Comment by danpovey** [comment]
How about if someone else does the component design and explains what the
kernel needs to implement, and you just do the CUDA kernels?
@vijayaditya, any ideas for who can do the component-level stuff?

**Comment by vijayaditya** [comment]
No one comes to my mind immediately. But I will keep this task in mind when
we have other requests for collaboration.

Vijay

**Comment by kangshiyin** [comment]
@danpovey sure, that would be good.

**Comment by danpovey** [comment]
Shiyin, if you want you could just make a PR for the kernel when you have
time, and then we'll find someone to do the wrapping code.  It should be
reasonably obvious from my description for the 'issue' what is required.

**Comment by kangshiyin** [comment]
Ok, I will start look into it when time permits.

**Comment by hainan-xv** [comment]
I can help with this if that's OK.

**Comment by danpovey** [comment]
[posting directly as I keep forgetting my emails are being delayed somehow.]
@kangshiyin -- Hainan is talking about the component-level work.  I'm still hoping you can do the GPU stuff (once you get back to China).

**Comment by danpovey** [comment]
Shiyin-- Hainan is talking about the component-level work.  I'm still
hoping you can do the GPU stuff (once you get back to China).

Dan
