### ISSUE TITLE
Implementation of --extra-left-context and --extra-right-context options in online2-wav-nnet3-latgen-faster

### ISSUE THREAD

**Issue by vijayaditya** [kaldi-asr/kaldi#1091]
This is necessary for online decoding with RNN AMs.

**Comment by kkm000** [comment]
Not done.
```
$ ./online2bin/online2-wav-nnet3-latgen-faster --help |& grep -P 'extra-[a-z]+-context'
  --extra-left-context-initial : Extra left context to use at the first frame of an utterance (note: this will just consist of repeats of the first frame, and should not usually be necessary. (int, default = 0)
```

**Comment by v-yunbin** [comment]
it seems “--extra-left-context 、--extra-right-context” not were supported.
`Command line was:
ERROR (VoskAPI:ReadConfigFile():parse-options.cc:493) Invalid option --extra-left-context=50 in config file model_tdnn_lstm//conf/model.conf
terminate called after throwing an instance of 'kaldi::KaldiFatalError'
  what():  kaldi::KaldiFatalError
Aborted (core dumped)`
TDNN-LSTM get more gain than TDNN on my testset, so adding them supporting is worthing.

**Comment by danpovey** [comment]
For extra-left-context in this online program you can use --extra-left-context-initial.
Exgtra right context is not really supported.

**Comment by v-yunbin** [comment]
I use only "--extra-left-context-initial" to decode lstm,  the accuracy rate drops a lot, just due to train lstm model with "chunk_left_context=40 、chunk_right_context=0“.
whether can I train lstm model with "chunk_left_context=0 、chunk_right_context=0"?

**Comment by v-yunbin** [comment]
@danpovey I compare some results as follows:
tdnn_lstm_all_sp: train lstm with opts ”"chunk_left_context=40 、chunk_right_context=0““
tdnn_lstm2_all_sp: train lstm with opts ”"chunk_left_context=0 、chunk_right_context=0““
```
# Model                tdnn_lstm_all_sp tdnn_lstm2_all_sp
# Num. of params             26.6M
     26.6M
# WER(%)                     3.72      3.71
# Final train prob        -0.0608   -0.0606
# Final valid prob        -0.0647   -0.0644
# Final train prob (xent)   -0.6213   -0.6225
# Final valid prob (xent)   -0.6573   -0.6522
```

**Comment by v-yunbin** [comment]
@danpovey teacher : If i train tdnn-lstm model without “--extra-left-context 、--extra-right-context” , whether I can use "online decode" to decode tdnn-lstm model ?

**Comment by kkm000** [comment]
@v-yunbin, it's irrelevant w.r.t. online/offline. In both cases, you can pad input with silence or low-amplitude (-60dB is a good ballpark) white noise at both start and end to satisfy context length. I usually use noise, as dead silence of all zeros may often to denormal floats and other computation issues in DSP. Unlikely in Kaldi, just out of habit.

Please do not reuse issues to ask questions. **We have a forum that is the best place to ask questions**, and getting answers and input from other users as well. We are hanging out there all the time, too. Here, in the issue tracker, we are just too few.

**Kaldi help forum**: https://groups.google.com/forum/#!forum/kaldi-help

**Instructions for joining**: http://kaldi-asr.org/forums.html
