### ISSUE TITLE
bugs in swbd/s5c/local/chain/tuning/run_blstm_6h.sh and other chain lstm scripts

### ISSUE THREAD

**Issue by GaofengCheng** [kaldi-asr/kaldi#1100]
bug found in run_blstm_6h.sh, run_lstm_6i.sh....
in run_lstm_6i.sh line 118:
`  steps/nnet3/lstm/make_configs.py  \`
`.....`
`--self-repair-scale 0.00001 \`
but the steps/nnet3/lstm/make_configs.py requires:
                `self_repair_scale_nonlinearity = args.self_repair_scale_nonlinearity,`
                `self_repair_scale_clipgradient = args.self_repair_scale_clipgradient)`
leading to error:
`make_configs.py: error: ambiguous option: --self-repair-scale could match --self-repair-scale-nonlinearity, --self-repair-scale-clipgradient`

**Comment by vijayaditya** [comment]
There are a lot of discrepancies like these across different recipes, as
self-repair-scale was recently introduced. Could you please submit a commit
fixing these ?

**Comment by GaofengCheng** [comment]
Ok

**Comment by danpovey** [comment]
I think it's safe to assume that whenever it's given as just
--self-repair-scale, what is meant is --self-repair-scale-nonlinearity

**Comment by vijayaditya** [comment]
I think @freewym already corrected this for tdnn config generators, where
self-repair-scale would have have meant self-repair-scale-nonlinearity. The
remaining issues are for RNNs, so please add both
self-repair-scale-nonlinearity and self-repair-scale-clipgradient for these
scripts. Just use the values you find in swbd/s5c/run_blstm.sh for these
variables.

--Vijay

**Comment by danpovey** [comment]
OK, but probably best not to add --self-repair-scale-clipgradient for the
older experiments that are only present in tuning/, or aren't currently the
latest recommended versions of any of the types of model.  To do so would
add a certain amount of confusion.

Dan

**Comment by GaofengCheng** [comment]
Solved.
