### ISSUE TITLE
--zero-if-disjoint should be --drop-frames

### ISSUE THREAD

**Issue by jasonrayles-nbcuni** [kaldi-asr/kaldi#1106]
In egs/voxforge/s5/local/run_sgmm2.sh, I think that the `--zero-if-disjoint` option should be `--drop-frames` when calling `steps/train_mmi_sgmm2.sh`

I think this option got re-renamed in commit 27219f986e89986f1dc0873dd045b6f60686e504.

**Comment by danpovey** [comment]
Thanks!  Just resolved this issue.
