### ISSUE TITLE
Training example context sizes

### ISSUE THREAD

**Issue by danpovey** [kaldi-asr/kaldi#1109]
Right now in recurrent setups in nnet3 was have an issue with the context at the edges of egs.
Suppose we use a large --extra-left-context and --extra-right-context, like 40.  Our practice is to do this even at the start/end of the file, to keep the egs all with the same structure, so compilation doesn't have to be repeated on each frame.
[...sorry, I accidentally created the issue too soon...]
But this means that when we test, we need to use the same extra-context even at the start/end of the segment, which is wasteful (when I finish nnet3 online-decoding setup, we'll be able to avoid this extra-context inside segments, at least with uni-directional LSTMs.).
My proposal is to modify the egs creation so that at the start/end of file it does not add the extra left/right context, and then to modify nnet3-merge-egs (and nnet3-chain-merge-egs) so that they batch together egs with identical structure (meaning, indexes).  
Right now nnet3*-merge-egs have a vector of egs.  They'll be modified to have a vector of vector of egs, and the code will be something like: each time we see a new eg, go to each vector and ask is it structurally the same as that first eg of that vector... if it is, then add to that vector (and write out the minibatch if we reached that size).. if it is not the same, create a new vector.
Of course, use pointers as necessary to avoid redundant copies of egs, which is expensive.

@freewym, perhaps you could work on this?  Not a huge hurry.

**Comment by danpovey** [comment]
@freewym, finished that comment, check it on github.

**Comment by freewym** [comment]
OK.
