### ISSUE TITLE
BackpropTruncationComponent

### ISSUE THREAD

**Issue by danpovey** [kaldi-asr/kaldi#1115]
This is something that we discussed in our group meeting, that @freewym is going to work on, but I want to create this issue to provide further details, to track progress, and to keep others including @vijayaditya informed.

We continue to have problems caused by the gradient explosion in backprop when using BLSTMs.  One reason is that we don't do truncated BPTT-- it's fairly hard in the nnet3 framework, but as I describe in this issue, it is possible to implement.  Since our working assumption is that when the gradients explode they do so fairly slowly, if we were to zero out the gradients every, say, 20 or 30 frames it should be enough to stop them getting large. [Consider that our normal BLSTM configurations have recurrence with a time step of 3, so there are only 10 recurrences in the span of 30 frames].

There is actually a way to zero out the gradients every certain number of frames.  It involves creating a component that is a non-simple Component (lacks flag kSimpleComponent), and that makes use of the PrecomputedIndexes functionality so it can "know about" the Cindexes that it is processing.  My current idea is that the component would also have gradient-clipping functionality, but would combine this with suitable truncation.  A typical configuration (and some aspects of this could be made the default) would be as follows:
   component type=BackpropTruncationComponent dim=1024 clipping-threshold=30.0 zeroing-threshold=2.0 zeroing-interval=30 recurrence-interval=3

The clipping-threshold would be a (2-norm-based) clipping threshold as used in ClipGradientComponent.  What the zeroing-threshold is about is as follows: if, as we cross a boundary of (some integer times zeroing-interval) frames, the norm of the gradient exceeds zeroing-threshold, then we completely zero out those gradients.  The reason we need the recurrence-interval (which should match the time-offset used in the LSTM/BLSTM) is that if it's processing, say, frame 32 and recurrence-interval is 3, then it can see that 32 - 3 < 20, so we'd be crossing that boundary of (some integer \* 30) frames.  It might be a good idea to use the 'n' index to shift where we put that boundary, so that for n=0 the boundary is at frames 0, 30, 60 and for n=1 the boundary is at frames 1, 31, 61, and so on.  That will mean that we don't always zero out gradients on frame 0, which could cause us to not learn utterance-boundary effects properly.

The PrecomputedIndexes object will probably contain a vector (maybe of floats) that somehow reflect whether or not this particular Cindex is crossing a boundary and so needs to be treated specially.  That is, some kind of vector with dimension == (num-rows we're processing), containing one of two possible values in each element.  You'll have to figure out the details.

You should definitely keep some stats so that we can find out what percentage of these gradients were clipped, normally and on the boundaries.  

What I am _hoping_ is that the self-repair that we have in ClipGradientComponent will turn out not to be necessary, because I've been having doubts about whether that was the right direction, and Yiming is anyway seeing mixed results experimentally.

A small detail specific to LSTMS:
It may not be ideal to be deciding on the zeroing for the 'c' and 'm' recurrence separately- it would be better to make a single decision for both of them.  This problem will naturally go away once the issue #1089 is implemented (@kangshiyin is going to  work on the CUDA for this), because when that is done the 'c' and 'm' will naturally be combined into one component output.  Now, at some point we will have to use a dim-range-node to break out the 'm' to do the projection (since we really implement projected LSTM i.e. LSTMP), but we can probably insert the BackpropTruncationComponent at the stage where the two are together-or just splice them back together again.  Anyway, this will most likely turn out to not even be important.

**Comment by kkm000** [comment]
Done in #1126
