### ISSUE TITLE
Document about converting arpa-lm into G.fst

### ISSUE THREAD

**Issue by sih4sing5hong5** [kaldi-asr/kaldi#1118]
The doc of [online_decoding](https://github.com/kaldi-asr/kaldi/blob/35ebbbe11235a5766e009e46b127901dada897b7/src/doc/online_decoding.dox#L356-L365), [data_prep.dox](https://github.com/kaldi-asr/kaldi/blob/85a3dd5f0b71e419abf1169a26b759bfc423a543/src/doc/data_prep.dox#L820-L828) and [format_lm.sh#L42-L44](https://github.com/kaldi-asr/kaldi/blob/master/egs/wsj/s5/utils/format_lm.sh#L42-L44) are different.
I was confused about them.
Should we use the same example?

**Comment by ognjentodic** [comment]
Also, "Preparing the grammar G" section in http://kaldi-asr.org/doc/graph_recipe_test.html is different (missing utils/s2eps.pl call).

**Comment by jtrmal** [comment]
Vassil's post is slightly outdated but still very useful for these kinds of
questions
http://vpanayotov.blogspot.com/2012/06/kaldi-decoding-graph-construction.html

**Comment by danpovey** [comment]
Those parts of the documentation that you pointed out are outdated-- the arpa2fst command was rewritten so that it does some of those extra steps.
@kkm000, do you have time to submit a PR to update the documentation?  Or does anyone else on this thread have time?

**Comment by sih4sing5hong5** [comment]
Which example is recommended?
I use the one in `online_encoding` now.
What I can do?

**Comment by danpovey** [comment]
Actually it doesn't matter I think, the tool is back compatible, but I'd
recommend the one in format_lm.sh.

**Comment by sih4sing5hong5** [comment]
I will copy the `format_lm.sh` one to others later.
```
gunzip -c $lm \
  | arpa2fst --disambig-symbol=#0 \
             --read-symbol-table=$out_dir/words.txt - $out_dir/G.fst
```

**Comment by danpovey** [comment]
ok thanks.

**Comment by sih4sing5hong5** [comment]
#1129 merged
