### ISSUE TITLE
copy-matrix critical error

### ISSUE THREAD

**Issue by danijel3** [kaldi-asr/kaldi#1119]
I have a simple example of a file that causes the matrix reading code in text mode to crash.

This is a file called test.ark:
```
test  [
  1 2 3 4 5
  1 2 3 4
  1 2 3 4 5 ]
```

It is parsed using this command:
`copy-matrix ark,t:test.ark ark:/dev/null`

This causes this error:
`*** Error in '/home/guest/kaldi/src/bin/copy-matrix': munmap_chunk(): invalid pointer: 0x0000000001027220 ***
`
(with backtrace and memory map below)

Ran it through GDB and the error is in the file kaldi-matrix.cc in line 1442

The cause of the error is obviously the uneven number of elements in each row. While most other parse errors are checked in that code, this one doesn't seem to be. The error seems to be caused by the reserve statement in line 1409.

If you ask me, the easiest way to fix this problem is to simply not add faulty lines to the data vector. If the "cur_row" doesn't have the same number of elements as the preceding line, it doesn't belong in the vector anyway...

**Comment by danpovey** [comment]
If there are lines with different numbers of elements, the matrix reading
code should crash via KALDI_ERROR.  Can you please add a check for this and
make a pull request?
Dan

**Comment by danijel3** [comment]
Sure, I'll give it a go, but I could use some hints to check if a similar error could exist in other parts of the code?

**Comment by danpovey** [comment]
I doubt there would be a similar issue anywhere else.

**Comment by danijel3** [comment]
Turned out the error was somewhat different than anticipated. It was caused by a double delete in two cases. It's fixed now...

**Comment by danpovey** [comment]
You mean it's fixed in current Kaldi code, or you'll submit a pull request?

On Sat, Oct 15, 2016 at 12:18 PM, Danijel Koržinek <notifications@github.com

**Comment by danijel3** [comment]
It's fixed in pull request #1121 referenced above.
