### ISSUE TITLE
compiling in shared mode

### ISSUE THREAD

**Issue by vince62s** [kaldi-asr/kaldi#1120]
in the middle of the make process, this pops up:

/usr/bin/ld: kaldi-lm.a(kaldi-lmtable.o): relocation R_X86_64_32 against `.rodata' can not be used when making a shared object; recompile with -fPIC
kaldi-lm.a(kaldi-lmtable.o): error adding symbols: Bad value
collect2: error: ld returned 1 exit status
make[1]: *** [libkaldi-lm.so] Error 1
make[1]: Leaving directory `/home/moses/kaldi/src/lm'
make: *** [lm] Error 2
make: *** Waiting for unfinished jobs....

**Comment by danpovey** [comment]
This happens if you configure with --shared after previously configuring
without that option.  You would need to do make clean.

**Comment by vince62s** [comment]
thanks.
