### ISSUE TITLE
Getting rid of need for alignments in iVector training

### ISSUE THREAD

**Issue by danpovey** [kaldi-asr/kaldi#1123]
@david-ryan-snyder, it continues to be a pain that we need alignments to get the LDA+MLLT transform for purposes of training speaker-id systems.
Can you see if it's possible to replace that with a PCA transform without hurting results?  Did we ever look at this?

**Comment by david-ryan-snyder** [comment]
This is for ASR speaker _adaptation_? I haven't gotten involved in that yet, so I don't know about PCA vs LDA, etc.

Have you tried using standard speaker ID features for the i-vector system? E.g., 20 mfccs + some deltas? Is it there a reason we don't do that?

**Comment by david-ryan-snyder** [comment]
And yes, I'm happy to look into this.

**Comment by danpovey** [comment]
Yes it's for adaptation.  We need it to take the same features as the nnet
is trained on, which is 40-dim MFCCs.  Anything apart from just getting the
transform a different way, will affect the runtime.  I believe there is a
binary est-pca which can be used to get the transform instead.


On Sun, Oct 16, 2016 at 6:35 PM, david-ryan-snyder <notifications@github.com

**Comment by danpovey** [comment]
BTW, you can start with tedlium s5_r2.

**Comment by david-ryan-snyder** [comment]
> Anything apart from just getting the
transform a different way, will affect the runtime.

Gotcha.

> BTW, you can start with tedlium s5_r2.

Will do.

**Comment by danpovey** [comment]
The easiest way to do it might be to add a script with the following usage:

steps/online/nnet2/get_pca_transform.sh <data-dir> <pca-dir>
  This script computes a PCA transform based on the data in <data-dir>, and
outputs it
  <pca-dir>/final.mat.  It puts the splicing options used into the file
<pca-dir>/splice_opts.
 Options:
        --dim  <pca-dim>             # default 40.  The dimension to
project to.
        --splice-opts <opts>         # default: '--left-context=3
--right-context=3'  Options to splice-feats
        --max-utts <max-num-utts>   # default: 5000.  Maximum number of
utterance to use for estimating
                                                      # the PCA transform

The output of this script would substitute for the output of
train_lda_mllt.sh




On Sun, Oct 16, 2016 at 6:42 PM, david-ryan-snyder <notifications@github.com

**Comment by david-ryan-snyder** [comment]
**LDA+MLLT (Baseline)**
```
%WER 10.5 | 507 17783 | 91.2 6.4 2.4 1.7 10.5 78.9 | 0.063 | exp/chain_cleaned/tdnn_sp_bi/decode_dev/score_10_0.0/ctm.filt.filt.sys
%WER 9.8 | 507 17783 | 91.8 6.0 2.3 1.6 9.8 77.5 | 0.022 | exp/chain_cleaned/tdnn_sp_bi/decode_dev_rescore/score_10_0.0/ctm.filt.filt.sys
%WER 9.5 | 1155 27500 | 91.6 5.9 2.4 1.1 9.5 73.2 | 0.084 | exp/chain_cleaned/tdnn_sp_bi/decode_test/score_10_0.0/ctm.filt.filt.sys
%WER 9.0 | 1155 27500 | 92.1 5.5 2.3 1.1 9.0 71.3 | 0.037 | exp/chain_cleaned/tdnn_sp_bi/decode_test_rescore/score_10_0.0/ctm.filt.filt.sys
```

**PCA _WIth_ Mean and Variance Normalization**
```
%WER 10.6 | 507 17783 | 91.2 6.4 2.4 1.7 10.6 82.4 | 0.068 | exp/chain_cleaned/tdnn_sp_bi/decode_dev/score_10_0.0/ctm.filt.filt.sys
%WER 9.9 | 507 17783 | 91.5 5.8 2.6 1.4 9.9 79.3 | 0.031 | exp/chain_cleaned/tdnn_sp_bi/decode_dev_rescore/score_10_0.5/ctm.filt.filt.sys
%WER 9.9 | 1155 27500 | 91.3 6.1 2.7 1.2 9.9 74.4 | 0.083 | exp/chain_cleaned/tdnn_sp_bi/decode_test/score_10_0.0/ctm.filt.filt.sys
%WER 9.4 | 1155 27500 | 91.7 5.7 2.6 1.2 9.4 71.9 | 0.062 | exp/chain_cleaned/tdnn_sp_bi/decode_test_rescore/score_10_0.0/ctm.filt.filt.sys
```

**PCA _Without_ Mean and Variance Normalization**
```
%WER 10.7 | 507 17783 | 91.0 6.6 2.4 1.6 10.7 80.9 | 0.089 | exp/chain_cleaned/tdnn_sp_bi/decode_dev/score_10_0.0/ctm.filt.filt.sys
%WER 10.1 | 507 17783 | 91.4 6.2 2.4 1.5 10.1 79.1 | 0.036 | exp/chain_cleaned/tdnn_sp_bi/decode_dev_rescore/score_9_0.5/ctm.filt.filt.sys
%WER 10.0 | 1155 27500 | 91.2 6.1 2.7 1.2 10.0 73.4 | 0.069 | exp/chain_cleaned/tdnn_sp_bi/decode_test/score_10_0.0/ctm.filt.filt.sys
%WER 9.4 | 1155 27500 | 91.8 5.7 2.5 1.1 9.4 71.2 | 0.044 | exp/chain_cleaned/tdnn_sp_bi/decode_test_rescore/score_10_0.0/ctm.filt.filt.sys
```

**Comment by david-ryan-snyder** [comment]
So it seems that replacing the LDA+MLLT with PCA increases WER.  The degradation is largest for the rescored test set, 9.0% -> 9.4%. Should we look into this further, or does it seem like the degradation is too much?

**Comment by danpovey** [comment]
[reposting my response since my email was lost:]
What are the objective function values from the neural net training?  Use steps/info/chain_dir_info.pl to test.
And also, look at the objf values printed in the iVector extraction logs and see if there is a big difference.

**Comment by danpovey** [comment]
What are the objective function values from the neural net training?  Use
steps/info/chain_dir_info.pl to test.
And also, look at the objf values printed in the iVector extraction logs
and see if there is a big difference.

Dan

**Comment by david-ryan-snyder** [comment]
**LDA+MLLT (Baseline)**
_Neural network training_
`num-iters=253 nj=2..12 num-params=7.0M dim=40+100->3597 combine=-0.10->-0.10 xent:train/valid[167,252,final]=(-1.35,-1.29,-1.29/-1.41,-1.38,-1.38) logprob:train/valid[167,252,final]=(-0.097,-0.085,-0.085/-0.115,-0.110,-0.109)`

_iVector extractor training_
`grep "Overall objective-function" exp/nnet3_cleaned/extractor/log/update.*
exp/nnet3_cleaned/extractor/log/update.0.log:LOG (ivector-extractor-est:Update():ivector-extractor.cc:1205) Overall objective-function improvement per frame was 132.282
exp/nnet3_cleaned/extractor/log/update.1.log:LOG (ivector-extractor-est:Update():ivector-extractor.cc:1205) Overall objective-function improvement per frame was 1.27825
exp/nnet3_cleaned/extractor/log/update.2.log:LOG (ivector-extractor-est:Update():ivector-extractor.cc:1205) Overall objective-function improvement per frame was 0.0589422
exp/nnet3_cleaned/extractor/log/update.3.log:LOG (ivector-extractor-est:Update():ivector-extractor.cc:1205) Overall objective-function improvement per frame was 0.0127591
exp/nnet3_cleaned/extractor/log/update.4.log:LOG (ivector-extractor-est:Update():ivector-extractor.cc:1205) Overall objective-function improvement per frame was 0.00487614
exp/nnet3_cleaned/extractor/log/update.5.log:LOG (ivector-extractor-est:Update():ivector-extractor.cc:1205) Overall objective-function improvement per frame was 0.00222484
exp/nnet3_cleaned/extractor/log/update.6.log:LOG (ivector-extractor-est:Update():ivector-extractor.cc:1205) Overall objective-function improvement per frame was 0.00113112
exp/nnet3_cleaned/extractor/log/update.7.log:LOG (ivector-extractor-est:Update():ivector-extractor.cc:1205) Overall objective-function improvement per frame was 0.000633291
exp/nnet3_cleaned/extractor/log/update.8.log:LOG (ivector-extractor-est:Update():ivector-extractor.cc:1205) Overall objective-function improvement per frame was 0.000388762
exp/nnet3_cleaned/extractor/log/update.9.log:LOG (ivector-extractor-est:Update():ivector-extractor.cc:1205) Overall objective-function improvement per frame was 0.000256551`

**PCA With Mean and Variance Normalization**
_Neural network training_
`num-iters=253 nj=2..12 num-params=7.0M dim=40+100->3597 combine=-0.11->-0.10 xent:train/valid[167,252,final]=(-1.38,-1.31,-1.31/-1.43,-1.40,-1.40) logprob:train/valid[167,252,final]=(-0.101,-0.088,-0.087/-0.117,-0.112,-0.110)`

_iVector extractor training_
`grep "Overall objective-function" exp/nnet3_cleaned/extractor/log/update.*
exp/nnet3_cleaned/extractor/log/update.0.log:LOG (ivector-extractor-est:Update():ivector-extractor.cc:1205) Overall objective-function improvement per frame was 98.1226
exp/nnet3_cleaned/extractor/log/update.1.log:LOG (ivector-extractor-est:Update():ivector-extractor.cc:1205) Overall objective-function improvement per frame was 1.2442
exp/nnet3_cleaned/extractor/log/update.2.log:LOG (ivector-extractor-est:Update():ivector-extractor.cc:1205) Overall objective-function improvement per frame was 0.0748216
exp/nnet3_cleaned/extractor/log/update.3.log:LOG (ivector-extractor-est:Update():ivector-extractor.cc:1205) Overall objective-function improvement per frame was 0.0195215
exp/nnet3_cleaned/extractor/log/update.4.log:LOG (ivector-extractor-est:Update():ivector-extractor.cc:1205) Overall objective-function improvement per frame was 0.00835416
exp/nnet3_cleaned/extractor/log/update.5.log:LOG (ivector-extractor-est:Update():ivector-extractor.cc:1205) Overall objective-function improvement per frame was 0.0041582
exp/nnet3_cleaned/extractor/log/update.6.log:LOG (ivector-extractor-est:Update():ivector-extractor.cc:1205) Overall objective-function improvement per frame was 0.00224828
exp/nnet3_cleaned/extractor/log/update.7.log:LOG (ivector-extractor-est:Update():ivector-extractor.cc:1205) Overall objective-function improvement per frame was 0.00130463
exp/nnet3_cleaned/extractor/log/update.8.log:LOG (ivector-extractor-est:Update():ivector-extractor.cc:1205) Overall objective-function improvement per frame was 0.000804885
exp/nnet3_cleaned/extractor/log/update.9.log:LOG (ivector-extractor-est:Update():ivector-extractor.cc:1205) Overall objective-function improvement per frame was 0.00052202`

**PCA Without Mean and Variance Normalization**
_Neural network training_
`num-iters=253 nj=2..12 num-params=7.0M dim=40+100->3597 combine=-0.11->-0.10 xent:train/valid[167,252,final]=(-1.37,-1.31,-1.30/-1.42,-1.39,-1.38) logprob:train/valid[167,252,final]=(-0.100,-0.088,-0.088/-0.116,-0.110,-0.110)`

_iVector extractor training_
`grep "Overall objective-function" exp/nnet3_cleaned/extractor/log/update.*
exp/nnet3_cleaned/extractor/log/update.0.log:LOG (ivector-extractor-est:Update():ivector-extractor.cc:1205) Overall objective-function improvement per frame was 95.7862
exp/nnet3_cleaned/extractor/log/update.1.log:LOG (ivector-extractor-est:Update():ivector-extractor.cc:1205) Overall objective-function improvement per frame was 1.41073
exp/nnet3_cleaned/extractor/log/update.2.log:LOG (ivector-extractor-est:Update():ivector-extractor.cc:1205) Overall objective-function improvement per frame was 0.0858491
exp/nnet3_cleaned/extractor/log/update.3.log:LOG (ivector-extractor-est:Update():ivector-extractor.cc:1205) Overall objective-function improvement per frame was 0.0215787
exp/nnet3_cleaned/extractor/log/update.4.log:LOG (ivector-extractor-est:Update():ivector-extractor.cc:1205) Overall objective-function improvement per frame was 0.00926884
exp/nnet3_cleaned/extractor/log/update.5.log:LOG (ivector-extractor-est:Update():ivector-extractor.cc:1205) Overall objective-function improvement per frame was 0.00451822
exp/nnet3_cleaned/extractor/log/update.6.log:LOG (ivector-extractor-est:Update():ivector-extractor.cc:1205) Overall objective-function improvement per frame was 0.00237803
exp/nnet3_cleaned/extractor/log/update.7.log:LOG (ivector-extractor-est:Update():ivector-extractor.cc:1205) Overall objective-function improvement per frame was 0.00135404
exp/nnet3_cleaned/extractor/log/update.8.log:LOG (ivector-extractor-est:Update():ivector-extractor.cc:1205) Overall objective-function improvement per frame was 0.000828248
exp/nnet3_cleaned/extractor/log/update.9.log:LOG (ivector-extractor-est:Update():ivector-extractor.cc:1205) Overall objective-function improvement per frame was 0.00053721`

**Comment by danpovey** [comment]
It's close to the boundary of where I'd say it's noise, vs. saying that
it's clearly worse.
Could you please try it on another setup?
Dan


On Tue, Oct 25, 2016 at 2:52 PM, david-ryan-snyder <notifications@github.com

**Comment by david-ryan-snyder** [comment]
Sure!

**Comment by david-ryan-snyder** [comment]
I also tried this on AMI and it seems to be the same or _slightly_ worse. On the eval it's worse by just 0.1% absolute. 

**Original**
_Neural Network Training_
`steps/info/chain_dir_info.pl exp/ihm/chain_cleaned/tdnn_sp_bi/
exp/ihm/chain_cleaned/tdnn_sp_bi/: num-iters=89 nj=2..12 num-params=7.1M dim=40+100->3768 combine=-0.11->-0.10 xent:train/valid[58,88,final]=(-1.44,-1.32,-1.33/-1.66,-1.58,-1.59) logprob:train/valid[58,88,final]=(-0.097,-0.082,-0.081/-0.132,-0.130,-0.129)
`

_WER_
```
%WER 22.4 | 13098 94489 | 80.6 11.1 8.3 3.0 22.4 55.1 | 0.067 | exp/ihm/chain_cleaned/tdnn_sp_bi/decode_dev/ascore_10/dev_hires.ctm.filt.sys
%WER 22.7 | 12643 89970 | 80.1 12.7 7.2 2.8 22.7 53.0 | 0.141 | exp/ihm/chain_cleaned/tdnn_sp_bi/decode_eval/ascore_10/eval_hires.ctm.filt.sys
```

**PCA With Mean and Variance Normalization**
_Neural Network Training_
`exp/ihm/chain_cleaned/tdnn_sp_bi/: num-iters=89 nj=2..12 num-params=7.1M dim=40+100->3768 combine=-0.11->-0.10 xent:train/valid[58,88,final]=(-1.46,-1.34,-1.34/-1.67,-1.59,-1.60) logprob:train/valid[58,88,final]=(-0.100,-0.084,-0.082/-0.131,-0.128,-0.126)`

_WER iter=89 (final)_
```
%WER 22.3 | 13098 94480 | 80.7 11.0 8.2 3.0 22.3 54.7 | 0.082 | exp/ihm/chain_cleaned/tdnn_sp_bi/decode_dev/ascore_10/dev_hires.ctm.filt.sys
%WER 22.8 | 12643 89975 | 80.0 12.8 7.2 2.8 22.8 53.0 | 0.151 | exp/ihm/chain_cleaned/tdnn_sp_bi/decode_eval/ascore_10/eval_hires.ctm.filt.sys
```

_WER iter=70_
```
%WER 22.4 | 13098 94468 | 80.6 11.0 8.4 3.0 22.4 55.0 | 0.095 | exp/ihm/chain_cleaned/tdnn_sp_bi/decode_dev/ascore_10/dev_hires.ctm.filt.sys
%WER 22.8 | 12643 89972 | 79.9 12.9 7.2 2.7 22.8 53.2 | 0.153 | exp/ihm/chain_cleaned/tdnn_sp_bi/decode_eval/ascore_10/eval_hires.ctm.filt.sys

```
_WER iter=60_
```
%WER 22.8 | 13098 94466 | 80.1 10.9 9.0 3.0 22.8 55.5 | 0.110 | exp/ihm/chain_cleaned/tdnn_sp_bi/decode_dev/ascore_10/dev_hires.ctm.filt.sys
%WER 23.2 | 12643 89967 | 79.5 12.7 7.8 2.7 23.2 53.7 | 0.173 | exp/ihm/chain_cleaned/tdnn_sp_bi/decode_eval/ascore_10/eval_hires.ctm.filt.sys
```

**Comment by danpovey** [comment]
Seems basically the same there: 9 word errors better on dev, 5 worse on
eval.

Sorry, can you try on another setup?  Right now we're in a situation where
we don't have evidence that it's worse, but can't be sure that it's
(normally) the same.


On Mon, Oct 31, 2016 at 7:14 PM, david-ryan-snyder <notifications@github.com

**Comment by david-ryan-snyder** [comment]
> Sorry, can you try on another setup? 

Sure! I can run 2 more setups so we have enough info.

**Comment by vince62s** [comment]
might sound silly but, to materialize whether this is noise or not, wouldn't it be quicker if we run a few times the same setup ?

**Comment by danpovey** [comment]
My intuition is that there are different types of noise, and you get rid of
only some of them by re-running the same setup.  So running a new setup
gives you more independent and more valuable information.

**Comment by david-ryan-snyder** [comment]
@danpovey I also reran current Tedlium recipe. This is the cleaned version without @vince62s's LM changes. Left column results are LDA and right column are PCA.

WER 10.6 vs 10.5 dev
WER 10.0 vs 10.0 dev rescore
WER 9.7 vs 9.9 test
WER 9.3 vs 9.5  test rescore

Average LDA results are 9.90%, PCA is 9.98%

**Comment by danpovey** [comment]
Interesting.  So this increases the likelihood that in general it's as good
as LDA+MLLT, but the results on other setups were negative enough that I
think it still makes sense to do one more test before we change all the
recipes over... sorry.  One possibility is to wait till @naxingyu has got
an nnet3 setup on gale_mandarin (which he's doing on our cluster), and then
do it on that setup.

Dan


On Fri, Nov 25, 2016 at 7:11 PM, david-ryan-snyder <notifications@github.com

**Comment by david-ryan-snyder** [comment]
Sure. I can also run it on @naxingyu recipe.

Can you suggest another recipe to try this on, besides Tedlium and AMI (which we did already)?

**Comment by danpovey** [comment]
You could try WSJ.

On Fri, Nov 25, 2016 at 7:45 PM, david-ryan-snyder <notifications@github.com

**Comment by david-ryan-snyder** [comment]
OK sounds good.

**Comment by david-ryan-snyder** [comment]
Hi @Dan,

Here are the results for WSJ, using the TDNN recipe.

LDA
eval92 %WER 6.68 [ 377 / 5643, 86 ins, 24 del, 267 sub ]
dev93 %WER 9.62 [ 792 / 8234, 147 ins, 99 del, 546 sub ]
eval92 %WER 3.97 [ 224 / 5643, 23 ins, 20 del, 181 sub ]
dev93 %WER 7.02 [ 578 / 8234, 59 ins, 86 del, 433 sub ]

PCA
eval92 %WER 6.38 [ 360 / 5643, 78 ins, 25 del, 257 sub ]
dev93 %WER 9.55 [ 786 / 8234, 161 ins, 74 del, 551 sub ]
eval92 %WER 3.81 [ 215 / 5643, 24 ins, 21 del, 170 sub ]
dev93 %WER 6.89 [ 567 / 8234, 51 ins, 91 del, 425 sub ]

As you can see, PCA looks a little better. Which seems to further indicate that replacing LDA with PCA in the i-vector pipeline doesn't hurt WER. 

This is what I propose (so I don't drag this on indefinitely): I'll prepare a PR with the new option for using PCA, and add in the ASR results that I have now. Then, it should be possible for you to look at the PR and decide what other results we need before pushing it.

**Comment by danpovey** [comment]
Cool, makes sense.
If it's just an option in the script, we can gradually modify the recipes
to use PCA instead of LDA, while we're making other changes.

**Comment by david-ryan-snyder** [comment]
OK, I will put it all in a PR soon so you can make that call.

**Comment by david-ryan-snyder** [comment]
@danpovey, @jtrmal, You might want to close this issue, as the scripts are there (as of #1514) to replace LDA+MLLT with PCA. However, not all of the existing recipes have been switched over, so you might decide to keep this open for visibility.

**Comment by kkm000** [comment]
Done #1514
