### ISSUE TITLE
Change how descriptors behave in nnet3

### ISSUE THREAD

**Issue by danpovey** [kaldi-asr/kaldi#1125]
This is something that I discussed with Vijay but that he probably doesn't have time for, and would be suitable for someone who wants to get more familiar with nnet3 at the code level.
We found that the way certain types of ForwardingDescriptor interact is a bit unintuitive.  Specifically, if you do something like
 Offset(Round(some_node, 10), 3)
you'll get the input from some_node at indexes 13, 23 and so on... whereas what we felt was more intuitive is that it's as if you evaluated the Round() expression when offsetting the t index first by 3, so it's still multiples of 10 but evaluated at an offset.  The way we want to make it, it has the nice property that if you were to make  an actual node with the internal expression (Round...) and use that node inside the outer expression, it's would give the same result as what the descriptors will give.
It doesn't change the language that you can express, I believe, it just affects the order in which you have to write the expressions.

I believe we don't have anything in the example scripts right now that would be affected by this change.

Anyway, the actual code change is quite simple.
In the various instances of ForwardingDescriptor, the code looks something like:
- Recurse
- Make some change to the indexes

The way it needs to be changed, it would look like:
- Make some change to the indexes
- Recurse.
  So it's not really that hard.
  Just be aware that the return type of the recursion is Cindex, which contains a node-id and and Index, whereas the argument of the recursion is Index, which is just a 3-tuple (n, t, x).  But this is not a problem, instead of changing the .second of the Cindex after the recursion, you just change the Index in the same way before the recursion.

**Comment by danpovey** [comment]
@GaofengCheng, you could do this if you have time.

**Comment by GaofengCheng** [comment]
@danpovey  I will begin this after I finish the chain dropout (b)lstm code (today will be ok)

**Comment by danpovey** [comment]
@GaofengCheng, don't bother with this.  I'm doing it myself as part of some more extensive changes to the nnet3 setup (faster compilation and support for multiple chunk sizes and different context length at utterance boundaries).  We don't need this separate issue any more so I'm closing it.
@vijayaditya, your [non-public] experiments are the only ones this is likely to affect.

**Comment by vijayaditya** [comment]
OK I have resorted to using noopcomponents to avoid these issues, so this
is not a high priority requirement for me too.
