### ISSUE TITLE
Spatial regularization component

### ISSUE THREAD

**Issue by danpovey** [kaldi-asr/kaldi#1128]
Some of you will have seen the Microsoft ArXiv paper, in which they report better-than-human performance on Switchboard.
https://arxiv.org/pdf/1610.05256v1.pdf
The new aspect of their work which is easiest to directly use in our system is their idea of "spatial regularization".  
This is something that happens on the output of hidden layers (e.g. affine layers or BLSTM layers).
The output of the layers is viewed [arbitrarily] as a two-dimensional grid, for instance a BLSTM layer with an output dimension of 512 could be viewed as a 16 \* 32 grid.
A penalty term is added to the objective function, that penalizes a particular activation being different from the average of the adjacent activations.  The way this is implemented in practice is that the output is convolved with a 3 x 3 kernel where the center pixel is 1 and all the other pixels have a value of -1/8, and some constant times the sum-squared of the result is added to the objective function [and obviously we backprop from there.]  The convolution is "circular", meaning that at the edges of the image we wrap around to the opposite edge of the image.

I propose to implement this as SpatialRegularizationComponent-- a component that will just copy its input in the forward pass (like ClipGradientComponent), but in the backward pass will add something the derivative.  We won't be able to add the objf term to the overall objective function, as this is now how the framework works, but this doesn't matter, as what's important is the derivative-- stats can be stored in the component from which we can get the objf via the Info() string if we really want to.

We'll need GPU and CPU versions of the computation.  Obviously the GPU one is the more important for speed, given that that's how we always train.  I don't want to assume that the dimensions of the activations are easy to factor.  For this and other reasons, I would like to implement this circular convolution on a fixed dimension, of size 256, and I'd like the thread-blocks to have dimension 16 \* 16 = 256.  The circular convolution will operate separately on 256-dimensional blocks of the layer activations, wrapping around the edges of these blocks (and it should behave as if padded with zeros for uneven-size blocks, although the code shouldn't assume that the memory is physically padded with zeros).  Remember not to use the macros CU1DBLOCK and CU2DBLOCK in the GPU code, as this would affect the behavior of the code-- just hardcode it as 16 \* 16 blocks.  In the kernel, the code will be quite trivial- no logarithmic reduction- but will need __syncthreads().

I want the backprop to be in-place, meaning that the in_deriv and out_deriv can share memory.  Note: unlike most backprop operations, the kernel won't be doing anything interesting with the out_deriv, it will just be adding to it (and the thing it adds to it is only a function of the activations, not of the out_deriv).

The derivative can be computed by a function like the following (note: the
backprop of the component pretty much just has to call this function).

// quick notes: requires SameDim(*this, value).
// 'scale' is scale on the term that's added to the deriv.
// need more documentation.
void CuMatrixBase<BaseFloat>::AddSpatialRegularizationDeriv(
  const CuMatrixBase<BaseFloat> &value, BaseFloat scale);

Computing the regularization value (i.e. the term that gets added to the objective
function) is actually harder (on GPU) than computing the derivative, because it requires a logarithmic reduction.  Rather than computing the regularization term every time we do the backprop, we can do it, say 1/4 of the time randomly, so the stats will be sampled.  (we probably won't even look at the stats very often, and they'll only be used for diagnostic reasons).
It can be done by a function with signature like:
 BaseFloat CuMatrixBase<BaseFloat>::ComputeSpatialRegularizationValue() const;
That function can create a temporary a CuVector of dimension NumRows() \* ((NumCols()+255)/256), and each thread block (operating on a 256-dimensional block of columns of one row of the matrix) will write to one element of the CuVector, then you can just use CuVectorBase::Sum() to compute the sum.  This means that the only logarithmic reduction that the kernel needs, is the reduction within the thread block.

I'm not sure who to ask to do this.  I think @kangshiyin  (who could do the GPU coding) and @freewym  (who could make the component) are pretty busy, and so are most of the other people who might normally do this.

**Comment by danpovey** [comment]
Actually, @kangshiyin, if you haven't started on the other thing (the new LSTM version) yet, you could do the GPU parts of this one instead-- it would improve our systems faster.

**Comment by kangshiyin** [comment]
OK, I'm now @ISCSLP, where Microsoft announced their paper. I will be back at the week end and start working on this.
