### ISSUE TITLE
swbd local/remove_dup_utts.sh is lost

### ISSUE THREAD

**Issue by GaofengCheng** [kaldi-asr/kaldi#1133]
Line 96 in /local/nnet3/run_ivector_commen.sh still calls for local/remove_dup_utts.sh , but file doesn't exist. I wonder whether the remove dup process is still needed ?  I will commit a update later.

**Comment by danpovey** [comment]
I responded to this by email but github did not post it.  Posting it manually.

That script was moved to utils/data/remove_dup_utts.sh.  Please make a PR to call it in the proper location.

**Comment by danpovey** [comment]
.. I mean to call it in the location utils/data/remove_dup_utts.sh

**Comment by danpovey** [comment]
That script was moved to utils/data/remove_dup_utts.sh.  Please make a PR
to have it in the proper location.
