### ISSUE TITLE
cu-device / SelectGpuIdAuto

### ISSUE THREAD

**Issue by vince62s** [kaldi-asr/kaldi#1134]
This refers to a question raised on forum.

When using GPU in exclusive mode, it runs only one job per GPU. On recent boards, it a pity since we can use better the power by running 2 or 3 jobs on them.

When running GPU in non-exclusive mode, the selection is done on "free memory ratio".
The only problem is that if you launch 4 jobs at the same time, they have not started to actually use the memory, hence the selection could lead to pick the same GPU, (which is my case because one GPU is having some overhead memory for display I guess).

A better way could be to have either a mechanism to allocate a certain number of jobs for a given gpu, or to be able to "reserve" a memory chunk per job (say 2GB) which would lead the selection mechanism to select the following board.

**Comment by lifeiteng** [comment]
Training, `one job per GPU` is faster than `multi job per GPU`, because `job switching on GPU` will cost some time, similar to `CPU context switching`.

Decoding, when num_jobs are much larger than GPU devices, my stage is ` echo "password" | sudo -S nvidia-smi -c 0`, modify `decode.sh` to balance GPU usage.
```
for n in $(seq $num_jobs);do
     $cmd JOB=$n:$n $dir/log/decode.JOB.log ... latgen-faster  --use-gpu=yes ...（modify the decoding program to support GPU configure） || exit 1 &
     sleep 5
done
wait
```

**Comment by danpovey** [comment]
The reason we don't recommend using non-exclusive mode is that it generally just degrades performance, as @lifeiteng said.  Closing the issue.
