### ISSUE TITLE
what happen (on the process of decoding, on the TIMIT)?

### ISSUE THREAD

**Issue by baylor369** [kaldi-asr/kaldi#1138]
Use of uninitialized value within %phonemap in concatenation (.) or string at local/decodetimit_norm_trans.pl line 86, <T> line 195.
Use of uninitialized value within %phonemap in concatenation (.) or string at local/decodetimit_norm_trans.pl line 86, <T> line 195.
Use of uninitialized value within %phonemap in concatenation (.) or string at local/decodetimit_norm_trans.pl line 86, <T> line 195.
Use of uninitialized value within %phonemap in concatenation (.) or string at local/decodetimit_norm_trans.pl line 86, <T> line 195.

**Comment by danpovey** [comment]
[reposting since my email was lost.]
Does anyone want to look into this?
I am sticking to my policy of not getting involved in TIMIT-related issues.

**Comment by danpovey** [comment]
Does anyone want to look into this?
I am sticking to my policy of not getting involved in TIMIT-related issues.

**Comment by naxingyu** [comment]
There is no such script in the timit recipe.
