### ISSUE TITLE
Is Fisher transcripts really optional for AMI exp?

### ISSUE THREAD

**Issue by tuming1990** [kaldi-asr/kaldi#1139]
I tried to run run_prepare_shared.sh. According to
```bash
# Path to Fisher transcripts LM interpolation (if not defined only AMI transcript LM is built),
```
I left definition of FISHER_TRANS commented. 
But
```bash
local/ami_train_lms.sh --fisher $FISHER_TRANS data/local/annotations/train.txt data/local/annotations/dev.txt data/local/dict/lexicon.txt data/local/lm
```
can't be excuted, saying that  
```bash
run_prepare_shared.sh: line 43: FISHER_TRANS: unbound variable
```

Then I defined FISHER_TRANS just as $PWD. The code just exited since in ami_train_lms.sh it needs fisher transcription to be provided.

So, how can I run the script without fisher transcription?

Thanks,
Ming

**Comment by alumae** [comment]
Just remove the ` --fisher $FISHER_TRANS` switch:

    local/ami_train_lms.sh data/local/annotations/train.txt data/local/annotations/dev.txt data/local/dict/lexicon.txt data/local/lm

**Comment by danpovey** [comment]
Resolved in commit c4c08c4

**Comment by tuming1990** [comment]
Thanks for making it clearer!

**Comment by FahadMaqbool** [comment]
Hi, Kindly reply.
If I just want to run AMI's Script without changing it. i.e. I want to use fisher data. How should I get it and How can I change the run script accordingly. specially this case statement. 
case $(hostname -d) in
  fit.vutbr.cz) FISHER_TRANS=/mnt/matylda2/data/FISHER/fe_03_p1_tran ;; # BUT,
  clsp.jhu.edu) FISHER_TRANS=/export/corpora4/ami/fisher_trans/part1 ;; # JHU,
  cstr.ed.ac.uk) FISHER_TRANS=`pwd`/eddie_data/lm/data/fisher/part1 ;; # Edinburgh,
 *) echo "Please modify the script to add your loaction of the Fisher transcripts, or modify this script."; exit 1;;
esac

**Comment by danpovey** [comment]
you can remove that case statement and just add
FISHER_TRANS=/foo/bar
where /foo/bar is the location on  your system.

**Comment by FahadMaqbool** [comment]
Thanks can you please elaborate then how to change run.sh accordingly if we don't use fisher data.

**Comment by danpovey** [comment]
It already says, in run_prepare_shared.sh right below where that variable
is set:

# Note: if you don't have the Fisher data, you can remove the --fisher
$FISHER_TRANS
# option to local/ami_train_lms.sh below, and remove the case statement
above.
