### ISSUE TITLE
Improve exception safety with smart pointers

### ISSUE THREAD

**Issue by elfring** [kaldi-asr/kaldi#1140]
Would you like to wrap any pointer data members with the template class "[std::unique_ptr](https://en.wikipedia.org/wiki/Smart_pointer#unique_ptr "a smart pointer")"?

Update candidates:
* [EigenvalueDecomposition](https://github.com/kaldi-asr/kaldi/blob/85a3dd5f0b71e419abf1169a26b759bfc423a543/src/matrix/jama-eig.h#L875 "EigenvalueDecomposition class")
* [OnlineSpeexDecoder::Decode](https://github.com/kaldi-asr/kaldi/blob/85a3dd5f0b71e419abf1169a26b759bfc423a543/src/online2/online-speex-wrapper.cc#L210 "OnlineSpeexDecoder::Decode function")
* [OnlineTcpVectorSource](https://github.com/kaldi-asr/kaldi/blob/85a3dd5f0b71e419abf1169a26b759bfc423a543/src/online/online-tcp-source.cc#L29 "OnlineTcpVectorSource class")

**Comment by jtrmal** [comment]
std::unique_ptr is C++11 -- we still support older C++
There is no existing benefit to add this to existing (debugged) code, I
think.
y.

**Comment by elfring** [comment]
Do you care if the corresponding destructors will be appropriately called if [an exception like "`std::bad_alloc`"](http://en.cppreference.com/w/cpp/memory/new/bad_alloc "Description for std::bad_alloc") would be thrown during object construction?

**Comment by danpovey** [comment]
[posting again because github may still be losing my emails],
Not really, because std::bad_alloc would be fatal to all existing Kaldi programs.

**Comment by danpovey** [comment]
Not really, because std::bad_alloc would be fatal to all existing Kaldi
programs.

**Comment by elfring** [comment]
Will any software adjustments [become more interesting for this issue](https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#r11-avoid-calling-new-and-delete-explicitly "C++ guideline “R.11: Avoid calling new and delete explicitly”")?

**Comment by danpovey** [comment]
We have been gradually replacing things with smart pointers.  But it's not
an urgent priority as (1) it may cause crashes and branch conflicts with
users,
and (2) there isn't any clear benefit to the user.

**Comment by elfring** [comment]
>… there isn't any clear benefit to the user.

Does [the C++ guideline “R.11: Avoid calling new and delete explicitly”](https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#r11-avoid-calling-new-and-delete-explicitly "Recommendations around allocation and deallocation") provide helpful information for such a view?

**Comment by jtrmal** [comment]
I think Dan's point was that changing existing code base (that does not
contain new/delete bugs)  does not bring any benefit for users (can only
introduce new bugs).
For new code, it's different, but that we already do, I believe.
y.

**Comment by elfring** [comment]
I propose to reduce exception-unsafe code further for C++ software components.
