### ISSUE TITLE
Should split_data.sh need utils ?

### ISSUE THREAD

**Issue by sih4sing5hong5** [kaldi-asr/kaldi#1148]
Like [steps/align_si.sh](https://github.com/kaldi-asr/kaldi/blob/85a3dd5f0b71e419abf1169a26b759bfc423a543/egs/wsj/s5/steps/align_si.sh#L62)
```
[[ -d $sdata && $data/feats.scp -ot $sdata ]] || split_data.sh $data $nj || exit 1;
```
Why it isn't `utils/split_data.sh`?
```
[[ -d $sdata && $data/feats.scp -ot $sdata ]] || utils/split_data.sh $data $nj || exit 1;
```

I searched and found many many scripts use `split_data.sh` directly.
Are they bugs?

**Comment by danpovey** [comment]
[posting directly as there is a delay for emails to github]
utils is always added to the path so it's not exactly a bug.  But we do prefer using the full path to the script.

**Comment by sih4sing5hong5** [comment]
Ok

**Comment by danpovey** [comment]
utils is always added to the path so it's not exactly a bug.  But we do
prefer using the full path to the script.
