### ISSUE TITLE
duplicated make_one_biased_lm.py

### ISSUE THREAD

**Issue by sih4sing5hong5** [kaldi-asr/kaldi#1152]
```
steps/cleanup/internal/make_one_biased_lm.py
steps/cleanup/make_one_biased_lm.py
```
None is used in `egs/`.
Their code are the same but their comments are different.

Wrong filenames in messages of other files:
https://github.com/kaldi-asr/kaldi/search?utf8=✓&q=make_one_biased_lm&type=Code

**Comment by danpovey** [comment]
Thanks- please fix this in the same PR, #1151

**Comment by sih4sing5hong5** [comment]
```
├── internal
│   ├── get_ctm_edits.py
│   ├── get_non_scored_words.py
│   ├── make_one_biased_lm.py
│   ├── modify_ctm_edits.py
│   ├── segment_ctm_edits.py
│   └── taint_ctm_edits.py
├── lattice_oracle_align.sh
├── make_biased_lm_graphs.sh
├── make_biased_lms.py
├── make_one_biased_lm.py
```
Which one should be removed? `internal` one?

**Comment by danpovey** [comment]
No, keep the one in internal/.
Obviously make sure it's called in the correct location, and make sure
there are no code differences.
I'll wait a little before merging, so you can rerun the setup and verify
that it still works.

**Comment by sih4sing5hong5** [comment]
I found no scripts that uses the `make_one_biased_lm.py`.

**Comment by danpovey** [comment]
It's called from another python script
