### ISSUE TITLE
lattice-align-words-lexicon | nbest-to-ctm

### ISSUE THREAD

**Issue by danpovey** [kaldi-asr/kaldi#1155]
This occurs in a bunch of script including scoring scripts.
Whenever we directly pipe the output of lattice-align-words-lexicon into nbest-to-ctm, we need to put the command
  lattice-1best ark:- ark:-
between them, because even for linear lattices, lattice-align-words-lexicon can in certain cases produce non-linear outputs (due to disambiguity in the lexicon).

@sih4sing5hong5, you could do this if you have time.

**Comment by sih4sing5hong5** [comment]
Does `lattice-align-words` produce non-linear outputs as `lattice-align-words-lexicon`?
 
Some scripts pipe the `lattice-1best` before `lattice-align-words`.
Like https://github.com/kaldi-asr/kaldi/blob/85a3dd5f0b71e419abf1169a26b759bfc423a543/egs/swbd/s5c/local/score_sclite.sh#L60-L62
Should I modify `lattice-1best | lattice-align-words | nbest-to-ctm` to `lattice-1best | lattice-align-words | lattice-1best | nbest-to-ctm`?

**Comment by danpovey** [comment]
No, lattice-align-words doesn't do that.   Only lattice-align-words-lexicon.

**Comment by sih4sing5hong5** [comment]
There are 3 `lattice-align-words-lexicon | nbest-to-ctm`.
Only 2 of them we need put.
```
$ find . -name '*.sh' -exec grep nbest-to-ctm {} -HB 10 \; | grep lattice-align-words-lexicon -A 2
./egs/wsj/s5/steps/cleanup/lattice_oracle_align.sh-      lattice-align-words-lexicon $lang/phones/align_lexicon.int $model  "ark:gunzip -c $dir/lat.JOB.gz|" ark:- \| \
./egs/wsj/s5/steps/cleanup/lattice_oracle_align.sh-      lattice-1best ark:- ark:- \| \
./egs/wsj/s5/steps/cleanup/lattice_oracle_align.sh:      nbest-to-ctm --frame-shift=$frame_shift --print-silence=$print_silence ark:- - \| \
--
./egs/wsj/s5/steps/get_ctm.sh-      lattice-align-words-lexicon $lang/phones/align_lexicon.int $model ark:- ark:- \| \
./egs/wsj/s5/steps/get_ctm.sh:      nbest-to-ctm --frame-shift=$frame_shift --print-silence=$print_silence ark:- - \| \
./egs/wsj/s5/steps/get_train_ctm.sh-
--
./egs/wsj/s5/steps/get_train_ctm.sh-      lattice-align-words-lexicon $lang/phones/align_lexicon.int $model ark:- ark:- \| \
./egs/wsj/s5/steps/get_train_ctm.sh:      nbest-to-ctm --frame-shift=$frame_shift --print-silence=$print_silence ark:- - \| \
```

**Comment by danpovey** [comment]
OK.
Make sure you check whether this occurs in any scripts in local directories
of egs.
Dan

**Comment by sih4sing5hong5** [comment]
Other scripts pipe to `lattice-to-ctm-conf` after `lattice-align-words-lexicon`.

**Comment by danpovey** [comment]
You don't have to worry about those cases because lattice-to-ctm-conf
expects nonlinear input.
