### ISSUE TITLE
Issues with context calculation in nnet3 models when using Round descriptors.

### ISSUE THREAD

**Issue by vijayaditya** [kaldi-asr/kaldi#1175]
We right now compute the context in the python scripts just by counting the splice-indexes. However when using the Round descriptors this computation can be wrong, as the round descriptors would round down the time index values.

Rather than re-implementing the logic for context calculation in the python code the config generator script can create the final model (using the layer-wise configs) and extract the values from the nnet3-am-info binary. 

(I am working on this)

**Comment by danpovey** [comment]
Vijay, my proposal for the xconfig pipeline for config generation has
this... not sure if that is what you are working on.  But no harm in fixing
the old setup too.

**Comment by vijayaditya** [comment]
OK.. then I will go through the xconfig PR before I work on this.
