### ISSUE TITLE
Kaldi cannot be installed (for now) if you have OpenFst

### ISSUE THREAD

**Issue by hajix** [kaldi-asr/kaldi#1180]
Hi

I run `extras/check_dependencies.sh` and it tells me:

> aj@aj-pc:~/Downloads/kaldi-master/tools$ extras/check_dependencies.sh
extras/check_dependencies.sh: python 2.7 is not the default python. You should either make it
extras/check_dependencies.sh: default or create an bash alias for kaldi scripts to run correctly
*** extras/check_dependencies.sh: Kaldi cannot be installed (for now) if you have OpenFst
***   installed in system space (version mismatches, etc.)
***   Please try to uninstall it.

after that, ehwn I need to make the tools, I encountered an error:

> aj@aj-pc:~/Downloads/kaldi-master/tools$ make
extras/check_dependencies.sh
extras/check_dependencies.sh: python 2.7 is not the default python. You should either make it
extras/check_dependencies.sh: default or create an bash alias for kaldi scripts to run correctly
*** extras/check_dependencies.sh: Kaldi cannot be installed (for now) if you have OpenFst
***   installed in system space (version mismatches, etc.)
***   Please try to uninstall it.
make: *** [check_required_programs] Error 1

what should I do to solve the problem?

**Comment by danpovey** [comment]
Maybe start by reading the message carefully.  Closing the issue.

**Comment by aevernon** [comment]
You need to install Python 2.7 and ensure that it is being invoked when you run the `python` command.

Reply to this comment with the output of `cat /etc/os-release`.

**Comment by aevernon** [comment]
Try this command to install Python 2.7:

```bash
apt-get update
apt-get install python2.7
```

The second message says you need to uninstall OpenFst. You will probably have to perform that task manually.

**Comment by hajix** [comment]
I already have python2.7, and it is pre-installed on ubuntu and is the default version. It seems that uninstalling OpenFst will solve the issue, but I don't know how to unistall it manually. I issued  `make && sudo make install` in the openFst folder.

`sudo make unistall` should work...

**Comment by aevernon** [comment]
That is correct: you don't need to `make install` OpenFst. You just compile it with `make`, and Kaldi will automatically link OpenFst when you compile Kaldi.

 `sudo make uninstall` seems reasonable.

**Comment by hajix** [comment]
ooops. The problem is that I removed openfst-1.4.3 folder, where I issued `sudo make install` command, and I don't know where to issue `sudo make uninstall` to remove openFst!!

**Comment by danpovey** [comment]
Probably remove the files in /usr/bin/fst* or something like that.
Please do not respond any more on github, it is for Kaldi development, not
for newbie installation questions.
The forums described at kaldi-asr.org/forums.html can be used for newbie
questions, but in your case your questions are extremely basic and only
tangentially Kaldi-related, so it would be better to find someone local who
can answer them.

**Comment by hajix** [comment]
The issue was solved by downloading openFst that I was making manually, and issue make clean in the openfst-1.3.4 folder.
thank for all answers
