### ISSUE TITLE
prior in lfmmi

### ISSUE THREAD

**Issue by RookieSupery2** [kaldi-asr/kaldi#1185]
when we train lf-mmi using chain, it seems no procedure for adding prior into the nnet3 model in scripts;
but it's common to use the prior in nnet1 training scripts. so we are curious about:
1) should we use option "adjust-prior" to add specific prior for lf-mmi trained model?
2) to make comparison more fair, should we delete the prior in nnet1 for lstm-hmm model?

**Comment by danpovey** [comment]
>
>    1.
>    should we use option "adjust-prior" to add specific prior for lf-mmi
>    trained model?
>
>
No.  The LF-MMI/chain setup is designed in such a way that it doesn't need
a prior term.


>
>    1. to make comparison more fair, should we delete the prior in nnet1
>    for lstm-hmm model?
>
>
No.

**Comment by RookieSupery2** [comment]
But now, I can't find the way why it doesn't  need a prior term in LF-MMI/chain setup.

**Comment by danpovey** [comment]
The model was built not to need it.  Check my publications page and read the paper.
Anyway github is not for these kinds of discussions.  See kaldi-asr.org/forums.html.
