### ISSUE TITLE
Chain,nnet3 : --chunk-{left,right}-context not honored when reusing egs

### ISSUE THREAD

**Issue by vijayaditya** [kaldi-asr/kaldi#1190]
When using `--egs.dir` option the current chain recipe does not ensure that the {left,right}-context being used for training is same as the one used specified in `--egs.chunk-{left,right}-context`. This is because `nnet3-chain-copy-egs` did not have `--{left,right}-context` options when the script was written. However @GaofengCheng recently added support for this in 93f2f65 . So this option has to be supported even in the scripts.

**Comment by vijayaditya** [comment]
The context options were also not being passed on to the ComputeCvProbabilities methods even in the normal frame level training scripts.

@vimalmanohar Check if there are similar issues in the sMBR training scripts.

**Comment by vijayaditya** [comment]
Same issue with the get_post.combined.* jobs which are used for computing the average posterior. 

BTW I want to add that these bugs would not be a issue unless you were training RNN AMs and using egs from a different experiment which has egs with different contexts.

**Comment by vijayaditya** [comment]
I am pushing a PR correcting this in a few minutes.

**Comment by vince62s** [comment]
do you recall this ?
https://groups.google.com/forum/#!searchin/kaldi-help/egs%7Csort:relevance/kaldi-help/udYrYTEDycU/JuodilwSAAAJ

I am not sure to get exactly what the issue would be.

**Comment by vijayaditya** [comment]
The nnet3 compiler decides the unfolding width of RNNs based on the left and right context available. So providing more context than specified means that your RNN history vector is not exactly what you wanted it to be. This can lead to context mismatch errors between training and decoding; and finally affect the performance. 

In our experimentation we found that the RNN performance is usually sensitive to the amount of context available, at least up to a certain context-width.

**Comment by vijayaditya** [comment]
Addressed in #1194
