### ISSUE TITLE
Support left-context and right-context in nnet3-discrimnative-copy-egs

### ISSUE THREAD

**Issue by vimalmanohar** [kaldi-asr/kaldi#1193]
support --left-context and --right-context options in nnet3-discriminative-copy-egs similar to nnet3-chain-copy-egs #1190

**Comment by danpovey** [comment]
Vimal, I don't see a compelling reason to do this.  Normally people will have used a certain left/right context in their base model and they'll just use the same one in the discriminative one when dumping egs.  There's no reason you'd use any other value.  So I don't see any reason to support changing it on the fly, it would just be added code.
