### ISSUE TITLE
 Shifting of chain egs happens before copy-egs so there can be insufficient context errors

### ISSUE THREAD

**Issue by vijayaditya** [kaldi-asr/kaldi#1203]
In ac1f932 , shifting of chain-egs happens before copy-egs call. The python training script has to be modified to request egs with contexts which account for this.

**Comment by danpovey** [comment]
Can you explain what the issue is in more detail?
You understand why I changed it, right?

**Comment by vijayaditya** [comment]
Sorry one of my setups broke and I thought this was the issue. However the setup was previously working as the copy preceded the shift, while it shouldn't have actually worked due to insufficient context.
