### ISSUE TITLE
The upgrade to C++11

### ISSUE THREAD

**Issue by danpovey** [kaldi-asr/kaldi#1234]
This is an issue for discussion.
Should we allow the use of C++11 features in Kaldi?  It seems like C++11 is old enough now that complier support should be universal.
The most obvious benefit is that we could use C++11 threads, which are easier to use than pthreads, and would make it easier to support Visual Studio (assuming their support for C++11 works OK).
I'm not saying we'd necessarily go all-in on things like "auto" and lambdas.
Also this change would make it more straightforward to keep up-to-date with the latest OpenFst.  It might even be possible to use an un-patched version of OpenFst, since the changes to minimization that we previously patched have now been accepted upstream.  [However, there is a change regarding threading, Incr() and Decr() that I think might still need to be patched, see openfst_gcc41up.patch.]

Obviously it would take a while to upgrade; we'd have to maintain a separate branch for a while.

**Comment by vdp** [comment]
FWIW, I think it should be safe to migrate to C++11. For example Google's, TensorFlow which is obviously an important piece of their strategy of waging the Cloud Wars, and supports a bunch of platforms including (since recently) Windows. Unsurprisingly their code is very well written style-wise, IMHO, and could be used as a guide for Kaldi's potential C++11 transition. I don't know why you don't like "auto"- it will remove much of the line-noise that are the iterator definitions in older C++ versions.

Just my 2c- obviously the opinion of the people who are actively contributing at the moment should be given much more weight than mine.

**Comment by dogancan** [comment]
I am on the same boat with @vdp. Even if we don't transition all of existing Kaldi codebase, a compiler with C++11 support is a perfectly reasonable requirement IMHO. We are currently going through hoops to support a number of OpenFst versions. If we require C++11, not only can we remove the support for old OpenFst versions, but also make things significantly easier for people who want to maintain Kaldi packages for Linux.

**Comment by danpovey** [comment]
@dogancan, it looks like there is support for allowing Kaldi to require C++11.  So I think we'll go ahead with this.  It would be great if you could help, as I know you're much more familiar with C++11 than I am.

The basic goal is to modify all the code that uses threads, to use C++11-style threads and not pthreads; to remove most of what exists in the thread/ directory; and if anything needs to remain, to move it to util/, e.g. util/kaldi-thread.h.  You can grep for pthread and for the classes and functions defined in kaldi-thread.h, namely Mutex, Semaphore, Barrier [not used much], MultiThreadable/RunMultiThreaded, and TaskSequencer.  Most of these are fairly vanilla, but the interfaces of the last two are non-standard enough that some wrapping code may be needed, or calling code may have to be changed. 
 
MultiThreadable/RunMultiThreaded is just a mechanism for running a number of parallel tasks, using no more than a specifiable number of threads at the same time (we actually spawn one thread per task, which is OK since the tasks are never too small).  It's not super pretty, and I'd be open to changing it since it's not used in too many places (but it may be easier to just keep a similar interface).

TaskSequencer is a little more special-- it's the situation of where you are processing a sequence of tasks, and are willing to use up to a certain number of threads; each task is associated with an object (with an operator () that does the work), but the destructor of the object may have side effects, so those destructors need to be called in order.  The TaskSequencer class is responsible for calling the destructors.  We won't be able to change the basic pattern that there is a class with an operator () and a destructor, because that would require changing too much code.  So likely some wrapping code will still be needed.

Note: in kaldi-thread.h a variable g_num_threads is declared which is registered to the --num-threads option in those programs that use threads.  (In the rare cases where different num-threads are wanted for different purposes, programs may have other options that specify the num-threads for different parts of the code).  Obviously this is a bit ugly.  I think the main use of it where passing it in would require an interface change, is in SGMM code where some precomputation is done multi-threaded; but there may be other cases like that.  It's very possible that this could be passed in via a config class somehow.  I'd be open to having this reworked if you can figure out how, but there may be a few cases where you'd have to change interfaces to pass things in.  But actually I don't care about this much-- leaving it as a global variable would be fine with me, and to some extent this is orthogonal to the C++11 upgrade.


Let's not go full-on C++11 yet in the code yet; maybe a little auto, but none of the exotic functionality.

**Comment by dogancan** [comment]
@danpovey, I have a few questions regarding the extent of changes we are planning to make. Should we keep the discussion related to this upgrade in this issue thread or should I open a new WIP pull request to keep track of the discussion and comments as well as code changes?

**Comment by danpovey** [comment]
This issue is fine for further discussion, until the PR exists.

**Comment by dogancan** [comment]
One thing that this upgrade will allow us is to drop support for old OpenFst releases going forward and remove a whole bunch of ifdef statements. Is there a good reason for supporting old OpenFst releases after this upgrade? With the current Kaldi installation mechanism, I don't see a particular reason to download and install an old OpenFst release.

**Comment by danpovey** [comment]
Yes that's true.  It would be possible to combine this with your other
patch, then we can test them together and have only one increment in the
configure version.

**Comment by dogancan** [comment]
I was thinking we would do the other patch first, make a Kaldi point release, mark that as the last release with support for old compilers and then remove support for old OpenFst releases along with the C++11 upgrade.

**Comment by danpovey** [comment]
That's possible too, but both patches will require extensive testing, and
the OpenFst upgrade is of the same nature as the C++11 upgrade in that it
doesn't really add functionality but is for future compatibility; so we
would save quite a lot of work by combining the two.

We don't really have the concept of Kaldi version number.  There is a
separate discussion about that but not really resolved.

**Comment by dogancan** [comment]
Ok, I guess we can branch off the current master and call that the legacy support branch or something and let people continue to use that branch with old compilers. That way it would be possible for people to open pull requests against that branch for maintenance. The openfst upgrade patch can be merged to that branch if need be.

Regarding versioning, this C++11 upgrade can be a good point to do a major version bump to signify a major change in platform support.

**Comment by danpovey** [comment]
As I said, we currently do not have a concept of version number.

In the past we tried supporting multiple versions (e.g. stable/trunk) but
it turned out to be way too much work.  It's just too much of a demand on
my time-- some things are doubled.  So we won't be doing this.  Kaldi will
be upgraded and if people don't want to upgrade, we can just let them the
know the git hash that they should check out to get the old version.

**Comment by dogancan** [comment]
Sorry for the confusion. I didn't mean to suggest we keep supporting multiple versions. Only that there would be a largely unsupported legacy branch for people to keep using with old compilers. I suppose that can get out of hand if people expect that branch will be supported. I haven't had to deal with this before, so I'll just shut up now :)

I understand that Kaldi does not have the concept of a version number yet. I meant to suggest that if there is going to be some sort of rudimentary versioning, then this upgrade could be a good point to start that.

**Comment by danpovey** [comment]
We could certainly make a note of the old git hash by creating a branch.

And I'll definitely consider introducing a version number.  The only really
practical approach, though (considering that our time is limited) is to
make the versions effectively be tags, i.e. no updates.  There is a
discussion of this at Issue #1179.

**Comment by danpovey** [comment]
Dogan, how about you edit the travis script so that it prints out the date at the start and after making in tools/; and then in src/, it first prints the date, then does 'make', then prints the date again, then does 'make test'?  This will let us know which part is slow.

**Comment by dogancan** [comment]
Initial timing results are below. Builds and tests are done with 3 concurrent jobs. Travis script builds only openfst in tools. Total time includes the startup costs.

task  | master | c++11
----- | ------- | ------
tools | 3:18     | 7:33
src    | 13:32   | 27:33
test   | 7:15     | 13:21
total  | 25:16  | 49:32

C++11 build takes twice as long. Whether it succeeds or fails depends on how busy Travis is at the time. Timeout is at 50 mins.

I still think the slowdown is due to the compiler. It seems the "--std=c++11" flag is enabling a different (and significantly slower) code path. Upgrading the compiler we use for travis (or for that matter the Ubuntu distibution) might help.

**Comment by dogancan** [comment]
I made some exploratory experiments building openfst with 3 concurrent jobs. Results are below.

platform                                         | master | c++11
---------------------------------|------- |-------
ubuntu 16.04 + g++-4.9               | 2:09    | 4:33
ubuntu 16.04 + g++-5.4               | 1:56     | 4:14
ubuntu 16.04 + clang (llvm-3.8)  | 1:34     | 3:35
macOS 10.12 + clang 8.0              | 2:18     |  3:33

It seems newer versions of g++ is doing a somewhat better job but not as good as clang.

**Comment by danpovey** [comment]
I've seen somewhere online that c++11 might be slower because the standard
library headers are more huge.  This might be hard to work around.

We might need to investigates alternatives to jenkins, including paid
options.
We already pay about $1700 per month for openslr.org due to network
ingress/egress, so paying a few dollars more is a rounding error.

**Comment by dogancan** [comment]
@danpovey, @jtrmal, @kkm000:
I changed the travis script to build and test with 4 concurrent jobs on the c++11 branch which seems to help a bit (total time around 40mins). Setting clang++ as the compiler is not enough to get a build going with clang though. According to the internetz, built in clang/c++11 support provided by travis VMs is sketchy at best. Apparently, the current best solution is to have a custom travis config to set up your own clang build environment (similar to what we are doing for g++ right now). I am not sure what the best course of action here is.

**Comment by vdp** [comment]
@dogancan BTW have you tried to set the optimization level to "-O0"? I haven't benchmarked this myself, but as far as I know in some cases it can speed-up compilation significantly. Another low-cost workaround could be to use pre-compiled OpenFST for the Travis jobs. I have absolutely no clue about Travis and how it's used with Kaldi, though..

@danpovey $1700 sounds like a lot. Using a dedicated host provider will be probably a lot cheaper (e.g. [Hetzner's bandwidth prices](https://wiki.hetzner.de/index.php/Traffic/en)).

**Comment by dogancan** [comment]
I just tried the optimization level "-O0" but that did not help. Apparently, that was already the default. Pre-compiled OpenFst should help a bit but the savings we can get from that is small compared how long it takes to compile kaldi.

**Comment by vdp** [comment]
Well, obviously the compilation speed is not much of a priority for the C++ folks. Let's just hope that all this bloat is compile-time-thing-only. While long compilation times are already annoying, if the runtime performance, and especially the decode-time performance, are adversely affected as well, that would be really bad..

**Comment by jtrmal** [comment]
http://stackoverflow.com/questions/34179434/is-compiling-with-c11-way-slower-than-with-c98


C++11 is known to be slow at compilation, in particular because standard
headers (like <map> or <vector> ....) are bringing lots of material (and
probably more in C++11 than in C++03).

For example, the following e.cc file (just two *standard* includes!):

#include <vector>#include <map>

When compiling with g++ -std=c++11 -C -E e.cc | wc -l I am getting 41870
preprocessed lines, when compiling with g++ -std=c++03 -C -E e.cc | wc -l I
am getting 15598 lines, both with GCC 5.3 <http://gcc.gnu.org/gcc-5/>, on
Linux/Debian/Sid/x86-64.

**Comment by kkm000** [comment]
Closing as completed in #1342.
