### ISSUE TITLE
Support for openfst 1.5.x

### ISSUE THREAD

**Issue by jtrmal** [kaldi-asr/kaldi#1235]
It would be good if we could include support for the openfst-1.5.x
I had reports it does not work right away, but due time constraints this wasn't pursued further.
Can be related to #1234  also.
We should at least evaluate how hard it would be to include the support and what are the major hurdles in that.

**Comment by danpovey** [comment]
@GaofengCheng, maybe you could look into this?

**Comment by dogancan** [comment]
Hi @danpovey. I think I can help with this. Let me investigate what changes are needed to support openfst 1.5.

**Comment by jtrmal** [comment]
Cool,  thanks a lot!
Y.

**Comment by danpovey** [comment]
Thanks.  @GaofengCheng, don't bother with this.. .I know you have other stuff you're doing.

**Comment by kkm000** [comment]
Past 1.5 as of #1342, done.
