### ISSUE TITLE
OpenFST 1.4.1 causes the build to fail

### ISSUE THREAD

**Issue by jrziviani** [kaldi-asr/kaldi#1239]
Hello!

After changing the Makefile to use open fst 1.4.1
```
  8 # OPENFST_VERSION = 1.3.4
  9 # Uncomment the next line to build with OpenFst-1.4.1.
 10  OPENFST_VERSION = 1.4.1
```
I have this error:
```
get --tries=1 -T 5 http://openfst.cs.nyu.edu/twiki/pub/FST/FstDownload/openfst-1.4.1.tar.gz || \
wget -T 10 -t 3 http://www.openslr.org/resources/2/openfst-1.4.1.tar.gz
--2016-12-01 21:24:11--  http://openfst.cs.nyu.edu/twiki/pub/FST/FstDownload/openfst-1.4.1.tar.gz
Resolving openfst.cs.nyu.edu (openfst.cs.nyu.edu)... 128.122.80.127
Connecting to openfst.cs.nyu.edu (openfst.cs.nyu.edu)|128.122.80.127|:80... connected.
HTTP request sent, awaiting response... Read error (Connection timed out) in headers.
Giving up.

--2016-12-01 21:24:16--  http://www.openslr.org/resources/2/openfst-1.4.1.tar.gz
Resolving www.openslr.org (www.openslr.org)... 107.178.217.247
Connecting to www.openslr.org (www.openslr.org)|107.178.217.247|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2016-12-01 21:24:17 ERROR 404: Not Found.
```
Neither www.openslr.org/resources/2/openfst-1.4.1.tar.gz nor openfst.cs.nyu.edu seems to have that package. I was able to get it from http://pkgs.fedoraproject.org/repo/pkgs/openfst/openfst-1.4.1.tar.gz/ca8f1730b9b9b281e515611fa9ae23c0/

Thanks

**Comment by jtrmal** [comment]
I'll upload the 1.4.1 package there (on openslr.org). I think something has happened to the primary mirror -- I had problems two days ago with accessing openfst.org (which works now, but who knows what's really going on).
y.

**Comment by jtrmal** [comment]
OK, it's uploaded and seems to work. Closing the issue.
Thanks for letting us know!
