### ISSUE TITLE
  could --frame-subsampling-factor be an option of nnet3/decode.sh ? (chain)

### ISSUE THREAD

**Issue by vince62s** [kaldi-asr/kaldi#1254]
Just asking.
Might prevent from mistakes when not thinking of generating the corresponding textfile.

**Comment by danpovey** [comment]
Hm... I think I'd rather not do that because it could lead to confusion as
to what the correct mechanism of specifying it was.  I view it as a
property of the system rather than as a decoding option [of course you can
hack it if you want.]

**Comment by vince62s** [comment]
I see your point, but when we build the tree, we have to specify the option and it triggers the creation of the text file, it does not embed the config in the tree, so we can easily forget. Anyway, was just a question. no big deal.
