### ISSUE TITLE
max-change invalid

### ISSUE THREAD

**Issue by naxingyu** [kaldi-asr/kaldi#1257]
max-change is now invalid in nnet3 code, but steps/nnet3/components.py is still generating natural gradientaffinecomponent using max-change.

**Comment by danpovey** [comment]
Can you be more specific?  max-change is valid; are you sure you compiled your code after updating?  Or maybe you have something wrong on your path?  It's max-change-per-minibatch which is deprecated, but I believe the config is still accepted.

**Comment by vijayaditya** [comment]
Also if xconfig style arch definitions are going to be the norm, a
deprecation warning has to be added to steps/nnet3/components.py and the
config generators which use these component library.

--Vijay

**Comment by naxingyu** [comment]
I know that max-change is valid in updatablecomponent itf. However, there is a `Bad initializer` error on the `max-change` item when I have a config like this
```
component name=Tdnn_0_affine type=NaturalGradientAffineComponent input-dim=300 output-dim=850  bias-stddev=0  max-change=0.75
```

**Comment by danpovey** [comment]
Can you paste the error?  It's still far from clear what the issue is.

**Comment by naxingyu** [comment]
I have changed the script so now it works... I'll catch it if it came up again. closing.

**Comment by danpovey** [comment]
You should not remove the max-change from the script.  It is required for
best performance, and it has not be deprecated.
I still think the most likely scenario is that your code has not been
compiled recently.  But if there *is* a problem in the script, it would be
nice to see the exact error message.

**Comment by naxingyu** [comment]
I'll check after finishing the GALE update.
