### ISSUE TITLE
Change utils/mkgraph.sh so that it ignores the --mono,--left-biphone and --quinphone options.

### ISSUE THREAD

**Issue by danpovey** [kaldi-asr/kaldi#1258]
.. and remove the use of those options from checked-in example scripts.
Currently the script checks that the options match the given model.  We should just be getting the options from the model.

@pegahgh, can you show @LvHang how to do this, including the use of 'find' to find such instances and possibly 'sed -i' to replace them?

**Comment by pegahgh** [comment]
Sure Dan.

**Comment by LvHang** [comment]
Thanks. 
I will learn from Pegah and help to deal with it.

**Comment by danpovey** [comment]
done in PR #1260
