### ISSUE TITLE
Create temporary files atomically in utils/mkgraph.sh

### ISSUE THREAD

**Issue by danpovey** [kaldi-asr/kaldi#1267]
To stop the situation where half-written file causes errors later on in case a graph build was interrupted, I would like the program utils/mkgraph.sh to be changed so that instead of:

`
some-command > $lang/tmp/foo.fst
`
it does something like the following:
`
trap "rm -f $lang/tmp/foo.fst.$$" EXIT HUP INT PIPE TERM
some-command > $lang/tmp/foo.fst.$$
mv $lang/tmp/foo.fst.$$ $lang/tmp/foo.fst
`
(note: `$$` is the process ID of the current bash script, used here to ensure unique filenames in case multiple processes are writing.  Or you could use mktemp if you prefer, but be careful to ensure compatibility with BSD-type mktemp).
@LvHang, can you please work on this?

**Comment by LvHang** [comment]
Hi Dan,
Get it. I'll deal with it.
Hang

**Comment by danpovey** [comment]
done in issue #1272
