### ISSUE TITLE
Reg. local/score_sclite.sh in egs/gale_mandarin

### ISSUE THREAD

**Issue by vijayaditya** [kaldi-asr/kaldi#1268]
I was just taking a look at the gale_mandarin setup and was confused to see 

```bash
if [ $stage -le 2 ]; then  
  $cmd LMWT=$min_lmwt:$max_lmwt $dir/scoring/log/score.LMWT.log \
    cp $data/stm $dir/score_LMWT/ '&&' \
    $hubscr -p $hubdir -V -l english -h hub5 -g $data/glm -r $dir/score_LMWT/stm $dir/score_LMWT/${name}.ctm || exit 1;
fi
```
in the local/score_sclite.sh where `-l english` was specified. I was wondering if this script is ever called from local/score.sh ie., is there an stm file in the data directories being decoded ? 

I guess it might have been unintentionally copied, so better delete it to avoid confusion.

**Comment by vijayaditya** [comment]
Same issue even in egs/hkust.

**Comment by naxingyu** [comment]
So, there is not stm in gale_mandarin or hkust. score_sclite.sh is deprecated.

**Comment by vijayaditya** [comment]
@naxingyu In that case I would recommend cleaning up the score.sh script and deleting score_sclite.sh scripts.

**Comment by naxingyu** [comment]
ok.

**Comment by naxingyu** [comment]
This issue is addressed.

**Comment by vijayaditya** [comment]
Thanks.

Vijay

**Comment by jtrmal** [comment]
Closing.  Y.
