### ISSUE TITLE
phone sequence to words

### ISSUE THREAD

**Issue by hajix** [kaldi-asr/kaldi#1271]
Hi

Is there any recipe to build a decoder to convert phone sequence to words? I already have my own dictionary, phone set and ARPA formatted trigram language model, and I want to build a decoder according to AN4 example. I renamed and lay my files down in a similar format of AN4 files. I also manipulate `run.sh` to only execute `lang prep` section. Every thing goes on until I get the following error:

> Checking word-level disambiguation symbols...
--> data/lang/phones/wdisambig.txt exists (newer prepare_lang.sh)
Checking word_boundary.int and disambig.int
--> generating a 25 word sequence
--> resulting phone sequence from L.fst corresponds to the word sequence
--> L.fst is OK
--> generating a 35 word sequence
--> resulting phone sequence from L_disambig.fst corresponds to the word sequence
--> L_disambig.fst is OK
Checking data/lang/oov.{txt, int} ...
--> 1 entry/entries in data/lang/oov.txt
--> data/lang/oov.int corresponds to data/lang/oov.txt
--> data/lang/oov.{txt, int} are OK
--> data/lang/L.fst is olabel sorted
--> data/lang/L_disambig.fst is olabel sorted
--> data/lang/G.fst is ilabel sorted
--> ERROR: data/lang/G.fst is empty
fstdeterminizestar data/lang/G.fst /dev/null 
--> data/lang/G.fst is determinizable
--> utils/lang/check_g_properties.pl successfully validated data/lang/G.fst
--> utils/lang/check_g_properties.pl succeeded.
--> Testing determinizability of L_disambig . G
fsttablecompose data/lang/L_disambig.fst data/lang/G.fst 
fstdeterminizestar 
--> ERROR: fail to determinize L_disambig . G.  Output is:
fst type                                          vector
arc type                                          standard
input symbol table                                none
output symbol table                               none
\# of states                                       0
\# of arcs                                         0
initial state                                     -1
\# of final states                                 0
\# of input/output epsilons                        0
\# of input epsilons                               0
\# of output epsilons                              0
\# of accessible states                            0
\# of coaccessible states                          0
\# of connected states                             0
\# of connected components                         0
\# of strongly conn components                     0
input matcher                                     y
output matcher                                    y
input lookahead                                   n
output lookahead                                  n
expanded                                          y
mutable                                           y
error                                             n
acceptor                                          y
input deterministic                               y
output deterministic                              y
input/output epsilons                             n
input epsilons                                    n
output epsilons                                   n
input label sorted                                y
output label sorted                               y
weighted                                          n
cyclic                                            n
cyclic at initial state                           n
top sorted                                        y
accessible                                        y
coaccessible                                      y
string                                            y
--> ERROR (see error messages above)
prepare_lang.sh: error validating output

Please tell me where is the problem from?

**Comment by danpovey** [comment]
In speech recognition, there is no stage where we convert a phone sequence
to words.  It's all jointly decoded.  It's not clear to me what you are
trying to do, and what your real underlying task is.

The output of the determinization command resulted in an empty FST.
Possibly your G.fst was empty or your lexicon didn't cover all of the words
in it.

Dan

**Comment by hajix** [comment]
Thanks for your answer

My original problem is that I already make a phone recognizer and I need to build full ASR system base on this model. The output of my phone recognizer model is a 40 dim vector which is probability of each phone (39 phone and silent). If I was wrong about using a decoder for solving this problem please note about it.

Decoding problem could be formulated as a search problem that maximizes the probability of P(W|X), where W is optimal word sequence and X is acoustic observation. I searched enough about decoding problem and finally concluded that kaldi is the best solution for decoding problem. I was thinking that kaldi has a straightforward solution for this.

As you mentioned above, `lang prep` make an empty G.fst. I check my LM and find out it contains some words that has no entry in my lexicon! Is it reason of empty G.fst?

**Comment by danpovey** [comment]
If you want to build a speech recognizer from scratch, which it seems is
what you are doing, it would probably be easier to write your own code.  In
any case you should understand more.  Search for hbka.pdf online to learn
the basics of FST-based decoding.

In any case, I don't think I want to spend my time helping you in this
direction because there is a huge amount of work involved and ultimately
it's not useful because you're just going to create a substandard speech
recognition system.

Dan

**Comment by mukherjeesougata** [comment]
@hajix have you built any system which converts phone sequences to word using lexicon?
