### ISSUE TITLE
Fix tutorial

### ISSUE THREAD

**Issue by danpovey** [kaldi-asr/kaldi#1273]
@akreal, do you have time to update the Wit Zelinski tutorial with a fix?

Please see the thread here
https://groups.google.com/forum/#!topic/kaldi-help/-WMWyO0W6Ek
and if you have time also have a look at the link and see if there were any other fixes that they made, that we could use.

**Comment by akreal** [comment]
I'll have a look next week.

**Comment by danpovey** [comment]
Thanks!

**Comment by akreal** [comment]
I've created PR to fix `arpa2fst` command.

Their PDF doesn't have this fix and seems to be the same version that I used for Doxygen.

Actually I never run commands from the tutorial and this would be good thing to do to see if everything works for the recent source. I hope to have time for this next week.

**Comment by jtrmal** [comment]
I think this was fixed,  so closing.

**Comment by akreal** [comment]
I went through the tutorial and everything seems to work fine except of a couple of minor things. There is #1296 to fix them.
