### ISSUE TITLE
GPU for the non nnet2 parts of the recipe

### ISSUE THREAD

**Issue by mosherayman** [kaldi-asr/kaldi#1284]
I have been looking at the various online/nnet2 scripts

The online/nnet2 scripts all check for GPUs:

if $use_gpu; then
  if ! cuda-compiled; then
    cat <<EOF && exit 1 
This script is intended to be used with GPUs but you have not compiled Kaldi with CUDA 
If you want to use GPUs (and have them), go to src/, and configure and make on a machine
where "nvcc" is installed.  Otherwise, call this script with --use-gpu false
EOF
  fi

The "regular" run.sh scripts do not check for GPUs.

Do the run.sh scripts benefit from a GPU?

thanks
moshe

**Comment by ognjentodic** [comment]
GPUs are used for nnet training (nnet2 and nnet3 codebase) and relevant scripts will check if there is GPU support. 

run.sh is a high-level script, defining your experiment/recipe. If you are doing nnet training, it will benefit from (require) GPU since you will be calling nnet related scripts.

**Comment by danpovey** [comment]
... and any scripts other than nnet training will not benefit from a GPU.
Those other steps are relatively fast and there is not much benefit in
coding them for GPU.
Dan

**Comment by mosherayman** [comment]
Thanks for the reply.

So to actually build the online/nnet2 recipes you need a multicore box for
the non GPU parts, and a GPU for the nnet2 parts.

SInce I am using AWS, it seems that to do this all on one box, we would
need a p2.8xlarge (32 cores and 8 GPUs) which costs a whopping $7.20/hour!

Alternatively, we could split this over 2 boxes a c4.[48]xlarge for the
non-gpu stuff ($1.20/hr) and a smaller GPU instance a p2.xlarge (only 4
cores and 1 GPU at $0.90/hr).

Has someone worked out the most economical way to run these things on AWS?
Do these things scale out over 8 GPUs?  If yes, does the performance boost
justify the increased cost?

thanks

==================
thanks,
Moshe

**Comment by danpovey** [comment]
It depends how much data you have... if a lot (e.g. Switchboard) then
probably best to get that big box with 8 GPUs.  Yes it scales fine to 8
GPUs if you have more than a couple hundred hours of data... we sometimes
use 8 GPUs even if we have only a hundred hours, but the speedup is never
completely linear.

Splitting over multiple boxes will be a bit of a hassle as you'd have to
set up NFS.

Dan

**Comment by ognjentodic** [comment]
Another perspective, from a scrappy startup, without access to a large CPU/GPU cluster:

- typically, non-GPU steps you will run only once (aside from decoding on dev/test, etc), so you could get a large non-GPU machine to do that
- you keep all the data on EBS, so when ready to switch to nnet part you can start a GPU instance with that EBS
- depending on number of GPUs, CPU cores, etc. you will need to adjust some of the config params
- you'll need to get familiar with the scripts (most lower-level scripts allow control of starting point, etc.)
- IIRC, I needed at least 64GB RAM for some nnet training steps (egs related); this was for librispeech and maybe also tedlium. This was for nnet3 training, can't recall the details for nnet2

Ogi

**Comment by nshmyrev** [comment]
An economic choice is a GPU server on OVH ($195/month for two GeForce GTX 970). Much faster than Amazon because it is a real hardware.

**Comment by vdp** [comment]
@nshmyrev: This sounds interesting, if one needs a lot(or OK, moderate by today's standards) GPU processing power for a limited period of time.. Have you benchmarked how much faster is this than say g2.2xlarge for training Kaldi models? I assume that you are saying they are faster than the g2 instances, because I'd expect the newer p2 ones will be significantly faster? (they also seem to be oversubscribed as far as I can tell from the insane(~$77/hour) spot price last time I checked)
