### ISSUE TITLE
Trouble with TaskSequencer

### ISSUE THREAD

**Issue by MertBuyuktuncay** [kaldi-asr/kaldi#1289]
Hi,
Due to a leak report in nnet3 modules I was checking out things in kaldi and I've seen a data race which leads to both some memory leak and probably incorrect initialization.

Let me try to explain...

TaskSequencer is used inside the method IvectorExtractor::ComputeDerivedVars().
TaskSequencer::Run() is called in a tight loop several times each time with a new parameter object. (in my case it is being called 512 times)

the important part in TaskSequencer is that thread_list_ is a raw pointer member. in the following code this member is overridden several times (thread count is 8)
TaskSequencer::Run()
{
	threads_avail_.Wait(); // wait till we have a thread for computation free.
    tot_threads_avail_.Wait(); // this ensures we don't have too many threads
    // waiting on I/O, and consume too much memory.
    
    // put the new RunTaskArgsList object at head of the singly
    // linked list thread_list_.
    thread_list_ = new RunTaskArgsList(this, c, thread_list_);
	...
	
}
	

thread_list_ variable is only deleted once in the destructor so all the other objects previously overridden have been leaked, also initializations are also done through a single thread_list_ pointer so every 8 object probably ends up being initialized with the same input.

In our own branch

I've changed the following method as follows:
void IvectorExtractor::ComputeDerivedVars() 
{
	...more code here
	
	 // Note, we could have used RunMultiThreaded for this and similar tasks we
  // have here, but we found that we don't get as complete CPU utilization as we
  // could because some tasks finish before others.
  {
    /*TaskSequencerConfig sequencer_opts;
    sequencer_opts.num_threads = g_num_threads;*/
    /*TaskSequencer<IvectorExtractorComputeDerivedVarsClass> sequencer(
        sequencer_opts);*/
	for (int32 i = 0; i < NumGauss(); i++)
		ComputeDerivedVars(i);
      //sequencer.Run(new IvectorExtractorComputeDerivedVarsClass(this, i));
  }
  KALDI_LOG << "Done.";
}

thus eliminating the TaskSequencer usage.
This from a few simple tests this change has increased our initialization durations only a little
before the change the initialization durations were around 180msec
after the change the initialization durations are around 210~240msec

I would like to take get your opinion on this change and if it can be accepted as a fix I would like to change it in this repository too.

Additional note : Instead of removing the threading I also thought of using a threadpool like construct but there is no thread pool etc. in kaldi so I do not know what I can put instead of this immediately. In my case I would not like to call pthread_create 512 times for a gain in initialization anyway so I completely removed the threading. 
My company thinks highly of kaldi so if you have plans to insert threadpool I think I might spend a little time to help you on this.

Regards
Mert Büyüktuncay

**Comment by danpovey** [comment]
We do plan to rewrite that code based on boost threads in the near future.
However, I am quite doubtful that there is really a leak there.
Notice that thread_list_ is a singly linked list and its destructor will
call delete on its tail.
What tool initially reported a leak, and can you show what it said?

**Comment by MertBuyuktuncay** [comment]
Hi Daniel,
The following image contains the corresponding info.
This is taken with the performance profiler that comes with visual studio 2015. It shows the difference between two snapshots on the memory of our process. The process belongs to a test application that is written just for this issue. The process is 64 bit.
In between these two snapshots nnet3 models are being loaded and released and nothing else is being done. (to be exact the same loading/releasing is done 3 times to see the difference more clearly)
![image](https://cloud.githubusercontent.com/assets/16477026/21515279/ed2a26b8-ccd6-11e6-97fe-90d5b14a475e.png)

With the change I've proposed the same test reports "no change" ie. all the allocated memory has been released successfully. 

To be absolutely sure I've also tracked the newed and deleted pointers by adding logs to the allocation and deletion locations. The logs also proved to me that only the last pointer is being deleted and the previous ones are leaked. I do not have that logs now. I can reproduce them if necessary.

This situation can also be observed from task manager. With our models the leak was around 15MB for each load/delete. So with a simple for loop repeating the same thing a few dozen times the memory shown by task manager jumps up quickly.

**Comment by danpovey** [comment]
Oh-- you're using Windows.
Microsoft products are... *special*.
There's no conceivable memory that could be leaked inside AddMat2Sp because
it doesn't even call new and all the things it uses are thoroughly debugged.
With 100% probability it's an error in the Microsoft tool you are using to
debug.

**Comment by danpovey** [comment]
... or alternatively it's possible that some lower level things we use are
thread safe on Linux but not thread safe on Microsoft.
If you figure out what is going wrong and how things should be changed, I'd
be happy to listen.  But so far you haven't identified any bug.  I don't
have time to get too deeply into Windows issues; in my experience the
answer is usually that Microsoft's compilers are badly messed up and the
workaround is painful, and it's just a huge waste of our time to deal with
it.  We're not really putting much priority on the Windows platform.

**Comment by danpovey** [comment]
Actually, have a look into the documentation of your BLAS library and see
whether you have to build or invoke it with special options if you want it
to be thread safe.

**Comment by MertBuyuktuncay** [comment]
Hi Dan,
What I have kind of observed was that TaskSequencer does not seem to delete the tail but only the list itself in the end. It is quite possible that I am misinterpreting things so I will write a small test for TaskSequencer and check if it really behaves as desired.

**Comment by danpovey** [comment]
Those bits of memory are not even supposed to be deleted by that code, to
my knowledge.  Very little memory is deleted by that call you are focusing
on.

I think most likely it's a non-thread-safe-BLAS issue.

**Comment by MertBuyuktuncay** [comment]
I've written a quick test on TaskSequencer.(Added testCode.txt here). It seems TaskSequencer is clear from leaks.
[testCode.txt](https://github.com/kaldi-asr/kaldi/files/675231/testCode.txt)

We are using intel mkl. Their documentation says it is threadsafe. I am not sure what exactly to test in mkl.

**Comment by MertBuyuktuncay** [comment]
In order to understand if this was a wrong leak report I tried running the test program longer than usual, Added an infinite loop st. it loads and releases the model infinitely many times.

After several tens of times my windows machine warned me about low resources, at this time my RAM was about half full so this most certainly did not occurred due to lack of memory, probably windows does not cope well with this many number of threads frequently being opened up and closed. After running the test app 3 times my  screen went blank, I needed to forcefully restart my machine. So much for windows 10. 

This situation does not occur in the non-threaded implementation. So instead of an application error we are facing windows not handling too many threads gracefully.

Still TaskSequencer generates more than necessary amount of threads. Even in linux this is not a very desired situation. You told you plan to rewrite the threading parts in the near future. I look forward to hear/see/help that work. I am a little surprised because I read you are slowly starting to use c++11. Do you not plan to use std::thread instead? Maybe that is a different disccussion though.

**Comment by danpovey** [comment]
sorry, I meant c++11 threads, not boost threads.  we plan to use
std::thread.  We could definitely use a thread pool.  We'd be happy to use
your help.  But first we want to do the upgrade to c++11, that may be a few
more weeks.

**Comment by danpovey** [comment]
Closing this issue--@MertBuyuktuncay, there is discussion about the threading in issue #1234.
