### ISSUE TITLE
Missing files in fisher_swbd

### ISSUE THREAD

**Issue by stanleyguan** [kaldi-asr/kaldi#1307]
I have encountered a few missing files running `fisher_swbd/s5/local/run_ivector_common.sh`:

`conf/mfcc_hires.conf`
`conf/online_cmvn.conf`
`local/remove_dup_utts.sh`

What I did was copying them over from other examples.

**Comment by danpovey** [comment]
Thanks a lot for reporting it.  @naxingu, can you please fix it?

**Comment by naxingyu** [comment]
Sorry about that. I’ll fix ASAP.

**Comment by naxingyu** [comment]
@danpovey , should we make remove_dup_utts a utils script instead of local?

X.

**Comment by danpovey** [comment]
It already exists, use

utils/data/remove_dup_utts.sh
