### ISSUE TITLE
Remove sinusoid detection code; remove old SGMM code

### ISSUE THREAD

**Issue by danpovey** [kaldi-asr/kaldi#1315]
I don't think the sinusoid-detection code is being used anywhere so I think it makes sense to remove it.
Also I don't believe the "old" sgmm code (as opposed to sgmm2, which is slightly better) has any reason to still be in the repository.  I'd like to remove that too.
I'm putting this up as an issue in case there are any objections.

**Comment by danpovey** [comment]
@LvHang, can you please work on this?  Start with removing the sgmm and sgmmbin directories, detect-sinusoids.cc and sinusoid-detection.{h,cc}.  You'll have to update the Makefiles.
Check that things still compile, and that they still compile even after doing 'make clean'
Search in the scripts for things that call any of the sgmm binaries, and remove them also.  They'll have sgmm in the name but not sgmm2.  E.g. you can find candidates with something like
```
find egs -name '*sgmm*' -not -name '*sgmm2*' -print
```
but be careful, sometimes we have a script like run_sgmm.sh but it actually does the sgmm2 training.  We want to keep the sgmm2 code and scripts.

**Comment by LvHang** [comment]
Ok，get it. I'll deal with it.

**Comment by mpenagar** [comment]
Timit recipe (and I think that many other) use init-ubm command in sgmmbin:

$ cat exp/ubm4/log/cluster.log
# init-ubm --intermediate-num-gauss=2000 --ubm-num-gauss=400 --verbose=2 --fullcov-ubm=true exp/tri3_ali/final.mdl exp/tri3_ali/final.occs exp/ubm4/0.ubm
# Started at Wed Jan 11 18:16:33 CET 2017
#
bash: line 1: init-ubm: command not found

How should it be replaced? Thanks!

**Comment by ngoel17** [comment]
Dan,
   I meant to visit the sinusoid detection code some point of time and
determine its usability for DTMF and ring tones. Can you please point me to
this.

Nagendra

**Comment by LvHang** [comment]
Hi Dan,
The code--"init-ubm" is originally in sgmmbin/ directory. I check the dependencies of it. I think it is not relate to sgmm/. At the same time, it will be called by some scripts, such as "train_ubm.sh". Maybe we can move it to another directory, such as gmmbin/. Which one is better?

Hang

**Comment by LvHang** [comment]
For sinusoid detection code, I think the code isn't be used anywhere in our standard scripts. I think this should be some personal needs. 

Hang

**Comment by danpovey** [comment]
I just fixed the init-ubm.cc issue manually and pushed the change, in the
interests of time.
Nagendra, the most recent git hash where the sinusoid-detection code
existed is f646952.  You can get it from there with e.g.
git checkout  f646952 [program-name]
Check Hang's PR to get a list of relevant source files.
Dan

**Comment by kkm000** [comment]
Close this?
