### ISSUE TITLE
Randomize over GPUs in process exclusive mode

### ISSUE THREAD

**Issue by stanleyguan** [kaldi-asr/kaldi#1319]
I'm training a BLSTM using `wsj/s5/steps/nnet3/chain/train.py` on [AWS P2 instances](https://aws.amazon.com/ec2/instance-types/p2/). I set my GPUs in process exclusive mode. I found that although earlier iterations only use a subset of GPUs, the _same subset_ are used at every iteration (e.g. it's always GPUs 0-3). After several hours the GPUs start throttling (or, stop [overclocking automatically](https://devblogs.nvidia.com/parallelforall/increase-performance-gpu-boost-k80-autoboost/)) due to depletion of heat headroom. As a result, training time per iteration deteriorates progressively from ~7.5 mins per iteration to ~15 mins per iteration in about a day.

One fix would be to randomize over the GPUs to use at each iteration. This won't help the later iterations where almost all GPUs are used, but probably still a better practice since you may not want to hit the same GPUs over and over again at the start.

For now I'm restarting my instance every few hours - which gives me a fresh hardware each time. One alternative would be to switch off process exclusive mode. But that sometimes will use the same GPU for two jobs.

**Comment by danpovey** [comment]
Don't switch off process exclusive mode-- it will then sometimes share GPUs
and crash.
You could try modifying the python script to set CUDA_VISIBLE_DEVICES to
different random subsets of the GPUs on different iterations.
But I'm not sure how much this would help the heat issue.  Seems like a
hardware design flaw.
Dan

**Comment by stanleyguan** [comment]
I think it's not necessarily a hardware flaw, since it can be desired to have GPUs overclock automatically when they're still cold. It's also very common for hardware to throttle themselves after running at full capacity for a long time -- I think it's kind of unavoidable.

I made the change you suggested and now after one day of continuous running I'm seeing minimal deterioration (it's using 6/16 GPUs currently). Do you want me to put in a PR? I'm new to contributing to kaldi and any suggestions in terms of style or particular to this issue are very welcome.

**Comment by danpovey** [comment]
Cool.
No, don't make a PR... this is very specific to the hardware setup that
you're using, and usually we're running via something like GridEngine,
and/or sharing the machine with other jobs, and this code would interfere
with that.

**Comment by stanleyguan** [comment]
No problem. Thanks.
