### ISSUE TITLE
nnet3 decoding

### ISSUE THREAD

**Issue by cdxie** [kaldi-asr/kaldi#1332]
In the nnet3 structure，when we finished the LSTM training，whether the LSTM decoding can be done parallel on GPU??
in the steps/nnet3/decode.sh, "parallel_opts" option is ignored, and no "use GPU" selection

**Comment by danpovey** [comment]
The internal code does support using GPUs, but it looks like the option
[--use-gpu] has not been made available at the binary level
[nnet3-latgen-faster].
It's not really recommended to use GPUs for decoding, as decoding one file
at a time doesn't make very good use of the GPU.

Dan
