### ISSUE TITLE
cu-rand issues

### ISSUE THREAD

**Issue by danpovey** [kaldi-asr/kaldi#1339]
@vesis84, do you have time to help with some cu-rand issues?

Firstly, I think it would be convenient to have the RandUniform() function work for CuVector also.

Also there are some optimizations that I think would be nice and a concern about safety that I have...

If the RandUniform()/RandGaussian() functions had different implementations for CuMatrix and CuSubMatrix, it would make the code more optimizable, as we know for a CuMatrix that the space between the strides is owned by us [well, modulo issues of how cudaMallocPitch() works.]

Also-- the even/odd thing only matters for Gaussian, not uniform, generation: search for 'even' here:
http://docs.nvidia.com/cuda/curand/group__HOST.html#group__HOST_1gb9280e447ef04e1dec4611720bd0eb69

I think it would be safer when allocating the 'tmp' matrix and dealing with the 'rounding-up' issue, to round up the numCols() to make it even when allocating the 'tmp' matrix, and then when calling curandGeneratexxx, to call it with the exact number of bytes from the first to the last [row,col].  I don't know if it's documented that when you call cudaMallocPitch it lets you own the memory past the last column up to the stride.  And I'm also a bit concerned what happens with matrices with one row.  The cu-allocator code just calls regular cudaMalloc if the matrix has one row, and there is no kind of padding, so this code would write one past the end.

**Comment by vesis84** [comment]
Hi, okay, I'll take a look at it...
