### ISSUE TITLE
Voxforge does not have LSTM script

### ISSUE THREAD

**Issue by 15mscsmirfan** [kaldi-asr/kaldi#1363]
There is not script available for Voxforge to run LSTM on it. Add LSTM for Voxforge data set.

**Comment by danpovey** [comment]
We are not really keeping the Voxforge script very up-to-date.  You can see the Librispeech scripts which use similar data but more of it.  however Librispeech is not always 100% up to date either.  Closing the issue since it's not likely to happen soon, and there are other pressing things.
