### ISSUE TITLE
make valgrind: definatley lost, invalid read

### ISSUE THREAD

**Issue by weegreenblobbie** [kaldi-asr/kaldi#1369]
We've been having issues with kaldi on our grid with jobs hanging and not finishing.  I've eliminated the possible causes: out of memory, time limit, frozen node.  The only thing left are possible bugs in kaldi.  But I could be wrong.  :)

So I started running `make valgrind` to test the example programs and ran into this:

```
echo -n > valgrind.out
for x in nnet-randomizer-test nnet-component-test; do echo $x>>valgrind.out; valgrind ./$x >/dev/null 2>> valgrind.out; done
! ( grep 'ERROR SUMMARY' valgrind.out | grep -v '0 errors' )
! ( grep 'definitely lost' valgrind.out | grep -v -w 0 )
==31416==    definitely lost: 240 bytes in 4 blocks
make[1]: *** [.valgrind] Error 1
make[1]: Leaving directory `/usr/local/kaldi/src/nnet'
valgrind on nnet failed
make: [valgrind] Error 1 (ignored)
root@fd2d8ec2d774:/usr/local/kaldi/src# git log -n 1
commit 61510ca0d8d9b38096701227ee064a166816fcbe
Author: Ke Li <kli26@jhu.edu>
Date:   Mon Jan 23 02:07:24 2017 -0500

    nnet3/report : Modified directory specification options in generate_plots.py  (#1368)
```

Kaldi configure command: `./configure --use-cuda=no --shared`

We've only been using kaldi for 2 weeks so we are still learning things.  When using openblas 0.2.19 and configuring with: `./configure --shared --mathlib=OPENBLAS --openblas-root=/usr/local --use-cuda=no`, `make valgrind` errors out with:

```
make[1]: Entering directory `/usr/local/kaldi/src/matrix'
echo -n > valgrind.out
for x in matrix-lib-test kaldi-gpsr-test sparse-matrix-test ; do echo $x>>valgrind.out; valgrind ./$x >/dev/null 2>> valgrind.out; done
! ( grep 'ERROR SUMMARY' valgrind.out | grep -v '0 errors' )
==6634== ERROR SUMMARY: 719 errors from 107 contexts (suppressed: 0 from 0)
==6638== ERROR SUMMARY: 4 errors from 3 contexts (suppressed: 0 from 0)
make[1]: *** [.valgrind] Error 1
make[1]: Leaving directory `/usr/local/kaldi/src/matrix'
valgrind on matrix failed
make: [valgrind] Error 1 (ignored)
```

We've been using openblas on the grid, I will try atlas and report back if that resolves our issues.

**Comment by danpovey** [comment]
Show us what's in valgrind.out.   Valgrind often shows a lot of spurious
errors.
It's extremely unlikely that this kind of problem would be caused by bugs
in Kaldi itself, although I'd be happy to learn about any memory leaks and
fix them.  Kaldi uses threading very sparingly, most programs do not use it
at all, and any real bugs would have been found long ago.
If a job is not finishing, let me know what kind of job it was (and maybe
show the partial output), and also what parallelization software you are
using (GridEngine?).  Have you been using that software a while?  It sounds
more like a problem with that.


Dan

**Comment by weegreenblobbie** [comment]
Thanks for the quick response.  Yes, we're using GridEngine.  I've been following the fisher switchboard recipe `kaldi/egs/fisher_swbd/s5/run.sh`, things were going very smoothly until this portion of `run.sh`:

```
#!/bin/bash
 
# It's best to run the commands in this one by one.
 
. ./cmd.sh
. ./path.sh
mfccdir=mfcc
set -e
rescore=true
  
#-----------------------------------------------------------------------------
# continue training --> exp/tri4a

d0=$(date "+%x %X")

(
  graph_dir=exp/tri3b/graph_fsh_sw1_tg
  utils/mkgraph.sh data/lang_fsh_sw1_tg exp/tri3b $graph_dir || exit 1;
  steps/decode_fmllr.sh --nj 50 --cmd "$decode_cmd" --config conf/decode.config \
   $graph_dir data/eval2000 exp/tri3b/decode_eval2000_fsh_sw1_tg || exit 1;
  steps/decode_fmllr.sh --nj 50 --cmd "$decode_cmd" --config conf/decode.config \
   $graph_dir data/rt03 exp/tri3b/decode_rt03_fsh_sw1_tg || exit 1;
) &

# Next we'll use fMLLR and train with SAT (i.e. on
# fMLLR features)

steps/align_fmllr.sh --nj 400 --cmd "$train_cmd" \
  data/train_nodup data/lang exp/tri3b exp/tri3b_ali || exit 1;

steps/train_sat.sh  --cmd "$train_cmd" \
  11500 800000 data/train_nodup data/lang exp/tri3b_ali  exp/tri4a || exit 1;

d1=$(date "+%x %X")

echo "BEGIN: $d0"
echo "END:   $d1"

xxxxxxxxxxxxxxxx
```

A random job stops writing to it's log, I don't see any error messages in the logs.  My last 5 error messages:

```
queue.pl: Error, unfinished job no longer exists, log is in exp/tri4a/log/fmllr.12.232.log, last line is 'LOG (gmm-est-fmllr[5.0.9~1448-5f15d]:main():gmm-est-fmllr.cc:143) For speaker fe_03_08175-B, auxf-impr from fMLLR is 0.101765, over 19039 frames.', syncfile is exp/tri4a/q/sync/done.13130.232, return status of qstat was 256
Possible reasons: a) Exceeded time limit? -> Use more jobs! b) Shutdown/Frozen machine? -> Run again!  Qmaster output was: Following jobs do not exist:
3269747
```

```
queue.pl: Error, unfinished job no longer exists, log is in exp/tri3b_ali/log/align_pass1.18.log, last line is 'WARNING (gmm-align-compiled[5.0.9~1448-5f15d]:AlignUtteranceWrapper():decoder-wrappers.cc:466) Retrying utterance fe_03_02325-A-014677-015563 with beam 40', syncfile is exp/tri3b_ali/q/sync/done.8646.18, return status of qstat was 256
Possible reasons: a) Exceeded time limit? -> Use more jobs! b) Shutdown/Frozen machine? -> Run again!  Qmaster output was: Following jobs do not exist: 
3269817
```

```
queue.pl: Error, unfinished job no longer exists, log is in exp/tri4a/log/acc.1.35.log, last line is 'LOG (gmm-acc-stats-ali[5.0.9~1448-5f15d]:main():gmm-acc-stats-ali.cc:105) Processed 6000 utterances; for utterance fe_03_04770-A-004818-005508 avg. like is -51.7111 over 688 frames.', syncfile is exp/tri4a/q/sync/done.14157.35, return status of qstat was 256
 Possible reasons: a) Exceeded time limit? -> Use more jobs! b) Shutdown/Frozen machine? -> Run again! Qmaster output was: Following jobs do not exist: 
 3270216
```

```
queue.pl: Error, unfinished job no longer exists, log is in exp/tri4a/log/align.10.24.log, last line is 'WARNING (gmm-align-compiled[5.0.9~1448-5f15d]:AlignUtteranceWrapper():decoder-wrappers.cc:466) Retrying utterance fe_03_03226-B-004922-005221 with beam 40', syncfile is exp/tri4a/q/sync/done.22772.24, return status of qstat was 256
Possible reasons: a) Exceeded time limit? -> Use more jobs! b) Shutdown/Frozen machine? -> Run again!  Qmaster output was: Following jobs do not exist: 
3270342
```

```
queue.pl: Error, unfinished job no longer exists, log is in exp/tri4a/log/fmllr.4.30.log, last line is 'LOG (gmm-est-fmllr[5.0.9~1448-5f15d]:main():gmm-est-fmllr.cc:143) For speaker fe_03_04117-B, auxf-impr from fMLLR is 0.0462073, over 18604 frames.', syncfile is exp/tri4a/q/sync/done.26770.30, return status of qstat was 256
Possible reasons: a) Exceeded time limit? -> Use more jobs! b) Shutdown/Frozen machine? -> Run again! Qmaster output was: Following jobs do not exist: 
3270439
```

When I run the failed jobs locally on my laptop, they only use around 150 MB.  They appear on different nodes.  After it fails, I look at the logs.  The failing host is different each time, not isolated to a single host.  So I run the failed script locally and lunch run.sh again.

Il suspect it's the combination of kaldi + openblas 0.2.19.  I'll go collect some valgrind output and post here.

Thanks!

**Comment by weegreenblobbie** [comment]
Some of the errors with kaldi + atlas.

[nnet3-valgrind.out.gz](https://github.com/kaldi-asr/kaldi/files/725141/nnet3-valgrind.out.gz)

[nnet-valgrind.out.gz](https://github.com/kaldi-asr/kaldi/files/725142/nnet-valgrind.out.gz)

**Comment by danpovey** [comment]
It looks to me most likely (almost certain) that your problems are
GridEngine related, possibly you or your sysadmins have configured your
GridEngine to kill jobs if they exceed memory or time limits.  You may find
something in the system logs or the Gridengine logs on the machine.

I'll check the valgrind stuff on our machines at some point in the future,
it's unrelated.  Your problem is 100% not an issue with the jobs crashing,
it would not manifest itself in that way.

Dan

**Comment by danpovey** [comment]
You can check the gridengine logs like this:

root@a04:/root# tail /var/spool/gridengine/execd/a04/messages 
01/23/2017 17:24:12|  main|a04|W|reaping job "4799855.14" PTF complains: Job does not exist
01/23/2017 17:33:38|  main|a04|E|removing unreferenced job 4799962.23 without job report from ptf
01/23/2017 17:34:26|  main|a04|E|removing unreferenced job 4800056.12 without job report from ptf
01/23/2017 17:35:15|  main|a04|W|reaping job "4800056.5" PTF complains: Job does not exist
01/23/2017 17:37:39|  main|a04|W|reaping job "4799962.62" PTF complains: Job does not exist
01/23/2017 17:37:39|  main|a04|E|removing unreferenced job 4799961.44 without job report from ptf
01/23/2017 17:38:54|  main|a04|E|removing unreferenced job 4800106.63 without job report from ptf

**Comment by weegreenblobbie** [comment]
Thanks for the pointer, I'll take a look at our grid and possible killing large memory jobs...

**Comment by danpovey** [comment]
BTW, if you do

qconf -sc | grep h_vmem

h_vmem              h_vmem      MEMORY      <=    YES         NO         0
      0


and it says YES where my line says NO, that means your grid has been
configured to strictly enforce memory requirements.  It will require a lot
of messing around to get Kaldi jobs to run in this environment without
being killed, because you need to get the memory requirements exact.
You'll want to create a file conf/queue.conf and configure the --mem option
to set the h_vmem option in that case (see
http://kaldi-asr.org/doc/queue.html), but you may need to specify larger
than normal values to --mem in your cmd.sh in train_cmd, decode_cmd etc.,
to avoid the hard limit.


Dan

**Comment by weegreenblobbie** [comment]
```
qconf -sc | grep h_vmem
h_vmem              h_vmem      MEMORY    <=    YES         NO         0        0
```

I was using --mem 4G.  I'll keep you posted.

**Comment by danpovey** [comment]
OK then check the GridEngine logs on the machine where it ran, and the
system logs (tail /var/log/messages or dmesg or journalctl -r).

Or it could be disk full or NFS problems, e.g. it couldn't write because
disk was full or nfs was stuck (dmesg would show errors if nfs had been
stuck).

do "df" to see if disk is full.

**Comment by weegreenblobbie** [comment]
```
df -h | grep -E "Filesystem|/export/shared"
Filesystem            Size  Used Avail Use% Mounted on
nas02:/export/shared   45T   37T  8.0T  83% /shared
```

Getting our IT to help me get access to the grid logs ...

Again, thanks for the help!

**Comment by weegreenblobbie** [comment]
My training step completed without any crashes.  The only change I made was linking kaldi with libatlas instead of openblas.  So the problem seems to be the combination of kaldi+openblas-0.2.19.

Thanks for your help.

**Comment by danpovey** [comment]
OK, but if the Kaldi binaries had crashed you'd have seen the status
reported in the logs.  It was definitely either a GridEngine or disk-full
issue.

**Comment by weegreenblobbie** [comment]
I'm not saying the issue I ran into is kaldi, the invalid read could be a bug in openblas 0.2.19, but I've got a working kaldi build (so far) so i'm not going to debug any deeper unless I hit another snag.

Runing valgrind on the matrix unittest exposed invalid reads, when I switched to atlas, no errors.

Reading invalid memory may cause a program to do anything, taking unpredictable paths through the code.  it may be harmless for many iteration because the invalid data may harmless in the context of read, some time later however, some real data was written to the location and then the invalid read causes a program to error out.  It has been my experience that when a random program on a random host errors out, and it's not predictable, invalid pointer reads/writes is the cause.

When I first built openblas, it selected my laptop's cpu arch, when I deployed to my cluster, the cpu arch mismatched.  No error showed up in any logs, just that feature extraction started and exited very quickly without any error messages except that no features were extracted.  I was only able to figure out the problem by removing some of the program chaining, and eventually an "Illegal Instruction" showed up in the logs.  I deduced an openblas problem, rebuilt and it went away.

I doubt you have time to investigate this either.  I'll stick with atlas.

**Comment by danpovey** [comment]
Invalid reads past the end of blocks of allocated memory are a known issue
with some matrix libraries, but they tend to be harmless (sometimes they
generate NaN's in that case we'd report it upstream).  They tend not to
cross page boundaries [so wouldn't cause segmentation faults].   Even if
they are not harmless, my point about the logs was that you wouldn't just
see a truncated log like what you saw; you'd see queue.pl saying what the
exit status of the program was.

**Comment by weegreenblobbie** [comment]
Oh, that's new information to me :).  From above, are you referring to the exit status of 256?

**Comment by danpovey** [comment]
No, I'm not talking about the exit status of qstat, I mean in the log file
there should be a final line reporting the status, but qstat said the log
file ended like this:

fmllr[5.0.9~1448-5f15d]:main():gmm-est-fmllr.cc:143) For speaker
fe_03_04117-B, auxf-impr from fMLLR is 0.0462073, over 18604 frames.

That looks like a job that was killed in the middle.  Of course, it could
be that if you were to look at the file now you would see a final line
reporting the status (this would point to issues with NFS
freshness/delays).  But if the log just stops in the middle, it means the
job was killed by GridEngine (or the file system was full).


Dan

**Comment by weegreenblobbie** [comment]
Ahhh, I see, that makes perfect sense.  So then I should make sure our grid logs the fact that a job is killed because it hit a run-time limit or memory limit.

Thanks!
