### ISSUE TITLE
Change how the --frame argument is chosen in TDNN training.

### ISSUE THREAD

**Issue by danpovey** [kaldi-asr/kaldi#1370]
This is for @LvHang (please ask @vimalmanohar and @freewym for help as needed),

I'll illustrate the issue here with reference to `train_tdnn.sh`, but the code I want
changed is the python-script version of the code, as called by train_dnn.py.

The --frame option controls which of the (e.g. 8) supervised frames in an eg is chosen to train on.
currently it's chosen as follows:
```
        archive=$[($k%$num_archives)+1]; # work out the 1-based archive index.                                                                                        
        frame=$[(($k/$num_archives)%$frames_per_eg)]; # work out the 0-based frame                                                                                    
 ```
If we define one sub-epoch at the time it takes to process all the archives, then that means that for the 1st sub-epoch we use frame 0, for the 2nd sub-epoch we use frame 1, and so on.
The problem here is that for big data, a sub-epoch might be quite long, and there may be certain pdfs that only occur at the very start/end of a file.  These will learn rather biased likelihoods.

What would be better is to change it to the equivalent of:
```
        archive=$[(k%num_archives)+1]; # work out the 1-based archive index.                                                                                        
        frame=$[((k/num_archives+archive)%frames_per_eg)]; # work out the 0-based frame                                                                                    
```
(note: I removed the dollar signs as they are not needed inside `$[..]` expressions.. anyway you'll be changing the python version of the script).

Please test this in the 'shortcut' branch on, say, the tedlium s5_r2 nnet3 TDNNs (not chain- it has to be with train_dnn.py).
This may make zero difference but we should test it anyway and I will probably merge it even if it makes no difference.

**Comment by LvHang** [comment]
Thanks. Get it.

**Comment by kkm000** [comment]
Done in #1389
