### ISSUE TITLE
[scripts] chain TDNN training: Python AttributeError in train.py

### ISSUE THREAD

**Issue by entn-at** [kaldi-asr/kaldi#1375]
Using latest Kaldi version (git sha1 hash f42b3ced09eecacdc037628ed06b05f91ef96c36).

When running the default chain TDNN model training script (local/chain/run_tdnn.sh) in swbd, the following error occurs in step 13 (within steps/nnet3/chain/train.py):

```
~/code/kaldi/egs/swbd/s5c$ bash local/chain/run_tdnn.sh
local/chain/run_tdnn.sh
Traceback (most recent call last):
  File "steps/nnet3/chain/train.py", line 19, in <module>
    import libs.nnet3.train.common as common_train_lib
  File "steps/libs/nnet3/train/__init__.py", line 13, in <module>
    import common
  File "steps/libs/nnet3/train/common.py", line 20, in <module>
    import libs.nnet3.train.dropout_schedule as dropout_schedule
AttributeError: 'module' object has no attribute 'train'
```

I cleared exp/chain (rm -rf exp/chain) before to make sure it's not caused by leftover files from previous runs. The script (train.py) ran fine before on the same machine (same installation) with the same data etc. before commit 61510ca0d8d9b38096701227ee064a166816fcbe.

**Comment by danpovey** [comment]
I can reproduce the problem but I don't understand enough about python
imports to fix it. @vimal-manohar, @vijaditya?

**Comment by vijayaditya** [comment]
I faced a similar problem yesterday. I thought of working on it today. I
think it is basically an issue in writing the __init__.py files of the
library. We would have to import the newly added modules in this file.

I will get to this later today, unless @vimal deals with it in the mean
time.

--Vijay

**Comment by danpovey** [comment]
I tried changing  steps/libs/nnet3/train/__init__.py to:

import common, dropout_schedule


__all__ = ["common", "dropout_schedule"]


but this didn't help

**Comment by entn-at** [comment]
I just got it to work. in steps/libs/nnet3/train/common.py on line 20 change

import libs.nnet3.train.dropout_schedule as dropout_schedule

to:

from libs.nnet3.train import dropout_schedule

This seems to take care of the issue, the script is now running fine preparing egs.
Thanks for the hints!

**Comment by danpovey** [comment]
I also found that deleting the line

import common
from steps/libs/nnet3/train/__init.py
fixes the immediate problem.
but I'm not sure if this would have other effects; and I'm not sure if
your approach would actually work with the real dropout code.

Dan

**Comment by danpovey** [comment]
I removed the statements


import common


__all__ = ["common"]

from the __init__.py in steps/libs/nnet3/train/, and it resolved the
problem for me.
I think that is the right fix, and I pushed the change.  I believe all
of those statements in __init__.py files in those subdirectories are
unnecessary.  But I don't know 100% so I'm not touching the others.

I think the issue was that it hadn't finished setting up the 'train'
module because it was still importing it, it was in the __init__.py's
import statement.
I haven't seen examples online where people put those kinds of
statements  (import foo) in __init__.py, it might not be needed at
all.

**Comment by vijayaditya** [comment]
I think the problem might be a circular import. Package libs.nnet3.train
was importing common which was again importing the package libs.nnet3.train.

Reading
https://docs.python.org/2/tutorial/modules.html#importing-from-a-package

I see that the "import common" is not necessary in
steps/libs/nnet3/train/__init_.py.

It can just have the line

__all__ = ["dropout_schedule", "common"]

The use of __all__ doesn't seem to be necessary now, however it  a good
thing to have to avoid issues when using "from .... import .... *"
statements.

Anyway the only change necessary is to remove
"import common" from steps/libs/nnet3/train/__init_.py , to avoid a
circular import.
