### ISSUE TITLE
usage of mktemp in base/get_version.sh and doc/get_version.sh does not work on OS X 10.10

### ISSUE THREAD

**Issue by andrely** [kaldi-asr/kaldi#1376]
OSX mktemp seems to need the -t <pattern> flag.

**Comment by danpovey** [comment]
It's working for me on el capitan:

mac:src: mktemp

/var/folders/sx/8w93_q_s09xdz864gb_ycnbr0000gn/T/tmp.Ba2ztmnw


I think it's the -d option that's problematic on mac.

Can you be more precise about what you observed?

**Comment by andrely** [comment]
I think this may be a 10.10 and earlier issue. 

My mktemp is in /usr/bin/mktemp 
mktemp -t tmp seems to produce the same result as gnu mktemp

To reproduce:

run ./configure in src
then running make depend ends in error:

$ make depend
/Applications/Xcode.app/Contents/Developer/usr/bin/make -C base/ depend
usage: mktemp [-d] [-q] [-t prefix] [-u] template ...
       mktemp [-d] [-q] [-u] -t prefix 
Makefile:11: *** .  Stop.
make: *** [base/depend] Error 2

I changed base/get_version.sh and doc/get_version.sh to use mktemp from gnu coreutils instead in order to build.

**Comment by danpovey** [comment]
I think we would have encountered this earlier if it was what you say.
Run /usr/bin/mktemp without arguments and see what it does.
It was alway the -d option that was a problem, requires a template.
The -t option apparently has a different meaning GNU vs mac.
(
http://unix.stackexchange.com/questions/30091/fix-or-alternative-for-mktemp-in-os-x
)

**Comment by danpovey** [comment]
Actually, according to the man page on mac for 'mktemp' you are right -> maybe they silently extended it, or maybe some installer has overwritten the system one in my build.
I just pushed a fix by adding the template (mktemp /tmp/temp.XXXXXX).
