### ISSUE TITLE
New CUDA code needed for dropout with fast LSTM

### ISSUE THREAD

**Issue by danpovey** [kaldi-asr/kaldi#1382]
@kangshiyin, I hope you can help with this (after the Chinese holidays finish, anyway)..
We want to implement a scheme similar to what @GaofengCheng did for regular LSTMs,
in the fast-LSTM setup that includes a NonlinearComponent.  The setup that worked
best for him had per-frame masks on the 'i' and 'f' quantities, i.e. where we had
```
                    i_t = Sigmoid(i_part + w_{ic}*c_{t-1})                                                                                                            
                     f_t = Sigmoid(f_part + w_{fc}*c_{t-1})        
```
we will now want to multiply i_t and f_t by random dropout masks (but different masks for i and f).
These dropout masks will be *per frame*.  The way this can be implemented is to add two
columns to the input of `*ComputeLstmNonlinearity*`, where the two columns will be the
scaling factors for i_t and f_t.  So it will be able to deal with input of dimension 5 * cell_dim + 2,
instead of just input of 5 * cell_dim.  It should be optional at the level of the `*ComputeLstmNonlinearity*` functions, so the code will still work with the old
input; but it would probably make sense to have two versions of the kernels.  
The component will need an extra boolean configuration value (e.g. use-dropout), which will tell it to expect the larger-dimensional input.  But we can deal with the component-level changes.

In the backprop you don't have to compute the derivatives w.r.t. the scaling factors; just leave them undefined, we will later ignore them.  Computing those derivatives would require an expensive tree-sum and would need extra temporary memory, and we don't need them.

I will later create a suitable component which can create these dropout masks.

This PR should be against the 'shortcut' branch.

**Comment by kangshiyin** [comment]
Sure. I will take a look later this week.
