### ISSUE TITLE
get_dropout_edit_string() should be called from common_train_lib

### ISSUE THREAD

**Issue by alumae** [kaldi-asr/kaldi#1390]
A recent commit makes in a number of places the following call:

`common_lib.get_dropout_edit_string(..)`

This results in an error:
```
Traceback (most recent call last):
  File "steps/nnet3/chain/train.py", line 528, in main
    train(args, run_opts, background_process_handler)
  File "steps/nnet3/chain/train.py", line 436, in train
    dropout_edit_string=common_lib.get_dropout_edit_string(
AttributeError: 'module' object has no attribute 'get_dropout_edit_string'
```

Replacing the call with a reference to `common_train_lib.get_dropout_edit_string(..)` fixes the problem.

I can make a PR but I believe it's easier to fix for @vimalmanohar who committed the initial code.

**Comment by migueljette** [comment]
Thank you for posting this @alumae! You're saving me a lot of poking around! :)

**Comment by danpovey** [comment]
Fixed now.  Thanks!
We need to do what @vdp suggested, which is to create some kind of testing setup that will run the nnet training scripts (in small versions) and let us know if something breaks.  I haven't had the time to set this up.  First step is to modify one of the smaller recipes [or a data-subset of some recipe] to use the nnet scripts (even if results are poor, just for testing purposes).
