### ISSUE TITLE
cannot find types.h

### ISSUE THREAD

**Issue by chris-hawley** [kaldi-asr/kaldi#1396]
I get 643 errors saying "Cannot open include file: 'fst/types.h': No such file or directory" 

I checked my include directories and they seem to be setup correctly and follow the instructions provided in windows/install.md

**Comment by jtrmal** [comment]
the openfst include paths are not set up correctly. You can also check if that file does exist (just in case something bad happened).
Did you really change the content of the file variable.props, i.e. step 12? 
I had a report from another guy two weeks ago that everything works all right.

**Comment by chris-hawley** [comment]
i did change my paths but i'm pretty sure i changed them the wrong way. Below is what i have. 
`<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="4.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <ImportGroup Label="PropertySheets" />
  <PropertyGroup Label="UserMacros">
    <MKLDIR>C:\Program Files (x86)\Intel\Composer XE\mkl</MKLDIR>
    <OPENBLASDIR>C:\Users\Yenda\Downloads\kaldi-svn\tools\OpenBLAS-v0.2.14-Win64-int32</OPENBLASDIR>
    <PTHREADW>C:\Users\Yenda\Downloads\kaldi-svn\tools\pthread-win32\Pre-built.2</PTHREADW>
    <OPENFST>C:\Users\Yenda\Downloads\kaldi-svn\tools\openfstwin-1.3.4\</OPENFST>
    <OPENFSTLIB>C:\Users\Yenda\Downloads\kaldi-svn\tools\openfstwin-1.3.4\MSVC12\x64\</OPENFSTLIB>
  </PropertyGroup>
  <PropertyGroup />
  <ItemDefinitionGroup />
  <ItemGroup>
    <BuildMacro Include="OPENBLASDIR">
      <Value>C:\Users\chris\Desktop\kaldi\tools\OpenBLAS</Value>
      <EnvironmentVariable>true</EnvironmentVariable>
    </BuildMacro>
    <BuildMacro Include="PTHREADW">
      <Value>C:\Users\chris\Desktop\kaldi\tools\pthreads</Value>
      <EnvironmentVariable>true</EnvironmentVariable>
    </BuildMacro>
    <BuildMacro Include="OPENFST">
      <Value>C:\Users\chris\Desktop\kaldi\tools\openfst</Value>
      <EnvironmentVariable>true</EnvironmentVariable>
    </BuildMacro>
    <BuildMacro Include="OPENFSTLIB">
      <Value>C:\Users\chris\Desktop\kaldi\tools\openfst\MSVC14\x64a</Value>
      <EnvironmentVariable>true</EnvironmentVariable>
    </BuildMacro>
    <BuildMacro Include="MKLDIR">
      <Value>$(MKLDIR)</Value>
      <EnvironmentVariable>true</EnvironmentVariable>
    </BuildMacro>
  </ItemGroup>
</Project>
`

**Comment by jtrmal** [comment]
you were supposed to change the paths in the "UserMacros" section.
That part defines variables that are used then all across the visual studio solution. that is the reason it does not work.

**Comment by jtrmal** [comment]
i.e. instead of 
```
 <PropertyGroup Label="UserMacros">
    <MKLDIR>C:\Program Files (x86)\Intel\Composer XE\mkl</MKLDIR>
    <OPENBLASDIR>C:\Users\Yenda\Downloads\kaldi-svn\tools\OpenBLAS-v0.2.14-Win64-int32</OPENBLASDIR>
    <PTHREADW>C:\Users\Yenda\Downloads\kaldi-svn\tools\pthread-win32\Pre-built.2</PTHREADW>
    <OPENFST>C:\Users\Yenda\Downloads\kaldi-svn\tools\openfstwin-1.3.4\</OPENFST>
    <OPENFSTLIB>C:\Users\Yenda\Downloads\kaldi-svn\tools\openfstwin-1.3.4\MSVC12\x64\</OPENFSTLIB>
  </PropertyGroup>
```
you should have
```
 <PropertyGroup Label="UserMacros">
    <MKLDIR>C:\Program Files (x86)\Intel\Composer XE\mkl</MKLDIR>
    <OPENBLASDIR>C:\Users\chris\Desktop\kaldi\tools\OpenBLAS</OPENBLASDIR>
    <PTHREADW>C:\Users\chris\Desktop\kaldi\tools\pthreads</PTHREADW>
    <OPENFST>C:\Users\chris\Desktop\kaldi\tools\openfst\</OPENFST>
    <OPENFSTLIB>C:\Users\chris\Desktop\kaldi\tools\openfst\MSVC14\x64a\</OPENFSTLIB>
  </PropertyGroup>
```
or something along those lines -- also make sure the path "C:\Users\chris\Desktop\kaldi\tools\openfst\MSVC14\x64a" is valid -- I haven't seen it yet with the 'a' suffix

**Comment by chris-hawley** [comment]
Also, i hit a build error after correcting the above. kaldi\src\base\get_version.sh wasn't ran so kaldi-base failed to build.

**Comment by danpovey** [comment]
That think with get_version.sh was an expected problem.
We should have the perl script create that file directly (dangerous to call
the shell file on Windows, probably wouldn't work).  It can just contain
the basic version number from src/.version.    E.g. it can just contain

#define KALDI_VERSION "5.0"

assuming src/.version contains 5.0.  Do you have time to do this and make a
pull request?

**Comment by jtrmal** [comment]
yes, that is an unresolved issue, but I don't really have time to spend on that now. 
create a file "base/version.h" containing the following:
```
// This file was automatically created by ./get_version.sh.
// It is only included by ./kaldi-error.cc.
#define KALDI_VERSION "5.0.142-13612-windows"
#define KALDI_GIT_HEAD "136120ad834a5bcc794a13689f8dee024f3c1ba9"
```

**Comment by jtrmal** [comment]
hm, maybe perl script might be the easiest option at least for now to make
it build. I'll try to get something done today.
y.

**Comment by danpovey** [comment]
Yenda, it's best it he does what I suggested, with KALDI_VERSION only, and
only the major.minor version.  the git thing is not needed right now.

**Comment by jtrmal** [comment]
Also, I'm reopening it as it might actually take longer to address this.

**Comment by jtrmal** [comment]
@chris-hawley , did you manage to go through the whole compilation?

**Comment by chris-hawley** [comment]
i got through the whole compilation but I ran the listed step manually. If a fix needs to be tested, I can try it.

**Comment by jtrmal** [comment]
ok, great. basicaly the only things that has to be tried is to run the
script get_version.pl inside the windows/ directory (preferably in the
shell) and tell us if you see any issues -- ideally, the script should not
output anything and the file src/base/version.h should contain onlu single
line saying
```
KALDI_WERSION=5.0-win
```
or similar. You should backup your version.h before you run it just to save
time -- the change of this file would essentially force complete
recompilation of kaldi.
y.

**Comment by jtrmal** [comment]
Closing again. We got reports it works now.
