### ISSUE TITLE
find: `/home/kaldi/tools/sequitur-g2p/lib64': No such file or directory

### ISSUE THREAD

**Issue by 15mscsmirfan** [kaldi-asr/kaldi#1413]
after installing the sequitur when I run the voxforge example it shows the error.
```
find: `/home/kaldi/tools/sequitur-g2p/lib64': No such file or directory
```
Although directory exists. I also checked that the install_sequitur.sh have the configuration as

```
echo "export SEQUITUR=$wd/sequitur"
echo "export PATH=\$PATH:\${SEQUITUR}/bin"
echo "_site_packages=\`readlink -f \${SEQUITUR}/lib/python*/site-packages\`"
echo "export PYTHONPATH=\$PYTHONPATH:\$_site_packages"
```

but it after installing it creates 

`kaldi/tools/sequitur-g2p/lib64`

I also have changed the **env.sh**  for sequitur-g2p to

```
export SEQUITUR=/state/partition1/home3/seecs/m.irfan15/kaldi/tools/sequitur-g2p
export PATH=$PATH:${SEQUITUR}/bin
_site_packages=`find ${SEQUITUR}/lib64 -type d -regex '.*python.*/site-packages'`

```
but still getting the same issue.

I'm using CentOS 6.5.

**Comment by jtrmal** [comment]
that recipe does not even use "find" in connection with the sequitur.
are you sure the primary problem wasn't something else and you created this
problem by fixing the primary issue?
y.

**Comment by jtrmal** [comment]
I'm closing this as there wasn;t any follow-up and the whole issue does not seem to be really related to the stock kaldi
