### ISSUE TITLE
WSJ speed perturbing

### ISSUE THREAD

**Issue by danpovey** [kaldi-asr/kaldi#1442]
I just noticed that local/nnet3/run_ivector_common.sh in the WSJ setup does not have speed perturbing.
This may be one reason that our nnet3 setup did not work so great in WSJ, and why the chain models were not better than regular models.
I'm considering just rewriting that script and invalidating the existing scripts there.
I'm not sure whether to ask someone to help with this.

**Comment by north1024** [comment]
About speed perturbing, how much improvement  in the swbd?

**Comment by north1024** [comment]
There is sp, the WER is 12.1%(tdnn). If there is not sp, what is WER?

Thanks.

**Comment by danpovey** [comment]
I don't recall exactly, but I'd expect about 0.8% to 1.0% absolute.
