### ISSUE TITLE
The result of online i-vector is better than offline i-vector in kaldi nnet3 model

### ISSUE THREAD

**Issue by huangjun0413** [kaldi-asr/kaldi#1450]
I do experiment in kaldi nnet3 and find  the result of TDNN+ offline i-vector(Sentence level) is better than the result of TDNN+ online i-vector. Is it reasonable?

**Comment by danpovey** [comment]
That is expected.

**Comment by north1024** [comment]
But in the SWBD, our experiments show that the performance of TDNN+ online i-vector is better than TDNN+ offline i-vector(Sentence level). What's happen about this phenomenon? Comparing TDNN+ online i-vector and TDNN+ offline i-vector(Sentence level), which is better?

**Comment by danpovey** [comment]
Firstly, by sentence level I guess you guys mean utterance level.
In general offline per-speaker iVectors should be better, then online
per-speaker, then offline per-utterance, then online-per-utterance should
be worst.
In general, the more data you have to estimate the iVector, the better it
is (assuming the data is well matched).
