### ISSUE TITLE
fix_data_dir.sh: no utterances remained: not proceeding further.

### ISSUE THREAD

**Issue by north1024** [kaldi-asr/kaldi#1454]
Directory with transcriptions exists, skipping downloading
patching file data/local/dict_nosp/lexicon0.txt
Prepared input dictionary and phone-sets for Switchboard phase 1.
Switchboard-1 data preparation succeeded.
utils/fix_data_dir.sh: filtered data/train/segments from 264333 to 0 lines based on filter /tmp/kaldi.Taip/recordings.
utils/fix_data_dir.sh: filtered data/train/wav.scp from 4870 to 0 lines based on filter /tmp/kaldi.Taip/recordings.
utils/fix_data_dir.sh: filtered data/train/reco2file_and_channel from 4870 to 0 lines based on filter /tmp/kaldi.Taip/recordings.
fix_data_dir.sh: no utterances remained: not proceeding further.

What's happen about this?

Thanks.

**Comment by danpovey** [comment]
maybe your /tmp directory is full.
