### ISSUE TITLE
fix_data_dir.sh doesn't do anything

### ISSUE THREAD

**Issue by nizmagu** [kaldi-asr/kaldi#1460]
After updating to the latest commit, when running `utils/fix_data_dir.sh data/train`, nothing happens.

`data/train/text` had 5229 utts and `data/train/utt2spk` had 6000 utts before running fix_data_dir.sh.
It printed nothing to stderr or stdout, and data/train remained the same after running, causing make_mfcc.sh to exit.

**Comment by nizmagu** [comment]
My data is encoded in UTF-8, and it seems to have something wrong with it, because it works fine on a similar data folder. However, I don't see any problem with it.

**Comment by danpovey** [comment]
You could change the
#!/bin/bash
at the top of fix_data_dir.sh to say
#!/bin/bash -x
so it will print lines as it goes, this may show which part is failing.
