### ISSUE TITLE
Openfstwin 1.6.1 does not exist

### ISSUE THREAD

**Issue by yuvalkry-si** [kaldi-asr/kaldi#1463]
Hello,

  The instructions for installing under windows refer to an old version of openfst-win: 1.3.4 
  and to a patch for that version - which does not exist anymore. 

  I tried:
   - Compiling with the newer openfstwin-1.4.1
   - Copying the patch from the fork of jtrmal and applying it.
 
Both ways resulted in compile errors for fst-related function definitions.

 So, I suppose the C++ code is modified for the newest openfst-1.6.1 but there
 is no corresponding version of openfstwin .

 How, then to settle the disagreement and compile for Windows?

     Thank you,
          Yuval

**Comment by jtrmal** [comment]
I didn't have the chance to look into it carefully, but it seems there is none for now.
You can checkout the 5.0 branch of kaldi (https://github.com/kaldi-asr/kaldi/tree/5.0) 
which will work with the older versions of openfstwin

I might have some time to look into the openfst on windows this weekend, more probably at the end of March.

**Comment by yuvalkry-si** [comment]
Thanks you,
    Yuval

2017-02-28 14:31 GMT+02:00 jtrmal <notifications@github.com>:

**Comment by kkm000** [comment]
[OpenFST 1.6 that compiles on Windows](https://github.com/kkm000/openfst/tree/win/1.6) with MS compiler, [changes](https://github.com/kkm000/openfst/compare/orig/1.6...win/1.6).
