### ISSUE TITLE
Build hangs on cygwin (64-bit version) while configuring sctk

### ISSUE THREAD

**Issue by jh3141** [kaldi-asr/kaldi#1469]
Left a cygwin build running for several hours, and found that it had got stuck during the configure phase for sctk.  It seems the configure process creates a "config.status" file, but then fails to terminate.

Example transcript:

> admin@tmp /cygdrive/f/kaldi/kaldi-trunk/tools/sctk
$ make config
(mkdir -p bin)
(cd src; make config)
make[1]: Entering directory '/cygdrive/f/kaldi/kaldi-trunk/tools/sctk-2.4.10/src'
(cd asclite; make config)
make[2]: Entering directory '/cygdrive/f/kaldi/kaldi-trunk/tools/sctk-2.4.10/src/asclite'
(cd core; sh config.sh -prefix=`cd ../../..; pwd`)
checking for g++... g++
checking for C++ compiler default output file name... a.exe
checking whether the C++ compiler works... yes
checking whether we are cross compiling... no
checking for suffix of executables... .exe
checking for suffix of object files... o
checking whether we are using the GNU C++ compiler... yes
checking whether g++ accepts -g... yes
checking whether make sets $(MAKE)... yes
checking for gcc... gcc
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ANSI C... none needed
checking for main in -lm... yes
checking how to run the C preprocessor... gcc -E
checking for egrep... grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking for unistd.h... (cached) yes
checking for string.h... (cached) yes
checking iostream usability... no
checking iostream presence... no
checking for iostream... no
checking ostream usability... no
checking ostream presence... no
checking for ostream... no
checking fstream usability... no
checking fstream presence... no
checking for fstream... no
checking iomanip usability... no
checking iomanip presence... no
checking for iomanip... no
checking map usability... no
checking map presence... no
checking for map... no
checking stdio.h usability... yes
checking stdio.h presence... yes
checking for stdio.h... yes
checking for stdlib.h... (cached) yes
checking math.h usability... yes
checking math.h presence... yes
checking for math.h... yes
checking time.h usability... yes
checking time.h presence... yes
checking for time.h... yes
checking list usability... no
checking list presence... no
checking for list... no
checking vector usability... no
checking vector presence... no
checking for vector... no
checking set usability... no
checking set presence... no
checking for set... no
checking assert.h usability... yes
checking assert.h presence... yes
checking for assert.h... yes
checking sstream usability... no
checking sstream presence... no
checking for sstream... no
checking float.h usability... yes
checking float.h presence... yes
checking for float.h... yes
checking limits.h usability... yes
checking limits.h presence... yes
checking for limits.h... yes
checking for an ANSI C-conforming const... yes
checking for size_t... yes
checking for install... /usr/bin/install
config.sh: creating ./config.status

**Comment by danpovey** [comment]
I think this problem will be very hard for us to reproduce, plus it's not an issue with Kaldi per se.  sctk and sclite scoring is not needed for most setups.  So just do "make -k" in tools/ and ignore the error.  For how to ask questions, see kaldi-asr.org/forums.html.
