### ISSUE TITLE
Demo from this project

### ISSUE THREAD

**Issue by blaisexen** [kaldi-asr/kaldi#1473]
Hi,
Where can we download a demo from this project?

What this project can do?

We are using desktop windows.

I'm just new on this name "Kaldi"

**Comment by danpovey** [comment]
it's something for speech recognition professionals.  if you don't already know, it's not for you.

**Comment by blaisexen** [comment]
No! I'm just asking a DEMO,

because many of the Contributors write something like this but nothing has been seen to be used by many!

a DEMO please! a Video from youtube that is surely from this contribution?
