### ISSUE TITLE
fix how KALDI_DOUBLEPRECISION is interrogated

### ISSUE THREAD

**Issue by danpovey** [kaldi-asr/kaldi#1481]
we test
#if (KALDI_DOUBLEPRECISION != 0)
and it would probably be better to do
#if defined(KALDI_DOUBLEPRECISION) && KALDI_DOUBLEPRECISION == 1

[assuming the preprocessor lets you do that for things that may not be defined].

the Makefile always defines it to 0 or 1, but people may mistakenly omit it, and we want it to default to 0.

in the longer term we should be looking towards doing this stuff via a config.h, which is less error prone.

@dogancan, do you have time?

**Comment by danpovey** [comment]
Actually, this may not need action after all, it turns out
http://stackoverflow.com/questions/5085392/what-is-the-value-of-an-undefined-constant-used-in-if
that undefined value default to 0.

**Comment by jtrmal** [comment]
I think we were already discussing this (or perhaps it's only I was looking into this) some time ago but I remember the same conclusion -- it is ok to leave it as it is.
y.
