### ISSUE TITLE
Tridiagonalizing matrix that is too large or has NaNs

### ISSUE THREAD

**Issue by YichiHuang** [kaldi-asr/kaldi#1482]
Hi,
I run the egs/sre10/v2
I run the sid/init_full_ubm_from_dnn.sh, error occured in the exp/full_ubm/log/init.log.
`ASSERTION FAILED (fgmm-global-init-from-accs:HouseBackward():qr.cc:124)" 'KALDI_ISFINITE(sigma)'"Tridiagonalizing matrix that is too large or has NaNs"
[Stack-Trace: ]
fgmm-global-init-from-accs() [0x5309c]
......`

**Comment by danpovey** [comment]
Hm, I don't think we've seen that before.  Most likely some NaN's somehow
got into your posteriors or features.  What I would do is add some checks
in the accumulation code (fgmm-global-acc-stats or whatever it's called),
to compute the sum of the input matrices and check it's not NaN (you can
check that x == x).  That at least will show where they are appearing.
E.g. maybe you are using GPUs without memory checking and it comes from the
hardware.  Or maybe you changed the script somehow.

Dan
