### ISSUE TITLE
transcripts-to-fsts does not handle missing cost specifier

### ISSUE THREAD

**Issue by yuvalkry-si** [kaldi-asr/kaldi#1485]
Hello,

  I am trying to run the KWS processing from wsj/s5/run.sh .

  The script local/kws_data_prep.sh contains this call to transcripts-to-fsts:

    # Compile keywords into FSTs
    transcripts-to-fsts ark:$kwsdatadir/keywords.int ark:$kwsdatadir/keywords.fsts

  whic results in an error message:

  ERROR (transcripts-to-fsts[5.1]:CheckImpl():util/kaldi-table-inl.h:2608) Trying to use empty RandomAccessTableReader (perhaps you passed the empty string as an argument to a program?)

  There are several calls to  transcripts-to-fsts with two arguments in the egs/ directory,
  mostly in babel.

  I am not very familiar with Kaldi's code but looking at kwsbin/transcripts-to-fsts.cc 
  maybe it should check that costs_rspecifier is not null when creating the costs reader?

    if ( po.NumArgs() == 2 ) {
      transcript_rspecifier  = po.GetArg(1);
      fst_wspecifier = po.GetArg(2);
    } else {
      transcript_rspecifier  = po.GetArg(1);
      costs_rspecifier = po.GetArg(2);
      fst_wspecifier = po.GetArg(3);
    }

    SequentialInt32VectorReader transcript_reader(transcript_rspecifier);
    RandomAccessDoubleReader costs_reader(costs_rspecifier);  <----------- Here
    TableWriter<VectorFstHolder> fst_writer(fst_wspecifier);

    Yuval

**Comment by jtrmal** [comment]
IIRC,  I fixed this a couple of days back.  Do you have uptodate kaldi?
Y.

**Comment by yuvalkry-si** [comment]
Oh, I see, you added the check "costs_reader.IsOpen()" and I haven't look there.
Sorry.
