### ISSUE TITLE
Try using ConstFst to reduce memory consumption in decoding

### ISSUE THREAD

**Issue by danpovey** [kaldi-asr/kaldi#1486]
Can someone (e.g. @LvHang) please look into whether reading Fsts as ConstFst instead of VectorFst for decoding leads to a substantial improvement in memory consumption?  ConstFst stores the vectors and arcs as one array so should be better for memory.  You can change any of the *-latgen-faster programs.

This may require writing a new version of ReadFstKaldi, e.g. add ReadConstFstKaldi.

**Comment by LvHang** [comment]
ok, thanks, let me deal with it.

**Comment by danpovey** [comment]
resolved with #1661
