### ISSUE TITLE
Fix compile problem in OpenFst

### ISSUE THREAD

**Issue by danpovey** [kaldi-asr/kaldi#1489]
@jtrmal or @dogancan  I wonder if either of you has time to set up a patch for OpenFst 1.6.1 to fix this error:

./../include/fst/shortest-path.h: In function 'void fst::internal::SingleShortestPathBacktrace(const fst::Fst<Arc>&, fst::MutableFst<Arc>*, const std::vector<std::pair<typename Arc::StateId, long unsigned int> >&, typename Arc::StateId)':
./../include/fst/shortest-path.h:77:8: error: inconsistent deduction for 'auto': 'auto' and then 'int'
   for (auto state = f_parent, d = kNoStateId; state != kNoStateId;
        ^~~~
1.6.1'

.. which is a compiler error, but it's probably very unnecessary to declare 2 variables in the same auto statement (one could be declared out of the loop).  So it would be nice to fix this via a patch.
You might have to go back to the old Makefiles and see how we used to apply those patches.

**Comment by danpovey** [comment]
Actually the easiest fix is to replace 'auto' on that line with: 'typename Arc::StateId'.

**Comment by jtrmal** [comment]
All right, I will do it.
y.

**Comment by jtrmal** [comment]
being addresed in #1490
