### ISSUE TITLE
nnet1 -> nnet2

### ISSUE THREAD

**Issue by hchen1024** [kaldi-asr/kaldi#1495]
I want to concatenate two networks, the one is DNN from nnet1, the another one is tdnn from nnet2, firstly I convert DNN (nnet1) to DNN (nnet2) by using src/nnet2bin/nnet1-to-raw-nnet, then the two networks (dnn_nnet2, tdnn_nnet2) are concatenated by using src/nnet2bin/raw-nnet-concat. About this process, are there some problems? 

Thanks.

**Comment by vesis84** [comment]
Hi, this sounds as a doable approach. K.
