### ISSUE TITLE
Modify alignment programs to be able to output per-frame acoustic costs

### ISSUE THREAD

**Issue by danpovey** [kaldi-asr/kaldi#1496]
People keep asking for the ability to output the per-frame acoustic costs.
I don't think this is really useful for anything, but we might as well add it.

This would involve adding an option like
```
  po.Register("write-per-frame-acoustic-loglikes", &per_frame_acwt_wspecifier,
                   "Wspecifier for table of vectors containg the acoustic log-likelihoods "
                    "per frame for each utterance.  E.g. ark:foo/per_frame_logprobs.1.ark");
```
to programs like gmm-align-compiled.
[note: that program's usage message needs to be cleaned up to adhere to current
conventions.]

I think the best way to implement this would be to add a function in lattice-functions.h
like this:

```
/** 
   This function extracts the per-frame log likelihoods from a linear
   lattice (which we refer to as an 'nbest' lattice elsewhere in Kaldi code).
   The dimension of *per_frame_loglikes will be set to the
   number of input symbols in 'nbest'.  The elements of 
   '*per_frame_loglikes' will be set to the .Value2() elements of the lattice
   weights, which represent the acoustic costs; you may want to scale this
   vector afterward by -1/acoustic_scale to get the original loglikes.
   If there are acoustic costs on input-epsilon arcs or the final-prob in 'nbest'
   (and this should not normally be the case in situations where it makes 
   sense to call this function), they will be included to the cost of the
   preceding input symbol, or the following input symbol for input-epsilons 
   encountered prior to any input symbol.  If 'nbest' has no input symbols,
   'per_frame_loglikes' will be set to the empty vector.
*/
void GetPerFrameAcousticCosts(const Lattice &nbest,
       Vector<BaseFloat> *per_frame_loglikes);
```
The code for the function above can closely mirror the code for the function
LatticeToLinear().

An extra optional argument called per_frame_acwt_wspecifier, of type 
BaseFloatVectorWriter, should be added to AlignUtteranceWrapper 
(have it default to NULL if not specified).  If this argument is NULL or
if per_frame_acwt_wspecifier->IsOpen() returns false, nothing will be
written to it and no extra computation will be done.

@vdp, I don't know how busy you are these days?  Do you have any time for this?
You could probably do it quite fast as you've messed around with this type quite a lot.

**Comment by danpovey** [comment]
Vassil is busy; @naxingyu, do you have time?  Or any volunteer?

**Comment by naxingyu** [comment]
ok

**Comment by naxingyu** [comment]
@danpovey sorry for the delay, was occupied. I couldn't find LatticeToLinear() in the current code base. Where is it?

**Comment by danpovey** [comment]
Oh, I think I meant GetLinearSymbolSequence

**Comment by danpovey** [comment]
@naxingyu, any progress?

**Comment by naxingyu** [comment]
I'll commit this weekend.

**Comment by danpovey** [comment]
Xingyu, are you still working on this?

**Comment by naxingyu** [comment]
Yes…
I have the basic code. But before I got to test, I was involved in a emergent project, till yesterday.
I think I can finish this before next Monday...

> 在 2017年4月27日，04:13，Daniel Povey <notifications@github.com> 写道：
> 
> Xingyu, are you still working on this?
>

**Comment by naxingyu** [comment]
One problem remaining, is there a std::vector to kale::Vector convertor?

> 在 2017年4月27日，04:13，Daniel Povey <notifications@github.com> 写道：
> 
> Xingyu, are you still working on this?
>

**Comment by danpovey** [comment]
One way to do the conversion is:

std::vector<BaseFloat> nonempty_vector(..)
SubVector<BaseFloat> vec(&(nonempty_vector[0]),
                nonempty_vector.size());
so it points  at the memory of 'nonempty_vector'.
