### ISSUE TITLE
How to use Acoustic Models from Google Android 

### ISSUE THREAD

**Issue by mscreenie** [kaldi-asr/kaldi#1512]
Is it possible to use the acoustic models from Google Android, I read you can download the models for offline ASR on Android devices. I've done it and it works well offline. 

How to use these models in Kaldi?

**Comment by ognjentodic** [comment]
you can't use these models in Kaldi

**Comment by mscreenie** [comment]
Thanks. Aside from possible legal issues could you explain why? Are they in an encrypted form or does someone need to write a parser for it to be used? 

The models are likely to be some of the best given the accuracy I've observed in different languages.

**Comment by danpovey** [comment]
They are proprietary and not designed to be readable by other tools.
see kaldi-asr.org/forums.html for how to ask questions like this.

**Comment by mscreenie** [comment]
Very interesting. Thank you for your response.
