### ISSUE TITLE
specifying the frame length for ctm creation

### ISSUE THREAD

**Issue by yuvalkry-si** [kaldi-asr/kaldi#1518]
Hello,

  The tools nbest-to-ctm and lattice-to-ctm-conf do not accept the --frame-length parameter
  although at least for nbest-to-ctm this option is mentioned in the usage message.
 
  In addition, when the frame length is shorted than 10ms (e.g. for very fast speech)
  the precision of the ctm files should be 3 decimal points, well, this I can easily change
  on my own...

       Yuval

**Comment by jtrmal** [comment]
nbest-to-ctm has the following options:
```
  --frame-shift               : Time in seconds between frames.
 (float, default = 0.01)
  --precision                 : Number of decimal places for start duration times (note: we may use a higher value than this if it's obvious from --frame-shift that this value is too small (int, default = 2)
```
as far as I understand, those are what you are looking for.
I'll change the help message.

**Comment by yuvalkry-si** [comment]
Ok, I see, so the frame length is actually not relevant for CTM conversion.

  Thanks,
      Yuval

**Comment by jtrmal** [comment]
I think the optiion was renamed in the past (I don't recall the reason), so it's frame-shift now.
y.
