### ISSUE TITLE
Cuda "invalid device function" running Karel's recipe onTIMIT

### ISSUE THREAD

**Issue by yuluz** [kaldi-asr/kaldi#1524]
Hello, I got 
_KALDI_ASSERT: at cmvn-to-nnet:main:cmvn-to-nnet.cc:66, failed: cmvn_stats.NumRows() == 2_ 
while pretraining the DBN, in the cmvn_glob_fwd.log, it says: 
_ERROR (nnet-forward:Set():cu-vector.cc:957) cudaError_t 8 : "invalid device function" returned from 'cudaGetLastError()'_
It might be GPU setting problem, but I did modify the makefile with "CUDA_ARCH=-gencode arch=compute_61,code=sm_61 " for my GTX1080 and the tests in cudamatrix and cuda samples succeeded.
How can I solve this problem? Thanks.

**Comment by danpovey** [comment]
closing here as we're seponding on the list.

**Comment by vesis84** [comment]
https://groups.google.com/forum/#!topic/kaldi-help/uhiTCWn8YWU
