### ISSUE TITLE
Installation problem 

### ISSUE THREAD

**Issue by rakib-BUET** [kaldi-asr/kaldi#1527]
I am new in linux and  trying to install kaldi on Linux mint 18 following Josh Meyer's Website

http://jrmeyer.github.io/kaldi/2016/01/26/Installing-Kaldi.html

My issue is when i run ./configure --shared

smlabc1@smlabc1-All-Series ~/kaldi/src $ ./configure --shared

OUTPUT 

Configuring ...
Checking compiler g++ ...
Checking OpenFst library in  ...
***configure failed: Could not find file /include/fst/fst.h:
  you may not have installed OpenFst. See ../tools/INSTALL ***

how could i solve this issue ?
I am waiting for your response 
Thanks in advance

**Comment by danpovey** [comment]
Closing this issue, you need to read the error messages.

**Comment by rakib-BUET** [comment]
Dear Dan,

where i would find the error messages ?

i have attached the screen shot for better understanding. 

![screenshot from 2017-04-04 11-07-33](https://cloud.githubusercontent.com/assets/26864022/24642151/06d1d150-1927-11e7-99b1-a4ecdbe15d3d.png)

**Comment by danpovey** [comment]
I think it's best if you don't try to work with Kaldi if you can't figure
that out yourself.
It gets harder from here, not easier.
