### ISSUE TITLE
how to bulid a speech to text user interface using kaldi either using spacy/ Keras/tensorflow?

### ISSUE THREAD

**Issue by kaarthi28** [kaldi-asr/kaldi#1534]
We're trying to build Automatic Speech Recognition using Kaldi and then for building models for NLP/NLU we're trying to use either Spacy/Keras/Tensorflow. Is there any way to integrate Kaldi with these tools?

**Comment by danpovey** [comment]
It won't be easy, you should get familiar with Kaldi itself before even
thinking about that.
see kaldi-asr.org/forums.html for how to ask questions.
