### ISSUE TITLE
How to train kaldi using LibriSpeech dataset?

### ISSUE THREAD

**Issue by kaarthi28** [kaldi-asr/kaldi#1535]
After following all the steps we were able to download LibriSpeech dataset and trained it.But the model got stuck at 3Gram. Is there any error I may have made while training? Let me know the training procedure for training dataset in "egs" folder.

**Comment by danpovey** [comment]
too little details provided (need screen paste), maybe you don't have enough memory.
but you should be asking on kaldi-help.
