### ISSUE TITLE
Installation instructions for native Windows with Visual Studio

### ISSUE THREAD

**Issue by luvwinnie** [kaldi-asr/kaldi#1536]
I'm following the windows/INSTALL instruction to install the kaldi on windows, but there are some instruction not  up to date.

5.Use patch (or you can use git patch) to patch the OpenFST(win).

The lastest master branch doesn't have the extras/openfstwin-1.3.4.patch file.
I would appreciate for updating the Installation Instruction for native Windows with Visual Studio!

**Comment by jtrmal** [comment]
yes, good point. At this time you have to use the 5.0 branch of kaldi when you need windows. THat is mostly because of the openfst 1.6. I have making these things working again on my todo list, but might take longer. I'll modify the readme to reflect that.
y.

**Comment by jtrmal** [comment]
I updated the installation instructions in #2032 
closing this
