### ISSUE TITLE
Kaldi configure script verifies on static openfst even with --static-fst=no option

### ISSUE THREAD

**Issue by posophe** [kaldi-asr/kaldi#155]
All is in the title.

**Comment by jtrmal** [comment]
I don't understand what is the question.
Y.

**Comment by posophe** [comment]
It's not a question, it's an issue. Even with the option --static-fst=no, the configure script verifies the presence of libfst.a. In fact, the script, during all the configuration process, verifies twice the existence of each dependencies.

**Comment by danpovey** [comment]
He might be talking about the configuration process on Darwin (i.e., mac).
The script says
    if [ "`uname`" == "Darwin"  ]; then
      ...
      if [ ! -f $FSTROOT/lib/libfst.a ]; then
        failure "Static OpenFST library not found:  See ../tools/INSTALL"
      fi

.. which does seem wrong.  I assume we do support dynamic OpenFst on Darwin.

**Comment by posophe** [comment]
You're right but the verification happens during a build on OBS i.e openSUSE tumbleweed

**Comment by danpovey** [comment]
Try to figure out which lines in the configure script are getting called.
What does `uname` output on your OS?  'Linux'?
Dan

**Comment by posophe** [comment]
I know exactly which one. I have patched the configure script to be able to build kaldi. 
@@ -449,10 +449,6 @@
   else
     spx_type=so
   fi
-  if [ ! -f "$SPEEXROOT/lib/libspeex.${spx_type}" ];then
-    echo "Static=[$static_speex] Speex library not found: You can still build Kaldi without Speex."
-    return
-  fi
 
   if [ -f $SPEEXROOT/include/speex/speex.h ]; then
     echo >> kaldi.mk
@@ -768,13 +764,6 @@
     failure "Could not find file $FSTROOT/include/fst/fst.h:
     you may not have installed OpenFst.  See ../tools/INSTALL"
 fi
-echo Checking OpenFst library was patched.
-if ! grep "multiple repeated" $FSTROOT/include/fst/minimize.h >/dev/null; then
-    echo "**  ERROR  **"
-    echo "** $FSTROOT/include/fst/minimize.h seems not to be patched:"
-    echo "patch not applied?  FST tools will not work in our recipe."
-    exit 1;
-fi
 
 # back up the old one in case we modified it
 if [ -f kaldi.mk ]; then
@@ -815,9 +804,6 @@
   if [ ! -e /System/Library/Frameworks/Accelerate.framework ]; then
     failure "Need the Accelerate.framework to compile on Darwin."
   fi
-  if [ ! -f $FSTROOT/lib/libfst.a ]; then
-    failure "Static OpenFST library not found:  See ../tools/INSTALL"
-  fi
   # posix_memalign and gcc -rdynamic options not present on OS X 10.5.*
   osx_ver=`sw_vers | grep ProductVersion | awk '{print $2}' | awk '{split($0,a,"\."); print a[1] "." a[2]; }'`
   echo "Configuring for OS X version $osx_ver ..."
@@ -868,9 +854,6 @@
       OPENFSTLDFLAGS="-Wl,-rpath=${FSTROOT}/lib"
       fst_type='so'
   fi
-  if [ ! -f "$FSTROOT/lib/libfst.${fst_type}" ]; then
-    failure "Static=[$static_fst] OpenFST library not found:  See ../tools/INSTALL"
-  fi
   echo OPENFSTLIBS = $OPENFSTLIBS >> kaldi.mk
   echo OPENFSTLDFLAGS = $OPENFSTLDFLAGS >> kaldi.mk

**Comment by danpovey** [comment]
OK, thanks.  Yenda usually deals with build issues, so I'll wait for him to
get to it.
Dan

**Comment by jtrmal** [comment]
Can you please send the diff as a attachment? The inline diff got
reformatted as it looked as markup, probably. Or better yet, open pull
request at github.
Thanks, y.

**Comment by danpovey** [comment]
BTW, the 'message text garbled?' link in gmail fixes this.

**Comment by posophe** [comment]
Oh yep sorry you're totally right. But I wouldn't open a pull request, as my patch does things I need but not in a good way.
http://paste.opensuse.org/71621692

**Comment by jtrmal** [comment]
Thanks -- but this is definitely really weird, your system (OpenSUSE gets
identified as OSX). What is the output from "uname" on your system?
y.

**Comment by jtrmal** [comment]
Also, try to run the configure script using "bash -x" and send me the
output (feel free to contact me directly -- jtrmal@gmail.com).
y.

**Comment by posophe** [comment]
I can't clearly identify the system, as I use the OpenSUSE Build Service but it shouldn't differ that much than my own system, excepted for the kernel version :
linux-cqwx.site 3.16.7-24-desktop #1 SMP PREEMPT

**Comment by jtrmal** [comment]
Can you send me the output from the command uname ?
y.

**Comment by posophe** [comment]
Linux cloud106 4.1.6-3-default #1 SMP Fri Aug 28 10:59:34 UTC 2015 (d867e86) i686 i686 i386 GNU/Linux.

**Comment by jtrmal** [comment]
Thanks,
can you also send me the output from running  something like
bash -x ./configure <your-parameters> >configure.log 2>&1
Thanks
y.

**Comment by posophe** [comment]
Here is my output : http://paste.opensuse.org/88333945
Please notice two things
- Because of my patch, I have to add OPENFST_VER, OPENFST_GE_10400 and EXTRA_CXXFLAGS manually.
- The configure script looks at /usr/Makefile when --fst-root is setted up as /usr

**Comment by jtrmal** [comment]
Sorry, I meant the original configure script, not that one with your
modifications. It will fail, but I will see what's going on -- I reviewed
the script yesterday and I couldn't find any reason why it should behave
how you describe. Thanks
y.

**Comment by posophe** [comment]
Ok the API of OBS is down for the moment. I'll post it as soon as possible. I would like to open a forum thread. I need more infos to ensure Kaldi runs correctly.

**Comment by posophe** [comment]
Unbelievable... I can't perform a print on the configure script, whereas nothing changed.

**Comment by posophe** [comment]
I need your help for a last thing. Do you know the name of all the binaries and their places where there are build ? I can easily use a hack for the libraries but not for the binaries without knowing their names.

**Comment by jtrmal** [comment]
I'd love to help, but I don't understand what you are doing or what you are
asking :(
y.

**Comment by posophe** [comment]
Well, I'm packaging kaldi for openSUSE (to provide a rpm, if you prefer). I'll find a way, no worries.

**Comment by posophe** [comment]
I have just a question about portaudio. I've seen kaldi depends on portaudio but doesn't build against portaudio. Why that ?

**Comment by jtrmal** [comment]
IIRC, portaudio was used for the first generation of the online decoder --
the later online decoder is not tied to it.
It gets build when you call make ext, I believe.

y.

**Comment by posophe** [comment]
Thanks you. But shouldn't it been changed according to these changes ?

**Comment by jtrmal** [comment]
@posophe , I lost track of your issue/issues.
Could you please verify these issues still persist in the latest github kaldi version?
Thanks, y.
