### ISSUE TITLE
Handwriting Recognition

### ISSUE THREAD

**Issue by selcouthlyBlue** [kaldi-asr/kaldi#1550]
I intend to use Kaldi for the handwriting recognition app I'm making for Android. So far, here's what I have:

1. I used the RETURNN framework (https://github.com/rwth-i6/returnn) to train and validate an MDLSTM Architecture that's implemented (more info in this paper https://www-i6.informatik.rwth-aachen.de/publications/download/1014/VoigtlaenderPaulDoetschPatrickNeyHermann--HwritingRecognitionwithLargeMultidimensionalLongShort-TermMemoryRecurrentNeuralNetworks--2016.pdf) in said framework. The model produced from training and validation can be decoded using a speech recognizer toolkit and Kaldi is one of those speech recognizers that can be used. The dataset used for training and validation is the IAM Offline Handwriting Dataset (http://www.fki.inf.unibe.ch/databases/iam-handwriting-database/download-the-iam-handwriting-database).

2. The mobile app is already made. All I really need now is the recognition model that will be used by the app to recognize handwriting and from what I've read, it is possible to integrate Kaldi to android.

Given what I have, I just have one question: how do I use Kaldi for this purpose?

**Comment by danpovey** [comment]
If they say their model can be used with Kaldi as a recognizer, then I'd
say that the first order of business is for you to figure out how to do
that.  E.g. see if they provide scripts to do it.

You say the mobile app is already written.  I'd say you are jumping the gun
a little bit if you haven't even figured out how to do the handwriting
recognition.

Incidentally, handwriting recognition is something that I want to add
support for in Kaldi, over the next few months.  This would be based on
Kaldi's own nnet3 framework.  I'll have to look into what databases are
available and what their format it.

Dan

**Comment by selcouthlyBlue** [comment]
Thank you for replying to my query. 

I have yet to get my answer on whether they provide scripts to do it. Although, if it's possible for me to create my own scripts for that then I can probably do it. 

What do you mean by "figuing out how to do handwriting recognition"?

**Comment by danpovey** [comment]
What I mean is, it seems to me that you haven't figured out how to get the
underlying technology to work, so it's too soon to start writing an app.

**Comment by danpovey** [comment]
closing this issue as it's a question not really an issue.

**Comment by selcouthlyBlue** [comment]
It turns out, Kaldi will be used to decode the log posteriors produced from running the framework.

**Comment by danpovey** [comment]
OK, but you need to learn about Kaldi.  We are not going to do the leg-work
of figuring out how to integrate Kaldi with their handwriting system; we
can answer focused questions (not here; see kaldi-asr.org/forums.html) but
we won't solve open-ended problems like this for you.

**Comment by selcouthlyBlue** [comment]
My apologies for asking such questions. I'll be learning more about Kaldi and start from there.
