### ISSUE TITLE
Problem about example librispeech

### ISSUE THREAD

**Issue by holysjl** [kaldi-asr/kaldi#1551]
I face a problem when I execute ./run.sh of the example librispeech.

holysjl@ubuntu:~/kaldi-trunk/egs/librispeech/s5$ ./run.sh
utils/validate_data_dir.sh: Successfully validated data-directory data/dev_clean
local/data_prep.sh: successfully prepared data in data/dev_clean
utils/validate_data_dir.sh: Successfully validated data-directory data/test_clean
local/data_prep.sh: successfully prepared data in data/test_clean
utils/validate_data_dir.sh: Successfully validated data-directory data/dev_other
local/data_prep.sh: successfully prepared data in data/dev_other
utils/validate_data_dir.sh: Successfully validated data-directory data/test_other
local/data_prep.sh: successfully prepared data in data/test_other
utils/validate_data_dir.sh: Successfully validated data-directory data/train_clean_100
local/data_prep.sh: successfully prepared data in data/train_clean_100
Preparing phone lists and clustering questions
 at -e line 2, <> line 4.

**Comment by danpovey** [comment]
My first guess is that your disk is full.  See kaldi-asr.org/forums.html for how to ask questions.

**Comment by danpovey** [comment]
Actually it looks like a perl script somewhere in prepare_dict.sh died, but
I'm not sure why.  You could add the option '-x' to the first line of
local/prepare_dict.sh and rerun from that command.
