### ISSUE TITLE
missing get_word_map.pl

### ISSUE THREAD

**Issue by vijayaditya** [kaldi-asr/kaldi#1556]
`get_word_map.pl` script which is being used in several recipes is missing. I tried searching for it in the old commits using the command `git log --all -- **/<filename>` but I am unable to find it.

https://github.com/kaldi-asr/kaldi/search?p=1&q=get_word_map.pl

**Comment by entn-at** [comment]
I believe it's contained in `kaldi_lm` in the `tools/` folder.

**Comment by vijayaditya** [comment]
Thanks !

**Comment by CuiDonCai** [comment]
@entn-at , the script train_lms.sh of aidatatang_200zh  could not find  get_word_map.pl, too. I didn't find get_word_map.pl in kaldi root directory. I can't even find kaldi_lm in kaldi root directory. my kaldi is new. it download a few days ago. Thanks？

**Comment by danpovey** [comment]
That's part of kaldi_lm, once you install it it should work.
That script should tell you how to install it.

**Comment by CuiDonCai** [comment]
@danpovey , yep, thanks. I just fixed it. It need manual installation.
