### ISSUE TITLE
Remove min-seg-len options

### ISSUE THREAD

**Issue by danpovey** [kaldi-asr/kaldi#1561]
This is to draw it to the attention of anyone who might be reworking recipes.
The use of combine_short_segments.sh in run_ivector_common.sh, as in:

```                                                                                                   utils/data/combine_short_segments.sh \
     data/${train_set}_sp_hires $min_seg_len data/${train_set}_sp_hires_comb

```
is no longer necessary (since we upgraded the chain-training scripts to allow multiple chunk lengths).  The idea is that you use something like
`frames_per_chunk=140,100,160`
in the training script, and if the database has a lot of short segments, you include a fairly short option (100 in this case, but could be e.g. 80 or 60).
The combine-short-segments thing was to solve the problem of losing too much data in chain training due to segments being shorter than the chunk size.

**Comment by danpovey** [comment]
Also, @david-ryan-snyder, my hope with the PCA thing was to simplify the scripts, but looking at the run_ivector_common.sh in AMI, it isn't simpler than before, it's more complicated (e.g. it selects segments of hires training data that were also in the original data, which isn't necessary since we no longer need the alignments).  You can just compute the PCA on the same subset of data that you're training the diagonal UBM on.

**Comment by david-ryan-snyder** [comment]
@danpovey, got it. I'll make the change.
