### ISSUE TITLE
Image augmentation

### ISSUE THREAD

**Issue by danpovey** [kaldi-asr/kaldi#1574]
@hhadian, I have got the basic recipes working in the CIFAR setup (although we need to get dropout working).
Can you please add image augmentation to this?

The way I'd like you to do this is to add a string option --image-augmentation-opts to the program train_raw_dnn.py, which will be passed into train_one_iteration.  If this flag is supplied, it will insert into the pipe after nnet3-shuffle-egs, the program nnet3-egs-augment-image with the specified option string (Something like --vertical-shift-0.1 --horizontal-shift=0.1 --horizontal-flip=true).

Bear in mind that that binary is not debugged or even carefully checked.  @YiwenShaoStephen is working on a python script that will turn a Kaldi matrix (in our chosen format) into an image, and we can use this to verify that the image augmentation binary is doing what we expect.

You might also have some comments on whether the CNN configurations I am using are reasonable, and some ideas for improved configurations.

**Comment by hhadian** [comment]
Ok, will do.

**Comment by hhadian** [comment]
Just to make sure, you mean the train_raw_dnn.py which is in `steps/nnet3`? Can that be used for general machine learning tasks (like this CIFAR task)?

**Comment by danpovey** [comment]
Yes, the example script I put in cifar/v1 already uses that.

**Comment by hhadian** [comment]
Interesting! I imagined quite a bit of changes would be needed.
So, most options in this script follow a category format (category separated by a dot), do you want me to use `--image.augmentation-opts` instead?

**Comment by danpovey** [comment]
OK, that seems reasonable.
