### ISSUE TITLE
Image augmentation-- rewrite/extension

### ISSUE THREAD

**Issue by danpovey** [kaldi-asr/kaldi#1586]
@YiwenShaoStephen, you could look at this if you want.

I think the way I started off the program nnet3-egs-augment-image.cc was not very ideal, I think we should rewrite it so that it's easier to extend it to things like shear and zoom, to be based on a co-ordinate transformation matrix.

In https://github.com/fchollet/keras/blob/master/keras/preprocessing/image.py, look for the function random_transform.  I think the function PerturbImage should be changed to be *structurally* more like the function random_transform.

For now, don't support any options other than the options it already supports; just try to change it so that it first gets a co-ordinate transform matrix.  Add a function as follows:

/**
  This function generates a co-ordinate transformation matrix according to 
  the image-augmentation config 'config'.  It is t transformation on the
  extended co-ordinate vector [ x, y, 1 ]^T, where x and y are the width
  and height co-ordinates into the image, with x=0, y=0 the top left of
  the image and x=1, y=1 the bottom right.   This matrix left-multiplies 
  the co-ordinates into the transformed image, giving 
     [ NEED SOME HELP HERE ]
*/
void GetRandomTransformMatrix(const ImageAugmentationConfig &config,
                                                         Matrix<BaseFloat> *transform_mat);

**Comment by danpovey** [comment]
Actually, I now realize that there are some gaps in my knowledge of how image augmentation transforms are represented.  E.g. do they left-multiply the co-ordinates into the transformed image, giving you the co-ordinates into the original image?  @hhadian , maybe it's better if you *start* this work, since you said you took an image processing course; and we can have @YiwenShaoStephen add any missing transformation types.

BTW, I notice the keras code doesn't use the co-ordinate transformation matrix to represent axis flips, but it seems to me that that would be quite possible to do so, and I think it would be more elegant.

**Comment by danpovey** [comment]
Also, @hhadian, when designing it, please bear in mind that this is intended to be used in handwriting and OCR-- this may affect some of the design choices.  For example, it might not make sense to treat the image as square when creating the random shear angle, because that would mean that you'd get very tiny 'real' shears when shearing long horizontal segments of text. 

So please make choices that will make sense in the application to OCR; this may mean that what I said in my draft comment about x=1,y=1 corresponding to the bottom right of the image might not make sense-- maybe having  x and y be 'real' co-ordinates with x=num-rows-1, y=num-cols-1 being the bottom right of the image would make more sense.

**Comment by danpovey** [comment]
From looking at what that script calls, and at the documentation here:
https://docs.scipy.org/doc/scipy-0.19.0/reference/generated/scipy.ndimage.affine_transform.html#scipy.ndimage.affine_transform

it looks like these matrix transformations are from the *new* to the *old* co-ordinates, so no inversion is necessary in applying them.  There is also something in the code there about centering, i.e. the function transform_matrix_offset_center, and that is probably important.

Just do linear interpolation between the 4 closest points of the old image.  Fancy higher-order splines are not needed, no-one will be looking at these images.

I'd say it will probably easiest to initially structure the code a little bit like the Keras code, just with a small subset of the functionality (and better documentation).  We are fixing the meaning of the axes (row = width, column = height), so all that 'axis'-related code will disappear and become constants.

@hhadian, once you set up the basic framework we can get others to fill in more transformation types, and refer them to the Keras code for guidance.

**Comment by hhadian** [comment]
OK will do

**Comment by YiwenShaoStephen** [comment]
How is it going now? I've done some reading on this topic and I think I can do more help. To make the algorithms more elegant as the keras does, I think it would be better to first make a intermediate matrix (like the 3d array in numpy) to store the value in the kaldi matrix, and then multiply transformation matrices on it.  It will be easier to do further work like debugging or documentation. Is the proposal applicable in this case?

**Comment by danpovey** [comment]
Hossein, I don't know how busy you are, should Stephen go ahead and start,
or are you going to do it soon (e.g. today)?

**Comment by hhadian** [comment]
I'll do it today.

**Comment by danpovey** [comment]
this is already done.
