### ISSUE TITLE
GetLinearSymbolSequences() implementation needs to be fixed

### ISSUE THREAD

**Issue by vdp** [kaldi-asr/kaldi#1591]
I believe the implementation of that function is somewhat broken. We have two options here:

* fix it, and the corresponding unit test, that is currently not general enough
* remove it altogether- unless my grep-fu is failing me, it's not actually used anywhere. I think it could be potentially useful, but for now it's just a dead code
* (a third option could be me just misunderstanding how this function is supposed to work)

I can open a PR, if that's deemed necessary- just let me know the branch you'd like me to base it on.

**Comment by vdp** [comment]
Just realized that I haven't actually said what I think is wrong with the code. I see three problems: a) a typo isymbols/osymbols, b) not taking into account that the start node will in general have branching factor greater than 1, c) fail to advance through the branches, so instead of returning N hypotheses it just returns N copies of the first hypothesis.
A quick-and-dirty fix that worked for me:
```
--- a/src/fstext/fstext-utils-inl.h
+++ b/src/fstext/fstext-utils-inl.h
@@ -259,15 +259,18 @@ bool GetLinearSymbolSequences(const Fst<Arc> &fst,
           error = true;
         break;
       } else {
-        if (fst.NumArcs(cur_state) != 1) {
+        if (fst.NumArcs(cur_state) != 1 && cur_state != start_state) {
           error = true;
           break;
         }
         ArcIterator<Fst<Arc> > aiter(fst, cur_state);
+        if (cur_state == start_state) {
+          aiter.Seek(n);
+        }
         const Arc &arc = aiter.Value();
         if (isymbols_out && arc.ilabel != 0)
           (*isymbols_out)[n].push_back(arc.ilabel);
-        if (osymbols_out && arc.ilabel != 0)
+        if (osymbols_out && arc.olabel != 0)
           (*osymbols_out)[n].push_back(arc.olabel);
         if (weights_out)
           (*weights_out)[n] = Times((*weights_out)[n], arc.weight);

```
Probably it can be made a bit "prettier"

**Comment by danpovey** [comment]
Just remove it, it doesn't seem to be used anywhere.  I think I prefer a PR
to kaldi_52.

**Comment by vdp** [comment]
The function was removed in PR #1594
