### ISSUE TITLE
Failures when python is python3

### ISSUE THREAD

**Issue by psmit** [kaldi-asr/kaldi#1592]
At this moment kaldi assumes that python is actually python2. Most distro's have this indeed configured this way, but I have at least 2 cases that this doesn't hold

1) Arch linux 
2) When using a module system and both python2 and python3 versions are loaded, sometimes this causes python to be linked to python2.

I think the best solution would be to write explicitly `#!/usr/bin/env python2` instead of `#!/usr/bin/env python3`. Afaik this would work in all situations correctly. Would you be open to a PR that implements this change?

**Comment by jtrmal** [comment]
I think that could work. 
https://www.python.org/dev/peps/pep-0394/

I'm not sure, however, if all distributions and other OS (Mac?) do support python2 link.  Also, according to the PEP, it's actually Arch that is causing the incompatibility, so I don't think we should spend too much of our time trying to deal with that.

**Comment by dresen** [comment]
I'm in the middle of installing Kaldi on a 2015 macbook pro and the solution with bash alias'ing python to python2.7 doesn't work - extras/check_dependencies.sh still reports version 3.*

**Comment by jtrmal** [comment]
@dresen -- I think that's because bash by default does not expand aliases when in non-interactive mode. I think 
shopt -s expand_aliases
might help

**Comment by jtrmal** [comment]
btw, when I'm thinking about it -- expanding the aliases could have a lot of negative results. Perhaps it would be better to define a shell function
```
function python() {
  python2 "$@"
}
```
or something like that -- I don't have time to test it out now.

**Comment by danpovey** [comment]
python2 is not defined on my mac.
I believe the Python community has accepted that python3 is essentially a
separate language for compatibility purposes, and that python2 will always
be invoked as "python", and python3 as "python3".

In my opinion Arch linux has painted itself into a corner by this choice,
because it's not compatible with the rest of the world.


Dan

**Comment by psmit** [comment]
I disagree Dan. In the linked PEP is written that this choice will be revisited every couple years. Also, this PEP came only after Arch changed it's default python. There was no python community opinion before they did that; the community saw the effects and created this PEP as a reaction.

Anyway, the advise of this PEP is to use python2 in the shebang. Could you maybe look why your mac does not have python2 defined; the PEP indicates that the mac installers have been updated to provide that.

**Comment by danpovey** [comment]
Hm.

The PEP does seem to say that python2 is the preferred way to invoke
python.  However, since my mac doesn't have python2 installed, and I think
probably a bunch of people have the same issue (regardless of the exact
reason), so I'm inclined to wait a bit before changing all the python's to
python2.

Dan

**Comment by psmit** [comment]
Fair point about the mac. On the other hand, in our group we still have a problem if some loads python modules in the 'wrong' order or e.g. enables a python3 virtual environment (for their own scripts).

Would it be a suggestion to reverse the warning; giving people the command how to create a python2 symlink if it doesn't exist? Or add a symlink automatically in the tools path somewhere if 'python2' doesn't exist?

**Comment by danpovey** [comment]
Hm, that is a reasonable idea.  But it's @jtrmal who understands best how
the env.sh works, so it's a question of when he has time.

(However, I'd say that it probably a bad idea for your group to purposely
set things up so you need to invoke python3 as just 'python', as the pep3
standard definitely doesn't recommend that).

**Comment by jtrmal** [comment]
What could work is create a correct symlink somewhere in, say, tools and
setting PATH so that this symlink will be preferred.
That might be more reliable than aliases or functions. I just worry if we
want to add another layer of indirection. Perhaps you could write a PR in
that direction and test it on your setup?

On the users -- I agree with Dan, mostly -- if the user or users purposely
maps/aliases python to python3, I don't actually think I want to care.
y.

**Comment by jtrmal** [comment]
BTW, I'm ok with changing the shebang to python2 if that helps in making
things more robust but so far it looks like opening another can of issues
without actually solving anything -- instead of archlinux, the problems
will (probably) start popping out somewhere else.
y.

**Comment by danpovey** [comment]
I'd be OK to wait until we hear more reports of problems, maybe few people
use arch linux anyway.
Peter Smit seemed to be saying that people in his group were *purposely*
mapping python to python3, it wasn't even an arch linux issue.
The fact that they were doing this intentionally makes me rather less
sympathetic to their situation than I was before.

**Comment by psmit** [comment]
We do not purposely map python to python3, but that symlink is created by different installations. For example when anaconda3 is installed, or when a python3 virtual environment is activated.

In our group it is like this:
The cluster has a version of python2 installed through rpm's, but the admins advise to use a different python, one that they have installed and which can be put on the path using the module system https://www.tacc.utexas.edu/research-development/tacc-projects/lmod . The reason for this is that many people desire up-to-date versions of all kind of important python packages and the Redhad rpm's aren't updated so often. If you want to use python3 at all you have to load their python3 installation and that will include a symlink of python to python3.

The reason this is the case, is that when anaconda3 is installed (the python installation they provide), it will also install a python symlink at its install location. This is normally not a problem as those users will most likely want to run only python3 specific code. 

No-one actually counted on as complicated installations as speech recognition systems. We do have some python3 code of our own and we want to run it interleaved with kaldi-scripts. Meaning we do have to load the python3 module (and also the python2 module). If we load them in the right order, with the python2-python somewhere earlier on the path everything is peachy; if not we have python linking to python3.

To summarize:

-  I think there a valid cases that python points to python3. The linked PEP is anyway mostly geared towards distributions and the symlinks I mainly talk about now are regarding python installers or virtual environments
- The PEP recommendation is to make scripts have a python_x_ shebang if it only runs on one version of python
- There seems to be an expectation that the python2 symlink should be present on all distributions, but at least on Dan's mac it seems there is not.

I think it would be beneficial to make the change I proposed; things should be working on all platforms afterwards. I can make a PR beginning next week (I'm on holiday the rest of the week) and test it at least on our systems. Maybe Dan can then test it on his mac to see if things work. Is that a good plan?

**Comment by danpovey** [comment]
The plan sounds OK to me.

**Comment by psmit** [comment]
Just a small note, I have been sick in the past 2 weeks and now I'm first swamped with some other work stuff. I'll hope to get to making the PR in one to two weeks from now.

**Comment by jprobichaud** [comment]
In case this could help, I would like to point to this AUR package (ArchLinux Repository): https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=kaldi

The author of that build has created some build prepare steps that address semi/automatically setting python shebang lines to "python2" along with few other manips.  Maybe this can serve as a source of inspiration?  

For a toolkit of the scope of Kaldi, it's probably a good thing to wrap a bit more tightly the tools used anyways (while I admit it could be less convenient in general to have to do `$PYTHON tools/script_name.py` instead of simply `tools/script_name.py`

**Comment by danpovey** [comment]
It's easy to change the shebangs.
I'm waiting for a time when I feel the systems when "python" points to
"python3" outnumber the systems where "python2" is not defined.   Right now
on my mac, which is running 10.12 (not the latest 10.13 but I'll install it
when it pushes me to install it), python2 is still not defined.

I'm very annoyed at how the Python team handled this transition.  What they
are doing makes about as much sense as redefining "awk" to invoke perl.

Dan

**Comment by bonrybon** [comment]
currently working in MacOS 12.5 and Im having the same issue for running the `make `command in `kaldi/tools`

extras/check_dependencies.sh
extras/check_dependencies.sh: python2.7 is not installed
extras/check_dependencies.sh: The following prerequisites are missing; install them first:
   python2.7
make: *** [check_required_programs] Error 1

how should I proceed on this?

**Comment by jtrmal** [comment]
you could comment it out in the script.
I will think about what could be done, but even brew does not carry
python2.7 anymore.
y.
