### ISSUE TITLE
Is the "dash" warning still current?

### ISSUE THREAD

**Issue by psmit** [kaldi-asr/kaldi#1593]
In the check dependencies script there is a warning if `/bin/sh` is actually `dash`. The proposed solution is often not possible on university-installed machines, as wise system administrators do not give normal users `sudo` powers.

The explanation in the script is:

    # Debian systems generally link /bin/sh to dash, which doesn't work   
    # with some scripts as it doesn't expand x.{1,2}.y to x.1.y x.2.y

But if I look to most kaldi scripts they use the `#!/bin/bash` shebang. Is there any script that will still fail with dash? Would you accept a PR that changes all (if any) shebangs that are `#!/bin/sh` to `#!/bin/bash` and remove the check?

**Comment by jtrmal** [comment]
The issue is not in incorrect shebang. The issue lies with the function popen() that is used for the pipe r/w-specifiers -- see man popen:

```
This command is passed to /bin/sh using the -c flag; interpretation, if any, is performed by the shell.
```

**Comment by danpovey** [comment]
I removed the warning- looks like we fixed scripts to not require that feature.
