### ISSUE TITLE
windows-complie

### ISSUE THREAD

**Issue by z7059652** [kaldi-asr/kaldi#1635]
according to install.md, the 5 step is patch the OpenFST(win). But I can't find the openfstwin-1.3.4.patch which is located in $(tools)/extras. 
thanks. I am looking forward to your reply

**Comment by jtrmal** [comment]
it's been discussed. you have to use the 5.0 branch. The 5.1 branch uses openfst 1.6.2 for which I wasn't able to make it compile under windows, yet, partially because I'm busy and partially I don;t have easy access to a windows machine.
y.
