### ISSUE TITLE
Get a topsorted latice?

### ISSUE THREAD

**Issue by psmit** [kaldi-asr/kaldi#1640]
I'm creating some rescoring scripts of my own and it would be very convenient if I can make lattices topologically sorted. It does not seem this is possible with the normal fst tools as I would need to define a custom weight to read the special lattice weights.

Is there any way to easily TopSort a lattice? If not, would you accept a patch that either introduces `lattice-topsort` or a flag to `lattice-copy` that TopSorts the lattices?

**Comment by jtrmal** [comment]
IMO lattice-topsort is a better option than adding flag.
y.

**Comment by vdp** [comment]
@psmit: BTW, why not use OpenFst's weight registration mechanism? If I'm not mistaken OpenFst's command line tools are build on top of their "script" infrastructure, so you should be able to use them with (compact) lattice weights. See [this comment](https://sourceforge.net/p/kaldi/mailman/message/32968915/) by Paul Dixon. He has a blog post about this too.

**Comment by psmit** [comment]
Thanks for the tip @vdp ! I'll certainly look to that as well to see if it would suit my purposes
