### ISSUE TITLE
extras/check_dependencies.sh some people have yum on ubuntu and that makes the script fail

### ISSUE THREAD

**Issue by lordadamson** [kaldi-asr/kaldi#1642]
The machine I was working on had yum on it even though it was an ubuntu machine. So the check_dependencies.sh script failed.
Maybe find a better way to detect OS in the script?

**Comment by danpovey** [comment]
I just pushed a change (on master) to the script so that if apt-get is present it doesn't look for yum.   Should work now.   If not re-open the issue.

**Comment by lordadamson** [comment]
thank you, I'll test and let you know the results.
