### ISSUE TITLE
Bug in train_raw_dnn.py

### ISSUE THREAD

**Issue by osadj** [kaldi-asr/kaldi#1644]
At the end of NN training using train_raw_dnn.py, I got an error that seems to be a bug. You can reproduce this by adding the following line in the main routine of train_raw_dnn.py:

print("{dir}/accuracy.{output_name}.report".format(dir=args.dir))

which generates the error:

Traceback (most recent call last):
  File "steps/nnet3/train_raw_dnn.py", line 447, in <module>
    main()
  File "steps/nnet3/train_raw_dnn.py", line 429, in main
    print("{dir}/accuracy.{output_name}.report".format(dir=args.dir))
KeyError: 'output_name'

**Comment by danpovey** [comment]
It would be great if you can make a pull request to fix this.  Otherwise
@vimalmanohar will do it, but he's very busy.

**Comment by osadj** [comment]
Sure. Will do.

**Comment by danpovey** [comment]
Also please fix the separately reported bug that reporting.interval should
be float but is int, in libs/nnet3/train/common.py

**Comment by osadj** [comment]
In that case, I have also resolved some issues with generate_plots. Should I also include those?

**Comment by danpovey** [comment]
sure.
