### ISSUE TITLE
Default dropout has changed?

### ISSUE THREAD

**Issue by psmit** [kaldi-asr/kaldi#1660]
I noticed that a xconfig-based tdnn_blstm recipe (like the one in swdb but for other data) suddenly had a very bad performance in kaldi52 compared to the master branch a month ago. I'm using the same egs and scripts and finally I found differences in the generated `configs/xconfigs.expanded.1` and `configs/xconfigs.expanded.2` . All relu-renorm-layers have gotten default values `dropout-proportion=0.5 learning-rate-factor=1.0 ng-affine-options=`.

I am assuming that `dropout-proportion=0.5` is different from earlier defaults, I guess that would be 
 `dropout-proportion=0.0`. Am I correct in my assumptions? If so, is this change intentional?

Related question, does this relate to the `--trainer.dropout-schedule` option in the `chain/train.py`? If so, how do they interact?

**Comment by danpovey** [comment]
That wouldn't be the reason.  dropout-proportion only has an effect if the
layer is something like relu-dropout-layer.  And dropout-schedule only has
an effect if there are dropout layers present.
Look for other reasons, e.g. see when the training likelihoods start to
differ.

Dan

**Comment by danpovey** [comment]
Also you can share the output of steps/info/chain_dir_info.pl for both
dirs, I might see something.

**Comment by psmit** [comment]
exp/chain/model/gr_tdnn_blstm_9_a: num-iters=2150 nj=4..4 num-params=48.3M dim=40+100->3426 xent:train/valid[1431,2149]=(-0.655,-0.595/-0.716,-0.718) logprob:train/valid[1431,2149]=(-0.046,-0.037/-0.064,-0.066)
    exp/chain/model/gr_tdnn_blstm_9_g: num-iters=1200 nj=4..4 num-params=48.3M dim=40+100->3426 xent:train/valid[798,1199]=(-0.745,-0.680/-0.785,-0.749) logprob:train/valid[798,1199]=(-0.060,-0.051/-0.072,-0.068)


_a is the old, well working model, _g is the one that has worse performance (on the same iterations)

Asr results on iteration 200 and 1200:

    %WER 20.47 [ 11780 / 57534, 1055 ins, 2275 del, 8450 sub ] exp/chain/model/gr_tdnn_blstm_9_a/decode200/wer_8_0.0
    %WER 18.27 [ 10509 / 57534, 1136 ins, 1809 del, 7564 sub ] exp/chain/model/gr_tdnn_blstm_9_a/decode1200/wer_7_0.5
    
    %WER 20.51 [ 11801 / 57534, 1015 ins, 2326 del, 8460 sub ] exp/chain/model/gr_tdnn_blstm_9_g/decode200/wer_8_0.0
    %WER 18.54 [ 10666 / 57534, 1099 ins, 2030 del, 7537 sub ] exp/chain/model/gr_tdnn_blstm_9_g/decode1200/wer_8_0.0

Log prob plot
[log_probability_output.pdf](https://github.com/kaldi-asr/kaldi/files/1043470/log_probability_output.pdf)

    exp/chain/model/gr_tdnn_blstm_9_a/log/compute_prob_train.200.log:LOG (nnet3-chain-compute-prob[5.1]:PrintTotalStats():nnet-chain-diagnostics.cc:170) Overall log-probability for 'output-xent' is -0.989956 per frame, over 18597 frames.
    exp/chain/model/gr_tdnn_blstm_9_a/log/compute_prob_train.200.log:LOG (nnet3-chain-compute-prob[5.1]:PrintTotalStats():nnet-chain-diagnostics.cc:175) Overall log-probability for 'output' is -0.0894093 + -0.00925079 = -0.0986601 per frame, over 18597 frames.
    exp/chain/model/gr_tdnn_blstm_9_a/log/compute_prob_train.1199.log:LOG (nnet3-chain-compute-prob[5.1]:PrintTotalStats():nnet-chain-diagnostics.cc:170) Overall log-probability for 'output-xent' is -0.679438 per frame, over 18597 frames.
    exp/chain/model/gr_tdnn_blstm_9_a/log/compute_prob_train.1199.log:LOG (nnet3-chain-compute-prob[5.1]:PrintTotalStats():nnet-chain-diagnostics.cc:175) Overall log-probability for 'output' is -0.0500758 + -0.00689841 = -0.0569742 per frame, over 18597 frames.

    exp/chain/model/gr_tdnn_blstm_9_g/log/compute_prob_train.200.log:LOG (nnet3-chain-compute-prob[5.1]:PrintTotalStats():nnet-chain-diagnostics.cc:170) Overall log-probability for 'output-xent' is -0.981283 per frame, over 18597 frames.
    exp/chain/model/gr_tdnn_blstm_9_g/log/compute_prob_train.200.log:LOG (nnet3-chain-compute-prob[5.1]:PrintTotalStats():nnet-chain-diagnostics.cc:175) Overall log-probability for 'output' is -0.0889928 + -0.00936367 = -0.0983564 per frame, over 18597 frames.
    exp/chain/model/gr_tdnn_blstm_9_g/log/compute_prob_train.1199.log:LOG (nnet3-chain-compute-prob[5.1]:PrintTotalStats():nnet-chain-diagnostics.cc:170) Overall log-probability for 'output-xent' is -0.680037 per frame, over 18597 frames.
    exp/chain/model/gr_tdnn_blstm_9_g/log/compute_prob_train.1199.log:LOG (nnet3-chain-compute-prob[5.1]:PrintTotalStats():nnet-chain-diagnostics.cc:175) Overall log-probability for 'output' is -0.0505923 + -0.00690476 = -0.057497 per frame, over 18597 frames.

I just confirmed that when decoding I use `--extra-left-context 50 --extra-right-context 50 --frames-per-chunk 150` for both. The older model still gives good results, even tough the scripts and code are updated.

I'm totally at a loss, as from the likelihood graphs it seems that the models are quite the same. Does this data give you any insight in what might be wrong?

**Comment by danpovey** [comment]
Wait-- by "very bad performance"  you refer to a 0.2% absolute difference?
That's well within the normal variability that you expect on a rerun; it's
no change at all.  Certainly not the kind of difference that the words
"very bad" imply.

**Comment by psmit** [comment]
Nope, I now made a mistake and blindly gave you the results from two runs with the original code... I'll take a cup of coffee now and give you the correct numbers

**Comment by psmit** [comment]
So to explain. I run _a with the old code. After that I switched to kaldi_52 to try things like proportional-shrink and other small parameter changes (1 change per experiment) and none of the results were getting better. After that I got suspicious and ran the _a code again, once with the old code and once with new code. The new code I stopped already after 400 iterations as it was clearly going wrong.

Now the right numbers:

    exp/chain/model/gr_tdnn_blstm_9_a: num-iters=2150 nj=4..4 num-params=48.3M dim=40+100->3426 xent:train/valid[1431,2149]=(-0.655,-0.595/-0.716,-0.718) logprob:train/valid[1431,2149]=(-0.046,-0.037/-0.064,-0.066)
    exp/chain/model/gr_tdnn_blstm_9_h: num-iters=400 nj=4..4 num-params=48.3M dim=40+100->3426 xent:train/valid[265,399]=(-0.819,-0.757/-0.840,-0.782) logprob:train/valid[265,399]=(-0.060,-0.056/-0.066,-0.064)

Asr output:

    %WER 20.47 [ 11780 / 57534, 1055 ins, 2275 del, 8450 sub ] exp/chain/model/gr_tdnn_blstm_9_a/decode200/wer_8_0.0
    %WER 19.63 [ 11295 / 57534, 976 ins, 2354 del, 7965 sub ] exp/chain/model/gr_tdnn_blstm_9_a/decode300/wer_8_0.0
    %WER 21.13 [ 12159 / 57534, 1045 ins, 2718 del, 8396 sub ] exp/chain/model/gr_tdnn_blstm_9_h/decode200/wer_8_0.5
    %WER 20.33 [ 11694 / 57534, 895 ins, 2916 del, 7883 sub ] exp/chain/model/gr_tdnn_blstm_9_h/decode300/wer_8_1.0

Logprob for iteration 200

    exp/chain/model/gr_tdnn_blstm_9_a/log/compute_prob_train.200.log:LOG (nnet3-chain-compute-prob[5.1]:PrintTotalStats():nnet-chain-diagnostics.cc:170) Overall log-probability for 'output-xent' is -0.989956 per frame, over 18597 frames.
    exp/chain/model/gr_tdnn_blstm_9_a/log/compute_prob_train.200.log:LOG (nnet3-chain-compute-prob[5.1]:PrintTotalStats():nnet-chain-diagnostics.cc:175) Overall log-probability for 'output' is -0.0894093 + -0.00925079 = -0.0986601 per frame, over 18597 frames.
    exp/chain/model/gr_tdnn_blstm_9_h/log/compute_prob_train.200.log:LOG (nnet3-chain-compute-prob[5.2]:PrintTotalStats():nnet-chain-diagnostics.cc:193) Overall log-probability for 'output-xent' is -0.867784 per frame, over 18597 frames.
    exp/chain/model/gr_tdnn_blstm_9_h/log/compute_prob_train.200.log:LOG (nnet3-chain-compute-prob[5.2]:PrintTotalStats():nnet-chain-diagnostics.cc:198) Overall log-probability for 'output' is -0.065865 + -0.00924318 = -0.0751082 per frame, over 18597 frames.

Iteration 399:

    exp/chain/model/gr_tdnn_blstm_9_a/log/compute_prob_train.399.log:LOG (nnet3-chain-compute-prob[5.1]:PrintTotalStats():nnet-chain-diagnostics.cc:170) Overall log-probability for 'output-xent' is -0.854367 per frame, over 18597 frames.
    exp/chain/model/gr_tdnn_blstm_9_a/log/compute_prob_train.399.log:LOG (nnet3-chain-compute-prob[5.1]:PrintTotalStats():nnet-chain-diagnostics.cc:175) Overall log-probability for 'output' is -0.0735583 + -0.008235 = -0.0817933 per frame, over 18597 frames.
    exp/chain/model/gr_tdnn_blstm_9_h/log/compute_prob_train.399.log:LOG (nnet3-chain-compute-prob[5.2]:PrintTotalStats():nnet-chain-diagnostics.cc:193) Overall log-probability for 'output-xent' is -0.756888 per frame, over 18597 frames.
    exp/chain/model/gr_tdnn_blstm_9_h/log/compute_prob_train.399.log:LOG (nnet3-chain-compute-prob[5.2]:PrintTotalStats():nnet-chain-diagnostics.cc:198) Overall log-probability for 'output' is -0.0559466 + -0.0083181 = -0.0642647 per frame, over 18597 frames.

**Comment by danpovey** [comment]
It's not clear from that output what the issue is.  The training log-prob
is better than before, which would normally be a good thing.  You don't
show valid log-probs, so I don't know if it's overtraining.
Maybe check that you can reproduce the old results with the old code, and
check that all the options in the training log files look about the same.
 (A few deprecated options have been removed though).

**Comment by psmit** [comment]
Here are the validation log-probs:

Iteration 200:

    exp/chain/model/gr_tdnn_blstm_9_a/log/compute_prob_valid.200.log:LOG (nnet3-chain-compute-prob[5.1]:PrintTotalStats():nnet-chain-diagnostics.cc:170) Overall log-probability for 'output-xent' is -0.962797 per frame, over 18375 frames.
    exp/chain/model/gr_tdnn_blstm_9_a/log/compute_prob_valid.200.log:LOG (nnet3-chain-compute-prob[5.1]:PrintTotalStats():nnet-chain-diagnostics.cc:175) Overall log-probability for 'output' is -0.0871902 + -0.00903586 = -0.096226 per frame, over 18375 frames.
    exp/chain/model/gr_tdnn_blstm_9_h/log/compute_prob_valid.200.log:LOG (nnet3-chain-compute-prob[5.2]:PrintTotalStats():nnet-chain-diagnostics.cc:193) Overall log-probability for 'output-xent' is -0.862515 per frame, over 18375 frames.
    exp/chain/model/gr_tdnn_blstm_9_h/log/compute_prob_valid.200.log:LOG (nnet3-chain-compute-prob[5.2]:PrintTotalStats():nnet-chain-diagnostics.cc:198) Overall log-probability for 'output' is -0.0676871 + -0.00898363 = -0.0766708 per frame, over 18375 frames.


Iter 399

    exp/chain/model/gr_tdnn_blstm_9_a/log/compute_prob_valid.399.log:LOG (nnet3-chain-compute-prob[5.1]:PrintTotalStats():nnet-chain-diagnostics.cc:170) Overall log-probability for 'output-xent' is -0.855274 per frame, over 18375 frames.
    exp/chain/model/gr_tdnn_blstm_9_a/log/compute_prob_valid.399.log:LOG (nnet3-chain-compute-prob[5.1]:PrintTotalStats():nnet-chain-diagnostics.cc:175) Overall log-probability for 'output' is -0.0780645 + -0.00806269 = -0.0861272 per frame, over 18375 frames.
    exp/chain/model/gr_tdnn_blstm_9_h/log/compute_prob_valid.399.log:LOG (nnet3-chain-compute-prob[5.2]:PrintTotalStats():nnet-chain-diagnostics.cc:193) Overall log-probability for 'output-xent' is -0.781898 per frame, over 18375 frames.
    exp/chain/model/gr_tdnn_blstm_9_h/log/compute_prob_valid.399.log:LOG (nnet3-chain-compute-prob[5.2]:PrintTotalStats():nnet-chain-diagnostics.cc:198) Overall log-probability for 'output' is -0.0641295 + -0.00817164 = -0.0723012 per frame, over 18375 frames.

I will go and dig through everything to find the problem and keep you informed

**Comment by danpovey** [comment]
If you still have the models, try rerunning the job that computes the
log-prob with the new vs old code and the new vs. old models to see that
the log-prob computation is not changed.

**Comment by psmit** [comment]
First observation, the old code does not run on the new model. nnet3-am-copy fails with:

    ERROR (nnet3-am-copy[5.1]:ExpectToken():io-funcs.cc:201) Expected token "<MaxChangePerSample>", got instead "<IsGradient>".

Old code is commit a7e6183 from May 16th, new code is commit a57eab6 from May 30th.

Old code:

    gr_tdnn_blstm_9_a:LOG (nnet3-chain-compute-prob[5.1]:PrintTotalStats():nnet-chain-diagnostics.cc:170) Overall log-probability for 'output-xent' is -0.989956 per frame, over 18597 frames.
    gr_tdnn_blstm_9_a:LOG (nnet3-chain-compute-prob[5.1]:PrintTotalStats():nnet-chain-diagnostics.cc:175) Overall log-probability for 'output' is -0.0894093 + -0.00925079 = -0.0986601 per frame, over 18597 frames.

New code:

    gr_tdnn_blstm_9_a:LOG (nnet3-chain-compute-prob[5.2]:PrintTotalStats():nnet-chain-diagnostics.cc:193) Overall log-probability for 'output-xent' is -0.989956 per frame, over 18597 frames.
    gr_tdnn_blstm_9_a:LOG (nnet3-chain-compute-prob[5.2]:PrintTotalStats():nnet-chain-diagnostics.cc:198) Overall log-probability for 'output' is -0.0894093 + -0.00925079 = -0.0986601 per frame, over 18597 frames.

    gr_tdnn_blstm_9_h:LOG (nnet3-chain-compute-prob[5.2]:PrintTotalStats():nnet-chain-diagnostics.cc:193) Overall log-probability for 'output-xent' is -1.71122 per frame, over 18597 frames.
    gr_tdnn_blstm_9_h:LOG (nnet3-chain-compute-prob[5.2]:PrintTotalStats():nnet-chain-diagnostics.cc:198) Overall log-probability for 'output' is -0.229249 + -0.0228406 = -0.25209 per frame, over 18597 frames.


I think this shows that the log-prob computation has not changed

**Comment by danpovey** [comment]
OK; I assume those are not the same iteration.

**Comment by psmit** [comment]
Actually they are all train logprobs from training iteration 200. I now see that the result for the newer model is different then from in the log-file. I'll investigate that and get back to you

**Comment by psmit** [comment]
In the logs there is a difference in command used for logprob calculation:

    ==> exp/chain/model/gr_tdnn_blstm_9_a/log/compute_prob_train.200.log <==
    # nnet3-chain-compute-prob --l2-regularize=5e-05 --leaky-hmm-coefficient=0.1 --xent-regularize=0.025 "nnet3-am-copy --raw=true exp/chain/model/gr_tdnn_blstm_9_a/200.mdl - |" exp/chain/model/gr_tdnn_blstm_9_a/den.fst "ark,bg:nnet3-chain-copy-egs --left-context=4                     --right-context=4 ark:exp/chain/prep/gr_tdnn_blstm_9/tdnn/egs/train_diagnostic.cegs                     ark:- | nnet3-chain-merge-egs --minibatch-size=1:64 ark:- ark:- |" 

    ==> exp/chain/model/gr_tdnn_blstm_9_h/log/compute_prob_train.200.log <==
    # nnet3-chain-compute-prob --l2-regularize=5e-05 --leaky-hmm-coefficient=0.1 --xent-regularize=0.025 "nnet3-am-copy --raw=true exp/chain/model/gr_tdnn_blstm_9_h/200.mdl - |" exp/chain/model/gr_tdnn_blstm_9_h/den.fst "ark,bg:nnet3-chain-copy-egs ark:exp/chain/prep/gr_tdnn_blstm_9/tdnn/egs/train_diagnostic.cegs                     ark:- | nnet3-chain-merge-egs --minibatch-size=1:64 ark:- ark:- |" 


So the new scripts do not include `--left-context=4                     --right-context=4` in the commands.

The logprob calculations in the previous message used both the same command, the one with left and right context.

**Comment by danpovey** [comment]
Those options are no longer passed in because in all currently checked-in
setups there is no need for it, since the egs are generated with the
desired amount of context.  I wanted to get rid of unnecessary complexity.

If you dumped the egs with more context, and then wanted for some reason to
use egs with less context, then the new code would cause a mismatch.

But it doesn't really make sense to run BLSTMs and to use
extra-left-context and extra-right-context of zero, which is what it looks
like you are doing.

**Comment by psmit** [comment]
I think we are onto something, the same is true for the training commands:

    head -n1 exp/chain/model/gr_tdnn_blstm_9_{a,h}/log/train.200.1.log
    ==> exp/chain/model/gr_tdnn_blstm_9_a/log/train.200.1.log <==
    # nnet3-chain-train --verbose=1 --apply-deriv-weights=False --l2-regularize=5e-05 --leaky-hmm-coefficient=0.1 --read-cache=exp/chain/model/gr_tdnn_blstm_9_a/cache.200 --write-cache=exp/chain/model/gr_tdnn_blstm_9_a/cache.201 --xent-regularize=0.025 --optimization.min-deriv-time=-12 --optimization.max-deriv-time-relative=12 --print-interval=10 --momentum=0.0 --max-param-change=2.0 "nnet3-am-copy --raw=true --learning-rate=0.00339076928389 exp/chain/model/gr_tdnn_blstm_9_a/200.mdl - |" exp/chain/model/gr_tdnn_blstm_9_a/den.fst "ark,bg:nnet3-chain-copy-egs                         --left-context=4 --right-context=4                         --frame-shift=0                         ark:exp/chain/prep/gr_tdnn_blstm_9/tdnn/egs/cegs.801.ark ark:- |                         nnet3-chain-shuffle-egs --buffer-size=5000                         --srand=200 ark:- ark:- | nnet3-chain-merge-egs                         --minibatch-size=64,32 ark:- ark:- |" exp/chain/model/gr_tdnn_blstm_9_a/201.1.raw 
    
    ==> exp/chain/model/gr_tdnn_blstm_9_h/log/train.200.1.log <==
    # nnet3-chain-train --verbose=1 --apply-deriv-weights=False --l2-regularize=5e-05 --leaky-hmm-coefficient=0.1 --read-cache=exp/chain/model/gr_tdnn_blstm_9_h/cache.200 --write-cache=exp/chain/model/gr_tdnn_blstm_9_h/cache.201 --xent-regularize=0.025 --optimization.min-deriv-time=-12 --optimization.max-deriv-time-relative=12 --print-interval=10 --momentum=0.0 --max-param-change=2.0 "nnet3-am-copy --raw=true --learning-rate=0.00339076928389 --scale=1.0 exp/chain/model/gr_tdnn_blstm_9_h/200.mdl - |" exp/chain/model/gr_tdnn_blstm_9_h/den.fst "ark,bg:nnet3-chain-copy-egs                         --frame-shift=0                         ark:exp/chain/prep/gr_tdnn_blstm_9/tdnn/egs/cegs.801.ark ark:- |                         nnet3-chain-shuffle-egs --buffer-size=5000                         --srand=200 ark:- ark:- | nnet3-chain-merge-egs                         --minibatch-size=64,32 ark:- ark:- |" exp/chain/model/gr_tdnn_blstm_9_h/201.1.raw

I'll go and look where this context was added in the past.

There is nowadays also a "scale=1.0" added but that sounds like a reasonable default

**Comment by psmit** [comment]
In this recipe it seems that extra-left-context and extra-right-context are only used during decoding. Is that then incorrect? https://github.com/kaldi-asr/kaldi/blob/master/egs/swbd/s5c/local/chain/tuning/run_tdnn_blstm_1b.sh

**Comment by psmit** [comment]
I anyway will dive into my scripts to see how I generate the egs and what the context is. Is there any command available (or standard log location) to see the context that was used for generating the egs?

**Comment by danpovey** [comment]
Yes, they should have been to train.py as well, I forget the option names.  I suspect that when @GaofengCheng ran this, he was using egs dumped from elsewhere.  The invocation of train.py should use the same options.  
In addition, there should no longer be separate variables chunk_left_context and extra_left_context (and the same for right), in both 1a and 1b there should just be the variables extra_left_context and extra_right_context, and they should be passed into the training as --egs.chunk-left-context (etc.)  Also, for the scripts to really be up to date, there should be --egs.chunk-left-context-initial=0 in training (and same for right-contxt-final), and in decoding there should be
--extra-left-context-initial 0 --extra-right-context-final 0.
@GaofengCheng, would you mind fixing these issues?

**Comment by danpovey** [comment]
for the egs context you'll see it in egs-dir/log/get_egs.*.log.

**Comment by psmit** [comment]
Thanks. I'll look to this and try to update my scripts. Thanks for all the help!

**Comment by psmit** [comment]
One thing still, I don't find any other tdnn_blstm scripts I can use as example. What would be the best tdnn_lstm script to look to as example to implement the newest style of doing things?

**Comment by danpovey** [comment]
Actually, wait, those scripts that Gaofeng added are  not wrong, they are
just a little out of date.  They do have the chunk-left-context option,
it's set to 40 (same for right context).  That is reasonable--  although
for more recent commits I prefer to have just a single variable
extra_left_context, you could set it to 40 for instance, and use it for
both purposes.
But it looks to me like you might have changed that to 0 without changing
the corresponding decoding options extra_left_context and
extra_right_context.  (note: having a single variable, as I now recommend,
would prevent this kind of mistake).
I don't know if there is a fully up to date TDNN+BLSTM recipe because we
don't recommend that  configuration any more, we recommend TDNN+LSTM which
is now giving better results than TDNN+BLSTM.

**Comment by psmit** [comment]
I see now. I think earlier those options did not have any effect anymore after egs generation and they got left out from my model training recipe. I fixed that now and I am rerunning stuff.

**Comment by danpovey** [comment]
Well actually they don't have any effect in kaldi_52, they used to
previously.
So it's clear why things are different now, but it's not clear why you are
getting a degradation in test results with kaldi_52, because if anything,
since you do use extra context in test time, we'd expect passing in those
context options in the old code would have hurt results.
Anyway if you have an all-modern script, with the initial/final options set
to zero, your problems would probably disappear.

**Comment by GaofengCheng** [comment]
@danpovey
maybe the usage of left_context (for training) and extra_left_context (for decoding) (also same for right) is reasonable, using more context during decoding (50 vs 40) should not affect the WER

**Comment by GaofengCheng** [comment]
@psmit recommend TDNN-LSTM rather than TDNN-BLSTM for performance and speed

**Comment by danpovey** [comment]
@GaofengCheng, it's not harmful, but it's wasteful; and since kaldi 5.1
it's not helpful to WER (the decay-time makes it unnecessary to use extra
context).  I don't like to have out-of-date scripts be the default.

Can you please prepare a "c" version of that TDNN+BLSTM script, and look
at: egs/wsj/s5/local/chain/run_tdnn_lstm.sh for reference?  Points to note:

- frames_per_chunk is a comma-separated list, not a single number.

- there are variables chunk_left_context and chunk_right_context which are
also used in decoding.  Remove any conditional shell statements in the
decoding block about setting those context variables.

 - Options --extra-left-context-initial 0 --extra-right-context-final 0
 are used in training and decoding (the training options have different
names though).

**Comment by GaofengCheng** [comment]
@danpovey OK I'll update a new scripts together with the results， will some delay be tolerable？

**Comment by danpovey** [comment]
no problem.
