### ISSUE TITLE
get_command_stdout in common lib will not raise exception unless the last command in the pipe fails

### ISSUE THREAD

**Issue by vijayaditya** [kaldi-asr/kaldi#1666]
Unless the last command fails the exit code will be 0, this can lead to missing important error information and uninformative errors later.
e.g. in [xconfig_to_configs.py]( https://github.com/kaldi-asr/kaldi/blob/master/egs/wsj/s5/steps/nnet3/xconfig_to_configs.py#L231) though the `nnet3-info` fails there is no exception as `head -n 4` will return with exit code 0.

**Comment by vijayaditya** [comment]
Is using `set -o pipefail` a possible solution  ?

**Comment by danpovey** [comment]
It's hard to fix this generically.
set -o pipefail doesn't work in dash, and we try to support systems where
/bin/sh is dash.
maybe best to fix it in the particular case.

**Comment by vijayaditya** [comment]
OK.
