### ISSUE TITLE
 two problems about Build  it on windows2013 and openblas

### ISSUE THREAD

**Issue by wuqiangch** [kaldi-asr/kaldi#1667]
Hi everyone:
1、Build started: Project: fsts-difference, Configuration: Release x64 ------
193>  fsts-difference.cc
193>c1xx : fatal error C1083: Cannot open source file: '..\..\..\src\fstbin\fsts-difference.cc': No such file or directory
2、Build started: Project: fsts-to-transcripts, Configuration: Release x64 ------
195>  fsts-scale.cc
195>c1xx : fatal error C1083: Cannot open source file: '..\..\..\src\fstbin\fsts-scale.cc': No such file or directory

where can i find the two files??

**Comment by danpovey** [comment]
I'm afraid the Windows build is not working at the moment.  Those files
were removed but maybe they are still present in the solution file.
Hopefully Yenda will fix it at some point but it's not a super high
priority.

**Comment by wuqiangch** [comment]
@danpovey Thanks very much!   I am study the egs/sre10/v1 and v2. I want to use my trained model to create a demo project. Likely,the input of the demo is a wav file and  the output of the demo is the feature of the wav file. Where can i find the reference material? Can you help me? Thanks!!

**Comment by jtrmal** [comment]
you could use the branch 5.0, but lot of things was improved in the newer
versions. For your purposes, it should be fine, though.
y.
