### ISSUE TITLE
–self-loop-scale 1.0  in chain training and decoding

### ISSUE THREAD

**Issue by yujunlhz** [kaldi-asr/kaldi#1668]
Dear Kaldi developers:
I notice the following statement in chain document:
"By default when we compile the graph, we use a 'self-loop-scale' of 0.1. This affects how the transition probabilities on self-loops are treated (it generally works better). However, for the 'chain' models, because of how they were trained, we need to use exactly the same transition-probability scaling we trained with, which for simplicity we have set to 1.0. So we supply the option –self-loop-scale 1.0 to the utils/mkgraph.sh script."

However, in the script:
egs/swbd/s5c/local/chain/run_tdnn_blstm.sh

I notice only in the decoding, there is " –self-loop-scale=1.0",  in the training, I don't see it anywhere, but its default value 0.1.  

Am I missing something?

Thanks
yujunlhz

**Comment by danpovey** [comment]
It's hardcoded in the training, it takes place at the C++ level.
Dan
