### ISSUE TITLE
Installation of sequitur and mmseg fails (Prerequisites for GALE Mandarin)

### ISSUE THREAD

**Issue by akshayc11** [kaldi-asr/kaldi#1672]
I am not sure if this is system dependent, but here is my setup:
I have a custom pythonpath where I have installed virtualenv, from which I have created a separate virtual environment.

When I try to run 
```
cd $KALDI_ROOT/tools
extras/install_sequitur.sh
```

I noticed that the installation script expects the setup.py to install the libraries at <sequitur_dir>/lib
However, the system installs it in <sequitur_dir>/lib64
A similar problem arose in the installation of mmseg 
```
extras/install_mmseg.sh
```

Changing the installation lines that refer to lib/ to lib64/ fixed that issue for me. 

I have attached a patch that I have created for that here. If you think this should be done, please feel free to apply the patch and commit it.

[fix_extra_tool_install.patch.txt](https://github.com/kaldi-asr/kaldi/files/1062037/fix_extra_tool_install.patch.txt)

Akshay

**Comment by jtrmal** [comment]
this is definitely system dependent. The patch itself is not
valid for other systems.
what system do you use?
y.

**Comment by danpovey** [comment]
The sequitur installation commands in install_sequitur.py explicitly select
the current directory as the installation target:

cd sequitur-g2p
make CXX=g++ CC=gcc
python setup.py install --prefix `pwd`

cd ../

So I don't understand why it would install in lib64.
Dan

**Comment by akshayc11** [comment]
When you specify the prefix, I believe the setup.py creates a lib (in my case lib64) folder, into which it installs the python-specific site-packages. I believe the issue may be arising due to something akin to this: https://github.com/Linuxbrew/legacy-linuxbrew/issues/443 

This is being run on a centOS (which is an RHEL fork)

One of the comments in the above issue was:
```
Looking at the Python bug tracker, this appears to be a change that certain Linux vendors make to their system Pythons to support mixed 32/64-bit systems. OpenSuSE does this; Ubuntu trusty (afaict, in my hands) does not. Apparently RHEL does. Linuxbrew or pyenv pythons should not.
```

I guess I am one of the unlucky few facing this issue.

**Comment by danpovey** [comment]
Hm.  If some OSs still do this, I think it might be worthwhile fixing it in
some way.  @jtrmal, any chance you could make an 'issue'?  Unless you
disagree.

**Comment by jtrmal** [comment]
I will. I think it should be fairly easy to fix -- will look into it.
y.

**Comment by jtrmal** [comment]
I created a fix for that. it would be great if @akshayc11  could test for lib64 case -- I tested for debian and seems to work for lib/ case.
y.

**Comment by akshayc11** [comment]
@jtrmal I tested the PR, and have added some comments there... Once those are addressed, I think the issue is fixed.
