### ISSUE TITLE
Question about egs/callhome_diarization 

### ISSUE THREAD

**Issue by YichiHuang** [kaldi-asr/kaldi#1675]
Hi,
I have a question about the script `egs/callhome_diarization/v1/local/make_callhome_test.sh`.
What's the meaning of `segments, seg2utt,utt2num`? Can you give me a format or example of the content in these files?
Thanks.

**Comment by david-ryan-snyder** [comment]
@YichiHuang,

This recipe is _not_ part of the main branch of Kaldi master. You might've found some partial work in one of my personal branches. Which branch were you looking at?

**Comment by YichiHuang** [comment]
@david-ryan-snyder 

Yes, I find this recipe in your personal branch.  The repository is `david-ryan-snyder/kaldi` with branch `kaldi-diarization-v3`.

**Comment by david-ryan-snyder** [comment]
That script you pointed to isn't used anywhere in that recipe (look in the run.sh). It's a leftover from some previous work.

Keep in mind that what you found is _work in progress_ in a personal branch that isn't intended for public use. If any of this recipe makes its way into the Kaldi master branch it may look significantly different from what you found and you can certainly expect better documentation etc.
