### ISSUE TITLE
Fix name 

### ISSUE THREAD

**Issue by Miail** [kaldi-asr/kaldi#1678]
https://github.com/kaldi-asr/kaldi/blob/85a3dd5f0b71e419abf1169a26b759bfc423a543/src/bin/analyze-counts.cc#L46

`ali-to-phone` doesn't exist, but` ali-to-phones` does.

**Comment by danpovey** [comment]
Do you know git/github well enough to create a pull request to fix this?

**Comment by danpovey** [comment]
forget it, i'll fix it myself with something else.
