### ISSUE TITLE
Non-windows filenames in egs/babel/s5d/results/

### ISSUE THREAD

**Issue by kkm000** [kaldi-asr/kaldi#1687]
In the directory in egs/babel/s5d/results/ there are 30 or so text files with the `:` in the name that cause error when checking out on Windows:
```
error: unable to create file egs/babel/s5d/results/kws_results.104-pashto.flp.marcc2.conf.jtrmal1@jhu.edu.2016-03-31T11:34:24-04:00: Invalid argument
```
Unlike Linux, Windows file name cannot contain a `:`. Is it ok to rename these? Are the filenames parsed by anything? And if the rename is possible, then the program that generates the names must also be updated.

**Comment by danpovey** [comment]
Fine to rename.  BABEL is over so we won't be adding more, most likely.

On Wed, Jun 14, 2017 at 6:10 PM, Kirill Katsnelson <notifications@github.com

**Comment by jtrmal** [comment]
I have renamed these files in my local repo a couple of weeks back but
didn't create pr, yet. Feel free to rename if you don't want to wait. The
naming is not important at all.
Y.
