### ISSUE TITLE
Remove unused feature types in nnet3 scripts

### ISSUE THREAD

**Issue by danpovey** [kaldi-asr/kaldi#1705]
In nnet3 scripts, sometimes we have "feature_type" which can be raw, or lda, and if lda, then "transform_dir" option is accepted.
I believe this is never used.
I'd like to have these options (and any use of them) removed to keep the scripts simple.
@LvHang, can you please look at this?
Search for "raw".

**Comment by LvHang** [comment]
ok，i will do that

Daniel Povey <notifications@github.com>于2017年6月21日 周三00:44写道：

**Comment by LvHang** [comment]
Hi Dan,
I think the "lda" feature has become a component of nnet3. Its format looks like
`fixed-affine-layer name=lda input=Append(-1,0,1,ReplaceIndex(ivector, t, 0)) affine-transform-file=$dir/configs/lda.mat`
So the shell scripts are out-of-date. We needn't judge the "feature_type" is raw or lda.
So you want me delete the "lda" branch and the unnecessary option "transform_dir", right?
Hang

**Comment by danpovey** [comment]
Yes, delete the "lda" branch.  You can also remove the feature-type option
that defaults to raw, but be sure to check whether any scripts try to set
it.

**Comment by LvHang** [comment]
Ok, get it. I will deal with it and test.

**Comment by danpovey** [comment]
addressed in #1711
