### ISSUE TITLE
Get the state alignment from the lattice.

### ISSUE THREAD

**Issue by Coastchb** [kaldi-asr/kaldi#1735]
Hi,
I have decode the utterance and get the corresponding lattice. How can I get the state alignment of the decoding results?
Thanks.

**Comment by danpovey** [comment]
You could turn the lattices into alignments using (lattice-1best then
lattice-to-linear), or lattice-best-path.  That will give you
transition-ids, you can turn them into pdf-ids (which correspond to
clustered states) with ali-to-pdf, or to phones with ali-to-phones.
Be careful to get the --lm-scale option to lattice-1best or
lattice-best-path right, it should match the LM scale that was used for the
best decoding result, in scoring.

**Comment by Coastchb** [comment]
Thank you, Povey.
