### ISSUE TITLE
Missing fstext/remap-leaves-inl.h

### ISSUE THREAD

**Issue by kkm000** [kaldi-asr/kaldi#1745]
The file `remap-leaves-inl.h` [included from `remap-leaves.h`](https://github.com/kaldi-asr/kaldi/blob/master/src/fstext/remap-leaves.h#L87) is nowhere to be found, not even in the [initial commit](https://github.com/kaldi-asr/kaldi/tree/10e9002c8800dbde67592b2232cc06e37620564e/src/fstext). The header seems to relate to factoring the F transducer from the original HBKA. Delete fstext/remap-leaves.h?

**Comment by danpovey** [comment]
yes, that file should be deleted-- done.  Thanks!
