### ISSUE TITLE
Make the combine stage optional

### ISSUE THREAD

**Issue by danpovey** [kaldi-asr/kaldi#1748]
Sometimes it seems like the model-combination is more trouble than it's worth.
I'd like a mechanism to disable it.  This applies to all the training scripts
`steps/nnet3/train_{,raw_}{rnn,dnn}.py steps/nnet3/chain/train.py`.
It could be put with the other combination-related options, e.g. as
`--trainer.optimization.do-final-combination`, defaulting to true.
If the option is set to false, for now just copy the last-numbered model to final.mdl.
This may affect the logic about which models to keep during training.

@LvHang, can you please do this?

**Comment by LvHang** [comment]
OK，i will do that


Daniel Povey <notifications@github.com>于2017年7月8日 周六16:14写道：

**Comment by david-ryan-snyder** [comment]
@LvHang, @danpovey, I think this issue might've been solved in https://github.com/kaldi-asr/kaldi/pull/1757.
