### ISSUE TITLE
Downsampling in feature extraction

### ISSUE THREAD

**Issue by danpovey** [kaldi-asr/kaldi#1754]
@pegahgh, can you please do this in the next few days?

I would like to make it possible to do downsampling automatically in feature extraction.

Please add to FrameExtractionOptions, a boolean option allow_downsample
(default: false), with documentation:
```
 "If true, allow the input waveform to have a higher frequency than "
 "the specified --sample-frequency (and we'll downsample)."
```

And modify OfflineFeatureTpl as follows:

First,  an unrelated change.  Remove the 'deprecated_wave_remainder' argument to
the Compute function and check that Kaldi still compiles, including the optional
extras online and onlinebin.  (the same for the const version.)
And change the comment for this version of Compute() to:

```
  // Internal (and back-compatibility) interface for computing features, which
  // requires that the user has already checked that the sampling frequency
  // of the waveform is equal to the sampling frequency specified in
  // the frame-extraction options.
```

Then, add another interface that requires the user to specify the
sampling frequency:

```
  /// Computes the features for one file (one sequence of features).  
  /// This is the newer interface where you specify the sample frequency
  /// of the input waveform.
  ///   @param [in] wave   The input waveform
  ///   @param [in] sample_freq  The sampling frequency with which
  ///                                     'wave' was sampled.
  ///  @param [in] vtln_warp  The VTLN warping factor (will normally
  ///                                   be 1.0).
  ///   @param [out]  output  The matrix of features, where the row-index
  ///                                is the frame index.
  void ComputeFeatures(const VectorBase<BaseFloat> &wave,
               BaseFloat sample_freq,
               BaseFloat vtln_warp,
               Matrix<BaseFloat> *output);
```

This function will check the sample frequency: if it's the same as
`computer_.GetFrameOptions().samp_freq`, then it will just call Compute();
if it's greater than that and allow_downsample is true, then downsample
the entire wave file and call the older Compute() version; else crash 
with a suitable error message.

There will also be a const version which will call the other
version of ComputeFeatures() with a copy of *this.
```
 /// This const version of ComputeFeatures() is a wrapper that
 /// calls the non-const ComputeFeatures() on a temporary object
 /// that is a copy of *this.  It is not as efficient because of the 
 /// overhead of copying *this.
  void ComputeFeatures(const VectorBase<BaseFloat> &wave,
               BaseFloat sample_freq,
               BaseFloat vtln_warp,
               Matrix<BaseFloat> *output) const;
```

The calling code, in compute-mfcc-feats and similar, will be simplified
so that instead of checking the sample frequency, it just provides it to the
newer interface.

**Comment by pegahgh** [comment]
sure, will do that tonight!

**Comment by david-ryan-snyder** [comment]
@pegahgh, @danpovey, In the interest of closing open tickets, didn't this feature get implemented in https://github.com/kaldi-asr/kaldi/pull/1773?
