### ISSUE TITLE
Removal of comments from STM files while using utils/subset_data_dir.sh

### ISSUE THREAD

**Issue by akshayc11** [kaldi-asr/kaldi#1765]
I noticed that when using utils/subset_data_dir.sh, the script chooses not to copy over the comments from the original stm file to the new stm file. However, when I used score_sclite.sh with a subsetted custom dataset (I can't release more detail right now), I got some errors in the scoring:
```Error: Label id ‘o’ lookup failed for utt (....)```
On adding the comments in the original STM back to the script, I was able to resolve the issue.

I propose to make a modification to the utils/subset_data_dir.sh that will first copy over all the comments from the stm file, and then copy over the filtered utterances.

Please let me know if this is a general problem, and then, I can create a merge request to solve it.

Thanks

Akshay

**Comment by danpovey** [comment]
That sounds reasonable.

**Comment by akshayc11** [comment]
Also, another thing I noted was that when you specify the speaker list, for the stm files, if a given audio file has more than one speakers, the stm subset created is derived from all the utterances with the same recording ID, irrespective of whether or not the speaker was selected to be in the subset, and would cause erroneous word error rates to be reported. 

I will create a merge request which addresses both of these issues.

**Comment by danpovey** [comment]
I just noticed your extra comment.
Don't check in the extra stuff about adding extra speakers, I don't think it exactly does the right thing either as speakers can be in multiple recordings.  I think if someone wants to do something sensible in this scenario they should be specifying utterance subsets, not speaker subsets.
Doing the right thing with stm's is not a super high priority as it relates to the NIST scoring tools and not to any of Kaldi's functionality, and I don't want to make the scripts too complex.

**Comment by akshayc11** [comment]
Got it. I will only perform the changes mentioned in the  original comment.
