### ISSUE TITLE
a question about function add-self-loops in utils/mkgraph.sh

### ISSUE THREAD

**Issue by boji123** [kaldi-asr/kaldi#1793]
I have seen the code in utils/mkgraph.sh , line131 , the code like 

`if [[ ! -s $dir/HCLG.fst || $dir/HCLG.fst -ot $dir/HCLGa.fst ]]; then
  add-self-loops --self-loop-scale=$loopscale --reorder=true\
    $model < $dir/HCLGa.fst > $dir/HCLG.fst || exit 1;`

And I'm reall confuse on the option '--reorder=true' .(the function add-self-loops is in src/bin)
In my test , when the option is 'false' , the number of fst arc is smaller than 'true' (about 10%), but the comment in function add-self-loops is : 'If true, reorder symbols for more decoding efficiency'

Can any one tell me something? Really appreciate.

**Comment by danpovey** [comment]
The efficiency issue is not about size, it's about decoding speed/accuracy tradeoff.  kaldi-asr.org/forums.html tells you how to ask questions.
