### ISSUE TITLE
Nvidia driver 384.59 crashes when using tdnn/lstm/blstm scripts

### ISSUE THREAD

**Issue by Potomac** [kaldi-asr/kaldi#1802]
Hello,

the recent nvidia driver ( 384.59 version ) released at end of july 2017 seems to react badly with kaldi scripts for the GPU training,

I get a random crash of the nvidia driver when I use kaldi script for the GPU training ( for example run_tdnn.sh, run_lstm.sh during the step with train.sh or train_rnn.py ), after several hours of training with 2 GPU cards the nvidia driver triggers a general protection fault,

more information here : 

https://devtalk.nvidia.com/default/topic/1021605/linux/nvidia-driver-384-59-triggers-a-kernel-crash-when-we-use-kaldi-software/

I have tested with a version of kaldi compiled on may 2017, not sure if the same problem exists with the last git version of kaldi,

it's a random bug, not easy to trigger, I have experienced this bug on a cluster ( grid5000 ) where PCs have 2 GPU card,

if I install an older nvidia driver ( 366.xx, 375.xx versions ) then there is no bug

**Comment by Potomac** [comment]
the crash log
[crash-log.txt](https://github.com/kaldi-asr/kaldi/files/1207319/crash-log.txt)

**Comment by danpovey** [comment]
Thanks for reporting the problem.  I'm bringing it to the attention of
someone in NVidia.  This is not the kind of thing we can help debug-- it's
obviously a bug in the driver.

**Comment by danpovey** [comment]
I noticed the conversatin on the NVidia forum.  I wonder if you could
reproduce this with mini_librispeech, it might be faster?
Also to help him reproduce it, look into the num-GPUs
(num-jobs-initial/final) and whether or not exclusive mode is set.

**Comment by Potomac** [comment]
I don't know mini_librispeech, you mean this script ? : 

https://github.com/kaldi-asr/kaldi/blob/master/egs/mini_librispeech/s5/run.sh 

is it faster to execute than tedlium/s5_r2 scripts ?

**Comment by danpovey** [comment]
Yes it's faster, it has much less data.

**Comment by Potomac** [comment]
Hello,

I tried the new nvidia driver 384.66 and it solves the bug :

http://www.nvidia.fr/download/driverResults.aspx/122968/fr

no problems with 384.66 driver

**Comment by danpovey** [comment]
Great-- thanks for letting us know!
