### ISSUE TITLE
Parameter sharing support in xconfig

### ISSUE THREAD

**Issue by vijayaditya** [kaldi-asr/kaldi#1804]
I plan to add parameter sharing support in xconfig. This has come up as one of the requirements during the JSALT workshop.

I plan to do it as follows, let me know if this is fine.

I will add support for another key in the input dictionary `parameter_name`, which will default to `name`.  Also I will assert that `parameter_name` exists in one of the `prev_layer.name`.

This `parameter_name` will be used for all the `component name={0}` lines in the configs.

[Relevant line in code.](https://github.com/kaldi-asr/kaldi/blob/master/egs/wsj/s5/steps/libs/nnet3/xconfig/basic_layers.py#L40)

**Comment by danpovey** [comment]
Did anyone actually end up building a recipe that relied on this?
I'm not sure that I agree with this change.  My concern is that it will
make the xconfig scripts more complicated and will be hard to support when
we make other changes.  Do we have a concrete use-case that makes sense?
My recollection is that there was a better way to do waht Sriram wanted to
do, using the 'x' index, that would not require any parameter sharing.

**Comment by vijayaditya** [comment]
The only use case is that of Sriram's. He decided to pursue this route due to lack of time for writing up the 'x' index version. 

I will just point him to my branch for his immediate needs.
