### ISSUE TITLE
travis compile or test times out

### ISSUE THREAD

**Issue by kkm000** [kaldi-asr/kaldi#1805]
Opening a separate issue to track this, xref #1783.

I made some modifications to the script under travis to not compile fst binaries. That shaved a few minutes off it, but this is not an entire solution.

I tried to use ccache, which reduced the `make all` time from 6:25 (with ccache enabled and empty cache) to 0:47 (cache warm) on my machine, absent any source changes. I hoped with the cache warm the build will take a shorter time, but the catch 22 is travis does not save the cache directory when a run times out, so the next compile starts with the blank slate. I'll see if it is possible to force travis to push the cache explicitly after compile but before running tests.

Another thing I am going to try is skip linking the binaries (compile only). I can think of bugs that would slip through the holes this way, but there are potential much worse ones that would not be caught even by linking anyway.

Other ideas welcome.

/cc @dogancan @jtrmal

**Comment by jtrmal** [comment]
I just recalled there was another thing we were discussing -- as we do not
patch openfst now, we could pull in the system package (if available). I
think compilation of that takes a fair amount of time as well (even though
that one can be almost completely cached by ccache)
y.

**Comment by kkm000** [comment]
I thought about this too, but the way I run configure now on OpenFST in my changeset (disable dep check and binaries) has shortened the compile time to a few seconds. No magic, since there are only 5 or 6 small cc files to compile.

**Comment by jtrmal** [comment]
all right, probably not worth the effort at all. y.

On Tue, Aug 15, 2017 at 2:38 PM, Kirill Katsnelson <notifications@github.com
