### ISSUE TITLE
python bindings for feature extractors

### ISSUE THREAD

**Issue by stefbraun** [kaldi-asr/kaldi#1807]
Hi all,

```kaldi``` is an amazing tool and I consider the feature extractors provided by ```kaldi``` as reference. The feature extractors from ```featbin``` generally work on ```.wav``` files from the hard disk and output ```.ark``` files to the hard disk. It would be amazing to have a python module ```kaldi_features``` that allows to:
- call a kaldi feature extraction routine in python, e.g. ```kaldi_features.compute-fbank-feats```
- directly provide the features in memory --> no time consumed to write a file to the hard disk, no python wrappers such as [[1]](https://github.com/janchorowski/kaldi-python), [[2]](https://github.com/vesis84/kaldi-io-for-python)  for reading ```.ark``` files required

I think that a lot of people in the python-loving deep learning world would appreciate this.

I would consider working on it, can someone give me a hint where to start with?

**Comment by danpovey** [comment]
Hm.  We've generally avoided adding python bindings as it would be extra
stuff to maintain, and it was never clear what was the right way to call
C++ (esp. templated C++) from python.

My feeling is that if all you need is the features, a better solution would
be to just implement that directly in python.  The feature processing code
really isn't that complicated, it's maybe simpler than dealing with all the
linking and wrapping issues.  Small differences may actually be harmless
and inconsequential (such as what you pointed out with the mel filterbanks).

**Comment by stefbraun** [comment]
Fair point, thanks a lot!
