### ISSUE TITLE
RNNLM feature scales

### ISSUE THREAD

**Issue by danpovey** [kaldi-asr/kaldi#1813]
@wantee, I'm having problems with instability in the sparse-word-feature version of RNNLM training.  I was able to work around the problem by scaling the constant feature down and by removing the length feature and the unigram feature, but I think we need a more general solution.

My proposal is that all the features be given a scaling factor (e.g. an extra field in features.txt), that the choose_features.py script be given an option --max-feature-rms (example default: 0.01), representing the maximum allowed root-mean-square value (i.e. uncentered standard deviation) of any feature; and that the scaling factors will all be 1.0 by default but then will be made smaller than 1.0 as needed to ensure that the RMS value of that feature not exceed the max-feature-rms.  

This will obviously require changes to various scripts.  Can you please work on the changes required to make this work, assuming you have time?
The only thing which might not be clear is what to do with the unigram-prob feature.  I recommend to subtract the negative-entopy from it, and then compute the scaling factor according to the --max-feature-rms limitation.

**Comment by wantee** [comment]
OK. Will do.

**Comment by danpovey** [comment]
addressed.
