### ISSUE TITLE
copy-feats cannot extract vad.ark files but can do so for features

### ISSUE THREAD

**Issue by chananshgong** [kaldi-asr/kaldi#1817]
I would like to export the VAD to view it in Audacity.
However, when I call copy-feats with a vad file it fails.
When a feature ark file is used it works fine.
```
copy-feats ark:mfcc/vad_train.2.ark ark,t: 
/kaldi/src/featbin/copy-feats ark:mfcc/vad_train.2.ark ark,t: 
ERROR (copy-feats[5.2.93-d117a]:Read():kaldi-matrix.cc:1463) Failed to read matrix from stream.  : Expected token FM, got FV File position at start is 42, currently 45
```
My guess it assumes it is a matrix instead of a vector.
Any work around please?

Thanks!

**Comment by jtrmal** [comment]
I believe you have to use copy-vector
y.

**Comment by danpovey** [comment]
actually it might be copy-int-vector.

**Comment by KrishnaDNkrishna** [comment]
copy-int-vector doesn't work. copy-vector works.

**Comment by Madhurananda** [comment]
copy-vector also worked for me, copy-int-vector didn't.
