### ISSUE TITLE
online2-wav-nnet3-latgen-faster: timestamps with transcript

### ISSUE THREAD

**Issue by fzliu** [kaldi-asr/kaldi#1823]
Hey folks - new Kaldi user here. I've been following the introduction as per https://chrisearch.wordpress.com/2017/03/11/speech-recognition-using-kaldi-extending-and-using-the-aspire-model/, and was wondering if there's a way to generate timestamped transcripts. Specifically, can Kaldi output the timestamp of each utterance along with the predicted transcript?

**Comment by danpovey** [comment]
It is possible- you'd normally do it as post-processing on the lattice,
e.g. see steps/get_ctm.sh, you can see the sequence of binaries in there.
See kaldi-asr.org/forums.html for how to ask questions.

**Comment by fzliu** [comment]
Was about to close this and re-post the question on the forum. Thanks for your help!
