### ISSUE TITLE
Error opening stream <filename.wav>

### ISSUE THREAD

**Issue by pranjaldaga** [kaldi-asr/kaldi#1825]
I am following https://chrisearch.wordpress.com/2017/03/11/speech-recognition-using-kaldi-extending-and-using-the-aspire-model/ to set up and work with the ASpIRE model.

When I am trying to transcribe my 8khz waveform using:
```
online2-wav-nnet3-latgen-faster \
  --online=false \
  --do-endpointing=false \
  --frame-subsampling-factor=3 \
  --config=exp/tdnn_7b_chain_online/conf/online.conf \
  --max-active=7000 \
  --beam=15.0 \
  --lattice-beam=6.0 \
  --acoustic-scale=1.0 \
  --word-symbol-table=exp/tdnn_7b_chain_online/graph_pp/words.txt \
  exp/tdnn_7b_chain_online/final.mdl \
  exp/tdnn_7b_chain_online/graph_pp/HCLG.fst \
  'ark:echo utterance-id1 utterance-id1|' \
  'scp:echo utterance-id1 <my_8khz_file.wav>|' \
  'ark:/dev/null'
```
I am receiving the following error:
"
LOG (online2-wav-nnet3-latgen-faster[5.2.94]:ComputeDerivedVars():ivector-extractor.cc:183) Computing derived variables for iVector extractor
LOG (online2-wav-nnet3-latgen-faster[5.2.94]:ComputeDerivedVars():ivector-extractor.cc:204) Done.
LOG (online2-wav-nnet3-latgen-faster[5.2.94]:RemoveSomeNodes():nnet-nnet.cc:916) Removed 2 orphan nodes.
LOG (online2-wav-nnet3-latgen-faster[5.2.94]:RemoveOrphanComponents():nnet-nnet.cc:841) Removing 2 orphan components.
LOG (online2-wav-nnet3-latgen-faster[5.2.94]:Collapse():nnet-utils.cc:770) Added 1 components, removed 2
LOG (online2-wav-nnet3-latgen-faster[5.2.94]:CompileLooped():nnet-compile-looped.cc:336) Spent 0.0500209 seconds in looped compilation.
WARNING (online2-wav-nnet3-latgen-faster[5.2.94]:HasKeyInternal():util/kaldi-table-inl.h:1769) Error opening stream my_8khz_file.wav
ERROR (online2-wav-nnet3-latgen-faster[5.2.94]:Value():util/kaldi-table-inl.h:1681) Could not get item for key utterance-id1, rspecifier is scp:echo utterance-id1 my_8khz_file.wav| [to ignore this, add the p, (permissive) option to the rspecifier.

[ Stack-Trace: ]

kaldi::MessageLogger::HandleMessage(kaldi::LogMessageEnvelope const&, char const*)
kaldi::MessageLogger::~MessageLogger()
kaldi::RandomAccessTableReaderScriptImpl<kaldi::WaveHolder>::Value(std::string const&)
kaldi::RandomAccessTableReader<kaldi::WaveHolder>::Value(std::string const&)
main
__libc_start_main
online2-wav-nnet3-latgen-faster() [0x490a39]
"

My guess is that there is a problem in interacting with the server. Can anyone let me know how to get around this issue?

Thanks!

**Comment by danpovey** [comment]
It's saying it can't find the file  my_8khz_file.wav.  Maybe it's about what directory it's in.  But this isn't the right place for questions, that script didn't come from us, ask that guy on his blog.  Plus, it's a trivial issue.

**Comment by pranjaldaga** [comment]
Got it! Thanks!
