### ISSUE TITLE
Problem installing Kaldi, related to OpenFST?

### ISSUE THREAD

**Issue by kkoenen** [kaldi-asr/kaldi#1826]
When I try to install Kaldi, I get this OpenFST related error. The error also shows when I try to install OpenFST by hand (1.6.3.) Please advice, thank you.

fst_test.o: In function `fst::internal::CompactFstImpl<fst::ArcTpl<fst::TropicalWeightTpl<float> >, fst::(anonymous namespace)::CustomCompactor<fst::ArcTpl<fst::TropicalWeightTpl<float> > >, unsigned short, fst::DefaultCompactStore<std::pair<int, fst::TropicalWeightTpl<float> >, unsigned short>, fst::DefaultCacheStore<fst::ArcTpl<fst::TropicalWeightTpl<float> > > >::Init(fst::Fst<fst::ArcTpl<fst::TropicalWeightTpl<float> > > const&, std::shared_ptr<fst::DefaultCompactStore<std::pair<int, fst::TropicalWeightTpl<float> >, unsigned short> >)':
fst_test.cc:(.text+0x3c35f): undefined reference to `fst::Int64ToStr(long, std::string*)

make[3]: Entering directory '/home/kkoenen/stt/kaldi-master/tools/openfst-1.6.2/src/test'
/bin/bash ../../libtool  --tag=CXX   --mode=link g++  -std=c++11   -o fst_test fst_test.o ../lib/libfst.la -lm -ldl 
libtool: link: g++ -std=c++11 -o .libs/fst_test fst_test.o  ../lib/.libs/libfst.so -lm -ldl -Wl,-rpath -Wl,/home/kkoenen/stt/kaldi-master/tools/openfst-1.6.2/lib
Makefile:645: recipe for target 'fst_test' failed
make[3]: Leaving directory '/home/kkoenen/stt/kaldi-master/tools/openfst-1.6.2/src/test'
Makefile:1054: recipe for target 'check-am' failed
make[2]: Leaving directory '/home/kkoenen/stt/kaldi-master/tools/openfst-1.6.2/src/test'
Makefile:358: recipe for target 'check-recursive' failed
make[1]: Leaving directory '/home/kkoenen/stt/kaldi-master/tools/openfst-1.6.2/src'
Makefile:414: recipe for target 'check-recursive' failed

**Comment by danpovey** [comment]
Check that your disk isn't full, and then try just ignoring the error and
continuing to install Kaldi.  You may have to do "make -k" in tools/, to
install other things that come after OpenFst.  You seem to be getting a
failure in the 'make test' of OpenFst, so it may not be fatal for Kaldi.
Search for
"undefined reference" in
http://www.openfst.org/twiki/bin/view/Forum/FstForumArchive2012
and you'll see a similar error which seems to be about link order, but I'd
be surprised if that was wrong in the OpenFst archive.
If it still fails, let us know what your OS is and what gcc version you
have.

Dan

**Comment by kkoenen** [comment]
TY! Tried 'make -k' in tools and then make in kaldi-master/src. Same error :(

Ultimately, I'm trying to get KaldiNL-master to work. For now, all the steps seem ok. But when I try to transcript a .wav file, the log shows:

`# extract-segments scp,p:/home/kkoenen/stt/output/intermediate/data/ALL/wav.scp /home/kkoenen/stt/output/intermediate/data/ALL/log/segments.1 ark:- | compute-mfcc-feats --verbose=2 --config=/home/kkoenen/stt/output/intermediate/mfcc.conf ark:- ark:- | copy-feats --compress=true ark:- ark,scp:/home/kkoenen/stt/output/intermediate/mfcc/raw_mfcc_ALL.1.ark,/home/kkoenen/stt/output/intermediate/mfcc/raw_mfcc_ALL.1.scp 
# Started at Wed Aug 16 21:41:54 CEST 2017
#
bash: line 1: extract-segments: command not found
bash: line 1: compute-mfcc-feats: command not found
bash: line 1: copy-feats: command not found
# Accounting: time=0 threads=1
# Ended (code 127) at Wed Aug 16 21:41:54 CEST 2017, elapsed time 0 seconds`

So I started researching, most probable cause was OpenFST not correctly installed. But maybe I'm on the wrong track? Any help is higly appreciated.. I've been at it for quite some days now.

You asked about OS and gcc version:
GCC
gcc (Ubuntu 5.4.0-6ubuntu1~16.04.4) 5.4.0 20160609
OS:
Description:    Ubuntu 16.04.3 LTS
Release:        16.04
Codename:       xenial

**Comment by danpovey** [comment]
You didn't say if Kaldi itself failed to compile e.g. if a file
src/*/extract-segments exists and is runnable then there is probably  no
problem except that you have not set up your path correctly.
