### ISSUE TITLE
Haskell bindings for kaldi

### ISSUE THREAD

**Issue by dfordivam** [kaldi-asr/kaldi#1831]
Hi

Are there any haskell bindings for using Kaldi with Haskell.
If there aren't any, I can try to create them.

The minimum required from such a bindings is to initialise the Kaldi (using the config files) and do speech recognition on an input pcm data.

More elaborate bindings will support tweaking the different parameters of Kaldi framework and ensure the things are connected properly by using static types.

**Comment by danpovey** [comment]
definitely not.  We don't even have python bindings so haskell are definitely not on the agenda.  I think you might not really appreciate what Kaldi is all about and how it is used.   it would be way too much work to do this.
