### ISSUE TITLE
Kaldi for Indian Languages 

### ISSUE THREAD

**Issue by ramaseshan** [kaldi-asr/kaldi#1837]
I have been experimenting kaldi and it looks pretty neat. Just wondering if someone had already tried this with any Indian languages, (possibly Kannada/Hindi) .
If not, if I am just referring to http://kaldi-asr.org/doc/kaldi_for_dummies.html and replacing the data there with local language words would it just work ? I am not sure, how well does the characters would represent. 
If someone could give me some tips/steps to proceed, it could helpful.

#newbie_question

**Comment by vijayaditya** [comment]
ASR and Keyword search recipes exist for some Indian languages in the IARPA
Babel program. I am not sure if this data is available for non participants
but the language agnostic recipes are available in egs/babel.

**Comment by ramaseshan** [comment]
@vijayaditya  I have a list of wav files and their translations available with me. Cant I just build up on top of that ?

**Comment by vijayaditya** [comment]
Just saw that this has been raised as an issue. kaldi-help google group is more appropriate for this discussion. Closing this issue.

I don't think the scripts are designed for such generic system building effort. However
the appropriate top level script which uses a graphemic lexicon is available [here](https://github.com/kaldi-asr/kaldi/blob/master/egs/babel/s5d/run-1-main-unicode.sh).
You can follow the relevant steps from there. 
 
You would definitely have to do data preparation and this forum might not be suitable for any hand-holding there.

**Comment by jhansiprs** [comment]
Dear Rama

I have work on Hindi speech on Kaldi. And it work perfectly.


If you need any help you can search for my paper.
"Continuous hindi speech recognition model based on kaldi asr toolkit"
In which I have designed the model for 100 speaker. More detail can be
found in the paper.


Thanks and Regards
Prashant Upadhyaya
Aligarh Muslim University

**Comment by easyash** [comment]
Hi Prashant,

I am trying to setup Kaldi toolkit ( and I am totally new to ASR or anything related).  I tried demo under egs folder and voxfrog/online_demo.  Here without live it works and with live( trying to use my mic it does not work, gives a portaudio related error).  This I am trying for Indian language.  Appreciate if you can share a working example with me, so that I can learn by experimenting.  Let me know please.

Regards,
Ashok

**Comment by danpovey** [comment]
That microphone stuff is still there only for legacy reasons and is not really supported any more; we decided to focus on the core ASR and not get involved in data-capture issues.  I recommend to learn in other ways, e.g. the "kaldi for dummies" tutorial.

**Comment by jhansiprs** [comment]
Dear Ashok Sir,

I think Daniel sir has already answered the question.

I think you can follow the same tutorial "kaldi for dummies" it is very
good tutorial.

Please follow these link
http://kaldi-asr.org/doc/kaldi_for_dummies.html
http://www.danielpovey.com/kaldi-lectures.html
https://www.eleanorchodroff.com/tutorial/kaldi/kaldi-intro.html.

As you mention you have been new in the field of ASR, I would suggest do
some preliminary reading on ASR, it will brush up your knowledge and the go
for the implementation of ASR using an of the toolkit like Kaldi, HTK or
Sphinx.

Please follow the lectures slides (
http://www.danielpovey.com/kaldi-lectures.html) it will really helpful.

Hope I have tried to explain you questions in simple way.

Thanks and Regards

Prashant upadhyaya
