### ISSUE TITLE
Missing header subfolder in compressed-matrix.h include directive

### ISSUE THREAD

**Issue by flavajav** [kaldi-asr/kaldi#1842]
In the file `src/matrix/compressed-matrix.h`, the following include directive needs to be corrected from
```c++
#include "kaldi-matrix.h"
```
to
```c++
#include "matrix/kaldi-matrix.h"
```
as it is, for example, in the file `src/matrix/sparse-matrix.h`. This does not affect the compilation of Kaldi proper since the corresponding object file is compiled from within the `src/matrix/` folder and thus `kaldi-matrix.h` is found since the invoking folder (in this case, `src/matrix/`) is by default included in the header search path. However, when writing new code in a completely separate location using `-I<kaldi-header-root-folder>` which somewhere includes `matrix/compressed-matrix.h`, compilation will fail with a "kaldi-matrix.h file not found" message (unless, of course, `-I<kaldi-header-root-folder>/matrix` is also added to the compiler flags).

It's not a big deal and there's an easy workaround, but I thought I'd mention it, especially since it should also prove to be a very quick issue to close.

**Comment by danpovey** [comment]
@sas91, can you please make a PR for this?

**Comment by sas91** [comment]
Sure I will.

*Thanks & Regards*,
Aswin

**Comment by jtrmal** [comment]
Addressed, closing.
