### ISSUE TITLE
Wrong comment expression in src/nnet3/nnet-simple-component.cc

### ISSUE THREAD

**Issue by ytyeung** [kaldi-asr/kaldi#1861]
line 5422, in the comment of BatchNormComponent

The expression of scale should be 

scale = (var + epsilon)^{-0.5} 

instead of 

scale = sqrt(var + epsilon)^{-0.5} ?

Please check. Thanks.

**Comment by danpovey** [comment]
can you please make a PR for this fix?  If it's not convenient let me know and I'll try.

**Comment by david-ryan-snyder** [comment]
@danpovey, @ytyeung  this can be closed.
