### ISSUE TITLE
alignment and compute the value of GOP

### ISSUE THREAD

**Issue by chijiaodaxie** [kaldi-asr/kaldi#1862]
Sorry, I was new both in kaldi and github, and I am doing some pronunciation evaluation，so I need to do some jobs on force alignment and compute the value of GOP, But I was little confused with how to do it in kaldi.
Now, I have got force-alignment result of audio and transcription use the script steps/align_si.sh, and then convert it to ctm format with command ali-to-phones, and what next should I do....

look forward your replies and discussions, Thanks

**Comment by danpovey** [comment]
You seem to mean "goodness of pronunciation".  This is pretty nontrivial to do.  You should ask on kaldi-help, not here.  Others may offer some help.

**Comment by chijiaodaxie** [comment]
OK, thx

**Comment by bamba518** [comment]
https://github.com/it-muslim/kaldi/blob/quran-academy/egs/hqa/helpers/gop.py
