### ISSUE TITLE
code snippet seem never be executed

### ISSUE THREAD

**Issue by yzmyyff** [kaldi-asr/kaldi#1885]
In swbd/s5c/local/swbd1_train_lms.sh, lines from 49 to 51 seem would never be executed.

I do not know if there is any problem here.

**Comment by psmit** [comment]
Why do you think they are never executed? To me it seems standard code that checks if those two files exist.

**Comment by yzmyyff** [comment]
```bash
for f in "$text" "$lexicon"; do 
  [ ! -f $x ] && echo "$0: No such file $f" && exit 1;  # $x is a missing variable, or it should be $f?
done
```

**Comment by psmit** [comment]
Yes, there is a bug. Maybe you can make a PR to fix it?

**Comment by yzmyyff** [comment]
Thanks, I will.
