### ISSUE TITLE
fatal error: nsync_cv.h: No such file or directory

### ISSUE THREAD

**Issue by nosqlcoco** [kaldi-asr/kaldi#1898]
I tried to install tensorflow by kaldi-trunk/tool/extras/install_tensorflow_cc.sh shell script, and Tensorflow source was downloaded, when I execute "make" under both src/tfrnnlm and src/tfrnnlmbin, got an error 
```
../../tools/tensorflow/tensorflow/core/platform/default/mutex.h:25:22: fatal error: nsync_cv.h: No such file or directory
```

Pre-info:
Ubuntu 16
CPU
kaldi install: git clone https://github.com/kaldi-asr/kaldi.git kaldi-trunk --origin golden

Detail log:
```
ksq@ksq-ThinkPad-T430:~/workspace/ml/kaldi-trunk/src/tfrnnlm$ make
g++ -std=c++11 -I.. -I/home/ksq/workspace/ml/kaldi-trunk/tools/openfst/include -Wno-sign-compare -I../../tools/tensorflow/bazel-tensorflow/external/protobuf/src -I../../tools/tensorflow/bazel-genfiles -I../../tools/tensorflow -I../../tools/tensorflow/tensorflow/contrib/makefile/downloads/eigen -I../../tools/tensorflow/tensorflow/contrib/makefile/downloads/protobuf/src -Wall -Wno-sign-compare -Wno-unused-local-typedefs -Wno-deprecated-declarations -Winit-self -DKALDI_DOUBLEPRECISION=0 -DHAVE_EXECINFO_H=1 -DHAVE_CXXABI_H -DHAVE_ATLAS -I/home/ksq/workspace/ml/kaldi-trunk/tools/ATLAS/include -msse -msse2 -pthread -g    -c -o tensorflow-rnnlm.o tensorflow-rnnlm.cc
In file included from ../../tools/tensorflow/tensorflow/core/platform/mutex.h:31:0,
                 from ../../tools/tensorflow/tensorflow/core/framework/variant.h:31,
                 from ../../tools/tensorflow/tensorflow/core/framework/allocator.h:26,
                 from ../../tools/tensorflow/tensorflow/core/framework/tensor.h:20,
                 from ../../tools/tensorflow/tensorflow/core/public/session.h:24,
                 from tensorflow-rnnlm.cc:24:
../../tools/tensorflow/tensorflow/core/platform/default/mutex.h:25:22: fatal error: nsync_cv.h: No such file or directory
compilation terminated.
<builtin>: recipe for target 'tensorflow-rnnlm.o' failed
make: *** [tensorflow-rnnlm.o] Error 1
```

**Comment by nosqlcoco** [comment]
Maybe a bug? I am not sure

**Comment by hlthu** [comment]
You need to add a line -I../../tools/tensorflow/bazel-tensorflow/external/nsync/public in the MakeFile.

Then the makefile islike this

EXTRA_CXXFLAGS = -Wno-sign-compare -I$(TENSORFLOW)/bazel-tensorflow/external/protobuf/src \
                 -I$(TENSORFLOW)/bazel-genfiles -I$(TENSORFLOW) \
                 -I../../tools/tensorflow/bazel-tensorflow/external/nsync/public \
                 -I$(TENSORFLOW)/tensorflow/contrib/makefile/downloads/eigen \
                 -I$(TENSORFLOW)/tensorflow/contrib/makefile/downloads/protobuf/src

Lu Huang

**Comment by nosqlcoco** [comment]
Thanks, I add `-I$(TENSORFLOW)/tensorflow/contrib/makefile/downloads/nsync/public \` as well

**Comment by danpovey** [comment]
BTW, we are making progress on the Kaldi-only RNNLM setup.  So far, based
on perplexities, it looks better than the TF-based setup, but I believe
Hainan has not finished the code necessary to rescore lattices yet.

It will be much easier to install for sure.

**Comment by albertz** [comment]
Some related discussion is [here](https://github.com/tensorflow/tensorflow/issues/2412).
