### ISSUE TITLE
Potential issue with GeneralMatrix

### ISSUE THREAD

**Issue by Jonathan-LeRoux** [kaldi-asr/kaldi#1915]
I use @dmitriy-serdyuk's [fork of  kaldi-python](https://github.com/dmitriy-serdyuk/kaldi-python) as a wrapper for kaldi's io functions, and I haven't been able to compile it against kaldi commits since [this commit](https://github.com/kaldi-asr/kaldi/commit/2fbf2df59055a1cf11f58aed9b4c6af110a91184).
kaldi_io_internal.so gets built, but only because the compilation command does not include `-Wl,--no-undefined`, which disallows undefined references. With that flag, I get the following error:
```
/remote/mm0/data1/leroux/kaldi_io_test/kaldi_python/../kaldi//src/util/kaldi-util.a(kaldi-holder.o): In function `kaldi::ExtractObjectRange(kaldi::GeneralMatrix const&, std::string const&, kaldi::GeneralMatrix*)':
/remote/mm0/data1/leroux/kaldi_io_test/kaldi_github/src/util/kaldi-holder.cc:95: undefined reference to `kaldi::GeneralMatrix::Type() const'
/remote/mm0/data1/leroux/kaldi_io_test/kaldi_github/src/util/kaldi-holder.cc:96: undefined reference to `kaldi::GeneralMatrix::GetFullMatrix() const'
/remote/mm0/data1/leroux/kaldi_io_test/kaldi_github/src/util/kaldi-holder.cc:98: undefined reference to `kaldi::GeneralMatrix::Type() const'
/remote/mm0/data1/leroux/kaldi_io_test/kaldi_github/src/util/kaldi-holder.cc:99: undefined reference to `kaldi::GeneralMatrix::GetCompressedMatrix() const'
/remote/mm0/data1/leroux/kaldi_io_test/kaldi_github/src/util/kaldi-holder.cc:102: undefined reference to `kaldi::GeneralMatrix::Type() const'
/remote/mm0/data1/leroux/kaldi_io_test/kaldi_github/src/util/kaldi-holder.cc:106: undefined reference to `kaldi::GeneralMatrix::GetMatrix(kaldi::Matrix<float>*) const'
/remote/mm0/data1/leroux/kaldi_io_test/kaldi_github/src/util/kaldi-holder.cc:109: undefined reference to `kaldi::GeneralMatrix::Clear()'
/remote/mm0/data1/leroux/kaldi_io_test/kaldi_github/src/util/kaldi-holder.cc:110: undefined reference to `kaldi::GeneralMatrix::SwapFullMatrix(kaldi::Matrix<float>*)'
collect2: error: ld returned 1 exit status
```

I'm not sure whether the issue is on the kaldi side or with a library missing in kaldi-python. I believe I should have everything needed when compiling kaldi-python, but I may be missing something:
```
ADDLIBS = $(KALDI_SRC)/lm/kaldi-lm.a $(KALDI_SRC)/decoder/kaldi-decoder.a $(KALDI_SRC)/lat/kaldi-lat.a \
          $(KALDI_SRC)/hmm/kaldi-hmm.a $(KALDI_SRC)/transform/kaldi-transform.a $(KALDI_SRC)/gmm/kaldi-gmm.a \
              $(KALDI_SRC)/tree/kaldi-tree.a $(KALDI_SRC)/matrix/kaldi-matrix.a  $(KALDI_SRC)/util/kaldi-util.a \
          $(KALDI_SRC)/base/kaldi-base.a
```

Apologies in advance if the problem is not on the kaldi side. I also mentioned this issue on the [kaldi-python repo](https://github.com/dmitriy-serdyuk/kaldi-python/pull/15).

**Comment by danpovey** [comment]
It looks to me like the linking order is wrong.  kaldi-util.a should come
before kaldi-matrix.a.

**Comment by Jonathan-LeRoux** [comment]
Thanks Dan, good catch, I don't get an error anymore. If it can be summarized in a few words, which change in this commit made it so that kaldi-util.a should now come before kaldi-matrix.a, while it was fine come after in previous versions?

**Comment by danpovey** [comment]
Some code from matrix/ was required in util/ after that commit.

**Comment by dmitriy-serdyuk** [comment]
Thanks guys, I'll fix this

**Comment by Jonathan-LeRoux** [comment]
I guess what I have to understand is why it wasn't needed before, even though there were references to code in matrix/.
Thanks to both of you for fixing it!

**Comment by danpovey** [comment]
The other things previously used from matrix/ within util/ might have been
inlined or they might have been such commonly called functions that they
were always requested by other things that were being compiled.

**Comment by Jonathan-LeRoux** [comment]
That makes sense, thanks for the explanation.
