### ISSUE TITLE
Is the scp splitting algorithm correct?

### ISSUE THREAD

**Issue by pranavj** [kaldi-asr/kaldi#1917]
I'm referring to 

[utils/split_scp.pl](https://github.com/kaldi-asr/kaldi/blob/master/egs/wsj/s5/utils/split_scp.pl) with utt2spk option

Consider following example.  
#spkrs = 5
#scps = 3
#utts per speaker as below
spk0 3
spk1 3 
spk2 1 
spk3 1
spk4 6

Then split_scp.pl gives output as
scp0 -> spk0 (total 3 utts)
scp1 -> spk1 + spk2 + spk3 (total 5 utts)
scp2 -> spk4 (total 6 utts)

Whereas optimal solution for roughly equal #utts per scp file should be 

scp0 -> spk0 + spk2 (total 4 utts)
scp1 -> spk1 + spk3 (total 4 utts)
scp2 -> spk4 (total 6 utts)

**If the algorithm is indeed not optimal, and if it is important to fix it, let me know.**

**Comment by danpovey** [comment]
It is not optimal, but it's not important to fix it; in fact, fixing it would create some headaches with back compatibility with existing setups.
