### ISSUE TITLE
generation of language model

### ISSUE THREAD

**Issue by vermashivam97** [kaldi-asr/kaldi#1922]
i am unable to generate language model in kaldi tool , so pleae help me out how to generate language model

**Comment by danpovey** [comment]
Kaldi is intended for people with at least a little background in speech and language technology, or at least in computer sciene- please give up now.

**Comment by vermashivam97** [comment]
kindly let me know how to generate language model from it .
Till date i am using the language model that i have generated from sphinx
tool in arpa format


On Oct 3, 2017 10:06 PM, "Daniel Povey" <notifications@github.com> wrote:

Closed #1922 <https://github.com/kaldi-asr/kaldi/issues/1922>.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/kaldi-asr/kaldi/issues/1922#event-1276355293>, or mute
the thread
