### ISSUE TITLE
something wrong in egs/wsj/s5/steps/tfrnnlm/lstm_fast.py lstm.py

### ISSUE THREAD

**Issue by qzfnihao** [kaldi-asr/kaldi#1929]
In lstm_fast.py, in function run_epoch 
line num: 281        iters += model.input.num_steps
line num: 288    return np.exp(costs / iters)
when we calculate ppl,  ppl = np.exp(costs/N),
if we use iters as N,  there is a mistake;  we need N = iters * model.input.batch_size;

**Comment by vince62s** [comment]
I think you are not correct.
num_steps is a number of words. iters is incremented by num_step each time in the loop.
the fact that we handle batches of X num_steps words is another thing.

**Comment by hainan-xv** [comment]
I based the script on TensorFlow's official RNNLM example https://github.com/tensorflow/models/blob/master/tutorials/rnn/ptb/ptb_word_lm.py
num_steps is supposed to mean "the number of unrolled steps of LSTM"

I guess this variable name is very confusing...
