### ISSUE TITLE
hi...iam using nnet2 tool to train NN..

### ISSUE THREAD

**Issue by shivakumar1393** [kaldi-asr/kaldi#1938]
iam getting following error
nnet-info exp/nnet5a_clean_100/11.mdl 
ERROR (nnet-info[5.2.158~1-e3fb7]:ReadBasicType():base/io-funcs-inl.h:68) ReadBasicType: did not get expected integer type, 60 vs. 4.  You can change this code to successfully read it later, if needed.

[ Stack-Trace: ]

kaldi::MessageLogger::HandleMessage(kaldi::LogMessageEnvelope const&, char const*)
kaldi::MessageLogger::~MessageLogger()
void kaldi::ReadBasicType<int>(std::istream&, bool, int*)
kaldi::nnet1::Component::Read(std::istream&, bool)
kaldi::nnet1::Nnet::Read(std::istream&, bool)
main
__libc_start_main
_start

some where i found we have to change the trunacte option in nnet-am-copy ...
can someone please help me???

**Comment by danpovey** [comment]
use nnet-am-info.
