### ISSUE TITLE
extract_ivectors.sh disregards num_threads disabeling parallel processing on small number of speakers.

### ISSUE THREAD

**Issue by chananshgong** [kaldi-asr/kaldi#1939]
See code here: https://github.com/kaldi-asr/kaldi/blob/master/egs/sre08/v1/sid/extract_ivectors.sh
Apparently `num-threads` is not used in the code which makes the parameter redundant. This limits the use of parallel processing with multiple CPU when processing a single speaker (`nj` must be smaller than number of speakers)
Same for `num-iters`.

**Comment by david-ryan-snyder** [comment]
This can be assigned to me.

**Comment by danpovey** [comment]
I don't really use the assignment feature... let's just leave it as a mental note.

**Comment by david-ryan-snyder** [comment]
That's fine.

**Comment by david-ryan-snyder** [comment]
@danpovey, this can be closed now.
