### ISSUE TITLE
config files

### ISSUE THREAD

**Issue by wuyifat** [kaldi-asr/kaldi#1969]
I was trying to run the scripts under egs/tedlium/s5/local/nnet3 and stuck with the second command
local/nnet3/run_tdnn.sh
with the error msg as below

Traceback (most recent call last):
  File "steps/nnet3/train_dnn.py", line 419, in main
    train(args, run_opts)
  File "steps/nnet3/train_dnn.py", line 184, in train
    variables = common_train_lib.parse_generic_config_vars_file(var_file)
  File "steps/libs/nnet3/train/common.py", line 348, in parse_generic_config_vars_file
    "i.e. xconfig_to_configs.py.".format(field_value))
Exception: You have num_hidden_layers=6 (real meaning: your config files are intended to do discriminative pretraining).  Since Kaldi 5.2, this is no longer supported --> use newer config-creation scripts, i.e. xconfig_to_configs.py.

Please advise how to fix it.

**Comment by danpovey** [comment]
That setup is outdated, use the s5_r2 setup.

**Comment by danpovey** [comment]
Yes, that's the correct order.
Probably that error was because of an earlier error.  This is not the right place to ask, see kaldi-asr.org/forums.html for the help list, but you need to be prepared to look at the output and troubleshoot basic issues on your own.
