### ISSUE TITLE
Verbosity level for GPU stats.

### ISSUE THREAD

**Issue by vesis84** [kaldi-asr/kaldi#1976]
Hi, would you mind if we increase the verbosity level for the GPU stats to some higher level, say to level 5?

https://github.com/kaldi-asr/kaldi/blob/41301bdda3b3e4a457a6b1d62e9ae03639884ae5/src/cudamatrix/cu-device.cc#L390

(I'd like to have possibility to show some verbose logs, without enabling the GPU kernel stats (i.e. without slowing down the code by GPU synchronization)).

**Comment by danpovey** [comment]
I think that would break some things.
We set verbose level to 1 on some iterations of nnet3 training so the stats
will be available for reference purposes.
What might possibly be feasible would be to change the level to 2.  But
it's not something I'd do without testing some nnet3 scripts to make sure
nothing too verbose is printed there.  It would likely require some code
changes in nnet3.

**Comment by vesis84** [comment]
Aha, I am using verbose levels 1, 2 and 3 for printing info about progress of the training:
- Level 1: frames per second every 5000 utts, loss values every 1h of processed data, showing activation/gradient stats of 1st/last mini-batch in an epoch,
- Level 2: activation/gradient stats every 25k frames,
- Level 3: shows the utt-keys,

Verbose level 2 would be good as well, as I don't use the levels 2,3 in production scripts (speed is not an issue for levels 2,3).

Sorry for causing the problems. Would there be also some verbose log-prints in nnet3, which could be printed without slowing down the code?
K.

**Comment by danpovey** [comment]
I guess it makes sense to have a verbose level greater than one that
guarantees no slow-down.
For instance, two.
But we'd have to move around some verbose levels in other code,
checking for verbose-level 2 statements and seeing if they were too verbose
to appear in the regular nnet3
training logs, and I don't have time to look at this right now.
I'll create an issue to track it.

**Comment by danpovey** [comment]
... oh, I see this is already an issue.  OK, let's leave it up for now.
