### ISSUE TITLE
Modernize vystadial_cz example

### ISSUE THREAD

**Issue by danpovey** [kaldi-asr/kaldi#1979]
Right now in our tuning experiments, there is a gap in data-size between mini_librispeech, at 5 hours, and the larger datasets.

vystadial_cz has 15 hours, the data is free, and it's non-English (for variety), so it seems like a good candidate for an alternative setup where we can tune things.

The task is to streamline and modernize the vystadial_cz scripts.  We want to take out anything that's unusual, remove the GMM-based discriminative training, probably add silence probabilities, and generally speaking, make it look more like the mini_librispeech setup structurally.

It may actually be easier to start almost from scratch, just taking the data-prep scripts from there, when preparing this.

Anyway this is a task that needs someone with a reasonable amount of Kaldi experience.  If no-one volunteers @jtrmal will probably do it, but help would be appreciated.

**Comment by vesis84** [comment]
Hi, since it is a Czech recipe, I will ask around our lab. Or I can help with it... K.

**Comment by danpovey** [comment]
Cool.
The aim is to make it look a bit more like mini_librispeech but doing it
just up to the SAT stage would be sufficient.

**Comment by akreal** [comment]
I tried to create a new recipe by adapting mini_librispeech and keeping the existing data preparation scripts for vystadial_cz. Should I make a PR for it?

**Comment by kkm000** [comment]
Fixed in #2278
