### ISSUE TITLE
Unexpected tools installation behavior

### ISSUE THREAD

**Issue by vsukhomlinov** [kaldi-asr/kaldi#198]
I was executing a make command from the tools directory and got that interesting output

```
... LONG INSTALLATION LOG ...

for p in align2html asclite ctmValidator mergectm2rttm; do \
		pod2man $p.pod -o $p.1; \
		pod2html $p.pod > $p.html; \
	done 2> /dev/null


Perforce client error:
	Connect to server failed; check $P4PORT.
	TCP connect to perforce:1666 failed.
	nodename nor servname provided, or not known
patch: **** Can't get file lock.h from Perforce
make: *** [openfst-1.3.4/.patched] Error 2
```

I was on wifi and didn't have access to perforce at that time, but was a bit scared by the fact this script tried to access it.

That behavior is in fact caused by 
```
$ pwd
~/kaldi/tools/openfst-1.3.4/src/include/fst
$ patch -p0 -N --verbose  < ../../../../extras/openfst_gcc41up.patch
Hmm...missing header for context diff at line 2 of patch
  Looks like a new-style context diff to me...
The text leading up to this was:
--------------------------
|*** lock.h
--------------------------
Get file lock.h from Perforce with lock? [y] ^C
```

Is there any flag that is missing in that command?

**Comment by danpovey** [comment]
See which patch you are using, e.g.
alias patch
which patch
Also, see if the -c flag helps.
It's always worked for us.
Dan


On Fri, Oct 2, 2015 at 1:02 AM, Vitaly Sukhomlinov <notifications@github.com

**Comment by danpovey** [comment]
According to http://linux.die.net/man/1/patch,
the flag -g 0 might help here.
We have never encountered this problem.  I don't see why it should even try
to access Perforce, since the file should exist (and anyway is not under
Perforce control).
Dan

**Comment by jtrmal** [comment]
I think he's  using a patch tool  that is probably hijacked or replaced  by
perforce  scm
Y.

**Comment by vsukhomlinov** [comment]
```
$ alias patch
-bash: alias: patch: not found
$ which patch
/usr/bin/patch
```

Both -c and -g 0 flags fix my problem. That may be a very rare case, but does it make sense to add one of these to the Makefile?

**Comment by danpovey** [comment]
I'm adding the -c flag; I'll check it in next time I check in something
else.
Thanks
(BTW, Yenda- if you do 'man patch', it does seem like it knows about
perforce and other old-fashioned version control systems).
Dan


On Fri, Oct 2, 2015 at 1:32 AM, Vitaly Sukhomlinov <notifications@github.com
