### ISSUE TITLE
Look into effect of baseline alignments on chain training

### ISSUE THREAD

**Issue by danpovey** [kaldi-asr/kaldi#1981]
I was looking into a discrepancy in some WSJ results and there's something I want to try.
I want to see whether alignments obtained using a slightly smaller-than-normal tree (i.e. closer to the size of the tree we use in chain training) would lead to better performance.

My idea is to, say, halve the size of the trees used in the two SAT systems we build before running the nnet3 and chain training.  This will probably degrade the performance of those systems but i want to see if it would help the final chain systems.
It may be hard to distinguish a real effect from randomness; we'll have to do this on more than one dataset.   Maybe start with mini_librispeech and WSJ.  If anyone wants to volunteer to do this it woul d be great.

**Comment by kkm000** [comment]
@danpovey, is this still relevant?
