### ISSUE TITLE
Check effect of stride-type on speed and memory

### ISSUE THREAD

**Issue by danpovey** [kaldi-asr/kaldi#1985]
Making this an issue so the conversation is archived and easy to access,

@hhadian, could you please either do this experiment or have a student do this?
In some setup (e.g. a typical speech setup), work out what the largest num-chunk-per-minibatch is (approximately) that we can use before getting out-of-memory errors.
Then change the code so that CuMatrix treats kDefaultStride as if it were kStrideEqualNumCols (see cu-matrix.cc:65, you can make it if (false)).
And see 
  (a) how much is the largest num-chunk-per-minibatch now?
  (b) what is the effect on speed?

It might be best to do this in a QLOGIN session so as to ensure the same GPU is used.

**Comment by hhadian** [comment]
I tried it on WSJ (using one of c02's GPUs)
The max minibatch size I could use with the current code was 670.
Then I changed the code, and the max minibatch size was 672 (almost no difference).
I checked some of the savings:
```
 default stride: 1664, num cols: 1537, num rows: 81408
 default stride: 512, num cols: 512, num rows: 81408
 default stride: 81408, num cols: 81408, num rows: 2
 default stride: 1664, num cols: 1557, num rows: 40
 default stride: 128, num cols: 20, num rows: 81408
 default stride: 1664, num cols: 1537, num rows: 20
 default stride: 128, num cols: 20, num rows: 20
 default stride: 640, num cols: 592, num rows: 160
 default stride: 128, num cols: 80, num rows: 81408
 default stride: 512, num cols: 512, num rows: 80
 default stride: 128, num cols: 80, num rows: 80
 default stride: 512, num cols: 512, num rows: 82432
 default stride: 384, num cols: 301, num rows: 82432
 default stride: 512, num cols: 512, num rows: 82432
 default stride: 82432, num cols: 82432, num rows: 2
 default stride: 384, num cols: 321, num rows: 40
 default stride: 128, num cols: 20, num rows: 82432
 default stride: 384, num cols: 301, num rows: 20
 default stride: 128, num cols: 20, num rows: 20
 default stride: 640, num cols: 592, num rows: 160
 default stride: 128, num cols: 80, num rows: 82432
 default stride: 512, num cols: 512, num rows: 80
 default stride: 128, num cols: 80, num rows: 80
```
As for the speed, there was no significant difference either:
The runtimes of a single job (measured using `time`) for 4 different minibatch sizes `256, 350, 500, 670` (with the current code):

```
256:
real  0m53.898s
user  1m13.584s
sys   0m3.664s

350:
real  1m2.096s
user  1m18.964s
sys   0m3.652s

500:
real  1m7.807s
user  1m24.376s
sys   0m3.500s

670:
real  1m11.306s
user  1m28.364s
sys   0m3.512s
```

And when treating default stride as if it were kStrideEqualNumCols:
```
256:
real    0m53.397s
user    1m13.516s
sys     0m2.944s

350:
real  0m59.777s
user  1m19.368s
sys   0m3.312s

500:
real  1m6.023s
user  1m23.884s
sys   0m3.492s

670:
real    1m10.189s
user    1m27.804s
sys     0m3.744s
```

**Comment by danpovey** [comment]
thanks, closing issue.
