### ISSUE TITLE
The blstm inference(chain model) takes a lot of time

### ISSUE THREAD

**Issue by yzmyyff** [kaldi-asr/kaldi#1988]
I trained the blstm chain model in swbd/s5c, but got a high real time factor.
This is the log in decode.1.log

> LOG (nnet3-latgen-faster[5.2.271-829ca]:main():nnet3-latgen-faster.cc:257) Time taken 474.593s: real-time factor assuming 100 frames/sec is 9.39416

And all other results are nearly 10.

Is this the normal speed for blstm or some wrong with it?

**Comment by danpovey** [comment]
Maybe you were running on a machine that was underpowered or were running too many threads vs. how many cores you had.  Nothing is wrong with the model.

**Comment by yzmyyff** [comment]
My machine has 2 Intel E5-2680(14 processors)
I set the nj = 28 from 50,  and RTF ≈ 7 that also much higher than the mentioned speed in [doc](http://kaldi-asr.org/doc/chain.html).
Has any configs to speedup it?

**Comment by jtrmal** [comment]
In my observation, the BLSTM models will take significantly more time than
LSTM and I _think_ I saw similar RTFs.
You can try to reduce decoding beams, that might help
y.

**Comment by danpovey** [comment]
I recommend TDNN or TDNN+LSTM if you care about speed
But this is not the right place for this type of questions, see
kaldi-asr.org/forums.html
