### ISSUE TITLE
change in tedlium chain script

### ISSUE THREAD

**Issue by calderma** [kaldi-asr/kaldi#2018]
Hello I was looking at the tedlium chain scripts (e.g. run_tdnn_lstm_attention_1a.sh) and i noticed that the line where the graph directory is created:
utils/mkgraph.sh --self-loop-scale 1.0 data/lang $dir $dir/graph
uses the $dir for the model instead of $tree_dir like it does in the mini_librispeech scripts. Doesn't this mean that there will be a mismatch when creating the graph directory since the topology is different? When I used the tedlium script as is the results were really bad but when I changed it to the $tree_dir the results were as expected. Thank you.

**Comment by danpovey** [comment]
@hhadian, can you see if he's right?

**Comment by hhadian** [comment]
I believe there is no problem with the scripts, I have run them w/o any
issues. 
@calderma, FYI, the topology stored in `$tree_dir/final.mdl` and
`$dir/final.mdl` are the same in chain setups.
I'm not sure why you got bad results with the original script. You might
want to create the graph (i.e. HCLG.fst) using $dir and $tree_dir
and then compare them. If they are not identical, I guess something might be wrong
in your setup.

**Comment by calderma** [comment]
Alright well i'm not sure why i got such wildly different results but it's working great now so I suppose it doesn't really matter. Thank you for your help.
