### ISSUE TITLE
export PATH=$PWD/utils/:$PATH in many path.sh files

### ISSUE THREAD

**Issue by galv** [kaldi-asr/kaldi#2058]
I noticed that we are directly adding the utils/ directory to PATH in multiple path.sh files (at least mini_librispeech and wsj. Probably more because of copy-pasta).

I'm guessing this is a mistake, as the convention seems to be prefix everything in utils/ with that directory name, e.g., 'utils/parse_options.sh', for the sake of namespacing.

Just pointing it out. I'm not sure what all depends on this (maybe it's intentional? But I doubt it), though probably some hacks with grep and find could do it.

**Comment by danpovey** [comment]
This is for historical reasons.  At one point we used invoke scripts without the path.  The reason it can't be changed right now is that there may be some scripts (in utils/ and steps/ and in example scsripts) that occasionally invoke things without the path.
