### ISSUE TITLE
ERROR: cudaError_t 6 : "the launch timed out and was terminated"

### ISSUE THREAD

**Issue by peterpantel** [kaldi-asr/kaldi#2065]
when I was running run_lstm_tdnn_a.sh under egs/wsj/s5, I got a ERROR like the following:
`ERROR (rnnlm-train[5.2]:CopyFromSmat():cu-sparse-matrix.cc:395) cudaError_t 6 : "the launch timed out and was terminated" returned from 'cusparse_csr2csc(GetCusparseHandle(), smat.NumRows(), smat.NumCols(), smat.NumElements(), smat.CsrVal(), smat.CsrRowPtr(), smat.CsrColIdx(), CsrVal(), CsrColIdx(), CsrRowPtr(), CUSPARSE_ACTION_NUMERIC, CUSPARSE_INDEX_BASE_ZERO)'
[ Stack-Trace: ]
kaldi::MessageLogger::HandleMessage(kaldi::LogMessageEnvelope const&, char const*)
kaldi::MessageLogger::~MessageLogger()
kaldi::CuSparseMatrix<float>::CopyFromSmat(kaldi::CuSparseMatrix<float> const&, kaldi::MatrixTransposeType)
kaldi::rnnlm::RnnlmTrainer::RunBackgroundThread()`

This error happened in the function of void kaldi::rnnlm::RnnlmTrainer::RunBackgroundThread(), during copying active word feature with "active_word_features_trans.CopyFromSmat(active_word_features, kTrans)". The program was run with all parameters unchanged since downloaded from git. 
I suggested that the error may happened because of too big batch size or chunk size. But after I changing the batch size and chunk size to smaller value, the error still existed.
Can you please tell me why this error happens and how to resolve it?
Thank you!

**Comment by danpovey** [comment]
I suspect that your version of Kaldi is outdated, because we fixed an issue
where those error codes were incorrectly printed.
I suspect the real error was
CUSPARSE_STATUS_EXECUTION_FAILED
This could be almost anything, e.g. driver or library issues; go to
cudamatrix/ and do 'run test'.

**Comment by danpovey** [comment]
@peterpantel, if you are still getting this issue please paste some more complete output from your program and let me know whether it's repeatable and whether you still get it with current code.  Others have reported this issue (but we can't replicate it locally) and I want to figure out what's happening.
