### ISSUE TITLE
[RNNLM] Question(s) about combining models

### ISSUE THREAD

**Issue by francoishernandez** [kaldi-asr/kaldi#2069]
Hi,
Training some quite big language models (Tedlium), we're wondering whether we could benefit from some sort of combination of models over the last epoch(s), like on the acoustic setups.
Would `nnet3-combine` be fit to this task if we feed it some raw RNNLM models and some egs dumped with `rnnlm-get-egs`? How would we handle the `feat_embedding.X.mat` in this case?
Is there a plan on appending this kind of combination to the RNNLM setup or wouldn't this be adapted to this kind of models?
Thanks for the RNNLM setup anyways, this will really help!
F

Edit: I guess I could average the models and embedding matrices with `nnet3-average` like it's done in `rnnlm_train.sh` for 'multi-job' iterations, but it may be too simple for a final combination. (and we wouldn't have the egs based choice of models.)

**Comment by danpovey** [comment]
It's definitely possible- I think we may have just not got around to it yet.
Currently Yiming is working on simplifying the combination code used in
regular nnet and chain training.
I'd probably wait till that is done (maybe a week) before implementing it
for RNNLM, it would save some coding.


On Thu, Dec 7, 2017 at 5:55 AM, François Hernandez <notifications@github.com

**Comment by francoishernandez** [comment]
Ok great, thanks for the heads up!

**Comment by danpovey** [comment]
The thing I said I'd merge about simplifying the combination code is merged now: #2067. 
For testing the RNNLM combination, something that you might find simpler to implement (and which will avoid adding C++ code), is to just launch a few jobs testing the objf on various averaged models, maybe combinations of the model up to the best single model.  You could use use nnet3-average and existing binaries for this.
