### ISSUE TITLE
There's something wrong in steps/data/augment_data_dir.py

### ISSUE THREAD

**Issue by by2101** [kaldi-asr/kaldi#2071]
I use this script to augment my data, and there's something wrong.
Specifically, the generated wav.scp is like this:
`863-000002.wav-noise wav-reverberate --shift-output=true --additive-signals='/data4/music_noise_16K_norm/norm_110.wav wav-reverberate --duration=6.16 - - |,/data4/music_noise_16K_norm/norm_136.wav' --start-times='0,0' --snrs='10,5' /data4/f001/wav/000002.wav - |`
It can not be used for wav-to-duration. And I directly run command
 ` wav-reverberate --shift-output=true --additive-signals='/data4/music_noise_16K_norm/norm_110.wav wav-reverberate --duration=6.16 - - |,/data4/music_noise_16K_norm/norm_136.wav' --start-times='0,0' --snrs='10,5' /data4/f001/wav/000002.wav -` failed.

So there's something wrong in steps/data/augment_data_dir.py line 82 to line 84. 
`    if len(bg_noise_utts) > 0:
        num = random.choice(num_opts)
        for i in range(0, num):
            noise_utt = random.choice(bg_noise_utts)
            noise = noise_wavs[noise_utt] + " wav-reverberate --duration=" \
            + dur_str + " - - |"
            snr = random.choice(bg_snr_opts)
            snrs.append(snr)
            start_times.append(0)
            noises.append(noise)`

I wrote a version fixed this bug. 
`    # Now handle the background noises
    if len(bg_noise_utts) > 0:
        num = random.choice(num_opts)
        for i in range(0, num):
            noise_utt = random.choice(bg_noise_utts)
            noise = "wav-reverberate --duration=" \
            + dur_str + " " + noise_wavs[noise_utt] + " - |"
            snr = random.choice(bg_snr_opts)
            snrs.append(snr)
            start_times.append(0)
            noises.append(noise)` 

I would like to provide this version. Otherwise, I wrote a script to generate some sample from wav.scp to test. I think it is useful to test some wave samples. I also would like to provide it.

**Comment by danpovey** [comment]
Yes, please do provide your changed version as a pull request.  It's best
if you find someone local who can explain how github works, if you don't
already know how, but if not, please contact Samuel Zhang <
samuelzhang1104@gmail.com>.  Please bear in mind that in general the
wav-file "rspecifiers" can be of two forms:
 (1) plain filenames, that don't end in the pipe symbol
and
 (2) piped commands, that end in the pipe symbol.
So your solution needs to work in both cases.  If it's case (1), you could
either precede the filename with "cat ", or (and this is more elegant),
replace the first "-" in the wav-reverberate command with the filename.

BTW, that Python code is very unreadable, rewriting it a bit for
readability might be nice, but we'd have to ask someone here to verify that
your version would do the same (and test it).

**Comment by by2101** [comment]
I already provided a pull request.

**Comment by by2101** [comment]
I already provided a pull request.

**Comment by by2101** [comment]
I already provided a pull request. #

**Comment by by2101** [comment]
Sure, I already provided a pull request.

**Comment by david-ryan-snyder** [comment]
Can you copy and paste how you ran augment_data_dir.py when it failed? E.g., the options you provided. I want to try and replicate the issue.

**Comment by by2101** [comment]
I did not set any option. I simply run 
`  python steps/data/augment_data_dir.py \
      --utt-suffix "noise" \
      --fg-snrs  $foreground_snrs \
      --bg-snrs $background_snrs \
      --num-bg-noises $num_bg_noises \
      --bg-noise-dir $noise_data_dir \
      --fg-noise-dir $noise_data_dir \
      ${data_dir} ${data_dir}_noise
`
Because between line 82 to 84,
`noise_wavs[noise_utt] + " wav-reverberate --duration=" \ + dur_str + " - - |"`
is not right. It cannot deal with non-pipeline case.

**Comment by david-ryan-snyder** [comment]
> is not right. It cannot deal with non-pipeline case.

Oh OK, I see what you mean now.
