### ISSUE TITLE
tfrnnlm _pywrap_tensorflow_internal.so: undefined symbol: _ZNK6google8protobuf7Message11GetTypeNameEv

### ISSUE THREAD

**Issue by ustcljw** [kaldi-asr/kaldi#2079]
I wanted to utilize the tfrnnlm module to rescore the lattice and ran into this mistake. my tensorflow version is 1.4. it seems that there is no function named __ZNK6google8protobuf7Message11GetTypeNameEv in _pywrap_tensorflow_internal.so, Is this a mistake caused by the version of tensorflow??

**Comment by danpovey** [comment]
It would help if you are more specific about what happened, e.g. show the
full error.
@hainan-xv may be able to help- I don't follow this stuff closely.

**Comment by hainan-xv** [comment]
1.4 shouldn't be a problem.
What kind of machine are you running on? What command did you run that failed? Please show us more information so we could help on this.

**Comment by ustcljw** [comment]
I just include the head file(tfrnnlm.h) in my code and run into this error. if i remove tfrnnlm.h, every thing is ok. By the way, my code is successfully compiled . My error is as follows. my platform is Tesla M40 with Ubuntu 16.04, python3.5, tensorflow1.4
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "/usr/lib/python3.5/imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "/usr/lib/python3.5/imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: /usr/local/lib/python3.5/dist-packages/tensorflow/python/_pywrap_tensorflow_internal.so: undefined symbol: _ZNK6google8protobuf7Message11GetTypeNameEv

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/data1/liujiawei/asr_offline/asr_rescore_lattice/asr/eval/evaluation.py", line 17, in <module>
    from asr.feature.feature import FeatExtractor
  File "/data1/liujiawei/asr_offline/asr_rescore_lattice/asr/feature/feature.py", line 12, in <module>
    import tensorflow as tf
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/__init__.py", line 24, in <module>
    from tensorflow.python import *
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/pywrap_tensorflow.py", line 72, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "/usr/lib/python3.5/imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "/usr/lib/python3.5/imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: /usr/local/lib/python3.5/dist-packages/tensorflow/python/_pywrap_tensorflow_internal.so: undefined symbol: _ZNK6google8protobuf7Message11GetTypeNameEv


Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/install_sources#common_installation_problems

**Comment by hainan-xv** [comment]
I am very confused now. Did you encounter the issues when running TF in python or the compiled (c++) binaries? From the error messages it looks like you're running Python but you also mentioned including header file tfrnnlm.h which is confusing to me.

Could you tell me which command are you running when you see those errors?

**Comment by danpovey** [comment]
So it's not an error with compiling Kaldi, it's an error running your own
Python code.  You should have clarified that from the start.

I guess something needs to be linked in that wasn't linked in.  There are
some quite complicated issues related to both swig and TensorFlow itself
here.  I'm not going to be able to help.

The TensorFlow compilation process is complicated and I don't understand it
even in the normal case, let alone when Kaldi and OpenFst are combined with
it.

**Comment by ustcljw** [comment]
I am very sorry for confusing you. I am doing asr project. I use kaldi for asr decoding and utilize swig to wrap the c++ for python3.5. According to the code in tfrnnlmbin, I modified my code, and include the tfrnnlm.h. To avoid other problems， I comment the code which copied from tfrnnlmbin, and leave the tfrnnlm.h only in my code. By the way， my code is according to the decoder-wrappers.cc
@hainan-xv

**Comment by hainan-xv** [comment]
I have no experience working with swig, and I agree with Dan that it's probably going to be very hard to use swig when the underlying C++ merged OpenFst, TensorFlow, and Kaldi.

**Comment by danpovey** [comment]
Also I don't understand how you can possibly expect it to work when all
you're using is the header file, without at least making attempt to link in
the relevant libraries, both the ones we wrote, and also the TensorFlow C
library and OpenFst and the relevant parts of Kaldi-- or maybe I
misunderstand you.

I think you are probably way out of your depth here and you probably need
local help from someone much more experienced.  But I might be
misunderstanding something.

**Comment by ustcljw** [comment]
There may be some confusion, I linked the relevant libraries, including tensorflow ,kaldi and openfst. Compiling process is ok. Anyway, thanks a lot, it may be an error I utilize swig to wrap tensorflow. @danpovey @hainan-xv

**Comment by hainan-xv** [comment]
Did you also link the libtensorflow_cc.so files etc that are generated in extras/install_tensorflow_cc.sh?
