### ISSUE TITLE
openfst-1.6.5.tar.gz is missing from openslr.org

### ISSUE THREAD

**Issue by wintermute0001** [kaldi-asr/kaldi#2085]
was changed here:

https://github.com/kaldi-asr/kaldi/pull/2026

file is missing and breaks install.

**Comment by jtrmal** [comment]
Thanks, I'll fix it tomorrow. It shouldn't be a showstopper, though, as the
openslr is just a backup location.
Y

**Comment by danpovey** [comment]
Addressed by @jtrmal
