### ISSUE TITLE
The inspection of the oov.txt

### ISSUE THREAD

**Issue by yzmyyff** [kaldi-asr/kaldi#2086]
The inspection of the oov.txt in rnnlm config should be OK while it's a empty **text** file.

I got a error if create it by```echo "" > oov.txt``` and all will be fine if create by ```touch oov.txt```.

I means that the oov.txt is not purely empty but a text file with the EOL sometimes.

**Comment by danpovey** [comment]
As long as it fails in the validation step (and not in the actual RNNLM
training) that's OK.

**Comment by danpovey** [comment]
BTW the normal way to create an empty file is:
`echo -n > oov.txt`
