### ISSUE TITLE
 I have some confuse in running scripts lre07/v2

### ISSUE THREAD

**Issue by whuawell** [kaldi-asr/kaldi#2089]
The problem is that: 
     in kaldi egs/lre07/v2, 
    The subdirectory v2 demonstrates the LID system using a time delay deep neural network based UBM which is used to replace the GMM-UBM of v1. The DNN is trained using about 1800 hours of the English portion of Fisher.
    can we use dnn to calculate the posterior of which class it should be, but the dnn is trained only using 1800 hours of the English portion of Fisher ? when using in LID, it's does make sense ?  In my opinion , different language have different phonetic , so i was confused by this scripts ? can any one suggest any information , good for help.

**Comment by danpovey** [comment]
this kind of question should be on kaldi-help.  see kaldi-asr.org/forums.html
