### ISSUE TITLE
How to build kaldi for ARM and Android

### ISSUE THREAD

**Issue by voidxb** [kaldi-asr/kaldi#2112]
Iread the blog:http://jcsilva.github.io/2017/03/18/compile-kaldi-android/,
however,there is some problem ,like 'lapacke.h'is not found.
Could you please tell me some advise?

**Comment by danpovey** [comment]
@jcsilva may be able to help you-- this is beyond my experience.

**Comment by jcsilva** [comment]
@voidxb 

according to your message, it was not clear when the problem happened. So, I just followed all the post instructions right now and it compiled. 

I started a new clean environment in Ubuntu 16.04 - 64 bits, downloaded the dependencies and it compiled. I attached a text file with the history of the bash commands I used. I think that if you follow it, you'll have success compiling it. I'm using the new OpenBLAS version (0.2.20), so there are some little differences from that i was using when the post was written. In the attached file you will recognize these differences.

The unique step I couldn't do right now was testing the compiled Kaldi in an Android device. I'm not working these stuffs any more and I don't have such device. Could you please test it?

@danpovey, OpenBLAS updated its code, and they're now supportting soft floating points for arm. New Android dev kits (greater than r14b) only support softfp. But current instructions found in kaldi/srcr/makefiles/android_openblas.mk are using -mfloat-abi=hard  -mhard-float -D_NDK_MATH_NO_SOFTFP=1 -lm_hard. I think it would be nice to update kaldi makefile and the post instructions to use the most recent versions of everything. But, as I already told, I'm not working with this any more and I'm not able to test if it's working (I can just compile the code). What do you think about?


[compile-kaldi-android.txt](https://github.com/kaldi-asr/kaldi/files/1594028/compile-kaldi-android.txt)

**Comment by danpovey** [comment]
@galv, do you have time to help with this?  Anything is better than nothing.

**Comment by voidxb** [comment]
thank you,  I will try it

**Comment by voidxb** [comment]
It works,thank you ,please update the blog for others

**Comment by voidxb** [comment]
Hi,thank you for your help before.Now we meet another problem,after I compile my project on the basis of kaldi to my shared library and call it, it shows "cannot locate symbol FLAGS_fst_align".Then I search FLAGS_fst_align in the whole openfst directory and only find "bool align=FLAGS_fst_align".....It has never been declared ？How  to solve it ?

**Comment by jcsilva** [comment]
Did you link OpenFST to you library? It seems you have a problem in this
linking operation.

If I were you, I would avoid using dynamic linking in your initial tests in
Android. Just after this step, you should try to link everything
dynamically. I remember to have faced some problems of linking order in
some Android versions... So, I compiled everything statically to guarantee
that all my stuffs were working properly.

Sorry for not being able to help you much more than this. As I told, I'm
not working with Android anymore, and I don't have a device here to repeat
you problem.



2018-01-06 10:21 GMT-02:00 void <notifications@github.com>:

**Comment by sevenwonder** [comment]
Any one could shed some light on how to test this complied Kaldi on android? Thanks

**Comment by jcsilva** [comment]
@sevenwonder, for testing it you have at least two options:

1. If you have a rooted phone, you may compile everything statically. Then you may just copy a binary like online2-wav-nnet3-latgen-faster to your device and run it in command line. It's the same thing you usually do when you use Kaldi in your computer.
2. You may write a JNI library. This way you would be able to write your own apps in Android. 

Option 2 demands deeper Android knowledge than option 1. For my tests, when I was working with this (it was in the begging of 2017), I chose option 1, e.g. I just used a rooted device.

**Comment by songpu2015617** [comment]
@jcsilva Thanks for your explanation.  Were you able to do the cross compilation on 64bit arm? Thanks

**Comment by jcsilva** [comment]
@songpu2015617, I have never tried the cross compilation for 64bit arm.

**Comment by saquibntt** [comment]
@songpu2015617 were you able to cross compile on 64bit arm processor?

**Comment by xqq2018rebuild** [comment]
Iread the blog:http://jcsilva.github.io/2017/03/18/compile-kaldi-android/,
When I went to the last step（cross compile kaldi src for arm7）, an error occured.
**_“kaldi-math.cc:50:12: error: use of undeclared identifier 'rand_r'”_**

Could you please tell me some advise? Thank you!

**Comment by Fatlog** [comment]
would it take much to make this also work for IOS?

**Comment by jtrmal** [comment]
Probably. It would also need someone having experience with programming for
iOS and I'd say pretty solid experience if it should be made to be usable
and useful.
y.

**Comment by danpovey** [comment]
@keli78 would you mind fixing the Android rand_r issue via a PR?  The fix should be to add an ifdef in kaldi-math.cc so that it uses rand_r only if defined(_POSIX_THREAD_SAFE_FUNCTIONS), and otherwise just uses rand() regardless.  Please see the link below for an example (press "..." to see more context in the code), and ask someone like Vimal to check your fix before making the PR.

https://git.merproject.org/mer-core/qtbase/commit/1cf82c4081d1d42af5a789a466a2fa8f8a10bbb3

**Comment by keli78** [comment]
@danpovey sure, I will do it.
