### ISSUE TITLE
Path bug in: lattice_oracle_align.sh

### ISSUE THREAD

**Issue by roman-verbit-ai** [kaldi-asr/kaldi#2116]
Hi,

stumbled upon a small path bug in _lattice_oracle_align.sh_:
line 74 calls: 
`utils/split_data.sh --per-utt $data $nj`
the "--per-utt" argument will cause _split_data.sh_ to create the split output in:
_data/split{JOB}**utt**_  
(as opposed to _data/split{JOB}_ - without the "--per-utt" argument)

next, in line 76 the split source dir is set to:
`sdata=$data/split$nj`

this might **accidently work** if you previously ran your decode in the same data dir - and you **happen** to have the same data inside _data/split{JOB}_.

but when running this in a new data dir created for oracle align (or any other scenario) - this will fail due to "path not found".

so, as I see it... line 76 should be:
`sdata=$data/split${nj}utt`

**Comment by danpovey** [comment]
Thanks for the bug report.  Fixing in commit 1431db17e.
