### ISSUE TITLE
egs/babel_multilang/s5/local/datasets/unsupervised_uem.sh symlink broken

### ISSUE THREAD

**Issue by galv** [kaldi-asr/kaldi#2119]
I just noticed that egs/babel_multilang/s5/local/datasets/unsupervised_uem.sh is a broken symlink.

Hopefully someone more familiar with the babel scripts can fix that, even if it means removing it. Maybe @jtrmal?

**Comment by jtrmal** [comment]
Yes, it should be removed. I'll fix it.
Y.
