### ISSUE TITLE
Kaldi C++ interface is leaky.

### ISSUE THREAD

**Issue by galv** [kaldi-asr/kaldi#2123]
I've noticed some issues when compiling a C++ library against Kaldi.

1. f2c.h, which is included via matrix/kaldi-blas.h, leaks various symbols into the global namespace. This was a big pain today, as f2c.h defines the symbol `real` to be `float`, which caused compilation errors when I included kaldi headers before Eigen headers (Eigen uses the symbol real as well).

2. To compile my separate library I must add `-DHAVE_CLAPACK` to the compiler command line and `${kaldi_PREFIX}/kaldi/tools/ATLAS_headers/include/` and `${kaldi_PREFIX}/kaldi/tools/CLAPACK/` to my include paths, since kaldi's header files depend recursively on those include paths being present, which is leaky, as it demands a library user know to include kaldi-specific dependencies. Note that this works only for ATLAS. It won't work with OpenBLAS, which is another reason why this workaround is bad.

From what I can tell, both of these can be fixed by removing the `#include matrix/kaldi-blas.h` from `matrix/matrix-common.h`, since this is the only header file that includes `kaldi-blas.h`. This means that kaldi-blas.h would have to be included in various .cc files afterwards, but I think that this is fine because it makes the library much cleaner to interface with.

**Comment by danpovey** [comment]
I think what you propose would be a good idea, but it would require a
little bit of work, and testing with different matrix libraries.
The following lines in matrix-common.h would be a problem:
typedef enum {
  kTrans    = CblasTrans,
  kNoTrans = CblasNoTrans
} MatrixTransposeType;
but we could just figure out what the numeric values are, put them in the
header, and use KALDI_STATIC_ASSERT in a c file that they are the same.

**Comment by galv** [comment]
Hmmm... I know you can declare enums without defining them, but it's of course not clear how you would access the enum values without defining the enum right in the .h file. I'll look into it.

This is something I'd like to look at maybe next week, after some deadlines have passed for me.
