### ISSUE TITLE
Idea/Suggestion: Use CUDA-enabled MPI to merge gradients when training with multiple GPUs

### ISSUE THREAD

**Issue by galv** [kaldi-asr/kaldi#2129]
Right now, when training with multiple GPUs, the gradients are saved to disk via nnet3-train, and then, when all are done, they are combined with nnet3-average.

I suspect we could get a good speedup (no real numbers right now, alas!) by using MPI (more specifically, NVIDIA's nccl library) to communicate between the nnet3-train processes using all-reduce, because (1) gradients don't need to be saved to disk first and (2) gradients of higher layers can be combined while gradients of lower layers are being computed. However, I don't think this fits into the current paradigms used by Kaldi and at CLSP, because I don't know of a way for sun grid engine to launch multiple processes at the same time, and this way your nnet3-train processes would run for multiple iterations, instead of being relaunched for every iteration. You would also have to do away with Kaldi's normal strategy of being able to change the number of GPUs as the number of training iterations change, for this to be reasonable.

Not something I'm planning to work on immediately (or necessarily will work on!), but I've been curious about this for a while, and am curious if anyone at CLSP has an opinion on it.

**Comment by danpovey** [comment]
This is definitely not planned.  The speedup would be small, and it's against the grain of how everything is organized.  There are other reasons why this would be very complex to implement, too, but I don't have time to summarize them all.

**Comment by roscisz** [comment]
I am not sure if this will be helpful, but last year I implemented model averaging with MPI into nnet3. You can find the code in my [fork](https://github.com/roscisz/kaldi-mpi), and specifically in the [nnet3-ctc-train-mpi](https://github.com/roscisz/kaldi-mpi/commit/2176d0810da77defb382fd8da7066ed583b7fe73#diff-2d8cb49e0cae0b98639778226cfbd53f) program. As the name suggests, it uses an old Kaldi branch which supported CTC, which makes my fork quite outdated, but maybe the code can still be useful.

Regarding performance, in case of training with model averaging, the speedup depends on the averaging frequency. In a [paper](http://ieeexplore.ieee.org/document/8035128/) from last year we examined the influence of averaging frequency on the final model efficiency. We found that there is a certain optimal range of averaging frequencies. In our case we chose 600k frames per iteration, and for that setting the MPI implementation reduced the execution time by 54.9%, so it might be worth investigating.

We didn't continue the work to look into nccl and I am not sure how useful this approach would be for the current Kaldi version.
