### ISSUE TITLE
how to add a new language model to api.ai librispeech model?

### ISSUE THREAD

**Issue by sadhana195090** [kaldi-asr/kaldi#2146]
Please let me know what all files should be generated from my text corpus and how they should be generated so that i can replace or append to the current language model in api.ai kaldi model trained on Librispeech.

**Comment by danpovey** [comment]
This kind of question should go to kaldi-help.  However, I think the gap between what you know and what you need to know is a little too large, hence I may decide not to answer it there in any case, and likely no-one else will either.  Search online for tutorials on SRILM.  It won't get you all the way though.
