### ISSUE TITLE
Kaldi ubuntu 16.04 install error

### ISSUE THREAD

**Issue by saurabhvyas** [kaldi-asr/kaldi#2147]
extras/check_dependencies.sh

./env.sh: line 1: export: `Volume1/kaldi/tools/python:/home/saurabh/.nvm/versions/node/v7.10.1/bin:/home/saurabh/torch/install/bin:/home/saurabh/anaconda3/bin:/home/saurabh/torch/install/bin:/home/saurabh/torch/install/bin:/home/saurabh/torch/install/bin:/home/saurabh/bin:/home/saurabh/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/saurabh/.mos/bin:/home/saurabh/bin': not a valid identifier
./env.sh: line 2: export: `Volume1/kaldi/tools/python:/media/saurabh/New': not a valid identifier
./env.sh: line 3: export: `Volume1/kaldi/tools/python:/media/saurabh/New': not a valid identifier
extras/check_dependencies.sh: line 107: mkdir: command not found
extras/check_dependencies.sh: python2.7 is installed, but the python2 binary does not exist. Creating a symlink and adding this to tools/env.sh
extras/check_dependencies.sh: line 109: which: command not found
extras/check_dependencies.sh: line 109: ln: command not found
*** extras/check_dependencies.sh: Warning: Kaldi scripts will fail if the directory name contains a space.
***  (it's OK if you just want to compile a few tools -> disable this check).

**Comment by danpovey** [comment]
Likely the directory name where you're installing it contains a space--- as it says.  Don't do that.
