### ISSUE TITLE
build-tree errors

### ISSUE THREAD

**Issue by whuawell** [kaldi-asr/kaldi#2152]
when run train_delta.sh on egs/thchs30, it falied when doing bulid-tree. After checking the logs , it seems that below assertion failed !
      KALDI_ASSERT(num_leaves - num_removed  - num_actually_removed == num_leaves_required);

After i add option --round-num-leaves=false, all things gone right. This my setting in train_delta.sh. I'm not sure it isn't a problem.

  echo "$0: building the tree"
  $cmd $dir/log/build_tree.log \
    build-tree $context_opts --verbose=1 --max-leaves=$numleaves \
    --round-num-leaves=false \
    --cluster-thresh=$cluster_thresh $dir/treeacc $lang/phones/roots.int \
    $dir/questions.qst $lang/topo $dir/tree || exit 1;

**Comment by danpovey** [comment]
This issue was already resolved, if you update your Kaldi to the latest version it wouldn't happen.

**Comment by whuawell** [comment]
thanks
