### ISSUE TITLE
How to improve the decoding speed?(nnet2 decoding)

### ISSUE THREAD

**Issue by haohao3** [kaldi-asr/kaldi#2157]
Hi, It takes a few seconds to decode a sentence with nnet-latgen-faster. I want to konw,how can this be improved, Thanks!

**Comment by danpovey** [comment]
there are lots of discussions on kaldi-help about these kinds of questions.  Try searching online before you ask, and in any case these kinds of questions should go to kaldi-help (but you need to be more specific and provide more details).

**Comment by haohao3** [comment]
thank you for you reply. thank you very much.
