### ISSUE TITLE
question about decoding speed

### ISSUE THREAD

**Issue by haohao3** [kaldi-asr/kaldi#2158]
Hello, author, I'm using nnet2's decoding method and I can see that the decoding of a sentence will take a few seconds, so I would like to ask what the optimization points are. Please,when you are free. Thank you.

**Comment by danpovey** [comment]
Same response as your previous, almost identical issue.

**Comment by haohao3** [comment]
sorry，It's my fault, I'm not see the reply before. Thank you very much!
