### ISSUE TITLE
How to extract speech pitches from wave files?

### ISSUE THREAD

**Issue by bastibe** [kaldi-asr/kaldi#2161]
I read your paper on fundamental frequency estimation, and I would like to try your algorithm. However, the documentation seems mostly concerned with setting up the entire speech recognition tool chain, instead of extracting a single feature on a single file.

I'd be grateful for any hints on how to go about this.

**Comment by jtrmal** [comment]
Something like thiscould be used
```
compute-kaldi-pitch-feats --sample-frequency=8000 scp:<(echo utt file.wav) ark,t:feats.txt
```

I'm closing this, as this is not a place to ask questions. If you need to follow up, sign up to kaldi-help

**Comment by bastibe** [comment]
Thank you very much, with your above example, I figured it out.

For future reference, the full command is

    compute-kaldi-pitch-feats --sample-frequency=44100 scp:<(echo foo path/to/file.wav) ark,t:outfile.txt

**Comment by danpovey** [comment]
@pegahgh and @hanglv, perhaps you can point this person to the standalone
project that you created?  What was it called?


On Thu, Jan 18, 2018 at 11:04 AM, Bastian Bechtold <notifications@github.com

**Comment by pegahgh** [comment]
@Hang, would you please point  him to the standalone pitch extractor?

**Comment by danpovey** [comment]
It's here
https://github.com/LvHang/pitch
Please let us know if there are any problems with it, or any usability
issues.
The aim is to make it possible to use our pitch extractor without compiling
all of Kaldi.

**Comment by bastibe** [comment]
Thank you very much! This is much easier to install than all of Kaldi!
