### ISSUE TITLE
Extra character '.' in slurm.pl

### ISSUE THREAD

**Issue by kamo-naoyuki** [kaldi-asr/kaldi#2170]
There is an extra character '.' at https://github.com/kaldi-asr/kaldi/blob/master/egs/wsj/s5/utils/parallel/slurm.pl#L397

```
print Q "  unset CUDA_VISIBLE_DEVICES.\n";
```
It causes the following error message, 

/var/spool/slurm/d/job.../slurm_script: line 14: unset: `CUDA_VISIBLE_DEVICES.': not a valid identifier

**Comment by danpovey** [comment]
Thanks, fix via commit d6391f864
