### ISSUE TITLE
kaldi-asr.org down

### ISSUE THREAD

**Issue by giampierosalvi** [kaldi-asr/kaldi#2171]
Hi,
the kaldi-asr.org site has been down (unresponsive) for a while.
- is this a local issue or do others experience the same problem?
- will the site be restored any time soon?
- in case it won't, can I find kaldi's documentation mirrored somewhere? (it does not seem to be included in the github repository)

Thank you!
Giampiero

**Comment by jtrmal** [comment]
The server is fine, except maybe some inconsiderate users overloading the network interface.
I restarted apache2 and added some users to blacklist (@danpovey -- its in /var/www/openslr/.htaccess)

**Comment by jtrmal** [comment]
It's actually quite hard to distinguish between  users using too many download threads and legit users using non-continuous download

**Comment by danpovey** [comment]
It's fine from here.  I suspect your internet service provider does not
provide very good links to its location.  Let us know where you are, and if
it's OK now.

**Comment by danpovey** [comment]
Forget it, we had someone else report at about the same time that it was very slow.  Possibly an issue with our hosting provider.  We moved a couple months ago from Google Cloud to Digitalocean.  It's not as good a provider, but the cost decreased from about $4k per month to a couple hundred dollars.  The cost from Google Cloud was unsustainable for us.

**Comment by jtrmal** [comment]
I can confirm I had the same problem when accessing openslr from
hopkins network
y.
