### ISSUE TITLE
kaldi install error in tools make

### ISSUE THREAD

**Issue by changsheng-liu** [kaldi-asr/kaldi#2172]
Hi, when I tried to run make in tools I got the attached error message. 
[error.txt](https://github.com/kaldi-asr/kaldi/files/1653863/error.txt)

When I tried to check by "CXX=g++-4.8 extras/check_dependencides.sh"
I got:
WARNING: unknown compiler g++-4.8.
all OK.

But my gcc version is 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.5)
Could you please have a look? Thanks.

**Comment by danpovey** [comment]
You didn't read the installation instructions carefully.
