### ISSUE TITLE
Travis CI Build currently timing out

### ISSUE THREAD

**Issue by galv** [kaldi-asr/kaldi#2179]
Right now the Travis CI build is timing out all the time, as far as I can tell. I do like to depend on it when open-sourcing some things I've done, so I miss having it.

A couple of suggestions for easy speed ups:

- Don't use ccache since we're building only once. My understanding is that ccache helps only when you do repeated builds.
- Parallelize building openfst. It my experience the fact that its compilation is single-threaded even when you do `make -j -C tools` is probably the biggest build bottleneck for me.
- Use ld.gold for linking, not ld. Should be as easy as `export LD=$(which ld.gold)` (assuming it's installed!)

If someone else can do this, that would be amazing~

**Comment by jtrmal** [comment]
I'm closing this as I think we have resolved the issues by upgrading on the paid plan.
