### ISSUE TITLE
batchnorm models fail silently without call to `SetBatchnormTestMode`

### ISSUE THREAD

**Issue by mikenewman1** [kaldi-asr/kaldi#2183]
I was having problems running recognition with models built from the latest Kaldi recipes, when using the ASR server from here
https://github.com/dialogflow/asr-server

Eventually I tracked down that they were missing a call to the function
```
      SetBatchnormTestMode(true, &(nnet_->GetNnet()));
```
in the file `src/Nnet3LatgenFasterDecoder.cc`
(Note that the code in GitHub has not been updated for a while!) 
Once I added this call, everything ran fine.

cf https://groups.google.com/forum/#!topic/kaldi-help/1N4aVb75IdU

**Comment by danpovey** [comment]
OK.  But you should open an issue in that project.
