### ISSUE TITLE
Old nnet3 model fails to load on "newer" Kaldi version

### ISSUE THREAD

**Issue by satmass** [kaldi-asr/kaldi#2186]
Recently I've tried to load a quite old nnet3 model for some testing (it was trained based on swbd/s5c/local/tuning/run_tdnn_5e.sh), but it fails with the message:

`ERROR (nnet3-am-info[5.3.93-7cf434]:Check():nnet-nnet.cc:737) Dimension mismatch for network-node jesus2: input-dim 2404 versus component-input-dim 2400`

Searching and testing around the previous commits, it seems this behavior started with the pull request #2031 more specifically, the commit 0da1675989d2f08ff6fae882764e9308f1cbb197

The odd thing is that only this one particular model fails, other models, even one based on the same training script, loads normally, so I'm not really sure if this suggests a bug in the code, in the model or somewhere else.

EDIT: It seems nnet3-am-copy gives a slightly different error:

`ERROR (nnet3-am-copy[5.3.93-7cf434]:Check():nnet-nnet.cc:737) Dimension mismatch for network-node jesus2-forward-output-affine: input-dim 2001 versus component-input-dim 2000`

**Comment by danpovey** [comment]
If you still have the training logs for that model, can you show the nnet3-info (or nnet3-am-info) output from one of the later progress logs?

**Comment by satmass** [comment]
Here is the trimmed log:
[progress.1718.log](https://github.com/kaldi-asr/kaldi/files/1661385/progress.1718.log)

Btw, the binaries work without problems if I compile Kaldi from before the mentioned commit, so I can also post the output of nnet3-am-info from the model if it's relevant.

**Comment by danpovey** [comment]
Fixed the issue in commit 7ee7893f9d1e
