### ISSUE TITLE
Enforce pronunciation during phoneme alignment

### ISSUE THREAD

**Issue by mdekorte** [kaldi-asr/kaldi#2187]
I would like to use Kaldi to train a model for phoneme alignment (automatic segmentation) given input text sentences and their phonetic transcriptions. The phonetic transcriptions used for this automatic segmentation are the same as those used in manual segmentation. My objective is to compare the two on the phoneme level, and evaluate what the mismatch of the boundaries is. To do so, I have trained a model using train_mono.sh and used the align_si.sh script to align the words to the audio. This results in an aligned phonetic transcription of the input sentence. However, presumably because the lexicon can contain the same word with multiple pronunciations, these phonetic transcriptions regularly differ from the original transcriptions. This gives problems when evaluating the quality of the automatic segmentation, because I can no longer map the phonemes on each other. 

Is there a way to force Kaldi to use a certain pronunciation during alignment, so that I can evaluate phoneme boundary quality directly with a manual segmentation?

**Comment by danpovey** [comment]
you could create a lexicon with tags, e.g. _1, _2, so each word had only one pronunciation.
Or you could build a system that's entirely on the phone level, with one phone mapping to one word, and without word-position-dependent phones (you'd have to supply the options --position-dependent-phones false and --sil-prob 0.0 to prepare_lang.sh, as well as changing the input to that script).   You could look at the TIMIT example, although normally I don't recommend people to look at that.  These kinds of  questions should go on kaldi-help, not here: see kaldi-asr.org/forums.html
