### ISSUE TITLE
[nnet3-rnnlm]

### ISSUE THREAD

**Issue by qindaying** [kaldi-asr/kaldi#2189]
Dear developers,
I read newest scripts of nnet3-rnnlm (e.g. run_tdnn.sh in egs/ptb ) but I face some problems... I am wondering why the dimension of output layer is equal to the embedding_dim?  Why it is not equal to the dimension of lexicon? (or training label is not one-hot vector?) Perhaps my knowledge to the rnnlm is out of date. I remember the basic concept of rnnlm is to provide the probability of next word. Also, why just using word embeddings can do lattice rescoring?  Can you provide me some papers about this issue?

Looking forward to your kind reply.

Best Regards,
Queena

**Comment by danpovey** [comment]
The way we have implemented it, the core part of the neural network just outputs a vector of the same dimension as the word embedding, and to compute the log-probability of a word, there is some code that manually computes a dot-product of the word embedding times that vector.   Then, if requested, it normalizes it by subtracting the log-sum-exp of all of them.
