### ISSUE TITLE
Switchboard data prep help

### ISSUE THREAD

**Issue by vineelpratap** [kaldi-asr/kaldi#2191]
Why do we add 5 ms to start and end time in Switchboard data prep step ? 
https://github.com/kaldi-asr/kaldi/blob/3031e26e6744f8454c268696829285cc3ff6bae1/egs/multi_en/s5/local/swbd1_data_prep.sh#L67

**Comment by danpovey** [comment]
that  code is just rounding-to-nearest as opposed to rounding down.
