### ISSUE TITLE
Problem in building openfst (Windows)

### ISSUE THREAD

**Issue by szjiajin** [kaldi-asr/kaldi#2192]
I followed instructions in windows/INSTALL. In  "Compiling OpenFST" section, the "cmake" step was successful. But when I tried to debug openfst.sln in vs 2017. It shows an error relating to ALL_BUILD,

Unable to start program '(openfst directory)\build64\x64\Debug\ALL_BUILD'.
Access Denied.

Is is because ALL_BUILD is set to startup project or something else?

**Comment by danpovey** [comment]
sorry, it looks like Yenda doesn't have time to deal with this; and anyway this is really an OpenFst issue, you should probably ask on their forums.

**Comment by jtrmal** [comment]
I didn't notice this, sorry -- but in fact, you didn't even show the error, so it's very hard to say anything constructive.

**Comment by tsungruihon** [comment]
@szjiajin  have you solved the problem yet ?
