### ISSUE TITLE
feature ark cannot be recognized / probed

### ISSUE THREAD

**Issue by roman-verbit-ai** [kaldi-asr/kaldi#2198]
Hi, 

Background:
Working with big amounts of audio and many data dirs, obviously - we try to minimize heavy operations. For example, the result of feature extraction can be reused in many cases, instead of being re-generated.

Problem:
The result of `make_mfcc.sh` (raw_mfcc_features.ark) is an opaque binary structure. There is no way what-so-ever to probe this structure to get the original parameters or even the acoustic model with which it was generated.

Suggestion:
It would be very useful, if there was a way to probe the features ark to identify its contents. Obviously, we don't want to change the structure of the ark itself - but maybe some 'system'-way can be devised in order to enable the option to probe the dir where feature extraction was ran. (excluding parsing logs)

For example: modify `make_mfcc.sh` so it copies the original config file and marks the acoustic model that was used during generation... or any other solution that seems good for the developers - will be welcome!

**Comment by danpovey** [comment]
If you run make_mfcc.sh without the last two arguments, the logs and the ark file will be put in a subdirectory of the data directory, and you could go one directory up and look at the .scp file if you want to see what utterances it is for.
I suggest that if you have a use-case where you need to make a record of the config file, you use the single-argument form of make_mfcc.sh and modify it so it copies the config file to the log directory.
The MFCCs are model-independent, the acoustic model is not involved.
Changing the archive format is something that is definitely not going to happen.
