### ISSUE TITLE
Purpose of mkl_p4n?

### ISSUE THREAD

**Issue by fgghjjkll** [kaldi-asr/kaldi#2202]
It seems that Intel deprecated this a while ago (MKL 11?), and so if you try to compile the gst-plugin (which the linker needed mkl_p4n for), you'll get an error saying that it can't find it. I removed the -lmkl_p4n flag from gst-plugin's Makefile and it compiled fine, and testing with alumae's kaldi-gstreamer-server seems to work without any issues either.
So before I submit a PR, I just wanted to know the purpose of this library?

**Comment by danpovey** [comment]
I have no idea.  Maybe @alumae can tell us.

**Comment by jtrmal** [comment]
IIRC, these libs contained some optimized code specific for P4. 
Intel changes the layout of the MKL libs now and then.  If it compiles and run without any problems, then the library is not needed.
The intel command line advisor (https://software.intel.com/en-us/articles/intel-mkl-link-line-advisor) can be used to figure out the proper switches and flags
