### ISSUE TITLE
Check range of `backstitch_training_interval`

### ISSUE THREAD

**Issue by tbluche** [kaldi-asr/kaldi#2203]
The option is used in a modulo here : https://github.com/kaldi-asr/kaldi/blob/master/src/nnet3/nnet-chain-training.cc#L73
But wasn't checked to be non-zero.
Should it be done here: https://github.com/kaldi-asr/kaldi/blob/master/src/nnet3/nnet-chain-training.cc#L39 ?

**Comment by danpovey** [comment]
@freewym, please fix.
