### ISSUE TITLE
WIP in swbd score_basic.sh

### ISSUE THREAD

**Issue by yzmyyff** [kaldi-asr/kaldi#2206]
We don't really use WIP param, just repeat ```lattice-best-path``` several times.

**Comment by danpovey** [comment]
@xiaohui-zhang, can you please fix?

**Comment by xiaohui-zhang** [comment]
sorry I'm confused about the issue here.... what does it mean by " just repeat lattice-best-path several times."? @yzmyyff

**Comment by danpovey** [comment]
He means here, in score_basic.sh:
```

*for* wip* in* $(echo $word_ins_penalty | sed 's/,/ /g'); *do*

  $cmd LMWT=$min_lmwt:$max_lmwt $dir/scoring/log/best_path.LMWT.${wip}.log \

    lattice-best-path --lm-scale=LMWT --word-symbol-table=$lang/words.txt \

    "ark:gunzip -c $dir/lat.*.gz|" ark,t:$dir/scoring/LMWT.${wip}.tra ||
*exit* 1;

*done*


```
the WIP is not really used.

**Comment by xiaohui-zhang** [comment]
ops sure. I thought the WIP here is "work-in-progress"....

**Comment by jtrmal** [comment]
@xiaohui-zhang I guess this was merged also?

**Comment by xiaohui-zhang** [comment]
yep
