### ISSUE TITLE
build issue for src/online

### ISSUE THREAD

**Issue by dwks** [kaldi-asr/kaldi#221]
src/online depends on jack on my Linux system because portaudio does, failing with undefined references to many jack functions. Not sure the best way to fix this although this works on Debian 8.2 (assuming libjack-dev is installed of course):
```
diff --git a/src/online/Makefile b/src/online/Makefile
index 4c0ad9f..27ddfe0 100644
--- a/src/online/Makefile
+++ b/src/online/Makefile
@@ -22,6 +22,7 @@ ifeq ($(UNAME), Linux)
   else
     EXTRA_LDLIBS += -lrt
   endif
+  EXTRA_LDLIBS += -ljack
 endif
```

**Comment by danpovey** [comment]
Let's wait till we get some other comments on this.
@jtrmal ?

**Comment by jtrmal** [comment]
That will solve problems for you, but will create problems for users that
do not have compiled portaudio against jack, I believe.
The correct solution would be, perhaps, use pkg-config? I'm not sure if we
can rely on its presence, though.
y.

**Comment by dwks** [comment]
It's strange. The pkg-config for portaudio doesn't list -ljack as a dependency even when it was built with jack support (which is the default if libjack-dev installed). So this doesn't help:
```
EXTRA_LDLIBS += $(shell pkg-config --libs ../../tools/portaudio/install/lib/pkgconfig/portaudio-2.0.pc)
```
Given the way the Makefile checks for alsa, here is a symmetric method for jack:
```
diff --git a/src/online/Makefile b/src/online/Makefile
index 4c0ad9f..3e1c7ca 100644
--- a/src/online/Makefile
+++ b/src/online/Makefile
@@ -22,6 +22,9 @@ ifeq ($(UNAME), Linux)
   else
     EXTRA_LDLIBS += -lrt
   endif
+  ifneq ($(wildcard ../../tools/portaudio/install/include/pa_jack.h),)
+    EXTRA_LDLIBS += -ljack
+  endif
 endif
 
 
```
There must be a better way however.

**Comment by dogancan** [comment]
Some time back I was struggling with this exact problem and the best solution I found at the time was to parse the portaudio libtool file after installation (tools/portaudio/lib/libportaudio.la) to figure out the library dependencies as well as linker flags on different platforms. The particular variables of interest are "dependency_libs" and "inherited_linker_flags".

**Comment by dwks** [comment]
Looks like a portaudio bug. The configure.in doesn't say it needs -ljack in its pkg-config for unix even though it does for windows; it just needs a LIBS="$LIBS $JACK_LIBS". I have reported it to the portaudio developers.

For kaldi, my earlier diff is probably sufficient unless we want to switch to pkg-config.

**Comment by danpovey** [comment]
I'll put it as a comment in the Makefile for now.
Dan

**Comment by dwks** [comment]
I meant this diff which should be safe.
```
+  ifneq ($(wildcard ../../tools/portaudio/install/include/pa_jack.h),)
+    EXTRA_LDLIBS += -ljack
+  endif
```

**Comment by danpovey** [comment]
Ok, I'll add that, thanks.

**Comment by dwks** [comment]
The portaudio folks don't seem to be fixing this right away. Let's just stick with what we already have. Closing the issue.
