### ISSUE TITLE
ami/s5b feature extraction issue

### ISSUE THREAD

**Issue by martaql** [kaldi-asr/kaldi#2222]
When using run.sh in ami/s5b I get the following log warnings.
Can anyone help me, please?

kaldi::MessageLogger::HandleMessage(kaldi::LogMessageEnvelope const&, char const*)
kaldi::MessageLogger::~MessageLogger()
kaldi::WaveHeaderReadGofer::Read4ByteTag()
kaldi::WaveInfo::Read(std::istream&)
kaldi::WaveData::Read(std::istream&)
kaldi::WaveHolder::Read(std::istream&)
kaldi::RandomAccessTableReaderScriptImpl<kaldi::WaveHolder>::HasKeyInternal(std::string const&, bool)
kaldi::RandomAccessTableReaderScriptImpl<kaldi::WaveHolder>::HasKey(std::string const&)
kaldi::RandomAccessTableReader<kaldi::WaveHolder>::HasKey(std::string const&)
main
__libc_start_main
_start

WARNING (extract-segments[5.3.116~1-ca5f]:Read():feat/wave-reader.h:197) Exception caught in WaveHolder::Read(). 
WARNING (extract-segments[5.3.116~1-ca5f]:HasKeyInternal():util/kaldi-table-inl.h:1776) Error reading object from stream 'sox -c 1 -t wavpcm -e signed-integer /home/ubuntu/kaldi/egs/ami/s5b/wav_db/TS3012d/audio/TS3012d.Headset-3.wav -t wavpcm - |'
WARNING (extract-segments[5.3.116~1-ca5f]:main():extract-segments.cc:125) Could not find recording AMI_TS3012d_H03, skipping segment AMI_TS3012d_H03_MTD048ME_0232390_0232439
LOG (extract-segments[5.3.116~1-ca5f]:main():extract-segments.cc:193) Successfully processed 0 lines out of 21700 in the segments file. 
WARNING (extract-segments[5.3.116~1-ca5f]:Close():kaldi-io.cc:512) Pipe sox -c 1 -t wavpcm -e signed-integer /home/ubuntu/kaldi/egs/ami/s5b/wav_db/TS3012d/audio/TS3012d.Headset-3.wav -t wavpcm - | had nonzero return status 32512
LOG (compute-mfcc-feats[5.3.116~1-ca5f]:main():compute-mfcc-feats.cc:176)  Done 0 out of 0 utterances.
LOG (copy-feats[5.3.116~1-ca5f]:main():copy-feats.cc:143) Copied 0 feature matrices.
# Accounting: time=20 threads=1
# Ended (code 1) at Thu Feb 15 06:15:57 UTC 2018, elapsed time 20 seconds

**Comment by jtrmal** [comment]
I think the real error message was higher in the log.
Anyway, there are two probable causes
a)
file /home/ubuntu/kaldi/egs/ami/s5b/wav_db/TS3012d/audio/TS3012d.Headset-3.wav
does not exist
b) you don't have sox installed or you have a version that does not support
the parameters. You could test that just running this command manually
 (sox -c 1 -t wavpcm -e signed-integer /home/ubuntu/kaldi/egs/ami/
s5b/wav_db/TS3012d/audio/TS3012d.Headset-3.wav -t wavpcm /dev/null )

y.

**Comment by martaql** [comment]
The problem was b), I did not have sox installed.
 
Thank you for the prompt reply.
