### ISSUE TITLE
Small bug with ParseOptions

### ISSUE THREAD

**Issue by maelp** [kaldi-asr/kaldi#2234]
There is an option in `ParseOptions` to remove the printing of the command-line arguments

https://github.com/kaldi-asr/kaldi/blob/master/src/util/parse-options.cc#L389

but this does not work for the first time it is called, at least not when calling it from C++ code which is using `ParseOptions`

I'm doing something like this:

 - create a ParseOptions
 - create an array of options
 - add the `--print-args=false` options
 - this prints the options
 - and if I do a `ParseOptions` a second time it is no longer printed

I expected that it wouldn't print the options the first time

**Comment by danpovey** [comment]
I don't really understand what you did-- you'll have to explain more concretely what you did, what member functions of class ParseOptions you called and with what arguments.

**Comment by maelp** [comment]
I do something which looks like this:

```
ParseOptions po("");
vector<const char *>argv;
string program_name = "program_name";
argv.push_back(program_name.c_str());
for (int i = 0 ; i < opts.size() ; i++) {
      argv.push_back(opts[i].c_str());
}
po.Read(argv.size(), (const char *const *)argv.data());
```

where I put the options in `opts`

even if I add the `--print-args=false` options to `opts` it still prints the command-line when calling `po.Read`, although https://github.com/kaldi-asr/kaldi/blob/85a3dd5f0b71e419abf1169a26b759bfc423a543/src/util/parse-options.h#L46 shows that `--print-args` is bound to the `print_args_` variable

**Comment by danpovey** [comment]
You'll have to get it in gdb to figure out what's going on.
Possibly you put a positional arg (not starting with --) before
--print-args=false and it was interpreted as a positional arg.

**Comment by maelp** [comment]
I put it as the first argument, but I will try to debug

**Comment by maelp** [comment]
After debugging I can confirm:

 - the `print-args` option is registered
 - I add `--print-args=false` at the beginning
 - the `print-args` option is correctly parsed
 - the `SetOption` is called with `print-args` set to `false`
 - at the end of the method, the `if (print_args_)` evaluates to `true` and prints the command line

**Comment by maelp** [comment]
Although at https://github.com/kaldi-asr/kaldi/blob/master/src/util/parse-options.cc#L553 if I print the value of the pointer at `(long)bool_map_["print-args"]` and `(long)print_args_` the values are different, although it is supposed to be equal when we register the option at https://github.com/kaldi-asr/kaldi/blob/85a3dd5f0b71e419abf1169a26b759bfc423a543/src/util/parse-options.h#L46

**Comment by danpovey** [comment]
Do "make depend" and make. If you changed something in the header, the
location of that variable in the object might have changed.

**Comment by maelp** [comment]
I found the bug, it was not in the Kaldi code
