### ISSUE TITLE
Fisher transcription data. getting it and using it. 

### ISSUE THREAD

**Issue by FahadMaqbool** [kaldi-asr/kaldi#2235]
Hi,
If I just want to run AMI's Script without changing it. i.e. I want to use fisher data. How should I get it and How can I change the run script accordingly. specially this case statement. for example.
"fe_03_p1_tran"
Is this some specific file/folder that I should be looking for??

case $(hostname -d) in
fit.vutbr.cz) FISHER_TRANS=/mnt/matylda2/data/FISHER/fe_03_p1_tran ;; # BUT,
clsp.jhu.edu) FISHER_TRANS=/export/corpora4/ami/fisher_trans/part1 ;; # JHU,
cstr.ed.ac.uk) FISHER_TRANS=pwd/eddie_data/lm/data/fisher/part1 ;; # Edinburgh,
*) echo "Please modify the script to add your loaction of the Fisher transcripts, or modify this script."; exit 1;;
esac

**Comment by danpovey** [comment]
just remove the case statement and set the FISHER_TRANS variable after the case statement.  closing as duplicate.
