### ISSUE TITLE
Building with unpatched openfst-1.5 installed in /usr

### ISSUE THREAD

**Issue by benob** [kaldi-asr/kaldi#224]
Even if I build kaldi with static openfst, it still tries to load libfstscript from /usr when used, for instance, with gst-kaldi-nnet2-online.
(gst-plugin-scanner:11140): GStreamer-WARNING **: Failed to load plugin './libgstkaldionline2.so': /usr/lib/libfstscript.so.1: undefined symbol: _ZN3fst22ShortestPathProperties

Any idea on how to fix (apart from uninstalling openfst from /usr)?

**Comment by jtrmal** [comment]
My guess would be that you compiled kaldi with static  openfst, but
the libgstkaldionline2
(gstreamer plugin) was compiled with dynamic version?
What ldd on the library will return?
y.

**Comment by benob** [comment]
You are right, it's a gst-kaldi-nnet2-online bug -- it does not follow kaldi's choice on making openfst static. Nevertheless, changing
OPENFSTLIBS="$FSTROOT/lib/libfst.a"
to
OPENFSTLIBS="$FSTROOT/lib/libfst.a $FSTROOT/lib/libfstscript.a"
in kaldi-trunk/src/configure works as well.

**Comment by jtrmal** [comment]
Tanel, do you have any view on this?
y,

**Comment by jtrmal** [comment]
@benob, as the issue seems more on the kaldi-gstreamer plugin, I propose to close this.

**Comment by posophe** [comment]
Yes, by the way as we talked about openfst-1.5, kaldi builds correctly with openfst 1.5 with no patch.

**Comment by jtrmal** [comment]
OK, thanks for letting us know -- I'll close this issue.

**Comment by danpovey** [comment]
Just FYI-- the patch was not to fix compilation problems but to
correct/modify run-time behavior.

**Comment by benob** [comment]
Could the patch be applied upstream?

**Comment by posophe** [comment]
It has to be rebased in a first place. It doesn't apply on state because of some functions changes. But I could submit it then if you wan't

**Comment by jtrmal** [comment]
If you have a patch feel free to send it to me (or submit a PR adding a
patch for FST 1.5 in the tools/ directory, similarly how openfst 1.4.1 is
modified)
y.

**Comment by posophe** [comment]
I would love to but I can't. I don't know what the patch is actually doing and how to adapt it to upstream changes

**Comment by jtrmal** [comment]
then perhaps we do not understand each other what was your proposition
about submitting it about?
y.

**Comment by posophe** [comment]
I meant submitting to fst upstream. Sorry, my bad.

**Comment by giuliopaci** [comment]
Hi to all, I already submitted the patch upstream. They told me they are going to review it in the next few months (the code seems easy, but the math behind it should be understood before it is accepted upstream).

Anyway, here is a refreshed version of the patch:
[1005_kaldi_patch.patch.txt](https://github.com/kaldi-asr/kaldi/files/119673/1005_kaldi_patch.patch.txt)

**Comment by danpovey** [comment]
I've already been waiting for years, but reminding them can't hurt.

**Comment by giuliopaci** [comment]
I knew that you already sent it, because they told me so, but was not aware that it was sent years ago. However I want to be optimist... And eventually remind them about this patch again in future.
I am pretty sure it will not be included in the next release. My goal would be to have it evaluated in two releases.
