### ISSUE TITLE
Issue with compiling tfrnnlm in Ubuntu16

### ISSUE THREAD

**Issue by martaql** [kaldi-asr/kaldi#2243]
Hi, I have been trying to compile tfrnnlm, but I get this error message:

g++-4.8 -shared -o libkaldi-tensorflow-rnnlm.so -Wl,--no-undefined -Wl,--as-needed  -Wl,-soname=libkaldi-tensorflow-rnnlm.so,--whole-archive kaldi-tensorflow-rnnlm.a -Wl,--no-whole-archive  -Wl,-rpath=/home/ubuntu/kaldi/tools/openfst/lib  -rdynamic -Wl,-rpath=/home/ubuntu/kaldi/src/lib  ../lm/libkaldi-lm.so  ../util/libkaldi-util.so  ../matrix/libkaldi-matrix.so  ../base/libkaldi-base.so /home/ubuntu/kaldi/tools/openfst/lib/libfst.so /usr/lib/libatlas.so.3 /usr/lib/libf77blas.so.3 /usr/lib/libcblas.so.3 /usr/lib/liblapack_atlas.so.3 -lm -lpthread -ldl -lz -ldl -fPIC -lrt -L../../tools/tensorflow/bazel-bin/tensorflow -ltensorflow_cc -ltensorflow_framework -L../../tools/tensorflow/bazel-bin/tensorflow -ltensorflow_framework
kaldi-tensorflow-rnnlm.a(tensorflow-rnnlm.o): In function `kaldi::tf_rnnlm::KaldiTfRnnlmWrapper::ReadTfModel(std::string const&, int)':
/home/ubuntu/kaldi/src/tfrnnlm/tensorflow-rnnlm.cc:75: undefined reference to `tensorflow::Status::ToString() const'
/home/ubuntu/kaldi/src/tfrnnlm/tensorflow-rnnlm.cc:79: undefined reference to `tensorflow::ReadBinaryProto(tensorflow::Env*, std::string const&, google::protobuf::MessageLite*)'
/home/ubuntu/kaldi/src/tfrnnlm/tensorflow-rnnlm.cc:82: undefined reference to `tensorflow::Status::ToString() const'
/home/ubuntu/kaldi/src/tfrnnlm/tensorflow-rnnlm.cc:88: undefined reference to `tensorflow::Status::ToString() const'
/home/ubuntu/kaldi/src/tfrnnlm/tensorflow-rnnlm.cc:100: undefined reference to `tensorflow::Status::ToString() const'
kaldi-tensorflow-rnnlm.a(tensorflow-rnnlm.o): In function `kaldi::tf_rnnlm::KaldiTfRnnlmWrapper::AcquireInitialTensors()':
/home/ubuntu/kaldi/src/tfrnnlm/tensorflow-rnnlm.cc:186: undefined reference to `tensorflow::Status::ToString() const'
/home/ubuntu/kaldi/src/tfrnnlm/tensorflow-rnnlm.cc:204: undefined reference to `tensorflow::Status::ToString() const'
kaldi-tensorflow-rnnlm.a(tensorflow-rnnlm.o):/home/ubuntu/kaldi/src/tfrnnlm/tensorflow-rnnlm.cc:238: more undefined references to `tensorflow::Status::ToString() const' follow
kaldi-tensorflow-rnnlm.a(tensorflow-rnnlm.o): In function `std::string* tensorflow::internal::MakeCheckOpString<long, int>(long const&, int const&, char const*)':
/home/ubuntu/kaldi/src/tfrnnlm/../../tools/tensorflow/tensorflow/core/platform/default/logging.h:187: undefined reference to `tensorflow::internal::CheckOpMessageBuilder::NewString()'
collect2: error: ld returned 1 exit status
../makefiles/default_rules.mk:31: recipe for target 'libkaldi-tensorflow-rnnlm.so' failed
make: *** [libkaldi-tensorflow-rnnlm.so] Error 1

[tfrnnlm_make.log](https://github.com/kaldi-asr/kaldi/files/1761261/tfrnnlm_make.log)

Can anyone help me?

**Comment by danpovey** [comment]
You shouldn't be explicitly configuring with gcc-4.8.  I think you misread the INSTALL file when you ran "configure", and added an option you shouldn't have added.  Make clean, re-configure without that option, and make again.

**Comment by martaql** [comment]
Thank you for the quick reply. 
I see, I'm sorry. I re-configured that, but I am still getting the same mistake. 
Any idea why that could be?

g++ -std=c++11 -I.. -I/home/ubuntu/kaldi/tools/openfst/include -Wno-sign-compare -I../../tools/tensorflow/bazel-tensorflow/external/protobuf/src -I../../tools/tensorflow/bazel-genfiles -I../../tools/tensorflow -I../../tools/tensorflow/tensorflow/contrib/makefile/downloads/eigen -I../../tools/tensorflow/tensorflow/contrib/makefile/downloads/nsync/public -I../../tools/tensorflow/tensorflow/contrib/makefile/downloads/protobuf/src -Wall -Wno-sign-compare -Wno-unused-local-typedefs -Wno-deprecated-declarations -Winit-self -DKALDI_DOUBLEPRECISION=0 -DHAVE_EXECINFO_H=1 -DHAVE_CXXABI_H -DHAVE_ATLAS -I/home/ubuntu/kaldi/tools/ATLAS_headers/include -msse -msse2 -pthread -g  -fPIC   -c -o tensorflow-rnnlm.o tensorflow-rnnlm.cc
In file included from /home/ubuntu/kaldi/tools/openfst/include/fst/expanded-fst.h:13:0,
                 from /home/ubuntu/kaldi/tools/openfst/include/fst/fstlib.h:28,
                 from ../fstext/deterministic-fst.h:56,
                 from ../tfrnnlm/tensorflow-rnnlm.h:28,
                 from tensorflow-rnnlm.cc:28:
/home/ubuntu/kaldi/tools/openfst/include/fst/log.h:48:0: warning: "LOG" redefined [enabled by default]
 #define LOG(type) LogMessage(#type).stream()
 ^
In file included from ../../tools/tensorflow/tensorflow/core/platform/logging.h:25:0,
                 from ../../tools/tensorflow/tensorflow/core/lib/core/status.h:25,
                 from ../../tools/tensorflow/tensorflow/core/framework/variant.h:29,
                 from ../../tools/tensorflow/tensorflow/core/framework/allocator.h:26,
                 from ../../tools/tensorflow/tensorflow/core/framework/tensor.h:20,
                 from ../../tools/tensorflow/tensorflow/core/public/session.h:24,
                 from tensorflow-rnnlm.cc:24:
../../tools/tensorflow/tensorflow/core/platform/default/logging.h:77:0: note: this is the location of the previous definition
 #define LOG(severity) _TF_LOG_##severity
 ^
In file included from /home/ubuntu/kaldi/tools/openfst/include/fst/expanded-fst.h:13:0,
                 from /home/ubuntu/kaldi/tools/openfst/include/fst/fstlib.h:28,
                 from ../fstext/deterministic-fst.h:56,
                 from ../tfrnnlm/tensorflow-rnnlm.h:28,
                 from tensorflow-rnnlm.cc:28:
/home/ubuntu/kaldi/tools/openfst/include/fst/log.h:49:0: warning: "VLOG" redefined [enabled by default]
 #define VLOG(level) if ((level) <= FLAGS_v) LOG(INFO)
 ^
In file included from ../../tools/tensorflow/tensorflow/core/platform/logging.h:25:0,
                 from ../../tools/tensorflow/tensorflow/core/lib/core/status.h:25,
                 from ../../tools/tensorflow/tensorflow/core/framework/variant.h:29,
                 from ../../tools/tensorflow/tensorflow/core/framework/allocator.h:26,
                 from ../../tools/tensorflow/tensorflow/core/framework/tensor.h:20,
                 from ../../tools/tensorflow/tensorflow/core/public/session.h:24,
                 from tensorflow-rnnlm.cc:24:
../../tools/tensorflow/tensorflow/core/platform/default/logging.h:89:0: note: this is the location of the previous definition
 #define VLOG(lvl)                        \
 ^
In file included from /home/ubuntu/kaldi/tools/openfst/include/fst/expanded-fst.h:13:0,
                 from /home/ubuntu/kaldi/tools/openfst/include/fst/fstlib.h:28,
                 from ../fstext/deterministic-fst.h:56,
                 from ../tfrnnlm/tensorflow-rnnlm.h:28,
                 from tensorflow-rnnlm.cc:28:
/home/ubuntu/kaldi/tools/openfst/include/fst/log.h:61:0: warning: "CHECK" redefined [enabled by default]
 #define CHECK(x) FstCheck(static_cast<bool>(x), #x, __FILE__, __LINE__)
 ^
In file included from ../../tools/tensorflow/tensorflow/core/platform/logging.h:25:0,
                 from ../../tools/tensorflow/tensorflow/core/lib/core/status.h:25,
                 from ../../tools/tensorflow/tensorflow/core/framework/variant.h:29,
                 from ../../tools/tensorflow/tensorflow/core/framework/allocator.h:26,
                 from ../../tools/tensorflow/tensorflow/core/framework/tensor.h:20,
                 from ../../tools/tensorflow/tensorflow/core/public/session.h:24,
                 from tensorflow-rnnlm.cc:24:
../../tools/tensorflow/tensorflow/core/platform/default/logging.h:97:0: note: this is the location of the previous definition
 #define CHECK(condition)              \
 ^
In file included from /home/ubuntu/kaldi/tools/openfst/include/fst/expanded-fst.h:13:0,
                 from /home/ubuntu/kaldi/tools/openfst/include/fst/fstlib.h:28,
                 from ../fstext/deterministic-fst.h:56,
                 from ../tfrnnlm/tensorflow-rnnlm.h:28,
                 from tensorflow-rnnlm.cc:28:
/home/ubuntu/kaldi/tools/openfst/include/fst/log.h:62:0: warning: "CHECK_EQ" redefined [enabled by default]
 #define CHECK_EQ(x, y) CHECK((x) == (y))
 ^
In file included from ../../tools/tensorflow/tensorflow/core/platform/logging.h:25:0,
                 from ../../tools/tensorflow/tensorflow/core/lib/core/status.h:25,
                 from ../../tools/tensorflow/tensorflow/core/framework/variant.h:29,
                 from ../../tools/tensorflow/tensorflow/core/framework/allocator.h:26,
                 from ../../tools/tensorflow/tensorflow/core/framework/tensor.h:20,
                 from ../../tools/tensorflow/tensorflow/core/public/session.h:24,
                 from tensorflow-rnnlm.cc:24:
../../tools/tensorflow/tensorflow/core/platform/default/logging.h:249:0: note: this is the location of the previous definition
 #define CHECK_EQ(val1, val2) CHECK_OP(Check_EQ, ==, val1, val2)
 ^
In file included from /home/ubuntu/kaldi/tools/openfst/include/fst/expanded-fst.h:13:0,
                 from /home/ubuntu/kaldi/tools/openfst/include/fst/fstlib.h:28,
                 from ../fstext/deterministic-fst.h:56,
                 from ../tfrnnlm/tensorflow-rnnlm.h:28,
                 from tensorflow-rnnlm.cc:28:
/home/ubuntu/kaldi/tools/openfst/include/fst/log.h:63:0: warning: "CHECK_LT" redefined [enabled by default]
 #define CHECK_LT(x, y) CHECK((x) < (y))
 ^
In file included from ../../tools/tensorflow/tensorflow/core/platform/logging.h:25:0,
                 from ../../tools/tensorflow/tensorflow/core/lib/core/status.h:25,
                 from ../../tools/tensorflow/tensorflow/core/framework/variant.h:29,
                 from ../../tools/tensorflow/tensorflow/core/framework/allocator.h:26,
                 from ../../tools/tensorflow/tensorflow/core/framework/tensor.h:20,
                 from ../../tools/tensorflow/tensorflow/core/public/session.h:24,
                 from tensorflow-rnnlm.cc:24:
../../tools/tensorflow/tensorflow/core/platform/default/logging.h:252:0: note: this is the location of the previous definition
 #define CHECK_LT(val1, val2) CHECK_OP(Check_LT, <, val1, val2)
 ^
In file included from /home/ubuntu/kaldi/tools/openfst/include/fst/expanded-fst.h:13:0,
                 from /home/ubuntu/kaldi/tools/openfst/include/fst/fstlib.h:28,
                 from ../fstext/deterministic-fst.h:56,
                 from ../tfrnnlm/tensorflow-rnnlm.h:28,
                 from tensorflow-rnnlm.cc:28:
/home/ubuntu/kaldi/tools/openfst/include/fst/log.h:64:0: warning: "CHECK_GT" redefined [enabled by default]
 #define CHECK_GT(x, y) CHECK((x) > (y))
 ^
In file included from ../../tools/tensorflow/tensorflow/core/platform/logging.h:25:0,
                 from ../../tools/tensorflow/tensorflow/core/lib/core/status.h:25,
                 from ../../tools/tensorflow/tensorflow/core/framework/variant.h:29,
                 from ../../tools/tensorflow/tensorflow/core/framework/allocator.h:26,
                 from ../../tools/tensorflow/tensorflow/core/framework/tensor.h:20,
                 from ../../tools/tensorflow/tensorflow/core/public/session.h:24,
                 from tensorflow-rnnlm.cc:24:
../../tools/tensorflow/tensorflow/core/platform/default/logging.h:254:0: note: this is the location of the previous definition
 #define CHECK_GT(val1, val2) CHECK_OP(Check_GT, >, val1, val2)
 ^
In file included from /home/ubuntu/kaldi/tools/openfst/include/fst/expanded-fst.h:13:0,
                 from /home/ubuntu/kaldi/tools/openfst/include/fst/fstlib.h:28,
                 from ../fstext/deterministic-fst.h:56,
                 from ../tfrnnlm/tensorflow-rnnlm.h:28,
                 from tensorflow-rnnlm.cc:28:
/home/ubuntu/kaldi/tools/openfst/include/fst/log.h:65:0: warning: "CHECK_LE" redefined [enabled by default]
 #define CHECK_LE(x, y) CHECK((x) <= (y))
 ^
In file included from ../../tools/tensorflow/tensorflow/core/platform/logging.h:25:0,
                 from ../../tools/tensorflow/tensorflow/core/lib/core/status.h:25,
                 from ../../tools/tensorflow/tensorflow/core/framework/variant.h:29,
                 from ../../tools/tensorflow/tensorflow/core/framework/allocator.h:26,
                 from ../../tools/tensorflow/tensorflow/core/framework/tensor.h:20,
                 from ../../tools/tensorflow/tensorflow/core/public/session.h:24,
                 from tensorflow-rnnlm.cc:24:
../../tools/tensorflow/tensorflow/core/platform/default/logging.h:251:0: note: this is the location of the previous definition
 #define CHECK_LE(val1, val2) CHECK_OP(Check_LE, <=, val1, val2)
 ^
In file included from /home/ubuntu/kaldi/tools/openfst/include/fst/expanded-fst.h:13:0,
                 from /home/ubuntu/kaldi/tools/openfst/include/fst/fstlib.h:28,
                 from ../fstext/deterministic-fst.h:56,
                 from ../tfrnnlm/tensorflow-rnnlm.h:28,
                 from tensorflow-rnnlm.cc:28:
/home/ubuntu/kaldi/tools/openfst/include/fst/log.h:66:0: warning: "CHECK_GE" redefined [enabled by default]
 #define CHECK_GE(x, y) CHECK((x) >= (y))
 ^
In file included from ../../tools/tensorflow/tensorflow/core/platform/logging.h:25:0,
                 from ../../tools/tensorflow/tensorflow/core/lib/core/status.h:25,
                 from ../../tools/tensorflow/tensorflow/core/framework/variant.h:29,
                 from ../../tools/tensorflow/tensorflow/core/framework/allocator.h:26,
                 from ../../tools/tensorflow/tensorflow/core/framework/tensor.h:20,
                 from ../../tools/tensorflow/tensorflow/core/public/session.h:24,
                 from tensorflow-rnnlm.cc:24:
../../tools/tensorflow/tensorflow/core/platform/default/logging.h:253:0: note: this is the location of the previous definition
 #define CHECK_GE(val1, val2) CHECK_OP(Check_GE, >=, val1, val2)
 ^
In file included from /home/ubuntu/kaldi/tools/openfst/include/fst/expanded-fst.h:13:0,
                 from /home/ubuntu/kaldi/tools/openfst/include/fst/fstlib.h:28,
                 from ../fstext/deterministic-fst.h:56,
                 from ../tfrnnlm/tensorflow-rnnlm.h:28,
                 from tensorflow-rnnlm.cc:28:
/home/ubuntu/kaldi/tools/openfst/include/fst/log.h:67:0: warning: "CHECK_NE" redefined [enabled by default]
 #define CHECK_NE(x, y) CHECK((x) != (y))
 ^
In file included from ../../tools/tensorflow/tensorflow/core/platform/logging.h:25:0,
                 from ../../tools/tensorflow/tensorflow/core/lib/core/status.h:25,
                 from ../../tools/tensorflow/tensorflow/core/framework/variant.h:29,
                 from ../../tools/tensorflow/tensorflow/core/framework/allocator.h:26,
                 from ../../tools/tensorflow/tensorflow/core/framework/tensor.h:20,
                 from ../../tools/tensorflow/tensorflow/core/public/session.h:24,
                 from tensorflow-rnnlm.cc:24:
../../tools/tensorflow/tensorflow/core/platform/default/logging.h:250:0: note: this is the location of the previous definition
 #define CHECK_NE(val1, val2) CHECK_OP(Check_NE, !=, val1, val2)
 ^
In file included from /home/ubuntu/kaldi/tools/openfst/include/fst/expanded-fst.h:13:0,
                 from /home/ubuntu/kaldi/tools/openfst/include/fst/fstlib.h:28,
                 from ../fstext/deterministic-fst.h:56,
                 from ../tfrnnlm/tensorflow-rnnlm.h:28,
                 from tensorflow-rnnlm.cc:28:
/home/ubuntu/kaldi/tools/openfst/include/fst/log.h:70:0: warning: "DCHECK" redefined [enabled by default]
 #define DCHECK(x) assert(x)
 ^
In file included from ../../tools/tensorflow/tensorflow/core/platform/logging.h:25:0,
                 from ../../tools/tensorflow/tensorflow/core/lib/core/status.h:25,
                 from ../../tools/tensorflow/tensorflow/core/framework/variant.h:29,
                 from ../../tools/tensorflow/tensorflow/core/framework/allocator.h:26,
                 from ../../tools/tensorflow/tensorflow/core/framework/tensor.h:20,
                 from ../../tools/tensorflow/tensorflow/core/public/session.h:24,
                 from tensorflow-rnnlm.cc:24:
../../tools/tensorflow/tensorflow/core/platform/default/logging.h:261:0: note: this is the location of the previous definition
 #define DCHECK(condition) CHECK(condition)
 ^
In file included from /home/ubuntu/kaldi/tools/openfst/include/fst/expanded-fst.h:13:0,
                 from /home/ubuntu/kaldi/tools/openfst/include/fst/fstlib.h:28,
                 from ../fstext/deterministic-fst.h:56,
                 from ../tfrnnlm/tensorflow-rnnlm.h:28,
                 from tensorflow-rnnlm.cc:28:
/home/ubuntu/kaldi/tools/openfst/include/fst/log.h:71:0: warning: "DCHECK_EQ" redefined [enabled by default]
 #define DCHECK_EQ(x, y) DCHECK((x) == (y))
 ^
In file included from ../../tools/tensorflow/tensorflow/core/platform/logging.h:25:0,
                 from ../../tools/tensorflow/tensorflow/core/lib/core/status.h:25,
                 from ../../tools/tensorflow/tensorflow/core/framework/variant.h:29,
                 from ../../tools/tensorflow/tensorflow/core/framework/allocator.h:26,
                 from ../../tools/tensorflow/tensorflow/core/framework/tensor.h:20,
                 from ../../tools/tensorflow/tensorflow/core/public/session.h:24,
                 from tensorflow-rnnlm.cc:24:
../../tools/tensorflow/tensorflow/core/platform/default/logging.h:262:0: note: this is the location of the previous definition
 #define DCHECK_EQ(val1, val2) CHECK_EQ(val1, val2)
 ^
In file included from /home/ubuntu/kaldi/tools/openfst/include/fst/expanded-fst.h:13:0,
                 from /home/ubuntu/kaldi/tools/openfst/include/fst/fstlib.h:28,
                 from ../fstext/deterministic-fst.h:56,
                 from ../tfrnnlm/tensorflow-rnnlm.h:28,
                 from tensorflow-rnnlm.cc:28:
/home/ubuntu/kaldi/tools/openfst/include/fst/log.h:72:0: warning: "DCHECK_LT" redefined [enabled by default]
 #define DCHECK_LT(x, y) DCHECK((x) < (y))
 ^
In file included from ../../tools/tensorflow/tensorflow/core/platform/logging.h:25:0,
                 from ../../tools/tensorflow/tensorflow/core/lib/core/status.h:25,
                 from ../../tools/tensorflow/tensorflow/core/framework/variant.h:29,
                 from ../../tools/tensorflow/tensorflow/core/framework/allocator.h:26,
                 from ../../tools/tensorflow/tensorflow/core/framework/tensor.h:20,
                 from ../../tools/tensorflow/tensorflow/core/public/session.h:24,
                 from tensorflow-rnnlm.cc:24:
../../tools/tensorflow/tensorflow/core/platform/default/logging.h:265:0: note: this is the location of the previous definition
 #define DCHECK_LT(val1, val2) CHECK_LT(val1, val2)
 ^
In file included from /home/ubuntu/kaldi/tools/openfst/include/fst/expanded-fst.h:13:0,
                 from /home/ubuntu/kaldi/tools/openfst/include/fst/fstlib.h:28,
                 from ../fstext/deterministic-fst.h:56,
                 from ../tfrnnlm/tensorflow-rnnlm.h:28,
                 from tensorflow-rnnlm.cc:28:
/home/ubuntu/kaldi/tools/openfst/include/fst/log.h:73:0: warning: "DCHECK_GT" redefined [enabled by default]
 #define DCHECK_GT(x, y) DCHECK((x) > (y))
 ^
In file included from ../../tools/tensorflow/tensorflow/core/platform/logging.h:25:0,
                 from ../../tools/tensorflow/tensorflow/core/lib/core/status.h:25,
                 from ../../tools/tensorflow/tensorflow/core/framework/variant.h:29,
                 from ../../tools/tensorflow/tensorflow/core/framework/allocator.h:26,
                 from ../../tools/tensorflow/tensorflow/core/framework/tensor.h:20,
                 from ../../tools/tensorflow/tensorflow/core/public/session.h:24,
                 from tensorflow-rnnlm.cc:24:
../../tools/tensorflow/tensorflow/core/platform/default/logging.h:267:0: note: this is the location of the previous definition
 #define DCHECK_GT(val1, val2) CHECK_GT(val1, val2)
 ^
In file included from /home/ubuntu/kaldi/tools/openfst/include/fst/expanded-fst.h:13:0,
                 from /home/ubuntu/kaldi/tools/openfst/include/fst/fstlib.h:28,
                 from ../fstext/deterministic-fst.h:56,
                 from ../tfrnnlm/tensorflow-rnnlm.h:28,
                 from tensorflow-rnnlm.cc:28:
/home/ubuntu/kaldi/tools/openfst/include/fst/log.h:74:0: warning: "DCHECK_LE" redefined [enabled by default]
 #define DCHECK_LE(x, y) DCHECK((x) <= (y))
 ^
In file included from ../../tools/tensorflow/tensorflow/core/platform/logging.h:25:0,
                 from ../../tools/tensorflow/tensorflow/core/lib/core/status.h:25,
                 from ../../tools/tensorflow/tensorflow/core/framework/variant.h:29,
                 from ../../tools/tensorflow/tensorflow/core/framework/allocator.h:26,
                 from ../../tools/tensorflow/tensorflow/core/framework/tensor.h:20,
                 from ../../tools/tensorflow/tensorflow/core/public/session.h:24,
                 from tensorflow-rnnlm.cc:24:
../../tools/tensorflow/tensorflow/core/platform/default/logging.h:264:0: note: this is the location of the previous definition
 #define DCHECK_LE(val1, val2) CHECK_LE(val1, val2)
 ^
In file included from /home/ubuntu/kaldi/tools/openfst/include/fst/expanded-fst.h:13:0,
                 from /home/ubuntu/kaldi/tools/openfst/include/fst/fstlib.h:28,
                 from ../fstext/deterministic-fst.h:56,
                 from ../tfrnnlm/tensorflow-rnnlm.h:28,
                 from tensorflow-rnnlm.cc:28:
/home/ubuntu/kaldi/tools/openfst/include/fst/log.h:75:0: warning: "DCHECK_GE" redefined [enabled by default]
 #define DCHECK_GE(x, y) DCHECK((x) >= (y))
 ^
In file included from ../../tools/tensorflow/tensorflow/core/platform/logging.h:25:0,
                 from ../../tools/tensorflow/tensorflow/core/lib/core/status.h:25,
                 from ../../tools/tensorflow/tensorflow/core/framework/variant.h:29,
                 from ../../tools/tensorflow/tensorflow/core/framework/allocator.h:26,
                 from ../../tools/tensorflow/tensorflow/core/framework/tensor.h:20,
                 from ../../tools/tensorflow/tensorflow/core/public/session.h:24,
                 from tensorflow-rnnlm.cc:24:
../../tools/tensorflow/tensorflow/core/platform/default/logging.h:266:0: note: this is the location of the previous definition
 #define DCHECK_GE(val1, val2) CHECK_GE(val1, val2)
 ^
In file included from /home/ubuntu/kaldi/tools/openfst/include/fst/expanded-fst.h:13:0,
                 from /home/ubuntu/kaldi/tools/openfst/include/fst/fstlib.h:28,
                 from ../fstext/deterministic-fst.h:56,
                 from ../tfrnnlm/tensorflow-rnnlm.h:28,
                 from tensorflow-rnnlm.cc:28:
/home/ubuntu/kaldi/tools/openfst/include/fst/log.h:76:0: warning: "DCHECK_NE" redefined [enabled by default]
 #define DCHECK_NE(x, y) DCHECK((x) != (y))
 ^
In file included from ../../tools/tensorflow/tensorflow/core/platform/logging.h:25:0,
                 from ../../tools/tensorflow/tensorflow/core/lib/core/status.h:25,
                 from ../../tools/tensorflow/tensorflow/core/framework/variant.h:29,
                 from ../../tools/tensorflow/tensorflow/core/framework/allocator.h:26,
                 from ../../tools/tensorflow/tensorflow/core/framework/tensor.h:20,
                 from ../../tools/tensorflow/tensorflow/core/public/session.h:24,
                 from tensorflow-rnnlm.cc:24:
../../tools/tensorflow/tensorflow/core/platform/default/logging.h:263:0: note: this is the location of the previous definition
 #define DCHECK_NE(val1, val2) CHECK_NE(val1, val2)
 ^
ar -cru kaldi-tensorflow-rnnlm.a tensorflow-rnnlm.o
ar: `u' modifier ignored since `D' is the default (see `U')
ranlib kaldi-tensorflow-rnnlm.a
g++ -shared -o libkaldi-tensorflow-rnnlm.so -Wl,--no-undefined -Wl,--as-needed  -Wl,-soname=libkaldi-tensorflow-rnnlm.so,--whole-archive kaldi-tensorflow-rnnlm.a -Wl,--no-whole-archive  -Wl,-rpath=/home/ubuntu/kaldi/tools/openfst/lib  -rdynamic -Wl,-rpath=/home/ubuntu/kaldi/src/lib  ../lm/libkaldi-lm.so  ../util/libkaldi-util.so  ../matrix/libkaldi-matrix.so  ../base/libkaldi-base.so /home/ubuntu/kaldi/tools/openfst/lib/libfst.so /usr/lib/libatlas.so.3 /usr/lib/libf77blas.so.3 /usr/lib/libcblas.so.3 /usr/lib/liblapack_atlas.so.3 -lm -lpthread -ldl -lz -ldl -fPIC -lrt -L../../tools/tensorflow/bazel-bin/tensorflow -ltensorflow_cc -ltensorflow_framework -L../../tools/tensorflow/bazel-bin/tensorflow -ltensorflow_framework
kaldi-tensorflow-rnnlm.a(tensorflow-rnnlm.o): In function `kaldi::tf_rnnlm::KaldiTfRnnlmWrapper::ReadTfModel(std::string const&, int)':
/home/ubuntu/kaldi/src/tfrnnlm/tensorflow-rnnlm.cc:75: undefined reference to `tensorflow::Status::ToString() const'
/home/ubuntu/kaldi/src/tfrnnlm/tensorflow-rnnlm.cc:79: undefined reference to `tensorflow::ReadBinaryProto(tensorflow::Env*, std::string const&, google::protobuf::MessageLite*)'
/home/ubuntu/kaldi/src/tfrnnlm/tensorflow-rnnlm.cc:82: undefined reference to `tensorflow::Status::ToString() const'
/home/ubuntu/kaldi/src/tfrnnlm/tensorflow-rnnlm.cc:88: undefined reference to `tensorflow::Status::ToString() const'
/home/ubuntu/kaldi/src/tfrnnlm/tensorflow-rnnlm.cc:100: undefined reference to `tensorflow::Status::ToString() const'
kaldi-tensorflow-rnnlm.a(tensorflow-rnnlm.o): In function `kaldi::tf_rnnlm::KaldiTfRnnlmWrapper::AcquireInitialTensors()':
/home/ubuntu/kaldi/src/tfrnnlm/tensorflow-rnnlm.cc:186: undefined reference to `tensorflow::Status::ToString() const'
/home/ubuntu/kaldi/src/tfrnnlm/tensorflow-rnnlm.cc:204: undefined reference to `tensorflow::Status::ToString() const'
kaldi-tensorflow-rnnlm.a(tensorflow-rnnlm.o):/home/ubuntu/kaldi/src/tfrnnlm/tensorflow-rnnlm.cc:238: more undefined references to `tensorflow::Status::ToString() const' follow
kaldi-tensorflow-rnnlm.a(tensorflow-rnnlm.o): In function `std::string* tensorflow::internal::MakeCheckOpString<long, int>(long const&, int const&, char const*)':
/home/ubuntu/kaldi/src/tfrnnlm/../../tools/tensorflow/tensorflow/core/platform/default/logging.h:187: undefined reference to `tensorflow::internal::CheckOpMessageBuilder::NewString()'
collect2: error: ld returned 1 exit status
../makefiles/default_rules.mk:31: recipe for target 'libkaldi-tensorflow-rnnlm.so' failed
make: *** [libkaldi-tensorflow-rnnlm.so] Error 1

**Comment by danpovey** [comment]
Likely you didn't read my last response carefully and failed to "make clean".

**Comment by martaql** [comment]
I did read it very carefully and did make clean before doing make again, but I got this error again.

**Comment by danpovey** [comment]
do "make clean" in the src/ directory and then make again.

If that still fails, remove the openfst directory e.g. tools/openfst-1.6.5
and do "make" in tools/ again to recompile it, then do "make clean" in
src/, and retry.

And if that still fails, let me know g++ version.  (g++ --version).

**Comment by martaql** [comment]
Thank you for the quick reply, again. 

I followed all the possible steps, but I am still getting the same error. 
My g++ version is : 
g++ (Ubuntu 4.8.5-4ubuntu2) 4.8.5
Copyright (C) 2015 Free Software Foundation, Inc.

**Comment by danpovey** [comment]
You may have to update your OS to get a more recent compiler.
There may be a way to fix it with that older compiler but we are not putting a lot of effort into this TensorFlow-based setup.

**Comment by martaql** [comment]
Ok, I upgraded my compiler to g++ 6.3 and went through the whole process again. 
I didn't get the error this time, so I guess that was the problem. 
Thank you!
