### ISSUE TITLE
error in thchs-30_data_prep.sh

### ISSUE THREAD

**Issue by xikunlun001** [kaldi-asr/kaldi#2251]
Hi,

I'm trying to play kaldi on my Mac and got an error that I can't figure it out in 3 hours.
I built kaldi successfully and tested well in yesno case.
Then I downloaded thchs-30 files and set the path to my local. 
Once I run the ./run.sh file,  an error appeared in thchs-30_data_prep.sh as following:

creating data/{train,dev,test}
cleaning data/train
preparing scps and text in data/train
local/thchs-30_data_prep.sh: line 19: /usr/bin/find: Argument list too long
cp: word.txt: No such file or directory
sort: open failed: wav.scp: No such file or directory
sort: open failed: utt2spk: No such file or directory
sort: open failed: text: No such file or directory
sort: open failed: phone.txt: No such file or directory
cleaning data/dev
preparing scps and text in data/dev
xargs: {}: No such file or directory
cp: word.txt: No such file or directory
sort: open failed: wav.scp: No such file or directory
sort: open failed: utt2spk: No such file or directory
sort: open failed: text: No such file or directory
sort: open failed: phone.txt: No such file or directory
cleaning data/test
preparing scps and text in data/test
xargs: {}: No such file or directory
cp: word.txt: No such file or directory
sort: open failed: wav.scp: No such file or directory
sort: open failed: utt2spk: No such file or directory
sort: open failed: text: No such file or directory
sort: open failed: phone.txt: No such file or directory

Anyone can help? I'll really appreciate if anyone can help to tell what's wrong of it.

Many thanks

**Comment by danpovey** [comment]
@naxingyu, can you look into this?
I suspect that 'find' in thchs-30_data_prep.sh should be 'echo'.
And there seems to be a compatibility issue with mac, with the -i option; it does not default to {}.
I suspect the xargs command should really be
` xargs -I% echo basename %.wav`

**Comment by xikunlun001** [comment]
@danpovey 
Thanks for quick response.
After replaced xargs command to "xargs -I% echo basename % .wav"
It still shows for train data: Argument list too long                      (Too many files in that folder?)
In test and dev folders, it seems the "do" part can't locate the correct file name or directory (Sorry, I'm not familiar with shell) and gave the following invalid number and no such file or directory error:

**preparing scps and text in data/train
local/thchs-30_data_prep.sh: line 19: /usr/bin/find: Argument list too long
cp: word.txt: No such file or directory
sort: open failed: wav.scp: No such file or directory
sort: open failed: utt2spk: No such file or directory
sort: open failed: text: No such file or directory
sort: open failed: phone.txt: No such file or directory
cleaning data/dev
preparing scps and text in data/dev
local/thchs-30_data_prep.sh: line 28: printf: basename: invalid number
local/thchs-30_data_prep.sh: line 30: printf: basename: invalid number
sed: /Users/xichen/Desktop/kaldi/egs/thchs30/Data/data_thchs30/data/basename.wav.trn: No such file or directory
sed: /Users/xichen/Desktop/kaldi/egs/thchs30/Data/data_thchs30/data/basename.wav.trn: No such file or directory
local/thchs-30_data_prep.sh: line 28: printf: /Users/xichen/Desktop/kaldi/egs/thchs30/Data/data: invalid number
local/thchs-30_data_prep.sh: line 30: printf: /Users/xichen/Desktop/kaldi/egs/thchs30/Data/data: invalid number
local/thchs-30_data_prep.sh: line 30: printf: thchs30/dev/A11: invalid number
sed: /Users/xichen/Desktop/kaldi/egs/thchs30/Data/data_thchs30/data//Users/xichen/Desktop/kaldi/egs/thchs30/Data/data_thchs30/dev/A11_101.wav.wav.trn: No such file or directory
sed: /Users/xichen/Desktop/kaldi/egs/thchs30/Data/data_thchs30/data//Users/xichen/Desktop/kaldi/egs/thchs30/Data/data_thchs30/dev/A11_101.wav.wav.trn: No such file or directory


.....

local/thchs-30_data_prep.sh: line 28: printf: /Users/xichen/Desktop/kaldi/egs/thchs30/Data/data: invalid number
local/thchs-30_data_prep.sh: line 30: printf: /Users/xichen/Desktop/kaldi/egs/thchs30/Data/data: invalid number
local/thchs-30_data_prep.sh: line 30: printf: thchs30/dev/A11: invalid number
sed: /Users/xichen/Desktop/kaldi/egs/thchs30/Data/data_thchs30/data//Users/xichen/Desktop/kaldi/egs/thchs30/Data/data_thchs30/dev/A11_60.wav.wav.trn: No such file or directory
sed: /Users/xichen/Desktop/kaldi/egs/thchs30/Data/data_thchs30/data//Users/xichen/Desktop/kaldi/egs/thchs30/Data/data_thchs30/dev/A11_60.wav.wav.trn: No such file or directory
^Z
[7]+  Stopped                 ./run.sh**

**Comment by danpovey** [comment]
Read my original response more carefully, there were two parts.

**Comment by danpovey** [comment]
actually, I now realize that changing 'find' to 'echo' wouldn't fix it.
You could try changin
`find foo/*.wav`
to
`find foo -name '*.wav'`
but I'm not 100% sure it will fix it.  Anyway I don't really maintain this recipe personally, @naxingyu will fix it I hope.

**Comment by xikunlun001** [comment]
@danpovey Thanks, Daniel. Do you think this is a compatibility issue with mac and the original code could work on a Linux system?
I tried your code and it works in the find part which no "Argument to long" error anymore, but the  invalid number and no such file or directory errors still not fixed. I hope @naxingyu could help to fix it or I'll try it on a Linux one later.

Thanks again.

**Comment by xikunlun001** [comment]
changed to the following and figure it out:

for nn in `find  $corpus_dir/$x -name "*.wav" | sort -u | xargs -I {} basename {} .wav`; do

**Comment by danpovey** [comment]
do you know how to make a pull request to github?  Xingyu doesn't seem to
be responding so I could merge a PR from you.

**Comment by xikunlun001** [comment]
@danpovey 
Yes, I can do that.

**Comment by naxingyu** [comment]
Sorry I just notice this. Thanks for the fix.

Best,
Xingyu Na
