### ISSUE TITLE
run_asr_segmentation.sh stage 2 makes train directory invalid

### ISSUE THREAD

**Issue by olix20** [kaldi-asr/kaldi#2269]
background: trying to do SAD using [run_asr_segmentation.sh](https://github.com/kaldi-asr/kaldi/blob/master/egs/swbd/s5c/local/run_asr_segmentation.sh). 

Main training data is in $data_dir which is fixed/validated with utterance ids prefixed with speaker ids. 

[prepare_targets_gmm.sh](https://github.com/kaldi-asr/kaldi/blob/master/egs/wsj/s5/steps/segmentation/prepare_targets_gmm.sh) in stage 3 reguires both <data> and <whole-recording-data> to have the recording-id as speaker. 

For this reasosn, stage 2 of `run_asr_segmentation.sh ` tries to replace speaker ids in utt2spk with recording ids but it's an incomplete effort: utterance ids still include old speaker ids as prefix and this in return fails `validate_data_dir.sh` since new speaker ids (recording ids) are not prefix of utterance ids. 

Kaldi 5.4

**Comment by vimalmanohar** [comment]
This script expects the recording-id to be the speaker as mentioned in https://github.com/kaldi-asr/kaldi/blob/19dc26ff833cbaedb5a2ffd2609d7cd8d0a8e6a5/egs/wsj/s5/steps/segmentation/prepare_targets_gmm.sh#L69. We might need a different script for the case where it is not the case. I believe it uses the CMVN stats computed from the one with segments for the data directory that is unsegmented.

**Comment by vimalmanohar** [comment]
There is an option --no-spk-sort in validate_data_dir.sh. Can you check if the issue is solved if using that option? In that case, I can just modify the script to use that option.
