### ISSUE TITLE
--use-gpu=wait

### ISSUE THREAD

**Issue by danpovey** [kaldi-asr/kaldi#2271]
I think it would be useful for the nnet3 and chain training scripts to support passing in the option --use-gpu=wait to programs like nnet3-chain-train which can use a GPU.  That way people without GridEngine can more easily train when num-jobs > their number of GPUs.
It should be possible to do this by changing the use-gpu option to be string valued, with mapping true -> yes and false -> no, and also allowing yes, no and wait.

@hhadian, do you have time for this?

**Comment by kkm000** [comment]
This is done long ago.
