### ISSUE TITLE
convert_data_dir_to_whole.sh doesn't produce the right text file

### ISSUE THREAD

**Issue by olix20** [kaldi-asr/kaldi#2275]
background: i have a valid kaldi directory but `text` file is quite unclean (movie subtitles with off timings). I use `convert_data_dir_to_whole.sh` to get full recording length segments and then feed it into `segment_long_utterances.sh`. 

`convert_data_dir_to_whole.sh` seem to be converting everything right except `text` file. Expectation is that the new `text` file contains a concatenation of all texts for all segments of each recording, but it generates something like: 

`<recording_id> <text_for_first_segment_of_the_recording> [a long list of semgnet ids]`

**Comment by vimalmanohar** [comment]
Fixed https://github.com/kaldi-asr/kaldi/pull/2277
