### ISSUE TITLE
kaldi-thread-test failed.

### ISSUE THREAD

**Issue by JiayiFu** [kaldi-asr/kaldi#2280]
I git clone the master branch of kaldi and install it successfully.
But when I get into the 'kaldi/src' directory and 'make test', the unit test failed when running 'kaldi-thread-test':

> Running kaldi-thread-test .../bin/bash: line 1: 30597 Aborted                 ./$x > $x.testlog 2>&1
>  0s... FAIL kaldi-thread-test

I tried to find the reason in log but there is only less information in the log file:

> terminate called after throwing an instance of 'std::system_error'
>   what():  Resource temporarily unavailable

My OS is Ubuntu 16.04 and the kernel version is 4.4.0-116-generic.
My gcc version is 5.4.0 and cuda version is 9.0.

I have no idea about the problem.
Can someone tell me how to solve this problem ? 
thx!

**Comment by danpovey** [comment]
You can probably just ignore it.  If it happens to others we may change the test, but this may be due to peculiarities in how your system was set up.
