### ISSUE TITLE
Question about Speaker Recognition and sre10

### ISSUE THREAD

**Issue by YongyuG** [kaldi-asr/kaldi#2281]
Hi,could you please tell me how to format the Timit dataset that can be runned in sre10/v1/run.sh, 

Due to lack of dataset, I am trying to run the script in sre10 on Timit; however, there are few question I am confusing. In the sre10/v1/run.sh,  I don't know what SWBD2 phase and SBWD Cellular stands for?
Moreover, I really dont know the format of train and test data, which used make_sre.sh to transform to  data/sre10_train and data/sre10_test.

**Comment by YongyuG** [comment]
One more question, why the speaker recognition example in Kaldi always trains diagonal UBM first and then full UBM, why not just train full UBM directly?

**Comment by david-ryan-snyder** [comment]
Hi @YongyuG,

It's better to ask questions like this on the Kaldi help forums: https://groups.google.com/forum/#!forum/kaldi-help. We usually use the GitHub issues for bugs or features. 

On Kaldi-help, be sure to search for similar messages, to see if your question is already answered. For example, there was a discussion about using TIMIT for speaker recognition that might be helpful for you:

https://groups.google.com/forum/#!searchin/kaldi-help/timit$20speaker$20recognition%7Csort:date/kaldi-help/mprIXxOQxSY/zt20ej7-BAAJ

> In the sre10/v1/run.sh, I don't know what SWBD2 phase and SBWD Cellular stands for?

The README.txt file gives you the LDC Catalog numbers for the typical datasets: https://github.com/kaldi-asr/kaldi/blob/master/egs/sre10/v1/README.txt . For example: https://catalog.ldc.upenn.edu/LDC2001S13. 

> why not just train diagonal UBM directly

Some people in the speaker recognition community use diagonal UBMs, others use full covariance UBMs. The latter are more flexible. The i-vector code requires full covariance UBMs, so you're stuck with them unless you want to modify the C++ code. But there's not reason I can think of to worry about it. 

> or full UBM directly?

I _think_ it's to reduce training time. The diagonal UBM should faster to train.

Best,
David

**Comment by david-ryan-snyder** [comment]
@danpovey, you should be able to close this issue. @YongyuG can follow up on Kaldi-help if he has more questions.

**Comment by Firew-T** [comment]
hi @all, pleas is it possible to use sre10, for speaker identification task?
