### ISSUE TITLE
egs/ptb training

### ISSUE THREAD

**Issue by XiangZhu0718** [kaldi-asr/kaldi#2282]
always show 'Training neural net(pass 0)'
no gpu running ?
anything wrong?

**Comment by danpovey** [comment]
Maybe it's very slow because you didn't compile for GPU, e.g. when you
configured Kaldi, 'nvcc' was not on the path.  @hainan-xv, please check
that 'cuda-gpu-available' returns zero status in the RNNLM training
scripts, and at least warn if not.

**Comment by XiangZhu0718** [comment]
in the configured kaldi,the nvcc is on the path..
we can just wait ?

**Comment by XiangZhu0718** [comment]
i modify the 'queue.pl' to 'run.pl' in the cmd.sh, anyelse shall i modify in the script?

**Comment by icestoneking** [comment]
How is this problem solved？@XiangZhu0718
