### ISSUE TITLE
rnnlm net structure

### ISSUE THREAD

**Issue by XiangZhu0718** [kaldi-asr/kaldi#2283]
where can i find info about rnnlm net structure?

**Comment by keli78** [comment]
I assume you have found the configs of rnnlm net architecture in script xxx/local/rnnlm/tuning/xxx.sh. For example for swbd, it's here: local/rnnlm/tuning/run_tdnn_lstm_1e.sh
For specific info about each layer (relu-renorm-layer, fast-lstmp-layer etc.) , you can check the python scripts here: steps/libs/nnet3/xconfig/{lstm.py, basic_layers.py, ...}

**Comment by hainan-xv** [comment]
If you search the word "xconfig" in the file swbd/s5c/local/rnnlm/tuning/run_tdnn_lstm_1a.sh you will see the network structure.
