### ISSUE TITLE
anything wrong with the function GetSplitTargets in gmm/model-common.cc

### ISSUE THREAD

**Issue by tratotasia** [kaldi-asr/kaldi#2287]
in line 140 and 141.
BaseFloat orig_occ = state_occs(state_to_split.pdf_index);
if ((state_to_split.num_components+1) * min_count >= orig_occ) 

why use the orig_occ instead of state_to_split.occupancy, since state_to_split.occupancy is specially computed  as it does in line 125 
BaseFloat occ = pow(state_occs(pdf_index), power);

it make no sence to initialize the state_to_split.occupancy if we use orig_occ.

therefore, i think maybe it's a bug.

**Comment by danpovey** [comment]
thanks, but it's not a bug.. the min_count should be interepreted as a real count, not one taken to a power.
