### ISSUE TITLE
question about perterb_speed_to_allowed_lengths.py

### ISSUE THREAD

**Issue by calderma** [kaldi-asr/kaldi#2305]
between lines 115 and 118 of the file, it has:

if len(utterances) / len(wav_scp) < 0.5:
        logger.info("More than half your data is problematic. Try "
                    "fixing using fix_data_dir.sh.")
        sys.exit(1)

shouldn't both of the lengths be floats? Otherwise it's always going to exit if even one file is problematic.

**Comment by hhadian** [comment]
It's OK in python3 (it won't be zero when len(utterances) / len(wav_scp)) but now I noticed that the script is not using python3. I'll fix it.
