### ISSUE TITLE
--num-jobs-multiple option

### ISSUE THREAD

**Issue by danpovey** [kaldi-asr/kaldi#2309]
@hhadian, would you mind doing this when you have time (not urgent)?
It's a change which should make it more efficient to use machines with several GPUs when using run.pl.  It's to add an option '--num-jobs-multiple' to the nnet training, with default value 1, whose effect will be to round up the number of jobs used to an integer multiple of the --num-jobs-multiple value.  We can add as a requirement that both --num-jobs-initial and --num-jobs-final must be >= --num-jobs-multiple.  (This is just to make setups easier to interpret, since the effective number of jobs at any time will always be >= --num-jobs-multiple).

This option will be mostly intended to be used in conjunction with the --use-gpu=wait option, on setups without GridEngine, to avoid situations where some of the GPUs are idle.

**Comment by hhadian** [comment]
Yes, I'll do it.

**Comment by kkm000** [comment]
I recall I implemented that.
