### ISSUE TITLE
mutil-gpus on a single machine

### ISSUE THREAD

**Issue by XiangZhu0718** [kaldi-asr/kaldi#2319]
can now run swbd/s5c/local/rnnlm/turing/run_tdnn_lstm_1e.sh with mutil-gpu on a single machine without gridEngine ? thank you.

**Comment by danpovey** [comment]
The '--use-gpu=wait' option has not been implemented in the RNNLM scripts.
 It would require changes to rnnlm/train_rnnlm.sh.  However, that example
script uses '--num-jobs-final 3', so it would work fine as long as the
machine had 3 or more GPUs.
