### ISSUE TITLE
`nj` in `get_frame_shift.sh`

### ISSUE THREAD

**Issue by olix20** [kaldi-asr/kaldi#2320]
I'm doing SAD with `detect_speech_activity.sh` and *one* single audio file. 
In the process, the directory containing that single file is converted to whole with one speaker. 

The problem is when `get_utt2dur.sh` is called by `get_frame_shift.sh` without passing `nj`, so 4 is used by default which is too many and i get `You are splitting into too many pieces! [reduce $nj] at utils/split_scp.pl line 209, <I> line 1.`

Does it make sense to add `nj` option to `get_frame_shift.sh` or is there another workaround?

**Comment by danpovey** [comment]
I think the best solution is for get_utt2dur.sh to check the number of utterances and if it's less than nj, set nj to that number.  (Only in the branch where it actually uses $nj).  Can you make a PR for this?

**Comment by olix20** [comment]
sure i can make a PR; but that means max `nj` will always be 4 in `get_utt2dur.sh` no matter what parent scripts are using. is that intended?

i currently reduce num jobs in parent scripts if `nj > num utterances`

**Comment by danpovey** [comment]
This is a corner case and I don't like adding the $nj option to all of those types of scripts.
See if this PR resolves it.

https://github.com/kaldi-asr/kaldi/pull/2326

**Comment by olix20** [comment]
Yes it solves the problem, thanks.

**Comment by weienzhang** [comment]
may i ask how can i adjust the nj , in the run.sh or just add some command in command line ?

**Comment by rushabhdharia** [comment]
@weienzhang You can adjust nj in the get_utt2dur.sh file
