### ISSUE TITLE
fstaddselfloops   ERROR: VectorFst::Read: read failed: <unspecified>

### ISSUE THREAD

**Issue by mjc14** [kaldi-asr/kaldi#2342]
i  have a question  about   fstaddselfloops .  my command is 

 tools/make_lexicon_fst.pl --pron-probs $tmpdir/lexiconp_disambig.txt 0 "sil" '#'$ndisambig | fstcompile --isymbols=$dir/tokens.txt --osymbols=$dir/words.txt  --keep_isymbols=false --keep_osymbols=false |   fstaddselfloops  "echo $token_disambig_symbol |" "echo $word_disambig_symbol |" |  fstarcsort --sort_type=olabel > $dir/L.fst || exit 1;

Following error occurs when I use fstaddselfloops  : 

 21  : ERROR: VectorFst::Read: read failed: <unspecified>
ERROR      2018-04-08 13:41:21,937 common.common                  read_from_stream                     21  : ERROR: FstHeader::Read: Bad FST header: -
ERROR      2018-04-08 13:41:21,938 common.common                  read_from_stream                     21  : ERROR (fstaddselfloops:ReadFstKaldi():kaldi-fst-io.cc:35) Reading FST: error reading FST header from standard input
ERROR      2018-04-08 13:41:21,938 common.common                  read_from_stream                     21  : ERROR (fstaddselfloops:ReadFstKaldi():kaldi-fst-io.cc:35) Reading FST: error reading FST header from standard input
ERROR      2018-04-08 13:41:21,938 common.common                  read_from_stream                     21  :
ERROR      2018-04-08 13:41:21,939 common.common                  read_from_stream                     21  : [stack trace: ]
ERROR      2018-04-08 13:41:21,939 common.common                  read_from_stream                     21  : kaldi::KaldiGetStackTrace()
ERROR      2018-04-08 13:41:21,939 common.common                  read_from_stream                     21  : kaldi::KaldiErrorMessage::~KaldiErrorMessage()
ERROR      2018-04-08 13:41:21,939 common.common                  read_from_stream                     21  : fst::ReadFstKaldi(std::string)
ERROR      2018-04-08 13:41:21,940 common.common                  read_from_stream                     21  : fstaddselfloops(main+0x14d) [0x4411ad]
ERROR      2018-04-08 13:41:21,940 common.common                  read_from_stream                     21  : /lib64/libc.so.6(__libc_start_main+0xf5) [0x7fef6593ac05]
ERROR      2018-04-08 13:41:21,940 common.common                  read_from_stream                     21  : fstaddselfloops() [0x440f99]
ERROR      2018-04-08 13:41:21,940 common.common                  read_from_stream                     21  :
ERROR      2018-04-08 13:41:21,957 common.common                  read_from_stream                     21  : ERROR (fstaddselfloops:ReadFstKaldi():kaldi-fst-io.cc:40) Could not read fst from standard input
ERROR      2018-04-08 13:41:21,958 common.common                  read_from_stream                     21  : ERROR (fstaddselfloops:ReadFstKaldi():kaldi-fst-io.cc:40) Could not read fst from standard input

**Comment by danpovey** [comment]
That would usually be because there was a failure in the previous element of the pipe-- fstcompile in this case.  But your errors look very strange, I have never seen stuff that looks like this:
  ```ERROR 2018-04-08 13:41:21,940 common.common read_from_stream 21```
So I suspect you  are trying to run it in some strange OS or framework.

**Comment by mjc14** [comment]
i run it in docker and i use python multi processing  to process multi task.

**Comment by danpovey** [comment]
OK, well it's hard to diagnoze what's going on from that output-- it could be out-of-memory or it could be some issue with the frameworks you are using.  Most likely that error you showed was not the first error.  My suggestion is to cut down on the frameworks-- likely the errors are a result of one of the frameworks you are using, and if you don't know how to debug them, then best not to use them at all.
