### ISSUE TITLE
How questions config is geted in Kaldi when building decision tree

### ISSUE THREAD

**Issue by yangxiaokang** [kaldi-asr/kaldi#2344]
when i read http://www.kaldi-asr.org/doc/tree_externals.html, I find this: 
the questions configuration class would be output by the compile-questions program, which takes in a topology list of phonetic questions (in our scripts, these are automatically obtained from tree-building statistics by the program cluster-phones.
It's difficult for me to understand how the phonetic questions are automatically obtained.

**Comment by jtrmal** [comment]
I don't remember precisely, but they are generated from an agglomerative clustering tree where every slice through the tree forms a question. This is not a good place to ask questions like that -- use kaldi-help for that purpose
