### ISSUE TITLE
install hangs on "checking for ANSI C header files... yes"

### ISSUE THREAD

**Issue by saeedbinhamad** [kaldi-asr/kaldi#2360]
Dear Kaldi people,

Im new to kaldi 

Install hangs on **Windows 10 Linux Subsystem** (Ubuntu Xenial)

`
sbh@DESKTOP-0HJPMSI:~/kaldi/tools$ ./extras/check_dependencies.sh
./extras/check_dependencies.sh: all OK.
sbh@DESKTOP-0HJPMSI:~/kaldi/tools$ nproc
8
sbh@DESKTOP-0HJPMSI:~/kaldi/tools$ make -j 8
extras/check_dependencies.sh
extras/check_dependencies.sh: all OK.
tar xojf sctk-2.4.10-20151007-1312Z.tar.bz2 || \
      tar --exclude '*NONE*html' -xvojf sctk-2.4.10-20151007-1312Z.tar.bz2
cd openfst-1.6.5/ && \
./configure --prefix=`pwd` --enable-static --enable-shared --enable-far --enable-ngram-fsts CXX="g++" CXXFLAGS=" " LDFLAGS="" LIBS="-ldl"
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... rm -rf sctk && ln -s sctk-2.4.10 sctk
cd sctk; make config
make[1]: Entering directory '/home/sbh/kaldi/tools/sctk-2.4.10'
(mkdir -p bin)
(cd src; make config)
make[2]: Entering directory '/home/sbh/kaldi/tools/sctk-2.4.10/src'
(cd asclite; make config)
make[3]: Entering directory '/home/sbh/kaldi/tools/sctk-2.4.10/src/asclite'
(cd core; sh config.sh -prefix=`cd ../../..; pwd`)
checking for g++... g++
checking for C++ compiler default output file name... a.out
checking whether the C++ compiler works... yes
checking whether we are cross compiling... no
checking for suffix of executables...
checking for suffix of object files... o
checking whether we are using the GNU C++ compiler... yes
checking whether g++ accepts -g... yes
checking whether make sets $(MAKE)... yes
checking for gcc... gcc
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ANSI C... none needed
checking for main in -lm... yes
checking how to run the C preprocessor... gcc -E
checking for egrep... grep -E
checking for ANSI C header files... yes
`

I have tried installing latest gcc and clang compilers from source as well to see if it works but no luck.

It always hangs here for DAYS! 

any idea?

**Comment by danpovey** [comment]
I think this is one of those moments that calls for the following cartoon:
http://dilbert.com/strip/1995-06-24

**Comment by danpovey** [comment]
sent too soon..
this will be hard for us to debug remotely. It's likely a Windows issue.
Someone with more linux command line experience could probably  figure out what is hanging, but I don't have time fo figure it out remotely-- try to find someone local who is more experience.
