### ISSUE TITLE
fstminimizeencoded error 

### ISSUE THREAD

**Issue by mjc14** [kaldi-asr/kaldi#2363]
we train  a lm, it only has  ngram 1 ,such as  
\data\
ngram 1=1223
ngram 2=0
ngram 3=0

then we use these comands 
fstisstochastic tmp/G.fst
fsttablecompose tmp/L.fst tmp/G.fst  > tmp/LG.co.fst
fstdeterminizestar --use-log=true   tmp/LG.co.fst  tmp/LG.det.fst
fstminimizeencoded   tmp/LG.det.fst  tmp/LG.min.fst
fstarcsort --sort_type=ilabel   tmp/LG.min.fst   tmp/LG.fst

log:
fstisstochastic tmp/G.fst
6.66432e-05 0

fstprint  tmp/LG.co.fst  |head
0	1	122	0
1	2	26	1	11.751461
1	3	26	2	11.751461
1	4	26	3	11.751461
1	5	81	3	11.751461
1	6	26	4	11.751461
1	7	81	4	11.751461
1	8	26	5	11.751461
1	9	117	5	11.751461
1	10	26	6	11.751461

fstprint  tmp/LG.det.fst  |head
0	1	122	0
1	2	2	0	4.63344526
1	3	3	0	9.26655388
1	4	4	0	9.672019
1	5	5	0	7.01526165
1	6	6	36970	11.751461
1	7	7	0	5.32174301
1	8	8	0	8.70693779
1	9	9	0	9.26655388
1	10	10	0	6.1642127

fstprint  tmp/LG.min.fst  |head
**22381	0	122	0**
0	1	2	0	4.63378906
0	2	3	0	9.26660156
0	3	4	0	9.671875
0	4	5	0	7.015625
0	22381	6	36970	11.7509766
0	5	7	0	5.32128906
0	6	8	0	8.70703125
0	7	9	0	9.26660156
0	8	10	0	6.1640625

we find some err in  LG.min.fst , the  fst order is wrong, the first line is 22381	0    122 0  .

**Comment by danpovey** [comment]
That is not an error.  The first listed state of an FST is its start state and it does not have be state 0 (although it usually is).  See openfst.org for more info.
