### ISSUE TITLE
the difference of ac_cost in method ProcessEmitting between LatticeFasterDecoder and FasterDecoder

### ISSUE THREAD

**Issue by tratotasia** [kaldi-asr/kaldi#2364]
in the process of FasterDecoder::ProcessEmitting , we caculate the ac_cost for Token when we find a not zero ilabel like this:
if (arc.ilabel != 0) {  // propagate..
          BaseFloat ac_cost =  - decodable->LogLikelihood(frame, arc.ilabel);
          double new_weight = arc.weight.Value() + tok->cost_ + ac_cost;
it's easy to understand that how the new_weight is calculated.

But when in the process of LatticeFasterDecoder::ProcessEmitting, we got a cost_offset from the best_elem's Token value,  and use it for next_cutoff and ac_cost when ilabel is not 0. 
like this:

/// get the next_cutoff. 
```
 if (best_elem) {
    StateId state = best_elem->key;
    Token *tok = best_elem->val;
    cost_offset = - tok->tot_cost;
    for (fst::ArcIterator<fst::Fst<Arc> > aiter(fst_, state);
         !aiter.Done();
         aiter.Next()) {
      Arc arc = aiter.Value();
      if (arc.ilabel != 0) {  // propagate..
        arc.weight = Times(arc.weight,
                           Weight(cost_offset -
                                  decodable->LogLikelihood(frame, arc.ilabel)));
        BaseFloat new_weight = arc.weight.Value() + tok->tot_cost;
        if (new_weight + adaptive_beam < next_cutoff)
          next_cutoff = new_weight + adaptive_beam;
      }
    }
  }
```

/// calculate a new cost.
```
 if (arc.ilabel != 0) {  // propagate..
          BaseFloat ac_cost = cost_offset -
              decodable->LogLikelihood(frame, arc.ilabel),
              graph_cost = arc.weight.Value(),
              cur_cost = tok->tot_cost,
              tot_cost = cur_cost + ac_cost + graph_cost;
```

My question is why using an extra cost_offset here instead of calculating the same variable like next_cutoff /next_weight_cutoff and tot_cost/new_weight in FasterDecoder::ProcessEmitting. It seems there is no difference to remove cost_offset here since that cost_offset will be minus again in LatticeFasterDecoder::GetRawLattice.

Maybe the only reason to use the cost_offset here is to avoid overflow, right???

Thanks & Regards

**Comment by danpovey** [comment]
It's about reducing round-off error in floating point operations.
