### ISSUE TITLE
IAM：run train_lm.sh get error of wellington.txt.txt

### ISSUE THREAD

**Issue by af258963** [kaldi-asr/kaldi#2365]
the error :    data/local/local_lm/data/text/wellington.txt.txt: No such file or directory

then I find  line 85 of  train_lm.sh  may fix as :
cat ${dir}/data/text/{iam,lob,brown,wellington}.txt | tr '[:space:]' '[\n*]' | grep -v "^\s*$" | sort | uniq -c | sort -bnr > ${dir}/data/word_count
  head -n $vocab_size ${dir}/data/word_count | awk '{print $2}' > ${dir}/data/wordlist

**Comment by af258963** [comment]
when I fixed the .txt.txt  then,it get the error:
validate_text_dir.py: Input file data/local/local_lm/data/text/wellington.txt doesn't look right.

**Comment by hhadian** [comment]
That error is because the Wellington corpus is not publicly available and
the scripts can't download it. Hopefully we'll prepare a fix today (to make
that corpus optional).
-Hossein

**Comment by af258963** [comment]
@hhadian thks，I got it.

**Comment by hhadian** [comment]
@af258963, you can use the fix in #2370 if you haven't already fixed the issues.
