### ISSUE TITLE
Did anyone compile it completely?

### ISSUE THREAD

**Issue by verydemo** [kaldi-asr/kaldi#2366]
Did anyone compile it completely?

I tried, a lot of errors.

**Comment by jtrmal** [comment]
yes, thousands of people. Read the readme first. Read the howto here: http://kaldi-asr.org/doc/install.html
Read carefully this http://www.catb.org/esr/faqs/smart-questions.html
Sign up to kaldi-help list (this place is not good for asking questions)
Resolve your issues.
