### ISSUE TITLE
Bug with the xconfig_to_configs

### ISSUE THREAD

**Issue by maelp** [kaldi-asr/kaldi#2367]
This is not recommended to use initializers with mutable objects https://github.com/kaldi-asr/kaldi/blob/82686ee6b109a219053feb731710670e93a01c0a/egs/wsj/s5/steps/libs/nnet3/xconfig/parser.py#L146

in this case the array is kept between multiple calls, so calling the method to parse a `.xconfig` twice might result in errors such as "this layer has the same name as a previous layer"

**Comment by danpovey** [comment]
i am not a great python programmer, is there an easy fix?
can you submit one?

**Comment by maelp** [comment]
The fix would be

```
def read_xconfig_file(xconfig_filename, existing_layers=None):
    if existing_layers is None:
        existing_layers = []
```

**Comment by maelp** [comment]
In this case the empty array is correctly recreated each time the method is called, rather than shared between calls to the method

**Comment by danpovey** [comment]
@xiaohui-zhang please make PR, I'm at ICASSP.

**Comment by xiaohui-zhang** [comment]
sure

**Comment by maelp** [comment]
With a small grep on the codebase I see that there is at least a few more times this pattern has been used

```
nnet3/dot/nnet3_to_dot.py
373:def GroupConfigs(configs, node_prefixes = []):
391:def ParseConfigLines(lines, node_prefixes = [], component_attributes = None ):
```
