### ISSUE TITLE
Chain model in kaldi 

### ISSUE THREAD

**Issue by voidxb** [kaldi-asr/kaldi#2372]
Hi,I am using the Chain model in Kaldi to develop my android project,however ,it does not work now.It is heared that you updated kaldi before,was kaldi-android respository updated together?

**Comment by danpovey** [comment]
Deploying Kaldi on Android is something that only experienced developers should attempt--  not for the kind of person who would say it "doesn't work" with no further explanation.  Anyway there isn't such a thing as the kaldi-android repository.  There is are options in kaldi's configure script that can be used to compile for Android, and others (I think jcsilva) have provided documentation on how to do it.
