### ISSUE TITLE
Python installation packages are not suggested correctly in kaldi/tools/extras/check_dependencies

### ISSUE THREAD

**Issue by dbdean** [kaldi-asr/kaldi#2379]
In the check dependencies script, the shell function `add_packages` requires three parameters, one for redhat, one for debian, and one for suse:

https://github.com/kaldi-asr/kaldi/blob/4fda1b04a102d3d0182fdab1444e22069b6a45a3/tools/extras/check_dependencies.sh#L12-L16

However, the python checks only provide one package name, instead of three like all the other `add_package` calls:

https://github.com/kaldi-asr/kaldi/blob/4fda1b04a102d3d0182fdab1444e22069b6a45a3/tools/extras/check_dependencies.sh#L90-L101

As a result, if python2 or python3 are missing, they don't actually get added to the package installation list for debian or suse (only redhat), which results in an empty list of suggested installations on debian if only python2 and/or python3 are missing.

**Comment by dbdean** [comment]
Sorry about that, I've updated the issue to make it clearer what the problem is.

**Comment by danpovey** [comment]
oh, you're right.  Any chance you could make a PR for it?  If not I can find someone else or do it myself.

**Comment by dbdean** [comment]
I'd have to do some research for the package names for redhat and opensuse. I'll keep it in mind if I have some spare time, but if someone else has the information at hand and can do it, that would be great.

**Comment by unizhu** [comment]
On redhat system python3 is called python32,33,3X...
