### ISSUE TITLE
Running kaldi on Android

### ISSUE THREAD

**Issue by somil55** [kaldi-asr/kaldi#2400]
Is it possible to use trained models on the Android platform? If yes, can anyone point me to some relevant links

**Comment by danpovey** [comment]
It's possible but difficult.  Search for android compilation instructions
by jcsilva.
Kaldi is not really optimized for low-memory operation, which matters on
phones; and the amount of computation in any ASR is significant for a phone
(battery life, etc.).  It's only something I'd recommend once you have a
server-based solution running and if you have a compelling need for
on-device.

**Comment by somil55** [comment]
I only want to run decoding phase on android. Is there anyone in the community who has benchmarked Kaldi for performance on android?

**Comment by danpovey** [comment]
Yes, i imagined you only wanted to run decoding on android.
I am not aware of any benchmarks.
This is not something that someone without prior ASR experience should
attempt.
