### ISSUE TITLE
exp/tri4b/graph_phone is not created after the execution of thchs-30 run.sh

### ISSUE THREAD

**Issue by phoenixbai** [kaldi-asr/kaldi#2417]
I am trying to run thchs-30, and run.sh exit at below location with log:

> steps/nnet/decode.sh --cmd run.pl --mem 4G --nj 8 --srcdir exp/tri4b_dnn_mpe exp/tri4b/graph_phone data/dae/test/0db/car_phone exp/tri4b_dnn_mpe/decode_phone_0db/car
steps/nnet/decode.sh: missing file exp/tri4b/graph_phone/HCLG.fst
local/score.sh --min-lmwt 4 --max-lmwt 15 --cmd run.pl --mem 4G data/dae/test/0db/cafe exp/tri4b/graph_word exp/tri4b_dnn_dae/decode_word_0db/cafe
local/score.sh: scoring with word insertion penalty=0.0,0.5,1.0
steps/nnet/decode.sh --cmd run.pl --mem 4G --nj 8 --srcdir exp/tri4b_dnn_mpe exp/tri4b/graph_phone data/dae/test/0db/cafe_phone exp/tri4b_dnn_mpe/decode_phone_0db/cafe
steps/nnet/decode.sh: missing file exp/tri4b/graph_phone/HCLG.fst
local/score.sh --min-lmwt 4 --max-lmwt 15 --cmd run.pl --mem 4G data/dae/test/0db/white exp/tri4b/graph_word exp/tri4b_dnn_dae/decode_word_0db/white
local/score.sh: scoring with word insertion penalty=0.0,0.5,1.0
steps/nnet/decode.sh --cmd run.pl --mem 4G --nj 8 --srcdir exp/tri4b_dnn_mpe exp/tri4b/graph_phone data/dae/test/0db/white_phone exp/tri4b_dnn_mpe/decode_phone_0db/white
steps/nnet/decode.sh: **missing file exp/tri4b/graph_phone/HCLG.fst**

According to log, it seems that the below line in bold is not executed? **graph_phone**  directory is missing, but **graph_word** is created correctly.  so what could be the possible reason? I failed to find any error info in the log.

```
#quick
steps/train_quick.sh --cmd "$train_cmd" 4200 40000 data/mfcc/train data/lang exp/tri3b_ali exp/tri4b || exit 1;
#test tri4b model
**local/thchs-30_decode.sh --nj $n "steps/decode_fmllr.sh" exp/tri4b data/mfcc &**

#quick_ali
steps/align_fmllr.sh --nj $n --cmd "$train_cmd" data/mfcc/train data/lang exp/tri4b exp/tri4b_ali || exit 1;
```

run log is attached.
[run_20180512.log](https://github.com/kaldi-asr/kaldi/files/1998347/run_20180512.log)

please help!

**Comment by danpovey** [comment]
I suspect what happened is you edited that script (local/thchs-30_decode.sh) while it was running.  bash reads files line by line, so you have to be careful about editing them while they run.

**Comment by phoenixbai** [comment]
@danpovey I am sure I didnot do that. But just in case, I will rerun to see if it is possible to reproduce it. 
thank you!
