### ISSUE TITLE
Online2 decode error

### ISSUE THREAD

**Issue by JunyuWei** [kaldi-asr/kaldi#2419]
I met some cases that when I am talking，chain model decodes right. But when I stop, it changed the result wrong(e.g. delete some words before).I wonder how to improve this. Any advice is thankful.

**Comment by danpovey** [comment]
If that happens frequently or consistently, or with a certain type of error
pattern, it's interesting.
It might be about the language model probability of end-of-sentence--
possibly the final word in what you said had a low end-of-sentence
probability and once you finalize the utterance, that gets taken into
account.

Dan

**Comment by JunyuWei** [comment]
@danpovey Thank you for the respoding. Actually the error happens frequently,especially at the begining and at the end of the sentences. It should be about the  language model, because it happened since i changed lmwt to 8. I will continue keep an eye on it, Temporarily, I shut off the final decoding to get the result right.

**Comment by JunyuWei** [comment]
But  during deocding and scoring, I found the lowest wer occured when lmwt was 8.

**Comment by danpovey** [comment]
probably you have very limited data and you are mostly looking at noise.
