### ISSUE TITLE
run ivector-extractor-sum-accs crash in aishell

### ISSUE THREAD

**Issue by liangyanfeng** [kaldi-asr/kaldi#2427]
ivector-extractor-sum-accs --parallel=false "ivector-extractor-acc-stats --num-threads=4 --num-samples-for-weights=3 exp/extractor_1024/0.ie 'ark,s,cs:add-deltas --delta-window=3 --delta-order=2 scp:data/train/split40/1/feats.scp ark:- | apply-cmvn-sliding --norm-vars=false --center=true --cmn-window=300 ark:- ark:- | select-voiced-frames ark:- scp,s,cs:data/train/split40/1/vad.scp ark:- |' 'ark,s,cs:gunzip -c exp/extractor_1024/post.1.gz|' -|" "ivector-extractor-acc-stats --num-threads=4 --num-samples-for-weights=3 exp/extractor_1024/0.ie 'ark,s,cs:add-deltas --delta-window=3 --delta-order=2 scp:data/train/split40/2/feats.scp ark:- | apply-cmvn-sliding --norm-vars=false --center=true --cmn-window=300 ark:- ark:- | select-voiced-frames ark:- scp,s,cs:data/train/split40/2/vad.scp ark:- |' 'ark,s,cs:gunzip -c exp/extractor_1024/post.2.gz|' -|" "ivector-extractor-acc-stats --num-threads=4 --num-samples-for-weights=3 exp/extractor_1024/0.ie 'ark,s,cs:add-deltas --delta-window=3 --delta-order=2 scp:data/train/split40/3/feats.scp ark:- | apply-cmvn-sliding --norm-vars=false --center=true --cmn-window=300 ark:- ark:- | select-voiced-frames ark:- scp,s,cs:data/train/split40/3/vad.scp ark:- |' 'ark,s,cs:gunzip -c exp/extractor_1024/post.3.gz|' -|" "ivector-extractor-acc-stats --num-threads=4 --num-samples-for-weights=3 exp/extractor_1024/0.ie 'ark,s,cs:add-deltas --delta-window=3 --delta-order=2 scp:data/train/split40/4/feats.scp ark:- | apply-cmvn-sliding --norm-vars=false --center=true --cmn-window=300 ark:- ark:- | select-voiced-frames ark:- scp,s,cs:data/train/split40/4/vad.scp ark:- |' 'ark,s,cs:gunzip -c exp/extractor_1024/post.4.gz|' -|" exp/extractor_1024/acc.0.1 
LOG (ivector-extractor-sum-accs[5.4.132~3-f8b67]:main():ivector-extractor-sum-accs.cc:71) Reading stats from ivector-extractor-acc-stats --num-threads=4 --num-samples-for-weights=3 exp/extractor_1024/0.ie 'ark,s,cs:add-deltas --delta-window=3 --delta-order=2 scp:data/train/split40/1/feats.scp ark:- | apply-cmvn-sliding --norm-vars=false --center=true --cmn-window=300 ark:- ark:- | select-voiced-frames ark:- scp,s,cs:data/train/split40/1/vad.scp ark:- |' 'ark,s,cs:gunzip -c exp/extractor_1024/post.1.gz|' -|
ivector-extractor-acc-stats --num-threads=4 --num-samples-for-weights=3 exp/extractor_1024/0.ie 'ark,s,cs:add-deltas --delta-window=3 --delta-order=2 scp:data/train/split40/1/feats.scp ark:- | apply-cmvn-sliding --norm-vars=false --center=true --cmn-window=300 ark:- ark:- | select-voiced-frames ark:- scp,s,cs:data/train/split40/1/vad.scp ark:- |' 'ark,s,cs:gunzip -c exp/extractor_1024/post.1.gz|' - 
add-deltas --delta-window=3 --delta-order=2 scp:data/train/split40/1/feats.scp ark:- 
select-voiced-frames ark:- scp,s,cs:data/train/split40/1/vad.scp ark:- 
apply-cmvn-sliding --norm-vars=false --center=true --cmn-window=300 ark:- ark:- 
LOG (ivector-extractor-acc-stats[5.4.132~3-f8b67]:ComputeDerivedVars():ivector-extractor.cc:183) Computing derived variables for iVector extractor
LOG (ivector-extractor-acc-stats[5.4.132~3-f8b67]:ComputeDerivedVars():ivector-extractor.cc:204) Done.
ERROR (ivector-extractor-sum-accs[5.4.132~3-f8b67]:ExpectToken():io-funcs.cc:203) Failed to read token [started at file position -1], expected <IvectorExtractorStats>

[ Stack-Trace: ]

kaldi::MessageLogger::HandleMessage(kaldi::LogMessageEnvelope const&, char const*)
kaldi::MessageLogger::~MessageLogger()
kaldi::ExpectToken(std::istream&, bool, char const*)
kaldi::IvectorExtractorStats::Read(std::istream&, bool, bool)
main
__libc_start_main
ivector-extractor-sum-accs() [0x40b6a9]

WARNING (ivector-extractor-sum-accs[5.4.132~3-f8b67]:Close():kaldi-io.cc:515) Pipe ivector-extractor-acc-stats --num-threads=4 --num-samples-for-weights=3 exp/extractor_1024/0.ie 'ark,s,cs:add-deltas --delta-window=3 --delta-order=2 scp:data/train/split40/1/feats.scp ark:- | apply-cmvn-sliding --norm-vars=false --center=true --cmn-window=300 ark:- ark:- | select-voiced-frames ark:- scp,s,cs:data/train/split40/1/vad.scp ark:- |' 'ark,s,cs:gunzip -c exp/extractor_1024/post.1.gz|' -| had nonzero return status 9

# Accounting: time=3 threads=1
# Ended (code 255) at Fri May 18 02:41:33 UTC 2018, elapsed time 3 seconds

I don't know where there is a problem. Is anyone else having this problem?

**Comment by danpovey** [comment]
You'll normally get those kinds of problems if you don't have enough memory.
you can use a machine with more memory or increase the num-jobs.
see kaldi-asr.org/forums.html for how to ask questions.  you could have found that using a simple web search.
