### ISSUE TITLE
Can kaldi score by PER (phoneme error rate) , instead of WER(word error rate) ?

### ISSUE THREAD

**Issue by linzehua** [kaldi-asr/kaldi#2428]
I am runing the 'timit' egs, by the result return its WER by default. I have not found how to get PER in document. Is there anybody know? How to setup for PER ? Thank you

**Comment by linzehua** [comment]
I am runing kaldi in ubuntu

**Comment by danpovey** [comment]
WER is  just what it prints, it's actually PER in the TIMIT case because the transcripts are at the phone level.  You probably could have found this out from a web search.
See kaldi-asr.org/forums.html for how to ask questions.
