### ISSUE TITLE
lattice-lmrescore-kaldi-rnnlm-pruned, Error: "Possibly not all states of input lattice are co-accessible?"

### ISSUE THREAD

**Issue by vesis84** [kaldi-asr/kaldi#2448]
Hi Hainan, Dan,
the problem with 'lattice-lmrescore-kaldi-rnnlm-pruned' is still there, even after re-building the GMM model/lattices, and when using nnet3-rnnlm:

`ASSERTION_FAILED (lattice-lmrescore-kaldi-rnnlm-pruned[5.4.107-f0333]:ComputeLatticeStateInfo():compose-lattice-pruned.cc:585) : '!arc_costs.empty() && "Possibly not all states of input lattice are co-accessible?"'`

I looked into the lattice generation command, and the `'steps/decode_fmllr.sh'`
generates lattices using options: `'--determinize-lattice=false --allow-partial=true'`.

So, there are 3 ways to fix it, and I am not sure, which one is the best:
A) enable determinization/minimization in the 'steps/decode_fmllr.sh',
B) add determinization/minimization into the RNNLM re-scoring scripts
(for example into the 'rnnlm/lmrescore_pruned.sh')
C) add determinization/minimization into the re-scoring binary: 'lattice-lmrescore-kaldi-rnnlm-pruned'

To me "C" seems best, as it imposes no assumption on the input lattices, and all changes would be done in one place. What would you suggest?

I can change the code, or you (Hainan/Dan) can do it as well,
please let me know what you prefer...

Thanks,
Karel

**Comment by vesis84** [comment]
(after discussing it by email w/o github...)

Hi all,
aha, I see. I tried adding the 'fst::Connect(&clat)' to lattice rescoring tool, and it fixed the problem.

The lattices were generated with 'steps/decode_fmllr.sh', I did not modify anything.
According to the script, the last tool called was: lattice-determinize-pruned-parallel
(and I used the current HEAD from the kaldi-asr/master on github)

Should I open a PR, in which the 'fst::Connect(&clat)' is added to all the RNNLM lattice re-scoring tools?

Thanks,
Karel

**Comment by vesis84** [comment]
And the lattice, which is causing the trouble is far from empty:

```
-rw-r--r--  1 iveselyk fit  620622 May 25 16:14 ...0014251_0015030.lat
-rw-r--r--  1 iveselyk fit  620442 May 25 16:27 ...0014251_0015030.lat.connect
```

And the diff is:

```
$ diff ...0014251_0015030.lat.ascii ...0014251_0015030.lat.connect.ascii
715d714
< 110   506     562     6.38439,284.324,14748
1496,1499d1494
< 506   507     562     3.8296,359.522,
< 507   508     562     3.51459,214.632,
< 508   509     562     3.51459,226.856,
< 509   Infinity,Infinity,
```

The `Infinity,Infinity,` weight looks suspicious, but it might be normal for the partial paths?

**Comment by vesis84** [comment]
Aha, it seems we should add `fst::Connect(.)` into `lattice-determinize-pruned-parallel`.
In `lattice-determinize-pruned` it's already there, right after determinization and before the minimization...

Btw. is there a tool which calls just `fst::Connect(.)`, I added it as an option to `lattice-copy`,
but I am not sure if it is not already somewhere else...

K.

**Comment by danpovey** [comment]
I think we generally assume that programs will output things that are
already connected; that's why we don't have command line tools to do that.
Anyway it looks like the issue is fixed.

**Comment by vesis84** [comment]
Yes, the rnnlm rescoring is working well for me now.

In the same time, I came across another issue: the RNNLM training crashes 'randomly' with an error message:
```
ERROR (rnnlm-train[5.4.146~5-6b94e]:CopyFromSmat():cu-sparse-matrix.cc:395) cusparseStatus_t 6 : "CUSPARSE_STATUS_EXECUTION_FAILED" returned from 'cusparse_csr2csc(GetCusparseHandle(), smat.NumRows(), smat.NumCols(), smat.NumElements(), smat.CsrVal(), smat.CsrRowPtr(), smat.CsrColIdx(), CsrVal(), CsrColIdx(), CsrRowPtr(), CUSPARSE_ACTION_NUMERIC, CUSPARSE_INDEX_BASE_ZERO)'

[ Stack-Trace: ]

kaldi::MessageLogger::HandleMessage(kaldi::LogMessageEnvelope const&, char const*)
kaldi::MessageLogger::~MessageLogger()
kaldi::CuSparseMatrix<float>::CopyFromSmat(kaldi::CuSparseMatrix<float> const&, kaldi::MatrixTransposeType)
kaldi::rnnlm::RnnlmTrainer::RunBackgroundThread()
kaldi::rnnlm::RnnlmTrainer::run_background_thread(kaldi::rnnlm::RnnlmTrainer*)
void std::_Bind_simple<void (*(kaldi::rnnlm::RnnlmTrainer*))(kaldi::rnnlm::RnnlmTrainer*)>::_M_invoke<0ul>(std::_Index_tuple<0ul>)
std::_Bind_simple<void (*(kaldi::rnnlm::RnnlmTrainer*))(kaldi::rnnlm::RnnlmTrainer*)>::operator()()
std::thread::_State_impl<std::_Bind_simple<void (*(kaldi::rnnlm::RnnlmTrainer*))(kaldi::rnnlm::RnnlmTrainer*)> >::_M_run()
```

This can appear in 39th iteration, till that point the training works fine. It is with this GPU:
`LOG (rnnlm-train[5.4.146~5-6b94e]:FinalizeActiveGpu():cu-device.cc:247) The active GPU is [1]: GeForce GTX 1080 free:7927M, used:187M, total:8114M, free/total:0.976953 version 6.1
`

It seems like the cuSparse library initialization error? Or just passing the handle? The unit-test `cu-sparse-matrix-test` on the same machine is working well... Is the cuSparse initialized together with cuBLAS, or is there a 'lazy' initialization? Can it be a GPU memory issue? (memory is already taken by allocator, so there is not enough of it to initialize cuSparse?)

When I resume the training, it continues well, which is strange...

**Comment by danpovey** [comment]
That is a GPU driver bug.  I believe that particular bug is related to file locking in the ~/.nv/ directory, which relates to JIT compilation caching.  It happens when several programs start at the same time and NFS is slow.
The bug is not present in recent driver versions, but recent drivers contain even worse bugs (see #2450) so don't upgrade to fix it.
I believe you can resolve that issue by putting CUDA_CACHE_DISABLE=1 in your path.sh and/or making sure your are compiling for all the required compute capabilities of your hardware.
