### ISSUE TITLE
Denoise module

### ISSUE THREAD

**Issue by zhly0** [kaldi-asr/kaldi#2457]
Hi，this is not a issue，just a question，is kaldi has  a  module that denoise the input？or the denoise module was implement by the user？
Thanks!

**Comment by danpovey** [comment]
No it doesn't have such a module.
Generally speaking denoising methods (e.g. spectral subtraction) will just deteriorate ASR performance.  What works better is multi-style training-- train on the same types of noises that  you want to test on.

**Comment by zhly0** [comment]
Thanks！
