### ISSUE TITLE
Final answer extraction from Apiai-Decode egs

### ISSUE THREAD

**Issue by vishalprabha** [kaldi-asr/kaldi#2462]
Hi, 

How to extract just the transcription answer of the Apiai-Decode model using ./recognize.sh. 
This prints the output on the console, however using subprocess or >> to write the output in the file is not copying out everything. 
Does anyone know how to get the transcription of the given wav file from the terminal?

**Comment by danpovey** [comment]
maybe it is going to stderr, figure out how redirect the standard error,
e.g. redirecting it with
>& foo
instead of > foo

**Comment by vishalprabha** [comment]
Thank you got it!
