### ISSUE TITLE
cp: cannot stat 'data/train_960_cleaned': No such file or directory

### ISSUE THREAD

**Issue by keanbin** [kaldi-asr/kaldi#2482]
run local/nnet/run_fsmn_ivector.sh DFSMN_S
error: cp: cannot stat 'data/train_960_cleaned': No such file or directory

where are data/train_960_cleaned?

**Comment by danpovey** [comment]
it would have been set up if you had run the run.sh before.
but this is in a PR, it's not in kaldi master, we don't support things like this.
