### ISSUE TITLE
CUDA 9.2 supports GCC 7

### ISSUE THREAD

**Issue by leomao** [kaldi-asr/kaldi#2484]
CUDA 9.2 is now listing gcc-7.3.1 in its supported compiler.
Should add following into `src/configure`.

```
        9_2)
          MIN_UNSUPPORTED_GCC_VER="8.0"
          MIN_UNSUPPORTED_GCC_VER_NUM=80000;
        ;;
```

**Comment by danpovey** [comment]
Sure, that makes sense.

**Comment by leomao** [comment]
0f954c27228436a088417cd1d7b1557357f012ec miss `;;` at the end.

**Comment by jtrmal** [comment]
resolved, closing
