### ISSUE TITLE
configure syntax error unexpected token

### ISSUE THREAD

**Issue by hartsantler** [kaldi-asr/kaldi#2490]
running configure in the src directory gives this error.
configure: line 421: syntax error near unexpected token `)'

```bash
[kizna@localhost src]$ pwd
/home/kizna/kaldi/src
[kizna@localhost src]$ ./configure --shared
./configure: line 421: syntax error near unexpected token `)'
./configure: line 421: `        *)'
```

**Comment by hartsantler** [comment]
i changed line 421 of the configure script, and added `;;` then it works.

```bash
        9_2 | 9_*)
          MIN_UNSUPPORTED_GCC_VER="8.0"
          MIN_UNSUPPORTED_GCC_VER_NUM=80000;
        ;;
        *)
          echo "Unsupported CUDA_VERSION (CUDA_VERSION=$CUDA_VERSION), please report it to Kaldi mailing list, together with 'nvcc -h' or 'ptxas -h' which lists allowed -gencode values..."; exit 1;
        ;;
```

**Comment by hartsantler** [comment]
now i can run `./configure --shared` but now i get an error about OpenFst.
Its strange that it falls back to the path `/include/fst/fst.h`, because on linux that should be `/usr/include/fst/fst.h`

```bash
[kizna@localhost src]$ ./configure --shared
Configuring ...
Checking compiler g++ ...
Checking OpenFst library in  ...
***configure failed: Could not find file /include/fst/fst.h:
  you may not have installed OpenFst. See ../tools/INSTALL ***
```

I installed OpenFst using `sudo dnf install openfst-devel openfst-tools` and fst.h is in /usr/include/fst where it should be.
```bash
[kizna@localhost src]$ ls -lh /usr/include/fst/fst.h 
-rw-r--r--. 1 root root 30K Mar  4 11:40 /usr/include/fst/fst.h
```
The configure script but not be fedora compatible, because defaulting to `/include/fst` looks like a windows path.

**Comment by danpovey** [comment]
We have fixed the syntax error in "configure".  But you should follow the instructions that it gives you, and look at ../tools/INSTALL, instead of going your own way.
