### ISSUE TITLE
can not build related so

### ISSUE THREAD

**Issue by TianBinyu** [kaldi-asr/kaldi#2492]
Dear gooofy 
Now we need to porting kaldi to Tizen platform, and the kaldi need use :
/usr/lib/libatlas.so.3 
/usr/lib/libf77blas.so.3 
/usr/lib/libcblas.so.3 
/usr/lib/liblapack_atlas.so.3 
after we download the atlas&lapack code, we only can generate three file, but the liblapack_atlas.so.3  is never created~
Can you help me to check this issue?
Thank you very much~

**Comment by danpovey** [comment]
It may work without liblapack_atlas-- it might be so-called "fat" atlas
where several different libararies are combined into one.
Or prehaps you didn't configure it to build the LAPACK parts.
I don't recommend to try to build ATLAS libraries yourself, the build
process is complicated.  Best to get libraries that someone else built.  Or
use CBLAS.

This
http://kaldi-asr.org/doc/matrixwrap.html
explains some of the background.

**Comment by TianBinyu** [comment]
@danpovey 
when i try to porting atlas to Tizen platform, i found  lots of build error related with CPU and gcc setting.
I think it is hard to porting all atlas.... :(

**Comment by danpovey** [comment]
Sorry: instead of saying "or use CBLAS" I should have said "Or use
OpenBLAS".  OpenBLAS is easier to build than ATLAS, and people seem to
already have adapted it for that platform.

https://bugs.tizen.org/browse/TRE-1897

**Comment by TianBinyu** [comment]
@danpovey 
thank you for your help~
i will try it~

**Comment by TianBinyu** [comment]
@danpovey 
when i want to build matrix.so, it request me to choose one option:
bash-3.2# g++ -std=c++11 -I.. -I/.build.packages/BUILD/kaldi-0.1.01/tools/openfst/include  -Wall -Wno-sign-compare -Wno-unused-local-typedefs -Wno-deprecated-declarations -Winit-self -DKALDI_DOUBLEPRECISION=0 -DHAVE_EXECINFO_H=1 -DHAVE_CXXABI_H   -I/.build.packages/BUILD/kaldi-0.1.01/tools/ATLAS_headers/include   -pthread -g  -fPIC   -c -o kaldi-matrix.o kaldi-matrix.cc

In file included from ../matrix/cblas-wrappers.h:29:0,
                 from ../matrix/jama-svd.h:34,
                 from kaldi-matrix.cc:26:
../matrix/kaldi-blas.h:113:4: error: #error "You need to define (using the preprocessor) either HAVE_CLAPACK or HAVE_ATLAS or HAVE_MKL (but not more than one)"
   #error "You need to define (using the preprocessor) either HAVE_CLAPACK or HAVE_ATLAS or HAVE_MKL (but not more than one)"

HAVE_CLAPACK is used for android.
HAVE_ATLAS is hard to build.
If i need to build MKL in Tizen?
I found this macro can not be replaced by OpenBLAS...
I am sorry to bother you... :(

**Comment by TianBinyu** [comment]
@danpovey 
it can choose openBLAS, thank you Danpovey~

**Comment by TianBinyu** [comment]
@danpovey 
After i use OpenBLAS, the issue is fixed, thank you very much~

**Comment by tomh4** [comment]
@TianBinyu can you share your solution to build kaldi for Tizen?
