### ISSUE TITLE
Building nnet3 with DOUBLE_PRECISION=1 fails

### ISSUE THREAD

**Issue by jhennrich** [kaldi-asr/kaldi#2496]
Building with DOUBLE_PRECISION=1 fails because `BaseFloat` is defined as `double`, so the following two functions have the same Signature:

```
src/nnet3/nnet-parse.cc:
std::string SummarizeVector(const VectorBase<BaseFloat> &vec) {
    ...
}

std::string SummarizeVector(const VectorBase<double> &vec) {
    Vector<BaseFloat> vec_copy(vec);
    return SummarizeVector(vec_copy);
}
```

Fix:
Since the second one is only a converter and only required if DP is disabled, it could be removed. Replace the function with:
```
#if (KALDI_DOUBLEPRECISION == 0)
std::string SummarizeVector(const VectorBase<double> &vec) {
    Vector<BaseFloat> vec_copy(vec);
    return SummarizeVector(vec_copy);
}
#endif
```

**Comment by danpovey** [comment]
Thanks for reporting the issue.  I think an easier fix would be to change
the BaseFloat to float.
Would you mind making a PR?

On Wed, Jun 13, 2018 at 7:54 AM, Johannes Hennrich <notifications@github.com

**Comment by jhennrich** [comment]
Then you would get the same problem when compiling with DP turned off.

**Comment by danpovey** [comment]
No, because it would exist in both float and double, and BaseFloat would
equal one of the two.

On Thu, Jun 14, 2018 at 8:14 AM, Johannes Hennrich <notifications@github.com

**Comment by jhennrich** [comment]
True, that works

**Comment by jtrmal** [comment]
resolved, closing
