### ISSUE TITLE
fstpushspecial, not converging after 200 iterations,

### ISSUE THREAD

**Issue by vesis84** [kaldi-asr/kaldi#2501]
Hi,
I've been recently looking into the `fstpushspecial` described in section 4  in [ping-ping paper (icassp13)](http://www.danielpovey.com/files/2013_icassp_pingpong.pdf).

It appeared that the method does not converge on our "min(det(L o G))":
`WARNING (fstpushspecial[5.4.53~1-eba5]:Iterate():push-special.cc:182) push-special: finished 200 iterations without converging.  Output will be inaccurate.
`

According to the log, the stochasticity of the "arc_sort(push_special(min(det(L o G)))" graph is following:
```
-0.0615572 -0.102471
[info]: LG not stochastic.
```

How severe is this? (i.e. what negative consequences are linked to the use of LG graph with imperfect pushing?) Is there something we should check on our side? (properties of LM ?, lexicon ?)

More info about the setup:
- the lexicon contains several pronunciation variants and pronunciation probabilities,
- the LM was built by 'pocolm',

Besides the warning, the `HCLG.fst` is generated, so we can decode with it.

But, we were wondering if there is a way to fix the weight pushing,
either by changing the input data, or by changing the algorithm.

Any comment on the topic?
Best, Karel.

**Comment by danpovey** [comment]
There will be very little negative consequences: a probably-indetectable
increase in search errors.
We could easily increase the max-iterations of that program, but it would
make it slower.
It's not like it's diverging; it just converges slowly for some inputs.
I'm not 100% sure what specific property these problematic inputs have.

Dan
