### ISSUE TITLE
generating spurious zeros as words in the lexicon

### ISSUE THREAD

**Issue by jtrmal** [kaldi-asr/kaldi#2502]
The way the awk line is
https://github.com/kaldi-asr/kaldi/blob/ca239f22dabcd1cde4b73a0dabeb148c58ccce45/egs/multi_en/s5/local/g2p/apply_g2p.sh#L32
generates lot of zeros (character 0) as oov words.txt, if the given speaker/utterance contains no oovs at all:
output from count_oov.pl
```
00p0UnUssOF8Bkxd 12 0
00xrzqTK1tLNWaBM 19 0
01JkFD2rzzgaz7tE 19 1 asy
```
gets converted by this line into
```
0
0
asy
```
instead of just outputting
```
asy
```

I believe one fix would be
```
 awk '{if (NF > 3 ) {for(i=4; i<NF; i++) printf "%s",$i OFS; if(NF) printf "%s",$NF; printf ORS}}' | \
```

**Comment by jtrmal** [comment]
@xiaohui-zhang can you please confirm and fix?

**Comment by xiaohui-zhang** [comment]
Probably just:
awk '{if (NF > 3 ) {for(i=4; i<NF; i++) printf "%s",$i OFS; printf "%s",$NF; printf ORS}}'

Sure I'll commit. Thanks Yenda for pointing it out.

**Comment by danpovey** [comment]
OK, but I think you are being too fancy with the OFS and ORS.  You can just
do:
awk '{if (NF > 3 ) {for(i=4; i<NF; i++) printf "%s ",$i; print $NF;}}'
which I think will have the same effect.

**Comment by jtrmal** [comment]
@xiaohui-zhang you will probably want to create PR?

**Comment by jtrmal** [comment]
@xiaohui-zhang , you fixed it only in your repo, can you please create a PR?

**Comment by xiaohui-zhang** [comment]
oh I've fixed it and Dan has merged it:
https://github.com/xiaohui-zhang/kaldi/commit/86acc448d3969d9afdbb2e3550bae748e4b62a2b Sorry I thought you know that...

**Comment by jtrmal** [comment]
ok, good -- no, I didn't know that, that links leads only to your repository
