### ISSUE TITLE
Speaker recognition possible

### ISSUE THREAD

**Issue by suresh-s** [kaldi-asr/kaldi#2516]
Is Speaker recognition possible with this framework?  I want to store the input voice pattern as part of enrolment process. then want to verify the input voice and find out who is currently speaking.

Is it possible?

**Comment by danpovey** [comment]
yes but this isn't the place for this type of question, and also, you need to do some background reading on speaker recognition and specifically speaker recognition with Kaldi.  If you had done even a basic web search you would have found plenty of info.
