### ISSUE TITLE
Debug ASR

### ISSUE THREAD

**Issue by songpu2015617** [kaldi-asr/kaldi#2517]
I am new to this area. I know this question maybe asked before. But I still want to know how Kaldi debug ASR failures from the output? How can you figure out it is the AM failure, lexicon failure or LM failure? Thanks for any input.

**Comment by danpovey** [comment]
You can't.  It's not even clear to me that it would be meaningful to classify failures in that way (except possibly in cases where the  reference transcription had words not in the lexicon).
Anyway see kaldi-asr.org/forums.html for how to ask questions.
