### ISSUE TITLE
make_vad failed

### ISSUE THREAD

**Issue by TianBinyu** [kaldi-asr/kaldi#2518]
@danpovey 

[mfcc.zip](https://github.com/kaldi-asr/kaldi/files/2122914/mfcc.zip)

Dear danpovey, we finished to porting kaldi to tizen platform.But when it runs, we met one issue:

sid/compute_vad_decision.sh --nj 1 --cmd run.pl data/sre16_eval_enroll exp/make_vad /home/abuild/rpmbuild/BUILD/Speaker-Identification/Speaker-Identification-Server/xv/mfcc
run.pl: job failed, log is in exp/make_vad/vad_sre16_eval_enroll.1.log
bash-3.2#
bash-3.2#
bash-3.2# cat exp/make_vad/vad_sre16_eval_enroll.1.log
 compute-vad --config=conf/vad.conf scp:data/sre16_eval_enroll/split1/1/feats.scp ark,scp:/home/abuild/rpmbuild/BUILD/Speaker-Identification/Speaker-Identification-Server/xv/mfcc/vad_sre16_eval_enroll.1.ark,/home/abuild/rpmbuild/BUILD/Speaker-Identification/Speaker-Identification-Server/xv/mfcc/vad_sre16_eval_enroll.1.scp
 Started at Thu Jun 21 09:12:32 UTC 2018

/home/abuild/rpmbuild/BUILD/Speaker-Identification/Speaker-Identification-Server/xv/bin/compute-vad --config=conf/vad.conf scp:data/sre16_eval_enroll/split1/1/feats.scp ark,scp:/home/abuild/rpmbuild/BUILD/Speaker-Identification/Speaker-Identification-Server/xv/mfcc/vad_sre16_eval_enroll.1.ark,/home/abuild/rpmbuild/BUILD/Speaker-Identification/Speaker-Identification-Server/xv/mfcc/vad_sre16_eval_enroll.1.scp
WARNING (compute-vad[5.4]:main():compute-vad.cc:82) No frames were judged voiced for utterance User5_0
LOG (compute-vad[5.4]:main():compute-vad.cc:95) Applied energy based voice activity detection; processed 0 utterances successfully; 0 had empty features, and 1 were completely unvoiced.
LOG (compute-vad[5.4]:main():compute-vad.cc:99) Proportion of voiced frames was 0 over 931 frames.
Accounting: time=0 threads=1
 Ended (code 1) at Thu Jun 21 09:12:32 UTC 2018, elapsed time 0 seconds

After we deal with one wav file, it seems the vad can not detect any voice in it:0 had empty features, and 1 were completely unvoiced.
We have attached the wav file and mfcc result file.
Now we guess maybe it is the openBLAS has some issue in tizen, so the mfcc is not right.But we do not know how to prove it.
I have one question, for same wav file,  i run it in linux platform and tizen platform,  the mfcc result file must be same, am i right?

**Comment by david-ryan-snyder** [comment]
I don't know what tizen is, but I do have a few suggestions:

* Verify what happens to your file on a standard platform. Maybe your file is too quiet, or your energy threshold is too high. 

* You can use **compare-feats** (https://github.com/kaldi-asr/kaldi/blob/master/src/featbin/compare-feats.cc) to compare features generated on the standard linux platform and tizen. They won't be identical, but they should have a high similarity score.

* What mfcc.conf are you using? It looks like you're running an x-vector recipe. Make sure you're using the mfcc.conf that comes with that recipe! You'll notice that the x-vector mfcc configs uses the default --use-energy option, which is --use-energy=true. This is _necessary_ for the energy VAD to work.

**Comment by danpovey** [comment]
Also, those binaries weren't always designed to operate on just one file.
It's possible that that file was really all silence, or quiet enough that
the dumb VAD would plausibly designate it as all silence.   In that case it
might not really be a bug.

**Comment by TianBinyu** [comment]
Dear david-ryan-snyder &  danpovey 
thank you for your reply~
I got it is the openBLAS issue, now when we use new openBLAS, issue is fixed.
So i will close this issue.
Thank you
