### ISSUE TITLE
problem with run.pl with gpu

### ISSUE THREAD

**Issue by Xinyi7** [kaldi-asr/kaldi#2543]
Hi, I am posting this issue that when I run run.pl --gpu 1 with kaldi, no error message was reported but the gpu usage according to nvidia-smi is still 0 percentage. I posted an issue earlier about gpu config before bc the gpu was too old but I have already changed the gpu to GTX 1060. I am wondering if there is anything that I did wrong that caused this? Thank you so much for your help.

**Comment by Xinyi7** [comment]
I am sorry i feel that I did not state the question clear enough. I ran cd to cudamatrix dir and ran make test after the installation and the test all passed. However, when I tried to extract mfcc vectors, I realized that the gpu is performing at 0% and 1%  and the script did not show up in the processes. Does mfcc extraction process not use gpu? I appreciate your time and help. :)

**Comment by danpovey** [comment]
MFCC extraction doesn't use GPU.  Only neural net training.

**Comment by Xinyi7** [comment]
Thank you.

**Comment by ArindamS22** [comment]
Can we train acoustic models which does not use neural network and the corresponding decoding graph in GPU @danpovey ?Thanks in advance.

**Comment by danpovey** [comment]
No
