### ISSUE TITLE
cu-matrix need something optimized

### ISSUE THREAD

**Issue by danpovey** [kaldi-asr/kaldi#2552]
@kangshiyin, I wonder if you could help me optimize a particular case of AddDiagMatMat?  It's something that I'm encountering in propagation of BatchNorm for a convolutional component (where block-dim is set); it's being called indirectly via AddDiagMat2.

With reference to the function definition:
```void CuVectorBase<Real>::AddDiagMatMat(Real alpha, const CuMatrixBase<Real> &M,
                                       MatrixTransposeType transM,
                                       const CuMatrixBase<Real> &N,
                                       MatrixTransposeType transN, Real beta) ```
the case that's slow looks like this:
```
(gdb) p M
p M
$8 = (const kaldi::CuMatrixBase<float> &) @0x7fffffffbff0: {
  data_ = 0x4abb760000, num_cols_ = 32, num_rows_ = 1039360, stride_ = 32}
(gdb) p transM
p transM
$9 = kaldi::kTrans
(gdb) p N
p N
$10 = (const kaldi::CuMatrixBase<float> &) @0x7fffffffbff0: {
  data_ = 0x4abb760000, num_cols_ = 32, num_rows_ = 1039360, stride_ = 32}
(gdb) p transN
p transN
$11 = kaldi::kNoTrans
(gdb) p alpha
p alpha
$12 = 9.62130571e-07
(gdb) p beta
p beta
$13 = 0
```
Is there any chance you could optimize for this case?  This is taking a big chunk of the computation time, which doesn't feel right.

**Comment by kangshiyin** [comment]
#2555 speeds up matrix of the size (1048576, 32) from 1.25 gflops to 16.44 gflops, but it still has distance to the possible peak ~55 gflops on that size. I will try it in a day or two.
