### ISSUE TITLE
nnet3-xvector-compute error 

### ISSUE THREAD

**Issue by breeef** [kaldi-asr/kaldi#2553]
i tried run:nnet3-xvector-compute final.raw scp:test.scp ark:test.ark to get vectors
but something should do before run this command ,i'm not good at shell and prel,please tell me ,what 
i should do ,mfcc?

**Comment by danpovey** [comment]
Your initial comment mentioned  the error:
``` Failed to read matrix from stream. : Expected "[", got "RIFFF" File position at start is 0, currently 5```
That looks like you are trying to read a wav file where a matrix of features were expected.  Until you understand Kaldi better you should be looking at the example scripts, not the underlying binaries.
E.g. in egs/sre16/v2/run.sh, search for sid/nnet3/xvector/extract_xvectors.sh.

Dan

**Comment by danpovey** [comment]
and see kaldi-asr.org/forums.html for how to ask questions.
