### ISSUE TITLE
Question about long silences in online decoding.

### ISSUE THREAD

**Issue by yusuf-gunaydin** [kaldi-asr/kaldi#2558]
We had performance drop during online recognition that included silences. Adding silence-weight option fixes the records that include say up to 1000-1500 ms (not sure about the exact duration, it might be greater than this) of continuous silence. If the silence is longer than this duration, the performance drop becomes an issue again.

Questions:
  - Is that drop in performance an expected situation?
  - Can we fix that by changing configuration values?
  - If this is expected, can you give an estimate duration that Kaldi can tolerate? (So that we can apply VAD and include some pre/postspeech silence without performance loss.)

By the way, we are using Kaldi as a C++ library. So, it is possible that we are using some things in a wrong way.

Thanks.

**Comment by olix20** [comment]
@yusuf-gunaydin have you considered doing vad/sad before decoding?

**Comment by yusuf-gunaydin** [comment]
Normally we are using VAD. However, when I talked with the team they said there may be some circumstances that using VAD may not be possible and in those cases long silences degrade the performance.

If it is expected for Kaldi to have low performance on long silence even with silence weighting I can try to persuade my team to use VAD everywhere.

**Comment by danpovey** [comment]
Could the issue be that your utterances are very long?  I don't recomend to
decode things longer than about 15 seconds; things like OpenFst's BestPath
won't work very well for such long utterances.

It would be interesting to know what kinds of errors you are getting.  Is
it that after the silence, you get deletions?  Just generally a lot of
errors?  What is the silence-weight you are using?  Is this an nnet3-based
setup?

**Comment by yusuf-gunaydin** [comment]
The utterances are shorter than 15 seconds. I have added an example utterance as [attachment](https://github.com/kaldi-asr/kaldi/files/2261429/4.zip). The structure is like: 0.5s silence -- 3s speech -- 2.5s silence -- 3s speech -- 2.5s silence.

The errors are deletions. For the attached file continous recognition result is "bir iki üç dört beş altı merhaba beş" while the full utterance decoding gives the correct result: "bir iki üç dört beş altı merhaba bir iki üç dört beş"
Actually the silence is between "beş altı" and "merhaba", but "merhaba" is recognized correctly even if it is directly after the silence. The words after it are deleted except the last one.

This is an nnet3 based setup. I have tried a whole range of values for silence-weight parameter. It didn't change the result. For these result the value was 0.001.

(I had to zip the wav file. Otherwise GitHub does not accept it.)

**Comment by danpovey** [comment]
Also I assume you didn't forget to set the
` --ivector-silence-weighting.silence-phones` option when you set the
`--ivector-silence-weighting.silence-weight` option?

**Comment by yusuf-gunaydin** [comment]
Yes, I have set the silence phones option.

The issue seems to occur on specific model and utterance combinations. I have tried another utterance with the same model, but it is recognized correctly. And other models can recognize the utterance with silence I sent before.

We are trying to train a small model to reproduce the issue. (The one we tried before is a private company model.) However, we haven't been able to create a model and utterance combination yet. As soon as we find a reproducible case I will post it here.

**Comment by danpovey** [comment]
Unless this is an issue that shows up clearly in statistics, for instance
the offline decoder recognizes silence on 20% of frames and on the same
data the online decoder recognizes silence on 25% of frames, I don't think
it's something I should get into debugging because it's probably not a
bug.  It's expected that there are slight differences between the two
decoders, due to small differences in how the ivectors are averaged and
(for recurrent models) how context is handled.  So it's not necessarily a
bug if one particular file shows a difference in recognition output.

**Comment by yusuf-gunaydin** [comment]
OK. I will close this issue now. If we can find a consistent case I will reopen it.
