### ISSUE TITLE
Question about the MFCC calculations existed in Kaldi

### ISSUE THREAD

**Issue by Diamondyelo** [kaldi-asr/kaldi#2559]
1. I found that Kaldi 5.3 and Kaldi 5.1 gives different MFCC results for the same input audio file. Is there any difference in the method of MFCC calculation between these two versions?

2. In kaldi 5.1, I try two differents ways of inputing the audio file. The first one is the audio file as a whole file. The second way is cutting the whole file into frames. By calculating the mfcc values of the files in these two ways. I found that, the MFCC value of the first frame in the second way corresponds to the values in the first way. However, from the second frames until the last frame, the mfcc values in the second way is totally different from those in the first one. I found this to be very abnormal. Can you give me an explanation about how this happens? Is there any dependance of the previous frames when calculating the second frame?

**Comment by entn-at** [comment]
This may be caused by the `--dither` option which causes random Gaussian noise to be added to the signal to avoid log of zero. It defaults to `1.0`, you can set it in your `mfcc.conf` to `0.0`.

**Comment by Diamondyelo** [comment]
Thanks for help, the second question has been successfully resolved.

I would also like to ask if it is possible to set the parameters so that the mfcc calculation results of the latest version of kaldi and kaldi5.1 are the same. I use the default parameters ( --use-energy=false ) to calculate mfcc in these two versions, the average relative error of the obtained results reached 30%.
