### ISSUE TITLE
Voxceleb Nnet Core dumped

### ISSUE THREAD

**Issue by Herlderlord** [kaldi-asr/kaldi#2561]
I've run the voxceleb v2 recipe (x-vectors) and i encountered the following error:

``
bash: line 1: 43540 Aborted                 (core dumped) ( nnet3-shuffle-egs --srand=73 ark:exp/xvector_nnet_1a/egs/egs_temp.73.ark ark,scp:exp/xvector_nnet_1a/egs/egs.73.ark,exp/xvector_nnet_1a/egs/egs.73.scp ) 2>> exp/xvector_nnet_1a/egs/log/shuffle.73.log >> exp/xvector_nnet_1a/egs/log/shuffle.73.log 
``

This message appeared after launching this command : 
``
local/nnet3/xvector/run_xvector.sh: Getting neural network training egs
``

Is it possible to help me solve the problem ? What information do you need ?

**Comment by danpovey** [comment]
you should show us what's in the log file.

**Comment by david-ryan-snyder** [comment]
@danpovey, we can close this
