### ISSUE TITLE
librispeech data validation issue

### ISSUE THREAD

**Issue by shadowoom** [kaldi-asr/kaldi#2566]
![capture](https://user-images.githubusercontent.com/7023289/43052314-0d6ef514-8e57-11e8-8495-5feda1e397e6.PNG)

I was running the librispeech s5 example and followed the steps in run.sh.
Has anyone encountered similar issue?  Can tell me how to resolve this?

**Comment by danpovey** [comment]
I can't see a reference to make_fbank.sh in any of the scripts in the librispeech s5 directory.  Are you using an up-to-date version of Kaldi (if not, how recent?) and are you using Kaldi from the official source?  Have you changed the scripts, perhaps?

**Comment by shadowoom** [comment]
Thank you for the reply. 

I directly cloned from this repo, https://github.com/tramphero/kaldi. The Alibaba_MIT_Speech_DFSMN patch which was built on the Kaldi speech recognition toolkit with commit "04b1f7d6658bc035df93d53cb424edc127fab819", was applied.  

The run_fsmn_ivector script in librispeech/s5/local/nnet/ folder can be found here:
https://github.com/tramphero/kaldi/blob/master/egs/librispeech/s5/local/nnet/run_fsmn_ivector.sh

I checked the wav.scp file and reco2dur file in train_960_cleaned folder, the length were already differed before they were copied into the data_fbank folder.

**Comment by danpovey** [comment]
It may be it is from a bug that was in an older copy of Kaldi at some
point; merging with master might resolve it (but it might not).
I'm not going to provide support for that external repo.

**Comment by shadowoom** [comment]
Okay, thanks, I will try to merge with master and see how.

**Comment by yangxueruivs** [comment]
I also met this problem before. I just ignore the data validation part of wav.scp and reco2dur(last one) in utils/validation_data_dir.sh and then it works correctly.

**Comment by shadowoom** [comment]
Thanks, that's really helpful.

**Comment by AlexPeng19** [comment]
@shadowoom hi, i trained the dfsmn model too and encountered the same issue, did you resolved it now by skipping the validation line? @yangxueruivs could you provide some detail for skip, such as which file, line numbers. on the other hand, did you exported the trained model? i mean how did you used it.

looking forward your response. thanks in advance.

**Comment by danpovey** [comment]
utils/fix_data_dir.sh may help.

This is likely an issue in the branch of Kaldi that you are using, which is
obviously not the master... you could comment on the repo where it's hosted
and ask them to help or to fix it.
