### ISSUE TITLE
has problem when use ssh.pl to run program

### ISSUE THREAD

**Issue by YihengJiang** [kaldi-asr/kaldi#2568]
First thanks for authors' work.

I write the follow two lines to  .queue/machines
172.16.46.105
172.16.46.108

Note: I run script on machine:172.16.46.105

but when I run script,it requests password for machine 172.16.46.105 ,however, this machine is my dominate machine, I have boot lots of processes,so it can not input password one by one, and it should not requests password in my understanding. 

I'm sure that ssh have configure finished, because as you can see, I run script on machine 105, but needn't input password for machine 108. And I have look processes by command "top",result present that script has ran on 108,but has not ran on 105.

now,what should I do to work it out?
Hope to get response from authors,thank you.

**Comment by danpovey** [comment]
I guess you are parallelizing using ssh.pl.
it's a ssh configuration issue.  Find someone local who understands such things.
