### ISSUE TITLE
.has_key() removed from Python3

### ISSUE THREAD

**Issue by JRMeyer** [kaldi-asr/kaldi#2570]
There's multiple scripts in the nnet3 
training pipeline which include .has_key() 
to search a dict for a key, but this method 
breaks in python3

use `key in dict` instead of `dict.has_key(key)`

**Comment by JRMeyer** [comment]
Here are the files with has_key:

egs/wsj/s5/steps/nnet3/dot/nnet3_to_dot.py
egs/wsj/s5/steps/nnet3/xconfig_to_configs.py
egs/voxforge/gst_demo/run-live.py
egs/wsj/s5/steps/nnet2/make_multisplice_configs.py
egs/wsj/s5/steps/libs/nnet3/xconfig/parser.py
egs/wsj/s5/steps/libs/nnet3/report/log_parse.py

**Comment by danpovey** [comment]
Thanks.  Do you have time to make a PR to fix it?

**Comment by JRMeyer** [comment]
I can easily make the changes, but I'm not confident I can run checks to
make sure it's all good...

Would you still like me to do a PR?


вт, 24 июл. 2018 г., 8:17 ПП Daniel Povey <notifications@github.com>:

**Comment by danpovey** [comment]
It's OK, I'll just look over the diff to check that it looks OK.   The
change is small enough that I don't think we need to test it.

**Comment by JRMeyer** [comment]
OK- I'll make a PR then

вт, 24 июл. 2018 г., 8:43 ПП Daniel Povey <notifications@github.com>:
