### ISSUE TITLE
 Cannot allocate the requested memory

### ISSUE THREAD

**Issue by xiaoming0217** [kaldi-asr/kaldi#2583]
Dear sir,
             There comes a problem when I was training nnet3  model in aisehll, which describes like this:
             

LOG (nnet3-train[5.4]:PrintMemoryUsage():cu-allocator.cc:127) Memory usage: 565742480 bytes currently allocated (max: 641014368); 334091864 currently in use by user (max: 493138232); 12619/135552 calls to Malloc* resulted in CUDA calls.
WARNING (nnet3-train[5.4]:MallocPitchInternal():cu-allocator.cc:97) Allocation of 10204 x 6656 region failed: freeing some memory and trying again. 
LOG (nnet3-train[5.4]:MallocPitchInternal():cu-allocator.cc:102) To avoid future problems like this, changing memory_factor from 1.3 to 1.1
LOG (nnet3-train[5.4]:PrintStatsForThisPhase():nnet-training.cc:305) Average objective function for 'output' for minibatches 650-659 is -0.543481 over 5120 frames.
LOG (nnet3-train[5.4]:PrintStatsForThisPhase():nnet-training.cc:305) Average objective function for 'output' for minibatches 660-669 is -0.562294 over 5120 frames.
LOG (nnet3-train[5.4]:PrintStatsForThisPhase():nnet-training.cc:305) Average objective function for 'output' for minibatches 670-679 is -0.569792 over 5120 frames.
LOG (nnet3-train[5.4]:PrintMemoryUsage():cu-allocator.cc:127) Memory usage: 450847632 bytes currently allocated (max: 641014368); 334091864 currently in use by user (max: 493138232); 13355/141334 calls to Malloc* resulted in CUDA calls.
WARNING (nnet3-train[5.4]:MallocPitchInternal():cu-allocator.cc:97) Allocation of 10204 x 6656 region failed: freeing some memory and trying again. 
LOG (nnet3-train[5.4]:PrintMemoryUsage():cu-allocator.cc:127) Memory usage: 476602768 bytes currently allocated (max: 641014368); 213959664 currently in use by user (max: 493138232); 13359/141353 calls to Malloc* resulted in CUDA calls.
WARNING (nnet3-train[5.4]:MallocPitchInternal():cu-allocator.cc:97) Allocation of 3400 x 11264 region failed: freeing some memory and trying again. 
LOG (nnet3-train[5.4]:PrintMemoryUsage():cu-allocator.cc:127) Memory usage: 464126352 bytes currently allocated (max: 641014368); 334091864 currently in use by user (max: 493138232); 13395/141541 calls to Malloc* resulted in CUDA calls.
WARNING (nnet3-train[5.4]:MallocPitchInternal():cu-allocator.cc:97) Allocation of 10204 x 6656 region failed: freeing some memory and trying again. 
LOG (nnet3-train[5.4]:PrintMemoryUsage():cu-allocator.cc:127) Memory usage: 464126352 bytes currently allocated (max: 641014368); 334091864 currently in use by user (max: 493138232); 13511/142371 calls to Malloc* resulted in CUDA calls.
WARNING (nnet3-train[5.4]:MallocPitchInternal():cu-allocator.cc:97) Allocation of 10204 x 6656 region failed: freeing some memory and trying again. 
LOG (nnet3-train[5.4]:PrintMemoryUsage():cu-allocator.cc:127) Memory usage: 464755472 bytes currently allocated (max: 641014368); 334091864 currently in use by user (max: 493138232); 13548/142558 calls to Malloc* resulted in CUDA calls.
WARNING (nnet3-train[5.4]:MallocPitchInternal():cu-allocator.cc:97) Allocation of 10204 x 6656 region failed: freeing some memory and trying again. 
LOG (nnet3-train[5.4]:PrintMemoryUsage():cu-allocator.cc:127) Memory usage: 393360864 bytes currently allocated (max: 641014368); 334091864 currently in use by user (max: 493138232); 13548/142558 calls to Malloc* resulted in CUDA calls.
WARNING (nnet3-train[5.4]:MallocPitchInternal():cu-allocator.cc:97) Allocation of 10204 x 6656 region failed: freeing some memory and trying again. 
LOG (nnet3-train[5.4]:PrintStatsForThisPhase():nnet-training.cc:305) Average objective function for 'output' for minibatches 680-689 is -0.569368 over 5120 frames.
LOG (nnet3-train[5.4]:PrintMemoryUsage():cu-allocator.cc:127) Memory usage: 489390992 bytes currently allocated (max: 641014368); 334544064 currently in use by user (max: 493138232); 13781/144003 calls to Malloc* resulted in CUDA calls.
WARNING (nnet3-train[5.4]:MallocPitchInternal():cu-allocator.cc:97) Allocation of 10200 x 4608 region failed: freeing some memory and trying again. 
LOG (nnet3-train[5.4]:PrintMemoryUsage():cu-allocator.cc:127) Memory usage: 410207632 bytes currently allocated (max: 641014368); 334544064 currently in use by user (max: 493138232); 13781/144003 calls to Malloc* resulted in CUDA calls.
WARNING (nnet3-train[5.4]:MallocPitchInternal():cu-allocator.cc:97) Allocation of 10200 x 4608 region failed: freeing some memory and trying again. 
LOG (nnet3-train[5.4]:PrintMemoryUsage():cu-allocator.cc:127) Memory usage: 356428784 bytes currently allocated (max: 641014368); 334544064 currently in use by user (max: 493138232); 13781/144003 calls to Malloc* resulted in CUDA calls.
ERROR (nnet3-train[5.4]:MallocPitchInternal():cu-allocator.cc:114) Cannot allocate the requested memory (10200 x 4608 = 47001600 bytes)

[ Stack-Trace: ]
nnet3-train() [0x9ce296]
kaldi::MessageLogger::HandleMessage(kaldi::LogMessageEnvelope const&, char const*)
kaldi::MessageLogger::~MessageLogger()
kaldi::CuMemoryAllocator::MallocPitchInternal(unsigned long, unsigned long, unsigned long*)
kaldi::CuMemoryAllocator::MallocPitch(unsigned long, unsigned long, unsigned long*)
kaldi::CuDevice::MallocPitch(unsigned long, unsigned long, unsigned long*)
kaldi::CuMatrix<float>::Resize(int, int, kaldi::MatrixResizeType, kaldi::MatrixStrideType)
kaldi::nnet3::NnetComputer::ExecuteCommand()
kaldi::nnet3::NnetComputer::Run()
kaldi::nnet3::NnetTrainer::TrainInternal(kaldi::nnet3::NnetExample const&, kaldi::nnet3::NnetComputation const&)
kaldi::nnet3::NnetTrainer::Train(kaldi::nnet3::NnetExample const&)
main
__libc_start_main
_start

1.Is it caused by insufficient memory of GPU?
2.How can I use multiple GPUs other than one GPU? Do I need to set several parameters?
3.Someone said  this problem is caused by no sampling. If this is ture,how should I setting the samples

**Comment by danpovey** [comment]
See if there is a warning earlier in the log about exclusive mode.  In that case you should use exclusive mode (nvidia-smi -c 3) and set `--use-gpu=yes` as the arg to chain/train.pyl

**Comment by xiaoming0217** [comment]
@danpovey 
Thank you so much for your reply.I tried your method，and built a compute-exclusive mode by using nvidia-smi -c 3. However, there comes a error which described like this:

nnet3-train --use-gpu=yes --read-cache=exp/nnet3/tdnn_sp/cache.12 --print-interval=10 --momentum=0.0 --max-param-change=2.0 --backstitch-training-scale=0.0 --l2-regularize-factor=0.333333333333 --backstitch-training-interval=1 --srand=12 'nnet3-copy --learning-rate=0.00435300771478 --scale=1.0 exp/nnet3/tdnn_sp/12.mdl - |' 'ark,bg:nnet3-copy-egs --frame=3              ark:exp/nnet3/tdnn_sp/egs/egs.27.ark ark:- |             nnet3-shuffle-egs --buffer-size=5000             --srand=12 ark:- ark:- |              nnet3-merge-egs --minibatch-size=512 ark:- ark:- |' exp/nnet3/tdnn_sp/13.3.raw 
WARNING (nnet3-train[5.4]:SelectGpuId():cu-device.cc:150) Will try again to get a GPU after 20 seconds.
Wed Aug  1 03:24:00 2018       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 384.130                Driver Version: 384.130                   |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 108...  Off  | 00000000:03:00.0 Off |                  N/A |
| 66%   82C    P2   169W / 250W |    938MiB / 11172MiB |     80%   E. Process |
+-------------------------------+----------------------+----------------------+
|   1  GeForce GTX 108...  Off  | 00000000:04:00.0  On |                  N/A |
| 79%   88C    P2   196W / 250W |   1320MiB / 11171MiB |     73%   E. Process |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0      6865      C   nnet3-train                                  939MiB |
|    1      1003      G   /usr/lib/xorg/Xorg                           242MiB |
|    1      1945      G   compiz                                       161MiB |
|    1      2184      G   fcitx-qimpanel                                 9MiB |
|    1      6868      C   nnet3-train                                 1007MiB |
+-----------------------------------------------------------------------------+
LOG (nnet3-train[5.4]:SelectGpuId():cu-device.cc:159) num-gpus=2. Device 0: all CUDA-capable devices are busy or unavailable.  Device 1: all CUDA-capable devices are busy or unavailable.  
ERROR (nnet3-train[5.4]:SelectGpuId():cu-device.cc:160) Failed to create CUDA context, no more unused GPUs? 

[ Stack-Trace: ]
nnet3-train() [0x9ce296]
kaldi::MessageLogger::HandleMessage(kaldi::LogMessageEnvelope const&, char const*)
kaldi::MessageLogger::~MessageLogger()
kaldi::CuDevice::SelectGpuId(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)
main
__libc_start_main
_start


# Accounting: time=20 threads=1
# Ended (code 255) at Wed Aug  1 03:24:00 CST 2018, elapsed time 20 seconds

How comes of this problem?

**Comment by danpovey** [comment]
You don't seem to have read my entire reply.
Anyway you shouldn't ask this question here.  see kaldi-asr.org/forums.html for how to ask questions in general, but this question is frequently asked and there are plenty of replies about it on the list.
