### ISSUE TITLE
Run "nnet-compute-test" on windows will cause error "vector iterator + offset out of range" and then crash.

### ISSUE THREAD

**Issue by qindazhu** [kaldi-asr/kaldi#2589]
Hi there,

If you build kaldi on windows according to the instructions [https://github.com/kaldi-asr/kaldi/blob/master/windows/INSTALL.md]() and run project "nnet-compute-test", then you will get error `vector iterator + offset out of range`.  The reason is as below.

Actually, there are two code snippets will cause the same error, they are both in function `IndexVectorHasher::operator ()` of `nnet-common.cc`.

- The first code snippet is `if (med > iter + n1)` at line 399 in `nnet-common.cc` 

- The second code snippet is ` for (; iter < end; iter += n2) ` at line 411 in `nnet-common.cc`.

For the two code snippets, both ` iter += n1` and `iter += n2` will cause assertion `_Mycont->_Mylast < _Ptr + _Off` failed in `vector` of MSVC (line 143 of function `_Vector_const_iterator& operator+=(difference_type _Off) ` in `vector` on my MSVC version  14.14.26428 ). I guess STL on Linux does not check the bound before operation `+=` so there is no error on Linux. However, I think that doing ` iter += n1` and `iter += n2` directly without checking bound is improper in a way, as it may cause some unexpected result in some cases.

I read the code of function `size_t IndexVectorHasher::operator ()` in `nnet-common.cc` and have fixed the error. (I guess...At least got the same test result compared with the result on Linux...)

My fixes are:

-  Change line 399 `if (med > iter + n1)`  to ` if (n1 <= index_vector.size())`

-  In the for-loop of line 411, add code:
    `    // check 'n2 > index_vector.size()' first,  `
`   // otherwise  'end - n2' will trigger error '_Ptr + _Off < _Mycont->_Myfirst' in 'vector' of MSVC`
    ` if (n2 > index_vector.size() || iter  >= end - n2) {
		  break;
	  }`

Could you kindly help to confirm this? If it's right, should I create a pr?

**Comment by danpovey** [comment]
Sure, make a PR.

**Comment by qindazhu** [comment]
Added the pr #2594, Could you kindly help to review this?
