### ISSUE TITLE
Creating MFCC's

### ISSUE THREAD

**Issue by banasu** [kaldi-asr/kaldi#2602]
I created MFCC's.
The (ID) (Ark file where mfcc is saved) : (offset) is in feats.scp.

My question is what exactly does the offset tell you?
For the first ID , offset = 4.
For the second , it was 38,067.
I tried counting for that many characters to see if ID1 began there. It didn't match with 4.
Need help.

**Comment by danpovey** [comment]
It's the character offset into the file.

**Comment by danpovey** [comment]
..but not of the id-- of the actual object being stored, like the matrix. see kaldi-asr.org/forums.html for how to ask questions.
