### ISSUE TITLE
how to transform a kaldi model to ONNX

### ISSUE THREAD

**Issue by wangyunxiaa** [kaldi-asr/kaldi#2603]
if i want to use kaldi-trained model in other environment like TF,I want to do a transform by ONNX，does kaldi support the conversion?and onnx is installed in python,if i want to transform a kaldimodel trained in c++,what shoud i do?do i need to install pykaldi?

**Comment by wangyunxiaa** [comment]
Thanks for your reply~ I have read some samples about onnxmltools on"https://github.com/onnx/onnxmltools"，if i want to transform a  model in new freamwork to ONNX, maybe I need  installed the packages or tools about it,  by the way,if i will do the transform by myself,which packages shoud I install, because the trained model by kaldi is in C++ environment however onnx is installed in python?

**Comment by underdogliu** [comment]
It's just my personal guess without any proof - although it won't be officially supported in foreseeable future like what Dan said above, there is tools in the wild like 'tfkaldi' or any other in-house tools which supports nnet training using other python frameworks (actually as far as I know, thre are individual researchers train nnet in this way. For example: [this one](http://www.cstr.ed.ac.uk/downloads/publications/2017/rownicka_asru17.pdf). So I guess it'll be possible but it require people to try and fail to figure out and it's not officially supported by kaldi team. Hope that helps though.

**Comment by danpovey** [comment]
@wangyunxiaa, you won't be able to do this.

**Comment by llhe** [comment]
@wangyunxiaa We made a in-house kaldi-onnx converter and also an onnx-[mace](https://github.com/XiaoMi/mace) converter which then we can run the kaldi model optimized for mobile phone or IoT devices. The converter and mace kaldi-specific  ops will be released soon.

**Comment by danpovey** [comment]
Cool!  What types of models does it work for?

**Comment by TonyMou** [comment]
@danpovey kaldi-onnx supports both nnet2 and nnet3 models.

**Comment by danpovey** [comment]
Does it have limitations in terms of, for example, the component types it supports?
I actually don't really know how the onnx format works, e.g. what level of representation it is most similar to.

**Comment by TonyMou** [comment]
ONNX is another representation of kaldi models, most of the kaldi components can be converted to ONNX operators. Nnet2 models can be easily converted. Porting nnet3 models  is also supported but just a little complicated, because some models with IfDefined descriptors are directed cyclic graphs.
We also did some work to make MACE(https://github.com/XiaoMi/mace) support running inference with  models converted from kaldi with frequently-used components , e.g. Affine, Splice, PNorm, Normalize, SumGroup, DimRange, LstmNonlinear.

**Comment by Jamiroquai88** [comment]
> @wangyunxiaa We made a in-house kaldi-onnx converter and also an onnx-[mace](https://github.com/XiaoMi/mace) converter which then we can run the kaldi model optimized for mobile phone or IoT devices. The converter and mace kaldi-specific ops will be released soon.

Hi, do you have some timeline for kaldi -> ONNX converter? Or is there some repo I can follow? Thanks.

**Comment by TonyMou** [comment]
@Jamiroquai88 The open-source process is on-going, will let you know when it's done.

**Comment by JiayiFu** [comment]
> @Jamiroquai88 The open-source process is on-going, will let you know when it's done.

Hi Tony, is there any recent progress about kaldi-to-onnx?

**Comment by TonyMou** [comment]
@JiayiFu The code has been completed and is under review.

**Comment by JiayiFu** [comment]
> @JiayiFu The code has been completed and is under review.
Thanks.

**Comment by TonyMou** [comment]
@JiayiFu @Jamiroquai88 @danpovey 
Check the tool here:  https://github.com/XiaoMi/kaldi-onnx

**Comment by danpovey** [comment]
Thanks for the info!  I would be interested to hear peoples' feedback from
using it.

Is that MACE tool also from Xiaomi?

Does this ONNX tool make you choose a fixed time range?  I notice in the
binary onnx file, words like input_time_range, start_index, end_index, for
each layer.  I am curious what those mean, and what the ONNX computation
looks like in the end (I have seen ONNX computations as text files with
variables like %1, %2, and so on).

**Comment by TonyMou** [comment]
@danpovey When propagating the network, some non-simple components, such as StatisticsExtraction, StatisticPooling,  Round,  need to know which time-index frame will be used,  and if there are left-context or right-context,  start time index and end-time index are required too. So, we put these info in the ONNX operator's attributes. Here is a ONNX model viewer to check the converted model:  https://lutzroeder.github.io/netron/

**Comment by danpovey** [comment]
That's interesting.  Showing part of what it displays for this model.
Can you give us some idea how you did the conversion to Onnx?  E.g. a few lines of code that illustrate the general spirit of what the conversion process is like, and a few lines of code that would show the core part of how the model is loaded and used ?


![Onnx](https://user-images.githubusercontent.com/3298747/57945770-c2d3a580-78a8-11e9-925a-f2176a7e9ebd.png)

**Comment by danpovey** [comment]
And @TonyMou, if you can (or one of your co-workers), please respond to this thread https://groups.google.com/d/msgid/kaldi-developers/27775727-23cf-41b0-a3d8-9e591df4a998%40googlegroups.com
on the kaldi-developers list.

**Comment by palaniappankvignesh** [comment]
I need help in converting onnx custom operator for kaldi's splice, targetrms and pNorm
