### ISSUE TITLE
when install srilm i got Error  :undefined reference to `libiconv_open' 

### ISSUE THREAD

**Issue by shipleyxie** [kaldi-asr/kaldi#2605]

**Comment by shipleyxie** [comment]
after i download the srilm_1.7.2.tar.gz , i rename it to srilm.tgz and put it into the kaldi/tool/  directory
i also have install the necessay lib to srilm:
after that :
`sh install_srilm.sh`
and i got the following error repo
ps: i have install libiconv ,and i can see it in /usr/bin  and /usr/local/bin
Could someone give the a solution to this problem?
_______________________________
/media/ai01/d14784b3-14f6-4ea0-89f2-ccc4c5d28966/voice/kaldi/kaldi/tools/srilm/misc/src/File.cc:125: undefined reference to `libiconv_close'
../../lib/i686-m64/libmisc.a(File.o): In function `File::reopen(char const*, char const*)':
/media/ai01/d14784b3-14f6-4ea0-89f2-ccc4c5d28966/voice/kaldi/kaldi/tools/srilm/misc/src/File.cc:165: undefined reference to `libiconv_close'
../../lib/i686-m64/libmisc.a(File.o): In function `File::reopen(char const*)':
/media/ai01/d14784b3-14f6-4ea0-89f2-ccc4c5d28966/voice/kaldi/kaldi/tools/srilm/misc/src/File.cc:214: undefined reference to `libiconv_close'
../../lib/i686-m64/libmisc.a(File.o): In function `File::reopen(char const*, unsigned long, int)':
/media/ai01/d14784b3-14f6-4ea0-89f2-ccc4c5d28966/voice/kaldi/kaldi/tools/srilm/misc/src/File.cc:246: undefined reference to `libiconv_close'
../../lib/i686-m64/libmisc.a(File.o): In function `File::reopen(std::string&, int)':
/media/ai01/d14784b3-14f6-4ea0-89f2-ccc4c5d28966/voice/kaldi/kaldi/tools/srilm/misc/src/File.cc:270: undefined reference to `libiconv_close'
../../lib/i686-m64/libmisc.a(File.o): In function `File::fgetsUTF8(char*, int)':
/media/ai01/d14784b3-14f6-4ea0-89f2-ccc4c5d28966/voice/kaldi/kaldi/tools/srilm/misc/src/File.cc:341: undefined reference to `libiconv_open'
/media/ai01/d14784b3-14f6-4ea0-89f2-ccc4c5d28966/voice/kaldi/kaldi/tools/srilm/misc/src/File.cc:379: undefined reference to `libiconv'
/media/ai01/d14784b3-14f6-4ea0-89f2-ccc4c5d28966/voice/kaldi/kaldi/tools/srilm/misc/src/File.cc:337: undefined reference to `libiconv_open'
collect2: error: ld returned 1 exit status
test -f ../bin/i686-m64/ngram
make[2]: *** [/media/ai01/d14784b3-14f6-4ea0-89f2-ccc4c5d28966/voice/kaldi/kaldi/tools/srilm/common/Makefile.common.targets:118: ../bin/i686-m64/ngram] Error 1
make[2]: Leaving directory '/media/ai01/d14784b3-14f6-4ea0-89f2-ccc4c5d28966/voice/kaldi/kaldi/tools/srilm/lm/src'
make[1]: *** [Makefile:109: release-programs] Error 1
make[1]: Leaving directory '/media/ai01/d14784b3-14f6-4ea0-89f2-ccc4c5d28966/voice/kaldi/kaldi/tools/srilm'
make: *** [Makefile:61: World] Error 2

**Comment by shipleyxie** [comment]
Fixed!
 remove lifile in /usr/local/bin   and /usr/local/include  will do the job.
it will let the script to find the correspoing link in /usr/bin and /usr/include.
and the install_srilm.sh script will successfully install this

**Comment by Hieunv1996** [comment]
This solution may help you.
https://stackoverflow.com/questions/51552703

**Comment by noloader** [comment]
> Fixed!
> remove lifile in /usr/local/bin and /usr/local/include will do the job.

I don't think that's a solution to the problem.
