### ISSUE TITLE
egs/tedlium/s5/local/nnet/run_lstm.sh uses wrong argument

### ISSUE THREAD

**Issue by mdeisher** [kaldi-asr/kaldi#2606]
I'm trying to retrain some old models we use for regression testing.  I found that the run_lstm.sh script for tedlium no longer works.  One issue is that --proto-opts "--clip-gradient 5.0" should probably be --proto-opts "--grad-clip 5.0" instead.  But even after that fix the script fails with error 127 and refers to the training log for more details.  Unfortunately, the training log shows nothing wrong (log attached).

--Mike
[train_nnet.log](https://github.com/kaldi-asr/kaldi/files/2271025/train_nnet.log)

**Comment by danpovey** [comment]
@vesis84 may be able to fix it.  I don't really maintain the nnet1 recipes myself.

**Comment by deepakbaby** [comment]
Hi,
I also encountered the same problem. Perhaps, the error is in ```logs/iter00.initial.log``` which says
```nnet-train-lstm-streams: command not found```. Aparently, this was part of the src/nnetbin before, but in the new git version, this command seems missing.
Is there any latest lstm recipes that are tested with the latest kaldi version?
--Deepak
