### ISSUE TITLE
Possible data race issue in kernel function _copy_low_upp,  _copy_upp_low, _add_diag_vec_mat

### ISSUE THREAD

**Issue by DayDayStudyNightNightUp** [kaldi-asr/kaldi#2612]
Hi All,

I have found a false positive case by submitting issue to kaldi project here: 
https://github.com/kaldi-asr/kaldi/issues/2604

The cpp code will compiled from "ssum[tid] += ssum[tid + shift];" to:
```
%1 = add tid, shift
%2 = load ssum[%1]
%3 = load ssum[tid]
%4 = add %2, %3
store %4 to ssum[tid]
```

Seems the two threads are in the same warp, so when GPU dispatch statement to each thread in same warp, they execute same statement and will wait for other thread in the same warp to continue. (Because just one PC register). Therefore, although "ssum[tid] += ssum[tid + shift];" will be executed at the same time,  load statement will always be executed before store statement.

But it raise another issue: can write&write data race happen during same warp execution while two threads execute same "store" statement?

To make myself clear, I found 3 more example in cu-kenerls.cu.

For kernel function _copy_low_upp, let's set dimA.rows = 5, dimA.stride = 0, say grid is (1 1 1), block is (3 2 1), consider thread (2 1 0) and thread (2 0 0):
for thread (2 1 0), i = 2, j = 1, index_1 = 1, index_2 = 2
for thread (2 0 0), i = 2, j = 0, index_1 = 0, index_2 = 2

A[index_2] = A[index_1] could be compiled to:
```
%3 = getelmentptr A, index_2
%4 = getlementprt A, index_1
%5 = load Real* %4
store Real %5, Real* %3
```
Although thread (2 1 0) and thread (2 0 0) are in the same warp, it will execute store Real %5, Real* %3 at
the same time. Will it cause data race behavior?

For _copy_upp_low, dimA.rows = 5, dimA.stride = 0, given the same setup for grid and block, thread (0 2 0) and thread (0 1 0) will face same issue as _copy_low_upp

For _add_diag_vec_mat, set mat_dim.rows = 5, mat_dim.cols = 5, mat_dim.stride = 1,  mat2_row_stride = 1, mat2_col_stride = 1, say grid is (1 1 1), block is (3 2 1).
Consider thread (0 1 0) and thread (1 0 0):
For thread (0 1 0), i = 0, j = 1, index = 1, index2 = 1, mat[1] = alpha * vec[1] * mat2[1] + beta * mat[1]
For thread (1 0 0), i = 1, j = 0, index = 1, index2 = 1, mat[1] = alpha * vec[0] * mat2[1] + beta * mat[1]
For the same reason, the two threads in the same warp execute the same store statement, is there any chance of data race here?

Thanks for the help! :)

**Comment by kangshiyin** [comment]
For a meaningful matrix, the condition `stride > 0` always holds.  For a meaningful row-major matrix, the condition `stride>=cols` always holds.  Your test cases just won't happen in Kaldi.

If you are interested in CUDA programming, I would suggest you copy the related code in Kaldi to stackoverflow.com and ask questions there.  More CUDA professionals are there available for these questions.
https://stackoverflow.com/questions/tagged/cuda

**Comment by DayDayStudyNightNightUp** [comment]
@kangshiyin Thanks for the help :)
