### ISSUE TITLE
How to reduce the time-cost of extracting XVector

### ISSUE THREAD

**Issue by z771511189** [kaldi-asr/kaldi#2616]
I write a shell script based on egs/sre16/v2/run.sh to implement VoicePrintRecognition function on Android platform.
I find that when execute nnet3-xvector-compute process, it costs about 2 seconds on Android platform.
How to reduce the cost time?

**Comment by z771511189** [comment]
Does there have multi-thread option in nnet3-xvector-compute like "gmm-global-init-from-feats --num-threads=$num_threads"?

**Comment by gorinars** [comment]
JFYI. You can check nnet3-xvector-compute-parallel implementation from

https://github.com/kaldi-asr/kaldi/pull/2303/files

I did not update the branch for a while, so you may want to merge it with more recent fork.

In our case, the main computational bottleneck was slow compilation solved by loading pre-computed cache. But multi-treading helps as well.

Still, as Dan noted, the model you are trying to use is too large for android system.
