### ISSUE TITLE
How to establish one-2-one relationship between transition-id and PDF-id?

### ISSUE THREAD

**Issue by longfenghou** [kaldi-asr/kaldi#2620]
Hello Author of Kaldi, i would like to ask a question about How to establish one-2-one relationship between transition-id and PDF-id?
In the ContextDependency class, 
We may use Compute (const std::vector< int32 > &phoneseq, int32 pdf_class, int32 *pdf_id) const
to outputs the pdf_id for certain phoneseq, 
However, based on this pdf_id, how to find out the corresponding Transition-id?
I found that one pdf_id corresponds to several Transtion-id as shown in the following:
Example from the tri1 model files:
PDF id is:0 Transition_id i is:0
PDF id is:0 Transition_id i is:1
PDF id is:0 Transition_id i is:2
PDF id is:0 Transition_id i is:3
PDF id is:0 Transition_id i is:4
PDF id is:200 Transition_id i is:5
PDF id is:200 Transition_id i is:6
PDF id is:200 Transition_id i is:7
PDF id is:200 Transition_id i is:8

Another example from the yesno example:
Transition-state 1: phone = SIL hmm-state = 0 pdf = 0
 Transition-id = 1 p = 0.25 [self-loop]
 Transition-id = 2 p = 0.25 [0 -> 1]
 Transition-id = 3 p = 0.25 [0 -> 2]
 Transition-id = 4 p = 0.25 [0 -> 3]
Transition-state 2: phone = SIL hmm-state = 1 pdf = 1
 Transition-id = 5 p = 0.25 [self-loop]
 Transition-id = 6 p = 0.25 [1 -> 2]
 Transition-id = 7 p = 0.25 [1 -> 3]
 Transition-id = 8 p = 0.25 [1 -> 4]
Transition-state 3: phone = SIL hmm-state = 2 pdf = 2
 Transition-id = 9 p = 0.25 [2 -> 1]
 Transition-id = 10 p = 0.25 [self-loop]
 Transition-id = 11 p = 0.25 [2 -> 3]
 Transition-id = 12 p = 0.25 [2 -> 4]
Transition-state 4: phone = SIL hmm-state = 3 pdf = 3
 Transition-id = 13 p = 0.25 [3 -> 1]
 Transition-id = 14 p = 0.25 [3 -> 2]
 Transition-id = 15 p = 0.25 [self-loop]
 Transition-id = 16 p = 0.25 [3 -> 4]

Is there any index in the transition model that we can use to help pdf-id to find out the only transition-id that correspond to the corrent phoneseq?

Thanks a lot

**Comment by danpovey** [comment]
It can't be done.
