### ISSUE TITLE
CRASH in nnet3 -> nnet_computation

### ISSUE THREAD

**Issue by VertikaJain** [kaldi-asr/kaldi#2628]
Hi, I faced a crash while using the NnetComputation() method of nnet3 folder of kaldi. (related to compiler)
Please resolve the crash and update the code.

Thanks.

![screenshot 27](https://user-images.githubusercontent.com/40227841/44269390-003fcf80-a252-11e8-8487-2e119b64d305.png)

**Comment by danpovey** [comment]
That screenshot doesn't seem to have any information about a crash-- none
that's obvious to me, anyway.

**Comment by danpovey** [comment]
Possibly your program is multi-threaded and you were using that object without locking.
