### ISSUE TITLE
NNET3: 1D CNN

### ISSUE THREAD

**Issue by Jamesswiz** [kaldi-asr/kaldi#2630]
Hello,
Is there any stable kaldi nnet3 recipe just with 1D CNNs with maxpooling?

**Comment by danpovey** [comment]
Yes, look for any recipe with a name like 'run_tdnn.sh'.  TDNNs and 1d CNNs
are the same thing.

**Comment by danpovey** [comment]
Oh, I see you edited it to say 'with maxpooling'.  In that case, no.
