### ISSUE TITLE
error when training NN

### ISSUE THREAD

**Issue by iezhanqingran** [kaldi-asr/kaldi#2632]
when I trained the TDNN, there occoured the following error:
![image](https://user-images.githubusercontent.com/17061626/44306677-5897de00-a3c6-11e8-9943-de60b2cb9cb2.png)
but when I used another GPU server to train the same network, it didnot occour any error
So how to solve it?
thank u.

**Comment by danpovey** [comment]
You didn't show enough of the output to make clear. but my guess would be a disk was full.
