### ISSUE TITLE
compose-lattice-pruned.cc broken in release builds with optimizations

### ISSUE THREAD

**Issue by Worldexe** [kaldi-asr/kaldi#2633]
In `src/lat/compose-lattice-pruned.cc:520`. there is code:
```
    ComposedStateInfo &info = composed_state_info_[composed_state_index];
    if (info.delta_backward_cost - info.delta_backward_cost != 0) {
      // if info.delta_backward_cost is +infinity...
      int32 prev_composed_state = info.prev_composed_state;
```
I am not sure if this infinity check conforms cpp standard, but it is broken at least on `g++ (Ubuntu 5.4.0-6ubuntu1~16.04.4) 5.4.0 20160609` if kaldi is being compiled with `-Ofast` flag (`-O3` and less works OK).

I propose rewriting it like this:
```
    ComposedStateInfo &info = composed_state_info_[composed_state_index];
    if (info.delta_backward_cost == std::numeric_limits<double>::infinity()) {
      // if info.delta_backward_cost is +infinity...
```

Edit: okay, `-Ofast` implies `-ffast-math`, which changes, in particular, NaN-related behaviour.
https://stackoverflow.com/questions/7420665/what-does-gccs-ffast-math-actually-do

But, I still think my proposed check is more readable and less error-prone in case someone (like me) will try to compile kaldi with `-Ofast`.

**Comment by danpovey** [comment]
I had a look into this.
From this stack-overflow conversation:

https://stackoverflow.com/questions/22931147/stdisinf-does-not-work-with-ffast-math-how-to-check-for-infinity

it looks like even std::isinf does not work if you use -Ofast or -ffast-math, as it does not guarantee correct implementation of IEEE floating point.

So the upshot it: don't compile with that option.
