### ISSUE TITLE
ERROR when training tdnn

### ISSUE THREAD

**Issue by iezhanqingran** [kaldi-asr/kaldi#2636]
when I trained the tdnn in the last iter of the last epoch, it occour an error, the log is in the attachment
how to solve it?
thanks
ERROR (nnet3-train[5.4]:CopyToVec():cu-vector.cc:899) cudaError_t 4 : "unspecified launch failure" returned from 'cudaMemcpy(dst->Data(), this->data_, sizeof(Real) * dim_, cudaMemcpyDeviceToHost)'

[ Stack-Trace: ]

kaldi::MessageLogger::HandleMessage(kaldi::LogMessageEnvelope const&, char const*)
kaldi::MessageLogger::~MessageLogger()
void kaldi::CuVectorBase<float>::CopyToVec<float>(kaldi::VectorBase<float>*) const
kaldi::Vector<float>::Vector<float>(kaldi::CuVectorBase<float> const&)
float kaldi::TraceMatMat<float>(kaldi::CuMatrixBase<float> const&, kaldi::CuMatrixBase<float> const&, kaldi::MatrixTransposeType)
kaldi::nnet3::OnlineNaturalGradient::PreconditionDirections(kaldi::CuMatrixBase<float>*, float*)
kaldi::nnet3::NaturalGradientAffineComponent::Update(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, kaldi::CuMatrixBase<float> const&, kaldi::CuMatrixBase<float> const&)
kaldi::nnet3::AffineComponent::Backprop(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, kaldi::nnet3::ComponentPrecomputedIndexes const*, kaldi::CuMatrixBase<float> const&, kaldi::CuMatrixBase<float> const&, kaldi::CuMatrixBase<float> const&, void*, kaldi::nnet3::Component*, kaldi::CuMatrixBase<float>*) const
kaldi::nnet3::NnetComputer::ExecuteCommand()
kaldi::nnet3::NnetComputer::Run()
kaldi::nnet3::NnetTrainer::TrainInternal(kaldi::nnet3::NnetExample const&, kaldi::nnet3::NnetComputation const&)
kaldi::nnet3::NnetTrainer::Train(kaldi::nnet3::NnetExample const&)
main
__libc_start_main
_start

[log.txt](https://github.com/kaldi-asr/kaldi/files/2313244/log.txt)

**Comment by danpovey** [comment]
It's "unspecified launch failure".   That sometimes happens randomly when
GPUs crash or have bad hardware, or due to driver bugs.   I'd just rerun
from that stage.  See the --stage and --train-stage options to the
run_tdnn.sh or whatever script you were running.
