### ISSUE TITLE
[scripts] [RNNLM] Strange behaviour related to encoding

### ISSUE THREAD

**Issue by francoishernandez** [kaldi-asr/kaldi#2637]
Hi there,
With @ldeseynes we've been having some encoding issues with recent RNNLM scripts. (Seems related to #2595 )
When writing features with `choose_features.py`, special characters such as accents etc. are not properly encoded. (See below for extract of `features.txt`.)
This does not break the pipe though. Training still runs still runs but produces very poor WERs when rescoring.

Old versions of scripts -- before the change to 'latin-1' encoding -- seem to still be running properly.

```
...
45      word    Ã©tÃ©   0.17
...
```
INSTEAD OF
```
...
45      word    été   0.17
...
```

**Comment by danpovey** [comment]
Can you please try to figure out what might be going wrong?
I believe latin-1 encoding, if you always read and write using that
encoding, is supposed to preserve byte sequences.  So it's very
strange if that were not working.
e-acute seems to be bytes 303 251
and that other sequence seems to be 303 203 302 251

**Comment by danpovey** [comment]
@francoishernandez, @ldeseynes ... please look into this!  It's bothering me that it was not working.
I tried to reproduce the problem using some simple python scripts but was not able to.  Actually,   at one point I thought I was able to reproduce the problem, but then it turned out my input file was wrong... that change to the e-acute seems to be something that some types of terminals do.

**Comment by francoishernandez** [comment]
I'll try to have a deeper look tomorrow.

Le dim. 26 août 2018 21:39, Daniel Povey <notifications@github.com> a
écrit :

**Comment by danpovey** [comment]
Thanks.  Bear in mind that the locale and the presence/absence of a
terminal may affect the behavior of programs (I guess you know this though).
The goal is always to make everything work with LC_ALL=C and to always set
that as the locale.

**Comment by jtrmal** [comment]
can you please test if

    print(line.encode('latin-1'))

will fix it?

**Comment by francoishernandez** [comment]
Hmmm. Actually, when doing `export LC_ALL=C` before opening my python shell, and executing
```
words_file_latin = codecs.open("words.txt", "r", encoding="latin-1")
words_file_write = codecs.open("words_latin.txt", "w", encoding="latin-1")
for line in words_file_latin.readlines():
    words_file_write.write(line)
```
it seems to be working, even for the "œ".

Then, writing a latin-1 file along looping over the vocab in `choose_features.py` is also working (i.e. writing it properly). But the script still outputs a broken `features.txt`.
Strange thing is:
- when running it with "utf-8" encoding, we get 11175 features;
- when running it with "latin-1" encoding, we get 11194 features.

So the issue is more around reading the vocab rather than writing the final file I believe...

**Comment by jtrmal** [comment]
I'm not familiar with the feature selection procedure but the fact that it
selects different number of features is intriguing. But also depends, what
the features represent -- if they are related to string length, then it
could explain things (unicode string decoded as utf-8 will be shorter than
the same decoded as latin1). Or unicode normalization? Anyway, just wildly
guessing.
y.

**Comment by danpovey** [comment]
Remember that the actual script in question re-opens stdout with the
latin-1 encoding at the very start of the script.

Dan

**Comment by danpovey** [comment]
Also, RE the difference in num-features: there may be whitespaces in your
input that are whitespace in UTF-8 but not in ascii.  In the ASR scripts,
the validation script checks for this and errors out as it is not allowed.
Possibly we need to upgrade the validation scripts for the RNNLM setup to
check for this.    @hainan-xv please check for this.
I assume you didn't change the script at all?  You are running a vanilla
check-out of Kaldi?

**Comment by danpovey** [comment]
Oh, wait... I see that there is a problem after all.  That script is
actually splitting characters inside words.  That means it is not valid at
all to use the latin-1 encoding.  @hainan-xv can you please change the
script back to use the utf-8 encoding?  I think it may be best to
explicitly set the encoding to utf-8, to avoid any possible
locale-dependent effects.

After checking in a quick fix, we can try to set an 'encoding' option to
the script so users can choose the encoding (may help in certain non-UTF
situations).  But let's get it working first.

**Comment by danpovey** [comment]
@DongjiGao, can you please make a quick fix changing that one script's  encoding to utf-8?  You can add in a comment something like
```
# because this script splits inside words, we cannot use latin-1; we actually need to know what 
# the encoding is.  By default we make this utf-8; to handle encodings that are not compatible
# with utf-8 (e.g. gbk), we'll eventually have to make the encoding an option to this script.
```
