### ISSUE TITLE
cudaStreamPerThread

### ISSUE THREAD

**Issue by danpovey** [kaldi-asr/kaldi#2638]
reminder to me to set this on API calls.. apparently the compiler option only works for kernel invocations.

**Comment by danpovey** [comment]
@galv, if you mess around with CUDA stuff you might want to address this.  This flag needs to be used when we create handles, e.g. for CuBLAS, and when we call things like SGEMM.

**Comment by galv** [comment]
Are you sure about this? According to [this](https://docs.nvidia.com/cuda/cuda-runtime-api/stream-sync-behavior.html), there are three kinds of "default" streams:

- The default stream, which takes the behavior of one of the following two based on whether the macro CUDA_API_PER_THREAD_DEFAULT_STREAM is defined:
- The legacy default stream, which synchronizes with all other streams (by default).
- The per-thread default stream, which synchronizes only with itself (by default).

In the driver_types.h header file, you can see that these streams are defined like this:

```
#define cudaStreamDefault                   0x00  /**< Default stream flag */
#define cudaStreamNonBlocking               0x01  /**< Stream does not synchronize with stream 0 (the NULL stream) */

 /**                                                                                                                                                                                                        
 * Legacy stream handle                                                                                                                                                                                     
 *                                                                                                                                                                                                          
 * Stream handle that can be passed as a cudaStream_t to use an implicit stream                                                                                                                             
 * with legacy synchronization behavior.                                                                                                                                                                    
 *                                                                                                                                                                                                          
 * See details of the \link_sync_behavior                                                                                                                                                                   
 */
#define cudaStreamLegacy                    ((cudaStream_t)0x1)

/**                                                                                                                                                                                                         
 * Per-thread stream handle                                                                                                                                                                                 
 *                                                                                                                                                                                                          
 * Stream handle that can be passed as a cudaStream_t to use an implicit stream                                                                                                                             
 * with per-thread synchronization behavior.                                                                                                                                                                
 *                                                                                                                                                                                                          
 * See details of the \link_sync_behavior                                                                                                                                                                   
 */
#define cudaStreamPerThread                 ((cudaStream_t)0x2)
```

They have three distinct values.

The point is that I am fairly certain that you already have the correct behavior. Simply by defining that macro, you alias the default stream (cudaStreamDefault) to act as a per-thread default stream (cudaStreamPerThread).

**Comment by danpovey** [comment]
Justin told me that that macro doesn't work for API calls (as opposed to
kernel invocations), which kind of makes sense if you consider that the
libraries won't have been compiled with that flag.

**Comment by danpovey** [comment]
.. and when creating the handles, it was some kind of cudaSetStream thing,
not an optional extra argument.  I saw that in some PR that those guys had
and queried it and he told me it's necessary.

**Comment by galv** [comment]
Hmm, that's a good point about those libraries coming precompiled.

Anyway, I actually already made the change and all the unit tests pass (but took a walk in the meanwhile and had doubts about whether it was really necessary), so I'll upload a PR soon.

**Comment by galv** [comment]
We'll need to add this as well in other CUDA API calls, according to this message Dan left in @2692: 
> I believe justin mentioned that we also need to use this cudaStreamPerThread for other API calls, like memcpy.

**Comment by kkm000** [comment]
@galv, @danpovey, I'm leaving this closed?
