### ISSUE TITLE
online2-wav-nnet3-latgen-faster   "Dimension mismatch: source features have dimension 280 and LDA #cols is 302"

### ISSUE THREAD

**Issue by saber5433** [kaldi-asr/kaldi#2657]
How could I fix it？I am trying to decode the chain model of aishell2.
ERROR (online2-wav-nnet3-latgen-faster[5.4]:OnlineTransform():online-feature.cc:421) Dimension mismatch: source features have dimension 280 and LDA #cols is 302

![c640c916998d42bebb8571d566dd9df](https://user-images.githubusercontent.com/15922669/44840317-5ad62400-ac73-11e8-8666-971f243c2bbc.png)

my mfcc.conf
![822f55893e234dce795eeed445eec6d](https://user-images.githubusercontent.com/15922669/44843016-dfc43c00-ac79-11e8-9ca5-0f261538975a.png)

my online.conf
![b8b0144ab07350dbbaeb459321b1256](https://user-images.githubusercontent.com/15922669/44840405-8a852c00-ac73-11e8-9e9a-bde77cc9ddb4.png)

**Comment by danpovey** [comment]
Hm.  I think I know what the problem might be, but it's not easy to fix.
The way that online decoding code was designed, you are not supposed to include the pitch features in the features that you give to the i-vector extractor; it doesn't support including the pitch features there.   But it looks like the pitch features must have been given to the i-vector extractor when it was trained.  Fixing this would require changes to the aishell2 training script.   (might involve utils/data/limit_feature_dim.sh).  
 @naxingyu, is there any chance you could look at this?

**Comment by wbgxx333** [comment]
@saber5433 you need change the aishell2 recipe,because the ivector must use no pitch;and nnet3 can use the pitch.you can follow the danpovey,and use the utils/data/limit_feature_dim.sh.and this is the same in aishell/s5/local/nnet3/run_tdnn.sh.

**Comment by naxingyu** [comment]
@danpovey  Sorry I just noticed this issue. I'll see what to do with the scripts.

**Comment by naxingyu** [comment]
@danpovey While modifying the script of aishell2, I was wondering, is there a better way of prevent this kind of issue from happening? For example, in `steps/online/nnet3/prepare_online_decoding.sh`, if `add-pitch` is enabled, compare the dimensions of the input of the ivector extractor and that of the network (minus the ivector part). If equal, there should be a warning (or error) that the user might be using pitch in the ivector of the online decoding setup.

**Comment by naxingyu** [comment]
OK, I'll do it after fixing this one.

**Comment by naxingyu** [comment]
This issue is addressed.

**Comment by icestoneking** [comment]
> @ saber5433你需要更改aishell2配方，因为ivector必须不使用音高;而nnet3可以使用pitch.you可以使用danpovey，并使用utils / data / limit_feature_dim.sh.这在aishell / s5中是相同的/local/nnet3/run_tdnn.sh。

In case of this problem, must be added “utils/data/limit_feature_dim.sh 0:39 data/${datadir}_hires data/${datadir}_hires_nopitch || exit 1;”in local/chain/run_tdnn.sh?

**Comment by icestoneking** [comment]
> @saber5433 you need change the aishell2 recipe,because the ivector must use no pitch;and nnet3 can use the pitch.you can follow the danpovey,and use the utils/data/limit_feature_dim.sh.and this is the same in aishell/s5/local/nnet3/run_tdnn.sh.

In case of this problem, must be added “utils/data/limit_feature_dim.sh 0:39 data/${datadir}_hires data/${datadir}_hires_nopitch || exit 1;”in local/chain/run_tdnn.sh?

**Comment by naxingyu** [comment]
This issue had been fixed in the referred PR. You should checkout the latest code.

**Comment by icestoneking** [comment]
> This issue had been fixed in the referred PR. You should checkout the latest code.

Ok, thank you for your reply.
