### ISSUE TITLE
Mel-frequency conversion: use `log1p`, `expm1`

### ISSUE THREAD

**Issue by christoph-conrads** [kaldi-asr/kaldi#2665]
The mel-frequency conversion functions `MelBanks::MelScale()` and `MelBanks::InverseMelScale()` ([`src/feat/mel-computations.h`, lines 81-87](https://github.com/kaldi-asr/kaldi/blob/66145ea9eaf2e5bd016198e6ac8d79a9fc6d8067/src/feat/mel-computations.h#L81-L87)) contain expressions of the form `log(1+x)` and `exp(x)-1`. For small `x`, the calculated results may be off by more than one [ULP](https://en.wikipedia.org/wiki/Unit_in_the_last_place). To fix this problem, the C standard library contains the functions [`log1p`](https://linux.die.net/man/3/log1p) and [`expm1`](https://linux.die.net/man/3/expm1).

Using `log1p` and `expm1` will have negligible impact on the speed and guarantees accurate results for all values. Do you want me to submit a patch?

As an example, consider for instance the computation of the mel-frequency of the default VTLN lower cutoff value `MelBanksOptions::vtln_low = 100` in the [`MelBanks::MelBanks(...)`, line 61-101](https://github.com/kaldi-asr/kaldi/blob/66145ea9eaf2e5bd016198e6ac8d79a9fc6d8067/src/feat/mel-computations.cc#L61-L101). Computing the equivalent of `InverseMelScale(MelScale(100.0f))` in Python yields a result with a difference of about 8 ULP to the same value computed with `log1p` and `expm1`. Usually for lower frequencies, the difference will be larger, for higher frequencies lower.

**Comment by danpovey** [comment]
Hm.  Interesting observation, but I think it's OK.  It's not a part of the computation where precision matters that much.  Incidentally, we have a Log1p function wrapper which was introduced for Windows compatibility and it might be necessary to test if Windows still has this problem if we were to look for the expm1 stuff.  So might be too much of a hassle.  But thanks for noticing.
