### ISSUE TITLE
Suggestion: use `ssize_t` everywhere

### ISSUE THREAD

**Issue by christoph-conrads** [kaldi-asr/kaldi#2671]
The Kaldi codes uses at least seven integer types on a regular basis:
* `MatrixIndexT`,
* `SignedMatrixIndexT`,
* `UnsignedMatrixIndexT` ([`matrix/kaldi-matrix.cc:1081-1083`](https://github.com/kaldi-asr/kaldi/blob/e50bd7308164bd5b914d235984959f8a232fed66/src/matrix/kaldi-matrix.cc#L1081-L1083)),
* `std::size_t` ([`matrix/kaldi-matrix.h:70-73`](https://github.com/kaldi-asr/kaldi/blob/e50bd7308164bd5b914d235984959f8a232fed66/src/matrix/kaldi-matrix.h#L70-L73)),
* `int64` (feature extraction),
* `int32` (feature extraction),
* `int` (Tensorflow RRNLM).

The code freely mixes some of these types at the most inappropriate ways, e.g., in [`NumFrames`](https://github.com/kaldi-asr/kaldi/blob/e50bd7308164bd5b914d235984959f8a232fed66/src/feat/feature-window.cc#L42), frame shift, frame length, and number of samples are stored as 64-bit integers but the number of frames is stored in a 32-bit integer. In [`SamplingLm::ConsumeNGram`](https://github.com/kaldi-asr/kaldi/blob/e50bd7308164bd5b914d235984959f8a232fed66/src/rnnlm/sampling-lm.cc#L35-L36) a signed integer is first cast to an unsigned integer in an expression where the compiler would automatically perform a cast. Later one is added to this integer and again casted to an unsigned type. If a variable `x` is a signed integer and `x+1` overflows, then the program exhibits undefined behavior and casting `x+1` to an unsigned type is irrelevant.

This is a complete mess. This is a disaster in a language where implicit type conversions are abound and the type of a variable makes the difference between heaven and hell in expression as simple as `x+1` (signed integer overflow is undefined behavior).

`std::size_t` is a standard C++ integer type that guarantees any index and any object size can be represented with it. All C and C++ standard functions take or return values of type `std::size_t` including `strlen`, `snprintf`, operator new, `std::vector::size`, `std::copy_n`, and so on. `std::size_t` matches the natural integer size on a machine, e.g., `sizeof(std::size_t) == 4` on 32-bit processors and `sizeof(std::size_t) == 8` on 64-bit CPUs. The Kaldi developers attempt to follow the Google Style Guide and this guide dictates using signed integers instead of unsigned integer throughout the code. Therefore I suggest using `ssize_t`. This type is the signed counter-part of `std::size_t`, ~~it is part of the C standard but not any C++ standard (hence the missing namespace specifier).~~ This type is defined by POSIX (see [`types.h`](http://pubs.opengroup.org/onlinepubs/009696799/basedefs/sys/types.h.html)). Since this type is not defined by the C and C++ standard, you should add the following static assertion to the Kaldi code:
```c++
static_assert(sizeof(ssize_t) == sizeof(std::size_t))
```
or
```c++
#include <type_traits>
static_assert(std::is_same<ssize_t, std::make_signed<std::size_t>::type>::value);
```

**Comment by christoph-conrads** [comment]
To avoid the static assertion, you could also used an alias, e.g.:
```c++
#include <type_traits>
using Integer = std::make_signed<std::size_t>::type;
```

**Comment by danpovey** [comment]
There are reasons for all of this but I don't have time to explain them right now.  It's not that I'm not aware of ssize_t.  You are maybe analyzing the code without knowing the expected size range of some of the quantities, so you can't see our logic.
