### ISSUE TITLE
`ExtractWaveformRemainder` with `FrameExtractionOptions::snip_edges = false`

### ISSUE THREAD

**Issue by christoph-conrads** [kaldi-asr/kaldi#2672]
What is the expected behavior of [`ExtractWaveformRemainder`](https://github.com/kaldi-asr/kaldi/blob/e50bd7308164bd5b914d235984959f8a232fed66/src/feat/feature-window.cc#L222-L235) when [`FrameExtractionOptions::snip_edges`](https://github.com/kaldi-asr/kaldi/blob/e50bd7308164bd5b914d235984959f8a232fed66/src/feat/feature-window.h#L85-L89) is false?

A [comment in `NumFrames`](https://github.com/kaldi-asr/kaldi/blob/e50bd7308164bd5b914d235984959f8a232fed66/src/feat/feature-window.cc#L60-L61) has the following to say about `FrameExtractionOptions::snip_edges`:
```c++
    // if --snip-edges=false, the number of frames is determined by rounding the
    // (file-length / frame-shift) to the nearest integer.  [snip]
```
Now consider that the following scenario:
* `frame_extraction_option.snip_edges == false`
* `frame_extraction_option.window_shift() == 90`
* There are 50 samples.

The important property of this setup is that `num-samples/window-shift` will be rounded up. Consequently, `NumFrames` will return 1. 

This is the current source code of `ExtractWaveformRemainder`:
```c++
void ExtractWaveformRemainder(const VectorBase<BaseFloat> &wave,
                              const FrameExtractionOptions &opts,
                              Vector<BaseFloat> *wave_remainder) {
  int32 frame_shift = opts.WindowShift();
  int32 num_frames = NumFrames(wave.Dim(), opts);
  // offset is the amount at the start that has been extracted.
  int32 offset = num_frames * frame_shift;
  KALDI_ASSERT(wave_remainder != NULL);
  int32 remaining_len = wave.Dim() - offset;
  wave_remainder->Resize(remaining_len); // line 232
  KALDI_ASSERT(remaining_len >= 0); // line 233
  if (remaining_len > 0)
    wave_remainder->CopyFromVec(SubVector<BaseFloat>(wave, offset, remaining_len));
}
```
With the values above, `num_frames = 1` and `offset = 90`. `remaining_len` will then be negative and since Lines 232 and 233 are in the wrong order the program will crash somewhere inside [`Vector::Resize`](https://github.com/kaldi-asr/kaldi/blob/master/src/matrix/kaldi-vector.cc#L190).

Apparently `ExtractWaveformRemainder` will only return if `num-samples/frame-size` is rounded down. This sounds hardly intentional. What is the desired behavior here?

**Comment by danpovey** [comment]
It looks like ExtractWaveformRemainder is no longer used anywhere.  I would
merge a PR to delete it.

**Comment by danpovey** [comment]
This is a duplicate question; I have just answered this.

**Comment by jtrmal** [comment]
Simply extract the function from one of the previous revisions of the repo
and copy it to your code anywhere you need it.
y.
