### ISSUE TITLE
nonzero return status 256

### ISSUE THREAD

**Issue by stefbraun** [kaldi-asr/kaldi#2685]
Hello,

I am running kaldi recipes on a slurm cluster and make_fbank_pitch.sh throws an error:

FAILING COMMAND
```
srun paste-feats --length-tolerance=2 "ark:compute-fbank-feats  --verbose=2 --config=conf/fbank.conf scp,p:exp/make_fbank/dev_clean/wav.10.scp ark:- |" "ark,s,cs:compute-kaldi-pitch-feats --verbose=2 --config=conf/pitch.conf scp,p:exp/make_fbank/dev_clean/wav.10.scp ark:- | process-kaldi-pitch-feats  ark:- ark:- |" ark:- | copy-feats --compress=true --write-num-frames=ark,t:exp/make_fbank/dev_clean/utt2num_frames.10 ark:- ark,scp:/home/cluster/stbraun/repos/espnet/egs/librispeech/asr1/fbank/raw_fbank_pitch_dev_clean.10.ark,/home/cluster/stbraun/repos/espnet/egs/librispeech/asr1/fbank/raw_fbank_pitch_dev_clean.10.scp
```

ERROR
```
WARNING (paste-feats[5.3.25~1-8cc5c8]:Close():kaldi-io.cc:512) Pipe compute-kaldi-pitch-feats --verbose=2 --config=conf/pitch.conf scp,p:exp/make_fbank/dev_clean/wav.10.scp ark:- | process-kaldi-pitch-feats  ark:- ark:- | had nonzero return status 256
LOG (paste-feats[5.3.25~1-8cc5c8]:main():paste-feats.cc:158) Done 0 utts, errors on 85
```
Interestingly, when adding a second command - echo $0 && -, the command runs through:
WORKING COMMAND
```
srun echo $0 && paste-feats --length-tolerance=2 "ark:compute-fbank-feats  --verbose=2 --config=conf/fbank.conf scp,p:exp/make_fbank/dev_clean/wav.10.scp ark:- |" "ark,s,cs:compute-kaldi-pitch-feats --verbose=2 --config=conf/pitch.conf scp,p:exp/make_fbank/dev_clean/wav.10.scp ark:- | process-kaldi-pitch-feats  ark:- ark:- |" ark:- | copy-feats --compress=true --write-num-frames=ark,t:exp/make_fbank/dev_clean/utt2num_frames.10 ark:- ark,scp:/home/cluster/stbraun/repos/espnet/egs/librispeech/asr1/fbank/raw_fbank_pitch_dev_clean.10.ark,/home/cluster/stbraun/repos/espnet/egs/librispeech/asr1/fbank/raw_fbank_pitch_dev_clean.10.scp
```
I cant find useful information on the nonzero return status 256 in this context, did anyone here experience the same issue?

**Comment by stefbraun** [comment]
seems like a problem on the cluster, kaldi was compiled for a different cpu type.

**Comment by danpovey** [comment]
I don't think that's the issue.  If you do
` srun command1 | command2`
it won't run the whole pipe, it will paste the output of srun into command2.  You need to put those commands in a bash script and run it.  Or better, run it via the wrapper utils/parallel/slurm.pl, the same way things are run in standard Kaldi scripts.  But you have to escape the '|' symbol using backslash.  The wrappers run.pl, queue.pl and slurm.pl know to treat it as a pipe symbol.

**Comment by stefbraun** [comment]
Thank you very much. I have failed to report the actual error that caused the problem:
```srun: error: cluster0: task 0: Illegal instruction```

The cluster uses different CPU types, and the kaldi version was compiled for a different CPU type than it was running on, hence the illegal instruction error. Somehow, `compute-fbank-feats` was working under this condition, but `compute-kaldi-pitch-feats` did not work. After using properly compiled kaldi, the error went away.
