### ISSUE TITLE
the multilingual chain model-training。。。。

### ISSUE THREAD

**Issue by wqn628** [kaldi-asr/kaldi#2687]
hello，I  am doing the multilingual chain model training in recent days。and first i use the get_egs.sh to generate the cges.*.ark file of each language and the combine them with the steps/chain/multilingual/combine_egs.sh. Finally, i revise the local/chain/run_lstm.sh to do the multilingual chain model training. besides, due to the fact that the chain model training of each language has finished, so i call the run_lstm.sh with "--satge 12".
However, in the trianing process, the error occured as follows:

`nnet3-chain-train --use-gpu=yes --apply-deriv-weights=False --l2-regularize=5e-05 --leaky-hmm-coefficient=0.1 --xent-regularize=0.025 --optimization.min-deriv-time=-8 --optimization.max-deriv-time-relative=15 --print-interval=10 --momentum=0.0 --max-param-change=1.41421356237 --backstitch-training-scale=0.0 --backstitch-training-interval=1 --l2-regularize-factor=0.333333333333 --srand=0 'nnet3-copy --learning-rate=0.003 --scale=0.99 exp/chain_mtl/kr0829_jp0703/lstm_6j_offline_1536_512_384_kaldifeat_ld5/0.mdl - |' exp/chain_mtl/kr0829_jp0703/lstm_6j_offline_1536_512_384_kaldifeat_ld5/den.fst 'ark,bg:nnet3-chain-copy-egs --outputs=ark:exp/chain_mtl/kr0829_jp0703/egs/cegs.output.2.ark --weights=ark:exp/chain_mtl/kr0829_jp0703/egs/cegs.weight.2.ark                         --frame-shift=2                         scp:exp/chain_mtl/kr0829_jp0703/egs/cegs.2.scp ark:- |                         nnet3-chain-shuffle-egs --buffer-size=5000                         --srand=0 ark:- ark:- | nnet3-chain-merge-egs                         --minibatch-size=32 ark:- ark:- |' exp/chain_mtl/kr0829_jp0703/lstm_6j_offline_1536_512_384_kaldifeat_ld5/1.2.raw 
LOG (nnet3-chain-train[5.4]:SelectGpuId():cu-device.cc:191) CUDA setup operating under Compute Exclusive Mode.
LOG (nnet3-chain-train[5.4]:FinalizeActiveGpu():cu-device.cc:247) The active GPU is [1]: TITAN Xp	free:11939M, used:250M, total:12189M, free/total:0.979414 version 6.1
nnet3-copy --learning-rate=0.003 --scale=0.99 exp/chain_mtl/kr0829_jp0703/lstm_6j_offline_1536_512_384_kaldifeat_ld5/0.mdl - 
LOG (nnet3-copy[5.4]:main():nnet3-copy.cc:114) Copied raw neural net from exp/chain_mtl/kr0829_jp0703/lstm_6j_offline_1536_512_384_kaldifeat_ld5/0.mdl to -
ASSERTION_FAILED (nnet3-chain-train[5.4]:SetTransitions():chain-den-graph.cc:67) : 'transition.pdf_id >= 0 && transition.pdf_id < num_pdfs' `
Each language has den.fst in the chain model training, but with the multilingual chain model training, which den.fst should "nnet3-chain-train" use ? or use different den. SFT interchangeably？
Any help would be appreciated

**Comment by danpovey** [comment]
@vimalmanohar and @pegahgh, is that script actually usable for multilingual training right now?  I only see it being used for semi-supervised training in the example scripts.  My recollection was that in order to truly do multilingual training (different den.fst's for different egs), one would need to use a different binary which is not checked in.

**Comment by vimalmanohar** [comment]
The script only supports having a single tree and single den.fst. There needs to be a modification to the binaries at the chain trainer level to store multiple denominator fsts in memory and use a different one each minibatch.
