### ISSUE TITLE
data dir ../ causes error

### ISSUE THREAD

**Issue by johnjosephmorgan** [kaldi-asr/kaldi#2688]
If you use the path ../ as the data directory the script download_and_untar.sh crashes. There are 2 lines that change to the $data directory. This makes the current directory jump up 2 levels when the data directory is ../.
The file is:
egs/mini_librispeech/s5/local/download_and_untar.sh

**Comment by danpovey** [comment]
@desh2608 could you look at it and maybe fix it?

**Comment by desh2608** [comment]
Fixed in PR https://github.com/kaldi-asr/kaldi/pull/2689
