### ISSUE TITLE
Why we need final tokens?

### ISSUE THREAD

**Issue by studyself** [kaldi-asr/kaldi#2729]
Hi All,

What is a final token? 
Is it a kind of token corresponding to non-emitting state, state 3, which has final-probability one, in HmmTopology?
Sorry that, i am not familiar with WFST. 
Before my diving into WFST, could you give me some top level views of designing principles of "final tokens" and  "final probs"?
Will the decoding results be different when I cut off the utterance at any frame before the last frame is reached?

Quinn

-------------------------- I am asking questions about codes below:
      BaseFloat final_cost = fst_.Final(state).Value() +
          lm_diff_fst_->Final(lm_state).Value();
......
......
        if (final_active_) {
          BaseFloat final_cost = tok_to_final_cost[tok];
          tok_extra_cost = (tok->tot_cost + final_cost) - best_cost_final;
        } else 
          tok_extra_cost = tok->tot_cost - best_cost_nofinal;

**Comment by danpovey** [comment]
replied on kaldi-help
