### ISSUE TITLE
Issue in Flags in the file kaldi/egs/wsj/s5/steps/tfrnnlm/vanilla_rnnlm.py

### ISSUE THREAD

**Issue by ervaibhavkumar** [kaldi-asr/kaldi#2732]
There are some issues with the flags specified in the file from line number 41 to line number 49 . 
This issue needs to be addressed 

Please assign this to me.

**Comment by danpovey** [comment]
Thanks!  I don't think I can assign without messing with membership, but
I'll leave it open until you make a PR.

**Comment by ervaibhavkumar** [comment]
@danpovey PR has been made with PR number as #2733

**Comment by hainan-xv** [comment]
Hmm, why is the old code problematic? I used the "-" character throughout the tfrnnlm setup, including the recipe scripts that use those RNNLM training scripts, as in https://github.com/kaldi-asr/kaldi/blob/master/egs/ami/s5/local/tfrnnlm/run_vanilla_rnnlm.sh

**Comment by ervaibhavkumar** [comment]
@hainan-xv When i ran the script vanilla_rnnlm.py directly . It gave error regarding the Flags. 
So I thought of making the changes. Afterwrads it was running fine with the changes that had been proposed.
