### ISSUE TITLE
Potential Make issue

### ISSUE THREAD

**Issue by calderma** [kaldi-asr/kaldi#2734]
using g++ 4.8.4 on ubuntu 14.04.5 when I attempt to make the Tools directory it fails and spits out the message about my compiler version needing to be >= 4.8.3. This appears to be because the check in extras/check_dependencies.sh uses g++ -dumpversion on line 32 which does not output the patch number of g++ so the GCC_VER is set to 4.8 here instead of 4.8.4:
32. GCC_VER=$($CXX -dumpversion)
If i change it so that it ignores the change to status=1 under that then everything compiles fine and the Makefile doesn't complain. which g++ and g++ --version output the expected version of 4.8.4 so I don't think it's a path issue. This could be something specific to my setup but I figured I'd bring it to your attention.

**Comment by danpovey** [comment]
Thanks for reporting it.  But I've never heard of another instance where it doesn't print the patch number.  Wherever I've tested it, it does.  I suspect it may be a problem with the package you are using.   If we hear of this being a common problem (or if it happens on  more recent distros) we'll address it.
