### ISSUE TITLE
Cuda 10 support

### ISSUE THREAD

**Issue by leomao** [kaldi-asr/kaldi#2743]
Cuda 10 was released. The support gencode values are:
```
'compute_30','compute_32','compute_35',
'compute_37','compute_50','compute_52','compute_53','compute_60','compute_61',
'compute_62','compute_70','compute_72','compute_75','sm_30','sm_32','sm_35',
'sm_37','sm_50','sm_52','sm_53','sm_60','sm_61','sm_62','sm_70','sm_72','sm_75'.
```

**Comment by danpovey** [comment]
Thanks.
If you want to try to get Kaldi to compile with CUDA 10, and maybe make the
changes to the Makefile and configure script to get it to work, I'd look at
your PR.  Until someone has got it to compile and run, we won't know if
additional things need to be done.
Dan
