### ISSUE TITLE
how to convert x-vector.ark to text

### ISSUE THREAD

**Issue by cageyoko** [kaldi-asr/kaldi#2756]
I want to use the x-vector by my backend classifier 
but i don't know how to get the x-vector matrix because x-vector.ark is binary..

what script can do it? ..

thanks!

**Comment by entn-at** [comment]
For questions like this it's better to ask in the group: https://groups.google.com/forum/#!forum/kaldi-help

That said, use `bin/copy-vector`, e.g., `copy-vector --binary=false ark:xvector.ark ark,t:xvector.txt `

Here is some more general info on IO: http://kaldi-asr.org/doc/io_tut.html
