### ISSUE TITLE
Issue In kaldi/egs/ami/s5/local/ami_download.sh

### ISSUE THREAD

**Issue by ervaibhavkumar** [kaldi-asr/kaldi#2766]
Hi,

I have found issue in the file fetched by command wget in the file kaldi/egs/ami/s5/local/ami_download.sh
I would like to work on it .
Can i start on this ?

Regards
Vaibhav

**Comment by danpovey** [comment]
Sure, but let us know what the issue is first.  It might just be a firewall
problem.

**Comment by puneetbawa** [comment]
The URL was pointing to file which doesn't exist . I had resolved in in #2769

**Comment by ervaibhavkumar** [comment]
@puneetbawa I think these resolves the issue 👍
