### ISSUE TITLE
I got an exception 'object of type 'map' has no len()' ,and the error can be found as flowing exception

### ISSUE THREAD

**Issue by ZerRui** [kaldi-asr/kaldi#2770]
egs/sre16/v2/steps/data
Traceback (most recent call last):
  File "steps/data/reverberate_data_dir.py", line 659, in <module>
    Main()
  File "steps/data/reverberate_data_dir.py", line 627, in Main
    rir_list = ParseRirList(args.rir_set_para_array, args.rir_smoothing_weight, args.source_sampling_rate)
  File "steps/data/reverberate_data_dir.py", line 533, in ParseRirList
    rir_list += SmoothProbabilityDistribution(current_rir_list, smoothing_weight, rir_set.probability)
  File "steps/data/reverberate_data_dir.py", line 449, in SmoothProbabilityDistribution
    if len(list) > 0:
TypeError: object of type 'map' has no len()

**Comment by ZerRui** [comment]
map python2

**Comment by danpovey** [comment]
@david-ryan-snyder, would you mind making a PR to fix this?  Likely a python3 compatibility issue where something needs to be converted explicitly to list with `list(x)`.   Sorry, I think you are by default the owner of this reverberation stuff for now, even though you didn't write all of it.

**Comment by david-ryan-snyder** [comment]
Sure, NP.

**Comment by david-ryan-snyder** [comment]
@ZerRui this should work for you once https://github.com/kaldi-asr/kaldi/pull/2771 is merged.
