### ISSUE TITLE
fstrand.cc missing po.Read

### ISSUE THREAD

**Issue by sdrobert** [kaldi-asr/kaldi#2773]
https://github.com/kaldi-asr/kaldi/blob/a7026219e17e3d29b8247c37c8e487ab3b0ea084/src/fstbin/fstrand.cc#L46

As you can see, fstrand is not actually reading the arguments.

Best,
Sean

**Comment by danpovey** [comment]
Oh, yes.  There is a statement missing, po.ReadArgs() or something like that.  @huangruizhe would you mind fixing this?

**Comment by huangruizhe** [comment]
Ok. I will look into it.
