### ISSUE TITLE
Minor issue in nnet2/train_tanh_fast.sh

### ISSUE THREAD

**Issue by Umar17** [kaldi-asr/kaldi#2782]
On line 171 of steps/nnet2/train_tanh_fast.sh:
`[ ! -z "$online_ivector_dir" ] && extra_opts+=(--online-ivector-dir $online_ivector_dir)`
but _$online_ivector_dir_ neither defined anywhere above nor got through arguments. Will it not be empty all the times?
Secondly, if someone wants to use train_tanh_fast with ivector training, should them hard code the path  of online_ivector_dir in the script?

**Comment by danpovey** [comment]
Sorry, this script is very old and deprecated, I don't think I am going to fix it.
