### ISSUE TITLE
issue in steps/nnet3/train_raw_dnn.py

### ISSUE THREAD

**Issue by yuzhoushenling** [kaldi-asr/kaldi#2783]
I want to run train_raw_dnn.py, and set use-dense-targets=false, but i don't know the format of targets-scp, please help me.

**Comment by vimalmanohar** [comment]
I added documentation in #2785. See egs/aspire/s5/local/nnet3/run_autoencoder.sh or egs/swbd/s5c/local/segmentation/tuning/train_stats_asr_sad_1a.sh for examples. 
You can ask questions in the google groups as suggested in http://kaldi-asr.org/forums.html.

**Comment by yuzhoushenling** [comment]
In run_autoencoder.sh and train_stats_asr_sad_1a.sh, the parameter use-dense-targets is true but I set it to false.  
I create a label file in which the line contains utterance_id and phoneme list, such as xxx_id 12 23 12 1 12. Then I use src/featbin/copy-feats to create a scp file and ark file, and I assign this scp file for the paramter targets-scp in the train_raw_dnn.py. But after I run train_raw_dnn.py, it show that ERROR (ali-to-post[5.5.19~4-c4020]:ReadBasicType():base/io-funcs-inl.h:74) ReadBasicType: did not get expected integer type, 67 vs. 4.
My English is poor, hope you can understand.

**Comment by kkm000** [comment]
This kind of questions is really better suited for http://kaldi-asr.org/forums.html.

I am closing this ticket for now. If you believe that your issue has not been addressed, please feel free to ping me, and I'll reopen it.
