### ISSUE TITLE
i-vector=?

### ISSUE THREAD

**Issue by 313024351** [kaldi-asr/kaldi#2798]
i trained i-vector using nnet/ivector's file.
but faled put it in nnet/train.sh's ivector=
as fllow 
# Train
  steps/nnet/train.sh --network-type lstm --learn-rate 0.00004 \
    --cmvn-opts "--norm-means=true --norm-vars=true" \
    --ivector "scp:exp/ivectors_train/ivectors_spk-as-utt.scp" \
    --delta-opts "--delta-order=2" --feat-type plain --splice 0 \
    --scheduler-opts "--momentum 0.9 --halving-factor 0.5" \
    --train-tool "nnet-train-multistream-perutt" \
    --train-tool-opts "--num-streams=10 --max-frames=15000" \
    --proto-opts "--cell-dim 320 --proj-dim 200 --num-layers 2" \
  ${train}_tr90 ${train}_cv10 data/lang $ali $ali $dir || exit 1;

and the error:
The input-dim is 139, the data had 39 dims.
why? how i use the i-vector to put in the nnet/train.sh?

**Comment by danpovey** [comment]
I don't believe we have any nnet1 example scripts for use with ivectors.  In any case, I don't respond to questions about nnet1.  You should stay closer to the example scripts.
