### ISSUE TITLE
How to extract features for a single .wav file

### ISSUE THREAD

**Issue by robi56** [kaldi-asr/kaldi#2803]
At inference time, I need to extract speech features from a single .wav file. How it will be possible?
The conversion steps:
.Wav file-> compute-fbank-feats and compute-kaldi-pitch-feats-> compute-cmvn-> normalize-> features 

The same task is done by the make_fbank_pitch.sh file but it works on a directory after completing data_processing steps in kalidi.

**Comment by danpovey** [comment]
The best way to do that is to look at the log files that make_fbank_pitch.sh produced, and adapt the commands in there.  Once you understand how Kaldi I/O works, it should be straightforward.  Search for the doc page on "Kaldi I/O from a command line perspective".
