### ISSUE TITLE
problem with lattice-align-words-lexicon

### ISSUE THREAD

**Issue by yangsuxia** [kaldi-asr/kaldi#2808]
Hi ,
     When I use  lattice-align-words-lexicon,I got the following problem.
```
WARNING (lattice-align-words-lexicon[5.4.231~1-287e2]:WordAlignLatticeLexicon():word-align-lattice-lexicon.cc:1015) [Lattice has input epsilons and/or is not input-deterministic (in Mohri sense)]-- i.e. lattice is not deterministic.  Word-alignment may be slow and-or blow up in memory.
WARNING (lattice-align-words-lexicon[5.4.231~1-287e2]:ProcessFinalWrapper():word-align-lattice-lexicon.cc:252) No final-probs to process. 
WARNING (lattice-align-words-lexicon[5.4.231~1-287e2]:main():lattice-align-words-lexicon.cc:108) Algorithm produced no output (due to --max-expand?), so passing input through as output, for key King_WindowsMobile_Speaker0414_0215
LOG (lattice-align-words-lexicon[5.4.231~1-287e2]:main():lattice-align-words-lexicon.cc:138) Successfully aligned **528 lattices; 6856 had errors.** 
LOG (lattice-1best[5.4.231~1-287e2]:main():lattice-1best.cc:103) Done converting 7384 to best path, 0 had errors.
```

     Why do I get empty alignment?

**Comment by danpovey** [comment]
I suspect there is either a mismatch (i.e. you didn't use the correct input to that program, e.g. from the wrong lang/ dir), or there is something unusual about how you are getting the input lattices or  how you are applying it.  Hard to know exactly what that might be.

**Comment by yangsuxia** [comment]
Thank you very much for your reply.
I have 300,000 pieces of data, nearly two-thirds of which produce empty results, and one-third produce results that are not empty. If it doesn't match, why aren't they all empty?

**Comment by danpovey** [comment]
Some of the word-ids might have been the same as when you generated the
lattices, and some different.  There are a lot of potential reasons.

**Comment by yangsuxia** [comment]
Thank you very much for your reply.
I had this problem when I clean up the data. If I set the parameter -- output - if - empty to true and generated ctm, would that affect my cleaning up of the data?

**Comment by danpovey** [comment]
Update your repository and re-run that.  I seem to remember we fixed a bug
in that script not long ago.

**Comment by yangsuxia** [comment]
Well, yes, thank you. I'll update the latest version.

**Comment by v-yunbin** [comment]
@danpovey  when i use "lattice-align-words-lexicon.", get inconsistent  alignment results with real wav.
1. real wav, duration is about 10 seconds:
![73B5DE50-421E-4152-9740-565A780EAF4E](https://user-images.githubusercontent.com/38179632/63847174-d02c2000-c9bf-11e9-84df-93a35271b4c4.png)
2. aligment result:
xxx_D11_750.wav 1 0.320 0.190 东北军
xxx_D11_750.wav 1 0.510 0.030 的
xxx_D11_750.wav 1 0.540 0.130 一些
xxx_D11_750.wav 1 0.670 0.120 爱国
xxx_D11_750.wav 1 0.790 0.190 将士
xxx_D11_750.wav 1 1.060 0.260 马占山
xxx_D11_750.wav 1 1.410 0.100 李
xxx_D11_750.wav 1 1.510 0.100 杜
xxx_D11_750.wav 1 1.650 0.090 唐
xxx_D11_750.wav 1 1.740 0.060 聚
xxx_D11_750.wav 1 1.800 0.100 伍
xxx_D11_750.wav 1 2.000 0.100 苏
xxx_D11_750.wav 1 2.100 0.060 炳
xxx_D11_750.wav 1 2.160 0.110 艾
xxx_D11_750.wav 1 2.350 0.070 邓
xxx_D11_750.wav 1 2.420 0.070 铁
xxx_D11_750.wav 1 2.490 0.060 梅
xxx_D11_750.wav 1 2.550 0.090 等
xxx_D11_750.wav 1 2.700 0.060 也
xxx_D11_750.wav 1 2.760 0.160 奋起
xxx_D11_750.wav 1 2.920 0.180 抗战

**Comment by jtrmal** [comment]
are you using a proper frame-skip factor if you have a chain model?
y.

**Comment by v-yunbin** [comment]
@jtrmal command is as follows: 
`lattice-align-words-lexicon data/lang_chain/phones/align_lexicon.int  exp/chain/tdnn_1a_sp/final.mdl "ark:gunzip -c temp/out/lat.1.gz|" ark:- | lattice-1best ark:- ark:- |  nbest-to-ctm ark:- temp/out/align.ctm`

**Comment by danpovey** [comment]
You need to set --frame-shift=0.03 to nbest-to-ctm, probably.
