### ISSUE TITLE
clear dependencies between modules

### ISSUE THREAD

**Issue by yzmyyff** [kaldi-asr/kaldi#2810]
I' m working on a bazel project using kaldi. I found there are not clear dependencies between modules when I wrote the build rules. such like 

lat/lattice-function.h include hmm/hmm-utils.h.
hmm/hmm-utils.h include lat/kaldi-lattice.h

**Comment by danpovey** [comment]
Actually the intention was always to have one-way dependencies between
those sub-directories in terms of linking, at least (and preferably also in
terms of includes, although this does not seem to be the case in this
particular instance).
The dependencies are one-way in terms of what has to be linked.  It looks
like the dependencies are not one-way from an "include" perspective.  For
our purposes it doesn't really matter though.  I think Daniel is right that
it would probably be better to just use Kaldi's own build system, if
possible.

Dan

**Comment by yzmyyff** [comment]
Thanks, depending on static libs may solve my problem.

**Comment by danpovey** [comment]
It wouldn't matter even for dynamic libs, the library dependencies are not
circular, check the Makefile.
