### ISSUE TITLE
any plans about depthwise separable convolution?

### ISSUE THREAD

**Issue by Cescfangs** [kaldi-asr/kaldi#2812]
`depthwise separable convolution` could  dramatically reduce computation cost, which is necessary for mobile and embeded device, any plans for kaldi to support `depthwise separable convolution`?

**Comment by danpovey** [comment]
We don't have any immediate plans for that, and probably won't until there is some indication that that type of convolution

**Comment by danpovey** [comment]
sorry: that that type of convolution is useful for ASR.

**Comment by Cescfangs** [comment]
Okay then
