### ISSUE TITLE
Create get_ctm_conf.sh

### ISSUE THREAD

**Issue by danpovey** [kaldi-asr/kaldi#2826]
need a script like get_ctm.sh which also includes confidences.

 https://groups.google.com/d/msgid/kaldi-help/CAFReZQaEd3hHNE1wRu0oiisv4RTzdSRP_bB5FxFd1TnvEw%3DOMw%40mail.gmail.com.

**Comment by danpovey** [comment]
@xiaohui-zhang do you have time for this?

**Comment by xiaohui-zhang** [comment]
sure！

**Comment by vimalmanohar** [comment]
This file is already in aspire. It should be moved to steps/conf.
https://github.com/kaldi-asr/kaldi/blob/master/egs/aspire/s5/local/multi_condition/get_ctm_conf.sh

**Comment by danpovey** [comment]
Oh, cool.

But let's make a soft link steps/get_ctm_conf.sh -> conf/get_ctm_conf.sh.

And make sure the script has adequate input-checking and documentation; and
be sure to have get_ctm.sh and get_ctm_fast.sh reference that script (e.g.
"See also: ") in their usage messages and, if applicable, in the comment at
the top of those files.


Dan

**Comment by xiaohui-zhang** [comment]
done

**Comment by svenha** [comment]
Thanks for the new script! Can this be generalized to (optionally) output the lattice with confidences? Maybe this is already covered by an old script (if so, which one?) or an idea for another script.

**Comment by danpovey** [comment]
Addressed in #2828
