### ISSUE TITLE
Wrong rescoring binary for tfrnnlm

### ISSUE THREAD

**Issue by ervaibhavkumar** [kaldi-asr/kaldi#2833]
Hi, 
When i was running through the script 
https://github.com/kaldi-asr/kaldi/blob/master/egs/wsj/s5/steps/lmrescore_rnnlm_lat.sh

The lattice rescoring binary is wrong. 
I want to work on this.
Should I proceed ?

Regards
Vaibhav

**Comment by danpovey** [comment]
Thanks-- let's try to resolve this by email with Hainan.  If it turns out to be a bug you can definitely make a PR.
