### ISSUE TITLE
Incorrect rescoring Binary used

### ISSUE THREAD

**Issue by ervaibhavkumar** [kaldi-asr/kaldi#2834]
Hi,

When i was running the script https://github.com/kaldi-asr/kaldi/blob/master/egs/ami/s5/local/tfrnnlm/run_vanilla_rnnlm.sh.

It was calling the wrong script for rescoring.
Should i proceed for a PR ?

Regards
Vaibhav

**Comment by danpovey** [comment]
I'm still not sure, based on our email conversation, whether there was really a problem; please figure it out by email with Hainan and if there is a problem, make a PR.  But I'm closing this issue in the interim-- please just make a PR if there was a problem.

**Comment by ervaibhavkumar** [comment]
@danpovey I was talking about this in #2892

**Comment by danpovey** [comment]
OK, you can go ahead and make a PR.  We don't really use that setup much, but it would be good to have a fix.

**Comment by ervaibhavkumar** [comment]
I will.
But can i know which setup you use ?

**Comment by danpovey** [comment]
The Kaldi-native RNNLM tools; look in egs/swbd/s5c/local/rnnlm/ for an
example.  Please don't ask quetions on github; they should go to
kaldi-help, but search online first.
