### ISSUE TITLE
why using online_ivector_dir= in the train_tanh_fast.sh?

### ISSUE THREAD

**Issue by 313024351** [kaldi-asr/kaldi#2841]
it is working on speaker adaption or else?

**Comment by 313024351** [comment]
> The ivectors are provided as an auxiliary input to help with speaker adaptation. See kaldi-asr.org/forums.html for how to ask questions.

Thank you.But what is the theory？Do i have some paper to read?

**Comment by danpovey** [comment]
There isn't a very useful theory.  Search online for some kind of introduction to i-vectors for speaker recognition.  Many people have tried adding ivectors to the features but it's an empirical thing.  Ask on the list next time.
