### ISSUE TITLE
Latency-Controlled CLDNN Net

### ISSUE THREAD

**Issue by wqn628** [kaldi-asr/kaldi#2849]
Hello，
Is there any stable kaldi nnet3 recipe with Latency-Control cldnn acoustic model ?

**Comment by GaofengCheng** [comment]
http://www.danielpovey.com/files/2017_spl_tdnnlstm.pdf
TDNN-LSTM is stable and good performance.

**Comment by wqn628** [comment]
Ok. thank you very much,
Is there Latency-Control cldnn acoustic model for acoustic model?

**Comment by danpovey** [comment]
No there isn't; I recommend the TDNN+LSTM.
