### ISSUE TITLE
TImer.cc change breaks windows build

### ISSUE THREAD

**Issue by btiplitz** [kaldi-asr/kaldi#2852]
In timer.cc:81, the destructor for Profiler fails as this does not exist on windows

**Comment by danpovey** [comment]
@huangruizhe can you please make a PR to fix this?  Ask someone for help if you don't know how.

**Comment by huangruizhe** [comment]
ok

**Comment by btiplitz** [comment]
@huangruizhe any progress.  I could make a PR myself it that helps.  I see 2 other problems on the windows side.  1 is uint8, etc is undefined.  We seem to have a fix for that I blew away when merging.  I also have another error I'm investigating (all for windows only)

**Comment by huangruizhe** [comment]
@btiplitz Thanks for the reminder and patience! I am new to this and I am working on it, and hopefully will deliver it today.
