### ISSUE TITLE
configure version should increment

### ISSUE THREAD

**Issue by btiplitz** [kaldi-asr/kaldi#2853]
commit 741b75b474a03a584e64dec36e96a47bcc2a1117 updated the script to incorporate the CUDA cub library which requires a new configuration.  It seems like 
CONFIGURE_VERSION=9
should now be 10

**Comment by danpovey** [comment]
@keli78 please make this change (just change CONFIGURE_VERSION) in kaldi.mk.  Reference this issue number in the PR by adding (#2853) to the line.

**Comment by keli78** [comment]
Hi Dan @danpovey  I think I should change CONFIGURE_VERSION to 10 in the configure file in /src since it generates the kaldi.mk right? And should I run some test for this change?

**Comment by danpovey** [comment]
Oh- yes, you're right: in configure.  No need to test it.
