### ISSUE TITLE
commonvoice/s5/local/prepare_dict.sh uses wrong path to sequitur

### ISSUE THREAD

**Issue by vvasily** [kaldi-asr/kaldi#2867]
commonvoice/s5/local/prepare_dict.sh uses the following path to sequitur:
sequitur=$KALDI_ROOT/tools/sequitur

But now sequitur is installed as $KALDI_ROOT/tools/sequitur-g2p. So, it should be:
sequitur=$KALDI_ROOT/tools/sequitur-g2p

**Comment by danpovey** [comment]
Thanks.  Can you please make a pull request?

**Comment by vvasily** [comment]
Yes, I have created it.

**Comment by kkm000** [comment]
Fixed in #2868
