### ISSUE TITLE
[RNNLM] old iteration model cleanup

### ISSUE THREAD

**Issue by slckl** [kaldi-asr/kaldi#2869]
When training acoustic models with Kaldi, e.g., with chain, there's a cleanup step (in train.py for chain, for example), which removes all but the last two trained models. Am I correct that there is no such cleanup step in any of the training scripts for rnnlm?

This has caused problems for us, where training a large model with lots of iterations causes us to run out of space.

If there is no such thing, I can create a PR for this as an option (similar to how it works for chain train.py) and the necessary fixes for related files which rely on there being models for all iterations.

**Comment by danpovey** [comment]
It's a great idea to do that-- yes please.
