### ISSUE TITLE
ComputeFeatures wrapper breaks windows

### ISSUE THREAD

**Issue by btiplitz** [kaldi-asr/kaldi#2879]
In feat/feature-common-inl.h the function OfflineFeatureTpl<F>::ComputeFeatures at about line 60 does not seem to be used, but when this exists, the windows build fails.  There does not appear to be a ComputeFeatures function with the 3 arguments required and windows figures this out (though it's never used to linux does not seem to care)

I commented it out on linux and built successfully without this wrapper, so perhaps the code is old

**Comment by danpovey** [comment]
Thanks-- I'll make a PR to remove it, assuming it all compiles fine.

**Comment by btiplitz** [comment]
I can submit a PR if you would like ?

**Comment by danpovey** [comment]
It's OK thanks, I'm already testing one.
