### ISSUE TITLE
replace dnn with cnn

### ISSUE THREAD

**Issue by 313024351** [kaldi-asr/kaldi#2902]
Firstly,Can we replace dnn with cnn that trained with mfcc in the file "extract_ivectors_dnn.sh"?
Secondly,If so,what is the generally step?
thirdly,I try it ,but it show "cnn need 39 dim feat,but you have 13"and the cnn trained with mfcc that was created with  make_mfcc.sh. What am I supposed to do?
thanks.

**Comment by danpovey** [comment]
I believe it means DNN in a generic sense, it's probably using a TDNN which is == 1-D CNN.  But also those are old, nnet2-based recipes that are deprecated; search for xvector to see our more recent recipes.   Also see kaldi-asr.org/forums.html for how to ask questions, this is not the right place.
