### ISSUE TITLE
 same wav has different results use"compute-mfcc-feats "

### ISSUE THREAD

**Issue by xgp0602** [kaldi-asr/kaldi#2904]
step1
$cat test.scp
1.wav 1.wav
1.wav 1.wav

step 2
 $compute-mfcc-feats scp:test.scp ark,t:-
1.wav  [
  8.624476 -36.99769 -10.14224 4.165749 -15.5063 -3.841846 -13.39886 -14.40349 1.999721 -7.6442 -21.7872 1.339085 -9.795901 ......
]
1.wav  [
  8.685931 -34.99401 -6.010984 6.777715 -16.93279 0.1244533 -2.13366 -10.40063 -2.038845 -10.09831 -15.8944 9.854256 -5.9527 ......
]
Why the same wav has different results

**Comment by danpovey** [comment]
This question has been asked many times on the list, do a google search.

**Comment by xgp0602** [comment]
can you give me keywords to search ,thinks

**Comment by danpovey** [comment]
I thought you might be smart enough to figure it out yourself, but I guess not.
I tried putting in the terms from your issue itself, with "kaldi" into Google:
```
same wav different results kaldi
```
and I got a relevant hit.
