### ISSUE TITLE
randomness in nnet3 training,

### ISSUE THREAD

**Issue by vesis84** [kaldi-asr/kaldi#2905]
Hi Dan, Yenda,
I'd like to ask about one characteristic of nnet3 training.

Recently we had some problems with re-running the experiments,
in which we were getting little different results each time.

I tried to track the issue. There are several spots, that are interesting to look at.

a) INITIALIZATION
I noticed that the initial weights are generated the same due to the seed,
but different from those generated on September 25th.
(could be a glibc/cuda/kaldi update, this is probably not possible to track down)

b) DATA STREAM
Then I checked the the training data which come into the training tool.
Here, it was okay. The egs were prepared the same way.
And the on-the-fly generated data stream was identical when run 2x in a row.

c) TRAINING TOOL
Here I tried to do 2 sequential runs of the 1st invocation of the training tool 'nnet3-chain-train'.
This was done with same data on the same server and GPU and with the same seed and nn initializaion. 

I have noticed that the models are not identical.
The difference is small, but there is the difference.

Is this expected?

I tried to set the '--leaky-hmm-coefficient=0', but this seems not to be supported.

Are there any other 'random'-related options in the code that I could try to disable?

Thank you,
Karel

**Comment by danpovey** [comment]
I don't think any randomness is coming from the Kaldi code itself, I think
it's from the inherent nondeterminism of GPU-based matrix multiplication.
At least that's my belief.  Of course, different architectures and
optimization methods may be more or less sensitive to the effects of this.

**Comment by vesis84** [comment]
Okay, I'll continue looking into it and do some tests... Let's see :)
