### ISSUE TITLE
CTC- some optimizations

### ISSUE THREAD

**Issue by danpovey** [kaldi-asr/kaldi#291]
@freewym, it would be good if you could help with this, with help from @vijayaditya.

Actually this relates to the 'tombstone' branch, which is in my personal repository, but I think you should be able to make a pull request to there.
If you do
cat /home/dpovey/kaldi-tombstone/egs/swbd/s5c/exp/ctc/tdnn_a/log/train.100.3.log
you will see that a fair amount of time is spent in Tensor3dCopy, see
Tensor3dCopy    8.79502s
If you learn a bit about CUDA, you'll see that memory access is best when threads in a thread block access sequential memory locations.   In the Tensor3dCopy function, this means that if the x stride is 1, it will be most efficient, because x maps to the thread index.
I'd like you to add to the top of that function, code like the following:
  if (the x stride is not 1 but the y or z stride is 1) {
    swap the x stride and dim with whichever other index has stride 1.
 }
I'd also like you to change the CPU version of the code so that instead of iterating over x, y, z it iterates over z, y, x.  This will make it more efficient if the x stride is 1, for memory-locality reasons.

**Comment by freewym** [comment]
Will take it.

Yiming
