### ISSUE TITLE
Can't understand ScalarClusterable::objf function in Decision tree building process

### ISSUE THREAD

**Issue by mahuichao** [kaldi-asr/kaldi#2914]
Hello,when I see the source code of kaldi about decision tree (questions obtained),I saw the function Objf() as follows:
`BaseFloat ScalarClusterable::Objf() const {
  if (count_ == 0) {
    return 0;
  } else {
    KALDI_ASSERT(count_ > 0);
    return -(x2_ - x_ * x_ / count_);
  }
}`
I don't know what thing this function do, any theory about -(x2_ - x_ * x_ /count_)?
thanks

**Comment by mahuichao** [comment]
didn't see the head file.

**Comment by csukuangfj** [comment]
The objective function is to maximize the negated sum of squared distances from the cluster center to each scalar.

To give you an example, if we have three scalars: `a`, `b`, `c`, we have
 - `x = a + b + c`
 - `x^2 = a^2 + b^2 + c^2`

The goal is to maximize `-(x^2 - x*x/3)`, which is computed from
`-1 * ((a - (a+b+c)/3)^2 + (b - (a+b+c)/3)^2 + (c - (a+b+c)/3)^2)`

In the above formula, the cluster center is `(a+b+c)/3`
- the squared distance between `a` the the cluster center is `(a - (a+b+c)/3)^2`
- the squared distance between `b` the the cluster center is `(b - (a+b+c)/3)^2`
- the squared distance between `c` the the cluster center is `(c - (a+b+c)/3)^2`

It is straightforward to get the formula for `n` scalars, which is exactly
```
x^2 - x*x/n
```
