### ISSUE TITLE
x-vector 

### ISSUE THREAD

**Issue by 313024351** [kaldi-asr/kaldi#2915]
How can i get x-vector through .sh?
for example
i-vector:train_umb.sh ->train_ivecotr_extract.sh->extract_ivecotr.sh
And what is the x-vector's steps?

**Comment by danpovey** [comment]
This question is too generic.

**Comment by MuruganR96** [comment]
Sir You can download  a pretrained x-vector model from this link
http://kaldi-asr.org/models/3/0003_sre16_v2_1a.tar.gz
Once you unzip the file you will get pretrained kaldi speaker recognition
model which can be used to extract x-vectors for any audio file.
