### ISSUE TITLE
vtln+ivector decode

### ISSUE THREAD

**Issue by 313024351** [kaldi-asr/kaldi#2918]
I want to decode through VTLN model and i-vecotr model.
How do I achieve it?
I don't see any "decode.sh" that has vtln+ivecotr.
thanks.

**Comment by danpovey** [comment]
We don't have any recipe that uses both of  those things.

**Comment by danpovey** [comment]
I don't believe the nnet2 recipes support training on adapted features.  Anyway, the short answer is that if you have to ask, you probably wouldn't be able to do it.

**Comment by EmreOzkose** [comment]
Hi @313024351 , Can you share decoding script if you was able to achieve any decoding with VTLN? (or any guidance, please :))
