### ISSUE TITLE
'chain' code - a piece I need help with.

### ISSUE THREAD

**Issue by danpovey** [kaldi-asr/kaldi#292]
The 'tombstone' stuff, which is an extension of CCTC, is working quite well, but I am realizing that the model can be implemented much more simply as 'almost' a conventional hybrid system, but one that's trained discriminatively from the start without lattices-- and the training procedure is a significant simplification of the 'tombstone CCTC' training stuff I have in my personal repo.  That stuff seems to be working well, but it's unnecessarily complicated.

I am starting work on this.  I am calling it the 'chain' model... actually it's a kind of simplification of a hybrid HMM-DNN system, where the system is trained discriminatively from the start.  The word 'chain' is chosen as it's a synonym for 'sequence', and the model is effectively a sequence model as that's how it's trained.  I want this to be done, if possible, within a week.  Perhaps this will become the 'next version' of high-performance models in Kaldi, instead of CTC.

I have pushed to my personal copy of Kaldi, the branch 'chain'; see git@github.com:/danpovey/kaldi.git.

This 'issue' is to do the implementation of what I've created the interface for in phone-topology.h.  @naxingyu, do you have time for this right now?  It involves some work with FSTs (nothing too complicated).

**Comment by naxingyu** [comment]
Yes. But I don't have exprience playing with the FST code. I'll have a 
look at your branch tomorrow.

Xingyu

在 2015/10/25 7:09, Daniel Povey 写道:

**Comment by danpovey** [comment]
They have a tutorial at OpenFst.org that is quite good at teaching you the
basics.

For I/O you can use the following functions:

void WriteFstKaldi(std::ostream &os, bool binary,
                   const VectorFst<Arc> &fst);

void ReadFstKaldi(std::istream &is, bool binary,
                  VectorFst<Arc> *fst);
[from fstext/kaldi-fst-io.h]

Dan
