### ISSUE TITLE
copy-feats: command not found

### ISSUE THREAD

**Issue by bar13290** [kaldi-asr/kaldi#2920]
Hi, I go over the tutorial on the kaldi documentation, and while I run the command:
"**_copy-feats ark:mfcc/raw_mfcc_train_yesno.1.ark ark,t:- | head_**",  I have got an error:
"**_copy-feats: command not found_**"

- I run this command from the s5 library.
- The script run.sh is working good with no errors.
- I use the path.sh before, and I checked the path of the kaldi root  in it
- I use clang 6.0
- all the commands that use the copy-feats function, get the same error.

I would like to get some help with this problem.

Thanks!

**Comment by danpovey** [comment]
It's a path issue.  You need to source path.sh:
```
. ./path.sh
```

**Comment by jtrmal** [comment]
Dan didn't say run -- he said source. That is a different thing
cf.
./path.sh
vs
. ./path.sh (or source ./path.sh)

Please do not post any follow-up here, this is hardly a bug. We have a
mailing list for user support.
y.

**Comment by linzhongzi** [comment]
copy-feats.exe， complie and build this， make sure it in the path
