### ISSUE TITLE
cu-kernels.cu function calling problem

### ISSUE THREAD

**Issue by aaronlyt** [kaldi-asr/kaldi#2922]
### environment:
  system: ubuntu 16.04
  cuda  V9.0.176
  gcc 5.5.0  

### problem:

cu-kernels.cu(2321): error: calling a __host__ function("__builtin_isnan") from a __global__ function("_group_pnorm<float> ") is not allowed

cu-kernels.cu(2386): error: calling a __host__ function("__builtin_isinf") from a __global__ function("_tanh<float> ") is not allowed

cu-kernels.cu(2321): error: calling a __host__ function("__builtin_isnan") from a __global__ function("_group_pnorm<double> ") is not allowed

cu-kernels.cu(2386): error: calling a __host__ function("__builtin_isinf") from a __global__ function("_tanh<double> ") is not allowed

4 errors detected in the compilation of "/tmp/tmpxft_0000591b_00000000-13_cu-kernels.compute_70.cpp1.ii".
--error 0x1 --
Makefile:32: recipe for target 'cu-kernels.o' failed
make[2]: *** [cu-kernels.o] Error 1

**Comment by danpovey** [comment]
Likely your gcc is too old for that version of CUDA.
