### ISSUE TITLE
cu-kernels.cu  Unsupported .version 

### ISSUE THREAD

**Issue by aaronlyt** [kaldi-asr/kaldi#2923]
### environment:

system: ubuntu 16.04
cuda V9.0.176
gcc 6.5.0

### error happen time
in src fold:
  
  ./configure is ok
 error happen in  make  -j 4 CXX=~/gcc-6.5.0/bin/g++

### error description
/home/lyt/gcc-5.2.0/bin/g++ -std=c++11 -I.. -isystem /home/lyt/software/kaldi/tools/openfst/include -O1  -Wall -Wno-sign-compare -Wno-unused-local-typedefs -Wno-deprecated-declarations -Winit-self -DKALDI_DOUBLEPRECISION=0 -DHAVE_EXECINFO_H=1 -DHAVE_CXXABI_H -DHAVE_ATLAS -I/home/lyt/software/kaldi/tools/ATLAS_headers/include -msse -msse2 -pthread -g  -DHAVE_CUDA -I/usr//include   -c -o full-gmm-normal.o full-gmm-normal.cc
#$ ptxas -arch=sm_30 -m64 "/tmp/tmpxft_000026dc_00000000-12_cu-kernels.compute_30.ptx"  -o "/tmp/tmpxft_000026dc_00000000-15_cu-kernels.compute_30.cubin"
ptxas /tmp/tmpxft_000026dc_00000000-12_cu-kernels.compute_30.ptx, line 9; fatal   : Unsupported .version 6.1; current version is '6.0'
ptxas fatal   : Ptx assembly aborted due to errors
 --error 0xff --
Makefile:32: recipe for target 'cu-kernels.o' failed
make[2]: *** [cu-kernels.o] Error 255

**Comment by btiplitz** [comment]
I build on ubuntu 16.04 with both Cuda 9 and Cuda 10, but I'm using gcc 5.4 which came with ubunto and I don't get any errors.  You said in the description you have gcc 6.5, but the command line is gcc-5.2.  As this version is lower than the stock gcc, I suspect that is related to the problem.  And nvidia will end up using the built-in gccunless oyu specify gccbin on the command line which could also be related to the issue

**Comment by danpovey** [comment]
You should be passing in the CXX variable to "configure", not to "make".

**Comment by aaronlyt** [comment]
i have tried ,but it still have the problem

**Comment by danpovey** [comment]
You can't just replace the binary.  g++ is a suite of tools including many components, such as the headers and system library.  You need to properly install it.
