### ISSUE TITLE
unable to take output at softmax layer

### ISSUE THREAD

**Issue by ramesh720** [kaldi-asr/kaldi#2933]
normally i trained tdnn xvector system for emotion recognition. instead of taking X vectors at 6 th layer for given data  , i want to take output at softmax layer(final layer) for test data. can you please help me how to take output at softmax layer for test data sir. Thanking you Sir

**Comment by danpovey** [comment]
I would recommend to just look at how the script takes it at the 6th layer and maybe remove whatever option changes the output layer (it's probably some option like --nnet-config=..., where the config mentions that layer).
