### ISSUE TITLE
kaldi/egs/librispeech/s5/path.sh uses wrong path to sequitur

### ISSUE THREAD

**Issue by vvasily** [kaldi-asr/kaldi#2937]
kaldi/egs/librispeech/s5/path.sh uses the following path to sequitur:
sequitur=$KALDI_ROOT/tools/sequitur/g2p.py

But now sequitur is installed as $KALDI_ROOT/tools/sequitur-g2p. So, it should be:
sequitur=$KALDI_ROOT/tools/sequitur-g2p/g2p.py

**Comment by danpovey** [comment]
@jtrmal  would you mind changing how the path is done in the librispeech setup?
I think we can just use the env.sh, but you know those issues best.

**Comment by kkm000** [comment]
@jtrmal, ping.
