### ISSUE TITLE
How to use the tri4b_dnn modules~

### ISSUE THREAD

**Issue by TianBinyu** [kaldi-asr/kaldi#2939]
Hi
Dear Sir
After i use the thchs30 script to train the ASR module, it works well and generate the module.
And tri1&tri2b&tri3b... modules are easy to use,but i do not know how to use this module:
'tri4b_dnn' which is generated by this script~
kaldi\egs\thchs30\s5\local\nnet\run_dnn.sh:
#!/bin/bash
#Copyright 2016  Tsinghua University (Author: Dong Wang, Xuewei Zhang).  Apache 2.0.

#run from ../..
#DNN training, both xent and MPE
....

ls
ali_train_pdf.counts  cv.scp             decode_test_word         final.mdl   nnet        phones.txt     train.scp.10k        tree
cmvn-g.stats          cv.scp_non_local   feat_type                final.nnet  nnet.init   splice5.proto  train.scp_non_local  tr_splice5_cmvn-g.nnet
cmvn_opts             decode_test_phone  final.feature_transform  log         nnet.proto  train.scp      train_sorted.scp     tr_splice5.nnet

i can not find the guide to use this module, can you help me to check it?
Thank you very much~

**Comment by danpovey** [comment]
Look at it more carefully, it includes decoding.
