### ISSUE TITLE
Build docker image with coda support report error

### ISSUE THREAD

**Issue by c2j** [kaldi-asr/kaldi#2940]
Build docker image with cuda support report error:
```
cd misc/docker/ubuntu-cuda
docker build -t kaldi-cuda .
```
Error 1:
```
Step 8/11 : RUN extras/check_dependencies.sh
 ---> Running in 49888bb995c8
extras/check_dependencies.sh: sox is not installed.
extras/check_dependencies.sh: we recommend that you run (our best guess):
 sudo apt-get install  sox
The command '/bin/sh -c extras/check_dependencies.sh' returned a non-zero code: 1
```
Error 2:
```
2018-12-26 13:45:14 (74.5 KB/s) - 'cub-1.8.0.zip' saved [602396/602396]

unzip -oq cub-1.8.0.zip
make: unzip: Command not found
make: *** [cub] Error 127
make: *** Waiting for unfinished jobs....
Makefile:160: recipe for target 'cub' failed
```

Should change this line in misc/docker/ubuntu-cuda/Dockerfile:
```
RUN extras/check_dependencies.sh
```
To
```
RUN apt-get install -y sox zip unzip; extras/check_dependencies.sh
```

**Comment by danpovey** [comment]
Sure, good idea.

**Comment by kkm000** [comment]
@c2j, are you still on this, or mark this up-for-grabs?

**Comment by kkm000** [comment]
Is anyone actually using these images? Any understanding in which way they are used? As written, it's more of an exercise in using docker that a practically useful thing. And most reasons not to package Kaldi into a deb/rpm apply here as well.

So I ran `docker build .`, got a 22GB image, and...??

**Comment by danpovey** [comment]
I've never used them, and I feel they are probably not particularly
useful.. I don't feel strongly about them.

**Comment by jtrmal** [comment]
seems like the dockerfiles were fixed in the meantime, please use [kaldi]/docker or download the images from docker hub
