### ISSUE TITLE
where does the script prep_test_aspire_segmentation.sh is placed  ? 

### ISSUE THREAD

**Issue by itaipee** [kaldi-asr/kaldi#2943]
https://github.com/kaldi-asr/kaldi/blob/9b320ad0b01e196885b27eb94152851b818f7297/egs/aspire/s5/local/run_asr_segmentation.sh#L216

**Comment by vimalmanohar** [comment]
It got renamed to local/nnet3/segment_and_decode.sh. Please check that it works and create a PR.

**Comment by danpovey** [comment]
@vimalmanohar if he doesn't make a PR please make sure someone does it.

**Comment by itaipee** [comment]
thanks
