### ISSUE TITLE
Graph of chain models

### ISSUE THREAD

**Issue by Umar17** [kaldi-asr/kaldi#2948]
Hi all,

From documentation of chain models, what I understand is that language model for such models is based on only 3-gram probabilities. Doesn't it increase WER (my practical observation is that it is so at least in case of live decoding)? It shows better offline results and has an edge over conventional DNN regarding graph size (it gives me liberty of at least 3 time more concurrent sessions than conventional DNN's graph. That's just amazing). 
Am I right? If yes then any suggestions for better results with chain models? Will RNNLM perform better and is compatible with chain models? Or something else?

Best Regards
Muhammad Omar Farooq

**Comment by danpovey** [comment]
The LM is normally a 3-gram, even for regular models.  The graph built for
chain models is somewhat smaller though.
RNNLM gives similar performance gains for all model types.

**Comment by Umar17** [comment]
Does LM back track to 2-gram and unigram if a probability is not found in 3-gram in case of chain models? Is there any trade off in WER and graph size? I mean should this reduced size affect WER or not at all (especially in online case when speech is coming from speakers in realtime)?

Best Regards
