### ISSUE TITLE
`MelBanks::Compute` ignores last FFT bin

### ISSUE THREAD

**Issue by christoph-conrads** [kaldi-asr/kaldi#2949]
During the FBANK features computation, the power spectrum is computed mapping a vector of dimension `n` containing Fourier coefficients to a vector of dimension `n/2 + 1`, see [`src/feat/feature-fbank.cc`, lines 95-96](https://github.com/kaldi-asr/kaldi/blob/46826d94e6e12c5d772fb7e4ae7e7c1ad165b69a/src/feat/feature-fbank.cc#L95-L96). In the following mel-frequency filterbanks computation, the number of power spectrum coefficients is set to `n/2` in [`src/feat/mel-computations.cc`, line 42](https://github.com/kaldi-asr/kaldi/blob/46826d94e6e12c5d772fb7e4ae7e7c1ad165b69a/src/feat/mel-computations.cc#L42). That is, the highest frequency Fourier coefficient is ignored.

If this is intentional, what is the reasoning behind it?

**Comment by danpovey** [comment]
Any time you are about to sample a signal, you'd normally apply some kind of analog or digitial filter to limit the frequency to less than the Nyquist.  So there wouldn't be any energy at the Nyquist anyway, if all went well.  Anyway we were following HTK code and aiming for compatibility.
