### ISSUE TITLE
[egs][aishell][s5] - possible to use online decode for tri models?

### ISSUE THREAD

**Issue by kenyeung128** [kaldi-asr/kaldi#2950]
@naxingyu for [egs][aishell][s5], would it be possible to use the models from exp/triX for online decoding with wav files? as seems couldn't get online-wav-gmm-decode-faster working with the models. thanks.

**Comment by danpovey** [comment]
You'd normally have to retrain the models specially for use with that
binary, since it requires the models to be trained with online CMN or
something like that.  There are scripts, in steps/online/ I think, for this.
