### ISSUE TITLE
recognition time of pre-trained model cvte

### ISSUE THREAD

**Issue by Ruhewang** [kaldi-asr/kaldi#2958]
hi
thank you sincerely for sharing such powerful toolkit for us to study.
I'm a newbie to Kaldi and tried to use the mandarin cvte pre-trained model to make recog prediction. The performance is good, but It takes about 60 mins to decode 10 short utterances and consumes huge memory. For English models, it usually very fast to decode.  Does anyone have any clues about why? 

Ruhe

**Comment by danpovey** [comment]
I don't know what type of model that is, you should ask the guys who released it.
