### ISSUE TITLE
how to generate random input data for nnet2 dnn's propogate computation?

### ISSUE THREAD

**Issue by TonyMou** [kaldi-asr/kaldi#2961]
Hi. Thanks for your work.
I was wondering if it is possible that generating random input data for testing a nnet2 dnn model in kaldi. Because I had an optimized inference framework for kaldi nnet2 dnn model, and want to validate the computation results between kaldi and this framework.
Do u have any suggestion? thanks!

**Comment by danpovey** [comment]
It's not clear whether you are talking about at the script level of code level.  The test code in the nnet2/ directory will likely generate random data and propagate through components.  I think you should be able to figure it out yourself.
