### ISSUE TITLE
make cub error

### ISSUE THREAD

**Issue by jinlan0639** [kaldi-asr/kaldi#2965]
root@DESKTOP-Q3BQQF1:~/kaldi-trunk/tools#  make cub
wget -T 10 -t 3 -O cub-1.8.0.zip https://github.com/NVlabs/cub/archive/1.8.0.zip
Will not apply HSTS. The HSTS database must be a regular and non-world-writable file.
ERROR: could not open HSTS store at '/root/.wget-hsts'. HSTS will be disabled.
--2019-01-04 10:01:17--  https://github.com/NVlabs/cub/archive/1.8.0.zip
Resolving github.com (github.com)... 13.229.188.59, 52.74.223.119, 13.250.177.223
Connecting to github.com (github.com)|13.229.188.59|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://codeload.github.com/NVlabs/cub/zip/1.8.0 [following]
--2019-01-04 10:01:18--  https://codeload.github.com/NVlabs/cub/zip/1.8.0
Resolving codeload.github.com (codeload.github.com)... 54.251.140.56, 13.250.162.133, 13.229.189.0
Connecting to codeload.github.com (codeload.github.com)|54.251.140.56|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 602396 (588K) [application/zip]
Saving to: ‘cub-1.8.0.zip’

cub-1.8.0.zip                 100%[=================================================>] 588.28K  37.5KB/s    in 11s

2019-01-04 10:01:30 (53.3 KB/s) - ‘cub-1.8.0.zip’ saved [602396/602396]

unzip -oq cub-1.8.0.zip
make: unzip: Command not found
Makefile:160: recipe for target 'cub' failed
make: *** [cub] Error 127

**Comment by danpovey** [comment]
because unzip wasn't installed.  I believe the latest version of Kaldi fixes that problem.

**Comment by jinlan0639** [comment]
it's solved ,thank you !
