### ISSUE TITLE
timit/local/nnet/run_dnn stopped at line 56

### ISSUE THREAD

**Issue by zdgithub** [kaldi-asr/kaldi#2975]
Hi，when I ran the `timit/local/nnet/run_dnn.sh` for DNN Hybrid Training & Decoding(Karel's recipe)，it stopped at `local/nnet/run_dnn.sh: line 56: exp/dnn4_pretrain-dbn/log/pretrain_dbn.log: No such file or directory`

**Comment by danpovey** [comment]
I don't really support that stuff and Karel doesn't often comment on github, so closing the issue.
Someone should create a training recipe for TIMIT using the standard chain scripts, though.  It would probably work better than what we have now.
