### ISSUE TITLE
Difference betwwen AffineComponentPreconditionedOnline and FixedAffineComponent when propogate

### ISSUE THREAD

**Issue by TonyMou** [kaldi-asr/kaldi#2976]
Does AffineComponentPreconditionedOnline have the same propogation caculation with FixedAffineComponent?

**Comment by danpovey** [comment]
Yes it should.

**Comment by TonyMou** [comment]
@danpovey  Thanks.
 But I got wrong results using (input * LinearParams + Bias, same with AffineComponent), to calculate AffineComponentPreconditionedOnline's output. Is there any different param used in  AffineComponentPreconditionedOnline's propogation?

**Comment by danpovey** [comment]
No, nothing is different.

**Comment by TonyMou** [comment]
@danpovey Thanks for your confirmation.
