### ISSUE TITLE
CUDA sparse-matrix class

### ISSUE THREAD

**Issue by danpovey** [kaldi-asr/kaldi#298]
Something needs to be coded for sparse-matrix support that's going to be quite important for the new 'chain' (post-CTC) stuff I am working on, and maybe some nearer-term things too (relating to multi-tree systems- we should be able to get a nice improvement).
We need to be able to efficiently do matrix multiplication by a sparse matrix.  The current CuSparseMatrix class does not have a data format that is conducive to this.
in cu-sparse-matrix.h, I'd like a new class added, that stores its data per-row.

The class CuRowSparseMatrix<Real> will have members:

  int32 num_rows_;
  int32 elements_per_row_;
  CuArray < std::pair<int32, Real> > data_;   // pairs (column-index, value).
                                                          //dim = num_rows_ * elements_per_row_.

where elements_per_row_ will be like a stride; it will be the maximum number of nonzero elements per row; you'll pad with (-1, 0.0) in case some rows have fewer than the maximum number of elements.
You can pass the pointer to the data across the "C" interface as void*.  It's messy but it avoids having to create a "C" equivalent to the C++ pair.

The key function that I want written (aside from the one to create the CuRowSparseMatrix<Real> from a SparseMatrix<Real> is the following function:

  // Do *this = alpha * a * b + beta * *this.
  // Only supports the case where trans_b = kTrans; will crash if trans_b = kNoTrans.
  void CuMatrixBase<Real>::AddMatSmat(Real alpha, CuMatrixBase<Real> &a, MatrixTransposeType trans_a,
                              CuRowSparseMatrix<Real> &b, MatrixTransposeType trans_b, Real beta);

The kernel will do the summation over the elements_per_row_ elements using a simple for loop.   You can assume that elements_per_row_ is fairly small, otherwise we wouldn't be using this.

Obviously there needs to be test code for this.

**Comment by danpovey** [comment]
@naxingyu, do you have time for this?  I know you've done a lot lately..

**Comment by naxingyu** [comment]
I'll do this next week (this week on phone-topology).

**Comment by danpovey** [comment]
OK thanks-- check in with us when you've done the phone-topology thing
though, because @hainan-xv was considering doing it.

**Comment by naxingyu** [comment]
I'll create a interface for CuRowSparseMatrix similar to CuSparseMatrix. 
Some basics are
* return numbers
* copy and swap functions
* data accessors and randomizer
* operators
* read and write
* a constructor from a SparseMatrix

Besides those, should I implement these?
* sum
* frobenius norm

And according to your design, I will add AddMatSmat as a member function 
of CuMatrixBase, is that right?

Xingyu

**Comment by danpovey** [comment]
> I'll create a interface for CuRowSparseMatrix similar to CuSparseMatrix.
> Some basics are
> * return numbers
> * copy and swap functions
> * data accessors and randomizer
> * operators
> * read and write
> * a constructor from a SparseMatrix
>

sure.


> Besides those, should I implement these?
> * sum
> * frobenius norm
>

only if you have time-- they might be useful for some diagnostics.  but we
can always copy to CPU for this.


>
> And according to your design, I will add AddMatSmat as a member function
> of CuMatrixBase, is that right?
>

yes.
Dan

**Comment by naxingyu** [comment]
It seems I should create a RowSparseMatrix class too? To handle the 
non-cuda situation?

X.

**Comment by danpovey** [comment]
Actually no, because the regular SparseMatrix class already stores its data
by row.
Dan
