### ISSUE TITLE
Fixed sparse affine component

### ISSUE THREAD

**Issue by danpovey** [kaldi-asr/kaldi#299]
Note: to fully implement this efficiently on the GPU, we depend on issue #298.  However, a placeholder implementation using full matrices could easily be created.

In nnet3, I'd like a FixedSparseAffineComponent to be implemented.  This won't have trainable parameters, its parameters will be initialized from a file.  This is going to be useful in some multi-tree training stuff that Hainan will implement.  (note: we previously got good results from this but it wasn't efficient; I think that once we implement it this way it will be almost as fast as the baseline system to train).

We'll add whoever helps us with these things, to the paper.

**Comment by vijayaditya** [comment]
Based on our discussion last week, I think it would be better to have a SparseAffineComponent with a fixed mode, determined by a bool. This bool would also be used to determine the output of the Properties() call of the component.

**Comment by danpovey** [comment]
OK with me to implement it that way.  However the training of the sparse
affine component would likely require other matrix operations we don't have
yet, so better to just have it throw an error for now.
