### ISSUE TITLE
Kaldi Results

### ISSUE THREAD

**Issue by andreaschandra** [kaldi-asr/kaldi#3004]
```
Besides the fact that you will notice some decoding results in the terminal window, go to newly made kaldi-trunk/egs/digits/exp. You may notice there folders with mono and tri1 results as well - directories structure are the same. Go to mono/decode directory. Here you may find result files (named in a wer_{number} way). Logs for decoding process may be found in log folder (same directory).
```
So I have trained audio data using an4, and the Kaldi ran successfully. According to the documentation, to see the result go to exp folder then look at mono/decode folder or tri1 folder.
My question is, in which file kaldi store the actual result?
I have been opened each files but there are a lot of result and i could not figure it out which actual result such as wer_10_0.0, wer_10_0.5 etc

**Comment by jtrmal** [comment]
This has been discussed several times in the kaldi-help mailing list, see http://kaldi-asr.org/forums.html how to join.
quick answer is the first number is LM weight and the second is word-insertion penalty (and all of them are valid results).
If you need to follow up, please join the kaldi-help mailing list -- this place is not suitable for this kind of discussion.
