### ISSUE TITLE
Error reading RIRS noises while extracting MFCCs on augmented data

### ISSUE THREAD

**Issue by majaldm** [kaldi-asr/kaldi#3005]
I'm extracting features from a dataset augmented with RIRS reverberation and musan noises (as in the Voxceleb/v2 recipe). The extraction completes with a 75% completion success.

Checking the log files the same error repeats over and over: **ERROR (compute-mfcc-feats[5.5.76~1416-535b]:Read4ByteTag():wave-reader.cc:56) WaveData: expected 4-byte chunk-name, got read error**

I also noticed that several files from the RIRS dataset can't be read, summing up all the times a file isn't read properly sums up to the number of unsuccessful extractions. As example:
**wav-reverberate --shift-output=true '--impulse-response=sox RIRS_NOISES/simulated_rirs/smallroom/Room147/Room147-00027.wav -r 16000 -t wav - |' - - 
sox FAIL formats: can't open input file `RIRS_NOISES/simulated_rirs/smallroom/Room147/Room147-00027.wav': No such file or directory**
(by the way, notice how the path to the rirs file is written between a grave accent and a apostrophe)

The RIRS files have been extracted on place from the official archive file, and I have checked to see that they are where they're supposed to be, together with other files named in the same way and that are read properly. Is this just a problem of having corrupted files or is there something more to it?

_Also, while looking into this I realized the way the compute feats command is called includes a strange wav_rspecifier_ ($logdir/wav_${name}.JOB.scp) _which points to a location where there's no such file:_
$cmd JOB=1:$nj $logdir/make_mfcc_${name}.JOB.log \
    compute-mfcc-feats  $vtln_opts --verbose=2 --config=$mfcc_config \
    scp,p:$logdir/wav_${name}.JOB.scp ark:- \| \
    copy-feats $write_num_frames_opt --compress=$compress ark:- \
    ark,scp:$mfccdir/raw_mfcc_$name.JOB.ark,$mfccdir/raw_mfcc_$name.JOB.scp \

**Comment by david-ryan-snyder** [comment]
> sox FAIL formats: can't open input file `RIRS_NOISES/simulated_rirs/smallroom/Room147/Room147-00027.wav': No such file or directory

Did you confirm that this file exists?

**Comment by majaldm** [comment]
Yes, they exist. They also pass the validation scripts.

**Comment by danpovey** [comment]
That is a relative pathname-- maybe you changed directory before calling that script.

**Comment by david-ryan-snyder** [comment]
What validation script does the RIR directory pass? 

As Dan mentioned, this has to be run from inside egs/voxceleb/v2.

**Comment by danpovey** [comment]
Closing this issue; likely just a question of relative pathnames.

**Comment by david-ryan-snyder** [comment]
Perhaps you interrupted the inflation of the rirs_noises.zip file. You could try deleting the RIR_NOISES directory, then rerun run.sh at stage=2.

**Comment by majaldm** [comment]
I redownloaded and unzipped the file to completion, but rerunning step 2 I got this error when executing steps/data/reverberate_data_dir.py :
````
Traceback (most recent call last):
  File "steps/data/reverberate_data_dir.py", line 658, in <module>
    Main()
  File "steps/data/reverberate_data_dir.py", line 655, in Main
    max_noises_per_minute = args.max_noises_per_minute)
  File "steps/data/reverberate_data_dir.py", line 443, in CreateReverberatedCopy
    .format(output_dir = output_dir))
  File "steps/data/data_dir_manipulation_lib.py", line 14, in RunKaldiCommand
    raise Exception("There was an error while running the command {0}\n".format(command)+"-"*10+"\n"+stderr)
TypeError: Can't convert 'bytes' object to str implicitly
````
