### ISSUE TITLE
get_egs_discriminative2.sh 

### ISSUE THREAD

**Issue by danpovey** [kaldi-asr/kaldi#301]
@vijayaditya  and @vimalmanohar:

Someone said on Kaldi-help:

"When I'm running this steps, some of the nnet-get-egs from stage 10 fail, because exp/nnet2_online/nnet_ms_sp_degs/priors_uttlist doesn't have any utterance from (for example in my case) data/train_sp_hires/split350/141/feats.scp.
I'm not sure how to fix this so that it doesn't randomly break when I change the data again."

I think it would be less wasteful to just use one job for this (i.e. to use non-split feats.scp).  Since the subset size is fairly small, this won't take long, and it will be less stressful to the cluster.

**Comment by danpovey** [comment]
fixed- cosing

**Comment by jtrmal** [comment]
Apparently, 
all_ids=$(seq -s, $nj) 
in combination with the filepath can generate a line/filename too long.
Perhaps the command there should be restructured along something like

find  $alidir -name "ali.*.gz"  -printf "%f\n" | sort -t '.' -k2,2n | xargs  -I{} gunzip -c $alidir/{}  | copy-int-vector ark:- ark,t:- | utils/filter_scp.pl $dir/priors_uttlist | ali-to-pdf $alidir/final.mdl ark,t:- ark:- 

or just replace it by a for-cycle? xargs sometimes does not have the -I option...

for i  in $(seq $nj); do gunzip -c $alidir/ali.$i.gz; done | copy-int-vector ark:- ark,t:- | utils/filter_scp.pl $dir/priors_uttlist | ali-to-pdf $alidir/final.mdl ark,t:- ark:- 

y.

**Comment by danpovey** [comment]
It's OK, I'm closing this.
The user who had the problem was likely using dash as the system shell in
/bin/sh; many scripts don't work with dash, and the solution I'm adopting
is to make scripts die if they detect the use of dash.  It isn't always
very easy to work around dash's limitations.
Dan
