### ISSUE TITLE
mel-computations cli help text "=" missing

### ISSUE THREAD

**Issue by boeddeker** [kaldi-asr/kaldi#3010]
The help text of `compute-mfcc-feats` says that the `--high-freq < 0` is the offset from Nyquist.
But the code says it is  `--high-freq <= 0`. 
In my mind should the help text say `--high-freq <= 0` is the offset from Nyquist.

Here the code positions:
https://github.com/kaldi-asr/kaldi/blob/8ce3a95761e0eb97d95d3db2fcb6b2bfb7ffec5b/src/feat/mel-computations.h#L66

https://github.com/kaldi-asr/kaldi/blob/8ce3a95761e0eb97d95d3db2fcb6b2bfb7ffec5b/src/feat/mel-computations.cc#L46

**Comment by danpovey** [comment]
OK, you can make a PR if you have time.
