### ISSUE TITLE
How to change data labels

### ISSUE THREAD

**Issue by panxin801** [kaldi-asr/kaldi#3013]
I'm new here. I am using nnet3+chain for traing a tdnn model. But now i just want to change the  frame label with my created label. After searching for a time, in folder `steps/libs/nnet3/train/chain_objf.py` has a function `compute_train_cv_probabilities`. In the function i find a code `nnet3-chain-compute-prob --l2-regularize={l2}... etc...`. 
Is the code upper generates the egs for trainging? and can where can i replace the labels. 
Thanks a lot for reply.

**Comment by danpovey** [comment]
The chain training is a sequence objective and doesn't have a concept of frame labels.  Maybe you want regular nnet3 training.  @vimalmanohar perhaps you could point him to the segmentation training scripts, which probably create their own labels?

**Comment by vimalmanohar** [comment]
You can see how labels are created using for e.g. prepare_targets_gmm.sh in
https://github.com/kaldi-asr/kaldi/blob/master/egs/swbd/s5c/local/run_asr_segmentation.sh

**Comment by panxin801** [comment]
Ok, I just went to a wedding ceremony and I will check this file if it can help.. Thanks a lot both of you.

**Comment by panxin801** [comment]
> You can see how labels are created using for e.g. prepare_targets_gmm.sh in
> https://github.com/kaldi-asr/kaldi/blob/master/egs/swbd/s5c/local/run_asr_segmentation.sh

Hello sir. I read about the .sh file, I still have a question for you. 
In fact I'm planning to do some teacher-student traing stuffs. Now I'm using nnet3 model. I use `nnet3-copy-egs` transfer a egs.1.ark to egs.1.txt. When I read the file "egs.1.txt"  in some lines there're pdf counts. I want to know if there're labels in this file either. If so ,I can replace it with my own label, and i think this way is easier.
