### ISSUE TITLE
how to compile kaldi with gpu

### ISSUE THREAD

**Issue by ououkhin63** [kaldi-asr/kaldi#3016]
Hi
I am the beginner for using Kaldi and now I am trying to compile kaldi with GPU. I found that I need to configure and make where the nvcc is installed.
So, I run the ./configure but it shows like that.
Unsupported CUDA_VERSION (CUDA_VERSION=10_0), please report it to Kaldi mailing list, together with 'nvcc -h' or 'ptxas -h' which lists allowed -gencode values...
Configuring ...
Backing up kaldi.mk to kaldi.mk.bak ...
Checking compiler g++ ...
Checking OpenFst library in /home/neuro/kaldi/tools/openfst ...
Doing OS specific configurations ...
On Linux: Checking for linear algebra header files ...
Using ATLAS as the linear algebra library.
Atlas found in /usr/lib/x86_64-linux-gnu
Validating presence of ATLAS libs in /usr/lib/x86_64-linux-gnu
Using library /usr/lib/x86_64-linux-gnu/liblapack.so as ATLAS's CLAPACK library.
Unsupported CUDA_VERSION (CUDA_VERSION=10_0), please report it to Kaldi mailing list, together with 'nvcc -h' or 'ptxas -h' which lists allowed -gencode values...
I don't know how to solve this problem. Please someone tell me.
Ps.Actually now I am using cuda version=10 for another testing.

**Comment by btiplitz** [comment]
Are you using the latest kaldi.  Configure has support for CUDA 10 at line 439 in the script.  And usually nvcc is installed in /usr/local/cuda.  Also if you are trying to do something fast (aka you are using a gpu), try using a different math library other than atlas.  The intel mkl or openblas is 2x faster on the linear algebra calls.

**Comment by jtrmal** [comment]
I agree with Brett -- please update your kaldi (git pull). If you need any follow-up, ask on the mailing list, this is not a suitable place for this kind of questions.
