### ISSUE TITLE
Kaldi requires sudo rights

### ISSUE THREAD

**Issue by jturpeinen** [kaldi-asr/kaldi#3026]
Hello!
I have been trying to install Kaldi for several times. extras/check_dependencies.sh told issues with g++ and zlib, but both were installed and recently updated, so I ignored warnings during first time. Then I used clang and clang++ as compiler, but tests with yesno-recipy didn't work. During recent run, I checked dependancies with sudo rights and everything seemed to be OK. This gave some hint, that makefiles would also recuire sudo rights. So I run makefiles with clang and sudo rights, and tested Kaldi again with yesno and it worked as it should. I'm just wondering why. Also, maybe informing others about this can help anyone with similar issues to install Kaldi.

**Comment by jtrmal** [comment]
Kaldi does not need sudo (or it shouldn't need) -- I would assume you did part of the install as a different user or for some reason, the access rights on your system are not right.
Which distribution are you using? Is the machine managed by you or by someone else?

**Comment by danpovey** [comment]
Also we can't debug "didn't work", it is too nonspecific.

**Comment by jturpeinen** [comment]
My system:
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.1 LTS
Release:	        18.04
Codename:	bionic
The machine is managed by me.

Yesno-recipy did fail somewhere between:
utils/prepare_lang.sh --position-dependent-phones false data/local/dict "<SIL>" data/local/lang data/lang
local/prepare_lm.sh
in run.sh. So it could not compute any features. Preparation of data and dictionary went fine.

**Comment by danpovey** [comment]
It would not have been an installation issue.  I can't comment on any
failure without seeing the error message.
