### ISSUE TITLE
egs folder size takes to much storage space

### ISSUE THREAD

**Issue by anderleich** [kaldi-asr/kaldi#3028]
Hi, 

I'm trying to train a nnet3 acoustic model. However, before the actual training stage, the script is generating the egs folder. This folder size is huge and is taking so much storage space (> 157Gb), which I do not have. Is there any way to reduce this load?

Thanks

**Comment by danpovey** [comment]
Not really.  You could remove speed perturbation if that is part of the
script.  Of course, that will degrade results.
