### ISSUE TITLE
Possible unnecessary __syncthreads using for kernel function "_sum_reduce" in src/cudamatrix/cu-kernels.cu

### ISSUE THREAD

**Issue by DayDayStudyNightNightUp** [kaldi-asr/kaldi#3029]
Hello there!

Currently I am learning kaldi source code and may find some unnecessary use of __syncthreads() for a kernel function in cu-kernels.cu.
```
template<typename Real>
__device__
static Real _sum_reduce(Real buffer[]) {
  // Total number of active threads
  int32_cuda nTotalThreads = blockDim.x;
  __syncthreads();
  // perform tree-based reduction (sum)
  while (nTotalThreads > 1) {
     ....
     __syncthreads();
  }
...
}
```
For kernel function _sum_reduce,  at line 42,  it calls __syncthreads() without any memory access before such calling. __syncthreads() can be deleted here without occurring any data race, does it indicate that this is an unnecessary barrier function calling?

Thanks very much ! :D

**Comment by jtrmal** [comment]
My understanding of the code is that this is a function template supposed
to be called in various places of kernels -- I think the first
__syncthreads() is just to make it foolproof in case the kernel does not do
it before calling the function.
Not sure if there is any penalty in calling sync twice, especially when
compiler could see and optimize-out the second call
y

**Comment by danpovey** [comment]
Ok.  Thanks for pointing it out though.
