### ISSUE TITLE
PerElementOffsetComponent

### ISSUE THREAD

**Issue by danpovey** [kaldi-asr/kaldi#303]
We need a PerElementOffsetComponent in nnet3.
This will be useful in the multi-decision-tree framework mentioned in previous issues.
It should support training, but also support a mode were you can't  do training.  @vijayaditya, do we have a standard name for the boolean variable that determines that.  E.g. is_updatable_ ?
I believe we have similar code in nnet2 that could be used for reference.
This issue is fairly easy, and would be suitable for someone who is getting started with this type of thing.

**Comment by vijayaditya** [comment]
the boolean has not yet been added to the components, I will use the name is_updatable_ when I am adding it.
