### ISSUE TITLE
[aishell2] [online][tri1]ERROR (online-wav-gmm-decode-faster[5.5]:LogLikelihoods():diag-gmm.cc:533) DiagGmm::ComponentLogLikelihood, dimension mismatch 39 vs. 48

### ISSUE THREAD

**Issue by icestoneking** [kaldi-asr/kaldi#3032]
hi, @danpovey 
    When I use online for “tri1” playback recognition, I have encountered a problem with “dimension mismatch 39 vs. 48”; when I use online for “tri3” playback recognition, I encountered “ERROR (online-wav-gmm-decode-faster[5.5]:OnlineLdaInput():online-feat-input.cc:209) Invalid parameters supplied to OnlineLdaInput”, Is my audio_data problem or model problem?I look forward to your reply, thanks.

**Comment by danpovey** [comment]
Likely some configuration problem, I expect you are working with a system configured or created by someone else (not on the Kaldi team).. best to ask them, not me.

**Comment by icestoneking** [comment]
Ok!Thank you very much for your reply.

**Comment by gezhaoDL** [comment]
online-wav-gmm-decode-faster

**Comment by gys18007141407** [comment]
> hi, @danpovey
> When I use online for “tri1” playback recognition, I have encountered a problem with “dimension mismatch 39 vs. 48”; when I use online for “tri3” playback recognition, I encountered “ERROR (online-wav-gmm-decode-faster[5.5]:OnlineLdaInput():online-feat-input.cc:209) Invalid parameters supplied to OnlineLdaInput”, Is my audio_data problem or model problem?I look forward to your reply, thanks.

have the same problem
