### ISSUE TITLE
Improve pre-trained model with my own data

### ISSUE THREAD

**Issue by Cloud299** [kaldi-asr/kaldi#3050]
I'm currently using kaldi ASpIRE Chain Model to perform decoding/transcribing wav files. My data is telephonic and I've found that ASpIRE performs the best out of all the pre-trained models I've come across (I'm open to suggestion if anyone knows of better models for telephonic data). It's not quite as accurate as Google/IBM model yet (understandably) but I was hoping I could improve its performance with my data.

I have hundreds of thousands of transcriptions (by Google STT) with their corresponding .wav files. I was wondering what's the simplest way to build upon ASpIRE model (or build my own) to improve accuracy ? Could someone point me to a good tutorial page. I've been looking through Kaldi webpage but can't find anything specifically applicable to telephonic data.

**Comment by danpovey** [comment]
You would probably want to train jointly on the aspire data plus your
data.  Or maybe just your data alone would be enough.  However that would
require getting the Fisher and Switchboard datasets, and also developing
enough familiarity with Kaldi so that you could do the data preparation,
train the system, etc.  Maybe best to start with the "kaldi for dummies"
tutorial if you haven't already.

There is really nothing special about telephone data, except that we
normally use an 8kHz sampling rate in that case.

**Comment by Cloud299** [comment]
Thank you. I have a follow-up question. My .wav files are typically 30 sec - 60 sec long. For best accuracy using the AsPire model, would it be best to decode the whole file or would it be better to chunk them into smaller/utterance-length files ? (I'm not sure how the AsPire model was trained). 
In general, for a long .wav file, would it be better to chunk it into smaller segments and then transcribe? 
I'm assuming that if the model is RNN-based, it'd be best to leave it as is because there'd be more context and hence the accuracy would be better ? 

Also, I see that the AsPire chain model on Kaldi was uploaded in 2016. I'm wondering if there's a been a newer/more updated ASR english model on Kaldi that I could use ?

**Comment by danpovey** [comment]
You'd have to try both approaches and test.   Look at the aspire decoding
scripts.  We had to do some special stuff to get the i-vectors to work
robustly in that setup.  My main concern about long utterances is how
robust the i-vector estimation would be, especially if the utterance was
mostly silence.

We don't normally spend a lot of effort uploading models, I'm not aware
that there is a more recent one available online.

**Comment by Cloud299** [comment]
Thank you for the feedback. I'm wondering if there's any preprocessing (narrow/broad bandpass filter...) step that you'd recommend to perform on the .wav file before transcribing to achieve higher accuracy ?

**Comment by danpovey** [comment]
No special steps.  As I said, you should go through the Kaldi for Dummies
tutorial, e.g. to train a system on some of your data.  Please do this
before asking any more questions.

**Comment by kkm000** [comment]
I am closing this ticket for now. If you believe that your issue has not been addressed, please feel free to ping me, and I'll reopen it.
