### ISSUE TITLE
lre07 v2 --> nnet3 support

### ISSUE THREAD

**Issue by anderleich** [kaldi-asr/kaldi#3053]
Hi,
I'm trying to build a language identification system following lre07 v2 recipe. From what I could understand, I need to make use of an already pretrained acoustic model. I have my own nnet3 (tdnn-lstm) model which I would like to use. However, I get and error when running `lid/init_full_ubm_from_dnn.sh`. It seems it only supports nnet2 as the binaries report **Nnet** is expected not **Nnet3**. Is there any solution?

**Comment by david-ryan-snyder** [comment]
The LID recipes aren't well maintained.

The solution is to write a new set of bash scripts that utilize nnet3 rather than nnet2 binaries. This isn't particularly difficult to do, if you're familiar with Kaldi scripts.

**Comment by kkm000** [comment]
@anderleich, is this a satisfactory answer? Should I close this?

**Comment by danpovey** [comment]
closing; updated language recognition recipes is more of a general wish, not a task to schedule.
