### ISSUE TITLE
recipe for target 'chain-kernels.o' failed

### ISSUE THREAD

**Issue by vikashchaurasia00** [kaldi-asr/kaldi#3069]
Hi,

I am installing kaldi-master using this

./configure --shared
make depend -j 8
make -j 8

Output of-
nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2018 NVIDIA Corporation
Built on Wed_Apr_11_23:16:29_CDT_2018
Cuda compilation tools, release 9.2, V9.2.88

g++ --version
g++ (GCC) 4.8.5
Copyright (C) 2015 Free Software Foundation, Inc.

I am getting this error on executing make -j 8

#$ cudafe++ --allow_managed --m64 --gnu_version=40805 --parse_templates --gen_c_file_name "/tmp/tmpxft_00003ba4_00000000-13_chain-kernels.compute_30.cudafe1.cpp" --stub_file_name "tmpxft_00003ba4_00000000-13_chain-kernels.compute_30.cudafe1.stub.c" --module_id_file_name "/tmp/tmpxft_00003ba4_00000000-3_chain-kernels.module_id" "/tmp/tmpxft_00003ba4_00000000-14_chain-kernels.cpp4.ii" 
g++ -std=c++11 -I.. -I/home/pradeeprangan/kaldi-master/tools/openfst/include  -Wall -Wno-sign-compare -Wno-unused-local-typedefs -Wno-deprecated-declarations -Winit-self -DKALDI_DOUBLEPRECISION=0 -DHAVE_EXECINFO_H=1 -DHAVE_CXXABI_H -DHAVE_ATLAS -I/home/pradeeprangan/kaldi-master/tools/ATLAS_headers/include -msse -msse2 -pthread -g  -fPIC -DHAVE_CUDA -I/usr//include   -c -o rescale-nnet.o rescale-nnet.cc
Segmentation fault (core dumped)
--error 0x8b --
Makefile:33: recipe for target 'chain-kernels.o' failed
make[2]: *** [chain-kernels.o] Error 139
make[2]: *** Waiting for unfinished jobs....
g++ -std=c++11 -I.. -I/home/pradeeprangan/kaldi-master/tools/openfst/include  -Wall -Wno-sign-compare -Wno-unused-local-typedefs -Wno-deprecated-declarations -Winit-self -DKALDI_DOUBLEPRECISION=0 -DHAVE_EXECINFO_H=1 -DHAVE_CXXABI_H -DHAVE_ATLAS -I/home/pradeeprangan/kaldi-master/tools/ATLAS_headers/include -msse -msse2 -pthread -g  -fPIC -DHAVE_CUDA -I/usr//include   -c -o nnet-limit-rank.o nnet-limit-rank.cc
g++ -std=c++11 -I.. -I/home/pradeeprangan/kaldi-master/tools/openfst/include  -Wall -Wno-sign-compare -Wno-unused-local-typedefs -Wno-deprecated-declarations -Winit-self -DKALDI_DOUBLEPRECISION=0 -DHAVE_EXECINFO_H=1 -DHAVE_CXXABI_H -DHAVE_ATLAS -I/home/pradeeprangan/kaldi-master/tools/ATLAS_headers/include -msse -msse2 -pthread -g  -fPIC -DHAVE_CUDA -I/usr//include   -c -o nnet-example.o nnet-example.cc
make[2]: Leaving directory '/home/pradeeprangan/kaldi-master/src/chain'
Makefile:142: recipe for target 'chain' failed
make[1]: *** [chain] Error 2
make[1]: *** Waiting for unfinished jobs....

Thank you

**Comment by danpovey** [comment]
A segfault in the compiler would always be a compiler bug.  It is likely to
do with the particular combination of gcc and the CUDA toolkit that you
have used-- only solution is to try different versions, paticularly more
recent versions (your gcc is fairly old).
I don't have time to go into it more deeply.

**Comment by vikashchaurasia00** [comment]
@danpovey Thank you,
Any other suggestion or solution for this because that is not woking for me.

**Comment by danpovey** [comment]
No more suggestions.

**Comment by chankim** [comment]
Hi, I'm seeing a similar error. Hope someone could show me the solution.
#$ g++ -std=c++11 -E -x c++ -D__CUDACC__ -D__NVCC__  -std=c++11 -I.. -isystem /home2/ckim/KALDI/kaldi/tools/openfst-1.6.7/include -O1  -Wall -Wno-sign-compare -Wno-unused-local-typedefs -Wno-deprecated-declarations -Winit-self -DKALDI_DOUBLEPRECISION=0 -DHAVE_EXECINFO_H=1 -DHAVE_CXXABI_H -DHAVE_MKL -I/opt/intel/mkl/include -m64 -msse -msse2 -pthread -g  -fPIC -DHAVE_CUDA -I/usr//include -fPIC -pthread -isystem /home2/ckim/KALDI/kaldi/tools/openfst-1.6.7/include -I"/usr//include" -I"/home2/ckim/KALDI/kaldi/tools/cub-1.8.0" -I"../" -D"__CUDACC_VER__=70517" -D"__CUDACC_VER_BUILD__=17" -D"__CUDACC_VER_MINOR__=5" -D"__CUDACC_VER_MAJOR__=7" -D"HAVE_CUDA" -D"KALDI_DOUBLEPRECISION=0" -D"CUDA_API_PER_THREAD_DEFAULT_STREAM" -include "cuda_runtime.h" -m64 "cu-kernels.cu" > "/tmp/tmpxft_00014686_00000000-14_cu-kernels.cpp4.ii"
#$ cudafe++ --allow_managed --m64 --gnu_version=40904 --c++11 --parse_templates --gen_c_file_name "/tmp/tmpxft_00014686_00000000-13_cu-kernels.compute_30.cudafe1.cpp" --stub_file_name "tmpxft_00014686_00000000-13_cu-kernels.compute_30.cudafe1.stub.c" --module_id_file_name "/tmp/tmpxft_00014686_00000000-3_cu-kernels.module_id" "/tmp/tmpxft_00014686_00000000-14_cu-kernels.cpp4.ii"
Segmentation fault (core dumped)
# --error 0x8b --
Makefile:32: recipe for target 'cu-kernels.o' failed
make[1]: *** [cu-kernels.o] Error 139
make[1]: Leaving directory '/home2/ckim/KALDI/kaldi/src/cudamatrix'
Makefile:136: recipe for target 'cudamatrix' failed
make: *** [cudamatrix] Error 2

**Comment by danpovey** [comment]
I can only suggest using a more recent CUDA toolkit version.

**Comment by joyfish** [comment]
I meet similiar issues
DHAVE_CUDA -I/usr//include -c -o rescale-nnet.o rescale-nnet.cc
Segmentation fault (core dumped)
--error 0x8b --
Makefile:33: recipe for target 'chain-kernels.o' failed
make[2]: *** [chain-kernels.o] Error 139

my solution
uninstall my cuda10-2. install cuda9.2/9/8

**Comment by danpovey** [comment]
@luitjens you may want to be aware of this (segfault in most recent CUDA compiler, as far as I can tell).

**Comment by joeyfish** [comment]
Actually I meet 2 problem.  1, Makefile:33: recipe for target 'chain-kernels.o' failed. 2, cu-vector-test crashed. I remember it report CUBLAS_STATUS_ARCH_MISMATCH issue.
I dont want to downgrade cuda10-2 at first. But finally I cannot go ahead. That's why I downgrade it.
