### ISSUE TITLE
Task: Make sure std::endl does not impact large file I/O performance

### ISSUE THREAD

**Issue by kkm000** [kaldi-asr/kaldi#3077]
There is a lot of uses of this iomanip in the codebase. Unfortunately, many C++ primers use it in place of a newline literal, but in realiy the thing not only outputs the linefeed, but also flushes the file. This may have a serious impact on writing large files.

I'm going to make a thorough run-through on this.

**Comment by jtrmal** [comment]
This might be slightly more difficult than it seems -- some of the python
scripts might be relying on on the line-by-line output.
I think I saw something in Karel's nnet1, not sure about nnet3 but I can be
mistaken in both cases.
y.

**Comment by kkm000** [comment]
@jtrmal thanks for the heads-up, I'll check nnet1 carefully. Generally, it does not matter if piping data one-way; the receiving program will still get data line-by-line, due to runtime buffering. I do not think python is different; `readline()` won't return an incomplete line unless the last one w/o a `\n` when the pipe is closed, but I'll test paranoidally, since you are bringing this up.

Only bidirectional communication is normally a concern. When you send something down one fd and wait for a response on another, you'd better flush it. : ) But I do not think this ever happens in Kaldi. Can you think of such an arrangement anywhere? There are some bidi comms in the online audio client/server, but I'm not touching that.

**Comment by jtrmal** [comment]
Good point, I think my comment might be completely moot.
y.
