### ISSUE TITLE
Descriptor handling in steps/nnet3/components.py

### ISSUE THREAD

**Issue by vijayaditya** [kaldi-asr/kaldi#309]
This issue has been raised to initiate discussion.

<code> steps/nnet3/components.py</code> is a library of config generators, e.g. LSTM node, Affine+Nonlinearity node.

In the current library the input and output of the Node generators are always descriptor strings. This kind of implementation makes adding arbitrary node sequences difficult. 
e.g. a node which outputs a sum-descriptor cannot be directly provided as an input to a node which adds offsets to the input descriptor. 

An easy resolution to this issue is to make use of NoOpComponents, however this is wasteful as NoOpComponents cost a matrix copy. Solving this problem using simple regex is not possible as SumDescriptor strings can get quite complex.

A way to solve this issue is to pass descriptor trees across nodes, and use Add<DesctriptorType> methods which operate on these trees and reorder descriptors, when needed.

e.g. Adding Offset -1  on Sum(Sum(A1, A2), Sum(A3, A4)) would result in
Sum(Sum(Offset(A1,-1), Offset(A2, -1)), Sum(Offset(A3, -1), Offset(A4,1)).

However things can quickly get complicated if we have Round descriptors in the input descriptor, and I don't yet have a clear understanding of how this has to be dealt with. 

TODO:
We will need to implement Add<Descriptor> methods for all the existing descriptors. These methods should be able to handle arbitrary descriptor trees, based on the rules of descriptor ordering. 

I realized that this might be of interest to other users too, so I have raised an issue. I plan to start this implementation in a week or two, as it not high priority. If some one else would like to do this they are welcome.

**Comment by danpovey** [comment]
One approach would be to apply operations to the descriptors even where not
allowed, and have a 'normalization' function that figures out how to turn
an invalid descriptor into a valid one.
I think it would be a mistake to try to handle all possible cases before
it's necessary.
Dan

**Comment by naxingyu** [comment]
If the 'normalization' function is to be implemented, Append(Append(a, 
b), c) --> Append(a, b, c) conversion should definitely be added.

**Comment by danpovey** [comment]
reopening this since Vijay says there is a TODO.

**Comment by danpovey** [comment]
I have implemented this at the C++ code level (not merged yet) and will close this issue.
In the short term I'll push to the 'chain' branch but it won't be long before that's merged to trunk.
