### ISSUE TITLE
decode wav on Android kaldi

### ISSUE THREAD

**Issue by ljhou** [kaldi-asr/kaldi#3092]
Recently , I try to develop kaldi on Android system. After getting features and cmvn, I use " nnet3-latgen-faster --frame-subsampling-factor=3 --frames-per-chunk=50 --extra-left-context=0 --extra-right-context=0 --extra-left-context-initial=-1 --extra-right-context-final=-1 --minimize=false --max-active=7000 --min-active=200 --beam=15.0 --lattice-beam=8.0 --acoustic-scale=1.0 --allow-partial=true --word-symbol-table=words.txt final.mdl HCLG.fst 'ark,s,cs:apply-cmvn --norm-means=false --norm-vars=false --utt2spk=ark:utt2spk scp:cmvn.scp scp:feats.scp ark:- |' 'ark:|lattice-scale --acoustic-scale=10.0 ark:- ark:- | gzip -c >lat.1007.gz' "    to get the decode results of a wav . 
   But here comes error of  "std::bad_cast255" .  --- I print some kaldi Logs in my cellphone project, and finally find it's about "const FstType &fst = dynamic_cast<const FstType&>(fst_);" in the src file of lattice-faster-decoder.cc :   void LatticeFasterDecoder::ProcessNonemitting(BaseFloat cutoff) . 
   what should i do to solve this ?

**Comment by danpovey** [comment]
Looks like it might be a runtime error where the FST type was not one of
the expected ones.
Possibly you are using an older Kaldi version to try to decode a graph
produced with a newer Kaldi version.
In any case, that code is not what is in the repo right now.

**Comment by ljhou** [comment]
The kaldi version compiled for  Android is the same as in Linux ，and we use the final.mdl , HCLG produced by kaldi in Linux for Android. and the openfst version is 1.6.7

**Comment by danpovey** [comment]
Your scripts might be from a newer or older Kaldi.  It could be about
expecting ConstFst versus VectorFst or something like that.  In any case it
looks like your code is more than a year old, I am not going to spend
effort supporting that, as most likely whatever it is would not happen with
the recent code.

**Comment by ljhou** [comment]
I change the version and the problem is fixed. thanks for the advice.
