### ISSUE TITLE
where is scores_voxceleb1_test for VoxCeleb Xvector System 1a

### ISSUE THREAD

**Issue by azuryl** [kaldi-asr/kaldi#3095]
I downloaded the X-vector  from http://www.kaldi-asr.org/models/m7

and run

eer=`compute-eer <(local/prepare_for_eer.py $voxceleb1_trials exp/scores_voxceleb1_test) 2> /dev/null`
/home/kaldi/egs/voxceleb/v1/0007_voxceleb_v1_1a$ Traceback (most recent call last):
  File "local/prepare_for_eer.py", line 11, in <module>
    trials = open(sys.argv[1], 'r').readlines()
FileNotFoundError: [Errno 2] No such file or directory: 'exp/scores_voxceleb1_test

**Comment by kkm000** [comment]
I suggest you join the kaldi-help discussion group at https://groups.google.com/forum/#!forum/kaldi-help and ask there. You have better chances of having your question there.

I am closing this ticket for now. If you believe that your issue has not been addressed, please feel free to ping me, and I'll reopen it.
