### ISSUE TITLE
OCR algorithm about IAM handwritting recognition

### ISSUE THREAD

**Issue by yulinxuanzhi** [kaldi-asr/kaldi#3096]
Hello, is there any document or paper to introduce the flow of IAM handwriting recognition algorithm?

**Comment by danpovey** [comment]
We have submitted one to ICDAR.  @aarora8 and @ChunChiehChang can you please forward your papers to David so he can add them to my publications page?   When it's done, let me know and I'll close this issue.

**Comment by ChunChiehChang** [comment]
Should we wait until after the review period for ICDAR?

**Comment by yulinxuanzhi** [comment]
Thanks for your reply, paper name and link : Using ASR methods for OCR [http://www.danielpovey.com/files/2019_icdar_asr_for_ocr.pdf](url)
