### ISSUE TITLE
Transfer learning on kaldi model

### ISSUE THREAD

**Issue by 0x10cx0** [kaldi-asr/kaldi#3098]
Hi there,

is there a way to do transfer learning of the existing kaldi model, for example, the Aspire model? I'm new to kaldi, appreciate it if someone can guide to do that.

thanks!

**Comment by danpovey** [comment]
You should look for discussions of this on the list.  I don't have time right now to answer such generic questions.  In general, it's hard to get improvements for this kind of thing (in most scenarios).
