### ISSUE TITLE
CUDA 8.0 incompatibility

### ISSUE THREAD

**Issue by danpovey** [kaldi-asr/kaldi#3099]
It looks like some recent changes have broken CUDA 8.0 compatibility.
From this kaldi-help thread
https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/kaldi-help/aImqiQX18dE/J9d1pP0MBwAJ

@luitjens, do you think we should e.g. control it with ifdefs somehow or just unsupport those versions?
I think some recent changes I merged from you guys must have stopped it working.
```
I have encountered some errors when trying to install Kaldi on a paper space GPU machine. I have followed the run the following series of commands. Any help would be appreciated

cd tools
make CXX=g++-4.8 -j 8 (successful)
cd ../src
./configure --shared (successful. attached the log config_shared.log)
make CXX=g++-4.8 depend -j 8 (successful, attached the log make_depend.log)
make CXX=g++-4.8 -j 8 (unsuccessful, attached the log make.log)

The snippet of the error log is as follows

In file included from cu-device.cc:37:0:
cu-device.cc: In member function ‘void kaldi::CuDevice::Initialize()’:
cu-device.cc:118:13: error: ‘CUBLAS_TENSOR_OP_MATH’ was not declared in this scope
             CUBLAS_TENSOR_OP_MATH));
             ^
../cudamatrix/cu-common.h:49:15: note: in definition of macro ‘CUBLAS_SAFE_CALL’
   if ((ret = (fun)) != 0) { \
               ^
cu-device.cc:118:34: error: ‘cublasSetMathMode’ was not declared in this scope
             CUBLAS_TENSOR_OP_MATH));
                                  ^
../cudamatrix/cu-common.h:49:15: note: in definition of macro ‘CUBLAS_SAFE_CALL’
   if ((ret = (fun)) != 0) { \
               ^
make[1]: *** [cu-device.o] Error 1
make[1]: Leaving directory `/home/paperspace/kaldi/src/cudamatrix'
make: *** [cudamatrix] Error 2

```

**Comment by luitjens** [comment]
I would just use this compiler guard around the cublasSetMathMode call.

#if CUDART_VERSION>=9000
   cublasSetMathMode(...);
#endif

You may have to add
#include <cuda_runtime_api.h>

To get that #define.

**Comment by danpovey** [comment]
Thanks!  @desh2608 can you please make a PR for this?  Obviously test that it compiles on our grid.  And spaces around operators (>=).

**Comment by desh2608** [comment]
Yeah, sure.

**Comment by rickychanhoyin** [comment]
I had similar issue and I fixed it by 

diff --git a/src/cudamatrix/cu-device.cc b/src/cudamatrix/cu-device.cc
index 140275d..d7ef0af 100644
--- a/src/cudamatrix/cu-device.cc
+++ b/src/cudamatrix/cu-device.cc
@@ -111,12 +111,14 @@ void CuDevice::Initialize() {
     CUBLAS_SAFE_CALL(cublasCreate(&cublas_handle_));
     CUBLAS_SAFE_CALL(cublasSetStream(cublas_handle_, cudaStreamPerThread));
     
+    #if CUDA_VERSION >= 9000
     if (device_options_.use_tensor_cores) {
       // Enable tensor cores in CUBLAS
       // Note if the device does not support tensor cores this will fall back to normal math mode
       CUBLAS_SAFE_CALL(cublasSetMathMode(cublas_handle_, 
             CUBLAS_TENSOR_OP_MATH));
     }
+    #endif
 
     // Initialize the cuSPARSE library
     CUSPARSE_SAFE_CALL(cusparseCreate(&cusparse_handle_));




// #include <cuda_runtime_api.h> is not nescessary in this case

**Comment by ravikirancap** [comment]
Hi @rickychanhoyin 
can you share your  src/cudamatrix/cu-device.cc file? I will update and check if it works for me

**Comment by rickychanhoyin** [comment]
My changes and Desh Raj (I believe) are on the current snapshot of Kaldi, you can just copy from  src/cudamatrix/cu-device.cc in the main trunk, and make two lines of modifications
