### ISSUE TITLE
signature call improvement

### ISSUE THREAD

**Issue by btiplitz** [kaldi-asr/kaldi#3107]
In the DecodableNnetSimpleLoopedInfo constructor, the interface has a pointer to Nnet (or AmNnetSimple.  It appears then to put a pointer to this into a "const Nnet &nnet".  Should the declaration have a const on the pointer ?.  S

ource code is in nnet3/decodable-simple-looped.cc/h

**Comment by danpovey** [comment]
No, it needs to do something that modifies the nnet.  But thanks for asking..
