### ISSUE TITLE
error when runing train_tanh_fast.sh

### ISSUE THREAD

**Issue by 313024351** [kaldi-asr/kaldi#3110]
The error in the log/train.0.1.log and log/train.1.1.log.But others are ok. the detail as flow:
ERROR (nnet-train-simple[5.5.243~1-8cafd]:ReorthogonalizeXt1():nnet-precondition-online.cc:222) Cholesky out of expected range, reorthogonalizing with Gram-Schmidt

[ Stack-Trace: ]
kaldi::MessageLogger::LogMessage() const
kaldi::MessageLogger::LogAndThrow::operator=(kaldi::MessageLogger const&)
kaldi::nnet2::OnlinePreconditioner::ReorthogonalizeXt1(kaldi::VectorBase<float> const&, float, kaldi::CuMatrixBase<float>*, kaldi::CuMatrixBase<float>*, kaldi::CuMatrixBase<float>*)
kaldi::nnet2::OnlinePreconditioner::PreconditionDirectionsInternal(int, float, kaldi::Vector<float> const&, kaldi::CuMatrixBase<float>*, kaldi::CuMatrixBase<float>*, kaldi::CuVectorBase<float>*, float*)
kaldi::nnet2::OnlinePreconditioner::PreconditionDirections(kaldi::CuMatrixBase<float>*, kaldi::CuVectorBase<float>*, float*)
kaldi::nnet2::OnlinePreconditioner::PreconditionDirections(kaldi::CuMatrixBase<float>*, kaldi::CuVectorBase<float>*, float*)
kaldi::nnet2::OnlinePreconditioner::Init(kaldi::CuMatrixBase<float> const&)
kaldi::nnet2::OnlinePreconditioner::PreconditionDirections(kaldi::CuMatrixBase<float>*, kaldi::CuVectorBase<float>*, float*)
kaldi::nnet2::AffineComponentPreconditionedOnline::Update(kaldi::CuMatrixBase<float> const&, kaldi::CuMatrixBase<float> const&)
kaldi::nnet2::AffineComponent::Backprop(kaldi::nnet2::ChunkInfo const&, kaldi::nnet2::ChunkInfo const&, kaldi::CuMatrixBase<float> const&, kaldi::CuMatrixBase<float> const&, kaldi::CuMatrixBase<float> const&, kaldi::nnet2::Component*, kaldi::CuMatrix<float>*) const
kaldi::nnet2::NnetUpdater::Backprop(kaldi::CuMatrix<float>*) const
kaldi::nnet2::NnetUpdater::ComputeForMinibatch(std::vector<kaldi::nnet2::NnetExample, std::allocator<kaldi::nnet2::NnetExample> > const&, kaldi::Matrix<float>*, double*)
kaldi::nnet2::DoBackprop(kaldi::nnet2::Nnet const&, std::vector<kaldi::nnet2::NnetExample, std::allocator<kaldi::nnet2::NnetExample> > const&, kaldi::Matrix<float>*, kaldi::nnet2::Nnet*, double*)
kaldi::nnet2::TrainNnetSimple(kaldi::nnet2::NnetSimpleTrainerConfig const&, kaldi::nnet2::Nnet*, kaldi::SequentialTableReader<kaldi::KaldiObjectHolder<kaldi::nnet2::NnetExample> >*, double*, double*)
main
__libc_start_main
_start
What is going on this error? Thanks.

**Comment by danpovey** [comment]
That is not the real error-- its exception would have been caught.  Find the real error and read its error message, I am sure it is very clear about why it happened.
Regardless, that script is very old and deprecated, you should be using up-to-date nnet3/chain scripts, such as local/chain/run_tdnn.sh.
