### ISSUE TITLE
Finish vector-stride stuff

### ISSUE THREAD

**Issue by danpovey** [kaldi-asr/kaldi#3122]
This is for the new branch of kaldi (Kaldi10).

(Note, it's not possible to compile the entire codebase yet, due to other changes I drafted but did not finish.)

I would like someone to finish some code changes relating to vector stride.  There are two parts to this.
 In kaldi-vector.cc, I changed the functions to properly use the stride up to about line 844.  From there, the functions still need to be modified.  I am also changing things so they properly declare local variables that are copies of data_, dim_, etc., to avoid possible unnecessary memory lookups (I am not sure how aggressive modern C++ compilers are about re-fetching things from memory in case another thread modified them).

We also need to write some test code that will actually test things in cases where the strides are not 1.  (Note: negative strides are supported too, so e.g. a function 
`   SubVector<Real>  VectorBase<Real>::Flip() const;`
could be added, which might be an easy way to augment the tests).

Also the same changes need to be added to class CuVector, so that it also supports stride.  If someone attempts  CPU<--> GPU copies on vectors of strides != 1, it will probably be easiest to just use temporaries with stride 1 as needed to accomplish the transfer.

**Comment by YiwenShaoStephen** [comment]
@danpovey I noticed that there are some functions before line 844 are still without stride support, like IsZero(), SetRandn(). Are they designed to be unchanged? Or should every function be added with stride?

**Comment by danpovey** [comment]
Everything is going to support a stride, those were probably just omissions.
