### ISSUE TITLE
KWS 

### ISSUE THREAD

**Issue by ckn123** [kaldi-asr/kaldi#3137]
Hello, I want to calculate ATWV on bable/s5b/loacal/kws_score.sh with my own file.
[help_message="$0: score the kwslist using the F4DE scorer from NIST
   Example:
     $0 [additional-parameters] <kaldi-data-dir> <kws-results-dir>
     Where the most important additional parameters can be:
     --extraid <extra-id> #for using, when a non-default kws tasks are setup
               (using the kws_setup.sh --extraid) for a kaldi-single data-dir
     --kwlist <kwlist> #allows for an alternative kwlist -- if not set, the default
               Kwlist is taken from <kaldi-data-dir>
     --f4de-prefix <prefix-id> #allows for scoring the same results using
               Different kwlists and storing them in the same dir "]
This parameter setting inside, I don't quite understand what is said inside. Can you give me a case study and give me a reference?

**Comment by jtrmal** [comment]
I suggest looking at the minilibrispeech example. It's substantially easier
to follow and understand
y.
