### ISSUE TITLE
I-vector in nnet3

### ISSUE THREAD

**Issue by 313024351** [kaldi-asr/kaldi#3140]
I extracted I-vector in the "sid" with DNN,and when I using I-Vector in the nnet3,i found no where can I fill the "I-vector path".It just have "online_ivector_dir".
    I want to use the I-vector that extracted with DNN in the nnet3.What should I do can?
Thanks

**Comment by danpovey** [comment]
We don't have very easy support for that in the scripts, but we did experiments with that type of thing and didn't really see any improvement in ASR performance.  I think you should just train a normal i-vector extractor.
