### ISSUE TITLE
A GPU related issue

### ISSUE THREAD

**Issue by jinxie0731** [kaldi-asr/kaldi#3160]
I succeed in compiling kaldi with CUDA=true, but when I executed "make test" in the path of src/cudamatrix, I got a lot of errors, how to fix this issue?
Any suggestion is welcome, thank you very much!

errors:
src/cudamatrix$ make test
... ...
Running cu-vector-test .../bin/bash: line 1: 26582 Aborted                 (core dumped) ./$x > $x.testlog 2>&1
 0s... FAIL cu-vector-test
Running cu-matrix-test .../bin/bash: line 1: 26588 Aborted                 (core dumped) ./$x > $x.testlog 2>&1
 4s... FAIL cu-matrix-test
Running cu-math-test .../bin/bash: line 1: 26605 Aborted                 (core dumped) ./$x > $x.testlog 2>&1
 5s... FAIL cu-math-test
Running cu-test .../bin/bash: line 1: 26624 Aborted                 (core dumped) ./$x > $x.testlog 2>&1
 2s... FAIL cu-test
Running cu-sp-matrix-test .../bin/bash: line 1: 26640 Aborted                 (core dumped) ./$x > $x.testlog 2>&1
 2s... FAIL cu-sp-matrix-test
Running cu-packed-matrix-test .../bin/bash: line 1: 26654 Aborted                 (core dumped) ./$x > $x.testlog 2>&1
 2s... FAIL cu-packed-matrix-test
Running cu-tp-matrix-test .../bin/bash: line 1: 26670 Aborted                 (core dumped) ./$x > $x.testlog 2>&1
 0s... FAIL cu-tp-matrix-test
Running cu-block-matrix-test .../bin/bash: line 1: 26684 Aborted                 (core dumped) ./$x > $x.testlog 2>&1
 2s... FAIL cu-block-matrix-test
Running cu-matrix-speed-test .../bin/bash: line 1: 26703 Aborted                 (core dumped) ./$x > $x.testlog 2>&1
 28s... FAIL cu-matrix-speed-test
Running cu-vector-speed-test .../bin/bash: line 1: 26741 Aborted                 (core dumped) ./$x > $x.testlog 2>&1
 1s... FAIL cu-vector-speed-test
Running cu-sp-matrix-speed-test .../bin/bash: line 1: 26755 Aborted                 (core dumped) ./$x > $x.testlog 2>&1
 1s... FAIL cu-sp-matrix-speed-test
Running cu-array-test .../bin/bash: line 1: 26770 Aborted                 (core dumped) ./$x > $x.testlog 2>&1
 1s... FAIL cu-array-test
Running cu-sparse-matrix-test .../bin/bash: line 1: 26784 Aborted                 (core dumped) ./$x > $x.testlog 2>&1
 1s... FAIL cu-sparse-matrix-test
Running cu-device-test ... 4s... SUCCESS cu-device-test
Running cu-rand-speed-test .../bin/bash: line 1: 26818 Aborted                 (core dumped) ./$x > $x.testlog 2>&1
 2s... FAIL cu-rand-speed-test
Running cu-compressed-matrix-test .../bin/bash: line 1: 26834 Aborted                 (core dumped) ./$x > $x.testlog 2>&1
 1s... FAIL cu-compressed-matrix-test
../makefiles/default_rules.mk:80: recipe for target 'test' failed
make: *** [test] Error 1

**If run cu-array-test individually, I get the following log:**
```
./cu-array-test 
LOG ([5.4.155~1-fdd8]:SelectGpuId():cu-device.cc:123) Manually selected to compute on CPU.
LOG ([5.4.155~1-fdd8]:main():cu-array-test.cc:136) Tests without GPU use succeeded.
WARNING ([5.4.155~1-fdd8]:SelectGpuId():cu-device.cc:196) Not in compute-exclusive mode.  Suggestion: use 'nvidia-smi -c 3' to set compute exclusive mode
LOG ([5.4.155~1-fdd8]:SelectGpuIdAuto():cu-device.cc:315) Selecting from 1 GPUs
LOG ([5.4.155~1-fdd8]:SelectGpuIdAuto():cu-device.cc:330) cudaSetDevice(0): GeForce GTX 1050 Ti with Max-Q Design	free:3538M, used:502M, total:4041M, free/total:0.875576
LOG ([5.4.155~1-fdd8]:SelectGpuIdAuto():cu-device.cc:379) Trying to select device: 0 (automatically), mem_ratio: 0.875576
LOG ([5.4.155~1-fdd8]:SelectGpuIdAuto():cu-device.cc:398) Success selecting device 0 free mem ratio: 0.875576
LOG ([5.4.155~1-fdd8]:FinalizeActiveGpu():cu-device.cc:247) The active GPU is [0]: **GeForce GTX 1050 Ti** with Max-Q Design	free:3502M, used:538M, total:4041M, free/total:0.866668 version 6.1
ERROR ([5.4.155~1-fdd8]:Set():cu-array.cc:74) cudaError_t 8 : "invalid device function" returned from 'cudaGetLastError()'

[ Stack-Trace: ]
./cu-array-test() [0x62a82c]
kaldi::MessageLogger::HandleMessage(kaldi::LogMessageEnvelope const&, char const*)
kaldi::MessageLogger::~MessageLogger()
kaldi::CuArrayBase<int>::Set(int const&)
./cu-array-test() [0x4ca89f]
main
__libc_start_main
_start

terminate called after throwing an instance of 'std::runtime_error'
  what():  
Aborted (core dumped)


**I also past my CUDA information here.**

nvcc -V
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2015 NVIDIA Corporation
Built on Tue_Aug_11_14:27:32_CDT_2015
Cuda compilation tools, release 7.5, V7.5.17
```

**Comment by danpovey** [comment]
Probably it's because your CUDA toolkit is too old for that hardware, you should upgrade it.
Also your version of Kaldi is pretty old, but that may not be the reason.
