### ISSUE TITLE
ivector-extractor-est's parameter

### ISSUE THREAD

**Issue by 313024351** [kaldi-asr/kaldi#3166]
Usage：ivector-extractor-est [options] <modle-in> <stats-in> <model-out>
Question：
 1. What is the <stats-in>'s effect in ivector-extractor-est ? And I do not know what is the means of the Comment "Sum accumulators for training of iVector extractor" in vector-extractor-sum-accs.cc.
 2. How can modle-in(*.ie) init ? It is random?
Thanks.

**Comment by danpovey** [comment]
It's an E-M procedure.  Look it up.  Most of your question was not understandable to me.
