### ISSUE TITLE
Nnet3::Nnet::Read() vs Nnet3::Nnet::Write() 

### ISSUE THREAD

**Issue by mohamedAlaaK** [kaldi-asr/kaldi#3168]
i am using nnet3-train to train a model and it writes a .raw file to disk
then i use nnet3-average on this .raw which all it does is loading the .raw file and then writes it on disk.
i compared the 2 .raw files with md5sum and they are different.

i reproduced this issue by typing a c++ file that all it does is ReadKaldiObject() and then WriteKaldiObject() and again input and output .raw files are different.

am i missing something here ?

**Comment by danpovey** [comment]
You could use nnet3-info to figure out how they are different.  But I assure you that whatever it is, it's something that doesn't matter.   Probably to do with some kind of diagnostics or roundoff effects.

**Comment by mohamedAlaaK** [comment]
converting both of them to .mdl files using nnet3-am-copy and using them to decode some data
they produce a 13% difference in word error rate.

**Comment by danpovey** [comment]
You should use nnet3-info to see how they differ, as I said.  E.g. could be batchnorm components.
But if you use the provided scripts to train, it should just work.
