### ISSUE TITLE
difference between MLLT and STC

### ISSUE THREAD

**Issue by mahuichao** [kaldi-asr/kaldi#3176]
hi,now I am learning algorithms behind the code .I have seen the **MLLT** source code,**official tutoria**l :"Feature and model-space transforms in Kaldi" and the###  paper : "maximum-likelihood-modeling-with-gaussian-distributions-for-classification","Semi-Tied Covariance Matrices for Hidden Markov Models".
Something confusing me,in ur tutorial **STC** and **MLLT** should be the same algorithm right?But I didn't find any connection between them,and one is transformed in **feature space** and the other one is transformed in **model space**,can you tell me some difference  between them?
Thanks in advance.By the way,kaldi is awesommmmm~~~e!

**Comment by danpovey** [comment]
They are the same thing, just different presentations.  Read the respective papers and think about it, I certainly don't have time.

**Comment by mahuichao** [comment]
@danpovey all right,still thanks for replying.At least I know they two are indeed the same thing.
