### ISSUE TITLE
How to compute nnet3 models' left-context and right-context when models have 'Round' descriptors?

### ISSUE THREAD

**Issue by TonyMou** [kaldi-asr/kaldi#3179]
I am writing python scripts to calculate left-context and right-context for nnet3 models and got stuck with round descriptors.
After reading the computation graph codes and it seems like that in order to calculate the contexts we need to feed inputs with different window size and run the computation for several rounds.

Is it possible to calculate the left context and right context just by parsing a *.mdl file. Could you provide any suggestion on this?  Thanks!

**Comment by danpovey** [comment]
Why don't you just do nnet3-info and get the left and right context from
its output?

You can safely ignore the Round() descriptors, as they are not used in any
of the architectures we use.

Dan

**Comment by TonyMou** [comment]
We are working on converting kaldi models to onnx, to make it more portable we prefer to just using a python tool to do the converting.
We've tried ignoring the Round() descriptors and just adding all the splice's(fused by Offset() and Append()) left and right contexts, but in some models with Round(), the results are different from using nnet3-info, such as the model in sre16_v2_1a.

**Comment by danpovey** [comment]
Oh, it's nice that you are doing that,

If you look at the code that computes the left and right context (I think
it's in nnet-utils.cc), it works out what it calls the 'modulus' of the
network, which is the least common multiple of the time-value in all the
Round() nodes (in a simple network it would just be the value you are
rounding to, like 10).   The left/right context is computed by taking a
chunk of input and seeing which outputs are computable.  The code takes
that chunk of input and shifts it to the right by all values n in [0, 1,
... modulus - 1], and for all of those values it computes the left/right
context, and the result is the largest of the left and right context
respectively over all those shifts.

In simple cases like the SRE examples that have, a single Round descriptor
like Round(, ..., 10), you could probably just add 9 to the left-context,
that would probably give you the correct value.


Dan

**Comment by TonyMou** [comment]
@danpovey Thanks for your detailed description. We've solved this problem.
