### ISSUE TITLE
How to get the posterior output from chain denominator forward-backward operation

### ISSUE THREAD

**Issue by panxin801** [kaldi-asr/kaldi#3181]
Hello. Using nnet3-Chain recipe, I have trained a TDNN model and I want to get the posterior formation output of forward-backward over denominator lattice or graph. Can you tell me what should I do next? 
To change c++ code or which tools should I use, can you give me guides on this. Thank you.

**Comment by danpovey** [comment]
It depends what format you want it in, but lattice-to-post is relevant, and the code inside it too.
