### ISSUE TITLE
Add train.py number of jobs leveling option to match number of GPUs

### ISSUE THREAD

**Issue by kkm000** [kaldi-asr/kaldi#3186]
I have 2 GPUs and am using a single machine for experimentation. Our current train.py scripts run the number of jobs with the increment of 1. This reduces my average GPU utilization somewhat, since odd-job-numbered iteration slack one GPU. 

I added a switch to train.py, `--trainer.optimization.num-jobs-step` to go with the multiple of N jobs as soon as the computed number of jobs reaches N. For 1 GPU, if you start with 1 job, there will be 1,2,4,6... jobs. For an example of 3 GPU, there could be 1,2,3,6,9...final.

I'd like to generalize that (it's a hack entirely in chain/train.py now, should go up to the library to generalize to other varieties of the trainer) and send a PR. Works for me, but I want to ask quickly if this is not a bad idea for some reason I'm unaware of.

**Comment by danpovey** [comment]
I think it's reasonable.

**Comment by kkm000** [comment]
Will do!
