### ISSUE TITLE
Can't build kaldi for android x86

### ISSUE THREAD

**Issue by Dr-Desty-Nova** [kaldi-asr/kaldi#3208]
Android NDK toolchains use `i686` as prefix for 32-bit x86 compilers/linkers.
![image](https://user-images.githubusercontent.com/49311045/55628577-c1975f00-57b9-11e9-950c-cd06bc2371a9.png)

But kaldi only allows x86 to be specified as a target.
This check is located here: https://github.com/kaldi-asr/kaldi/blob/ddeac9837a8f1e390a75948d0f34931a8f145c77/src/configure#L994

Can we relax it a bit to include i686 as a target?

**Comment by danpovey** [comment]
I would be fine with doing that but I would want to first hear that you have got it to work like that.  The android build stuff was made by people more knowledgeable than me about such matters.  I'm not sure how experienced an android developer you are, and whether you know about all the issues involved.

**Comment by Dr-Desty-Nova** [comment]
Yes, it successfully compiles after I relax the check. Moreover, my test suite that was originally for arm runs just fine, only had to add `-fPIC` to `CXXFLAGS`.

**Comment by danpovey** [comment]
OK.  Can you please make a pull request?

**Comment by Dr-Desty-Nova** [comment]
@danpovey sure, will do on Monday. Thanks for quick answers.

**Comment by kkm000** [comment]
@Dr-Desty-Nova, we do not have this in the contrib guidelines yet, but could you please keep two things in mind when putting up the PR: (1) preferably wrap the PR body text itself at column 70, roughly, as you type it in the GitHub PR form, and (2) add a line `Fixes #3208` at the end of the body? The reason for (1) is the body becomes the Git commit message. (In this case, hardly more that 72 characters would be needed anyway :))

**Comment by Dr-Desty-Nova** [comment]
@kkm000 , done, #3213
