### ISSUE TITLE
make error 

### ISSUE THREAD

**Issue by Orange15** [kaldi-asr/kaldi#321]
../util/kaldi-holder-inl.h:767:16: error: reinterpret_cast from
      'std::vector<float32>' to 'char *' is not allowed
      os.write(reinterpret_cast<char*> (tmp), sizeof(tmp));
               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
make[1]: *** [kaldi-table.o] Error 1
make[1]: *** Waiting for unfinished jobs....
make: *** [util] Error 2

**Comment by jtrmal** [comment]
You didn't provide any information about your system. What OS, what
compiler? Is it a recent version of Kaldi?
y.

**Comment by danpovey** [comment]
I had a look at the code there, and it does look like a bug.  This is in
some sphinx-feature-writing code that I think was never used, as we only
ever read sphinx features.  Probably his compiler is just more sensitive.
I'll fix it.
Dan

**Comment by danpovey** [comment]
Thanks-- fixed.  Closing.

**Comment by Orange15** [comment]
@danpovey, it is ok, thanks very much.
