### ISSUE TITLE
bad catch

### ISSUE THREAD

**Issue by btiplitz** [kaldi-asr/kaldi#3210]
when the change was put into the error handling to throw (which we already did), it brought up a problem with a few limited issues.  In cu-allocator, when a memory allocation fails, the call is to KALDI_ERR.  

In cu-allocator.cc:519, this call to KALDI_ERR I don't think should be caught and I believe perhaps this needs to be an assert?  If not catching, the behavior will end the program either way, but out of memory is a dangerous catch in almost every case

**Comment by danpovey** [comment]
There aren't any cases where we catch an error an attempt to continue, except an isolated case to do with the natural gradient code and failure of Cholesky decomposition (and in that case there are no allocations inside that code block, I believe).  So I think it's safe.
