### ISSUE TITLE
How to use?

### ISSUE THREAD

**Issue by VeliBaba** [kaldi-asr/kaldi#322]
Hi!
Please, explain me, how to use this toolkit for training and decoding?
In what format and structure must be my training data?

**Comment by jtrmal** [comment]
This is not how it works. You are supposed to read the docs (http://kaldi-asr.org/doc/), especially the Installation and Tutorial sections. I believe your questions are answered there.
Also, please refrain from using the github "Issues" to ask questions -- see http://kaldi-asr.org/forums.html to see how and where you can ask for help -- after reading the docs, please!
