### ISSUE TITLE
Training TDNN

### ISSUE THREAD

**Issue by vkothapally** [kaldi-asr/kaldi#3223]
I am trying use CHiME-5 recipe fro LF-MMI TDNN for a different dataset. I am done with triphone training, alignments and initialization of tdnn. However, when I run "steps/nnet3/chain/train.py" with the default parameters in the recipe I get this error. I checked at every stage for errors. I see few WARNINGS at different stages until I reach this step but no ERRORS which could have crashed the code in further stages.

"ERROR (chain-est-phone-lm:FindNonzeroLmStateIndexForHistory():language-model.cc:104) Error looking up LM state index for history (likely code bug)"

Any help how do I resolve this issue?

**Comment by danpovey** [comment]
The error message indicates it would likely be a problem  in the code.
If you send to me an archive containing  just the files necessary to
reproduce the problem, I will try to find time to fix the issue.

**Comment by vkothapally** [comment]
Thanks a lot for your quick response @danpovey. Here is a [link] to download the folder similar to s5 containing files which I think should be able to reproduce the same error. If any additional files are required, I can get back to you (https://utdallas.box.com/s/t36wpcs182e7pd9yqnl3plcb37x3myv7)

**Comment by danpovey** [comment]
That file is too big it would take half an hour to download (and another
half hour to upload to
CLSP where I would debug it).  can you upload a file with just what is
needed to run that one command line, that crashed?  It probably takes just
one or two files.

**Comment by vkothapally** [comment]
Sure! I have a folder and the error file in the link. To the best of my knowledge these files should be necessary and sufficient to trace the error. Thanks a lot again for your attention and help @danpovey. Means a lot.
(https://utdallas.box.com/s/mcmzgk7hu5yp9aeynmd4r4eqe4gbq4f2)

**Comment by danpovey** [comment]
I was not able to reproduce this error with current Kaldi code, and now I see that your code must be extremely old, because it doesn't even print the version number in the error message.  Fix: update your code.
