### ISSUE TITLE
`make_biased_lms.py` will fail when utterance IDs have utf8 chars.

### ISSUE THREAD

**Issue by RuABraun** [kaldi-asr/kaldi#3227]
I had a regression in performance due to [this](https://github.com/kaldi-asr/kaldi/commit/2e26464accd93b6d9949406e2dbda9450273e5f1) commit, which changed `make_biased_lms.py` to use python3. This caused an error on [this line](https://github.com/kaldi-asr/kaldi/blob/master/egs/wsj/s5/steps/cleanup/make_biased_lms.py#L65), when an utterance ID has a utf8 char, and as the same graph is used for a group of utterances, caused a significant amount of training data to be discarded.

I fixed it by removing utf8 chars from utterance IDs in my training pipeline, but thought it might be still worth making you guys aware of this, not sure what the best way of dealing with this is (I tried adding `.encode('utf-8')` but got some weird `UnicodeEncodeError [...] surrogates not allowed` error so I went the easy route of just getting rid of all the utf8 characters).

**Comment by danpovey** [comment]
@vimalmanohar  do you have time to fix this?
I am assuming the right way to do this is to announce that all the files' encodings, including the stdin and stdout of this program, are all utf-8 (and remove the '.endcode()'), but I don't remember the invocation.

**Comment by bringtree** [comment]
@RuABraun  Could you give me your train data? I may be can deal with this question.

**Comment by danpovey** [comment]
@bringtree  thankyou.  I had hoped @vimalmanohar would do it but he has a million things to do so if you can fix it that would be great. 

Actually, adding these lines
```
     sys.stdout = codecs.getwriter('UTF-8')(sys.stdout.buffer)
       sys.stdin = codecs.getreader('UTF-8')(sys.stdin.buffer)
```
somewhere near the top of the script might fix it.  Perhaps you could add that and attempt to verify that it still works where there is utf-8 in the utterance-id?  It doesn't have to be run as part of the script, just in isolation is fine.

**Comment by RuABraun** [comment]
Sorry @bringtree  I missed your comment somehow. Yeah all you need to reproduce it is have an utterance with a utf8 character.
