### ISSUE TITLE
decode with transform_dir.

### ISSUE THREAD

**Issue by 313024351** [kaldi-asr/kaldi#3231]
We trained nnet with nnet3's script and We expect decode with transform_dir, but it is not exist in nnet3/decode.
Could We use the nnet2/decode.sh to decode the nnet3's nnet with transform_dir?

**Comment by danpovey** [comment]
What script did you train with specifically?  I don't recall that we ever had any nnet3 scripts that supported transform_dir, since we always use raw MFCCs with ivectors.

**Comment by 313024351** [comment]
transform_dir in nnet3/lstm/train.sh.

**Comment by danpovey** [comment]
As that script says, it's deprecated.  The transform_dir parameter is no longer supported in the decoding script.
