### ISSUE TITLE
text file 'data/train/text' contains disallowed UTF-8 whitespace character(s)

### ISSUE THREAD

**Issue by Joee1995** [kaldi-asr/kaldi#3233]
When running this command `steps/make_mfcc.sh --cmd "$train_cmd" --nj 16 $x exp/make_mfcc/$x $mfccdir`, I receive an error  as follow:

> steps/make_mfcc.sh --cmd run.pl --nj 16 data/train exp/make_mfcc/data/train mfcc
utils/validate_text.pl: The line for utterance TIBETAN_01_01 contains CR (0x0D) character
utils/validate_text.pl: ERROR: text file 'data/train/text' contains disallowed UTF-8 whitespace character(s)

I check my `data/train/text` but have no idea. Anyone can help?

**Comment by danpovey** [comment]
You should have done a google search, you would have found posts on the forum.  This is not the right place to ask.
