### ISSUE TITLE
Does the accuracy of MINUTES(duration) in SPEAKERS.TXT have influence on the training model?

### ISSUE THREAD

**Issue by z384647062** [kaldi-asr/kaldi#3234]
I have been trying to use my own data set to train the model by using the scripts of _Librispeech_.
It was found that there is one column called _MINUTES(duration of the audio files)_ in the file _SPEAKERS.TXT_ in the origin data set of _Librispeech_.
Does the accuracy of _MINUTES_(calculated from the data set?) in _SPEAKERS.TXT_ have influence on the training model? Will it matter if I set a wrong number?

**Comment by danpovey** [comment]
That is just some metadata that has been computed from the underlying data.  It's not used anywhere in the model training process.  This kind of thing belongs on kaldi-help.
