### ISSUE TITLE
 MKL package intel-mkl-64bit-2019.2-057 installation FAILED. Not able to install Intel MKL

### ISSUE THREAD

**Issue by Palash1995** [kaldi-asr/kaldi#3253]
### Not able to install Intel MKL via extras/install_mkl.sh 
**below is the terminal output** 
` 
palash@KonvergePC:~/ASR/kaldi/tools$ sudo extras/install_mkl.sh
extras/install_mkl.sh: Your system is using debian-style package management.
+ apt-get update
Hit:1 https://download.sublimetext.com apt/dev/ InRelease                                                                                        
Hit:2 http://ppa.launchpad.net/apandada1/brightness-controller/ubuntu xenial InRelease                                                                                      
Hit:3 http://ppa.launchpad.net/mystic-mirage/pycharm/ubuntu xenial InRelease                                                                                                               
Hit:4 http://in.archive.ubuntu.com/ubuntu xenial InRelease                                                                                                                 
Get:5 http://in.archive.ubuntu.com/ubuntu xenial-updates InRelease [109 kB]                                                                                               
Hit:6 http://ppa.launchpad.net/qbittorrent-team/qbittorrent-stable/ubuntu xenial InRelease                                     
Hit:7 http://ppa.launchpad.net/ravefinity-project/ppa/ubuntu xenial InRelease                                                                                                                              
Get:8 http://in.archive.ubuntu.com/ubuntu xenial-backports InRelease [107 kB]                                                                                                                              
Get:9 http://security.ubuntu.com/ubuntu xenial-security InRelease [109 kB]                                                                                                                                 
Ign:10 http://www.getdeb.net/ubuntu xenial-getdeb InRelease                                                                                                                                                
Ign:11 http://www.getdeb.net/ubuntu xenial-getdeb Release                                                                                                                                                  
Ign:12 http://www.getdeb.net/ubuntu xenial-getdeb/a amd64 Packages                                                                                                                                         
Ign:13 http://www.getdeb.net/ubuntu xenial-getdeb/a i386 Packages                                                                                                                                          
Ign:14 http://www.getdeb.net/ubuntu xenial-getdeb/a all Packages                                                                                                                                           
Ign:15 http://www.getdeb.net/ubuntu xenial-getdeb/a Translation-en_IN                                                                                                                                      
Ign:16 http://www.getdeb.net/ubuntu xenial-getdeb/a Translation-en                                                                                                                                         
Ign:17 http://www.getdeb.net/ubuntu xenial-getdeb/a amd64 DEP-11 Metadata                                                                                                                                  
Ign:18 http://www.getdeb.net/ubuntu xenial-getdeb/a DEP-11 64x64 Icons                                                                                                                                     
Ign:12 http://www.getdeb.net/ubuntu xenial-getdeb/a amd64 Packages                                                                                                                                         
Ign:13 http://www.getdeb.net/ubuntu xenial-getdeb/a i386 Packages                                                                                                                                          
Ign:14 http://www.getdeb.net/ubuntu xenial-getdeb/a all Packages                                                                                                                                           
Ign:15 http://www.getdeb.net/ubuntu xenial-getdeb/a Translation-en_IN
Ign:16 http://www.getdeb.net/ubuntu xenial-getdeb/a Translation-en
Ign:17 http://www.getdeb.net/ubuntu xenial-getdeb/a amd64 DEP-11 Metadata
Ign:18 http://www.getdeb.net/ubuntu xenial-getdeb/a DEP-11 64x64 Icons
Ign:12 http://www.getdeb.net/ubuntu xenial-getdeb/a amd64 Packages
Ign:13 http://www.getdeb.net/ubuntu xenial-getdeb/a i386 Packages
Ign:14 http://www.getdeb.net/ubuntu xenial-getdeb/a all Packages
Ign:15 http://www.getdeb.net/ubuntu xenial-getdeb/a Translation-en_IN
Ign:16 http://www.getdeb.net/ubuntu xenial-getdeb/a Translation-en
Ign:17 http://www.getdeb.net/ubuntu xenial-getdeb/a amd64 DEP-11 Metadata
Ign:18 http://www.getdeb.net/ubuntu xenial-getdeb/a DEP-11 64x64 Icons
Ign:12 http://www.getdeb.net/ubuntu xenial-getdeb/a amd64 Packages
Ign:13 http://www.getdeb.net/ubuntu xenial-getdeb/a i386 Packages
Ign:14 http://www.getdeb.net/ubuntu xenial-getdeb/a all Packages
Ign:15 http://www.getdeb.net/ubuntu xenial-getdeb/a Translation-en_IN
Ign:16 http://www.getdeb.net/ubuntu xenial-getdeb/a Translation-en
Ign:17 http://www.getdeb.net/ubuntu xenial-getdeb/a amd64 DEP-11 Metadata
Ign:18 http://www.getdeb.net/ubuntu xenial-getdeb/a DEP-11 64x64 Icons
Ign:12 http://www.getdeb.net/ubuntu xenial-getdeb/a amd64 Packages
Ign:13 http://www.getdeb.net/ubuntu xenial-getdeb/a i386 Packages
Ign:14 http://www.getdeb.net/ubuntu xenial-getdeb/a all Packages
Ign:15 http://www.getdeb.net/ubuntu xenial-getdeb/a Translation-en_IN
Ign:16 http://www.getdeb.net/ubuntu xenial-getdeb/a Translation-en
Ign:17 http://www.getdeb.net/ubuntu xenial-getdeb/a amd64 DEP-11 Metadata
Ign:18 http://www.getdeb.net/ubuntu xenial-getdeb/a DEP-11 64x64 Icons
Err:12 http://www.getdeb.net/ubuntu xenial-getdeb/a amd64 Packages
  403  Forbidden
Ign:13 http://www.getdeb.net/ubuntu xenial-getdeb/a i386 Packages
Ign:14 http://www.getdeb.net/ubuntu xenial-getdeb/a all Packages
Ign:15 http://www.getdeb.net/ubuntu xenial-getdeb/a Translation-en_IN
Fetched 325 kB in 48s (6,682 B/s)
Reading package lists... Done
W: The repository 'http://archive.getdeb.net/ubuntu xenial-getdeb Release' does not have a Release file.
N: Data from such a repository can't be authenticated and is therefore potentially dangerous to use.
N: See apt-secure(8) manpage for repository creation and user configuration details.
E: Failed to fetch http://www.getdeb.net/ubuntu/dists/xenial-getdeb/a/binary-amd64/Packages  403  Forbidden
E: Failed to fetch http://www.getdeb.net/ubuntu/dists/xenial-getdeb/a/i18n/Translation-en  403  Forbidden
E: Failed to fetch http://www.getdeb.net/ubuntu/dists/xenial-getdeb/a/dep11/Components-amd64.yml  403  Forbidden
E: Failed to fetch http://www.getdeb.net/ubuntu/dists/xenial-getdeb/a/dep11/icons-64x64.tar  403  Forbidden
E: Some index files failed to download. They have been ignored, or old ones used instead.
extras/install_mkl.sh: MKL package intel-mkl-64bit-2019.2-057 installation FAILED.

Please open an issue with us at https://github.com/kaldi-asr/kaldi/ if you
believe this is a bug.
`
**Can anyone help me resolve this?**

**Comment by kkm000** [comment]
Find all lines that read `deb  http://www.getdeb.net/ ....`  in /etc/apt/sources.list and all files /etc/apt/sources.list.d/*.list, and remove them. This site went down in 2013. You must have noticed the same error when installing updates on your system.

**Comment by danpovey** [comment]
It's great to have  people on the team who know about this stuff!  I would
not have known how to fix that.

**Comment by Palash1995** [comment]
Thanks for the prompt response @kkm000 , @entn-at 

I didn't removed Forbidden `deb http://www.getdeb.net/....` links from the dir's as  I was able to install  intel-mkl-64bit-2019.2-057 by following the [official page](https://software.intel.com/en-us/articles/installing-intel-free-libs-and-python-apt-repo)

Although I have small doubts

a) If installation via install_mkl.sh didn't worked then which intel-mkl version we should install ? . Like in my case i have installed intel-mkl-64bit-2019.2-057, as i have received error for MKL package intel-mkl-64bit-2019.2-057 installation FAILED. We should always install latest intel-mkl version or the one which we received for ?

b) Through official installation [doc](https://software.intel.com/en-us/articles/installing-intel-free-libs-and-python-apt-repo) eventually i am doing sudo apt-get install intel-mkl-64bit-2019.2-057.  So if didn't removed the   Forbidden `deb http://www.getdeb.net/....` links in dir's then how come i am able to install this way?

Please forgive me if these queries seems very basic as i am very naive and just started with linux.

Regards,
Palash

**Comment by jtrmal** [comment]
because you have added another (alternative) repository (from Intel)
providing the package
I don't think anyone will spend much more time on it -- your system has
very outdated configuration for updates, so your problems wouldn't exist
normally.
y.
