### ISSUE TITLE
Online feature pipeline keeps mfcc features forever

### ISSUE THREAD

**Issue by rosun82** [kaldi-asr/kaldi#3258]
It seems that the `kaldi::OnlineNnet2FeaturePipeline` keeps the extracted features forever. Is there any possibilities to add interfaces to release the memory occupied by old features? In such case, the frames ready would become a range.

**Comment by danpovey** [comment]
That was addressed in #3038.  I believe if you put, say, --max-feature-vectors=500 in your mfcc.conf (or whatever type of feature config you have, in that online config directory), it should activate.
Caution: I am not sure if this has been tested with i-vectors + silence-weighting, it's possible that could crash.
