### ISSUE TITLE
kaldi-stream.h not found

### ISSUE THREAD

**Issue by csukuangfj** [kaldi-asr/kaldi#3262]
See the comment below
https://github.com/kaldi-asr/kaldi/blob/e3a9844aa35e2ad5437bb7e5cbfe8326fd28e635/src/util/kaldi-table.h#L81-L83

But there is no file called `kaldi-stream.h`

**Comment by danpovey** [comment]
It's kaldi-io.h.  If you make a PR to change it, I will merge.  Be sure to reference this issue in the PR's name so they are cross-referenced.

**Comment by csukuangfj** [comment]
@danpovey 
fixed in #3153
