### ISSUE TITLE
Error in the comment for wxfilename and rxfilename

### ISSUE THREAD

**Issue by csukuangfj** [kaldi-asr/kaldi#3264]
See the comment below
https://github.com/kaldi-asr/kaldi/blob/0cc941f7e5fd519a9ffba8c85adafee6d7db0b83/src/util/kaldi-io.h#L55-L72

For the wxfilename
> (3) A pipe: e.g.  "gunzip -c /tmp/abc.gz |"

which is actually an **rxfilename**.

For the rxfilename
> (3) A pipe: e.g. "| gzip -c > /tmp/abc.gz"

which is a **wxfilename**.

**Comment by danpovey** [comment]
Yes you're right. Please make a PR to fix this along with the other small errors you noticed.

**Comment by csukuangfj** [comment]
In addition, the following lists some misleading names in the source code:

----

https://github.com/kaldi-asr/kaldi/blob/0cc941f7e5fd519a9ffba8c85adafee6d7db0b83/src/util/kaldi-table.cc#L225-L227

`std::string *wxfilename,` should be `std::string *rxfilename,`

----

https://github.com/kaldi-asr/kaldi/blob/0cc941f7e5fd519a9ffba8c85adafee6d7db0b83/src/util/kaldi-table-test.cc#L91-L93

Even though `ClassifyWspecifier` does not check the validity of the string `foo|`, it is misleading to use an rxfilename here to demonstrate `ClassifyWspecifier`

**Comment by danpovey** [comment]
That's right, thanks.  Rather than making an issue for each one, I suggest
you accumulate them and make a PR with the fixes in one batch, which I can
review.

**Comment by csukuangfj** [comment]
@danpovey 
fixed in #3153
