### ISSUE TITLE
Error in the comment for WspecifierOptions

### ISSUE THREAD

**Issue by csukuangfj** [kaldi-asr/kaldi#3265]
See the comment below
https://github.com/kaldi-asr/kaldi/blob/0cc941f7e5fd519a9ffba8c85adafee6d7db0b83/src/util/kaldi-table.h#L69-L70

But the default is actually **not flush**

https://github.com/kaldi-asr/kaldi/blob/0cc941f7e5fd519a9ffba8c85adafee6d7db0b83/src/util/kaldi-table.h#L117

**Comment by csukuangfj** [comment]
fixed in #3153

**Comment by kkm000** [comment]
> fixed in #3153

Can you please do it the other way round, [close the issues from the PR](https://help.github.com/en/articles/closing-issues-using-keywords)?
