### ISSUE TITLE
broken link in wave-reader.h

### ISSUE THREAD

**Issue by csukuangfj** [kaldi-asr/kaldi#3266]
https://github.com/kaldi-asr/kaldi/blob/9e9ae13813a216c6b108e368099403018bc825cf/src/feat/wave-reader.h#L23-L25

https://ccrma.stanford.edu/courses/422/projects/WaveFormat/

is not accessible any more.

Furthermore, there is a **space** between `https://` and `ccrma`.

**Comment by kkm000** [comment]
I do not think the wave format is *specified* anywhere at all, in the sense of having a formal spec. I think it's totally ok to delete the sentence and the link, no point to maintain a link to a randomly selected description selected out of the million existing ones. Please push the fix into the PR you already have, if you're up to fixing it?
