### ISSUE TITLE
aishell train chain error 

### ISSUE THREAD

**Issue by frankhetao** [kaldi-asr/kaldi#3267]
my data is 15G aishell

steps/nnet3/chain/get_egs.sh: Number of utterances is very small. Please check your data.
Traceback (most recent call last):
  File "steps/nnet3/chain/train.py", line 624, in main
    train(args, run_opts)
  File "steps/nnet3/chain/train.py", line 387, in train
    stage=args.egs_stage)
  File "steps/libs/nnet3/train/chain_objf/acoustic_model.py", line 118, in generate_chain_egs
    egs_opts=egs_opts if egs_opts is not None else ''))
  File "steps/libs/common.py", line 158, in execute_command
    p.returncode, command))
Exception: Command exited with status 1: steps/nnet3/chain/get_egs.sh --frames-overlap-per-eg 0                 --cmd "run.pl --mem 8G"                 --cmvn-opts "--norm-means=false --norm-vars=false"                 --online-ivector-dir "exp/nnet3/ivectors_train_sp"                 --left-context 13                 --right-context 13                 --left-context-initial -1                 --right-context-final -1                 --left-tolerance '5'                 --right-tolerance '5'                 --frame-subsampling-factor 3                 --alignment-subsampling-factor 3                 --stage -10                 --frames-per-iter 1500000                 --frames-per-eg 150,110,90                 --srand 0                 data/train_sp_hires exp/chain/tdnn_1a_sp exp/tri5a_sp_lats exp/chain/tdnn_1a_sp/egs

[aishell train cmd log.txt](https://github.com/kaldi-asr/kaldi/files/3115752/aishell.train.cmd.log.txt)

**Comment by danpovey** [comment]
The log says
`steps/nnet3/chain/get_egs.sh: Number of utterances is very small. Please check your data.`
Probably you have less than 100 or 200  utterances.  You'd need thousands.
