### ISSUE TITLE
The active GPU is [0]: Unknown GPU	free:0M, used:0M, total:0M, free/total:-nan version 6.1

### ISSUE THREAD

**Issue by thesby** [kaldi-asr/kaldi#3269]
OS: ubuntu 18.04
CUDA: 10.1
GPU:  nvidia 1060 
DRIVER: 418.39

I tried `./cu-vector-test` and got an error:
```
./cu-vector-test 
LOG (cu-vector-test[5.5.277~1-b180]:SelectGpuId():cu-device.cc:138) Manually selected to compute on CPU.
-1.05384e+09 -1.05384e+09
-2.15126e+08 -2.15126e+08
LOG (cu-vector-test[5.5.277~1-b180]:main():cu-vector-test.cc:868) Tests without GPU use succeeded.
LOG (cu-vector-test[5.5.277~1-b180]:SelectGpuId():cu-device.cc:208) CUDA setup operating under Compute Exclusive Mode.
WARNING (cu-vector-test[5.5.277~1-b180]:DeviceGetName():cu-device.cc:493) Get GPU name fail with ret: 3
LOG (cu-vector-test[5.5.277~1-b180]:FinalizeActiveGpu():cu-device.cc:268) The active GPU is [0]: Unknown GPU	free:0M, used:0M, total:0M, free/total:-nan version 6.1
Floating point exception (core dumped)
```
I added at line 491 of file `cu-device.cc'
```
      // call the function
      int ret = cuDeviceGetName_ptr(name, len, dev);
	  if (ret != 0) {
		KALDI_WARN << "Get GPU name fail with ret: " << ret ;
	  }
```
The `ret` was 3,
```
This indicates that the CUDA driver has not been initialized with cuInit() or that initialization has failed.
```

**Comment by danpovey** [comment]
I have never seen that error before.  Maybe @luitjens might have some idea.

**Comment by luitjens** [comment]
A couple of thoughts.  1) Driver/toolkit missmatch.  2) bad or fake GPU.   

Did you buy your GPU from a legitimate source?  

https://www.guru3d.com/news-story/numerous-fake-nvidia-geforce-gtx-1060-graphics-cards-sold-on-ebay.html

Please provide full nvidia-smi -q output and the results of deviceQuery here.

**Comment by tomkocse** [comment]
@luitjens I encounter similar errors. I am using Tesla V100 GPUs, does anyone report error on using kaldi with V-series GPUs?

**Comment by luitjens** [comment]
How often do you see it?  Are you sharing the GPU across multiple processes?

**Comment by tomkocse** [comment]
I am setting up my new server so this is the first time I see it and I keep seeing.
I try to downgrade cuda from 10.0 to 9.2 but the problem is still there.
All the gpus are in exclusive mode.

**Comment by danpovey** [comment]
You haven't shown any pasted error, e.g. was it

Get GPU name fail with ret: 3

?

**Comment by tomkocse** [comment]
I don't have that warning of "Get GPU name fail with ret: 3"
My errors are as follows:

./cu-vector-test
LOG (cu-vector-test[5.5.335~1-cec89]:SelectGpuId():cu-device.cc:146) Manually selected to compute on CPU.
-1.05384e+09 -1.05384e+09
-2.15126e+08 -2.15126e+08
LOG (cu-vector-test[5.5.335~1-cec89]:main():cu-vector-test.cc:868) Tests without GPU use succeeded.
LOG (cu-vector-test[5.5.335~1-cec89]:SelectGpuId():cu-device.cc:216) CUDA setup operating under Compute Exclusive Mode.
WARNING (cu-vector-test[5.5.335~1-cec89]:DeviceGetName():cu-device.cc:497) cannot open libcuda.so
WARNING (cu-vector-test[5.5.335~1-cec89]:GetFreeGpuMemory():cu-allocator.cc:299) cannot open libcuda.so
LOG (cu-vector-test[5.5.335~1-cec89]:FinalizeActiveGpu():cu-device.cc:284) The active GPU is [4]: Unknown GPU   free:0M, used:0M, total:0M, free/total:1 version 7.0
WARNING (cu-vector-test[5.5.335~1-cec89]:GetFreeGpuMemory():cu-allocator.cc:299) cannot open libcuda.so
WARNING (cu-vector-test[5.5.335~1-cec89]:GetFreeGpuMemory():cu-allocator.cc:299) cannot open libcuda.so
LOG (cu-vector-test[5.5.335~1-cec89]:AllocateNewRegion():cu-allocator.cc:506) About to allocate new memory region of 1048576 bytes; current memory info is: free:0M, used:0M, total:0M, free/total:1
WARNING (cu-vector-test[5.5.335~1-cec89]:GetFreeGpuMemory():cu-allocator.cc:299) cannot open libcuda.so
LOG (cu-vector-test[5.5.335~1-cec89]:AllocateNewRegion():cu-allocator.cc:506) About to allocate new memory region of 1048576 bytes; current memory info is: free:0M, used:0M, total:0M, free/total:1
WARNING (cu-vector-test[5.5.335~1-cec89]:GetFreeGpuMemory():cu-allocator.cc:299) cannot open libcuda.so
LOG (cu-vector-test[5.5.335~1-cec89]:AllocateNewRegion():cu-allocator.cc:506) About to allocate new memory region of 2097152 bytes; current memory info is: free:0M, used:0M, total:0M, free/total:1
.... then the same statement keep repeating.

I could remove the warning of "cannot open libcuda.so" by setting
export LD_LIBRARY_PATH=/usr/local/cuda-10.0/lib64/stubs/:${LD_LIBRARY_PATH}
but the problem is still there.

My another question is that, is it necessary to provide libcuda.so at run time ?
It seems that I do not have that warning of missing libcuda.so in previous version of kaldi and CUDA.

**Comment by danpovey** [comment]
That's a different error.
The difference regarding finding lubcuda.so is probably about paths.  I wouldn't worry about it too much; if I see more of this error in future I'll look into changing the configure script.

**Comment by tomkocse** [comment]
@danpovey Can you advice how I should solve my errors? It seems that the program can't obtain a correct memory info.

Here is another version of my errors:
```
nnet3-chain-train --use-gpu=yes --apply-deriv-weights=False --l2-regularize=0.0 --leaky-hmm-coefficient=0.1 --xent-regularize=0.1 --print-interval=10 --momentum=0.0 --max-param-change=1.41421356237 --backstitch-training-scale=0.0 --backstitch-training-interval=1 --l2-regularize-factor=0.333333333333 --optimization.memory-compression-level=2 --srand=0 "nnet3-am-copy --raw=true --learning-rate=0.00075 --scale=1.0 exp/chain_cleaned/tdnn1c_sp/0.mdl - |nnet3-copy --edits='set-dropout-proportion name=* proportion=0.0' - - |" exp/chain_cleaned/tdnn1c_sp/den.fst 'ark,bg:nnet3-chain-copy-egs                          --frame-shift=2                         ark:exp/chain_cleaned/tdnn1c_sp/egs/cegs.2.ark ark:- |                         nnet3-chain-shuffle-egs --buffer-size=5000                         --srand=0 ark:- ark:- | nnet3-chain-merge-egs                         --minibatch-size=32 ark:- ark:- |' exp/chain_cleaned/tdnn1c_sp/1.2.raw
LOG (nnet3-chain-train[5.5.335~1-cec89]:SelectGpuId():cu-device.cc:216) CUDA setup operating under Compute Exclusive Mode.
LOG (nnet3-chain-train[5.5.335~1-cec89]:FinalizeActiveGpu():cu-device.cc:284) The active GPU is [1]: Unknown GPU        free:0M, used:0M, total:0M, free/total:1 version 7.0
nnet3-copy '--edits=set-dropout-proportion name=* proportion=0.0' - -
nnet3-am-copy --raw=true --learning-rate=0.00075 --scale=1.0 exp/chain_cleaned/tdnn1c_sp/0.mdl -
LOG (nnet3-am-copy[5.5.335~1-cec89]:main():nnet3-am-copy.cc:151) Copied neural net from exp/chain_cleaned/tdnn1c_sp/0.mdl to raw format as -
LOG (nnet3-copy[5.5.335~1-cec89]:ReadEditConfig():nnet-utils.cc:1311) Set dropout proportions for 13 components.
LOG (nnet3-chain-train[5.5.335~1-cec89]:AllocateNewRegion():cu-allocator.cc:506) About to allocate new memory region of 1048576 bytes; current memory info is: free:0M, used:0M, total:0M, free/total:1
LOG (nnet3-chain-train[5.5.335~1-cec89]:AllocateNewRegion():cu-allocator.cc:506) About to allocate new memory region of 1048576 bytes; current memory info is: free:0M, used:0M, total:0M, free/total:1
LOG (nnet3-chain-train[5.5.335~1-cec89]:AllocateNewRegion():cu-allocator.cc:506) About to allocate new memory region of 1048576 bytes; current memory info is: free:0M, used:0M, total:0M, free/total:1
LOG (nnet3-chain-train[5.5.335~1-cec89]:AllocateNewRegion():cu-allocator.cc:506) About to allocate new memory region of 1048576 bytes; current memory info is: free:0M, used:0M, total:0M, free/total:1
LOG (nnet3-chain-train[5.5.335~1-cec89]:AllocateNewRegion():cu-allocator.cc:506) About to allocate new memory region of 1048576 bytes; current memory info is: free:0M, used:0M, total:0M, free/total:1

```

**Comment by danpovey** [comment]
I don't see any errors there, if it was an error it would say ERROR.

**Comment by tomkocse** [comment]
The problem is that it keeps looping of requesting a small piece of memory when the GPU seems to have 0M of free memory. When I check with nvidia-smi, that particular GPU should have enough free memory for use.

**Comment by danpovey** [comment]
Looks like your GPU is not properly reporting the memory info, and the GPU
type is "unknown GPU".  maybe one of those fake GPUs?

**Comment by luitjens** [comment]
please paste the output of nvidia-smi.  is this within a VM or container?

**Comment by tomkocse** [comment]
@luitjens It is not within a VM or container.
This is the ouput of nvidia-smi
```
Thu May 23 10:15:04 2019
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 410.48                 Driver Version: 410.48                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla V100-PCIE...  Off  | 00000000:04:00.0 Off |                    0 |
| N/A   34C    P0    34W / 250W |      0MiB / 16130MiB |      0%   E. Process |
+-------------------------------+----------------------+----------------------+
|   1  Tesla V100-PCIE...  Off  | 00000000:06:00.0 Off |                    0 |
| N/A   34C    P0    36W / 250W |      0MiB / 16130MiB |      0%   E. Process |
+-------------------------------+----------------------+----------------------+
|   2  Tesla V100-PCIE...  Off  | 00000000:07:00.0 Off |                    0 |
| N/A   36C    P0    37W / 250W |      0MiB / 16130MiB |      0%   E. Process |
+-------------------------------+----------------------+----------------------+
|   3  Tesla V100-PCIE...  Off  | 00000000:08:00.0 Off |                    0 |
| N/A   34C    P0    36W / 250W |      0MiB / 16130MiB |      0%   E. Process |
```

**Comment by luitjens** [comment]
thanks is there anything suspicious in dmesg?

I'm not aware of any fake v100s and would be surprised if this were the
case.  I'll review the code that sets the gpu tomorrow.

**Comment by danpovey** [comment]
You sure you compiled Kaldi with 10.1?

**Comment by tomkocse** [comment]
Yes, I set the cuda path I run ./configure before compilation.

**Comment by luitjens** [comment]
do the Nvidia samples like device query run fine?  can you provide output
from device query?

**Comment by tomkocse** [comment]
I just upgrade CUDA from 10.0 to 10.1 and the problem is solved. 
I am using driver version 418.67 now and kaldi can properly obtain the GPU type and memory info.
Thank you for your time on looking at the problem.

**Comment by TangShuai-HUST** [comment]
Hi,
I meet the same problem. I am using driver version 418.67 and cuda 10.1.168.
My errors are as follows:
./cuda-gpu-available 
LOG ([5.5.0-6c816]:main():cuda-gpu-available.cc:60) 
LOG ([5.5.0-6c816]:SelectGpuId():cu-device.cc:223) CUDA setup operating under Compute Exclusive Mode.
LOG ([5.5.0-6c816]:FinalizeActiveGpu():cu-device.cc:308) The active GPU is [0]: Unknown GPU     free:0M, used:0M, total:0M, free/total:1 version 6.1
### HURRAY, WE GOT A CUDA GPU FOR COMPUTATION!!! ##

### Testing CUDA setup with a small computation (setup = cuda-toolkit + gpu-driver + kaldi):
### Test OK!

nvidia-smi outputs are follows:
![image](https://user-images.githubusercontent.com/15995403/63686074-90383200-c833-11e9-98cc-6aa9dff754e3.png)

**Comment by TangShuai-HUST** [comment]
> Hi,
> I meet the same problem. I am using driver version 418.67 and cuda 10.1.168. How to slove it ?
> 
> My errors are as follows:
> ./cuda-gpu-available
> LOG ([5.5.0-6c816]:main():cuda-gpu-available.cc:60)
> LOG ([5.5.0-6c816]:SelectGpuId():cu-device.cc:223) CUDA setup operating under Compute Exclusive Mode.
> LOG ([5.5.0-6c816]:FinalizeActiveGpu():cu-device.cc:308) **The active GPU is [0]: Unknown GPU free:0M, used:0M, total:0M, free/total:1 version 6.1**
> ##HURRAY, WE GOT A CUDA GPU FOR COMPUTATION!!! ##
> 
> ###Testing CUDA setup with a small computation (setup = cuda-toolkit + gpu-driver + kaldi):
> ###Test OK!
> 
> nvidia-smi outputs are follows:
> ![image](https://user-images.githubusercontent.com/15995403/63686074-90383200-c833-11e9-98cc-6aa9dff754e3.png)

I have solve the problem by change the libcuda.so. When I update the gpu driver, it change the libcuda.so to link to the error file.

**Comment by TangShuai-HUST** [comment]
> When was your Kaldi code updated? I wasn't expecting 5.5.0, I'd expect 5.5.xxx with x a 3-digit number at least. I don't know that that would be the issue, but it might be relevant.
> Also, if you previously compiled with an older CUDA toolkit version you might want to `make clean` and re-make.

Thank Dan quickly to reply the question.

 I have solve the problem by change the libcuda.so. When I update the gpu driver, it change the libcuda.so to link to the error file.

**Comment by AIwzx** [comment]
I meet the same problem
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 440.100      Driver Version: 440.100      CUDA Version: 10.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+=================
|   0  GeForce RTX 208...  Off  | 00000000:01:00.0 Off |                  N/A |
| 27%   39C    P8     1W / 250W |    264MiB / 11016MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   1  GeForce RTX 208...  Off  | 00000000:02:00.0 Off |                  N/A |
| 27%   35C    P8     4W / 250W |   7356MiB / 11019MiB |      0%      Default |

my error :
./cu-vector-test 
LOG (cu-vector-test[5.5.769~2-ff4cb]:SelectGpuId():cu-device.cc:153) Manually selected to compute on CPU.
-1.05384e+09 -1.05384e+09
-2.15126e+08 -2.15126e+08
LOG (cu-vector-test[5.5.769~2-ff4cb]:main():cu-vector-test.cc:868) Tests without GPU use succeeded.
WARNING (cu-vector-test[5.5.769~2-ff4cb]:SelectGpuId():cu-device.cc:228) Not in compute-exclusive mode.  Suggestion: use 'nvidia-smi -c 3' to set compute exclusive mode
LOG (cu-vector-test[5.5.769~2-ff4cb]:SelectGpuIdAuto():cu-device.cc:408) Selecting from 2 GPUs
WARNING (cu-vector-test[5.5.769~2-ff4cb]:DeviceGetName():cu-device.cc:548) cannot open libcuda.so
WARNING (cu-vector-test[5.5.769~2-ff4cb]:GetFreeGpuMemory():cu-allocator.cc:299) cannot open libcuda.so
LOG (cu-vector-test[5.5.769~2-ff4cb]:SelectGpuIdAuto():cu-device.cc:423) cudaSetDevice(0): Unknown GPU	free:0M, used:0M, total:0M, free/total:1
WARNING (cu-vector-test[5.5.769~2-ff4cb]:DeviceGetName():cu-device.cc:548) cannot open libcuda.so
WARNING (cu-vector-test[5.5.769~2-ff4cb]:GetFreeGpuMemory():cu-allocator.cc:299) cannot open libcuda.so
LOG (cu-vector-test[5.5.769~2-ff4cb]:SelectGpuIdAuto():cu-device.cc:423) cudaSetDevice(1): Unknown GPU	free:0M, used:0M, total:0M, free/total:1
how can i solve it
