### ISSUE TITLE
error while installing the tool extras/install_sacc.sh

### ISSUE THREAD

**Issue by EgorLakomkin** [kaldi-asr/kaldi#3273]
Hi,

When I am trying to install the tool extras/install_sacc.sh, I get

    No Java Runtime Environment(JRE) was found on this system.

JRE should be bundled with the Matlab runtime which it downloads, but looks like it doesn't work.

**Comment by danpovey** [comment]
I don't know why you would be trying to do that, the only place sacc was ever used is in maybe the very first BABEL recipes, but we quickly replaced it with our own pitch extractor.  Closing the issue as I don't think it's likely something that needs fixing.
