### ISSUE TITLE
can not build with CUDA enabled

### ISSUE THREAD

**Issue by MaeThird** [kaldi-asr/kaldi#3277]
The source code is gitted from the  newest master and works well with cpu-only compiled.Because it's too slow,so I need to rebuild it with CUDA-enabled.

> 
**export CXX=/bin/g++-7
export CXXFLAGS="-O3"
./configure --use-cuda --cudatk-dir=/opt/cuda/ --cuda-arch=sm_61 --shared --mathlib=CLAPACK --clapack-root=/**
> 
But it failed at compiling cu-kernels.cu with
> 
**nvcc fatal   : A single input file is required for a non-link phase when an outputfile is specified
make[1]: *** [Makefile:32: cu-kernels.o] Error 1**
> 
My cuda version: 10.1 cudnn: 7.5.
Can anyone help?

**Comment by danpovey** [comment]
Show more output from make, eg what command generated the error?  And show
kaldi.mk

**Comment by kkm000** [comment]
`--cuda-arch` takes nvcc *flags*. As specified, nvcc thinks `sm_61` is an input file (and cu_kernels.cu is the second input file). Specify e.g. `--cuda-arch=-arch=sm_61` or `--cuda-arch='-gencode arch=compute_61,code=sm_61'`.

**Comment by MaeThird** [comment]
@kkm000 Thanks a lot. I'll try it immediately.
