### ISSUE TITLE
Possibility to support Bazel build?

### ISSUE THREAD

**Issue by rosun82** [kaldi-asr/kaldi#3282]
Dear repository owners,

I am wondering whether it would be possible to add sets of bazel BUILD files to Kaldi, so it can be compiled as a Bazel repository?

The potential benefit from this approach:

- Easier interoperability with other tools, such as Tensorflow.

- Faster build, if each build target contains only a handful of .cc files.

- Lower setup cost, if external dependencies can be imported and built automatically by Bazel.

Thanks

**Comment by danpovey** [comment]
No there is no such plan but if it's easy and you are willing, I would consider merging it.
