### ISSUE TITLE
BlockSoftmax recipe in RM

### ISSUE THREAD

**Issue by naxingyu** [kaldi-asr/kaldi#3293]
There are some running errors in blocksoftmax recipe in RM. Such as:
1. gzcat is not installed. It might be installed as alias of zcat? But no instructions.
2. WSJ alignments should have prefix 'wsj' instead of 'wsj_'.

Question is, do we fix such kind issues in almost deprecated scripts?

**Comment by danpovey** [comment]
I would't bother if I were you.  Can you please review that PR I mentioned you in?

**Comment by naxingyu** [comment]
ok

**Comment by naxingyu** [comment]
@danpovey I searched but find no open PR mentioning me. Would you please add the PR id here? Thanks!

**Comment by danpovey** [comment]
Oops sorry, I mixed you up with Shiyin Kang, who does CUDA stuff.  This is
CUDA related.  Forget about it.  But nice to hear from you.
