### ISSUE TITLE
Operational efficiency problem

### ISSUE THREAD

**Issue by flycat666** [kaldi-asr/kaldi#3298]
When I use more threads to calculate, the efficiency is not improved according to the number of threads. For example, it takes 10 hours to use 10 threads, and 7 hours instead of 5 hours when I use 20 threads.

**Comment by danpovey** [comment]
That's pretty normal, because you start to overload the CPU's memory
bandwidth.  It's the same with almost any types of task (except  perhaps
some very unusual mathematical problems that are CPU-bound)
Dan

**Comment by flycat666** [comment]
thanks
