### ISSUE TITLE
Uncompress() fail.

### ISSUE THREAD

**Issue by bringtree** [kaldi-asr/kaldi#3301]
the code:
![image](https://user-images.githubusercontent.com/20106478/57266304-f8f57600-70ad-11e9-81a5-afd5ee0ab303.png)
the log:
![image](https://user-images.githubusercontent.com/20106478/57266284-e2e7b580-70ad-11e9-972f-98b5958c97fe.png)

The log outputs "172 examples". It means the 92nd in code has been executed and tmp_nnet_chain_eg->inputs[0].features is a CompressedMatrix. However,  the log outputted nothing about the 94th in the code. I think the 93rd triggers the error and I can't find something about this error from the log.
Could you please explain why this happens?

**Comment by danpovey** [comment]
The error messages are printed from the line of Kaldi code the KALDI_ERR macro is invoked.  Sorry too busy to help more.

**Comment by kkm000** [comment]
Please always post text, not pictures.

This does not look like a Kaldi standard binary. We do not have a program called `nnet3-chain-spec-argument_v2` Probably it crashed? It's impossible to tell with the information you provided.

I am closing this ticket for now. If you believe that your issue has not been addressed, please feel free to ping me, and I'll reopen it.

**Comment by bringtree** [comment]
@kkm000  It is the mini code about nnet3-chain-spec-argument_v2.
```c++

#include "base/kaldi-common.h"
#include "util/common-utils.h"
#include "hmm/transition-model.h"
#include "nnet3/nnet-chain-example.h"

int main(int argc, char *argv[])
{
  try
  {
    using namespace kaldi;
    using namespace kaldi::nnet3;
    typedef kaldi::int32 int32;
    typedef kaldi::int64 int64;

    const char *usage =
        "Usage:  nnet3-chain-shuffle-egs <egs-rspecifier> <egs-wspecifier>\n"
        "\n"
        "nnet3-chain-shuffle-egs ark:train.egs ark:shuffled.egs\n";

    ParseOptions po(usage);

    po.Read(argc, argv);

    if (po.NumArgs() != 2)
    {
      po.PrintUsage();
      exit(1);
    }

    std::string examples_rspecifier = po.GetArg(1),
                examples_wspecifier = po.GetArg(2);

    std::pair<std::string, NnetChainExample *> single_egs;

    SequentialNnetChainExampleReader example_reader(examples_rspecifier);
    NnetChainExampleWriter example_writer(examples_wspecifier);

    NnetChainExample *tmp_nnet_chain_eg = NULL;
    Matrix<float> tmp_feature_matrix;
    for (; !example_reader.Done(); example_reader.Next())
    {
      tmp_nnet_chain_eg = new NnetChainExample(example_reader.Value());
      std::vector<NnetIo>::iterator iter = tmp_nnet_chain_eg->inputs.begin(),
                                    end = tmp_nnet_chain_eg->inputs.end();
      for (; iter != end; ++iter)
      {
        // 
        KALDI_LOG << "fail";
        iter->features.Uncompress();        
        KALDI_LOG << "test";

      }
      tmp_feature_matrix = tmp_nnet_chain_eg->inputs[0].features.GetFullMatrix();

      example_writer.Write(example_reader.Key(), *tmp_nnet_chain_eg);
    }

    return 0;
  }
  catch (const std::exception &e)
  {
    std::cerr << e.what() << '\n';
    return -1;
  }
}
```
I need to GetFullMatrix().
tmp_feature_matrix = tmp_nnet_chain_eg->inputs[0].features.GetFullMatrix();
Howerver,        ``` iter->features.Uncompress();  ```always failed.

**Comment by bringtree** [comment]
I don't know why Uncompress fail.
I use GetMatrix to pass this problem and the code looks like running.....

**Comment by bringtree** [comment]
Oh, I find when I call the Uncompress(). 
```c++
    cmat_.CopyToMat(&mat_);
```
```c++
CompressedMatrix::CopyToMat
630:   KALDI_ASSERT(mat->NumRows() == num_rows);
```
mat->NumRows()  is 0 !!!
num_rows isn't 0.

**Comment by bringtree** [comment]
Maybe it needs to add the code.
``` c++  
sparse-matrix.cc
void GeneralMatrix::Uncompress() {
  if (cmat_.NumRows() != 0) {
    mat_->Resize(cmat_.NumRows(), cmat_.NumCols(), kUndefined); // add code.
    cmat_.CopyToMat(&mat_);
    cmat_.Clear();
  }
}
```
?
