### ISSUE TITLE
Confusion about cu-device / cudadecoder

### ISSUE THREAD

**Issue by housebaby** [kaldi-asr/kaldi#3310]
hello, @hugovbraun @danpovey 
Sorry to bother you!
I am a little confused about how multiply CPU-threads interact with one device.
Q1:
In the cudamatrix/cu-device.h， It is mentioned that " Each thread has its own CuDevice object, which contains the cublas and cusparse handles.  These are unique to the thread (which is what is recommended by NVidia).
But in cudadecoder/README, it is mentioned that,  "cuda-control-threads:  Number of CPU threads simultaniously submitting work to the device.  For best performance this should be between 2-4".
Do the above two statements contradict each other, 
Or does it mean that several CPU threads can interact with one device ,but each of them should have their own cu-device object? we can have several cu-device objects on one GPU device?

Q2:  I implemented a multi-thread nnet-compute program on machine with 8 Tesla V100 card. Multi-thread aims to improve GPU-occupacy , 
But I found that  GPU-occupacy doesn't scales linearly with number of threads , In contrary, GPU-Occupacy will decrease with too many threads.  
reattime_ratio | thread_num | Gpu-occupacy
0.003337 | 100 | 49%-51%
0.002499 | 80 | 50%-52%
0.001939 | 56 | 54%~56%
0.001743 | 50 | 54%，55%，56%
0.001359 | 16 | 53%~60%

Can you some advice on the above two questions .
Thanks you, and looking forward to your answer

**Comment by luitjens** [comment]
Q1:  Several threads can share a GPU.  CUDA control threads do exactly this.  Each thread has its own set of stream so that the work can run in parallel.  You will notice that the cu-device is thread local:

cu-device.cc:thread_local CuDevice CuDevice::this_thread_device_;

Q2:  Is this for inference or training?  How are you measuring occupancy?  How are you assigning threads to GPUs?  Currently Kaldi is 1 process per GPU.

**Comment by housebaby** [comment]
@luitjens Thanks for your remark 
Q2  is for inference. I used "nvidia-smi" to watch the occupancy during inference.
A multi-thread process is used to  assign threads to GPU , while all threads work simultaneously, and each thread corresponding to a decoder and decoding utterance one by one.

**Comment by housebaby** [comment]
It is expected that when the number of threads increases, the occupancy of GPU will also increase. But actually, it didn't.
