### ISSUE TITLE
How to restart tdnn train in failed iter number

### ISSUE THREAD

**Issue by v-yunbin** [kaldi-asr/kaldi#3318]
I try restart the train with parameter "args.exit_stage=1540" as follows， but it still train from 0 inter.  im very puzzled.
```
  steps/nnet3/chain/train.py --stage 0 \
    --cmd "$decode_cmd" \
    --use-gpu=wait \
      ..........................
    --exit-stage 1540 \
    --lat-dir exp/tri4_sp_lats \
    --dir $dir  || exit 1;
```

**Comment by danpovey** [comment]
You should use --stage, not --exit-stage.

**Comment by v-yunbin** [comment]
@danpovey but how to set "--stage" ? it can retrain from failed  inter?

**Comment by danpovey** [comment]
Set it to the last iteration that succeeded (or maybe the one that failed)-- try both, whichever one seems to work is fine.

**Comment by v-yunbin** [comment]
@danpovey thank you very much, it work.
