### ISSUE TITLE
incorrect data directory when using utils/prepare_extended_lang.sh with the parameter  --word-list

### ISSUE THREAD

**Issue by jtrmal** [kaldi-asr/kaldi#3339]
Hi, the way utils/prepare_extended_lang.sh behaves makes (in some cases) the lang dir incorrect if the parameter --word-list parameter is supplied.
The problem is that the prepare_lang is called first, which means that oov.int and the *.int and *.csl files in phone subdir are generated using the original word-map and only after that the map is regenerated.

**Comment by jtrmal** [comment]
probably @xiaohui-zhang could check if I'm right.
IMO, there is no easy fix, because it goes down to L.fst -- I think the course of fix would be to add a parameter to prepare_lang.sh

**Comment by jtrmal** [comment]
@DongjiGao following your latest PR #3485, I wonder if you'd be able to look at this?
Thanks :)

**Comment by DongjiGao** [comment]
OK, I will take a look.

Dongji

On Jul 22, 2019, at 4:37 PM, jtrmal <notifications@github.com<mailto:notifications@github.com>> wrote:


@DongjiGao<https://github.com/DongjiGao> following your latest PR #3485<https://github.com/kaldi-asr/kaldi/pull/3485>, I wonder if you'd be able to look at this?
Thanks :)

**Comment by xiaohui-zhang** [comment]
Thanks @jtrmal for raising this problem. Actually, I created that script before @danpovey made this much better one (interface-wise): https://github.com/kaldi-asr/kaldi/blob/master/egs/wsj/s5/utils/lang/extend_lang.sh  The only functionality my version has, while Dan's newer version doesn't have is that, the newer version doesn't support lexiconp_silprobs.txt. I would suggest @DongjiGao try to port this functionality into Dan's version, and delete my version (IIRC it's not being used by any official script anyway).

**Comment by danpovey** [comment]
@DongjiGao is there any chance you could address this issue?

**Comment by DongjiGao** [comment]
I can do that. I am preparing a presentation for the reading group on Monday. I will fix it after the reading group.

**Comment by jtrmal** [comment]
I assume this is resolved.
