### ISSUE TITLE
mkl installation failed behind proxy

### ISSUE THREAD

**Issue by ashimajain2595** [kaldi-asr/kaldi#3342]
I followed the same steps as in extras/install_mkl.h for installing mkl but there were some certificate and proxy related issues. On modifying the commands as below, I am now getting "unexpected TLS packet error".

```
$ wget -q0- https://apt.repos.intel.com/intel-gpg-keys/GPG-PUB-KEY-INTEL-SW-PRODUCTS-2019.PUB --no-check-certificate 
$ apt-key --keyring /usr/share/keyrings/intel-sw-products.gpg add - 
$ echo 'deb [signed by=/usr/share/keyrings/intel-sw-products.gpg trusted=yes] https://apt.repos.intel.com/mkl all main > /etc/apt/sources.list.d/intel-mkl.list
$ apt-get update
$ apt-get install intel-mkl-64bit-2019.2-057
```

```
Ign:1 https://apt.repos.intel.com/mkl all InRelease
Ign:2 https://apt.repos.intel.com/mkl all Release
Ign:3 https://apt.repos.intel.com/mkl all/main all Packages
Ign:4 https://apt.repos.intel.com/mkl all/main i386 Packages
Ign:5 https://apt.repos.intel.com/mkl all/main amd64 Packages
Err:4 https://apt.repos.intel.com/mkl all/main i386 Packages
Could not handshake: An unexpected TLS packet was received. [IP: <ip port>]
E: Failed to fetch https://apt.repos.intel.com/mkl/dists/all/main/binary-i386/Packages
Could not handshake: An unexpected TLS packet was received. [IP: <ip port>]
```

I am working on Ubuntu 18.04 and the proxy configuration has already been set in /etc/apt/apt.conf

Please let me know if anyone has ideas on how to resolve this issue.

**Comment by bringtree** [comment]
Oh, you can download the mkl library source form https://software.intel.com/en-us/mkl

**Comment by danpovey** [comment]
I don't think you want the source, probably you want the compiled libararies etc.  Probably a proxy issue; check your proxy works for https (this is from searching for the error `An unexpected TLS packet was received`).
