### ISSUE TITLE
aishell/v1/run.sh cannot download the resource.tgz

### ISSUE THREAD

**Issue by Honei** [kaldi-asr/kaldi#3343]
in the aishell/vi/run.sh, there is two line code to download the aishell data resource, but in the run.sh line 24, the parameter is resource_aishell,
`local/download_and_untar.sh $data $data_url resource_aishell`
<br>
but in the local/download_and_untar.sh script, the file named resource is  in line 31,
`list="data_aishell resource"`

**Comment by naxingyu** [comment]
Thanks. I'll fix it ASAP.
