### ISSUE TITLE
something wrong happens when install mkl

### ISSUE THREAD

**Issue by 77281900000** [kaldi-asr/kaldi#3350]
+ exec sudo extras/install_mkl.sh -sp debian intel-mkl-64bit-2019.2-057
+ apt-get update
/usr/lib/apt/methods/https: error while loading shared libraries: librtmp.so.1: cannot open shared object file: No such file or directory
Hit:1 http://mirrors.aliyun.com/ubuntu xenial InRelease
Hit:2 http://mirrors.aliyun.com/ubuntu xenial-updates InRelease                  
Hit:3 http://mirrors.aliyun.com/ubuntu xenial-backports InRelease                
Hit:4 http://mirrors.aliyun.com/ubuntu xenial-security InRelease                 
Hit:5 http://archive.ubuntu.com/ubuntu xenial InRelease                          
Hit:6 http://archive.canonical.com/ubuntu xenial InRelease              
Hit:7 http://ppa.launchpad.net/ubuntu-toolchain-r/test/ubuntu xenial InRelease
Reading package lists... Done
E: Method https has died unexpectedly!
E: Sub-process https returned an error code (127)
E: Method /usr/lib/apt/methods/https did not start correctly
W: No sandbox user '_apt' on the system, can not drop privileges
E: Failed to fetch https://apt.repos.intel.com/mkl/dists/all/InRelease  
E: Some index files failed to download. They have been ignored, or old ones used instead.
extras/install_mkl.sh: MKL package intel-mkl-64bit-2019.2-057 installation FAILED.

**Comment by danpovey** [comment]
`apt-get update` is a basic system maintenance function.  If that fails it means your system is in a bad way.  But it has nothing specifically to do with Kaldi.
