### ISSUE TITLE
how to change "raw_mfcc_pitch_train_hires.*.txt” to "raw_mfcc_pitch_train_hires.*.ark”

### ISSUE THREAD

**Issue by panxin801** [kaldi-asr/kaldi#3356]
Hello, I have a question may need help. 
By using kaldi script I make a mfcc ark file named "raw_mfcc_pitch_train_hires.1.txt", then I use "copy-feats ark:raw_mfcc_pitch_train_hires.1.ark ark,t:raw_mfcc_pitch_train_hires.1.txt" to change it in txt model. After some modifies in txt file, I want to change the txt formation back in ark file. Is there a way can achieve this ?
Oh, by the way, I tried " copy-feats ark,t:raw_mfcc_pitch_train_hires.1.txt ark:raw_mfcc_pitch_train_hires.1.la". But "raw_mfcc_pitch_train_hires.1.la" is different from "raw_mfcc_pitch_train_hires.1.ark", so I don't know what to do now.
Thank you for your help.

**Comment by danpovey** [comment]
> Hello, I have a question may need help.
> By using kaldi script I make a mfcc ark file named
> "raw_mfcc_pitch_train_hires.1.txt", then I use "copy-feats
> ark:raw_mfcc_pitch_train_hires.1.ark
> ark,t:raw_mfcc_pitch_train_hires.1.txt" to change it in txt model. After
> some modifies in txt file, I want to change the txt formation back in ark
> file. Is there a way can achieve this ?
>
Technically that .txt is still an archive file, it is just a text one.  You
don't have to use ",t" when reading it, that has no effect.

 Oh, by the way, I tried " copy-feats
ark,t:raw_mfcc_pitch_train_hires.1.txt ark:raw_mfcc_pitch_train_hires.1.la".
But "raw_mfcc_pitch_train_hires.1.la" is different from
"raw_mfcc_pitch_train_hires.1.ark", so I don't know what to do now.

It wouldn't be bitwise the same-- conversion to and from text would not
preserve the exact numbers.

Dan


Thank you for your help.

**Comment by panxin801** [comment]
Thank you for reply, Dan. If there's a way of converse from text and preserve the exact numbers ? If not , may I use " copy-feats ark,t:1.txt ark:1.ark"  to converse txt back in ark formation ?  
Thanks a lot.

**Comment by danpovey** [comment]
There isn't a way, but the differences are so small as to not matter.

**Comment by panxin801** [comment]
ok thanks a lot Dan. I get it.
