### ISSUE TITLE
configure with mkl error

### ISSUE THREAD

**Issue by tao0103** [kaldi-asr/kaldi#3357]
Hi,
I want to use intel mkl package,but I have no root permission.So I download it in my home account.
When I run configure:

./configure --shared --mkl-root=/home/<username>/intel/mkl

get error:
***configure failed: CUDA 8_0 does not support g++ (g++-8).
                 You need g++ < 6.0. ***

So the only solution is change gcc version?

**Comment by danpovey** [comment]
An easier solution would be to upgrade your CUDA.  Downgrading your gcc
would normally be more complicated.

**Comment by kkm000** [comment]
Just FYI (and/or for the benefit of anyone who's searching):
gcc7 is supported starting from CUDA 10.0, gcc8 from CUDA 10.1.

There is an interesting on-going project for nvcc-less compilation of .cu files with clang, but it was not up to the task last time I tried. It's not in any officially released clang, anyway.
