### ISSUE TITLE
Issues with running examples on Cygwin

### ISSUE THREAD

**Issue by ivannson** [kaldi-asr/kaldi#3359]
I'm trying to run some Kaldi examples after I have compiled it on Cygwin, however, when the directory is specified in a file, Cygwin can't follow it. For example, I am trying to run the following in Cygwin terminal:

`steps/make_mfcc.sh`

This returns:

`No such file or directory`

This makes sense, since steps is not a directory, but a file with the following content:
`
../../wsj/s5/steps/`

Which leads to steps directory which is what I need, and if I manually point it to the correct place, it works fine, but then breaks when a similar approach to pointing to a directory is used.

I have tried compiling Kaldi on Linux (Ubuntu 16.04) and running the same example, and everything worked perfectly, which leads me to believe that it's a Cygwin issue.

Is there a way to make it work as it does on Ubuntu?

**Comment by danpovey** [comment]
Hm it may have something to do with the difference between Windows and
Cygwin symlinks.
For instance, you might have checked out Kaldi with a Windows version of
git instead of a cygwin one?
I am actually not 100% sure if there are different types of symlinks.
Cygwin has changed in recent years.

**Comment by danpovey** [comment]
closing as there is not much more I can say and we're not putting much effort into cygwin, but let us know if you find out what the issue was.

**Comment by nshmyrev** [comment]
Links has to be enabled on Cygwin https://stackoverflow.com/questions/18654162/enable-native-ntfs-symbolic-links-for-cygwin. I answered the same on SO https://stackoverflow.com/questions/56394640/how-to-follow-a-filepath-specified-within-a-text-file-on-cygwin#comment99390972_56394640

**Comment by ivannson** [comment]
@nshmyrev Yep, I saw that, thank you. Didn't seem to work in this case unfortunately, so I'm trying to find another way of doing it.
