### ISSUE TITLE
Make test under cudamatrix failed 

### ISSUE THREAD

**Issue by FulingChen** [kaldi-asr/kaldi#3363]
I am new to Kaldi. I installed and compiled kaldi in the docker in GPU station. I met with this issue when I try to make test under /src.  It seems like all tests under /src/cudamatrix/ failed. 

Here is the error I run only one test file ./cu-math-test

> LOG ([5.5.356~1435-8706]:main():cu-math-test.cc:739) Tests without GPU use succeeded.
> WARNING ([5.5.356~1435-8706]:SelectGpuId():cu-device.cc:221) Not in compute-exclusive mode.  Suggestion: use 'nvidia-smi -c 3' to set compute exclusive mode
> LOG ([5.5.356~1435-8706]:SelectGpuIdAuto():cu-device.cc:349) Selecting from 2 GPUs
> LOG ([5.5.356~1435-8706]:SelectGpuIdAuto():cu-device.cc:364) cudaSetDevice(0): Quadro P6000     free:24171M, used:274M, total:24446M, free/total:0.988764
> LOG ([5.5.356~1435-8706]:SelectGpuIdAuto():cu-device.cc:364) cudaSetDevice(1): GeForce GTX 1060 6GB     free:6005M, used:73M, total:6078M, free/total:0.98799
> LOG ([5.5.356~1435-8706]:SelectGpuIdAuto():cu-device.cc:411) Trying to select device: 0 (automatically), mem_ratio: 0.988764
> LOG ([5.5.356~1435-8706]:SelectGpuIdAuto():cu-device.cc:430) Success selecting device 0 free mem ratio: 0.988764
> LOG ([5.5.356~1435-8706]:FinalizeActiveGpu():cu-device.cc:284) The active GPU is [0]: Quadro P6000      free:24093M, used:352M, total:24446M, free/total:0.985573 version 6.1
> ERROR ([5.5.356~1435-8706]:ComputeLstmNonlinearity():cu-math.cc:515) cudaError_t 48 : "no kernel image is available for execution on the device" returned from 'cudaGetLastError()'
> 
> [ Stack-Trace: ]
> kaldi::MessageLogger::LogMessage() const
> kaldi::MessageLogger::LogAndThrow::operator=(kaldi::MessageLogger const&)
> void kaldi::cu::ComputeLstmNonlinearity<float>(kaldi::CuMatrixBase<float> const&, kaldi::CuMatrixBase<float> const&, kaldi::CuMatrixBase<float>*)
> ./cu-math-test() [0x4452df]
> void kaldi::CudaMathUnitTest<float>()
> main
> __libc_start_main
> _start
> 
> terminate called after throwing an instance of 'kaldi::KaldiFatalError'
>   what():  kaldi::KaldiFatalError
> Aborted (core dumped)

It seems like kaldi is able to detect GPU, but can't find the kernel image.
Here is the environment info from nvidia-smi
root@9812e285e291:/kaldi/src/cudamatrix# nvidia-smi
Tue Jun  4 02:37:18 2019
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 418.43       Driver Version: 418.43       CUDA Version: 10.1     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Quadro P6000        Off  | 00000000:01:00.0  On |                  Off |
| 26%   28C    P8     9W / 250W |    121MiB / 24446MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   1  GeForce GTX 106...  Off  | 00000000:02:00.0 Off |                  N/A |
|  0%   37C    P8     6W / 120W |      2MiB /  6078MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
+-----------------------------------------------------------------------------+

I used arch sm 75 in the src/configure. And all the compilation was quite successfully. I don't know why it doesn't work here.

Can you provide some suggestions?
Thanks!

Fuling

**Comment by danpovey** [comment]
It's using the Quadro GPU which has a compute capability of 6.1.  You'd
have to compile with that, or disable that GPU by doing something like
export CUDA_VISIBLE_DEVICES=1

**Comment by FulingChen** [comment]
Thanks Daniel,
Could you please give me more guidance on how to compile correctly with Quadro GPU?

**Comment by danpovey** [comment]
It should work by default.  There should be something like `arch=compute_61,code=sm_61` in the kaldi.mk, among other things.

**Comment by FulingChen** [comment]
It is solved by compiling with sm as 61. Thanks for all your help!
