### ISSUE TITLE
How to train 8kHz Chinese speech recognition?

### ISSUE THREAD

**Issue by whaozl** [kaldi-asr/kaldi#3368]
i see [aidatatang_200zh](https://github.com/kaldi-asr/kaldi/tree/master/egs/aidatatang_200zh/s5).

but it is 16kHz. How to modify to 8kHz?

What steps are needed?

**Comment by danpovey** [comment]
In conf/mfcc.conf and conf/mfcc_hires.conf, change
`--sample-frequency=16000`
to 
```
--sample-frequency=8000
--allow-downsample=true
```

**Comment by whaozl** [comment]
hello thank you very much.
My audio data is 8kHz, I just need to change its configuration sample-frequency=8000. Right?
@danpovey

**Comment by underdogliu** [comment]
@whaozl  If your audio data is 8khz from the beginning, then yes and you don't even add `--allow-downsample=true` in the conf file I believe.
