### ISSUE TITLE
AddElements kernel rewrite

### ISSUE THREAD

**Issue by danpovey** [kaldi-asr/kaldi#337]
The kernel _cuda_matrix_add_elements needs to be rewritten.  It looks like it was copied and modified from other code and it's designed in a way that doesn't really make sense.  It should use multiple blocks as well as multiple threads, and each kernel invocation should probably handle just one element.  Obviously this changes how it will be invoked.
Anyone familiar with GPU programming can do this.
Dan

**Comment by naxingyu** [comment]
If it is not urgent, I would like to ask my colleague Zhichao @zhichaowang to do this. It could be a good practise for him.

**Comment by danpovey** [comment]
Good idea- thanks.  Please do the first pass of code review once he submits
a pull request, in that case.

**Comment by naxingyu** [comment]
Sure.

**Comment by danpovey** [comment]
Closing as addressed in 43100d633faf66b2909b5517ef9f5f685d6b4423
