### ISSUE TITLE
Refusing to split data because number of speakers 0 is less than the number of output .scp files 40

### ISSUE THREAD

**Issue by whaozl** [kaldi-asr/kaldi#3376]
```
[haozl@centos7 s5data8k]$ steps/decode.sh --cmd "$decode_cmd" --config conf/decode.config --nj $njob  exp/mono/graph data/test exp/mono/decode_test
steps/decode.sh --cmd run.pl --config conf/decode.config --nj 40 exp/mono/graph data/test exp/mono/decode_test
utils/split_scp.pl: Refusing to split data because number of speakers 0 is less than the number of output .scp files 40
```

Must I have speaker identity information when training ASR? 
I see that **train tdnn** extracted the ivector feature?

**Comment by danpovey** [comment]
If you don't have speaker identity you can just have utt2spk and spk2utt be a one to one map.
You need to make sure your data directory passes validation (see utils/data/validate_data_dir.sh).

**Comment by danpovey** [comment]
and you should use kaldi-help for this kind of question.

**Comment by whaozl** [comment]
thankyou dan. yes, I join the kaldi help group.
