### ISSUE TITLE
egs/aidatatang/s5/local/prepare_dict.sh run error

### ISSUE THREAD

**Issue by boystray** [kaldi-asr/kaldi#3380]
prepare_dict.sh report
`The encoding pragma is no longer supported at -e line 2.
BEGIN failed--compilation aborted at -e line 2.`

I think  the 180 line in prepare_dict.sh
 `  perl -e '
  use encoding utf8;`has bug.
my perl is v5.26.2,the encoding pragma which is deprecated since perl 5.18.

**Comment by danpovey** [comment]
@jtrmal any idea how to fix this?

**Comment by naxingyu** [comment]
egs/aishell/s5/local/wer_output_filter give a solution. hkust and
gale_mandarin have similar issue.

**Comment by danpovey** [comment]
@naxingyu is there any chance you could commit a fix?  I think Yenda is busy with workshop-related stuff (those Hopkins summer workshops).

**Comment by jtrmal** [comment]
I will try to resolve this in the upcoming days. I just cannot today.
y.

**Comment by boystray** [comment]
btw,there is the same "use encoding utf8;" problem in egs/aidatatang_200zh/s5/local/create_oov_char_lexicon.pl

**Comment by naxingyu** [comment]
OK, will do today.
Best,
Xingyu Na
