### ISSUE TITLE
kaldi/egs/librispeech/s5/local/nnet3/run_tdnn.sh  error

### ISSUE THREAD

**Issue by BowenPang** [kaldi-asr/kaldi#3381]
Exception: You have num_hidden_layers=6 (real meaning: your config files are intended to do discriminative pretraining). Since Kaldi 5.2, this is no longer supported --> use newer config-creation scripts, i.e. xconfig_to_configs.py.

Please advise how to fix it.

**Comment by danpovey** [comment]
The message itself tells you what to do: use newer scripts.  That setup is no longer supported.
You can look at e.g. egs/mini_librispeech/s5  for an example of a modern setup.
