### ISSUE TITLE
Minor bug fix for component end token

### ISSUE THREAD

**Issue by danpovey** [kaldi-asr/kaldi#339]
The  `<NaturalGradientAffineComponent>` ends with `<NaturalGradientAffineComponent>` instead of `</NaturalGradientAffineComponent>`.  This needs to be fixed, but the fix needs to be able to read the previously written models.

**Comment by danpovey** [comment]
@tomkocse, this is very small, but you can help with this.

**Comment by tomkocse** [comment]
@danpovey , "but the fix needs to be able to read the previously written models." <--------- Do you mean that the code still need to tolerate those models which has already wrongly ends with <NaturalGradientAffineComponent> ?

**Comment by vijayaditya** [comment]
I think thats what he means.

--Vijay
