### ISSUE TITLE
error when ivector-plda-scoring

### ISSUE THREAD

**Issue by WilburZiWong** [kaldi-asr/kaldi#3396]
Well, when I run the sre16 v1 run.sh, I had a problem at the stage 7. It said that I do not have nontarget scores, so I modified my trials file. But finally I found that exp/scores/sre16_eval_scores totally do not have nontarget scores, and I also found that the scores calculating based on exp/ivectors_sre16_eval_test/ivector.scp. So, I wanted to look for some issues in stage 5 when generates the ivector.scp file. It appears that sid/extract_ivectors.sh only extract the ivectors basing the vad.scp and it only contains the all target items except the nontarget items.
  So now, I do not know how to solve this problem and I hopefully look forward to somebody's solutions or suggestions. 
  Thank u! :)

**Comment by WilburZiWong** [comment]
> WARNING (ivector-plda-scoring[5.5.350~1-0e5e]:main():ivector-plda-scoring.cc:175) Key 03416-03393_female_20160706193011_79297570_Xiaomiphone-Android_verify_11 not present in test iVectors.

> WARNING` (ivector-plda-scoring[5.5.350~1-0e5e]:main():ivector-plda-scoring.cc:175) Key 03416-03393_female_20160706193044_79753907_Xiaomiphone-Android_verify_13 not present in test iVectors.

> LOG (ivector-plda-scoring[5.5.350~1-0e5e]:main():ivector-plda-scoring.cc:214) Mean score was 2.28007, standard deviation was 3.60072

> LOG (ivector-plda-scoring[5.5.350~1-0e5e]:main():ivector-plda-scoring.cc:217) Processed 239 trials, 3107 had errors.

The log "exp/scores/log/sre16_eval_scoring.log" parts of the last contents are showed above.
I have 239 target trials and 3107 nontarget trials. It means that I totally have 3107+239 lines in my sre16_eval_test/trials file.

**Comment by WilburZiWong** [comment]
The sre16_eval_scores also only contains 239 target scores.

**Comment by danpovey** [comment]
Likely a local issue.
