### ISSUE TITLE
Compile failed in cudafeatbin

### ISSUE THREAD

**Issue by luckmoon** [kaldi-asr/kaldi#3398]
I clone the master brunch, and when i entry the cudafeatbin folder and make, it fails with information below. And my env is P40 GPU, CUDA9.0, CentOS 7.5, gcc 4.8.5.

/usr/local/cuda/lib64/libcusolver.so: undefined reference to `GOMP_parallel_start'
/usr/local/cuda/lib64/libcusolver.so: undefined reference to `GOMP_critical_start'
/usr/local/cuda/lib64/libcusolver.so: undefined reference to `GOMP_loop_dynamic_start'
/usr/local/cuda/lib64/libcusolver.so: undefined reference to `GOMP_critical_end'
/usr/local/cuda/lib64/libcusolver.so: undefined reference to `omp_get_max_threads'
/usr/local/cuda/lib64/libcusolver.so: undefined reference to `GOMP_loop_end_nowait'
/usr/local/cuda/lib64/libcusolver.so: undefined reference to `omp_get_thread_num'
/usr/local/cuda/lib64/libcusolver.so: undefined reference to `GOMP_loop_dynamic_next'
/usr/local/cuda/lib64/libcusolver.so: undefined reference to `GOMP_parallel_end'
/usr/local/cuda/lib64/libcusolver.so: undefined reference to `omp_get_num_threads'
collect2: error: ld returned 1 exit status
make: *** [apply-cmvn-online-cuda] Error 1
make: *** Waiting for unfinished jobs....
/usr/local/cuda/lib64/libcusolver.so: undefined reference to `GOMP_parallel_start'
/usr/local/cuda/lib64/libcusolver.so: undefined reference to `GOMP_critical_start'
/usr/local/cuda/lib64/libcusolver.so: undefined reference to `GOMP_loop_dynamic_start'
/usr/local/cuda/lib64/libcusolver.so: undefined reference to `GOMP_critical_end'
/usr/local/cuda/lib64/libcusolver.so: undefined reference to `omp_get_max_threads'
/usr/local/cuda/lib64/libcusolver.so: undefined reference to `GOMP_loop_end_nowait'
/usr/local/cuda/lib64/libcusolver.so: undefined reference to `omp_get_thread_num'
/usr/local/cuda/lib64/libcusolver.so: undefined reference to `GOMP_loop_dynamic_next'
/usr/local/cuda/lib64/libcusolver.so: undefined reference to `GOMP_parallel_end'
/usr/local/cuda/lib64/libcusolver.so: undefined reference to `omp_get_num_threads'
collect2: error: ld returned 1 exit status
make: *** [compute-mfcc-feats-cuda] Error 1

**Comment by luckmoon** [comment]
I upgrade cuda 9.0 to cuda 9.2, it works!

**Comment by danpovey** [comment]
When exactly did you check out the kaldi master?  Because I thought we
changed the configure script so that it deals with this situation properly,
by not using cusolver if the CUDA version is too old.
