### ISSUE TITLE
docker&port problem when doing parallelization by ssh.pl

### ISSUE THREAD

**Issue by quinn0126** [kaldi-asr/kaldi#3403]
First thanks for authors' work.

I tried to run kaldi on timit example in two machines, and I create two dockers for each machine with respective port number. Then I succeed in making password-free connection within those dockers.

But I got two errors when running ./run.sh:

1 IF I write the follow two lines to .queue/machines
10.18.101.92
10.18.101.96
It requests password for machine I currently use, after I input the physical machine password, it shows that the connection failed.

2 IF I write the follow two lines (with port number) to .queue/machines
10.18.101.92 -p 30763
10.18.101.96 -p 30320
It shows that ssh.pl: bad line '10.18.101.96 -p 30763' in .queue/machines.

now,what should I do to work it out?
Hope to get response from authors, thank you again!

**Comment by danpovey** [comment]
sorry don't have time to debug this local issue.
