### ISSUE TITLE
About yesno   ——the first project

### ISSUE THREAD

**Issue by ucasiggcas** [kaldi-asr/kaldi#3407]
Dear,

After I download the kaldi on ubuntu18,
`cd ./egs/yesno/s5`
`./run.sh`

Bugs

`Preparing language models for test
local/prepare_lm.sh: line 13: arpa2fst: command not found
fstisstochastic data/lang_test_tg/G.fst 
ERROR (fstisstochastic[5.5.388~1-777f8]:Input():kaldi-io.cc:756) Error opening input stream data/lang_test_tg/G.fst

[ Stack-Trace: ]
fstisstochastic(kaldi::MessageLogger::LogMessage() const+0xb1a) [0x56051f7a9ec4]
fstisstochastic(kaldi::MessageLogger::LogAndThrow::operator=(kaldi::MessageLogger const&)+0x21) [0x56051f71ebc7]
fstisstochastic(kaldi::Input::Input(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool*)+0xf6) [0x56051f736766]
fstisstochastic(fst::ReadFstKaldiGeneric(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool)+0x54) [0x56051f729b2a]
fstisstochastic(main+0x229) [0x56051f71db53]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xe7) [0x7fd55380cb97]
fstisstochastic(_start+0x2a) [0x56051f71d84a]

kaldi::KaldiFatalErrorERROR: ReadFst: Can't open file: data/lang_test_tg/G.fst
ERROR: FstHeader::Read: Bad FST header: tmpdir.g/empty_words.fst
Succeeded in formatting data.
steps/make_mfcc.sh --nj 1 data/train_yesno exp/make_mfcc/train_yesno mfcc
utils/validate_data_dir.sh: WARNING: you have only one speaker.  This probably a bad idea.
   Search for the word 'bold' in http://kaldi-asr.org/doc/data_prep.html
   for more information.
utils/validate_data_dir.sh: Successfully validated data-directory data/train_yesno
steps/make_mfcc.sh: [info]: no segments file exists: assuming wav.scp indexed by utterance.
steps/make_mfcc.sh: Succeeded creating MFCC features for train_yesno
steps/compute_cmvn_stats.sh data/train_yesno exp/make_mfcc/train_yesno mfcc
Succeeded creating CMVN stats for train_yesno
fix_data_dir.sh: kept all 31 utterances.
fix_data_dir.sh: old files are kept in data/train_yesno/.backup
steps/make_mfcc.sh --nj 1 data/test_yesno exp/make_mfcc/test_yesno mfcc
utils/validate_data_dir.sh: WARNING: you have only one speaker.  This probably a bad idea.
   Search for the word 'bold' in http://kaldi-asr.org/doc/data_prep.html
   for more information.
`
and 
`1 warnings in exp/mono0a/log/update.*.log
exp/mono0a: nj=1 align prob=-81.88 over 0.05h [retry=0.0%, fail=0.0%] states=11 gauss=371
steps/train_mono.sh: Done training monophone system in exp/mono0a
mkgraph.sh: expected data/lang_test_tg/G.fst to exist
steps/decode.sh --nj 1 --cmd utils/run.pl exp/mono0a/graph_tgpr data/test_yesno exp/mono0a/decode_test_yesno
steps/decode.sh: Error: no such file exp/mono0a/graph_tgpr/HCLG.fst
grep: exp/mono0a/decode_test_yesno/wer_*: No such file or directory`

I don't know why,
Please help me,Thx

**Comment by danpovey** [comment]
Likely you didn't compile Kaldi.  You should use web search or Kaldi-help for these kinds of basic questions.
