### ISSUE TITLE
Modification to NormalizeComponent

### ISSUE THREAD

**Issue by danpovey** [kaldi-asr/kaldi#341]
I need NormalizeComponent to be extended.. it relates to the 'chain' branch that I'm working on in my own repo.
Instead of rescaling so that the output rms value is 1, I'd like this to be configurable, so that you can set
target-rms=0.25
in the config (or whatever value you want).  Obviously this would have to be tested- just extending the function GenerateRandomComponentConfig() should be enough.
@pegahgh, could you please do this this afternoon?  I need it for something.
Dan

**Comment by pegahgh** [comment]
Sure! I will modify the component!
