### ISSUE TITLE
Bug or outdated/wrong comment?

### ISSUE THREAD

**Issue by cloudhan** [kaldi-asr/kaldi#3418]
When I skimming through some code, I find

https://github.com/kaldi-asr/kaldi/blob/8ce3a95761e0eb97d95d3db2fcb6b2bfb7ffec5b/src/util/stl-utils.h#L98-L109

It states `(because the set was in sorted order).` But the set is an `unordered_set`, is it a bug or simply forgetting to remove the comment when copying code from the `set` version of `CopySetToVector`?

**Comment by danpovey** [comment]
yes the comment is wrong.  if you make a PR to remove it I would merge, but won't leave the issue up (too minor)
