### ISSUE TITLE
egs/aidatatang_200zh/s5/local/create_oov_char_lexicon.pl has a bug

### ISSUE THREAD

**Issue by boystray** [kaldi-asr/kaldi#3430]
the code in local/prepare_dict.sh will get lexicon for Chinese OOV words
`# get lexicon for Chinese OOV words

local/create_oov_char_lexicon.pl $dict_dir/lexicon-ch/ch-char-dict-mp.txt \
  $dict_dir/lexicon-ch/words-ch-oov.txt > $dict_dir/lexicon-ch/lexicon-ch-oov.txt || exit 1;`

but after the code is run,  what i get in data/local/dict/lexicon-ch/lexicon-ch-oov.txt is
`一一九
         
一一二         

一一列举            
`

so there is no lexicon for Chinese word.
when the rest codes in prepare_dict.sh continue to run,like
`# compose IV and OOV lexicons for Chinese

cat $dict_dir/lexicon-ch/lexicon-ch-oov-mp.txt $dict_dir/lexicon-ch/lexicon-ch-iv.txt |\
  awk '{if (NF > 1 && $2 ~ /[A-Za-z0-9]+/) print $0;}' > $dict_dir/lexicon-ch/lexicon-ch.txt || exit 1;`

the OOV lexicons is lost,because lexicon-ch-oov-mp.txt has only one column which is word.
so much lexicons is missing,in the end, unk  is included in mono/decode_dev/log/decode.1.log

**Comment by boystray** [comment]
@naxingyu

**Comment by boystray** [comment]
btw, $dict_dir/lexicon-ch/ch-char-dict-mp.txt is following
`%	PA1
3	SAN1
6	LIU4
8	BA1
9	JIU3
A	A
B	BI1
C	C
G	G
K	K
M	M
O	O
P	P
Q	Q
R	R
S	S
T	T
U	U
V	V
c	C
o	O
s	S`

i think it is missing Chinese char.
and follow the code, the $dict_dir/cedict/ch-dict-1.txt is 
`% PA1
3C SAN1 C
3P SAN1 P
3Q SAN1 Q
88 BA1 BA1
996 JIU3 JIU3 LIU4
A A
ACG A C G
B BI1
CP C P
MV M V
OS O S
P P
PK P K
PU P U
Q Q
T T
VCR V C R
cos C O S`

so i think ch-dict-1.txt is missing   Chinese char.maybe this is the root.

**Comment by boystray** [comment]
i have solve the bug.
"use utf8" don't treat Chinese character in Input/Output as utf8 string. I use binmode to tell perl to process  Input/Output as utf8.
like the following code
`cat $dict_dir/cedict/ch-dict-1.txt | awk '{print $1}' |\
  perl -e '
  use  utf8;
  binmode(STDIN,":encoding(utf8)");-----------------------treat STDIN as utf8
  binmode(STDOUT,":encoding(utf8)");
  while (<STDIN>) {
    @A = split(" ", $_);
    @chars = split("", $A[0]);
    foreach (@chars) {
      print "$_\n";
    }
  }
  ' | grep -v '^$' > $dict_dir/lexicon-ch/ch-char.txt || exit 1;`

**Comment by danpovey** [comment]
Great.  Can you please make a pull request to fix it?

**Comment by boystray** [comment]
i pull request #3434 to fix it

**Comment by naxingyu** [comment]
Thank you for the fix! Then it means #3386 is causing this bug for aidatatang, hkust and gale_mandarin. I'll fix them ASAP.

**Comment by danpovey** [comment]
@naxingyu  any progress on fixing this as it relates to those other recipes?

**Comment by naxingyu** [comment]
Sorry, totally forgot this. I'm on it now.

**Comment by wiranphowan** [comment]
wiranthphothiwan@gmail.com

ในวันที่ ส. 12 ต.ค. 2019 10:58 Xingyu Na <notifications@github.com>
เขียนว่า:

**Comment by naxingyu** [comment]
@danpovey I just realized this issue has been fixed by #3442 I forgot to refer this issue.

**Comment by naxingyu** [comment]
@danpovey this issue can be closed.

**Comment by jtrmal** [comment]
closing
