### ISSUE TITLE
Error in generating libgstkaldi.so

### ISSUE THREAD

**Issue by cibin91** [kaldi-asr/kaldi#344]
hi,
-> I downloaded the code from this repository and first run the make file from the tool folder
->Then from the src folder i run the make file
->When running the online demo from the voxforge folder in the egs,i get an issue in online-gmm-decode-faster
->So from the gst-plugin folder in the src,i run the make file to generate libgstkaldi.so
->But when running kaldimarshal.h file is notfound in gst-plugin
      What i have to do to solcve this issue or to get kaldimarshal.h

**Comment by danpovey** [comment]
The gst-plugin folder is not required to run online-gmm-decode-faster.
Without knowing what your issue was with online-gmm-decode-faster, I don't
know how to fix it.

Dan
