### ISSUE TITLE
Neural net expects 'ivector' features with dimension 100 but you provided 0

### ISSUE THREAD

**Issue by mahuichao** [kaldi-asr/kaldi#3446]
Hello ,I use kaldi source code to implement a tool like alignment ,but when I run to the code of :
`  decoder.Decode(decodable)` in decoder-wrappers,I got error:Neural net expects 'ivector' features with dimension 100 but you provided 0,I am sure there is no ivector,so can U help me to solve this problem?I think there should be a option for it,but I didn't find it.

**Comment by danpovey** [comment]
Likely you supplied the wrong args to the constructor of the decodable object.  Not really a bug so closing issue for now.  kaldi-help is preferred for these kinds of questions, but looking carefully at the constructor would likely help.  depends on the type of the decodable object.

**Comment by mahuichao** [comment]
@danpovey Thanks, guy.,and sorry for the question,I have thought the issue is for asking questions,this won't happen again.
