### ISSUE TITLE
FST Error

### ISSUE THREAD

**Issue by WorldHellow** [kaldi-asr/kaldi#3450]
I am receiving this error when enter the command ./run.sh

```
> Creating data/local/dict/lexiconp.txt from data/local/dict/lexicon.txt
> utils/prepare_lang.sh: line 547: fstaddselfloops: command not found
> ERROR: FstHeader::Read: Bad FST header: standard input
```
I have install openfst from the tools folder and has also entered the make command.

**Comment by danpovey** [comment]
Than it's a path issue.  Check your path.sh.  It should be in the same directory as run.sh.  And you're not saying which directory you are in, there are tons of files called run.sh.  But try to resolve this by yourself; our github is not for beginner questions like this.

**Comment by dhpollack** [comment]
@danpovey I have the same error. I noticed there is no fstaddselfloops.c in the tar file for openfst that is downloaded. I also downloaded several version on openslr.org/2 and didn't see it there either.

**Comment by danpovey** [comment]
fstaddselfloops comes from Kaldi itself, it's an extension.  So if you had
not compiled Kaldi or did not have $KALDI_ROOT/src/fstbin on your PATH, you
wouldn't get it.

**Comment by abdowiss** [comment]
also my problem
 a@a-VirtualBox:~/kaldi-trunk/egs/digits$ ./run.sh

===== PREPARING ACOUSTIC DATA =====


===== FEATURES EXTRACTION =====

steps/make_mfcc.sh --nj 1 --cmd utils/run.pl data/train exp/make_mfcc/train mfcc
utils/validate_data_dir.sh: Successfully validated data-directory data/train
steps/make_mfcc.sh: [info]: no segments file exists: assuming wav.scp indexed by utterance.
utils/run.pl: line 1: parallel/run.pl: No such file or directory
steps/make_mfcc.sh --nj 1 --cmd utils/run.pl data/test exp/make_mfcc/test mfcc
utils/validate_data_dir.sh: Successfully validated data-directory data/test
steps/make_mfcc.sh: [info]: no segments file exists: assuming wav.scp indexed by utterance.
utils/run.pl: line 1: parallel/run.pl: No such file or directory
steps/compute_cmvn_stats.sh data/train exp/make_mfcc/train mfcc
make_cmvn.sh: no such file data/train/feats.scp
steps/compute_cmvn_stats.sh data/test exp/make_mfcc/test mfcc
make_cmvn.sh: no such file data/test/feats.scp

===== PREPARING LANGUAGE DATA =====

utils/prepare_lang.sh data/local/dict <UNK> data/local/lang data/lang
Checking data/local/dict/silence_phones.txt ...
--> reading data/local/dict/silence_phones.txt
--> text seems to be UTF-8 or ASCII, checking whitespaces
--> text contains only allowed whitespaces
--> data/local/dict/silence_phones.txt is OK

Checking data/local/dict/optional_silence.txt ...
--> reading data/local/dict/optional_silence.txt
--> text seems to be UTF-8 or ASCII, checking whitespaces
--> text contains only allowed whitespaces
--> data/local/dict/optional_silence.txt is OK

Checking data/local/dict/nonsilence_phones.txt ...
--> reading data/local/dict/nonsilence_phones.txt
--> text seems to be UTF-8 or ASCII, checking whitespaces
--> text contains only allowed whitespaces
--> data/local/dict/nonsilence_phones.txt is OK

Checking disjoint: silence_phones.txt, nonsilence_phones.txt
--> disjoint property is OK.

Checking data/local/dict/lexicon.txt
--> reading data/local/dict/lexicon.txt
--> text seems to be UTF-8 or ASCII, checking whitespaces
--> text contains only allowed whitespaces
--> data/local/dict/lexicon.txt is OK

Checking data/local/dict/extra_questions.txt ...
--> data/local/dict/extra_questions.txt is empty (this is OK)
--> SUCCESS [validating dictionary directory data/local/dict]

**Creating data/local/dict/lexiconp.txt from data/local/dict/lexicon.txt
utils/prepare_lang.sh: line 502: fstaddselfloops: command not found
ERROR: FstHeader::Read: Bad FST header: standard input

===== LANGUAGE MODEL CREATION =====
===== MAKING lm.arpa =====


===== MAKING G.fst =====

./run.sh: line 82: arpa2fst: command not found

===== MONO TRAINING =====

steps/train_mono.sh --nj 1 --cmd utils/run.pl data/train data/lang exp/mono
steps/train_mono.sh: Initializing monophone system.
steps/train_mono.sh: line 71: feat-to-dim: command not found
error getting feature dimension

**Comment by jtrmal** [comment]
This looks like a clear case of either not compiling kaldi or not setting
the path correctly
Y.

**Comment by abdowiss** [comment]
please what's the problem 15 day  I don't can to test it  correctly 

cd s5
a@a-VirtualBox:~/kaldi-trunk/egs/yesno/s5$ ./run.sh
Preparing train and test data
Dictionary preparation succeeded
utils/prepare_lang.sh --position-dependent-phones false data/local/dict <SIL> data/local/lang data/lang
Checking data/local/dict/silence_phones.txt ...
--> reading data/local/dict/silence_phones.txt
--> text seems to be UTF-8 or ASCII, checking whitespaces
--> text contains only allowed whitespaces
--> data/local/dict/silence_phones.txt is OK

Checking data/local/dict/optional_silence.txt ...
--> reading data/local/dict/optional_silence.txt
--> text seems to be UTF-8 or ASCII, checking whitespaces
--> text contains only allowed whitespaces
--> data/local/dict/optional_silence.txt is OK

Checking data/local/dict/nonsilence_phones.txt ...
--> reading data/local/dict/nonsilence_phones.txt
--> text seems to be UTF-8 or ASCII, checking whitespaces
--> text contains only allowed whitespaces
--> data/local/dict/nonsilence_phones.txt is OK

Checking disjoint: silence_phones.txt, nonsilence_phones.txt
--> disjoint property is OK.

Checking data/local/dict/lexicon.txt
--> reading data/local/dict/lexicon.txt
--> text seems to be UTF-8 or ASCII, checking whitespaces
--> text contains only allowed whitespaces
--> data/local/dict/lexicon.txt is OK

Checking data/local/dict/extra_questions.txt ...
--> data/local/dict/extra_questions.txt is empty (this is OK)
--> SUCCESS [validating dictionary directory data/local/dict]

**Creating data/local/dict/lexiconp.txt from data/local/dict/lexicon.txt
utils/prepare_lang.sh: line 547: fstaddselfloops: command not found
ERROR: FstHeader::Read: Bad FST header: standard input
Preparing language models for test
local/prepare_lm.sh: line 13: arpa2fst: command not found
local/prepare_lm.sh: line 15: fstisstochastic: command not found
ERROR: ReadFst: Can't open file: data/lang_test_tg/G.fst
ERROR: FstHeader::Read: Bad FST header: tmpdir.g/empty_words.fst
Succeeded in formatting data.
steps/make_mfcc.sh --nj 1 data/train_yesno exp/make_mfcc/train_yesno mfcc
utils/validate_data_dir.sh: WARNING: you have only one speaker.  This probably a bad idea.
   Search for the word 'bold' in http://kaldi-asr.org/doc/data_prep.html
   for more information.
utils/validate_data_dir.sh: Successfully validated data-directory data/train_yesno
steps/make_mfcc.sh: [info]: no segments file exists: assuming wav.scp indexed by utterance.
run.pl: job failed, log is in exp/make_mfcc/train_yesno/make_mfcc_train_yesno.1.log
steps/compute_cmvn_stats.sh data/train_yesno exp/make_mfcc/train_yesno mfcc
steps/compute_cmvn_stats.sh: no such file data/train_yesno/feats.scp
fix_data_dir.sh: kept all 31 utterances.
fix_data_dir.sh: old files are kept in data/train_yesno/.backup
steps/make_mfcc.sh --nj 1 data/test_yesno exp/make_mfcc/test_yesno mfcc
utils/validate_data_dir.sh: WARNING: you have only one speaker.  This probably a bad idea.
   Search for the word 'bold' in http://kaldi-asr.org/doc/data_prep.html
   for more information.
utils/validate_data_dir.sh: Successfully validated data-directory data/test_yesno
steps/make_mfcc.sh: [info]: no segments file exists: assuming wav.scp indexed by utterance.
run.pl: job failed, log is in exp/make_mfcc/test_yesno/make_mfcc_test_yesno.1.log
steps/compute_cmvn_stats.sh data/test_yesno exp/make_mfcc/test_yesno mfcc
steps/compute_cmvn_stats.sh: no such file data/test_yesno/feats.scp
fix_data_dir.sh: kept all 31 utterances.
fix_data_dir.sh: old files are kept in data/test_yesno/.backup
steps/train_mono.sh --nj 1 --cmd utils/run.pl --totgauss 400 data/train_yesno data/lang exp/mono0a
steps/train_mono.sh: Initializing monophone system.
steps/train_mono.sh: line 75: feat-to-dim: command not found
error getting feature dimension
mkgraph.sh: expected data/lang_test_tg/G.fst to exist
steps/decode.sh --nj 1 --cmd utils/run.pl exp/mono0a/graph_tgpr data/test_yesno exp/mono0a/decode_test_yesno
steps/decode.sh: Error: no such file data/test_yesno/split1/1/feats.scp
grep: exp/mono0a/decode_test_yesno/wer_*: Aucun fichier ou dossier de ce type

**Comment by abdowiss** [comment]
I had complied kaldi ,

**Comment by JohnoverBoard** [comment]
May I know how? I am trying out the exact same tutorial of yesno hebrew

**Comment by ahmad88me** [comment]
@WorldHellow I had a similar issue too.
Try to check the dependencies `extras/check_dependencies.sh`
```
kaldi/tools $ extras/check_dependencies.sh
extras/check_dependencies.sh: Intel MKL does not seem to be installed.
 ... Download the installer package for your system from: 
 ...   https://software.intel.com/mkl/choose-download
 ... You can also use other matrix algebra libraries. For information, see:
 ...   http://kaldi-asr.org/doc/matrixwrap.html
```
I downloaded the KML, and compiled the kaldi from the source. Try to go to /src and follow the instructions in the INSTALL file. I hope this helps.

**Comment by terry891** [comment]
This is what I found.
 
There are a lot of .cc files regarding this NOT FOUND error in directory /src/fstbin. There is one named fstaddselfloops.cc, which is causing the issue above. However, the .cc file cannot run as executable, so we have to do make (there should be a Makefile in /src/fstbin).

1. To use `make` in /src/fstbin, you have to use `make` in the prior directory /src in order to create the Kaldi.mk file
2. In /src, you can change line 583 in `vim configure` to the directory of your MKL package
3. Then run `./configure`, `make -j clean depend`, 'make -j <NGPU>'
4. Then go to /src/fstbin do 'make' (this should take a while)
5. You should see there are many executables and .o files, one of them is called fstaddselfloops
6. Make you you put this folder kaldi/src/fstbin in your Path variables `export PATH=<path to your Kaldi dir>/src/fstbin:$PATH`

Now the problem should be fixed! :)

**Comment by atarikaltunn** [comment]
> This is what I found.
> 
> There are a lot of .cc files regarding this NOT FOUND error in directory /src/fstbin. There is one named fstaddselfloops.cc, which is causing the issue above. However, the .cc file cannot run as executable, so we have to do make (there should be a Makefile in /src/fstbin).
> 
> 1. To use `make` in /src/fstbin, you have to use `make` in the prior directory /src in order to create the Kaldi.mk file
> 2. In /src, you can change line 583 in `vim configure` to the directory of your MKL package
> 3. Then run `./configure`, `make -j clean depend`, 'make -j '
> 4. Then go to /src/fstbin do 'make' (this should take a while)
> 5. You should see there are many executables and .o files, one of them is called fstaddselfloops
> 6. Make you you put this folder kaldi/src/fstbin in your Path variables `export PATH=<path to your Kaldi dir>/src/fstbin:$PATH`
> 
> Now the problem should be fixed! :)

thank you Terry,

I am new with kaldi and ml. I've tried your solution and now I have new errors :) 

> /root/eesen/asr_egs/wsj/utils/ctc_compile_dict_token.sh: line 63: fstarcsort: command not found
> /root/eesen/asr_egs/wsj/utils/ctc_compile_dict_token.sh: line 62: fstcompile: command not found

I could not find anything to do when I google it.

**Comment by EchoInCloud** [comment]
> Than it's a path issue. Check your path.sh. It should be in the same directory as run.sh. And you're not saying which directory you are in, there are tons of files called run.sh. But try to resolve this by yourself; our github is not for beginner questions like this.

--------------------
I have read many posts like this from you..
I remember you asking similar questions a few years ago and expecting others to answer..

You threw together this "vosk-api" years ago, which is full of carelessness and nonsense.. since then you haven't fixed anything.. basic things are missing from your application.. lazy and tedious work..

And we are not here to improve a sloppy job. of yours.

(despite that, I also fixed many basic errors in it... it's rubbish in its original form... not a stand-alone application...)

NOTE: The Kaldi is working properly on windows and I build it with only 8 issues out of 10

You are simply a primitive jerk with people, and I would love tosee how would you react if another person's app does not work properly and you need to fix it and clean. It1s funny you act like you did not ask anything in the past.. until the Kaldi came to me, I didn't even know you existed.. you haven't changed the world.. what you have done so far, someone else would have done it and maybe with not that much issues...

**Comment by EchoInCloud** [comment]
@danpovey 
https://github.com/kaldi-asr/kaldi/issues/3450#issuecomment-509276662
> Than it's a path issue. Check your path.sh. It should be in the same directory as run.sh. And you're not saying which directory you are in, there are tons of files called run.sh. But try to resolve this by yourself; our github is not for beginner questions like this.

--------------------
I have read many posts like this from you..
I remember you asking similar questions a few years ago and expecting others to answer..

You threw together this "vosk-api" years ago, which is full of carelessness and nonsense.. since then you haven't fixed anything.. basic things are missing from your application.. lazy and tedious work..

And we are not here to improve a sloppy job. of yours.

(despite that, I also fixed many basic errors in it... it's rubbish in its original form... not a stand-alone application...)

**Comment by jtrmal** [comment]
Except Vosk/API is not Dan's work at all and opinions from an identity that has zero evidence of doing anything useful on github except insulting people is not something I will leave to exist.
