### ISSUE TITLE
egs/wsj/s5/steps/nnet/train.sh line 212 if [ -n $feature_transform ]; then  always return true

### ISSUE THREAD

**Issue by xiaominfc** [kaldi-asr/kaldi#3453]
hi 
I find：

egs/wsj/s5/steps/nnet/train.sh line 212
```
if [ -n $feature_transform ]; then
```
the code return true always 

I think forget "" for the $feature_transform maybe

like:
```
if [ -n "$feature_transform" ]; then
or
if[[ -n $feature_transform ]]; then

```

end:
thanks for you and your project!

**Comment by xiaominfc** [comment]
line 279  also:
```
if [ -n $feature_transform_proto ]; then
```

**Comment by danpovey** [comment]
Hm you're right; 
 `if [ -n ]; then echo yes; fi`
 prints yes (one would expect it to print nothing if it were the opposite of -z, which does actually work if you leave out the quotes, but only with single brackets, not double brackets).  I suppose this is a kind of inconsistency / design failure in bash itself.  If you add the quotes and make a PR I will merge it.
