### ISSUE TITLE
inconsistent behavior of feat-to-dim for wspecifier and wxfilename

### ISSUE THREAD

**Issue by csukuangfj** [kaldi-asr/kaldi#3457]
See the code
https://github.com/kaldi-asr/kaldi/blob/b5385b46c135f8d1f2bf4f9924e287e6fd91cd23/src/featbin/feat-to-dim.cc#L51-L61

It prints the dimension of every utterance when it is a wspecifier.
However, it only prints the dim of the first utterance for a wxfilename.

**Comment by danpovey** [comment]
It is by design.

**Comment by csukuangfj** [comment]
@danpovey 

could you please tell me the reason behind such a design or point me to
some related document?

**Comment by danpovey** [comment]
it's for when you need the dimension of the features.  they are all the same.  find examples by `git grep feat-to-dim`.
