### ISSUE TITLE
Error comment in LogSub

### ISSUE THREAD

**Issue by csukuangfj** [kaldi-asr/kaldi#3459]
See the code
https://github.com/kaldi-asr/kaldi/blob/b5385b46c135f8d1f2bf4f9924e287e6fd91cd23/src/base/kaldi-math.h#L226-L227

It actually returns `log(exp(x) - exp(y))`

**Comment by danpovey** [comment]
I prefer if you just fix things like this in your PR but not create separate issues for little things like this (and also missing asserts).
