### ISSUE TITLE
potential access array out of bounds in VectorBase<Real>::Floor

### ISSUE THREAD

**Issue by csukuangfj** [kaldi-asr/kaldi#3460]
See the code

https://github.com/kaldi-asr/kaldi/blob/b5385b46c135f8d1f2bf4f9924e287e6fd91cd23/src/matrix/kaldi-vector.cc#L804-L807

The precondition should be 

```
this->Dim() <= v.Dim()
```

**Comment by csukuangfj** [comment]
The same problem exists also for 

https://github.com/kaldi-asr/kaldi/blob/b5385b46c135f8d1f2bf4f9924e287e6fd91cd23/src/matrix/kaldi-vector.cc#L824-L826

**Comment by csukuangfj** [comment]
The following function checks the dimension explicitly
https://github.com/kaldi-asr/kaldi/blob/b5385b46c135f8d1f2bf4f9924e287e6fd91cd23/src/matrix/kaldi-vector.cc#L784-L790

**Comment by danpovey** [comment]
The intention was that they should be the same size.  You can just add an assert to that effect.

**Comment by songmeixu** [comment]
This issue has been fixed in merged commit: 1ff668adbec7987a8b9f91932a786ad8c4b75d86. (E.g https://github.com/kaldi-asr/kaldi/commit/1ff668adbec7987a8b9f91932a786ad8c4b75d86#diff-aed5c3631e97229af5754522462dd62fR813) Is't right? @csukuangfj  If so, it can be closed.

**Comment by csukuangfj** [comment]
+2
