### ISSUE TITLE
CMVN-related to prepare decoding scripts for nnet3

### ISSUE THREAD

**Issue by LeviBarnes** [kaldi-asr/kaldi#3461]
Make appropriate changes to egs/wsj/s5/steps/online/nnet3/prepare_online_decoding.sh, etc. to generate conf file for decoding with CMVN.

Assign to me, please.

**Comment by danpovey** [comment]
Thanks!  We'll just note that you are assigned, I don't think I can github-assign people who aren't officially members, and I don't really add the "big" list of contributors to that list, it would quickly get confusing.

**Comment by vesis84** [comment]
Hi, I am looking into adding support of online-cmvn to train/decode chain scripts. Along the way I will be  asking questions. That I'll need to discuss with Dan, those will be posted here.

Question 1), 
in 'RM' code i found that the i-vector extraction is done by a binary: 'ivector-extract-online2'. Is this the only way how the i-vectors are extracted or are there other scripts that need to be updated as well? 
(currently I added '--use-cmvn' flag to 'steps/online/nnet2/train_ivector_extractor.sh', 
and I track it for ivector extraction by touching empty file 'online_cmvn_iextractor')

So it seems that I need to add a new option '--online-cmvn-iextractor' to 'ivector-extract-online2'.
That is both easy to implement and to understand...

**Comment by danpovey** [comment]
I think we discussed this a bit in #3439 already.  The thing to do is to add an option to ivector-extra-online2 (but it would go somewhere in the appropriate options class):
like --apply-cmvn-to-feats, default false, with a docstring like: "If true, apply the online CMVN also the features used to estimate the i-vectors (not just in getting posteriors)."  It's quite simple as far as the i-vectors are concerned.  It would also be necessary to add support for CMVN-ing the features that get given to the nnet (this is a separate issue from the i-vectors, code-wise).  In the training script it would be done via changes to the command lines that get issued, using apply-cmvn-online or whatever it is.  In online decoding changes would have to be made too, to support CMVN at that level (if @luitjens et al haven't already done this, but I think they might have).

 https://github.com/kaldi-asr/kaldi/pull/3439#issuecomment-516038431

**Comment by vesis84** [comment]
Okay, this is pretty much consistent with what I have now... Thanks Dan.

Question 2),
in 'RM' recipe, in 'local/chain/run_tdnn.sh', there is a script 'steps/nnet3/chain/build_tree.sh', which is run with 'data/train', while the 'train.py' is called with 'data/train_hires'. 

Would it make sense to use the same features for 'build_tree' and 'train' ?
If yes, I'll add the online-cmvn support already to the 'steps/nnet3/chain/build_tree.sh'.
Is this okay?

K.

**Comment by danpovey** [comment]
The build_tree script would normally be used with GMM features.  I don't
think there is much value in adding support for online-cmvn features as we
wouldn't be using that in the forseeable future.  If you do want to do it
though, be super careful to not break any of its existing behavior.

**Comment by vesis84** [comment]
Please look at #3498

**Comment by vesis84** [comment]
Closing this, the changes were already made in #3498 and #3560 ...

**Comment by vesis84** [comment]
Closing this, the changes were already made in #3498 and #3560 ...
