### ISSUE TITLE
compute cmvn stats error

### ISSUE THREAD

**Issue by v-yunbin** [kaldi-asr/kaldi#3463]
when use the script "compute_cmvn_stats.sh" to compute cmvn, met follows errors:
```
compute-cmvn-stats --spk2utt=ark:data/train_sp/spk2utt scp:data/train_sp/feats.scp ark,scp:/home/kaldi/kaldi-master/egs/aishell2/s5/mfcc_perturbed/cmvn_train_sp.ark,/home/kaldi/kaldi-master/egs/aishell2/s5/mfcc_perturbed/cmvn_train_sp.scp
ASSERTION_FAILED (compute-cmvn-stats[5.5]:InitCmvnStats():cmvn.cc:26) : 'dim > 0'

[ Stack-Trace: ]
kaldi::MessageLogger::HandleMessage(kaldi::LogMessageEnvelope const&, char const*)
kaldi::FatalMessageLogger::~FatalMessageLogger()
kaldi::KaldiAssertFailure_(char const*, char const*, int, char const*)
kaldi::InitCmvnStats(int, kaldi::Matrix<double>*)
main
__libc_start_main
_start
```

**Comment by danpovey** [comment]
You must have an empty matrix as one of your feature matrices.  You could do
`feat-to-len scp:data/train_sp/feats.scp ark,t:- | grep -w 0`
to find out which utterances are affected.  I'm not sure why this would happen.  Likely a preceding error.  Closing this as this kind of thing should go on the list, not here.

**Comment by v-yunbin** [comment]
automatic filtering of entries with feature length of 0:
feat-to-len scp:data/train_sp/feats.scp ark,t:feat-to-len scp:data/train_sp/feats.len
awk ' { if($2>0){ print($0); } }' feat.len > feat.len.tmp
awk '{a[$1]++;b[$1]=$0} END {for(c in a) if(a[c]!=1) print b[c]}' feat.len.tmp train_sp/feats.scp > ./feat.scp
rm train_sp/feats.scp
cp train_sp/feat.scp train_sp/feats.scp
