### ISSUE TITLE
./configure can't see fst.h 

### ISSUE THREAD

**Issue by Jake-s16** [kaldi-asr/kaldi#3464]
I did just manage to do the ./configure, make and make install for openfst 1.7.2 but
./configure in the kaldi folder can't see fst.h because it's looking in /include/fst/ instead of /usr/local/include/fst/

**Comment by danpovey** [comment]
use the option e.g. --fst-root=/usr/local
I don't know if it will work.  Kaldi provides an installation setup that works, I recommend to follow that.
