### ISSUE TITLE
Should the text mode of Write function increase the output precision?

### ISSUE THREAD

**Issue by JiayiFu** [kaldi-asr/kaldi#3468]
The text mode of `MatrixBase<Real>::Write` uses the default precision of `std::ostream`. 
If the true value of a floating point is 57.0697556, what is written in the text file is 57.06976.
When I use other programs to read the values from the text file to do some calculations, there would be an error due to the precision gap. Another way to avoid this gap is to use the binary mode but I think both modes should output the correct values?
Should `MatrixBase<Real>::Write` increase the output precision?

**Comment by danpovey** [comment]
It's using the default precision.  I can't think of any important cases
where these small differences would matter.
In any case we mainly use text mode only for debugging.
