### ISSUE TITLE
OnlineFeatureMatrix::Good is not implemented

### ISSUE THREAD

**Issue by csukuangfj** [kaldi-asr/kaldi#3469]
See the code

https://github.com/kaldi-asr/kaldi/blob/b5385b46c135f8d1f2bf4f9924e287e6fd91cd23/src/online/online-feat-input.h#L386

`find . -type f -name "*.cc" -exec grep -n "Good" {} +`
cannot find it.

**Comment by danpovey** [comment]
That code is old and not really maintained.  Please fix this next time you fix other cosmetic issues.  But I'll close the issue here  as it's not important enough to track.
