### ISSUE TITLE
Help to run example online demo

### ISSUE THREAD

**Issue by cibin91** [kaldi-asr/kaldi#347]
hi,
 ->  I builded kaldi in Ubuntu
 ->I have to run a speech recognition online demo,which is in 
                      /egs/voxforge/online_demo
->I used ./run.sh --test-mode live ,to run demo
       But it shows the following error
              ->./run.sh: line 57: online-gmm-decode-faster: command not found
    Instruct me to run an online demo using my own voice

**Comment by danpovey** [comment]
It's a path issue.  I just pushed a fix to path.sh in the voxforge setup to
add onlinebin/ to the path.
you have to do 'git pull' to get the change.

Dan

**Comment by cibin91** [comment]
hi Dan,
        Thanks for the reply,
  Do i need to run the make in the onlinebin
              kaldimaster/src/onlinebin->make
  Before running path.sh in voxforge

**Comment by cibin91** [comment]
d
