### ISSUE TITLE
thchs30 dae run failed

### ISSUE THREAD

**Issue by KiAlexander** [kaldi-asr/kaldi#3470]
**thchs30**

DAE: generate training data...
run.pl: 8 / 8 failed, log is in exp/dae/gendata/add_noise_train.*.log

log:
/home/yjm/.pyxbld/temp.linux-x86_64-3.6/pyrex/thchs30_util.c: In function '__pyx_pw_12thchs30_util_1energy':
/home/yjm/.pyxbld/temp.linux-x86_64-3.6/pyrex/thchs30_util.c:1202:13: warning: '__pyx_v_e' may be used uninitialized in this function [-Wmaybe-uninitialized]
   __pyx_v_e = (__pyx_v_e / __pyx_v_l);
             ^
/home/yjm/.pyxbld/temp.linux-x86_64-3.6/pyrex/thchs30_util.c:1124:9: note: '__pyx_v_e' was declared here
   float __pyx_v_e;
         ^
/home/yjm/.pyxbld/temp.linux-x86_64-3.6/home/yjm/.pyxbld/temp.linux-x86_64-3.6/pyrex/thchs30_util.o: file not recognized: File truncated
collect2: error: ld returned 1 exit status
Cython possibly not installed, using standard python code. The process might be slow
Traceback (most recent call last):
  File "local/dae/add-noise-mod.py", line 154, in <module>
    main()
  File "local/dae/add-noise-mod.py", line 149, in main
    output_wave_file(args.wavdir, fname, result)
  File "local/dae/add-noise-mod.py", line 91, in output_wave_file
    f.write(wave_header(mat, 16000))
  File "local/dae/add-noise-mod.py", line 78, in wave_header
    16)  # bits / sample
struct.error: char format requires a bytes object of length 1

**Comment by danpovey** [comment]
@naxingyu do you know anything?

In any case, installing cython might resolve this

**Comment by KiAlexander** [comment]
cython  is  already installed before

$ cython -V
Cython version 0.28.2

**Comment by naxingyu** [comment]
looking into it.

**Comment by naxingyu** [comment]
This error happens in python 3. Current tools/check_depedencies.sh will make sure py2.7 is default in Kaldi environment. @KiAlexander please run that shell and see if the error goes away.
Meanwhile, I see that current trend is to support py3, so I'll make a fix to make this script is py3 compatible. @danpovey

**Comment by naxingyu** [comment]
There are too errors. First one is complaining that Cython is not installed in the python environment that it runs, so @KiAlexander could you run python and python3, and try `import pyximport`? See which one fails.

**Comment by KiAlexander** [comment]
**Thanks**, python2 failes to import pyximport  , while python3 which I use succeeds in importing that.
After I run that shell (tools/check_depedencies.sh), py3.6 is set as default. Cython error is solved, but struct erros still happan.

"
# local/dae/add-noise-mod.py --noise-level 0 --sigma0 10 --seed 32 --verbose 0 --noise-prior 0.0,10.0,10.0,10.0 --noise-src data/dae/noise/noise.scp --wav-src exp/dae/gendata/train_split_7.scp --wavdir wav/dae/train 
# Started at Wed Jul 17 14:04:29 CST 2019
#
3.6.5 |Anaconda, Inc.| (default, Apr 29 2018, 16:14:56) 
[GCC 7.2.0]
sys.version_info(major=3, minor=6, micro=5, releaselevel='final', serial=0)
**Traceback (most recent call last):
  File "local/dae/add-noise-mod.py", line 157, in <module>
    main()
  File "local/dae/add-noise-mod.py", line 147, in main
    scale = math.sqrt(noise / noise_energies[type])
ValueError: math domain error**
# Accounting: time=2 threads=1
# Ended (code 1) at Wed Jul 17 14:04:31 CST 2019, elapsed time 2 seconds
# local/dae/add-noise-mod.py --noise-level 0 --sigma0 10 --seed 32 --verbose 0 --noise-prior 0.0,10.0,10.0,10.0 --noise-src data/dae/noise/noise.scp --wav-src exp/dae/gendata/train_split_8.scp --wavdir wav/dae/train 
# Started at Wed Jul 17 14:04:29 CST 2019
#
3.6.5 |Anaconda, Inc.| (default, Apr 29 2018, 16:14:56) 
[GCC 7.2.0]
sys.version_info(major=3, minor=6, micro=5, releaselevel='final', serial=0)
**Traceback (most recent call last):
  File "local/dae/add-noise-mod.py", line 157, in <module>
    main()
  File "local/dae/add-noise-mod.py", line 152, in main
    output_wave_file(args.wavdir, fname, result)
  File "local/dae/add-noise-mod.py", line 94, in output_wave_file
    f.write(wave_header(mat, 16000))
  File "local/dae/add-noise-mod.py", line 81, in wave_header
    16)  # bits / sample
struct.error: char format requires a bytes object of length 1**
"

And at last I pip intsall cython in python2, and run check_depedencies.sh, it works out!

**Comment by Mryangkaitong** [comment]
> looking into it
HELLO, i am python2,but have error
`# local/dae/add-noise-mod.py --noise-level 0 --sigma0 10 --seed 32 --verbose 0 --noise-prior 0.0,10.0,10.0,10.0 --noise-src data/dae/noise/noise.scp --wav-src exp/dae/gendata/train_split_1.scp --wavdir wav/dae/train 
# Started at Wed Aug 19 12:44:56 CST 2020
#
Traceback (most recent call last):
  File "local/dae/add-noise-mod.py", line 154, in <module>
    main()
  File "local/dae/add-noise-mod.py", line 144, in main
    scale = math.sqrt(noise / noise_energies[type])
ValueError: math domain error
# Accounting: time=545 threads=1
# Ended (code 1) at Wed Aug 19 12:54:02 CST 2020, elapsed time 545 seconds`
do you know anything?

**Comment by danpovey** [comment]
Thats a local script, Im not going to spend time debugging it myself but
please make a PR if you figure it out.

**Comment by Mryangkaitong** [comment]
OK thanks
