### ISSUE TITLE
Number of jobs not configured in 'steps/nnet3/train_dnn.py' when generatings egs

### ISSUE THREAD

**Issue by parag-verma-lw** [kaldi-asr/kaldi#3473]
The `steps/nnet3/train_dnn.py` script calls the `generate_egs()` function in `steps/libs/nnet3/train/frame_level_objf/acoustic_model.py`, which in turn calls `steps/nnet3/get_egs.sh`

However, since the number of jobs / --nj argument is not passed to `steps/nnet3/get_egs.sh`, the default `nj` value (6) is used, which causes errors further down the line.

A simple fix I used was to create an extra argument `num_jobs` in `generate_egs`. Since `num_jobs` is already a variable defined in `steps/nnet3/train_dnn.py`, I simply passed it along and called `steps/nnet3/get_egs.sh` with `--nj=num_jobs`

**Comment by danpovey** [comment]
You could use something like `--egs.opts "--nj 4"` to pass that option into get_egs.sh.
