### ISSUE TITLE
Kaldi cann't detect cuda and may be a bug

### ISSUE THREAD

**Issue by shanguanma** [kaldi-asr/kaldi#3479]
system configure:
combine Kaldi with cuda80,cudnn7.1,mathlib is ATLAS.
GPU driver information is :
Fri Jul 19 11:01:48 2019       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 418.67       Driver Version: 418.67       CUDA Version: 10.1     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla K20Xm         On   | 00000000:02:00.0 Off |                    0 |
| N/A   25C    P8    29W / 235W |      0MiB /  5700MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   1  Tesla K20Xm         On   | 00000000:84:00.0 Off |                    0 |
| N/A   26C    P8    30W / 235W |      0MiB /  5700MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+

train model is chain/cnn_tdnn_1a.sh, error log:

# Started at Fri Jul 19 10:41:47 SGT 2019 on node01
nnet3-chain-train --use-gpu=yes --apply-deriv-weights=False --l2-regularize=0.0 --leaky-hmm-coefficient=0.1 --read-cache=exp/chain_1a/tdnn_cnn_tdnnf_1c_sp/cache.836 --xent-regularize=0.1 --print-interval=10 --momentum=0.0 --max-param-change=2.0 --backstitch-training-scale=0.0 --backstitch-training-interval=1 --l2-regularize-factor=0.0666666666667 --optimization.memory-compression-level=2 --srand=836 'nnet3-am-copy --raw=true --learning-rate=0.000543996234528 --scale=1.0 exp/chain_1a/tdnn_cnn_tdnnf_1c_sp/836.mdl - |' exp/chain_1a/tdnn_cnn_tdnnf_1c_sp/den.fst 'ark,bg:nnet3-chain-copy-egs                          --frame-shift=2                         ark:exp/chain_1a/tdnn_cnn_tdnnf_1c_sp/egs/cegs.60.ark ark:- |                         nnet3-chain-shuffle-egs --buffer-size=5000                         --srand=836 ark:- ark:- | nnet3-chain-merge-egs                         --minibatch-size=64 ark:- ark:- |' exp/chain_1a/tdnn_cnn_tdnnf_1c_sp/837.15.raw
ERROR (nnet3-chain-train[5.5.424~1-b5385]:SelectGpuId():cu-device.cc:166) No CUDA GPU detected!, diagnostics: cudaError_t 30 : "unknown error", in cu-device.cc:166

[ Stack-Trace: ]
nnet3-chain-train(kaldi::MessageLogger::LogMessage() const+0x8a3) [0x8a9235]
nnet3-chain-train(kaldi::MessageLogger::LogAndThrow::operator=(kaldi::MessageLogger const&)+0x11) [0x591701]
nnet3-chain-train(kaldi::CuDevice::SelectGpuId(std::string)+0x3eb) [0x773ceb]
nnet3-chain-train(main+0x406) [0x5901ee]
/lib64/libc.so.6(__libc_start_main+0xf5) [0x2aaac03cdaf5]
nnet3-chain-train() [0x58fd19]

kaldi::KaldiFatalError
# Ended (code 65280) at Fri Jul 19 10:41:47 SGT 2019, elapsed time 181 seconds

**Comment by danpovey** [comment]
"Unknown error" likely indicates driver issues.  You should verify that other programs can access the GPU on that node, e.g. try to find the NVidia samples.   Your local sysadmin may need to help.

**Comment by shanguanma** [comment]
Thanks for your quickly reply ,Dan. I will try to test it.
