### ISSUE TITLE
In lattice-faster-decoder.cc:AdvanceDecoding [LINE 694-715]

### ISSUE THREAD

**Issue by ALeiQ** [kaldi-asr/kaldi#3483]
Strictly speaking，there should use [max_active-1] and [min_active-1], in nth_element and tmp_array_

**Comment by ALeiQ** [comment]
if (tmp_array_.size() > static_cast<size_t>(config_.max_active)) {
      std::nth_element(tmp_array_.begin(),
                       tmp_array_.begin() + config_.max_active,
                       tmp_array_.end());
      max_active_cutoff = tmp_array_[config_.max_active];
    }

i think there should replace by
      std::nth_element(tmp_array_.begin(),
                       tmp_array_.begin() + config_.max_active - 1,
                       tmp_array_.end());
      max_active_cutoff = tmp_array_[config_.max_active - 1];
Actually, there will not crash..

**Comment by danpovey** [comment]
Closing this because it doesn't really matter (using max-active+1 instead of max-active elements.)
