### ISSUE TITLE
The problem of network structure  in transfer learning

### ISSUE THREAD

**Issue by lianrzh** [kaldi-asr/kaldi#3484]
https://github.com/kaldi-asr/kaldi/blob/master/egs/rm/s5/local/chain/tuning/run_tdnn_wsj_rm_1a.sh

I can't find the chain model structure of wsj model(`src_mdl=../../wsj/s5/exp/chain/tdnn1d_sp/final.mdl`), so it's not easy to understand the generation process of network configure file. Can you explain the meanings of ` input=Append(tdnn6.renorm@-3,tdnn6.renorm)` (`relu-renorm-layer name=tdnn-target input=Append(tdnn6.renorm@-3,tdnn6.renorm) dim=450`).
In addition, I would like to ask how can I know what network layer is there and how to configure it.
Thanks.

**Comment by danpovey** [comment]
That looks to me like an older configuration.  It means that to generate the input of that layer for time t, it appends the output of layer tdnn6.renorm at time t-3, with the output of layer tdnn6.renorm at time t.  You shouldn't really ask this type of question on github.
