### ISSUE TITLE
cudaError invalid argument

### ISSUE THREAD

**Issue by mahuichao** [kaldi-asr/kaldi#3488]
I do GOP with kaldi, there are two stage in one thread:**compute forward _prob(nnet3-compute)** .**do alignment(which I do decode and compute forward prob again)**.
But int the second stage when I do **decode** ,I got Error :
>   "ERROR ([5.4]:SetZero():cudamatrix/cu-matrix.cc:488) cudaError_t 11 : "invalid argument" returned from 'cudaMemset2D(data_, stride_ * sizeof(Real), 0.0, num_cols_ * sizeof(Real), num_rows_ )'",
When I see the source code ,the error place like follows :
`  CuMatrix<BaseFloat> ivector_feats_cu;
  if (ivector.Dim() > 0) {
    ivector_feats_cu.Resize(1, ivector.Dim());// here error occurred
    ivector_feats_cu.Row(0).CopyFromVec(ivector);
    computer.AcceptInput("ivector", &ivector_feats_cu);
  }
  computer.Run()`

in the function Resize:
`CuTimer tim;
CU_SAFE_CALL(cudaMemset2D(data_, stride_ * sizeof(Real), 0,
                           num_cols_ * sizeof(Real), num_rows_ ));
CuDevice::Instantiate().AccuProfile("CuMatrix::SetZero", tim);
`
Is this a bug I checked the argument,data_ is not NULL and other like num_cols_ and num_rows_ is ok too

**Comment by danpovey** [comment]
I notice it's an older Kaldi version but that's likely not the reason.
It's almost certainly a bug in your code, either w.r.t. GPU initialization (e.g. doing it after already doing work using CuMatrix), or possibly something related to multi-threading.  Or maybe just a memory bug.  Without knowing your code I couldn't say.

**Comment by mahuichao** [comment]
yes,I think this is bz of doing **Resize** in Second Stage after already doing work using CuMatrix in the **first stage**. So Can U give me some advice to this problem? Thanks

**Comment by danpovey** [comment]
Resizing existing matrices is fine, it's not that.   Without seeing your code I can't really debug it.

**Comment by mahuichao** [comment]
@danpovey OK,still thanks,I will check it again .
