### ISSUE TITLE
Kaldi Transcriptions for new audio

### ISSUE THREAD

**Issue by bhavana012** [kaldi-asr/kaldi#3489]
I've  trained a kaldi model using my own data. I guess the results are in mono/decode/logs/decode.1.log.
I'm trying to find a way in which I could use this model to get transcriptions for a new audio file.
And also if there's a way I could use reinforcement learning for the model?

**Comment by kkm000** [comment]
This tracker is for Kaldi development only. If you have a question about using Kaldi, please use the kald-help discussion group: https://groups.google.com/forum/#!forum/kaldi-help

Instructions for joining are available at: http://kaldi-asr.org/forums.html

You'll certainly get a better help there than here, it's active and a very friendly user group!
