### ISSUE TITLE
MKL installation failed

### ISSUE THREAD

**Issue by hbutzl** [kaldi-asr/kaldi#3492]
W: The repository 'http://ppa.launchpad.net/t-tujikawa/ppa/ubuntu xenial Release' does not have a Release file.
N: Data from such a repository can't be authenticated and is therefore potentially dangerous to use.
N: See apt-secure(8) manpage for repository creation and user configuration details.
E: Failed to fetch http://ppa.launchpad.net/t-tujikawa/ppa/ubuntu/dists/xenial/main/binary-amd64/Packages  404  Not Found
E: Some index files failed to download. They have been ignored, or old ones used instead.
extras/install_mkl.sh: MKL package intel-mkl-64bit-2019.2-057 installation FAILED.

**Comment by xbsdsongnan** [comment]
download by yourself,then put the tools and install

**Comment by danpovey** [comment]
I don't see any repos like that in the install_mkl.sh script, it only uses
official Intel repos, which wouldn't
pull in any user stuff like that.  Likely an existing issue with your
apt-sources or whatever it's called.

**Comment by kkm000** [comment]
Find and remove the line `deb http://ppa.launchpad.net/t-tujikawa/ppa/ubuntu xenial Release` from either `/etc/apt/sources.list` or some file in `/etc/apt/sources.list.d/`, and run `apt-get update`. Your apt is broken by this line. If you need software from it, re-add it later using newer, secure methods (sorry, I have no time help with that, but info is abundant on the internet). This error is related to MKL; your apt setup is broken.
