### ISSUE TITLE
dnn training error

### ISSUE THREAD

**Issue by xbsdsongnan** [kaldi-asr/kaldi#3493]
DNN training: stage 0: feature generation
producing fbank for train
steps/make_fbank.sh --nj 2 --cmd run.pl data/fbank/train exp/make_fbank/train fbank/train
utils/validate_data_dir.sh: Successfully validated data-directory data/fbank/train
steps/make_fbank.sh: [info]: no segments file exists: assuming wav.scp indexed by utterance.
steps/make_fbank.sh: Succeeded creating filterbank features for train
steps/compute_cmvn_stats.sh data/fbank/train exp/fbank_cmvn/train fbank/train
Succeeded creating CMVN stats for train
producing fbank for dev
steps/make_fbank.sh --nj 2 --cmd run.pl data/fbank/dev exp/make_fbank/dev fbank/dev
utils/validate_data_dir.sh: Successfully validated data-directory data/fbank/dev
steps/make_fbank.sh: [info]: no segments file exists: assuming wav.scp indexed by utterance.
steps/make_fbank.sh: Succeeded creating filterbank features for dev
steps/compute_cmvn_stats.sh data/fbank/dev exp/fbank_cmvn/dev fbank/dev
Succeeded creating CMVN stats for dev
producing fbank for test
steps/make_fbank.sh --nj 2 --cmd run.pl data/fbank/test exp/make_fbank/test fbank/test
utils/validate_data_dir.sh: Successfully validated data-directory data/fbank/test
steps/make_fbank.sh: [info]: no segments file exists: assuming wav.scp indexed by utterance.
steps/make_fbank.sh: Succeeded creating filterbank features for test
steps/compute_cmvn_stats.sh data/fbank/test exp/fbank_cmvn/test fbank/test
Succeeded creating CMVN stats for test
producing test_fbank_phone
# INFO
steps/nnet/train.sh : Training Neural Network
	 dir       : exp/tri4b_dnn 
	 Train-set : data/fbank/train 10000, exp/tri4b_ali 
	 CV-set    : data/fbank/dev 893 exp/tri4b_ali_cv 

SKIPPING TRAINING... (steps/nnet/train.sh)
nnet already trained : exp/tri4b_dnn/final.nnet (nnet/nnet_iter14_learnrate7.8125e-06_tr1.0350_cv1.3844_final_)
# Accounting: time=0 threads=1
# Ended (code 0) at Fri Jul 26 21:03:23 CST 2019, elapsed time 0 seconds
# steps/nnet/train.sh --copy_feats false --cmvn-opts "--norm-means=true --norm-vars=false" --hid-layers 4 --hid-dim 1024 --learn-rate 0.008 data/fbank/train data/fbank/dev data/lang exp/tri4b_ali exp/tri4b_ali_cv exp/tri4b_dnn 
# Started at Fri Jul 26 21:09:41 CST 2019
#
steps/nnet/train.sh --copy_feats false --cmvn-opts --norm-means=true --norm-vars=false --hid-layers 4 --hid-dim 1024 --learn-rate 0.008 data/fbank/train data/fbank/dev data/lang exp/tri4b_ali exp/tri4b_ali_cv exp/tri4b_dnn

# INFO
steps/nnet/train.sh : Training Neural Network
	 dir       : exp/tri4b_dnn 
	 Train-set : data/fbank/train 10000, exp/tri4b_ali 
	 CV-set    : data/fbank/dev 893 exp/tri4b_ali_cv 

SKIPPING TRAINING... (steps/nnet/train.sh)
nnet already trained : exp/tri4b_dnn/final.nnet (nnet/nnet_iter14_learnrate7.8125e-06_tr1.0350_cv1.3844_final_)
# Accounting: time=0 threads=1
# Ended (code 0) at Fri Jul 26 21:09:41 CST 2019, elapsed time 0 seconds
steps/nnet/align.sh --nj 2 --cmd run.pl data/fbank/train data/lang exp/tri4b_dnn exp/tri4b_dnn_ali
steps/nnet/decode.sh --nj 2 --cmd run.pl --mem 4G --srcdir exp/tri4b_dnn --config conf/decode_dnn.config --acwt 0.1 exp/tri4b/graph_phone data/fbank/test_phone exp/tri4b_dnn/decode_test_phone
steps/nnet/decode.sh --nj 2 --cmd run.pl --mem 4G --srcdir exp/tri4b_dnn --config conf/decode_dnn.config --acwt 0.1 exp/tri4b/graph_word data/fbank/test exp/tri4b_dnn/decode_test_word
steps/nnet/decode.sh: line 112: nndir: unbound variable
steps/nnet/decode.sh: line 112: nndir: unbound variable
steps/nnet/align.sh: line 85: nndir: unbound variable

**Comment by danpovey** [comment]
That's a bug introduced a week or two agao; I just fixed it in #3494

**Comment by WorldHellow** [comment]
Hey I am having the same error. How Can i fix this?

**Comment by danpovey** [comment]
Bug is fixed; you have to do `git pull` to get the fix (and recompile in src/ in case the update introduced incompatibilities between the scripts and the binaries.)
