### ISSUE TITLE
unable to install MKL. kaldi-help is not working

### ISSUE THREAD

**Issue by ip75** [kaldi-asr/kaldi#3500]
kaldi-help
You do not have permission to post to this group.
Return to the group's topic listing.

BUG:

unable to install MKL

[ip@ubuntu][~/dev/kaldi/tools]% extras/install_mkl.sh
extras/install_mkl.sh: Your system is using debian-style package management.
extras/install_mkl.sh: You must be root to install MKL.

Restart this script using the 'sudo' command, as:

  sudo extras/install_mkl.sh -sp debian intel-mkl-64bit-2019.2-057

We recommend adding the '-sp debian' options to skip the MKL and distro
detection, since this has already been done. This minimizes the number of
programs invoked with the root privileges to keep your system safe from
unexpected or erroneous changes. Also, if you are setting the CC environment
variable, sudo might not allow it to propagate to the command that it invokes.

Run the above sudo command now? [Y/n]:
+ exec sudo extras/install_mkl.sh -sp debian intel-mkl-64bit-2019.2-057
+ apt-get update
Get:1 file:/var/cuda-repo-10-1-local-10.1.168-418.67  InRelease
Ign:1 file:/var/cuda-repo-10-1-local-10.1.168-418.67  InRelease
Get:2 file:/var/cuda-repo-10-1-local-10.1.168-418.67  Release [574 B]
Get:2 file:/var/cuda-repo-10-1-local-10.1.168-418.67  Release [574 B]
Get:3 file:/var/cuda-repo-10-1-local-10.1.168-418.67  Release.gpg [833 B]                                                                  
Get:3 file:/var/cuda-repo-10-1-local-10.1.168-418.67  Release.gpg [833 B]                                         
Ign:3 file:/var/cuda-repo-10-1-local-10.1.168-418.67  Release.gpg                                                 
Hit:4 http://us.archive.ubuntu.com/ubuntu disco InRelease                                                                                                      
Hit:5 http://security.ubuntu.com/ubuntu disco-security InRelease                                                                                               
Hit:6 http://archive.canonical.com/ubuntu disco InRelease           
Get:7 http://us.archive.ubuntu.com/ubuntu disco-updates InRelease [97,5 kB]
Get:8 http://us.archive.ubuntu.com/ubuntu disco-backports InRelease [88,8 kB]
Reading package lists... Done        
W: GPG error: file:/var/cuda-repo-10-1-local-10.1.168-418.67  Release: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY F60F4B3D7FA2AF80
E: The repository 'file:/var/cuda-repo-10-1-local-10.1.168-418.67  Release' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
extras/install_mkl.sh: MKL package intel-mkl-64bit-2019.2-057 installation FAILED.

Please open an issue with us at https://github.com/kaldi-asr/kaldi/ if you
believe this is a bug.
[ip@ubuntu][~/dev/kaldi/tools]%

**Comment by danpovey** [comment]
Looks like the issue is that it is dependent on the return status of apt-get update, and if your system is in a slightly messed-up state that may not work.  Try changing 
``` apt-get update &&```
to
``` apt-get update;```
and LMK if it helps

**Comment by ip75** [comment]
you are absolutely right.
i removed cuda developers repo from apt settings and mkl installed successfully.
this is my fault and inattention
