### ISSUE TITLE
Tutorials minor errors

### ISSUE THREAD

**Issue by bhigy** [kaldi-asr/kaldi#351]
I've been going through the tutorials and I noticed some little issues:
- [x] Overview of the distribution - time estimation: in the list of tutorials, the time estimation is 25mn while it's 20 mn in the tutorial.
- [x] Overview of the distribution - the tools/ directory (line 2): there is no install.sh in the directory.
- [x] Overview of the distribution - the src/ directory (4th paragraph): in kaldi.mk, -O0 and -DKALDI_PARANOID options doesn't seem to be activated by default anymore.
- [x] Overview of the distribution - the src/ directory (4th paragraph): most targets are not defined in base/Makefile any more.
- [x] Running the example scripts: link to the paper  "Speech Recognition with Weighted Finite State Transducers" is not working properly. I already proposed a fix for this.

**Comment by danpovey** [comment]
Thanks a lot.  I've merged that patch.  Could you please submit a patch for
the other issues- just guess as best you can, how to fix them?  It's always
hard to get help fixing the tutorial.
Dan

**Comment by bhigy** [comment]
I can try.

**Comment by danpovey** [comment]
closed since resolved.
