### ISSUE TITLE
online2-wav-nnet3-latgen-faster，error：Input feature dimension mismatch: got 40 but network expects 43

### ISSUE THREAD

**Issue by QAQ1551QAQ** [kaldi-asr/kaldi#3511]
![image](https://user-images.githubusercontent.com/50564800/62681347-12c79180-b9ec-11e9-91b4-a52b9b00817c.png)

**Comment by weiwchu** [comment]
seems to me that you train a model with 43 dim features (I think the aishell's mandarin speech contain extra pitch features), but you are using 40 dim mfcc as input

**Comment by QAQ1551QAQ** [comment]
> seems to me that you train a model with 43 dim features (I think the aishell's mandarin speech contain extra pitch features), but you are using 40 dim mfcc as input

So how should I modify my test input?

**Comment by weiwchu** [comment]
ah, it also might because of some issues in iVector

Cao you show the content of you online.conf here?

**Comment by weiwchu** [comment]
I think I met something similar like you, if there is a silence weight factor in the online.conf, I think you might have set it to 0, you can set it to a very small value like 0.00001.

**Comment by danpovey** [comment]
I suspect the issue is that when you called prepare_online_decoding.sh you
forgot to add the flags that relate to pitch features.  You have to specify
the pitch config somehow.  Look at the script's usage message or the script
itself.
