### ISSUE TITLE
Windows 10, Visual Studio 2017 kaldi-cudamatrix build fails. c:\users\spencer\kaldi\src\cudamatrix\cu-matrix.cc(1709): error C2664: 'void kaldi::CuMatrixBase<Real>::Log(const kaldi::CuMatrixBase<Real> &)': cannot convert argument 1 from 'Real' to 'const kaldi::CuMatrixBase<Real> &' 

### ISSUE THREAD

**Issue by spencerkirn** [kaldi-asr/kaldi#3514]
Hello, I am trying to install Kaldi to use PyTorch-Kaldi on my Windows 10 laptop using Microsoft visual studio 2017 and OpenBLAS. I attached the output from the MVS2017 output window here: [Kaldi-CudaMatrix_Error.txt](https://github.com/kaldi-asr/kaldi/files/3490248/Kaldi-CudaMatrix_Error.txt). Seems like everything in the project that is not based on kaldi-cudamatrix.lib is able to build (except obviously those built on portaudio.h). The issue seems to be in cu-matrix.cc on line 1709 where the error: 
`c:\users\spencer\kaldi\src\cudamatrix\cu-matrix.cc(1709): error C2664: 'void kaldi::CuMatrixBase<Real>::Log(const kaldi::CuMatrixBase<Real> &)': cannot convert argument 1 from 'Real' to 'const kaldi::CuMatrixBase<Real> &'` 
is thrown.

Thank you in advance,
Spencer

**Comment by danpovey** [comment]
Please see if #3515  fixes it. Looks like a name lookup problem.  I'm not sure what the C++ standard says about the situation where a class-member function doesn't match but there's a matching function outside the class.  (I suspect VS2017 is wrong, but the fix is easy.)

**Comment by spencerkirn** [comment]
Thank you for your quick response. That seemed to fix most of the issues. I still have 14 failed builds, here is the output from trying to rebuild the kaldi-cudamatrix project:
[Kaldi-CudaMatrix_Error2.txt](https://github.com/kaldi-asr/kaldi/files/3492371/Kaldi-CudaMatrix_Error2.txt) Is this as good as the build is going to get on Windows, or am I still missing something?

**Comment by danpovey** [comment]
You can ignore the failures in online/.
The rest seem to be linking failures.  You may have to grep for the names
of the functions not found and figure out which directory they are in, and
then go through the visual studio project thingies and see if those are
being linked.   And then there is some kind of script we provide that
generates the vcproj files... there might be some issue in that script.
Sorry I dont have time to debug.
Dan

**Comment by spencerkirn** [comment]
I understand, I appreciate your help and should be able to figure it out from here.

Thank you,
Spencer

**Comment by danpovey** [comment]
thanks, please let us know what the fix is, and make a PR if possible.

**Comment by spencerkirn** [comment]
Sorry for the delay, but the errors were in io-funcs-test, kaldi-error-test, kaldi-math-test, batched-wav-nnet3-cuda, and timer-test. I never actually found the errors (I have no C++ experience or Microsoft Visual Studio experience) but I was able to solve the problem by replacing those 5 files with the corresponding files in from the kaldi folder I was originally having issues with.

**Comment by danpovey** [comment]
Thanks!!  Closing the issue even though it's not really resolved, because the fact that things don't work quite right on Windows is a long-running and known problem.
