### ISSUE TITLE
SRILM alternatives?

### ISSUE THREAD

**Issue by Mistobaan** [kaldi-asr/kaldi#3519]
Are there alternatives to the SRILM language model?

What are the requirements to replace it?

**Comment by balakkvj** [comment]
Look at kaldi_lm in kaldi/tools/

**Comment by jtrmal** [comment]
Anything that produces arpa-format LM is ok.
Other options can be pocolm or irstlm and there are others...
Y.

**Comment by ahmetaa** [comment]
kenlm lmplz is decent and fast.
