### ISSUE TITLE
src/configure should be aware of $MKL_ROOT

### ISSUE THREAD

**Issue by iskunk** [kaldi-asr/kaldi#3522]
I am building Kaldi with the Intel MKL in a non-standard location.

Setting `MKL_ROOT` in the environment allows `tools/extras/check_dependencies.sh` to find the library and continue on its way.

However, `src/configure` does not pick up on that variable, and wants me to pass in something like `--mkl-root=$MKL_ROOT`.

This seems redundant, as well as inconsistent. Could the `configure` script pick up on `MKL_ROOT` if `--mkl-root=*` is not specified?

**Comment by kkm000** [comment]
Reworking `configure` is on my laundry list, although it's getting a bit too long, and . But yeah, thanks, this is a sensible thing to do.

Is the variable `MKL_ROOT` recognized by MKL scripts themselves? In `configure` we have this
https://github.com/kaldi-asr/kaldi/blob/2453b615efd3b347036288d110431334ed740661/src/configure#L713-L721

It's spelled `MKLROOT` there. I'm just wondering which is the right spelling.

**Comment by iskunk** [comment]
I couldn't tell you about `MKL_ROOT`, since I am using an MKL install that was put in by a different person. But I would expect that the MKL install script takes a command-line parameter (`--prefix=...`?) rather than an environment variable.

It seems like `MKLROOT` is only used internally (in the configure script, makefiles, etc.) rather than any sort of script interface intended [by the documentation] for the user. In any event, what matters most is that `check_dependencies.sh` and `configure` agree on the name, and respond to the variable being set.

**Comment by danpovey** [comment]
The script removes the '-' from the name when it parses it.  

Modifying the interface of `configure` while keeping it consistent within that script (i.e. applying it to all those variables) would be a bit dangerous and would probably end up being a bit confusing.  So I don't think we'll do that.

**Comment by iskunk** [comment]
@danpovey, would it be preferable for `check_dependencies.sh` to take `MKLROOT` instead of (or in addition to) `MKL_ROOT`?

(Note that this isn't about changing the command-line options of the `configure` script; this is strictly about the environment variable `MKL_ROOT`, which is what `check_dependencies.sh` currently looks for.)

**Comment by danpovey** [comment]
I don't understand why you need check_dependencies.sh to take that other
form.  It seems to me the existing mechanism is adequate and I don't want
to mess with it.
