### ISSUE TITLE
Question:get_egs.sh, Number of utterances is very small. Please check your data.

### ISSUE THREAD

**Issue by CuiDonCai** [kaldi-asr/kaldi#3532]
Hi:
  I have a question about get_egs.sh . I got a wrong that is Number of utterances is very small. Please check your data  in get_egs.sh. Because $(wc -l <$dir/train_subset_uttlist)=0.
the code of produce  $dir/train_subset_uttlist:
```awk '{print $1}' $data/utt2spk | \
   utils/filter_scp.pl --exclude $dir/valid_uttlist | \
   utils/shuffle_list.pl 2>/dev/null | \
   head -$num_utts_subset > $dir/train_subset_uttlist
```
my line number of $dir/valid_uttlist and my line number of $data/utt2spk are equal. why bring about this situation？ I don't  modify any code. this is wrong about data preparation or others?
Thanks for help!

**Comment by danpovey** [comment]
Those scripts won't work right if you run on an extremely tiny amount of data.

**Comment by CuiDonCai** [comment]
Sorry to bother again，I test the code in librispeech with the all data about dev,-{clean, other}, test-{clean-other},train-{clean-100,clean-360,other-500}(not mini-librispeech data). I still get this error. Something wrong happend in during processing?




At 2019-08-25 01:15:22, "Daniel Povey" <notifications@github.com> wrote:


Those scripts won't work right if you run on an extremely tiny amount of data.

**Comment by danpovey** [comment]
Something must have gone wrong earlier.  There should be thousands or tens of thousands of utterances in that data, and I think it only takes 300 utterances for the valid subset, so something doesn't match.

**Comment by CuiDonCai** [comment]
I am sorry not to provide enough information.  the number of the the valid subset is 903009.  And the number is equal number of utt2spk that compute train_subset_uttlist.  So the number of train_subset_uttlist is zero(So error appear).
```
./train_960_cleaned_sp_hires/*
wc -l <utt2uniq =903009; wc -l < wav.scp=843264; wc -l < feats.scp=903009; wc -l < spk2utt =16398; wc -l < reco2dur=843264;  wc -l < spk2gender=16398;  wc -l < utt2dur =903009; wc -l < utt2spk=903009; wc -l segments=903009; wc -l < text=903009;wc -l < utt2num_frames=903009; wc -l < utt2spk =903009;
```
 I check process of generating data , it seems ok.  Couldn't you tell me  where is the most likely problem? I'm a new one.  Thanks for your help.




At 2019-08-26 03:05:32, "Daniel Povey" <notifications@github.com> wrote:


Something must have gone wrong earlier. There should be thousands or tens of thousands of utterances in that data, and I think it only takes 300 utterances for the valid subset, so something doesn't match.

**Comment by CuiDonCai** [comment]
I see.  the valid subset should be only 300 utterances. So my valid subset is wrong!  I read  the get_egs.sh scripts,  utterance number of valid subset  should be 300. my valid subset is created by :
```
if [ -f $data/utt2uniq ]; then
  # Must hold out all augmented versions of the same utterance.
  echo "$0: File $data/utt2uniq exists, so ensuring the hold-out set" \
       "includes all perturbed versions of the same source utterance."
  utils/utt2spk_to_spk2utt.pl $data/utt2uniq 2>/dev/null | \
      utils/shuffle_list.pl 2>/dev/null | \
    awk -v max_utt=$num_utts_subset '{
        for (n=2;n<=NF;n++) print $n;
        printed += NF-1;
        if (printed >= max_utt) nextfile; }' |
    sort > $dir/valid_uttlist
```
and my utt2uniq seem right,  no strange values in it, no an empty one. So at first I thought the script has some problem. I  will delete utt2uniq, and create valid subset by utt2spk. I'll do more tests and check. Thanks! 
utt2uniq:
100-121669-0000-1 100-121669-0000-1
100-121669-0001-1 100-121669-0001-1
...
sp0.9-100-121669-0002-1 100-121669-0002-1
sp0.9-100-121669-0003-1 100-121669-0003-1
...
sp1.1-100-121669-0000-1 100-121669-0000-1
sp1.1-100-121669-0001-1 100-121669-0001-1

**Comment by danpovey** [comment]
I'd prefer if you figure out what went wrong.

**Comment by CuiDonCai** [comment]
yes, I guessed that. You give me answer before I verify it. Actually, I'm also not  familiar with kaldi. Thank you very much!!!
