### ISSUE TITLE
multi corpus Chinese ASR recipe

### ISSUE THREAD

**Issue by naxingyu** [kaldi-asr/kaldi#3533]
There are over 1k hours of free Chinese data on openslr. A new recipe using all the available Chinese free corpus will demonstrate how to:
1. merge and train Chinese models using data from multiple sources
2. merge vocabulary from multiple sources
3. train a general LM and adapt to certain domain.

**Comment by naxingyu** [comment]
I've started a recipe here https://github.com/naxingyu/kaldi/tree/add-multi_cn/egs/multi_cn/s5

**Comment by underdogliu** [comment]
@naxingyu great! So are we gonna:

1. Use all Chinese recipe from openslr? including aishell1+datatang_200h+thchs30+magic data? 

2. Will we use DaCiDian as the main dictionary?

**Comment by wbgxx333** [comment]
great.
