### ISSUE TITLE
Enable tighter control of downloaded dependencies

### ISSUE THREAD

**Issue by iskunk** [kaldi-asr/kaldi#3543]
Hello,

I am using Kaldi in a large organization, with fairly tight rules concerning how third-party software is used, built, etc. The approach that the Kaldi build system uses to handle dependencies like sctk, OpenFST et al. is convenient to help the user get up and running quickly, but in a regulated environment, it's a bit too fast and loose for comfort.

I would like to propose a couple points of new functionality, across the various scripts under `tools/`, to the end of maintaining the convenient behavior currently implemented, while allowing it to be easily switched into a stricter mode more suitable for such an environment:

1. Check whether an environment variable `WGET` is set; if so, then use it, otherwise default its value to `wget`. Not only does this allow using a wget executable not in one's PATH, this allows one to set a value of `false`, effectively nulling the ability of the build system to download anything.

2. Check an environment variable `DOWNLOAD_DIR` (first-draft name); if set, then copy the required source tarball from there instead of downloading same. (This way, the tarballs can be downloaded and vetted in advance of the Kaldi build.)

I have an implementation of this in the current Git tree. [Here is a preliminary patch](https://github.com/kaldi-asr/kaldi/files/3548616/kaldi-dep-dl-revamp.patch.txt), for initial review. (I can prepare a PR if desired, but would need to know how it should be structured, etc.)

There are a few related changes included in the above:
* Various URLs have been updated to the `https://` form where supported;
* Dropped the `--no-check-certificate` option wherever it was not needed (this is an option that you definitely don't want to use unless absolutely necessary);
* Added variables containing package versions, and then replaced various copy-pasted version strings with these, to simplify package version bumps.

**Comment by danpovey** [comment]
That all looks fine to me.  You can go ahead and make a PR.

**Comment by iskunk** [comment]
I'm happy that it's to your liking :-)

I will work on getting a PR together, and hope to have that submitted within a few days.

**Comment by danpovey** [comment]
Resolved in #3573
