### ISSUE TITLE
Broken link in tools/Makefile

### ISSUE THREAD

**Issue by soloice** [kaldi-asr/kaldi#3564]
The [hyperlink](https://github.com/kaldi-asr/kaldi/blob/f3e77b1b6a0f6626e7a8b706b1d61ad029c97db5/tools/Makefile#L131) for `sph2pipe_v2.5.tar.gz` seems to be outdated.

Replacing it with `http://merlin.fit.vutbr.cz/kaldi/sph2pipe_v2.5.tar.gz`works for me.

**Comment by danpovey** [comment]
You could make a PR for that change.  Bear in mind that it's only a backup
location, the primary one is openslr which is rarely down.

**Comment by danpovey** [comment]
closing as not significant enough to track since it's only a backup location, but if you make a PR I will merge.

**Comment by soloice** [comment]
Thanks for your kind reply. 
The original link turns out to work well today, so it should be a temporary technical issue with `sourceforge.net`.
It would be better to leave it as is.
