### ISSUE TITLE
Kaldi on Android (working)

### ISSUE THREAD

**Issue by nanaghartey** [kaldi-asr/kaldi#3571]
[Here is](https://github.com/alphacep/kaldi-android-demo) a successful Android studio build of Kaldi by Nickolay Shmyrev (author of pocketsphinx). Everything works offline, on-device. Can we work on this and merge with kaldi-asr.

**Comment by danpovey** [comment]
That looks great.  We should work out which parts it would make sense to
make part of Kaldi though.
Definitely we wouldn't include the trained models in the repo, it would
make it too bulky.
It might make more sense to just have a link to that repo, and if there are
any changes that need to be made to the Kaldi build process or to Kaldi
code, then make those.

**Comment by nshmyrev** [comment]
Thank you, Dan. It is still work in progress, we'll merge essentials bits for sure.

**Comment by gabriel-TheCode** [comment]
Thanks duuuuude ! That's awesome ! 😭

**Comment by kkm000** [comment]
@nshmyrev, I lost track of this. Before the stale bot kicks in: Is this done, in progress, on hold? Thanks.
