### ISSUE TITLE
why unenrolled user get high plda score?

### ISSUE THREAD

**Issue by xuexuanyu** [kaldi-asr/kaldi#3575]
I just started learning speaker recognition and trained a model based on ivector+plda using kale. But now I have found a few problems that bother me.
as the plda scoring result：
0001 0004_006 -80.47889
0005 0004_006 -68.86308
0003 0004_006 -51.18082
0002 0004_006 1.089066

0004 is an unenrolled user , but it can get high plda score when compare with 0002.
both 0004 and 0002 are female, I think maybe the i-vector contain gender info ? 
but how can I get rid of this influences？It's really bother me .

**Comment by danpovey** [comment]
Maybe they just sound similar?
There will always be speakers that are easy to confuse with each other.
