### ISSUE TITLE
voxforge online_demo  ./run.sh --test-mode live stack error dump

### ISSUE THREAD

**Issue by yuchao86** [kaldi-asr/kaldi#3576]
My computer is MacBook 10.14.6. when I was run  the voxofge online demo ,
it crash dump: 

 ~/Downloads/kaldi-master/egs/voxforge/online_demo 
 online_demo> ./run.sh --test-mode live

  LIVE DEMO MODE - you can use a microphone and say something

  The (bigram) language model used to build the decoding graph was
  estimated on an audio book's text. The text in question is
  "King Solomon's Mines" (http://www.gutenberg.org/ebooks/2166).
  You may want to read some sentences from this book first ...

online-gmm-decode-faster --rt-min=0.5 --rt-max=0.7 --max-active=4000 --beam=12.0 --acoustic-scale=0.0769 online-data/models/tri2b_mmi/model online-data/models/tri2b_mmi/HCLG.fst online-data/models/tri2b_mmi/words.txt 1:2:3:4:5 online-data/models/tri2b_mmi/matrix
ERROR (online-gmm-decode-faster[5.4]:OnlineDecodableDiagGmmScaled():online-decodable.cc:36) Attempt to initialize decodable object with empty input: please check this before the initializer!

[ Stack-Trace: ]
0   online-gmm-decode-faster            0x00000001036152f7 _ZN5kaldiL18KaldiGetStackTraceEv + 71
1   online-gmm-decode-faster            0x0000000103614f80 _ZN5kaldi13MessageLogger13HandleMessageERKNS_18LogMessageEnvelopeEPKc + 976
2   online-gmm-decode-faster            0x0000000103614a94 _ZN5kaldi13MessageLoggerD2Ev + 228
3   online-gmm-decode-faster            0x0000000103615165 _ZN5kaldi13MessageLoggerD1Ev + 21
4   online-gmm-decode-faster            0x00000001033a9c49 _ZN5kaldi28OnlineDecodableDiagGmmScaledC2ERKNS_9AmDiagGmmERKNS_15TransitionModelEfPNS_19OnlineFeatureMatrixE + 393
5   online-gmm-decode-faster            0x00000001033a9ee7 _ZN5kaldi28OnlineDecodableDiagGmmScaledC1ERKNS_9AmDiagGmmERKNS_15TransitionModelEfPNS_19OnlineFeatureMatrixE + 55
6   online-gmm-decode-faster            0x0000000103375199 main + 3881
7   libdyld.dylib                       0x00007fff6e2043d5 start + 1
8   ???                                 0x000000000000000b 0x0 + 11

**Comment by danpovey** [comment]
I don't really maintain that code directly right now, but try commenting out the check that failed and see if it works normally.  Let us know if that fixes the issue.

**Comment by danpovey** [comment]
Sorry, closing this because we don't maintain that audio-capture stuff any more and it may be a platform-specific problem or one specific to you.  But I would merge a fix if you made one.

**Comment by jnoelvictorino** [comment]
Hi,

I have also experienced this issue with the same kind of Mac 10.14.6.
@yuchao86 Did you find any solution to this?

**Comment by yuchao86** [comment]
I rebuild this project ,and run it all ok.

**Comment by jnoelvictorino** [comment]
I tried to rebuild the project again but no luck. May I know which CLT do you have and if you have XCode installed?

**Comment by jnoelvictorino** [comment]
Update: I tried to rebuilt again but this time with XCode 11.2.1. Still not working
<img width="1430" alt="image" src="https://user-images.githubusercontent.com/45357338/68758822-ddb58580-0651-11ea-9a62-12cceeb338ac.png">

**Comment by danpovey** [comment]
As I said above, the online demo involves microphone capture issues and I
don't maintain it.
I wonder whether you even need to be using that.  It is not a good entry
point for Kaldi.

**Comment by jnoelvictorino** [comment]
Thank you. I understand.
I am interested in this because I want to learn how to use trained models in Kaldi with microphone.
I ask question in the Google group.

Thank you.
