### ISSUE TITLE
How to use PLDA score for classification

### ISSUE THREAD

**Issue by rameshkunasi** [kaldi-asr/kaldi#3586]
Hi All,

In Speaker recognition, I am finding log likelihood ratio using ivector-plda-scoring(PLDA). In the paper "Probability Linear Discriminant Analysis" by S.Ioffe, after finding likelihood score(R), If score(R) > π(diff)/π(same) we can say test utterance is belongs to same class. But I don't know how to find π(diff), π(same) values. 
Note: π(diff), π(same) are priors.
Can anyone help me.

Ramesh

**Comment by rameshkunasi** [comment]
Hello Sir,

I want to verify Speaker Verification results with and without PLDA score normalization. I found s-norm code from kaldi help discussion([](https://groups.google.com/d/msg/kaldi-help/6C9zfam2ne4/1KKqzNRoBQAJ)). As per that binary i have to provide 
**adapt-train-ivector-rspecifier** and **adapt-test-ivector-rspecifier** cohort lists. 
How we will know who are the cohort speakers to enrollment & who are the cohort speakers to enrollment?

**Comment by danpovey** [comment]
should be on kaldi-help
