### ISSUE TITLE
Natural gradient initialization speedup

### ISSUE THREAD

**Issue by danpovey** [kaldi-asr/kaldi#359]
@xiaohui-zhang, could you please do this?
I have some changes in this pull request https://github.com/kaldi-asr/kaldi/pull/358
that I have not yet merged, which aim to decrease the startup time of the nnet3 natural gradient code.  I want this back-ported to nnet2.  Hopefully while testing this in nnet2 you may find any issues.
You don't have to do complete runs with this- don't waste GPUs on it- but maybe test a few individual runs.
Dan

**Comment by xiaohui-zhang** [comment]
sure!
