### ISSUE TITLE
Some questions about local/nnet3/xvector/run_xvector.sh 

### ISSUE THREAD

**Issue by xuexuanyu** [kaldi-asr/kaldi#3591]
I am using the recipe in sre16/v2 , but I have some problem now.

I only get accuracy:train/valid[65,99]=(0.773,0.751/0.63,0.64), and I think maybe I have done something wrong.

1、In  local/nnet3/xvector/run_xvector.sh , it's said:

If you're satisfied with the number of archives (e.g., 50-150 archives is reasonable) and with the number of examples per speaker (e.g., 1000-5000 is reasonable) then you can let the script continue to the later stages. Otherwise, try increasing or decreasing the --num-repeats option.  You might need to fiddle with --frames-per-iter. 

I don't quite understand the meaning of this sentence. In my case, I use my own corpus that contain about 600 speakers and 17000 utts. And after stage 3, I inspect the ranges.* , I found I only have 1 archive with 22540 utts. Does this have a bad effect on training?

2、I found in run_xvector.sh, the default num-epochs is only 2, So I change it to 100. But I found the accuracy didn't improve after 6 epochs. The duration of each epochs decrease and finally fixed in 20s after 14 epochs.  Is it normal or I have just made a mistake?
The accuracy.output.report is 
%Iter	duration	train_objective	valid_objective	difference
0	117.0	0	0	0
1	87.0	0.263736	0.235955	-0.027781
2	96.0	0.564103	0.460674	-0.103429
3	86.0	0.703297	0.599251	-0.104046
4	82.0	0.750916	0.670412	-0.080504
5	85.0	0.758242	0.677903	-0.080339
6	87.0	0.794872	0.655431	-0.139441
7	87.0	0.787546	0.662921	-0.124625
8	92.0	0.791209	0.677903	-0.113306
9	83.0	0.783883	0.666667	-0.117216
10	85.0	0.783883	0.666667	-0.117216
11	65.0	0.794872	0.681648	-0.113224
12	80.0	0.772894	0.685393	-0.087501
13	53.0	0.776557	0.666667	-0.10989
14	20.0	0.78022	0.659176	-0.121044
15	20.0	0.791209	0.670412	-0.120797
16	20.0	0.783883	0.659176	-0.124707
……
……
99	20.0	0.750916	0.636704	-0.114212

3、In train.0.1.log , I got:
`LOG (nnet3-train[5.5.473~1-54e9]:PrintStatsForThisPhase():nnet-training.cc:278) Average objective function for 'output' for minibatches 0-9 is -6.45925 over 320 frames.
LOG (nnet3-train[5.5.473~1-54e9]:PrintStatsForThisPhase():nnet-training.cc:278) Average objective function for 'output' for minibatches 10-19 is -6.44498 over 320 frames.
LOG (nnet3-train[5.5.473~1-54e9]:PrintStatsForThisPhase():nnet-training.cc:278) Average objective function for 'output' for minibatches 20-29 is -6.43395 over 320 frames.
……
……

LOG (nnet3-train[5.5.473~1-54e9]:PrintStatsForThisPhase():nnet-training.cc:278) Average objective function for 'output' for minibatches 670-679 is -4.51014 over 320 frames.
LOG (nnet3-train[5.5.473~1-54e9]:PrintStatsForThisPhase():nnet-training.cc:278) Average objective function for 'output' for minibatches 680-689 is -4.49494 over 320 frames.
LOG (nnet3-train[5.5.473~1-54e9]:PrintStatsForThisPhase():nnet-training.cc:278) Average objective function for 'output' for minibatches 690-699 is -4.47389 over 320 frames.`

But in train.1.1.log, I only got:

`LOG (nnet3-train[5.5.473~1-54e9]:PrintStatsForThisPhase():nnet-training.cc:278) Average objective function for 'output' for minibatches 0-9 is -4.20625 over 640 frames.
LOG (nnet3-train[5.5.473~1-54e9]:PrintStatsForThisPhase():nnet-training.cc:278) Average objective function for 'output' for minibatches 10-19 is -4.17903 over 640 frames.
……
……
LOG (nnet3-train[5.5.473~1-54e9]:PrintStatsForThisPhase():nnet-training.cc:278) Average objective function for 'output' for minibatches 300-309 is -2.52515 over 640 frames.
LOG (nnet3-train[5.5.473~1-54e9]:PrintStatsForThisPhase():nnet-training.cc:278) Average objective function for 'output' for minibatches 310-319 is -2.52651 over 640 frames.
LOG (nnet3-train[5.5.473~1-54e9]:PrintStatsForThisPhase():nnet-training.cc:278) Average objective function for 'output' for minibatches 320-329 is -2.51057 over 640 frames.
s.`
It's seem not all minibatches have been used. Does I do something wrong?

I want to know what made it and how to improve the accuracy.

Sorry for my bad skill ...

**Comment by danpovey** [comment]
this kind of question should go to kaldi-help.  (Not sure if someone would answer, but...)
