### ISSUE TITLE
Kaldi future?

### ISSUE THREAD

**Issue by jgbradley1** [kaldi-asr/kaldi#3594]
Have any decisions been made regarding how [recent events](http://www.danielpovey.com/leaving.html) will impact the future of Kaldi? Will development continue or will [licensing](https://github.com/kaldi-asr/kaldi/blob/master/COPYING) be a problem for other research efforts?

**Comment by danpovey** [comment]
It will continue as before with no change in the license.  I am only considering jobs that would allow me to do that.
