### ISSUE TITLE
Issue installing kaldi on ubuntu 18.04

### ISSUE THREAD

**Issue by ppsingh98** [kaldi-asr/kaldi#3595]
Error while installing kaldi: Please help to resolve:

//.homelibs//pplibfstfarscript.so/:anaconda3 /undefinedbin /reference. .to/ lib`/fst::gcc/IsSTListx86_64(-stdconda_cos6:-:linux__cxx11-:gnu:/basic_string7.3.0</char.,. /std.:.:/char_traits.<.char/>.,. /stdx86_64:-:conda_cos6allocator-<linux-gnuchar/>bin />ld:  .const/&.)libs'/
libfstfarscript.so/:home /undefinedpp /referenceanaconda3 /tobin /`.fst.:/:libIsSTList/(gccstd/:x86_64:-__cxx11conda_cos6:-:linuxbasic_string-<gnuchar/,7.3.0 /std.:.:/char_traits.<.char/>.,. /std.:.:/allocatorx86_64<-charconda_cos6>- linux>- gnuconst/&bin)/'ld
:/ home.//pp./libsanaconda3//libfstfarscript.sobin:/ .undefined. /referencelib /gcc/tox86_64 -`conda_cos6fst-:linux:-IsSTTablegnu(/std7.3.0:/:.__cxx11.:/:.basic_string.</char.,. /std.:.:/char_traitsx86_64<-charconda_cos6>-,linux -stdgnu:/:binallocator/<ldchar:>  .>/ .constlibs&/)libfstfarscript.so':
 undefined reference to gnu/7.3.0/../../../collect2: error: ld returned 1 exit status
../x86_64-conda_cos6-linux-gnu/bin/ld: ./.libs/libfstfarscript.so: undefined reference to `fst::IsSTList(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
/home/pp/anaconda3/bin/../lib/gcc/x86_64-conda_cos6-linux-gnu/7.3.0/../../../../x86_64-conda_cos6-linux-gnu/bin/ld: ./.libs/libfstfarscript.so: undefined reference to `fst::IsSTTable(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
collect2: error: ld returned 1 exit status
`fst::IsSTTable(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
collect2: error: ld returned 1 exit status
Makefile:571: recipe for target 'farequal' failed
make[4]: *** [farequal] Error 1
make[4]: *** Waiting for unfinished jobs....
Makefile:567: recipe for target 'farcreate' failed
make[4]: *** [farcreate] Error 1
Makefile:563: recipe for target 'farcompilestrings' failed
make[4]: *** [farcompilestrings] Error 1
make[4]: Leaving directory '/home/pp/anaconda3/PPSingh/nfr/pykaldi-master/tools/kaldi/tools/openfst-1.6.7/src/extensions/far'
Makefile:378: recipe for target 'install-recursive' failed
make[3]: *** [install-recursive] Error 1
make[3]: Leaving directory '/home/pp/anaconda3/PPSingh/nfr/pykaldi-master/tools/kaldi/tools/openfst-1.6.7/src/extensions'
Makefile:358: recipe for target 'install-recursive' failed
make[2]: *** [install-recursive] Error 1
make[2]: Leaving directory '/home/pp/anaconda3/PPSingh/nfr/pykaldi-master/tools/kaldi/tools/openfst-1.6.7/src'
Makefile:414: recipe for target 'install-recursive' failed
make[1]: *** [install-recursive] Error 1
make[1]: Leaving directory '/home/pp/anaconda3/PPSingh/nfr/pykaldi-master/tools/kaldi/tools/openfst-1.6.7'
Makefile:66: recipe for target 'openfst_compiled' failed
make: *** [openfst_compiled] Error 2

**Comment by danpovey** [comment]
It's some error installing OpenFST.  I don't really understand what is going on there.  You should probably post this on the OpenFST forums, but I don't know how long it would take them to respond.  Your environment looks very strange (e.g. all that anaconda stuff).

**Comment by danpovey** [comment]
Also, removing the openfst directories from tools/, removing the --enable-far option from the Makefile there and recompiling may suffice as a workaround.

Closing this issue as I don't think I will be able to help further.
