### ISSUE TITLE
recipe for target 'lattice-lmrescore-kaldi-rnnlm-pruned' failed

### ISSUE THREAD

**Issue by ppsingh98** [kaldi-asr/kaldi#3598]
While installing kaldi on Ubuntu 18.04, following error is encountered ( removed option --enable-far as suggested)
/home/pp/anaconda3/bin/../lib/gcc/x86_64-conda_cos6-linux-gnu/7.3.0/../../../../x86_64-conda_cos6-linux-gnu/bin/ld: ../nnet3/libkaldi-nnet3.so: undefined reference to `kaldi::LatticeFasterDecoderTpl<fst::Fst<fst::ArcTpl<fst::TropicalWeightTpl<float> > >, kaldi::decoder::StdToken>::FinalRelativeCost() const'
/home/pp/anaconda3/bin/../lib/gcc/x86_64-conda_cos6-linux-gnu/7.3.0/../../../../x86_64-conda_cos6-linux-gnu/bin/ld: ../nnet3/libkaldi-nnet3.so: undefined reference to `kaldi::chain::DenominatorGraph::DenominatorGraph(fst::VectorFst<fst::ArcTpl<fst::TropicalWeightTpl<float> >, fst::VectorState<fst::ArcTpl<fst::TropicalWeightTpl<float> >, std::allocator<fst::ArcTpl<fst::TropicalWeightTpl<float> > > > > const&, int)'
collect2: error: ld returned 1 exit status
<builtin>: recipe for target 'lattice-lmrescore-kaldi-rnnlm-pruned' failed
make[1]: *** [lattice-lmrescore-kaldi-rnnlm-pruned] Error 1
make[1]: Leaving directory '/home/pp/anaconda3/PPSingh/nfr/pykaldi-master/tools/kaldi/src/latbin'
Makefile:136: recipe for target 'latbin' failed
make: *** [latbin] Error 2

**Comment by danpovey** [comment]
You should show a bit more output, in general, when reporting these errors, as I can't see the command line that failed.  But I checked the code and Makefiles, and it all looks fine.  I suspect something is seriously weird with your compiler, e.g. you switched between different compiler versions in the middle of compilation.  `make clean` might help.

**Comment by ppsingh98** [comment]
Executed make clean and tried again. Output is as follows:
/home/pp/anaconda3/bin/x86_64-conda_cos6-linux-gnu-c++  -Wl,-rpath=/home/pp/anaconda3/PPSingh/nfr/pykaldi-master/tools/kaldi/tools/openfst-1.6.7/lib -rdynamic -Wl,-O2 -Wl,--sort-common -Wl,--as-needed -Wl,-z,relro -Wl,-z,now -Wl,--disable-new-dtags -Wl,--gc-sections  -Wl,-rpath=/home/pp/anaconda3/PPSingh/nfr/pykaldi-master/tools/kaldi/src/lib  lattice-lmrescore-kaldi-rnnlm-pruned.o   ../rnnlm/libkaldi-rnnlm.so  ../nnet3/libkaldi-nnet3.so  ../cudamatrix/libkaldi-cudamatrix.so  ../lat/libkaldi-lat.so  ../lm/libkaldi-lm.so  ../fstext/libkaldi-fstext.so  ../hmm/libkaldi-hmm.so  ../tree/libkaldi-tree.so  ../util/libkaldi-util.so  ../matrix/libkaldi-matrix.so  ../base/libkaldi-base.so /home/pp/anaconda3/PPSingh/nfr/pykaldi-master/tools/kaldi/tools/openfst-1.6.7/lib/libfst.so -L/home/pp/intel/compilers_and_libraries_2019.5.281/linux/mkl/lib -Wl,-rpath=/home/pp/intel/compilers_and_libraries_2019.5.281/linux/mkl/lib -lmkl_intel_lp64  -lmkl_core  -lmkl_sequential    -ldl -lpthread -lm  -lm -lpthread -ldl  -o lattice-lmrescore-kaldi-rnnlm-pruned
/home/pp/anaconda3/bin/../lib/gcc/x86_64-conda_cos6-linux-gnu/7.3.0/../../../../x86_64-conda_cos6-linux-gnu/bin/ld: warning: libkaldi-chain.so, needed by ../nnet3/libkaldi-nnet3.so, not found (try using -rpath or -rpath-link)
/home/pp/anaconda3/bin/../lib/gcc/x86_64-conda_cos6-linux-gnu/7.3.0/../../../../x86_64-conda_cos6-linux-gnu/bin/ld: warning: libkaldi-decoder.so, needed by ../nnet3/libkaldi-nnet3.so, not found (try using -rpath or -rpath-link)
/home/pp/anaconda3/bin/../lib/gcc/x86_64-conda_cos6-linux-gnu/7.3.0/../../../../x86_64-conda_cos6-linux-gnu/bin/ld: ../nnet3/libkaldi-nnet3.so: undefined reference to `kaldi::LatticeFasterDecoderTpl<fst::Fst<fst::ArcTpl<fst::TropicalWeightTpl<float> > >, kaldi::decoder::StdToken>::AdvanceDecoding(kaldi::DecodableInterface*, int)'
/home/pp/anaconda3/bin/../lib/gcc/x86_64-conda_cos6-linux-gnu/7.3.0/../../../../x86_64-conda_cos6-linux-gnu/bin/ld: ../nnet3/libkaldi-nnet3.so: undefined reference to `kaldi::DecodableMatrixMapped::DecodableMatrixMapped(kaldi::TransitionModel const&, kaldi::MatrixBase<float> const&, int)'
/home/pp/anaconda3/bin/../lib/gcc/x86_64-conda_cos6-linux-gnu/7.3.0/../../../../x86_64-conda_cos6-linux-gnu/bin/ld: ../nnet3/libkaldi-nnet3.so: undefined reference to `kaldi::LatticeFasterDecoderTpl<fst::Fst<fst::ArcTpl<fst::TropicalWeightTpl<float> > >, kaldi::decoder::StdToken>::~LatticeFasterDecoderTpl()'
/home/pp/anaconda3/bin/../lib/gcc/x86_64-conda_cos6-linux-gnu/7.3.0/../../../../x86_64-conda_cos6-linux-gnu/bin/ld: ../nnet3/libkaldi-nnet3.so: undefined reference to `kaldi::LatticeFasterDecoderTpl<fst::Fst<fst::ArcTpl<fst::TropicalWeightTpl<float> > >, kaldi::decoder::StdToken>::InitDecoding()'
/home/pp/anaconda3/bin/../lib/gcc/x86_64-conda_cos6-linux-gnu/7.3.0/../../../../x86_64-conda_cos6-linux-gnu/bin/ld: ../nnet3/libkaldi-nnet3.so: undefined reference to `kaldi::chain::Supervision::Read(std::istream&, bool)'
/home/pp/anaconda3/bin/../lib/gcc/x86_64-conda_cos6-linux-gnu/7.3.0/../../../../x86_64-conda_cos6-linux-gnu/bin/ld: ../nnet3/libkaldi-nnet3.so: undefined reference to `kaldi::LatticeFasterDecoderTpl<fst::Fst<fst::ArcTpl<fst::TropicalWeightTpl<float> > >, kaldi::decoder::StdToken>::LatticeFasterDecoderTpl(fst::Fst<fst::ArcTpl<fst::TropicalWeightTpl<float> > > const&, kaldi::LatticeFasterDecoderConfig const&)'
/home/pp/anaconda3/bin/../lib/gcc/x86_64-conda_cos6-linux-gnu/7.3.0/../../../../x86_64-conda_cos6-linux-gnu/bin/ld: ../nnet3/libkaldi-nnet3.so: undefined reference to `kaldi::chain::ComputeChainObjfAndDeriv(kaldi::chain::ChainTrainingOptions const&, kaldi::chain::DenominatorGraph const&, kaldi::chain::Supervision const&, kaldi::CuMatrixBase<float> const&, float*, float*, float*, kaldi::CuMatrixBase<float>*, kaldi::CuMatrix<float>*)'
/home/pp/anaconda3/bin/../lib/gcc/x86_64-conda_cos6-linux-gnu/7.3.0/../../../../x86_64-conda_cos6-linux-gnu/bin/ld: ../nnet3/libkaldi-nnet3.so: undefined reference to `kaldi::chain::Supervision::Write(std::ostream&, bool) const'
/home/pp/anaconda3/bin/../lib/gcc/x86_64-conda_cos6-linux-gnu/7.3.0/../../../../x86_64-conda_cos6-linux-gnu/bin/ld: ../nnet3/libkaldi-nnet3.so: undefined reference to `kaldi::chain::MergeSupervision(std::vector<kaldi::chain::Supervision const*, std::allocator<kaldi::chain::Supervision const*> > const&, kaldi::chain::Supervision*)'
/home/pp/anaconda3/bin/../lib/gcc/x86_64-conda_cos6-linux-gnu/7.3.0/../../../../x86_64-conda_cos6-linux-gnu/bin/ld: ../nnet3/libkaldi-nnet3.so: undefined reference to `kaldi::DecodableMatrixMapped::~DecodableMatrixMapped()'
/home/pp/anaconda3/bin/../lib/gcc/x86_64-conda_cos6-linux-gnu/7.3.0/../../../../x86_64-conda_cos6-linux-gnu/bin/ld: ../nnet3/libkaldi-nnet3.so: undefined reference to `kaldi::chain::Supervision::Swap(kaldi::chain::Supervision*)'
/home/pp/anaconda3/bin/../lib/gcc/x86_64-conda_cos6-linux-gnu/7.3.0/../../../../x86_64-conda_cos6-linux-gnu/bin/ld: ../nnet3/libkaldi-nnet3.so: undefined reference to `kaldi::chain::Supervision::Supervision(kaldi::chain::Supervision const&)'
/home/pp/anaconda3/bin/../lib/gcc/x86_64-conda_cos6-linux-gnu/7.3.0/../../../../x86_64-conda_cos6-linux-gnu/bin/ld: ../nnet3/libkaldi-nnet3.so: undefined reference to `kaldi::chain::Supervision::operator==(kaldi::chain::Supervision const&) const'
/home/pp/anaconda3/bin/../lib/gcc/x86_64-conda_cos6-linux-gnu/7.3.0/../../../../x86_64-conda_cos6-linux-gnu/bin/ld: ../nnet3/libkaldi-nnet3.so: undefined reference to `kaldi::LatticeFasterDecoderTpl<fst::Fst<fst::ArcTpl<fst::TropicalWeightTpl<float> > >, kaldi::decoder::StdToken>::GetRawLattice(fst::VectorFst<fst::ArcTpl<fst::LatticeWeightTpl<float> >, fst::VectorState<fst::ArcTpl<fst::LatticeWeightTpl<float> >, std::allocator<fst::ArcTpl<fst::LatticeWeightTpl<float> > > > >*, bool) const'
/home/pp/anaconda3/bin/../lib/gcc/x86_64-conda_cos6-linux-gnu/7.3.0/../../../../x86_64-conda_cos6-linux-gnu/bin/ld: ../nnet3/libkaldi-nnet3.so: undefined reference to `kaldi::LatticeFasterDecoderTpl<fst::Fst<fst::ArcTpl<fst::TropicalWeightTpl<float> > >, kaldi::decoder::StdToken>::FinalRelativeCost() const'
/home/pp/anaconda3/bin/../lib/gcc/x86_64-conda_cos6-linux-gnu/7.3.0/../../../../x86_64-conda_cos6-linux-gnu/bin/ld: ../nnet3/libkaldi-nnet3.so: undefined reference to `kaldi::chain::DenominatorGraph::DenominatorGraph(fst::VectorFst<fst::ArcTpl<fst::TropicalWeightTpl<float> >, fst::VectorState<fst::ArcTpl<fst::TropicalWeightTpl<float> >, std::allocator<fst::ArcTpl<fst::TropicalWeightTpl<float> > > > > const&, int)'
/home/pp/anaconda3/bin/../lib/gcc/x86_64-conda_cos6-linux-gnu/7.3.0/../../../../x86_64-conda_cos6-linux-gnu/bin/ld: warning: libkaldi-chain.so, needed by ../nnet3/libkaldi-nnet3.so, not found (try using -rpath or -rpath-link)
/home/pp/anaconda3/bin/../lib/gcc/x86_64-conda_cos6-linux-gnu/7.3.0/../../../../x86_64-conda_cos6-linux-gnu/bin/ld: warning: libkaldi-decoder.so, needed by ../nnet3/libkaldi-nnet3.so, not found (try using -rpath or -rpath-link)
/home/pp/anaconda3/bin/../lib/gcc/x86_64-conda_cos6-linux-gnu/7.3.0/../../../../x86_64-conda_cos6-linux-gnu/bin/ld: ../nnet3/libkaldi-nnet3.so: undefined reference to `kaldi::LatticeFasterDecoderTpl<fst::Fst<fst::ArcTpl<fst::TropicalWeightTpl<float> > >, kaldi::decoder::StdToken>::AdvanceDecoding(kaldi::DecodableInterface*, int)'
/home/pp/anaconda3/bin/../lib/gcc/x86_64-conda_cos6-linux-gnu/7.3.0/../../../../x86_64-conda_cos6-linux-gnu/bin/ld: ../nnet3/libkaldi-nnet3.so: undefined reference to `kaldi::DecodableMatrixMapped::DecodableMatrixMapped(kaldi::TransitionModel const&, kaldi::MatrixBase<float> const&, int)'
/home/pp/anaconda3/bin/../lib/gcc/x86_64-conda_cos6-linux-gnu/7.3.0/../../../../x86_64-conda_cos6-linux-gnu/bin/ld: ../nnet3/libkaldi-nnet3.so: undefined reference to `kaldi::LatticeFasterDecoderTpl<fst::Fst<fst::ArcTpl<fst::TropicalWeightTpl<float> > >, kaldi::decoder::StdToken>::~LatticeFasterDecoderTpl()'
/home/pp/anaconda3/bin/../lib/gcc/x86_64-conda_cos6-linux-gnu/7.3.0/../../../../x86_64-conda_cos6-linux-gnu/bin/ld: ../nnet3/libkaldi-nnet3.so: undefined reference to `kaldi::LatticeFasterDecoderTpl<fst::Fst<fst::ArcTpl<fst::TropicalWeightTpl<float> > >, kaldi::decoder::StdToken>::InitDecoding()'
/home/pp/anaconda3/bin/../lib/gcc/x86_64-conda_cos6-linux-gnu/7.3.0/../../../../x86_64-conda_cos6-linux-gnu/bin/ld: ../nnet3/libkaldi-nnet3.so: undefined reference to `kaldi::chain::Supervision::Read(std::istream&, bool)'
/home/pp/anaconda3/bin/../lib/gcc/x86_64-conda_cos6-linux-gnu/7.3.0/../../../../x86_64-conda_cos6-linux-gnu/bin/ld: ../nnet3/libkaldi-nnet3.so: undefined reference to `kaldi::LatticeFasterDecoderTpl<fst::Fst<fst::ArcTpl<fst::TropicalWeightTpl<float> > >, kaldi::decoder::StdToken>::LatticeFasterDecoderTpl(fst::Fst<fst::ArcTpl<fst::TropicalWeightTpl<float> > > const&, kaldi::LatticeFasterDecoderConfig const&)'
/home/pp/anaconda3/bin/../lib/gcc/x86_64-conda_cos6-linux-gnu/7.3.0/../../../../x86_64-conda_cos6-linux-gnu/bin/ld: ../nnet3/libkaldi-nnet3.so: undefined reference to `kaldi::chain::ComputeChainObjfAndDeriv(kaldi::chain::ChainTrainingOptions const&, kaldi::chain::DenominatorGraph const&, kaldi::chain::Supervision const&, kaldi::CuMatrixBase<float> const&, float*, float*, float*, kaldi::CuMatrixBase<float>*, kaldi::CuMatrix<float>*)'
/home/pp/anaconda3/bin/../lib/gcc/x86_64-conda_cos6-linux-gnu/7.3.0/../../../../x86_64-conda_cos6-linux-gnu/bin/ld: ../nnet3/libkaldi-nnet3.so: undefined reference to `kaldi::chain::Supervision::Write(std::ostream&, bool) const'
/home/pp/anaconda3/bin/../lib/gcc/x86_64-conda_cos6-linux-gnu/7.3.0/../../../../x86_64-conda_cos6-linux-gnu/bin/ld: ../nnet3/libkaldi-nnet3.so: undefined reference to `kaldi::chain::MergeSupervision(std::vector<kaldi::chain::Supervision const*, std::allocator<kaldi::chain::Supervision const*> > const&, kaldi::chain::Supervision*)'
/home/pp/anaconda3/bin/../lib/gcc/x86_64-conda_cos6-linux-gnu/7.3.0/../../../../x86_64-conda_cos6-linux-gnu/bin/ld: ../nnet3/libkaldi-nnet3.so: undefined reference to `kaldi::DecodableMatrixMapped::~DecodableMatrixMapped()'
/home/pp/anaconda3/bin/../lib/gcc/x86_64-conda_cos6-linux-gnu/7.3.0/../../../../x86_64-conda_cos6-linux-gnu/bin/ld: ../nnet3/libkaldi-nnet3.so: undefined reference to `kaldi::chain::Supervision::Swap(kaldi::chain::Supervision*)'
/home/pp/anaconda3/bin/../lib/gcc/x86_64-conda_cos6-linux-gnu/7.3.0/../../../../x86_64-conda_cos6-linux-gnu/bin/ld: ../nnet3/libkaldi-nnet3.so: undefined reference to `kaldi::chain::Supervision::Supervision(kaldi::chain::Supervision const&)'
/home/pp/anaconda3/bin/../lib/gcc/x86_64-conda_cos6-linux-gnu/7.3.0/../../../../x86_64-conda_cos6-linux-gnu/bin/ld: ../nnet3/libkaldi-nnet3.so: undefined reference to `kaldi::chain::Supervision::operator==(kaldi::chain::Supervision const&) const'
/home/pp/anaconda3/bin/../lib/gcc/x86_64-conda_cos6-linux-gnu/7.3.0/../../../../x86_64-conda_cos6-linux-gnu/bin/ld: ../nnet3/libkaldi-nnet3.so: undefined reference to `kaldi::LatticeFasterDecoderTpl<fst::Fst<fst::ArcTpl<fst::TropicalWeightTpl<float> > >, kaldi::decoder::StdToken>::GetRawLattice(fst::VectorFst<fst::ArcTpl<fst::LatticeWeightTpl<float> >, fst::VectorState<fst::ArcTpl<fst::LatticeWeightTpl<float> >, std::allocator<fst::ArcTpl<fst::LatticeWeightTpl<float> > > > >*, bool) const'
/home/pp/anaconda3/bin/../lib/gcc/x86_64-conda_cos6-linux-gnu/7.3.0/../../../../x86_64-conda_cos6-linux-gnu/bin/ld: ../nnet3/libkaldi-nnet3.so: undefined reference to `kaldi::LatticeFasterDecoderTpl<fst::Fst<fst::ArcTpl<fst::TropicalWeightTpl<float> > >, kaldi::decoder::StdToken>::FinalRelativeCost() const'
/home/pp/anaconda3/bin/../lib/gcc/x86_64-conda_cos6-linux-gnu/7.3.0/../../../../x86_64-conda_cos6-linux-gnu/bin/ld: ../nnet3/libkaldi-nnet3.so: undefined reference to `kaldi::chain::DenominatorGraph::DenominatorGraph(fst::VectorFst<fst::ArcTpl<fst::TropicalWeightTpl<float> >, fst::VectorState<fst::ArcTpl<fst::TropicalWeightTpl<float> >, std::allocator<fst::ArcTpl<fst::TropicalWeightTpl<float> > > > > const&, int)'
collect2: error: ld returned 1 exit status
collect2: error: ld returned 1 exit status
<builtin>: recipe for target 'lattice-lmrescore-kaldi-rnnlm' failed
make[1]: *** [lattice-lmrescore-kaldi-rnnlm] Error 1
make[1]: *** Waiting for unfinished jobs....
<builtin>: recipe for target 'lattice-lmrescore-kaldi-rnnlm-pruned' failed
make[1]: *** [lattice-lmrescore-kaldi-rnnlm-pruned] Error 1
make[1]: Leaving directory '/home/pp/anaconda3/PPSingh/nfr/pykaldi-master/tools/kaldi/src/latbin'
Makefile:136: recipe for target 'latbin' failed
make: *** [latbin] Error 2

**Comment by danpovey** [comment]
You never told me before that you were trying to compile PyKaldi.
I don't know... that compilation setup may be a little different from
normal.  It seems like it's not compiling all the libraries that nnet3
depends on (e.g. decoder, chain), or it can't find them.

**Comment by ppsingh98** [comment]
Thanks for all the guidance. I have not compiled pykaldi yet. Will do it after installation of kaldi.  Where can i  set -rpath or -rpath-link as suggested in the error and warning messages.

**Comment by danpovey** [comment]
PyKaldi uses a different version of Kaldi that has been modified somehow.
I suspect you are not using Kaldi master;
