### ISSUE TITLE
use specaugment by kaldi

### ISSUE THREAD

**Issue by Lomax314** [kaldi-asr/kaldi#3599]
Hi,
I would like to know how to implement specaugment(https://arxiv.org/pdf/1904.08779.pdf) on kaldi. Do you know how to implement it?
By the way, do you think that mfcc features are better than fbank features when implementing automatic speech recognition?
Thank you.

**Comment by danpovey** [comment]
sorry, you should look for past discussions of these issues on the mailing lists, of which there are many.

**Comment by Lomax314** [comment]
Ok, thanks your reply!

**Comment by chenfuouc** [comment]
Hi, 

I‘m trying to  implement specaugment method in Kaldi, but a bug raise when enter the decode stage

ERROR (nnet3-latgen-faster[5.4.271~1404-e50bd]:ExpectToken():io-funcs.cc:212) Expected token "</GeneralDropoutComponent>", got instead "<SpecAugmentMaxProportion>"

The model script is similar with the egs/mini_librispeech/s5/local/chain/tuning/run_tdnn_1i.sh and the decode script is the steps/nnet3/decode.sh in master. Can you give some clue about the ERROR? @danpovey

**Comment by danpovey** [comment]
It's because your code is too old; likely you updated your repo but didn't recompile.

**Comment by chenfuouc** [comment]
I compiled my Kaldi code on Aug 18 with the newest master code. I have checked the code, and it's similar with the https://github.com/kaldi-asr/kaldi/pull/3449
I will recompile the newest master code  and retry decode, thanks for your reply
@danpovey

**Comment by mahuichao** [comment]
@chenfuouc did you solve this problem? I am facing the same issue,I have no idea what to do with it.I don't think this is the problem of code verison,I think this is the problem of default net-config setting.

**Comment by danpovey** [comment]
No, I'm sure it's a code version issue.  Do `make depend -j` and `make -j` in src/ to make sure everything is properly compiled.

**Comment by mahuichao** [comment]
@danpovey OK, i will try it , Thanks for replying Dan .
