### ISSUE TITLE
Help to install kaldi in windows

### ISSUE THREAD

**Issue by cibin91** [kaldi-asr/kaldi#360]
hi,
 -> I started installing kaldi in windows with the help of INSTALL(instruction) file in kaldi/windows.
 ->I completed the step 1,2,2(a),2(b),2(c),2(d-1),Skiped the step 2(d-2),2(e)
 ->Then completed the step 3,4(a),4(b-1)
->While running step4(c) ie)runing the following command in terminal(I am using Visual studio 2013)
                     perl generate_solution.pl --vsver vs2013
In the terminal the following lines appears
 INFO: parsing D:/Cibin/windows/kaldi/windows/../src/base/Makefile
INFO: parsing D:/Cibin/windows/kaldi/windows/../src/matrix/Makefile
INFO: parsing D:/Cibin/windows/kaldi/windows/../src/util/Makefile
.
.
.
        Guide me to know
1]Whether the instruction i followed is right or not?
2]What i have to do to carry forward,and install  it successfully?

Regards
Cibin

**Comment by jtrmal** [comment]
1) this isn't a place to ask question (I'm closing it and won't answer any follow up)
2) the best thing would be just to open the generated solution and try to compile and see.
y.

**Comment by elasolova** [comment]
yeah it seems like you are doing a ***** job maintaining the windows branch. Yeah, I guess we should ask questions to our parents, they will probably answer more constructively.
