### ISSUE TITLE
question when using sre16

### ISSUE THREAD

**Issue by panxin801** [kaldi-asr/kaldi#3603]
During sre16， I use my own data it meet the following question, I may need some help.
In file "local/nnet3/xvector/run_xvector.sh" , it has  one line like this "steps/nnet3/train_raw_dnn.py ".
After run this file I have errors like the following lines

stats-pooling-0-10000_input(1, 84, 0) is kNotComputable, dependencies: stats-extraction-0-10000(1, 84, 0)[kNotComputable],
stats-pooling-0-10000_input(1, 85, 0) is kNotComputable, dependencies: stats-extraction-0-10000(1, 85, 0)[kNotComputable],
ERROR (nnet3-compute-prob[5.4.105~1-4fda]:CreateComputation():nnet-compile.cc:59) Not all outputs were computable, cannot create computation.

Someone know what's wrong and how can I fix this ? Thank you for your help.

**Comment by danpovey** [comment]
I suspect you also modified the xconfig somehow.

But if you didn't modify the xconfig, it's possible that that setup
requires some minimum utterance length.  That would likely be configurable
somehow.

**Comment by panxin801** [comment]
I didn't modify the xconfig in fact. So it must be the minium utterance is too short I guess. Thanks Dan

**Comment by danpovey** [comment]
If you showed more output it might be clearer to me.  Not sure which set of
outputs were not computable.
