### ISSUE TITLE
huge egs files for just 17.3 gb of data

### ISSUE THREAD

**Issue by zaowad** [kaldi-asr/kaldi#3605]
steps/nnet2/get_egs.sh keeps generating egs files and goes beyond 70 gb.Then my hdd space becomes 0.Although i am using a dataset of total 17.3 gb and no augmentation.How to get around this problem??? I would be much obliged if u can help me out as soon as possible

**Comment by danpovey** [comment]
It may be to do with acoustic context... that could give you a factor of 3
or so, depending on configuration.
I don't really support nnet2 to inensively right now.  I suggest to use
nnet3 examples, e.g. local/chain/run_tdnn.sh is in various recipes and will
give much better results.
