### ISSUE TITLE
Calculate the mfcc feature, the value is inf

### ISSUE THREAD

**Issue by hawl666** [kaldi-asr/kaldi#3606]

**Comment by danpovey** [comment]
not enough description

**Comment by hawl666** [comment]
My data sampling rate is 200000, nmels parameter has set to 256, calculate mfcc result is inf.
In order to run successfully, I modify the source code kaldi/src/feat/mel-computations.cc,commented  line 123,124, under Linux is OK，but the value is inf under Windows10.
