### ISSUE TITLE
Calculate the mfcc feature, the value is inf 

### ISSUE THREAD

**Issue by hawl666** [kaldi-asr/kaldi#3607]
My data sampling rate is 200000, nmels parameter has set to 256, calculate mfcc result is inf.
In order to run successfully, I modify the source code kaldi/src/feat/mel-computations.cc,commented line 123,124, under Linux is OK，but the value is inf under Windows10.

**Comment by danpovey** [comment]
You set a large number of bins, comment out an assertion that says:
"You may have set --num-mel-bins too large.", 
and then get surprised when it crashes?  Really?
What you are trying to do can't be done.  Set the number of bins smaller.  Or maybe just compute spectrogram features if that's what you want.
