### ISSUE TITLE
vystadial_en online demo is not working

### ISSUE THREAD

**Issue by sumeet559** [kaldi-asr/kaldi#3613]
make gmm-latgen-faster
wget https://vystadial.ms.mff.cuni.cz/download/pykaldi/egs/vystadial/online_demo/data/vystadial-sample-cs.tar.gz -O data/vystadial-sample-cs.tar.gz
tries to download but gives 404.

Also not able to ping vystadial.ms.mff.cuni.cz
Any other options?

**Comment by danpovey** [comment]
I see that in those download scripts there are some commented-out
references to openslr.  If you were to comment the cuni.cz links and
uncomment the openslr ones it should work.  You could check that change in.

**Comment by sumeet559** [comment]
Can't find any openslr link commented in online demo section. Is it somewhere else.

**Comment by danpovey** [comment]
It’s in scripts inside local/.  Do `git grep wget` in that directory or maybe `git grep openslr`.

**Comment by sumeet559** [comment]
That is for training, which is working fine. My training is already done. 
I am looking to run the online_demo part which is not working.

**Comment by danpovey** [comment]
Looking for where in the script it's downloading something is not rocket science, use 'git grep' and the URL it's showing.  Closing the issue.  But please fix if you find what the fix was.
