### ISSUE TITLE
Unable to install MKL

### ISSUE THREAD

**Issue by ucaslyc** [kaldi-asr/kaldi#3617]
The command is: sudo ./extras/install_mkl.sh -sp debian intel-mkl-64bit-2019.2-057

And I get this:
Get:1 https://apt.repos.intel.com all InRelease
Ign https://apt.repos.intel.com all InRelease
Hit http://security.ubuntu.com trusty-security InRelease
Hit http://security.ubuntu.com trusty-security/main Sources
Hit http://security.ubuntu.com trusty-security/restricted Sources
Hit http://security.ubuntu.com trusty-security/universe Sources
Ign https://apt.repos.intel.com all/main amd64 Packages/DiffIndex
Hit http://security.ubuntu.com trusty-security/multiverse Sources
Hit http://security.ubuntu.com trusty-security/main amd64 Packages
Hit http://security.ubuntu.com trusty-security/restricted amd64 Packages
Hit http://security.ubuntu.com trusty-security/universe amd64 Packages
Ign https://apt.repos.intel.com all/main i386 Packages/DiffIndex
Hit http://security.ubuntu.com trusty-security/multiverse amd64 Packages
Hit http://security.ubuntu.com trusty-security/main i386 Packages
Ign http://cn.archive.ubuntu.com trusty InRelease
Ign http://extras.ubuntu.com trusty InRelease
Hit http://extras.ubuntu.com trusty Release.gpg
Hit http://cn.archive.ubuntu.com trusty-updates InRelease
Hit http://security.ubuntu.com trusty-security/restricted i386 Packages
Hit http://extras.ubuntu.com trusty Release
Hit http://cn.archive.ubuntu.com trusty-backports InRelease
Hit http://extras.ubuntu.com trusty/main Sources
Hit http://security.ubuntu.com trusty-security/universe i386 Packages
Hit https://apt.repos.intel.com all/main amd64 Packages
Hit https://apt.repos.intel.com all/main i386 Packages
Hit http://extras.ubuntu.com trusty/main amd64 Packages
Hit http://cn.archive.ubuntu.com trusty Release.gpg
Hit http://extras.ubuntu.com trusty/main i386 Packages
Hit http://security.ubuntu.com trusty-security/multiverse i386 Packages
Hit http://cn.archive.ubuntu.com trusty-updates/main Sources
Hit http://security.ubuntu.com trusty-security/main Translation-en
Hit http://cn.archive.ubuntu.com trusty-updates/restricted Sources
Hit http://cn.archive.ubuntu.com trusty-updates/universe Sources
Hit http://security.ubuntu.com trusty-security/multiverse Translation-en
Ign http://extras.ubuntu.com trusty/main Translation-en
Hit http://cn.archive.ubuntu.com trusty-updates/multiverse Sources
Hit http://security.ubuntu.com trusty-security/restricted Translation-en
Hit http://cn.archive.ubuntu.com trusty-updates/main amd64 Packages
Hit http://security.ubuntu.com trusty-security/universe Translation-en
Hit http://cn.archive.ubuntu.com trusty-updates/restricted amd64 Packages
Hit http://cn.archive.ubuntu.com trusty-updates/universe amd64 Packages
Hit http://cn.archive.ubuntu.com trusty-updates/multiverse amd64 Packages
Hit http://cn.archive.ubuntu.com trusty-updates/main i386 Packages
Hit http://cn.archive.ubuntu.com trusty-updates/restricted i386 Packages
Hit http://cn.archive.ubuntu.com trusty-updates/universe i386 Packages
Hit http://cn.archive.ubuntu.com trusty-updates/multiverse i386 Packages
Hit http://cn.archive.ubuntu.com trusty-updates/main Translation-en
Hit http://cn.archive.ubuntu.com trusty-updates/multiverse Translation-en
Hit http://cn.archive.ubuntu.com trusty-updates/restricted Translation-en
Ign https://apt.repos.intel.com all/main Translation-en
Hit http://cn.archive.ubuntu.com trusty-updates/universe Translation-en
Hit http://cn.archive.ubuntu.com trusty-backports/main Sources
Hit http://cn.archive.ubuntu.com trusty-backports/restricted Sources
Hit http://cn.archive.ubuntu.com trusty-backports/universe Sources
Hit http://cn.archive.ubuntu.com trusty-backports/multiverse Sources
Hit http://cn.archive.ubuntu.com trusty-backports/main amd64 Packages
Hit http://cn.archive.ubuntu.com trusty-backports/restricted amd64 Packages
Hit http://cn.archive.ubuntu.com trusty-backports/universe amd64 Packages
Hit http://cn.archive.ubuntu.com trusty-backports/multiverse amd64 Packages
Hit http://cn.archive.ubuntu.com trusty-backports/main i386 Packages
Hit http://cn.archive.ubuntu.com trusty-backports/restricted i386 Packages
Hit http://cn.archive.ubuntu.com trusty-backports/universe i386 Packages
Hit http://cn.archive.ubuntu.com trusty-backports/multiverse i386 Packages
Hit http://cn.archive.ubuntu.com trusty-backports/main Translation-en
Hit http://cn.archive.ubuntu.com trusty-backports/multiverse Translation-en
Hit http://cn.archive.ubuntu.com trusty-backports/restricted Translation-en
Hit http://cn.archive.ubuntu.com trusty-backports/universe Translation-en
Hit http://cn.archive.ubuntu.com trusty Release
Hit http://cn.archive.ubuntu.com trusty/main Sources
Hit http://cn.archive.ubuntu.com trusty/restricted Sources
Hit http://cn.archive.ubuntu.com trusty/universe Sources
Hit http://cn.archive.ubuntu.com trusty/multiverse Sources
Hit http://cn.archive.ubuntu.com trusty/main amd64 Packages
Hit http://cn.archive.ubuntu.com trusty/restricted amd64 Packages
Hit http://cn.archive.ubuntu.com trusty/universe amd64 Packages
Hit http://cn.archive.ubuntu.com trusty/multiverse amd64 Packages
Hit http://cn.archive.ubuntu.com trusty/main i386 Packages
Hit http://cn.archive.ubuntu.com trusty/restricted i386 Packages
Hit http://cn.archive.ubuntu.com trusty/universe i386 Packages
Hit http://cn.archive.ubuntu.com trusty/multiverse i386 Packages
Hit http://cn.archive.ubuntu.com trusty/main Translation-en
Hit http://cn.archive.ubuntu.com trusty/multiverse Translation-en
Hit http://cn.archive.ubuntu.com trusty/restricted Translation-en
Hit http://cn.archive.ubuntu.com trusty/universe Translation-en
Fetched 4430 B in 34s (127 B/s)
Reading package lists... Done
W: GPG error: https://apt.repos.intel.com all InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 1A8497B11911E097

+ apt-get install -y wget apt-transport-https ca-certificates gnupg
Reading package lists... Done
Building dependency tree
Reading state information... Done
apt-transport-https is already the newest version.
ca-certificates is already the newest version.
gnupg is already the newest version.
wget is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 799 not upgraded.
+ wget -qO- https://apt.repos.intel.com/intel-gpg-keys/GPG-PUB-KEY-INTEL-SW-PRODUCTS-2019.PUB
+ apt-key --keyring /usr/share/keyrings/intel-sw-products.gpg add -
OK
+ echo 'deb [signed-by=/usr/share/keyrings/intel-sw-products.gpg] https://apt.repos.intel.com/mkl all main'
+ ln -s /usr/share/keyrings/intel-sw-products.gpg /etc/apt/trusted.gpg.d/
Get:1 https://apt.repos.intel.com all InRelease
Ign https://apt.repos.intel.com all InRelease
Hit http://security.ubuntu.com trusty-security InRelease
Ign http://cn.archive.ubuntu.com trusty InRelease
Hit http://security.ubuntu.com trusty-security/main Sources
Hit http://cn.archive.ubuntu.com trusty-updates InRelease
Hit http://security.ubuntu.com trusty-security/restricted Sources
Hit http://cn.archive.ubuntu.com trusty-backports InRelease
Hit http://security.ubuntu.com trusty-security/universe Sources
Hit http://cn.archive.ubuntu.com trusty Release.gpg
Hit http://security.ubuntu.com trusty-security/multiverse Sources
Hit http://cn.archive.ubuntu.com trusty-updates/main Sources
Hit http://security.ubuntu.com trusty-security/main amd64 Packages
Ign https://apt.repos.intel.com all/main amd64 Packages/DiffIndex
Hit http://cn.archive.ubuntu.com trusty-updates/restricted Sources
Hit http://security.ubuntu.com trusty-security/restricted amd64 Packages
Hit http://cn.archive.ubuntu.com trusty-updates/universe Sources
Hit http://security.ubuntu.com trusty-security/universe amd64 Packages
Hit http://cn.archive.ubuntu.com trusty-updates/multiverse Sources
Hit http://security.ubuntu.com trusty-security/multiverse amd64 Packages
Hit http://cn.archive.ubuntu.com trusty-updates/main amd64 Packages
Ign http://extras.ubuntu.com trusty InRelease
Hit http://security.ubuntu.com trusty-security/main i386 Packages
Hit http://extras.ubuntu.com trusty Release.gpg
Ign https://apt.repos.intel.com all/main i386 Packages/DiffIndex
Hit http://cn.archive.ubuntu.com trusty-updates/restricted amd64 Packages
Hit http://security.ubuntu.com trusty-security/restricted i386 Packages
Hit http://extras.ubuntu.com trusty Release
Hit http://cn.archive.ubuntu.com trusty-updates/universe amd64 Packages
Hit http://security.ubuntu.com trusty-security/universe i386 Packages
Hit http://extras.ubuntu.com trusty/main Sources
Hit http://extras.ubuntu.com trusty/main amd64 Packages
Hit http://security.ubuntu.com trusty-security/multiverse i386 Packages
Hit http://cn.archive.ubuntu.com trusty-updates/multiverse amd64 Packages
Hit http://extras.ubuntu.com trusty/main i386 Packages
Hit http://security.ubuntu.com trusty-security/main Translation-en
Hit http://cn.archive.ubuntu.com trusty-updates/main i386 Packages
Hit http://security.ubuntu.com trusty-security/multiverse Translation-en
Hit http://cn.archive.ubuntu.com trusty-updates/restricted i386 Packages
Hit https://apt.repos.intel.com all/main amd64 Packages
Hit https://apt.repos.intel.com all/main i386 Packages
Hit http://security.ubuntu.com trusty-security/restricted Translation-en
Hit http://cn.archive.ubuntu.com trusty-updates/universe i386 Packages
Ign http://extras.ubuntu.com trusty/main Translation-en
Hit http://security.ubuntu.com trusty-security/universe Translation-en
Hit http://cn.archive.ubuntu.com trusty-updates/multiverse i386 Packages
Hit http://cn.archive.ubuntu.com trusty-updates/main Translation-en
Hit http://cn.archive.ubuntu.com trusty-updates/multiverse Translation-en
Hit http://cn.archive.ubuntu.com trusty-updates/restricted Translation-en
Hit http://cn.archive.ubuntu.com trusty-updates/universe Translation-en
Hit http://cn.archive.ubuntu.com trusty-backports/main Sources
Hit http://cn.archive.ubuntu.com trusty-backports/restricted Sources
Hit http://cn.archive.ubuntu.com trusty-backports/universe Sources
Hit http://cn.archive.ubuntu.com trusty-backports/multiverse Sources
Hit http://cn.archive.ubuntu.com trusty-backports/main amd64 Packages
Hit http://cn.archive.ubuntu.com trusty-backports/restricted amd64 Packages
Hit http://cn.archive.ubuntu.com trusty-backports/universe amd64 Packages
Hit http://cn.archive.ubuntu.com trusty-backports/multiverse amd64 Packages
Hit http://cn.archive.ubuntu.com trusty-backports/main i386 Packages
Hit http://cn.archive.ubuntu.com trusty-backports/restricted i386 Packages
Hit http://cn.archive.ubuntu.com trusty-backports/universe i386 Packages
Ign https://apt.repos.intel.com all/main Translation-en
Hit http://cn.archive.ubuntu.com trusty-backports/multiverse i386 Packages
Hit http://cn.archive.ubuntu.com trusty-backports/main Translation-en
Hit http://cn.archive.ubuntu.com trusty-backports/multiverse Translation-en
Hit http://cn.archive.ubuntu.com trusty-backports/restricted Translation-en
Hit http://cn.archive.ubuntu.com trusty-backports/universe Translation-en
Hit http://cn.archive.ubuntu.com trusty Release
Hit http://cn.archive.ubuntu.com trusty/main Sources
Hit http://cn.archive.ubuntu.com trusty/restricted Sources
Hit http://cn.archive.ubuntu.com trusty/universe Sources
Hit http://cn.archive.ubuntu.com trusty/multiverse Sources
Hit http://cn.archive.ubuntu.com trusty/main amd64 Packages
Hit http://cn.archive.ubuntu.com trusty/restricted amd64 Packages
Hit http://cn.archive.ubuntu.com trusty/universe amd64 Packages
Hit http://cn.archive.ubuntu.com trusty/multiverse amd64 Packages
Hit http://cn.archive.ubuntu.com trusty/main i386 Packages
Hit http://cn.archive.ubuntu.com trusty/restricted i386 Packages
Hit http://cn.archive.ubuntu.com trusty/universe i386 Packages
Hit http://cn.archive.ubuntu.com trusty/multiverse i386 Packages
Hit http://cn.archive.ubuntu.com trusty/main Translation-en
Hit http://cn.archive.ubuntu.com trusty/multiverse Translation-en
Hit http://cn.archive.ubuntu.com trusty/restricted Translation-en
Hit http://cn.archive.ubuntu.com trusty/universe Translation-en
Fetched 4430 B in 28s (155 B/s)
Reading package lists... Done
W: GPG error: https://apt.repos.intel.com all InRelease: The following signatures were invalid: KEYEXPIRED 1569575501
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following extra packages will be installed:
  intel-comp-l-all-vars-19.0.2-187
  intel-comp-nomcu-vars-19.0.2-187
  intel-conda-index-tool-19.0.2-187
  intel-conda-intel-openmp-linux-64-shadow-package-2019
  2-187
  intel-conda-mkl-devel-linux-64-shadow-package-2019.2-
  87
  intel-conda-mkl-include-linux-64-shadow-package-2019.
  -187
  intel-conda-mkl-linux-64-shadow-package-2019.2-187
  intel-conda-mkl-static-linux-64-shadow-package-2019.2
  187
  intel-conda-tbb-linux-64-shadow-package-2019.2-187
  intel-mkl-cluster-2019.2-187
  intel-mkl-cluster-c-2019.2-187
  intel-mkl-cluster-f-2019.2-187
  intel-mkl-cluster-rt-2019.2-187
  intel-mkl-common-2019.2-187
  intel-mkl-common-c-2019.2-187
  intel-mkl-common-c-ps-2019.2-187
  intel-mkl-common-f-2019.2-187
  intel-mkl-common-ps-2019.2-187
  intel-mkl-core-2019.2-187 intel-mkl-core-c-2019.2-187
  intel-mkl-core-f-2019.2-187
  intel-mkl-core-ps-2019.2-187
  intel-mkl-core-rt-2019.2-187 intel-mkl-doc-2019
  intel-mkl-doc-ps-2019 intel-mkl-f95-2019.2-187
  intel-mkl-f95-common-2019.2-187
  intel-mkl-gnu-2019.2-187 intel-mkl-gnu-c-2019.2-187
  intel-mkl-gnu-f-2019.2-187
  intel-mkl-gnu-f-rt-2019.2-187
  intel-mkl-gnu-rt-2019.2-187 intel-mkl-pgi-2019.2-187
  intel-mkl-pgi-c-2019.2-187
  intel-mkl-pgi-rt-2019.2-187 intel-mkl-psxe-2019.2-057
  intel-mkl-tbb-2019.2-187 intel-mkl-tbb-rt-2019.2-187
  intel-openmp-19.0.2-187 intel-psxe-common-2019.2-057
  intel-psxe-common-doc-2019 intel-tbb-libs-2019.2-187
The following NEW packages will be installed:
  intel-comp-l-all-vars-19.0.2-187
  intel-comp-nomcu-vars-19.0.2-187
  intel-conda-index-tool-19.0.2-187
  intel-conda-intel-openmp-linux-64-shadow-package-2019
  2-187
  intel-conda-mkl-devel-linux-64-shadow-package-2019.2-
  87
  intel-conda-mkl-include-linux-64-shadow-package-2019.
  -187
  intel-conda-mkl-linux-64-shadow-package-2019.2-187
  intel-conda-mkl-static-linux-64-shadow-package-2019.2
  187
  intel-conda-tbb-linux-64-shadow-package-2019.2-187
  intel-mkl-64bit-2019.2-057
  intel-mkl-cluster-2019.2-187
  intel-mkl-cluster-c-2019.2-187
  intel-mkl-cluster-f-2019.2-187
  intel-mkl-cluster-rt-2019.2-187
  intel-mkl-common-2019.2-187
  intel-mkl-common-c-2019.2-187
  intel-mkl-common-c-ps-2019.2-187
  intel-mkl-common-f-2019.2-187
  intel-mkl-common-ps-2019.2-187
  intel-mkl-core-2019.2-187 intel-mkl-core-c-2019.2-187
  intel-mkl-core-f-2019.2-187
  intel-mkl-core-ps-2019.2-187
  intel-mkl-core-rt-2019.2-187 intel-mkl-doc-2019
  intel-mkl-doc-ps-2019 intel-mkl-f95-2019.2-187
  intel-mkl-f95-common-2019.2-187
  intel-mkl-gnu-2019.2-187 intel-mkl-gnu-c-2019.2-187
  intel-mkl-gnu-f-2019.2-187
  intel-mkl-gnu-f-rt-2019.2-187
  intel-mkl-gnu-rt-2019.2-187 intel-mkl-pgi-2019.2-187
  intel-mkl-pgi-c-2019.2-187
  intel-mkl-pgi-rt-2019.2-187 intel-mkl-psxe-2019.2-057
  intel-mkl-tbb-2019.2-187 intel-mkl-tbb-rt-2019.2-187
  intel-openmp-19.0.2-187 intel-psxe-common-2019.2-057
  intel-psxe-common-doc-2019 intel-tbb-libs-2019.2-187
0 upgraded, 43 newly installed, 0 to remove and 799 not upgraded.
Need to get 572 MB of archives.
After this operation, 0 B of additional disk space will be used.
WARNING: The following packages cannot be authenticated!
  intel-comp-l-all-vars-19.0.2-187
  intel-comp-nomcu-vars-19.0.2-187
  intel-conda-index-tool-19.0.2-187
  intel-conda-intel-openmp-linux-64-shadow-package-2019
  2-187 intel-tbb-libs-2019.2-187
  intel-conda-tbb-linux-64-shadow-package-2019.2-187
  intel-openmp-19.0.2-187 intel-mkl-doc-2019
  intel-mkl-common-2019.2-187
  intel-mkl-core-rt-2019.2-187
  intel-mkl-core-2019.2-187
  intel-conda-mkl-linux-64-shadow-package-2019.2-187
  intel-conda-mkl-include-linux-64-shadow-package-2019.
  -187
  intel-conda-mkl-devel-linux-64-shadow-package-2019.2-
  87
  intel-conda-mkl-static-linux-64-shadow-package-2019.2
  187 intel-mkl-cluster-rt-2019.2-187
  intel-mkl-cluster-2019.2-187
  intel-mkl-common-c-2019.2-187
  intel-mkl-cluster-c-2019.2-187
  intel-mkl-common-f-2019.2-187
  intel-mkl-cluster-f-2019.2-187
  intel-mkl-common-ps-2019.2-187 intel-mkl-doc-ps-2019
  intel-mkl-common-c-ps-2019.2-187
  intel-mkl-core-c-2019.2-187
  intel-mkl-core-f-2019.2-187
  intel-mkl-core-ps-2019.2-187
  intel-mkl-f95-common-2019.2-187
  intel-mkl-f95-2019.2-187 intel-mkl-gnu-rt-2019.2-187
  intel-mkl-gnu-2019.2-187 intel-mkl-gnu-c-2019.2-187
  intel-mkl-gnu-f-rt-2019.2-187
  intel-mkl-gnu-f-2019.2-187
  intel-mkl-pgi-rt-2019.2-187 intel-mkl-pgi-2019.2-187
  intel-mkl-pgi-c-2019.2-187 intel-mkl-psxe-2019.2-057
  intel-mkl-tbb-rt-2019.2-187 intel-mkl-tbb-2019.2-187
  intel-psxe-common-doc-2019
  intel-psxe-common-2019.2-057
  intel-mkl-64bit-2019.2-057
E: There are problems and -y was used without --force-yes
./extras/install_mkl.sh: MKL package intel-mkl-64bit-2019.2-057 installation FAILED.

Please open an issue with us at https://github.com/kaldi-asr/kaldi/ if you
believe this is a bug.

I have already use apt-get update and still have this error.

**Comment by danpovey** [comment]
Looks like an Intel signature may have expired.  You should probably just issue that apt command from the command line and type "yes" when prompoted.
