### ISSUE TITLE
Invalid Signature preventing install_mkl

### ISSUE THREAD

**Issue by SConsul** [kaldi-asr/kaldi#3618]
After running sudo ./install_mkl.sh -sp debian intel-mkl-64bit-2019.2-057, the following happens:

Hit:1 http://in.archive.ubuntu.com/ubuntu bionic InRelease                                       
Hit:2 http://ppa.launchpad.net/danielrichter2007/grub-customizer/ubuntu bionic InRelease         
Hit:3 http://in.archive.ubuntu.com/ubuntu bionic-updates InRelease                               
Get:4 https://apt.repos.intel.com/mkl all InRelease [4,430 B]                                    
Hit:5 http://archive.ubuntu.com/ubuntu xenial InRelease                                          
Hit:6 http://archive.canonical.com/ubuntu bionic InRelease                                       
Ign:7 http://dl.google.com/linux/chrome/deb stable InRelease                                     
Get:8 http://security.ubuntu.com/ubuntu bionic-security InRelease [88.7 kB]                      
Hit:9 http://dl.google.com/linux/chrome/deb stable Release                                       
Hit:10 http://in.archive.ubuntu.com/ubuntu bionic-backports InRelease                            
Err:4 https://apt.repos.intel.com/mkl all InRelease                                              
  The following signatures were invalid: EXPKEYSIG 1A8497B11911E097 "CN = Intel(R) Software Development Products", O=Intel Corporation
Hit:11 https://download.sublimetext.com apt/stable/ InRelease                       
Err:8 http://security.ubuntu.com/ubuntu bionic-security InRelease                                
  Connection timed out [IP: 91.189.88.31 80]
Reading package lists... Done      
W: GPG error: https://apt.repos.intel.com/mkl all InRelease: The following signatures were invalid: EXPKEYSIG 1A8497B11911E097 "CN = Intel(R) Software Development Products", O=Intel Corporation
E: The repository 'https://apt.repos.intel.com/mkl all InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
./install_mkl.sh: MKL package intel-mkl-64bit-2019.2-057 installation FAILED.

**Comment by danpovey** [comment]
This seems to be a very recent Intel problem, see here
https://software.intel.com/en-us/forums/intel-math-kernel-library/topic/821365
We should follow that thread and see if there is any fix from there; the Intel people haven't responded yet.

**Comment by Chushuhuch** [comment]
Looks like it's fixed. Worked for me today. Had to run install_mkl 2 times for some reason though.

**Comment by danpovey** [comment]
thanks, closing.
