### ISSUE TITLE
 Failure in compute-mfcc-feats while LVTLN (steps/train_lvtln.sh)

### ISSUE THREAD

**Issue by puneetbawa** [kaldi-asr/kaldi#3623]
compute-mfcc-feats --vtln-map=ark:data/train_vtln/spk2warp --utt2spk=ark:data/train_vtln/utt2spk --write-utt2dur=ark,t:exp/make_mfcc/train/utt2dur.7 --verbose=2 --config=conf/mfcc.conf scp,p:exp/make_mfcc/train/wav_train_vtln.7.scp ark:- 

ERROR (compute-mfcc-feats[5.5.433~1452-7637d]:main():compute-mfcc-feats.cc:82) The --utt2spk option is only needed if the --vtln-map option is used.

**Comment by danpovey** [comment]
Resolved in #3624
