### ISSUE TITLE
Github protection rule

### ISSUE THREAD

**Issue by danpovey** [kaldi-asr/kaldi#3625]
A few minutes ago I tried to fix a conflict in #3538 via the github command line.  It gave me a dialog that said 'warning: this will merge to master' and I pressed 'ok'.  It seems to have created a merge commit of some kind-- one that didn't seem to give any changes-- but the PR itself did not show as merged.  A couple minutes later-- at least, I think it was later-- when I merged #3624, I noticed that that commit somehow showed up twice in the commit history.  I was kind of confused as to what had happened, but decided that the best thing was just to undo the damage via a force-push.  

This required me to undo the github 'protection rule' that had prevented me from force-pushing to master, and afterward I tried to reproduce it, but I don't 100% know what was in it, so whoever originally created it, please help!

I suspect this is a kind of github bug that happens when the branch that you are trying to fix a conflict in has the same name as the destination branch of the PR.

**Comment by jtrmal** [comment]
I think we can close it.
