### ISSUE TITLE
I/O and NumPy

### ISSUE THREAD

**Issue by danpovey** [kaldi-asr/kaldi#3626]
This is kind of a big issue.

I want to modify the I/O in kaldi10 to use the NumPy format wherever possible (at least for the binary version; for the text version it would be the way NumPy prints the arrays when you "print" them in Python).  The above is for the core data; but the way of combining into bigger files would still be done using the ark/scp mechanism.

The following
https://github.com/rogersce/cnpy
might be a good place to look for reference.

Bear in mind that the tensor directory does not currently compile.
For the time being the contents of the tensor directory would only be used for I/O.

**Comment by csukuangfj** [comment]
I'll take it.

**Comment by danpovey** [comment]
OK, we should discuss this a bit before you do anything substantial because plans have moved on a little since I wrote this.   Let me think a bit.. will be in touch within the hour.

**Comment by danpovey** [comment]
Actually, OK, you can go ahead.  I think a transition to NumPy matrices would be a good idea.  But bear in mind that this should, at the current time, be separated from the main work of getting PyTorch support, as it's kind of an orthogonal issue and may not land at the same time.  Also we'll need to support reading both these types of matrices and the legacy format.  (Also this won't necessarily come packaged with the other changes in the kaldi10 branch, except maybe a small subset of Tensor for the sake of having an interface available to read arbitrary-dimension arrays).

**Comment by csukuangfj** [comment]
all right, I see.

**Comment by csukuangfj** [comment]
There are **three** versions of numpy format:
- version 1.0
- version 2.0
- version 3.0

Please refer to https://numpy.org/devdocs/reference/generated/numpy.lib.format.html

Which version should we support?

**Comment by danpovey** [comment]
[for the record:  my intention is that we support 2.0 and 3.0; 3.0 is just a very small extension of 2.0, regarding UTF-8 support.]
