### ISSUE TITLE
Error while running extras/install_mkl.sh

### ISSUE THREAD

**Issue by puneetbawa** [kaldi-asr/kaldi#3628]
extras/install_mkl.sh: Your system is using debian-style package management.
+ apt-get update
Hit:1 http://in.archive.ubuntu.com/ubuntu disco InRelease
Get:2 http://in.archive.ubuntu.com/ubuntu disco-updates InRelease [97.5 kB]                                                     
Get:3 https://apt.repos.intel.com/mkl all InRelease [4,430 B]                                                                                                   
Hit:4 http://in.archive.ubuntu.com/ubuntu disco-backports InRelease                                                                 
Ign:5 http://dl.google.com/linux/chrome/deb stable InRelease                                     
Err:3 https://apt.repos.intel.com/mkl all InRelease                        
  The following signatures were invalid: EXPKEYSIG 1A8497B11911E097 "CN = Intel(R) Software Development Products", O=Intel Corporation
Hit:6 http://security.ubuntu.com/ubuntu disco-security InRelease
Hit:7 http://dl.google.com/linux/chrome/deb stable Release
Reading package lists... Done
W: GPG error: https://apt.repos.intel.com/mkl all InRelease: The following signatures were invalid: EXPKEYSIG 1A8497B11911E097 "CN = Intel(R) Software Development Products", O=Intel Corporation
E: The repository 'https://apt.repos.intel.com/mkl all InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
extras/install_mkl.sh: MKL package intel-mkl-64bit-2019.2-057 installation FAILED.

**Comment by puneetbawa** [comment]
![intelmkl_issuekaldi](https://user-images.githubusercontent.com/12969314/65940820-22d97b80-e447-11e9-94bd-bec6a69720a3.png)

**Comment by danpovey** [comment]
There was a signature problem with the Intel package, see #3618.
Try re-running it.  Someone said he was able to fix it that way (thanks to Intel doing something.)

**Comment by puneetbawa** [comment]
Tried the steps as listed on their developers forum. now getting more of them. Kudos to Intel. 
Can someone please brief in the temporal solution for the below attached failure?
![Screenshot from 2019-10-02 20-59-04](https://user-images.githubusercontent.com/12969314/66058612-4cce9300-e558-11e9-922b-57d6cec76752.png)

**Comment by puneetbawa** [comment]
Finally Resolved! Please follow the following steps. 

1) wget https://apt.repos.intel.com/intel-gpg-keys/GPG-PUB-KEY-INTEL-SW-PRODUCTS-2019.PUB
2) apt-key add GPG-PUB-KEY-INTEL-SW-PRODUCTS-2019.PUB
3) sh -c 'echo deb https://apt.repos.intel.com/mkl all main > /etc/apt/sources.list.d/intel-mkl.list'
4) apt-get update
5) apt-get install -f --allow-downgrades --allow-remove-essential --allow-change-held-packages -y intel-mkl-64bit-2019.1-053

**Comment by danpovey** [comment]
Thanks!
Let's see if people have further problems and if we need to change the installation script.

**Comment by terminate9298** [comment]
Is it Important to use Downgraded version of MKL or Newer version can be installed ??
