### ISSUE TITLE
[scripts] The timecode string of vad result is not consistent

### ISSUE THREAD

**Issue by sih4sing5hong5** [kaldi-asr/kaldi#3656]
I ran scripts like `callhome_diarization/v2/diarization/vad_to_segments.sh`, got `segment`
```
tong0000000-ku0000000-0000-0229 tong0000000 0 2.3
tong0000000-ku0000000-0261-0561 tong0000000 2.61 5.61
```
The timecode in filename is `0229`, but for end time is `2.3`

The bug maybe in https://github.com/kaldi-asr/kaldi/blob/master/egs/wsj/s5/utils/segmentation.pl#L356-L366.

**Comment by jtrmal** [comment]
I assume this is resolved.
