### ISSUE TITLE
Adding one line in egs/chime4/s5_1ch/local/rnnlm/tuning/run_lstm_1a.sh

### ISSUE THREAD

**Issue by Peidong-Wang** [kaldi-asr/kaldi#3662]
There is a small typo in egs/chime4/s5_1ch/local/rnnlm/tuning/run_lstm_1a.sh, which can be solved by adding the following code between line 68 and 69:

`rm $text_dir/chime4.txt.tmp`

**Comment by jtrmal** [comment]
Can you please create a PR

**Comment by Peidong-Wang** [comment]
fixed with PR #3794
