### ISSUE TITLE
No binary files generated when i compile kaldi

### ISSUE THREAD

**Issue by AhmedCheikhRouhou** [kaldi-asr/kaldi#3664]
Hello everyone,
Thank you for this great tool.
I used kaldi about 1 year ago and it was working great.

I installed ubuntu 18 for my new computer with GPU. everything goes well but no binaries are generated after running "make -j xxx" and only ***.a files are created. This is the first time i build kaldi with GPU support.

Please can you help me to solve this issue. 

Thanks in advance.

**Comment by jtrmal** [comment]
there would be probably some error shown.
Go to src/ and run 'make' (without any other parameters) and hopefully find
the error
y.

**Comment by AhmedCheikhRouhou** [comment]
There is no errors, everything is builded. Although, the scripts provided are running very well but i need to use the binary files to adapt my previously created scripts.

**Comment by jtrmal** [comment]
In that case I suspect you are looking in the wrong places... Typically,
binaries will be in directories '*bin' and libraries/archives will be
elsewhere...
y.
