### ISSUE TITLE
Kaldi on Windows: error  : The imported project "C:\Users\Momina\kaldi\kaldiwin_vs2017_OPENBLAS\kaldiwin\variables.props" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.

### ISSUE THREAD

**Issue by Momina12** [kaldi-asr/kaldi#3677]
I am compiling kaldi on windows. I have generated solution file by generate_solution.pl script. Now, I am opening that solution file to VS2017 and the following error is encountered:
error  : The imported project "C:\Users\me\kaldi\kaldiwin_vs2017_OPENBLAS\kaldiwin\variables.props" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk. 
variables.props is already in kaldiwin folder. I have tried number of solutions still no luck!
Kindly help me out!

**Comment by danpovey** [comment]
Sorry, I don't think this is something we'd be able to help with from the Kaldi side.  Looks potentially like a local issue, possibly with VS or your file system, or maybe a permission issue.
