### ISSUE TITLE
doubt about `AddWordInsPenToCompactLattice`

### ISSUE THREAD

**Issue by csukuangfj** [kaldi-asr/kaldi#3692]
It is **word** insertion penalty, but the code uses `ilabel`, i.e., tid, instead of `olabel`.
https://github.com/kaldi-asr/kaldi/blob/d649afdc1f4c2ca88820159a438e35efce60dee8/src/lat/lattice-functions.cc#L1194-L1200

If `ilabel` is not 0, it cannot guarantee that there is a word along the arc.

I also found this thread recommending using `olabel`:
https://sourceforge.net/p/kaldi/mailman/message/32073002/
```cpp
for (fst::ArcIterator<fst::Fst<Arc> > aiter(fst_, state);
        !aiter.Done(); aiter.Next()) {
         Arc arc = aiter.Value();
          if (arc.ilabel != 0) {
           Weight ac_weight(- decodable->LogLikelihood(frame, arc.ilabel));
        BaseFloat new_weight = arc.weight.Value() + tok->weight_.Value()
            + ac_weight.Value();

        if (arc.olabel) //Word label so add insertion penalty
          new_weight += insertion penalty;
       ...
       ...
       ...
       ...
```

**Comment by danpovey** [comment]
The CompactLattice format is different, it is an acceptor (ilabel==olabel) and the transition-ids are in the costs (CompactLatticeWeight).
