### ISSUE TITLE
utt2spk_to_spk2utt.pl has syntax error 

### ISSUE THREAD

**Issue by lamudazh** [kaldi-asr/kaldi#3695]
when install example , there is a error  happens, says utt2spk_to_spk2utt.pl  line21 has syntax error 
line21: 'if (@ARGV >1){ '

    for x in test train; do
        for f in text wav.scp utt2spk; do
            sort data/${x}/${f} -o data/${x}/${f}
        done
        sudo bash utils/utt2spk_to_spk2utt.pl data/${x}/utt2spk > data/${x}/spk2utt
data/${x}/spk2utt
    done 
<!
    WARNING: THE KALDI ISSUE TRACKER IS **ONLY** USED FOR KALDI DEVELOPMENT!

    If you have a question about using Kaldi, please use the kald-help discussion group:

    https://groups.google.com/forum/#!forum/kaldi-help

    Instructions for joining are available at: http://kaldi-asr.org/forums.html
-->

**Comment by jtrmal** [comment]
COuld you please reformat? I have problems figure out what is what and what is supposed to be the error.

**Comment by danpovey** [comment]
It's because you are invoking with `sudo bash`, it is a perl script, not a bash script.
You shouldn't be ahving to use sudo.  You will just get ownership mixed up.
