### ISSUE TITLE
some confusion about mle-diag-gmm.cc

### ISSUE THREAD

**Issue by Honei** [kaldi-asr/kaldi#3698]
Hi everyone, 
Recently I read about the training process of UBM, but I have some confusion in the process in kaldi in file mle-diag-gmm.cc, line 325 and 333,
I don't know why `mean.Scale(1.0 / occ);`, but not `mean.Scale(1.0 / occ_sum);`。
when i read the E-M for GMM， the formula is about  `mean.Scale(1.0 / occ_sum);`

**Comment by danpovey** [comment]
occ is the occupation count for that gaussian, occ_sum is for the entire mixture of Gaussians.

**Comment by Honei** [comment]
@danpovey Thanks you. I read kaldi and theory again.
