### ISSUE TITLE
po->opts

### ISSUE THREAD

**Issue by danpovey** [kaldi-asr/kaldi#37]
In parts of the code where type OptionsItf is used, for historical reasons the variable name is typically "po" (for ParseOptions).  I think this is confusing and should be changed.  If someone could find time to do this, that would be helpful.  Do it by script if you want.

**Comment by naxingyu** [comment]
Like "op" for OptionParser, as in Python?

**Comment by danpovey** [comment]
Previously it was "po" as abbrev for the ParseOptions class.  But now an
abstract interface OptionsItf is used, so the variable name "opts" would be
more suitable.
Dan

**Comment by vdp** [comment]
In addition to the dumb PR above(I thought "oh, super easy, let's test how PRs work"), I've tried to use the refactoring capabilities of QtCreator, but changing "op->Register(" to "opts->Register(", breaks the indentation for the help message on the next line, and to be honest editing all these files manually, or writing a script doesn't appeal that much to me at the moment...

**Comment by danpovey** [comment]
I would be OK with a patch that breaks the indentation; we can fix that
gradually as we visit each file.
Dan
