### ISSUE TITLE
ERROR: text file 'data/test/text' contains disallowed UTF-8 whitespace character(s)

### ISSUE THREAD

**Issue by Momina12** [kaldi-asr/kaldi#3702]
Hi,
I am running run.sh script to train my model. At stage steps/make_mfcc.sh, I am getting error:
steps/make_mfcc.sh --cmd run.pl --mem 4G --nj 4 data/test exp/make_mfcc/test /home/sm/kaldi/egs/urdu/s5/urdu/mfcc
utils/validate_text.pl: The line for utterance 101adnan_ali061-20160925-aby-139 contains disallowed Unicode whitespaces
**utils/validate_text.pl: ERROR: text file 'data/test/text' contains disallowed UTF-8 whitespace character(s)**
I used "dos2unix" and iconv to fix this, error is still there. Moreover my file is in UTF-8 format.
I have trained my model with 120 hours of data before, I didn't face this error. Kindly help me out.

**Comment by jtrmal** [comment]
I would do

grep '101adnan_ali061-20160925-aby-139' data/test/text | uconv -f utf-8 -t
utf-8 -x Any-Name  and looked at the output, if there are some suspicious
white space characters, such as unbreakable space, half-width space and
stuff like that.  If you look into utils/validate_text.pl, you might be
even able to figure out exactly what characters the validator does not like.
y.

**Comment by yondu22** [comment]
echo -ne '\xEF\xBB\xBF' > utf8_text
then copy all the content over to utf8_text and then mv utf_text data/test/tex
Sometimes headers of the file cause an issue, it isn't in your case ,but i just put this here for future users

**Comment by YuanzhongZheng** [comment]
cat data/test/text |tr -d '/r'

**Comment by sunotsue** [comment]
the cat command didn't work for me.

**Comment by baixf-xyz** [comment]
sed -i 's/\xe3\x80\x80//g' data/test/text
