### ISSUE TITLE
Kaldi on Windows

### ISSUE THREAD

**Issue by Momina12** [kaldi-asr/kaldi#3704]
I am compiling kaldi on windows. Right now, I am building the solution file generated by generate_solution.pl. I faced a lot of errors but I managed to solve them. Most of the errors were related libraries .i.e. cannot include portaudio.h, in.h, etc etc.  After resolving these errors, out of 634 projects, 624 are building successfully. Now,  I am facing some kind of syntax errors, undeclared identifier, link error and some missing if I am not wrong. They are so many that i cannot write or copy paste each of them, so I'm attaching screenshots of few errors.
KIndly help me out to solve these errors
![link](https://user-images.githubusercontent.com/51845054/68371730-2906fa00-0161-11ea-8865-e0ad6124cb6a.PNG)
![missing](https://user-images.githubusercontent.com/51845054/68371735-2c01ea80-0161-11ea-9629-f3560755e368.PNG)
![syntax_error](https://user-images.githubusercontent.com/51845054/68371733-2ad0bd80-0161-11ea-9ef4-2a851c83660c.PNG)
![undeclared](https://user-images.githubusercontent.com/51845054/68371739-2d331780-0161-11ea-9c0a-09779a9b7624.PNG)
![undefined](https://user-images.githubusercontent.com/51845054/68371742-2efcdb00-0161-11ea-91f3-8078a798f886.PNG)

**Comment by jtrmal** [comment]
Those Pa_* linking errors are to be expected.
The rest of the errors look more like a there was something (error or
unknown type) in our source code and the other errors are just the result
of the compiler struggling to do something reasonable (I have never seen it
do something reasonable) after that "something".
You will have to track it down and find the "original"  error -- it
definitely won't be in the  system header files
y.
