### ISSUE TITLE
RestAPI or Kaldi for windows

### ISSUE THREAD

**Issue by Momina12** [kaldi-asr/kaldi#3712]
Hi
I have built kaldi on windows. Some linking errors in 4 projects are coming but after some discussion, I came to know that these are expected errors. Now, I want to ask that is it possible if I build my trained model (linux) on windows else I have to develop API for it? 
Thanks in advance :)

**Comment by danpovey** [comment]
Not sure what you are asking.  The model would be portable between linux and windows but windows is not suitable for training.

**Comment by Momina12** [comment]
Yeah, I know that windows are not suitable for training that's why I trained model on linux, now I have already trained model. I want it to compile it on windows as well. Is it possible? If yes then how?

**Comment by danpovey** [comment]
There is no such thing as `build` or `compile` a model, it's not a piece of
code.
The same decoder programs, and the same command lines, would work on
windows as they would on Linux.

**Comment by Momina12** [comment]
Ok thanks a lot. I understood :)
