### ISSUE TITLE
utils/split_scp.pl: You are splitting into too many pieces! [reduce $nj]

### ISSUE THREAD

**Issue by weienzhang** [kaldi-asr/kaldi#3716]
今天我在运行timit例子的时候，运行到 MMI + SGMM2 Training & Decoding  ，报错utils/split_scp.pl: You are splitting into too many pieces! [reduce $nj]，想问下怎么可以解决这个问题，是调整nj的个数，是调整run.sh里的nj吗
Today I was running the timit example, when it comes to MMI + SGMM2 Training & Decoding and report 'utils/split_scp.pl: You are splitting into too many pieces! [reduce $nj]' , I want to ask how to solve this problem, it is to adjust the number of nj in run.sh?
![微信图片_20191113102837](https://user-images.githubusercontent.com/24769686/68727822-73282980-0600-11ea-9cff-c18c5e2daf86.png)

**Comment by pyyush** [comment]
I have the exact issue.  
<img width="792" alt="Screen Shot 2019-11-13 at 12 26 31 AM" src="https://user-images.githubusercontent.com/49844424/68735614-464a2700-05ac-11ea-9736-f9a69168712c.png">

**Comment by weienzhang** [comment]
> I have the exact issue.
> <img alt="Screen Shot 2019-11-13 at 12 26 31 AM" width="792" src="https://user-images.githubusercontent.com/49844424/68735614-464a2700-05ac-11ea-9736-f9a69168712c.png">

https://github.com/kaldi-asr/kaldi/issues/2320 
I occasionally saw this issue but don't know exactly what to do, think maybe you can check this out

**Comment by pyyush** [comment]
Did you try #2326 ?

**Comment by weienzhang** [comment]
i checked the 2326 but i didn't know clearly what to do, but i do some change in cmd.sh and run.sh, that error didn't show but now it comes up with this:




&nbsp;

重要邮件

&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Piyush Vyas"<notifications@github.com&gt;; 
发送时间: 2019年11月13日(星期三) 下午2:25
收件人: "kaldi-asr/kaldi"<kaldi@noreply.github.com&gt;; 
抄送: "嘎嘎嘎"<825221251@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [kaldi-asr/kaldi] utils/split_scp.pl: You are splitting into too many pieces! [reduce $nj] (#3716)




Did you try #2326 ?

**Comment by rushabhdharia** [comment]
#2326 is already merged in get_utt2dur.sh in lines 92-95

**Comment by jtrmal** [comment]
I would suggest to reduce the nj to 16 -- timit is a very small corpus
y.

**Comment by pyyush** [comment]
@jtrmal I've 2 NVIDIA V100's and 24 CPU cores in total. What should the best setting be for my case just for timit ?

**Comment by jtrmal** [comment]
Try 16 or skip sgmm training completely.
Y.

**Comment by rushabhdharia** [comment]
@weienzhang change train_nj (from 30 to 15) in line 30 in the file kaldi/egs/timit/s5/run.sh

**Comment by weienzhang** [comment]
> @weienzhang change train_nj (from 30 to 15) in line 30 in the file kaldi/egs/timit/s5/run.sh

ok i changed it and it seems work out , thank you
