### ISSUE TITLE
Some mfcc feature values are -nan

### ISSUE THREAD

**Issue by echochoc** [kaldi-asr/kaldi#3719]
I would like to use Kaldi MFCC feature in my own project and I wrote the following code to do my first try. I compute the MFCC feature of the test.wav file in kaldi-master\src\feat\test_data and output the result in a file.
```
int main(int argc, char** argv)
{
	const char* fileNames = argv[1];
	
	std::ifstream is(fileNames, std::ios_base::binary);
	WaveData wave;
	wave.Read(is);
	KALDI_ASSERT(wave.Data().NumRows() == 1);
	SubVector<BaseFloat> waveform(wave.Data(), 0);
	
	Matrix<BaseFloat> features;
	
	// the parametrization object
	MfccOptions op;
	// trying to have same opts as baseline.
	op.frame_opts.dither = 1.0;
	op.frame_opts.preemph_coeff = 0.0;
	op.frame_opts.window_type = "rectangular";
	op.frame_opts.remove_dc_offset = false;
	op.frame_opts.round_to_power_of_two = true;
	op.mel_opts.low_freq = 0.0;
	op.mel_opts.htk_mode = true;
	op.htk_compat = true;
	
	Mfcc mfcc(op);
	
	// compute mfccs.
	mfcc.Compute(waveform, 1.0, &features);
	std::cout << "== features.NumRows() == " << features.NumRows() << "\n";
	std::cout << "== features.NumCols() == " << features.NumCols() << "\n";
	const char* output_path = "features.txt";
	std::ofstream ofs(output_path, std::ios::out);
	for (int i = 0; i < features.NumRows(); i++)
	{
		for (int j = 0; j < features.NumCols(); j++)
		{
			ofs << features.Data()[i * features.NumCols() + j] << " ";
		}
		ofs << "\n";
	}
	ofs.close();
	
	std::cout << "Compute OK. \n";
	
	return 0;
}
```

Here is the result I got [features.txt](https://github.com/kaldi-asr/kaldi/files/3849486/features.txt)
There are some -nan as value in features.
Can someone help me to find the problem ?

**Comment by echochoc** [comment]
My environment is 
`
$ sudo lsb_release -a
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.6 LTS
Release:	16.04
Codename:	xenial

$ uname -r
4.15.0-69-generic

$ gcc --version
gcc (Ubuntu 5.4.0-6ubuntu1~16.04.12) 5.4.0 20160609
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
`

**Comment by danpovey** [comment]
That's an extremely strange combination of options.
Possibly there is some path by which a NaN can get in there.
But it's not a high priority to fix it, given how unusual your choice of
options is.

**Comment by danpovey** [comment]
closing as wontfix.  sorry.
of course I would merge a fix if you figured it out.

**Comment by echochoc** [comment]
Thank you for your reply. This code was just extracted from kaldi-master\src\feat\feature-mfcc-test.cc.
I think I found the reason why the problem occurs.
In this line
`ofs << features.Data()[i * features.NumCols() + j] << " ";`
instead of using features.NumCols(), I should use features.Stride(), it was my mistake.
