### ISSUE TITLE
Store value of the DecodableNnetSimpleLoopedInfo in DecodableNnetLoopedOnlineBase

### ISSUE THREAD

**Issue by valboldakov** [kaldi-asr/kaldi#3721]
Good afternoon.
 
Recently I started to implement Kaldi based nnet3 online decoder. And I found out that `DecodableNnetLoopedOnlineBase` stores instance of `DecodableNnetSimpleLoopedInfo` as a const reference. You can see it [here](https://github.com/kaldi-asr/kaldi/blob/master/src/nnet3/decodable-online-looped.cc).

Wouldn't it will be better to save it as a value? Because now we need to ensure that instance of `DecodableNnetSimpleLoopedInfo` will outlive `DecodableNnetLoopedOnlineBase` instance.
I tried to find any mention about it in the docs but I wasn't successful.

It may not be a really big problem but it leads us to undefined behavior when we init `DecodableNnetLoopedOnlineBase` from `SingleUtteranceNnet3DecoderTpl` with `DecodableNnetSimpleLoopedInfo` as const reference and `DecodableNnetSimpleLoopedInfo` doesn't outlive `DecodableNnetLoopedOnlineBase`.

As far as I can understand `DecodableNnetSimpleLoopedInfo` can be copied without any changes to the codebase.

If you are positive about this change, I would like to make the PR.

**Comment by danpovey** [comment]
It's actually that way for a good reason-- the design enables multiple recognition threads to share the same static info.

**Comment by valboldakov** [comment]
Thank you for your answer.
