### ISSUE TITLE
How to use tensorflow as acoustic model

### ISSUE THREAD

**Issue by panxin801** [kaldi-asr/kaldi#3722]
I want to use tensorflow as acoustic model, during decode stage. During decode I need to use `nnet3-latgen-faster` and after checking it needs feats, HCLG and final.mdl,  how can I replace final.mdl with tensorflow model, can you give me some advices, or if there is another way? Thanks for your time and help.

**Comment by danpovey** [comment]
It's very non-trivial.  sorry.  can't help.

**Comment by panxin801** [comment]
Thans you for the help dan.
