### ISSUE TITLE
the kws 

### ISSUE THREAD

**Issue by xbsdsongnan** [kaldi-asr/kaldi#3723]
the hitlist may be from a text ?

**Comment by jtrmal** [comment]
question without context and not really clear what the question means -> closing

**Comment by xbsdsongnan** [comment]
the kws from mini_librispeech ,the demo must be a hitlist, however,the hitlist must a text

**Comment by xbsdsongnan** [comment]
can you give me an E-mail,This will help me to contact you and discuss kwswenti with you
