### ISSUE TITLE
Common voices mozilla

### ISSUE THREAD

**Issue by Cyrix126** [kaldi-asr/kaldi#3726]
The Mozilla common voices has evolved since. The tool "commonvoice" in Koldi is outdated.
Since Mozilla add support for multi-language, it would be nice if the script propose which language do we want.

**Comment by danpovey** [comment]
Agreed, but the core Kaldi team doesn't really maintain these kinds of recipes, they are mostly contributions.  Of course if anyone wants to work on it that would be great, but I don't know if it's a big priority.  So closing the issue as it will take space from issues we plan to address.
