### ISSUE TITLE
Bug in callhome_diarization/v2/diarization/VB_reseg.py

### ISSUE THREAD

**Issue by HsunGong** [kaldi-asr/kaldi#3729]
Use this code, the `uttname` is utterance name with `spk+id`, but `uttline` is `spk` in `rttm` file. It always skips and then goes wrong.

Some Debug info:
- when running code like this, we skip all utts with warning above.
```python
if X_voiced.shape[0] == 0:
            print("Warning: {} has no voiced frames in the initialization file".format(utt))
            continue
```
- command option: `python3 diarization/VB_resegmentation.py --max-speakers 10 --max-iters 10 --downsample 25 --alphaQInit 100.0 --sparsityThr 0.001 --epsilon 1e-6 --minDur 1 --loopProb 0.9 --statScale 0.2 --llScale 1.0 --channel 0 --initialize 1 data/callhome/split20/10 exp/VB/rttm/ivector_rttm exp/VB/tmp exp/VB/tmp/dubm.tmp exp/VB/tmp/ie.tmp` in `VB_resegmentation.sh`.
.
Then I track back, I found `init_ref` is set to 0, which is set in function `create_ref`. Then I found some output in https://github.com/kaldi-asr/kaldi/issues/3729#issuecomment-557394869 AT line 60.

**Code Track**:
Init: https://github.com/kaldi-asr/kaldi/blob/0cc71f19a26f95b798b0141f70c16157270115a6/egs/callhome_diarization/v1/diarization/VB_resegmentation.py#L191
<- https://github.com/kaldi-asr/kaldi/blob/0cc71f19a26f95b798b0141f70c16157270115a6/egs/callhome_diarization/v1/diarization/VB_resegmentation.py#L178
<- https://github.com/kaldi-asr/kaldi/blob/0cc71f19a26f95b798b0141f70c16157270115a6/egs/callhome_diarization/v1/diarization/VB_resegmentation.py#L60
with uttname in `utt2spk`, uttnameline in `rttm`

**Comment by danpovey** [comment]
Can you please show the command line you called it with and how it died (the error message)?
@leibny please figure out who wrote this / who could fix it!

**Comment by HsunGong** [comment]
In `data/callhome/spk2utt, utt2spk, utt2xxx`: `spk` is actually **utterance name**, and `utt` is actually **segments from this utterance**. 
And, in `data/callhome/ref.rttm`, line[1] is actually **utterance name** or so called `spk`(means  **utterance name** 
 == `spk`), and Line[7] is real speaker we want to cluster. 
Then, I found the code run like below: in `VB_reseg.py`, it read rttm with the thought: **utterance name** == `utt`, here we see the error.

One idea to fix this? Maybe change `rttm` file with **utterance name** replaced with `utt`

**Comment by danpovey** [comment]
OK but I am asking (a) what is the exact command line you called it with including options, and (b) what error message or stack trace did it die with?  This will be needed for someone to fix it.

**Comment by HsunGong** [comment]
Some Debug info:
```python
if X_voiced.shape[0] == 0:
            print("Warning: {} has no voiced frames in the initialization file".format(utt))
            continue
```
when running code like this, we skip all utts with warning above.

Then I track back, I found `init_ref` is set to 0, which is set in function `create_ref`. Then I found some output in https://github.com/kaldi-asr/kaldi/issues/3729#issuecomment-557394869 AT line 60.

The whole track is shown in https://github.com/kaldi-asr/kaldi/issues/3729#issue-526603681.

**Comment by danpovey** [comment]
@HuangZiliAndy  could you please have a look?

**Comment by HsunGong** [comment]
Because I rerun VB in ivector system, but the script doesn't create MFCC features for `data/callhome`, then I create from `callhome1` and `callhome2`, which causes the problem.
