### ISSUE TITLE
install error

### ISSUE THREAD

**Issue by zxyzqs** [kaldi-asr/kaldi#3730]
root@user-SYS-7049GP-TRT:/media/user/Disk02/lizhe/zhu/kaldi/tools# bash extras/install_mkl.sh 
extras/install_mkl.sh: Your system is using debian-style package management.
+ apt-get update
命中:1 http://cn.archive.ubuntu.com/ubuntu bionic InRelease                                           
命中:2 http://security.ubuntu.com/ubuntu bionic-security InRelease                                                     
命中:3 http://cn.archive.ubuntu.com/ubuntu bionic-updates InRelease                                                    
命中:5 http://cn.archive.ubuntu.com/ubuntu bionic-backports InRelease                                                
获取:4 http://ppa.launchpad.net/linrunner/tlp/ubuntu bionic InRelease [15.4 kB]                                      
错误:4 http://ppa.launchpad.net/linrunner/tlp/ubuntu bionic InRelease
  由于没有公钥，无法验证下列签名： NO_PUBKEY 2B3F92F902D65EFF
正在读取软件包列表... 完成   
W: GPG 错误：http://ppa.launchpad.net/linrunner/tlp/ubuntu bionic InRelease: 由于没有公钥，无法验证下列签名： NO_PUBKEY 2B3F92F902D65EFF
E: 仓库 “http://ppa.launchpad.net/linrunner/tlp/ubuntu bionic InRelease” 没有数字签名。
N: 无法安全地用该源进行更新，所以默认禁用该源。
N: 参见 apt-secure(8) 手册以了解仓库创建和用户配置方面的细节。
extras/install_mkl.sh: MKL package intel-mkl-64bit-2019.2-057 installation FAILED.

Please open an issue with us at https://github.com/kaldi-asr/kaldi/ if you
believe this is a bug.

**Comment by Discovery-ASR** [comment]
具体原因不清楚。我在公司装没有问题，在个人电脑上配环境一直配不上。后来换了清华源的ubuntu1604镜像，源也配的清华源，做晚上已经成功安装intel-mkl了。建议你试一下。tools目录make编译过程中的依赖，还没进行。

**Comment by danpovey** [comment]
It's failing in "apt-get update" which is a very standard thing that many install scripts have.
That indicates some kind of system problem.   You could learn about apt package management or /etc/apt/sources.list to find more about it.
For now you could just try remove the "apt-get update" part of the install_mkl.sh script and see if it works anyway.
Summary: it's a local system problem, not a bug.

**Comment by zxyzqs** [comment]
This problem solved. I recommand this solution, https://software.intel.com/en-us/articles/installing-intel-free-libs-and-python-apt-repo.
