### ISSUE TITLE
Move CheckAndFixConfigs() outside of NnetBatchComputer

### ISSUE THREAD

**Issue by hugovbraun** [kaldi-asr/kaldi#3734]
We currently have a function [CheckAndFixConfigs()](http://kaldi-asr.org/doc/classkaldi_1_1nnet3_1_1NnetBatchComputer.html#aeb4fbab0a662101fff04c90e166ae8e0) in the NnetBatchComputer that makes sure that frames_per_chunk is a multiple of frame_subsampling_factor. However that functionality is useful outside of just the NnetBatchComputer. Would it be acceptable to move it to the [NnetSimpleComputationOptions](http://kaldi-asr.org/doc/structkaldi_1_1nnet3_1_1NnetSimpleComputationOptions.html) ? I can take care of it, just need the green light.

**Comment by danpovey** [comment]
Sure you can move it to NnetSimpleComputationOptions().

**Comment by danpovey** [comment]
I mean NnetSimpleComputationOptions

**Comment by hugovbraun** [comment]
Ok, will do
