### ISSUE TITLE
kaldi-rnnlm exhaust too much memory

### ISSUE THREAD

**Issue by mxer** [kaldi-asr/kaldi#3738]
when I training rnnlm on my own text with kaldi-rnnlm, I find it exhausted almost all 256g memory, my text is about 800M, and vocab is about 500k , is there any way to reduce memory consumption?

**Comment by danpovey** [comment]
If it uses a lot of CPU memory it is probably because your validation set
is too large so the jobs writing compute_prob_*.{train,valid}.log pile up
in memory.
Solution: use a much much smaller validation set, e.g. around 10k words.

**Comment by mxer** [comment]
Thanks for fast reply, Dan! 
I have tried to make validation set smaller and it works! 
By the way, is 10k the upper limit of validation set or it grows with the size of text corpus?

**Comment by danpovey** [comment]
I would stick with around 10k -- or less if the corpus is super tiny.

**Comment by mxer** [comment]
OK! Thank you for your kind reply. Since my problem has been solved, I'll close this issue.
