### ISSUE TITLE
Is there a nnet3 tool works like 'latgen-faster-mapped'

### ISSUE THREAD

**Issue by panxin801** [kaldi-asr/kaldi#3743]
If there is a nnet3 or nnet3-chain tool in  $kaldi_root/src  can work like latgen-faster-mapped, which can use `trans-model-in (fst-in|fsts-rspecifier) loglikes-rspecifier` as part of the input param, especially using ` loglikes-rspecifier`

**Comment by danpovey** [comment]
I don't see why you wouldn't just use latgen-faster-mapped itself?  Because
there would be nothing
specific to nnet3 about what you are doing in that binary.
loglikes-rspecifier can come from nnet3-compute

**Comment by panxin801** [comment]
Yeah I know what you are meaning, and I tried that  it works, but latgen-faster-mapped doest't support frame-subsampling-factor=3 in which works in chain model. Can you give me some advice?

**Comment by danpovey** [comment]
The frame-subsampling-factor would be given to nnet3-compute.  No point
computing things you don't need.

**Comment by panxin801** [comment]
Oh, I get it. You mean in `nnet3-compute` use frame-subsampling-factor=3 and in `latgen-faster-mapped` just use all the frame output from `nnet3-compute` to solve the problem

**Comment by danpovey** [comment]
Yes

**Comment by panxin801** [comment]
Oh that's brilliant. Thank you very much dan.  Thanks
