### ISSUE TITLE
Windows: cannot open file 'fst.lib'

### ISSUE THREAD

**Issue by sebftw** [kaldi-asr/kaldi#3744]
I tried to compile kaldi for windows using the guide [windows/INSTALL.md](https://github.com/roscisz/kaldi-mpi/blob/master/windows/INSTALL.md).
At the last step I ran into the issue: `LINK : fatal error LNK1104: cannot open file 'fst.lib'`.
The problem was that the kaldi solution expected to find this file in `$(OPENFSTLIB)/src/lib/Release`.

![image](https://user-images.githubusercontent.com/5397919/69862900-c99d9500-129b-11ea-9317-1484cb928142.png)

## My solution

Previously, when compiling OpenFST, the output was put in `openfst\build_output\x64\Release`. This folder then contained `bin` and `lib`, with `lib` containing `libfst.lib` and `libfstscript.lib`.
The solution to the LINK errors was to create the folders `src/lib/Release` and then place `libfst.lib` in it and **rename** `libfst.lib` to `fst.lib`. E.g. in my case looking like this:

![image](https://user-images.githubusercontent.com/5397919/69863435-12a21900-129d-11ea-819d-266ca364bdd6.png)

Finally I set the environment variable to point to this: `OPENFSTLIB=C:\Users\Sebastian\Desktop\kaldi\openfst\build_output\x64\src\lib\Release`.

And then it could successfully compile.

I am by no means an experienced developer, simply a student trying to do automatic speech recognition, so maybe all of this is obvious. And I couldn't find any other references to this issue anywhere. I did change the [variables.props](https://github.com/kaldi-asr/kaldi/blob/master/windows/variables.props.dev) and set `OPENFST` and `OPENFSTLIB`. But like you see, `AdditionalLibraryDirectories` (in [openfstwin_*.props](https://github.com/kaldi-asr/kaldi/blob/master/windows/openfstwin_release.props)) points to `$(OPENFSTLIB)\src\lib\Release`, which did not exist anywhere in my case.
I hope if someone runs into the same issue this may help them.

## Short solution
The problem can also be solved by simply setting `OPENFST` and `OPENFSTLIB` to the same value - the folder of openfst - in my case `C:\Users\Sebastian\Desktop\kaldi\openfst,` and then creating the folder `Release` in `openfst\src\lib` and putting `fst.lib` (copied and renamed from libfst.lib) in it.

Maybe I am a special case, and it worked smoothly for most others. Every other step of the guide I had no issues with. Thank you for supporting Windows!
I compiled with VS2017, OpenBLAS, x64, Windows 10.

**Comment by danpovey** [comment]
@cloudhan I think you are familiar with Windows build issues?  More on the cmake side, obviously, but I wonder if you might know?

**Comment by jtrmal** [comment]
It might be something changed in MSVC or simply a bug in our generator...
But you solved it the right way, as far as I can judge.
y.

**Comment by cloudhan** [comment]
I see in step 12,
> No matter what you plan to use, set both the OPENFST* and PTHREADW variables correctly

 this is not cmake based build anyway. Maybe try to rebuild with cmake?

**Comment by erksch** [comment]
I ran into a similar problem. I think you used the solution that comes with the openfst repo. Although you seemed to resolve your problem I would recommend not use it and create the solution with cmake instead, as described in `windows/INSTALL.md`. Then it will have the "intended" folder structure by default and will create the libs with the correct name.

**Comment by karkirowle** [comment]
Yes, same thing here. I couldn't get it to work with @sebftw 's solution, but I'm able to use it with the cmake builded version.

Unfortunately, the current version of openfst doesn't build without modifications as their CMakeFileLists.txt in commit 0bca6e7, which was commited yesterday, does not include the header files for the cc in the same directory. Fortunately, it can be copied from src/include/fst/test, and then it builds without a problem.

**Comment by danpovey** [comment]
@karkirowle which repo is that commit in, and what needs to be copied from where?  Sorry I am not familiar with this part.

**Comment by karkirowle** [comment]
@danpovey I'm talking about, [the windows port openfst repo](https://github.com/kkm000/openfst). 
The related issue in the OpenFST repo is [here](https://github.com/kkm000/openfst/issues/26), perhaps I should also make a comment there. What I did is simply 

`cp src/include/fst/test/* src/test`

in the OpenFST root, because that's the location of the missing header files. I'm actually not absolutely sure on second look if it's a recent commit that's causing the problem. My guess is that /src/include/fst/test should be included during the build, but it is not, throwing the error. I'm not skilful enough in cmake to find the source of the problem now. But this is just a related OpenFST issue.

For this issue, I would suggest that Line 38 is removed in [INSTALL.md](https://github.com/kaldi-asr/kaldi/blob/master/windows/INSTALL.md), so that cmake becomes the only recommended build path for OpenFST. The source of this problem is the discrepancy in the generated folder structure.

**Comment by cloudhan** [comment]
maybe have a try with [cmake/INSTALL.md](https://github.com/kaldi-asr/kaldi/blob/master/cmake/INSTALL.md)

**Comment by maximeduvey** [comment]
Hello everyone ! I have the clean way to do it, and it's easy.
Ok so, in Visual Studio when you have multiple project with the same dependencies (with path) you generaly use props (files ending with .props) that will define path and lib to load.

In the Kaldiwin folder, you will have these props at the same level as the other libs, so everyone can access it easily :
![2022-07-20 19_15_24-kaldiwin](https://user-images.githubusercontent.com/19221086/180043175-0bce990d-607f-4422-93fe-bfb80e9cc839.png)

As you can see, there is a openfst file for each configuration, in these you can specify the path accordling to your environment, and even change the name of the library 👍
![openfst](https://user-images.githubusercontent.com/19221086/180043629-80651748-f5dd-4fec-85c5-e37885621058.png)

And if you, somehow, failed to specify correctly the main path, you can see there is a variables.props wich contain all the main path :)

Pro tip : you can modify these file without having to reload the project, they are loaded when you try to compil in VS.

Hope i've been helpful
