### ISSUE TITLE
Bad word  at ./../../../tools/kaldi_lm/get_word_map.pl line 43, <> line 4.

### ISSUE THREAD

**Issue by AhmadFoda** [kaldi-asr/kaldi#3753]
in egs/mgb2_arabic/s5 after downloading the data into DB directory and start run.sh I found this error (Bad word  at ./../../../tools/kaldi_lm/get_word_map.pl line 43, <> line 4.)

**Comment by danpovey** [comment]
Likely the input to that scsript is empty for some reason, you'll have to figure out what went wrong earlier.  Closing issue for now as there is not enough to go on.

**Comment by AhmadFoda** [comment]
input to this script is data/local/word_map and its content is :
 A
 B
C
10 D
20 E

**Comment by AhmadFoda** [comment]
my bad figured out that the file (ar_grapheme_lexicon) was corrupted so the word_map file was also corrupted after that downloading ar_grapheme_lexicon problem solved. Thanks
