### ISSUE TITLE
Make fails on CentOS 8

### ISSUE THREAD

**Issue by maltejanssen** [kaldi-asr/kaldi#3772]
Hi, I have tried building Kaldi on CentOS 8. When executing make in the tools folder I get the following output:

```
make[2]: Entering directory '/opt/kaldi/tools/sctk-2.4.10/doc'
for p in align2html asclite ctmValidator mergectm2rttm; do \
        pod2man $p.pod -o $p.1; \
        pod2html $p.pod > $p.html; \
done 2> /dev/null
make[2]: *** [makefile:14: all] Error 127
make[2]: Leaving directory '/opt/kaldi/tools/sctk-2.4.10/doc'
make[1]: *** [makefile:25: doc] Error 2
make[1]: Leaving directory '/opt/kaldi/tools/sctk-2.4.10'
make: *** [Makefile:108: sclite_compiled] Error 2
```

Has anyone encountered this before and knows how to fix it?

**Comment by danpovey** [comment]
you.will have to remove 2 >/dev/null to debug

**Comment by jtrmal** [comment]
IIRC Error 127 is usually "command/executable not found"
y.

**Comment by maltejanssen** [comment]
Thanks guys. I am kinda new to c/c++ and makefiles. I had to install the perl package perl-Pod-Html.

**Comment by jtrmal** [comment]
well, definitely good job figuring out the dependency.
y.
