### ISSUE TITLE
FATAL ERROR in Subsetting Train Set (Babel s5b)

### ISSUE THREAD

**Issue by Kreeby** [kaldi-asr/kaldi#3775]
/export/babel/data/splits/Zulu_Babel206/train.LimitedLP.list ./data/raw_train_data
utils/make_absolute.sh: line 7: cd: /export/babel/data/206-zulu/release-current/conversational: No such file or directory

FATAL: input data directory does not exist

While trying to start ./run-1-main.sh we get an error with existence of directory. How to manage it?

P.S Where this export/babel/data appears (I mean in folders)

**Comment by danpovey** [comment]
You have to obtain the data (from LDC; it is not free) and change that path to wherever you put that part of the data.
