### ISSUE TITLE
nnet3-copy accuracy loss

### ISSUE THREAD

**Issue by haha010508** [kaldi-asr/kaldi#3777]
hi
I use nnet3-copy transfer .raw file to text file, and use the text file in my net, i found the result is differnet from the .raw file, later i found the nnet3-copy accuracy loss, for example: in .raw file, a number is:-0.128157005, but in text file is -0.128157, and the error will transfer from one layer to another, so the result will wrong.

**Comment by danpovey** [comment]
Not a bug; a little precision loss is expected when going via text format.  It won't make any difference to the WER results anyway.
