### ISSUE TITLE
local/swbd1_data_download.sh missing in fisher_swbd recipe

### ISSUE THREAD

**Issue by vijayaditya** [kaldi-asr/kaldi#378]
Is this the same file as the one used in swbd recipe ? If not could the owner of the recipe upload the appropriate script.

**Comment by danpovey** [comment]
Vijay, did you submit a fix for this in master?  Can we close this issue?

**Comment by vijayaditya** [comment]
Please close the issue. I found several other issues with the fisher_swbd
recipe. I will submit a fix for all of them next week.

--Vijay

**Comment by danpovey** [comment]
actually, will leave as open till resolved, so we don't lose track.

**Comment by vijayaditya** [comment]
@keli78 completed this.

**Comment by naxingyu** [comment]
The beginning of swbd1_data_prep.sh actually do what 
swbd1_data_download.sh does. It's a duplicate.

在 2016/2/17 6:31, Vijayaditya Peddinti 写道:

**Comment by danpovey** [comment]
Can you please figure out the best way to fix this, and submit a PR?

**Comment by naxingyu** [comment]
OK. The first 60 lines of swbd1_data_prep.sh is exactly the same as 
swbd1_data_download.sh.
IMO, simply removing swbd1_data_download.sh would fix this. (for both 
swbd and fisher_swbd recipes)

在 2016/2/17 11:27, Daniel Povey 写道:

**Comment by naxingyu** [comment]
Sorry, I was wrong. The point of swbd1_data_download is to provide 
transcriptions for preparing dict and getting acronyms mapping before 
swbd1_data_prep could use it. Thus the best way is to delete the 
download part in swbd1_data_prep.

在 2016/2/17 11:27, Daniel Povey 写道:

**Comment by danpovey** [comment]
OK.  It would be good if you can create a pull request for this.

**Comment by danpovey** [comment]
and be sure if we have done things like edit the URLs, that the most recent
version is the one that gets run.

**Comment by naxingyu** [comment]
yes i'll make sure it works.

在 2016/2/17 12:06, Daniel Povey 写道:
> and be sure if we have done things like edit the URLs, that the most 
> recent
> version is the one that gets run.
>
>
