### ISSUE TITLE
wrap DenominatorGraph

### ISSUE THREAD

**Issue by songmeixu** [kaldi-asr/kaldi#3786]

**Comment by naxingyu** [comment]
on it

**Comment by naxingyu** [comment]
It seems that most of the member functions of `DenominatorGraph` do not need to be exposed. It just need a constructor with `StdVectofFst` for loading, and `DenominatorComputation` takes case of the rest. Is it correct? @danpovey

**Comment by csukuangfj** [comment]
I think this issue can be closed now.
