### ISSUE TITLE
wrap chain::Supervision object

### ISSUE THREAD

**Issue by songmeixu** [kaldi-asr/kaldi#3787]

**Comment by naxingyu** [comment]
This should be chain::SupervisionOptions ?

**Comment by danpovey** [comment]
I meant Supervision but I was really talking about whichever code from the egs needs to be wrapped so that we can train with it.

**Comment by naxingyu** [comment]
Supervision and NnetChainSupervision are both bound in [here](https://github.com/kaldi-asr/kaldi/blob/pybind11/src/pybind/chain/chain_supervision_pybind.cc#L30) and [here](https://github.com/kaldi-asr/kaldi/blob/pybind11/src/pybind/nnet3/nnet_chain_example_pybind.cc#L33). We just need to see which interfaces are needed for kaldi-pybind to interact with pytorch.

**Comment by csukuangfj** [comment]
I think both are needed and they have already been wrapped and merged.

Please refer to https://github.com/mobvoi/kaldi/blob/fangjun-pybind11/egs/aishell/s10/chain/dataset.py#L125
for how the two are used in Python

```python
            supervision = eg.outputs[0].supervision
            supervision_list.append(supervision)

            batch_size = supervision.num_sequences
```

**Comment by csukuangfj** [comment]
I think this issue can be closed now.
