### ISSUE TITLE
speaker-id: Improvements to GMM-based frame-level VAD

### ISSUE THREAD

**Issue by david-ryan-snyder** [kaldi-asr/kaldi#381]
- Add Viterbi smoothing to compute-vad-from-frame-likes. Specify a penalty for switching between classes.
- compute-vad-from-frame-likes and merge-vads binaries interpret certain floats as integers. Add checks to ensure that these floats have an integer equivalent.
- Currently the GMM-based VAD is only used in the example egs/bn_music_speech. This needs to be added to the SID and LID recipes where it proves helpful.

See: https://github.com/kaldi-asr/kaldi/pull/354

(assignee: david-ryan-snyder)

**Comment by kkm000** [comment]
@david-ryan-snyder, if you do not mind, what are the publications behind this development? I see a reference to the MUSAN corpus, but that's all. I am very interested in voice discrimination!

**Comment by david-ryan-snyder** [comment]
@kkm000, this is mostly motivated by our experiences with speaker verification. Previously, we used only a simple energy-based VAD. Of course, this doesn't do a good job of distinguishing between music and speech (and other noises) that we sometimes encountered in real-world speaker verification. We felt that a simple GMM-based VAD trained to distinguish between these types of events would do a better job, so we compiled the MUSAN corpus, and introduced the GMM-based VAD.

Anyway, to answer your question, we have an ArXiv report that describes the MUSAN corpus (http://arxiv.org/pdf/1510.08484.pdf). There's no specific paper to point to for the VAD itself, but it's based on things like http://www.crim.ca/perso/patrick.kenny/Alam_odyssey2014.pdf and http://hltcoe.jhu.edu/uploads/publications/papers/17307_slides.pdf.

**Comment by david-ryan-snyder** [comment]
@kkm000, I should also point out that @vimalmanohar is working on a more robust set of VAD tools (https://github.com/vimalmanohar/kaldi/tree/snr). However, this will probably take a few months to make its way into Kaldi.

**Comment by kkm000** [comment]
@david-ryan-snyder: Thank you, very interesting!

**Comment by StevenLOL** [comment]
And a DNN-VAD ?

**Comment by david-ryan-snyder** [comment]
@vimalmanohar is working on that. I'm not sure what the status is.

**Comment by david-ryan-snyder** [comment]
@danpovey, @jtrmal, this issue can be closed/removed.

It's no longer relevant now that we have @vimalmanohar 's SAD system.

**Comment by david-ryan-snyder** [comment]
I just realized I can close this.
