### ISSUE TITLE
fstmakecontextfst produces C.fst with duplicated arcs on disambig symbols

### ISSUE THREAD

**Issue by taomanwai** [kaldi-asr/kaldi#3810]
For this [toy example](https://tommytaobucket.s3.amazonaws.com/C.pdf), mono-phone of Chinese, where one phone exactly equal to one Chinese character

Why and is it a bug ?

**Comment by danpovey** [comment]
I don't know, it depends what args you called the program with.

**Comment by taomanwai** [comment]
Sorry for missing command line code

fstmakecontextfst --context-size=1 --central-position=0 --read-disambig-syms=lang/phones/disambig.int  --write-disambig-syms=disambig_ilabels_1_0.int phones.txt 11 ilabels_1_0 > C.fst

PS:
phones.txt:
<eps> 0
SIL 1
SPN 2
地 3
鐵 4
去 5
#0 6
#1 7
#nonterm:entity 8
#nonterm_begin 9
#nonterm_end 10

lang/phones/disambig.int:
6
7
8
9
10

**Comment by danpovey** [comment]
The following lines:
```
    for (size_t i = 0; i < disambig_in.size(); i++) {
      int32 sym = disambig_in[i];
      loop_fst.AddArc(0, StdArc(sym, sym, TropicalWeight::One(), 0));
    }
```
need to be removed from fstmakcontextfst.cc since those symbols are already added from phones.txt.  Do you have time to make a PR:

**Comment by taomanwai** [comment]
Sure and wait, forking ...

**Comment by taomanwai** [comment]
PR created
