### ISSUE TITLE
use #!/usr/bin/env bash instead of #!/bin/bash

### ISSUE THREAD

**Issue by esdeboer** [kaldi-asr/kaldi#3812]
In quite some shell scripts #!/bin/bash is used, this won't work on distributions that don't have bash in /bin , for example freeBSD. Could you maybe replace them with #!/usr/bin/env bash , which should be more portable.

example are the scripts in tools/extra or in egs/wsj/s5

**Comment by danpovey** [comment]
You're right.  The intention is that we should always use /usr/bin/env (and
the same for Python invocations).
If you want you could write some kind of script which would replace them,
and make a pull request.
You could even leave the script in misc/maintenance, assuming it's
reasonably nice and portable.

**Comment by esdeboer** [comment]
I've created pull request #3881 with the script to use /usr/bin/env on all bash scripts in the project.
There are still quite some rough edges to get it to compile on freebsd. I got the tools dir to compile, but the src dir still has some linking issues if I try to compile with gmake, cmake does work.

**Comment by jtrmal** [comment]
resolved by #3881
