### ISSUE TITLE
I found an error of sorting  utt2spk   in the  "/kaldi/egs/timit/s5/utils/validate_data_dir.sh" 

### ISSUE THREAD

**Issue by tdkman** [kaldi-asr/kaldi#3816]
I  tried to   run sample  of  digit asr ,  but  I get a error.  
 "utils/validate_data_dir.sh: utt2spk is not in sorted order when sorted first on speaker-id (fix this by making speaker-ids prefixes of utt-ids)"

I looked at the " validate_data_dir.sh"  file and the problem was due to inconsistent sort parameters.

in the check_sorted_and_uniq  function ,there are no sort parameters,
function check_sorted_and_uniq {
  ! perl -ne '((substr $_,-1) eq "\n") or die "file $ARGV has invalid newline";' $1 && exit 1;
  ! awk '{print $1}' $1 | sort | uniq | cmp -s - <(awk '{print $1}' $1) && \
    echo "$0: file $1 is not in sorted order or has duplicates" && exit 1;
}

but in the code blew , we have the sort parameter -k2

if ! $no_spk_sort; then
  ! cat $data/utt2spk | sort -k2 | cmp -s - $data/utt2spk && \
     echo "$0: utt2spk is not in sorted order when sorted first on speaker-id " && \
     echo "(fix this by making speaker-ids prefixes of utt-ids)" && exit 1;
fi
after I cancel the sort parameters -k2 ,the code executes successfully!

**Comment by danpovey** [comment]
It's an issue with your data, not with the script.  The easiest fix is to make sure that the speaker-id is a prefix of the utterance-id.
The script is doing what is intended.
