### ISSUE TITLE
zlib is not getting installed.

### ISSUE THREAD

**Issue by OhmVikrant** [kaldi-asr/kaldi#3819]
When 'sudo apt-get install zlib1g-dev' is run, it show no error but on running 'extras/check_dependencies.sh'  we get the error that 'zlib is not installed. Please refer to the screenshot below.

![zlib_issue](https://user-images.githubusercontent.com/46784336/71837968-c8068e80-30dd-11ea-9200-7dce512d6362.jpeg)

**Comment by danpovey** [comment]
Looks like your `$(CC)` variable (the compiler) is probably set to something from an anaconda distribution, which would be bypassing the system compiler and its associated libraries.

**Comment by naxingyu** [comment]
sudo apt-get install zlib-devel

**Comment by shantanuspathak** [comment]
I am having similar problem
Please tell me how to fix the problem
how to make $(CC) point to system compiler ?
