### ISSUE TITLE
MKL package installation failed

### ISSUE THREAD

**Issue by ranjal** [kaldi-asr/kaldi#3821]
Hi Everyone,
I am trying to install KALDI speech toolkit and i am getting following error in one of the step of Kaldi installation.
I am new and i am follwing this link http://jrmeyer.github.io/asr/2016/01/26/Installing-Kaldi.html
for Kaldi installation.

hcl-rishi@hclrishi:~/kaldi/tools$ sudo extras/install_mkl.sh
extras/install_mkl.sh: Your system is using debian-style package management.
+ apt-get update
Ign:1 http://www.scootersoftware.com bcompare4 InRelease                                      
Hit:2 http://www.scootersoftware.com bcompare4 Release                                        
Hit:4 https://download.sublimetext.com apt/stable/ InRelease                                       
Hit:5 http://download.virtualbox.org/virtualbox/debian xenial InRelease                                              
Hit:6 http://in.archive.ubuntu.com/ubuntu xenial InRelease                                                           
Ign:7 http://dl.google.com/linux/chrome/deb stable InRelease                                                         
Hit:8 http://in.archive.ubuntu.com/ubuntu xenial-updates InRelease                                                   
Hit:9 http://in.archive.ubuntu.com/ubuntu xenial-backports InRelease                                                 
Hit:10 http://dl.google.com/linux/chrome/deb stable Release                                                          
Hit:11 https://download.docker.com/linux/ubuntu xenial InRelease                                                     
Get:13 http://security.ubuntu.com/ubuntu xenial-security InRelease [109 kB]                         
Hit:14 http://ppa.launchpad.net/maarten-baert/simplescreenrecorder/ubuntu xenial InRelease     
Ign:15 http://ppa.launchpad.net/mc3man/trusty-media/ubuntu xenial InRelease                                          
Hit:16 http://ppa.launchpad.net/viktor-krivak/pycharm/ubuntu xenial InRelease                                        
Hit:17 http://ppa.launchpad.net/webupd8team/java/ubuntu xenial InRelease                                             
Ign:18 http://ppa.launchpad.net/mc3man/trusty-media/ubuntu xenial Release                                            
Ign:19 http://ppa.launchpad.net/mc3man/trusty-media/ubuntu xenial/main amd64 Packages                                
Ign:20 http://ppa.launchpad.net/mc3man/trusty-media/ubuntu xenial/main i386 Packages                                 
Ign:21 http://ppa.launchpad.net/mc3man/trusty-media/ubuntu xenial/main all Packages                                  
Ign:22 http://ppa.launchpad.net/mc3man/trusty-media/ubuntu xenial/main Translation-en_IN                             
Ign:23 http://ppa.launchpad.net/mc3man/trusty-media/ubuntu xenial/main Translation-en                                
Ign:24 http://ppa.launchpad.net/mc3man/trusty-media/ubuntu xenial/main amd64 DEP-11 Metadata                         
Ign:25 http://ppa.launchpad.net/mc3man/trusty-media/ubuntu xenial/main DEP-11 64x64 Icons
Ign:19 http://ppa.launchpad.net/mc3man/trusty-media/ubuntu xenial/main amd64 Packages
Ign:20 http://ppa.launchpad.net/mc3man/trusty-media/ubuntu xenial/main i386 Packages
Ign:21 http://ppa.launchpad.net/mc3man/trusty-media/ubuntu xenial/main all Packages
Ign:22 http://ppa.launchpad.net/mc3man/trusty-media/ubuntu xenial/main Translation-en_IN
Ign:23 http://ppa.launchpad.net/mc3man/trusty-media/ubuntu xenial/main Translation-en
Ign:24 http://ppa.launchpad.net/mc3man/trusty-media/ubuntu xenial/main amd64 DEP-11 Metadata
Ign:25 http://ppa.launchpad.net/mc3man/trusty-media/ubuntu xenial/main DEP-11 64x64 Icons
Ign:19 http://ppa.launchpad.net/mc3man/trusty-media/ubuntu xenial/main amd64 Packages
Ign:20 http://ppa.launchpad.net/mc3man/trusty-media/ubuntu xenial/main i386 Packages
Ign:21 http://ppa.launchpad.net/mc3man/trusty-media/ubuntu xenial/main all Packages
Ign:22 http://ppa.launchpad.net/mc3man/trusty-media/ubuntu xenial/main Translation-en_IN
Ign:23 http://ppa.launchpad.net/mc3man/trusty-media/ubuntu xenial/main Translation-en
Ign:24 http://ppa.launchpad.net/mc3man/trusty-media/ubuntu xenial/main amd64 DEP-11 Metadata
Ign:25 http://ppa.launchpad.net/mc3man/trusty-media/ubuntu xenial/main DEP-11 64x64 Icons
Ign:19 http://ppa.launchpad.net/mc3man/trusty-media/ubuntu xenial/main amd64 Packages
Ign:20 http://ppa.launchpad.net/mc3man/trusty-media/ubuntu xenial/main i386 Packages
Ign:21 http://ppa.launchpad.net/mc3man/trusty-media/ubuntu xenial/main all Packages
Ign:22 http://ppa.launchpad.net/mc3man/trusty-media/ubuntu xenial/main Translation-en_IN
Ign:23 http://ppa.launchpad.net/mc3man/trusty-media/ubuntu xenial/main Translation-en
Ign:24 http://ppa.launchpad.net/mc3man/trusty-media/ubuntu xenial/main amd64 DEP-11 Metadata
Ign:25 http://ppa.launchpad.net/mc3man/trusty-media/ubuntu xenial/main DEP-11 64x64 Icons
Ign:19 http://ppa.launchpad.net/mc3man/trusty-media/ubuntu xenial/main amd64 Packages
Ign:20 http://ppa.launchpad.net/mc3man/trusty-media/ubuntu xenial/main i386 Packages
Ign:21 http://ppa.launchpad.net/mc3man/trusty-media/ubuntu xenial/main all Packages
Ign:22 http://ppa.launchpad.net/mc3man/trusty-media/ubuntu xenial/main Translation-en_IN
Ign:23 http://ppa.launchpad.net/mc3man/trusty-media/ubuntu xenial/main Translation-en
Ign:24 http://ppa.launchpad.net/mc3man/trusty-media/ubuntu xenial/main amd64 DEP-11 Metadata
Ign:25 http://ppa.launchpad.net/mc3man/trusty-media/ubuntu xenial/main DEP-11 64x64 Icons
Err:19 http://ppa.launchpad.net/mc3man/trusty-media/ubuntu xenial/main amd64 Packages
  404  Not Found [IP: 2001:67c:1560:8008::15 80]
Ign:20 http://ppa.launchpad.net/mc3man/trusty-media/ubuntu xenial/main i386 Packages
Ign:21 http://ppa.launchpad.net/mc3man/trusty-media/ubuntu xenial/main all Packages
Ign:22 http://ppa.launchpad.net/mc3man/trusty-media/ubuntu xenial/main Translation-en_IN
Ign:23 http://ppa.launchpad.net/mc3man/trusty-media/ubuntu xenial/main Translation-en
Ign:24 http://ppa.launchpad.net/mc3man/trusty-media/ubuntu xenial/main amd64 DEP-11 Metadata
Ign:25 http://ppa.launchpad.net/mc3man/trusty-media/ubuntu xenial/main DEP-11 64x64 Icons
Fetched 109 kB in 3min 16s (556 B/s)
Reading package lists... Done
W: Target Packages (contrib/binary-amd64/Packages) is configured multiple times in /etc/apt/sources.list:56 and /etc/apt/sources.list:57
W: Target Packages (contrib/binary-i386/Packages) is configured multiple times in /etc/apt/sources.list:56 and /etc/apt/sources.list:57
W: Target Packages (contrib/binary-all/Packages) is configured multiple times in /etc/apt/sources.list:56 and /etc/apt/sources.list:57
W: Target Translations (contrib/i18n/Translation-en_IN) is configured multiple times in /etc/apt/sources.list:56 and /etc/apt/sources.list:57
W: Target Translations (contrib/i18n/Translation-en) is configured multiple times in /etc/apt/sources.list:56 and /etc/apt/sources.list:57
W: Target DEP-11 (contrib/dep11/Components-amd64.yml) is configured multiple times in /etc/apt/sources.list:56 and /etc/apt/sources.list:57
W: Target DEP-11-icons (contrib/dep11/icons-64x64.tar) is configured multiple times in /etc/apt/sources.list:56 and /etc/apt/sources.list:57
W: Target Packages (contrib/binary-amd64/Packages) is configured multiple times in /etc/apt/sources.list:56 and /etc/apt/sources.list:58
W: Target Packages (contrib/binary-i386/Packages) is configured multiple times in /etc/apt/sources.list:56 and /etc/apt/sources.list:58
W: Target Packages (contrib/binary-all/Packages) is configured multiple times in /etc/apt/sources.list:56 and /etc/apt/sources.list:58
W: Target Translations (contrib/i18n/Translation-en_IN) is configured multiple times in /etc/apt/sources.list:56 and /etc/apt/sources.list:58
W: Target Translations (contrib/i18n/Translation-en) is configured multiple times in /etc/apt/sources.list:56 and /etc/apt/sources.list:58
W: Target DEP-11 (contrib/dep11/Components-amd64.yml) is configured multiple times in /etc/apt/sources.list:56 and /etc/apt/sources.list:58
W: Target DEP-11-icons (contrib/dep11/icons-64x64.tar) is configured multiple times in /etc/apt/sources.list:56 and /etc/apt/sources.list:58
W: The repository 'http://ppa.launchpad.net/mc3man/trusty-media/ubuntu xenial Release' does not have a Release file.
N: Data from such a repository can't be authenticated and is therefore potentially dangerous to use.
N: See apt-secure(8) manpage for repository creation and user configuration details.
E: Failed to fetch http://ppa.launchpad.net/mc3man/trusty-media/ubuntu/dists/xenial/main/binary-amd64/Packages  404  Not Found [IP: 2001:67c:1560:8008::15 80]
E: Some index files failed to download. They have been ignored, or old ones used instead.
W: Target Packages (contrib/binary-amd64/Packages) is configured multiple times in /etc/apt/sources.list:56 and /etc/apt/sources.list:57
W: Target Packages (contrib/binary-i386/Packages) is configured multiple times in /etc/apt/sources.list:56 and /etc/apt/sources.list:57
W: Target Packages (contrib/binary-all/Packages) is configured multiple times in /etc/apt/sources.list:56 and /etc/apt/sources.list:57
W: Target Translations (contrib/i18n/Translation-en_IN) is configured multiple times in /etc/apt/sources.list:56 and /etc/apt/sources.list:57
W: Target Translations (contrib/i18n/Translation-en) is configured multiple times in /etc/apt/sources.list:56 and /etc/apt/sources.list:57
W: Target DEP-11 (contrib/dep11/Components-amd64.yml) is configured multiple times in /etc/apt/sources.list:56 and /etc/apt/sources.list:57
W: Target DEP-11-icons (contrib/dep11/icons-64x64.tar) is configured multiple times in /etc/apt/sources.list:56 and /etc/apt/sources.list:57
W: Target Packages (contrib/binary-amd64/Packages) is configured multiple times in /etc/apt/sources.list:56 and /etc/apt/sources.list:58
W: Target Packages (contrib/binary-i386/Packages) is configured multiple times in /etc/apt/sources.list:56 and /etc/apt/sources.list:58
W: Target Packages (contrib/binary-all/Packages) is configured multiple times in /etc/apt/sources.list:56 and /etc/apt/sources.list:58
W: Target Translations (contrib/i18n/Translation-en_IN) is configured multiple times in /etc/apt/sources.list:56 and /etc/apt/sources.list:58
W: Target Translations (contrib/i18n/Translation-en) is configured multiple times in /etc/apt/sources.list:56 and /etc/apt/sources.list:58
W: Target DEP-11 (contrib/dep11/Components-amd64.yml) is configured multiple times in /etc/apt/sources.list:56 and /etc/apt/sources.list:58
W: Target DEP-11-icons (contrib/dep11/icons-64x64.tar) is configured multiple times in /etc/apt/sources.list:56 and /etc/apt/sources.list:58
extras/install_mkl.sh: MKL package intel-mkl-64bit-2019.2-057 installation FAILED.

Please open an issue with us at https://github.com/kaldi-asr/kaldi/ if you
believe this is a bug.

Please guide me.
Thanks in advance.

**Comment by danpovey** [comment]
That's a system issue, not a kaldi-specific issue; `apt-get update` is a common system update command.  Clean up your /etc/apt/sources.list, e.g. remove lines 57 and 58, that might work.  Look on Debian lists if not.
