### ISSUE TITLE
without file aspire_prep_rir_noise_list.py

### ISSUE THREAD

**Issue by nichongjia-2007** [kaldi-asr/kaldi#3824]
When running aspire/s5/local/multi_condition/run_nnet2_common.sh, 

The line "python local/multi_condition/aspire_prep_rir_noise_list.py data/impulses_noises data/impulses_noises/info"

Could not find the file aspire_prep_rir_noise_list.py

Could you include the file into the directory?

**Comment by Shujian2015** [comment]
Hi @nichongjia-2007 , are you running the aspire recipe? as far as I know, run_nnet2_common.sh is no longer called in that recipe.

**Comment by kkm000** [comment]
I am closing this issue, as you've been apparently helped. If you believe that your issue has not been addressed, please feel free to ping me, and I'll reopen it. @-mention me for a faster response!
