### ISSUE TITLE
Branch pybind11 can not be compiled without GPU.

### ISSUE THREAD

**Issue by qindazhu** [kaldi-asr/kaldi#3825]
FYI.

`g++ -c -std=c++11 -I.. -isystem /home/work/kaldi/tools/openfst-1.6.7/include -O1 -Wno-sign-compare -Wall -Wno-sign-compare -Wno-unused-local-typedefs -Wno-deprecated-declarations -Winit-self -DKALDI_DOUBLEPRECISION=0 -DHAVE_EXECINFO_H=1 -DHAVE_CXXABI_H -DHAVE_MKL -I/opt/intel/mkl/include -m64 -msse -msse2 -pthread -g -fPIC -I/usr/include/python3.6m -I/usr/local/include/python3.6m -I/root/.local/include/python3.6m -O3 -flto -I. -o dlpack/dlpack_pybind.o dlpack/dlpack_pybind.cc
dlpack/dlpack_pybind.cc: In function ‘kaldi::DLPackCuSubVector<float>* kaldi::CuSubVectorFromDLPack(pybind11::capsule*)’:
dlpack/dlpack_pybind.cc:299:19: error: cannot convert ‘pybind11::none’ to ‘kaldi::DLPackCuSubVector<float>*’ in return
   return py::none();
                   ^
dlpack/dlpack_pybind.cc: In function ‘kaldi::DLPackCuSubMatrix<float>* kaldi::CuSubMatrixFromDLPack(pybind11::capsule*)’:
dlpack/dlpack_pybind.cc:315:19: error: cannot convert ‘pybind11::none’ to ‘kaldi::DLPackCuSubMatrix<float>*’ in return
   return py::none();
                   ^
make: *** [dlpack/dlpack_pybind.o] Error 1
`

It seems it is intended to do this for now

https://github.com/kaldi-asr/kaldi/blob/4807173a3338e90f0c3eee417ac3155875468d6e/src/pybind/dlpack/dlpack_pybind.cc#L289-L301

I'll try to fix it later this week.

**Comment by danpovey** [comment]
The way Kaldi itself works when not compiled for GPU is it expects those
GPU things to actually be on CPU.

**Comment by qindazhu** [comment]
Sure, will do. It seems there is required some `#if HAVE_CUDA == 1...#else`, but I need to figure out all related code first. Anyway, I'll get familiar with branch pybind11 this week and then fix the issue.

**Comment by csukuangfj** [comment]
just return `nullptr` instead of `py::none()` will do.

**Comment by qindazhu** [comment]
Aha, I have done this, but encounter a new error and is trying to fix it now.

`g++ -c -std=c++11 -I.. -isystem /home/work/kaldi/tools/openfst-1.6.7/include -O1 -Wno-sign-compare -Wall -Wno-sign-compare -Wno-unused-local-typedefs -Wno-deprecated-declarations -Winit-self -DKALDI_DOUBLEPRECISION=0 -DHAVE_EXECINFO_H=1 -DHAVE_CXXABI_H -DHAVE_MKL -I/opt/intel/mkl/include -m64 -msse -msse2 -pthread -g -fPIC -I/usr/include/python3.6m -I/usr/local/include/python3.6m -I/root/.local/include/python3.6m -O3 -flto -I. -o util/util_pybind.o util/util_pybind.cc
g++ -std=c++11 -I.. -isystem /home/work/kaldi/tools/openfst-1.6.7/include -O1 -Wno-sign-compare -Wall -Wno-sign-compare -Wno-unused-local-typedefs -Wno-deprecated-declarations -Winit-self -DKALDI_DOUBLEPRECISION=0 -DHAVE_EXECINFO_H=1 -DHAVE_CXXABI_H -DHAVE_MKL -I/opt/intel/mkl/include -m64 -msse -msse2 -pthread -g -fPIC -I/usr/include/python3.6m -I/usr/local/include/python3.6m -I/root/.local/include/python3.6m -O3 -flto -I. -shared -o kaldi_pybind.cpython-36m-x86_64-linux-gnu.so chain/chain_den_graph_pybind.o chain/chain_pybind.o chain/chain_supervision_pybind.o chain/chain_training_pybind.o cudamatrix/cu_device_pybind.o cudamatrix/cu_matrix_pybind.o cudamatrix/cu_vector_pybind.o cudamatrix/cudamatrix_pybind.o dlpack/dlpack_deleter.o dlpack/dlpack_pybind.o dlpack/dlpack_submatrix.o dlpack/dlpack_subvector.o feat/feat_pybind.o feat/feature_pybind.o feat/online_feature_pybind.o feat/wave_reader_pybind.o fst/arc_pybind.o fst/compile_pybind.o fst/fst_pybind.o fst/symbol_table_pybind.o fst/vector_fst_pybind.o fst/weight_pybind.o fstext/kaldi_fst_io_pybind.o kaldi_pybind.o matrix/compressed_matrix_pybind.o matrix/kaldi_matrix_pybind.o matrix/kaldi_vector_pybind.o matrix/matrix_common_pybind.o matrix/matrix_pybind.o matrix/sparse_matrix_pybind.o nnet3/nnet3_pybind.o nnet3/nnet_chain_example_pybind.o nnet3/nnet_common_pybind.o nnet3/nnet_example_pybind.o tests/test_dlpack_subvector.o util/kaldi_io_pybind.o util/table_types_pybind.o util/util_pybind.o -Wl,--no-whole-archive -Wl,-rpath=/home/work/kaldi/src/pybind/../lib  -Wl,-rpath=/home/work/kaldi/tools/openfst-1.6.7/lib -rdynamic -flto -Wl,-rpath=/home/work/kaldi/src/pybind/../../tools/openfst/lib  ../base/libkaldi-base.so  ../chain/libkaldi-chain.so  ../cudamatrix/libkaldi-cudamatrix.so  ../feat/libkaldi-feat.so  ../fstext/libkaldi-fstext.so  ../matrix/libkaldi-matrix.so  ../nnet3/libkaldi-nnet3.so  ../util/libkaldi-util.so ../../tools/openfst/lib/libfstscript.so /home/work/kaldi/tools/openfst-1.6.7/lib/libfst.so -L/opt/intel/mkl/lib/intel64 -Wl,-rpath=/opt/intel/mkl/lib/intel64 -lmkl_intel_lp64  -lmkl_core  -lmkl_sequential    -ldl -lpthread -lm  -lm -lpthread -ldl  ../base/libkaldi-base.so  ../chain/libkaldi-chain.so  ../cudamatrix/libkaldi-cudamatrix.so  ../feat/libkaldi-feat.so  ../fstext/libkaldi-fstext.so  ../matrix/libkaldi-matrix.so  ../nnet3/libkaldi-nnet3.so  ../util/libkaldi-util.so ../../tools/openfst/lib/libfstscript.so
lto1: internal compiler error: in output_die, at dwarf2out.c:8500
Please submit a full bug report,
with preprocessed source if appropriate.
See <http://bugzilla.redhat.com/bugzilla> for instructions.
lto-wrapper: g++ returned 1 exit status
/bin/ld: error: lto-wrapper failed
collect2: error: ld returned 1 exit status
make: *** [kaldi_pybind.cpython-36m-x86_64-linux-gnu.so] Error 1
`

**Comment by csukuangfj** [comment]
For the other problem, please refer to https://github.com/kaldi-asr/kaldi/issues/3795
> I don't use ABI specifically.
I got another problem when I reclone kaldi and build it agian.

The might exist some problems with your compiler.

**Comment by qindazhu** [comment]
Thanks Fangjun. 

BTW, for the fix. I think it's better for us to compile Cuda related code only on GPU devices, instead of just returning a `nullptr` on CPU devices. Anyway, return a `nullptr` is meaningless to the user, right?

**Comment by csukuangfj** [comment]
`return nullptr`  is to please the compiler. `KALDI_ERR` will throw and the program will crash.

You have to return something from the function which is declared to return something.

**Comment by qindazhu** [comment]
Actually not, you have to return `nullptr` because there is a `#if...#else`

https://github.com/kaldi-asr/kaldi/blob/4807173a3338e90f0c3eee417ac3155875468d6e/src/pybind/dlpack/dlpack_pybind.cc#L289-L301

But I guess return `nullptr` from function `CuSubVectorFromDLPack` means the function will be never called by CPU devices, right? If so, why not just compile it only on GPU devices by putting `#if HAVE_CUDA == 1` outside of the function. This will prevent users from calling this function on CPU devices, instead of having some crash by passing `nullptr`.

**Comment by csukuangfj** [comment]
Without the return statement, the function becomes
```cpp
DLPackCuSubMatrix<float>* CuSubMatrixFromDLPack(py::capsule* capsule) {
  KALDI_ERR << "Kaldi is not compiled with GPU!";
}
```

You can see that the signature declares to return `DLPackCuSubMatrix<float>*`
but it returns nothing and results in compiler warnings.

`return nullptr` is added to remove compiler warnings and is never executed due to
`KALDI_ERR`, which causes the program to crash.

The crash is not caused by `return nullptr` but by `KALDI_ERR`.

A user can compile Kaldi without GPU support on a GPU enabled computer. For example,
if his cuda toolkit is not installed in `/usr/local/cuda`, the `configure` script of Kaldi
may not be able to detect the existence of CUDA and so Kaldi is compiled with CPU only.

But the user is expected to call `CuSubVectorFromDLPack` from Python; in this
case, the program will crash and shows an error: `Kaldi is not compiled with GPU`

**Comment by csukuangfj** [comment]
In PyTorch, the `tensor` has a method `cuda()`. You can call it even if you do not have a GPU, but
you will get `raise AssertionError("Torch not compiled with CUDA enabled")`

**Comment by qindazhu** [comment]
Yes, I'm totally agree with you on the crash time, my point is, it's better for us to do more things on compile time instead of runtime. We should never expose any interface to users if he will never call it.

**Comment by qindazhu** [comment]
so we will follow PyTorch rules, throw exception in runtime, right? I'm fine with this, just want to make sure the rules to follow.

**Comment by csukuangfj** [comment]
Initially, I followed the approach you just suggested. But I think a **uniform** interface presented
to the user may be better. Users have the right to choose which one to use. But if he
chooses the one not supposed to use, the program will fail **explicitly**.

**Comment by qindazhu** [comment]
Sounds reasonable. Then I'll follow this approach in my PRs. Thanks for clarification.
