### ISSUE TITLE
CMVN question 

### ISSUE THREAD

**Issue by panxin801** [kaldi-asr/kaldi#3827]
HI,
I have mfcc feat which dim is 16, and then I calculate the cmvn stats, but I find the cmvn dim is 17(17=16+1), I don't know what is storaging in the last dimension, can you explain this. 
Thanks

**Comment by danpovey** [comment]
it stores the count of frames.  reading the code would have been quicker.

**Comment by csukuangfj** [comment]
@panxin801 

The format of the CMVN is as follows

```
row0: sum_feat_dim_0,      sum_feat_dim_1,       ..., sum_feat_dim_15,       total_frame_count
row1: square_sum_feat_dim0,square_sum_feat_dim_1,..., square_sum_feat_dim_15, 0
```

The code for `sum_feat_dim_i` is
https://github.com/kaldi-asr/kaldi/blob/129e28bd6186ce369310906985d09e182ed3122a/src/transform/cmvn.cc#L44

The code for `square_sum_feat_dim_i` is
https://github.com/kaldi-asr/kaldi/blob/129e28bd6186ce369310906985d09e182ed3122a/src/transform/cmvn.cc#L45

Code for `total_frame_count` is
https://github.com/kaldi-asr/kaldi/blob/129e28bd6186ce369310906985d09e182ed3122a/src/transform/cmvn.cc#L40

**Comment by panxin801** [comment]
Oh, I get it . Thank you Dan , thank you csukuangfj so much. I just dont know the total_frame_count now I am clear now. Thank you again
