### ISSUE TITLE
Speaker verification with Kaldi on Android

### ISSUE THREAD

**Issue by chamecall** [kaldi-asr/kaldi#3829]
I have to define by a voice whether it has spoken by one particular person or not..
Is that possible to handle a speaker verification with Kaldi on Android?

**Comment by danpovey** [comment]
It is, but it would be quite a bit of work to deploy, especially with getting the model small enough and memory efficient.  You could look at the i-vector or x-vector setups for speaker verification.  You should learn the basics of how speaker verification works first.

**Comment by danpovey** [comment]
.. btw, we just call it speaker-id in many Kaldi scripts.. it's really the same task.
