### ISSUE TITLE
speaker-id: Bug inivector/voice-activity-detection.cc

### ISSUE THREAD

**Issue by david-ryan-snyder** [kaldi-asr/kaldi#383]
On the Kaldi ASR forums, lzhu.qs@gmail.com pointed out that there may be a bug in ivector/voice-activity-detection.cc line 54. `if (log_energy_data[t] > energy_threshold)`  should probably be changed to `if (log_energy_data[t2] > energy_threshold)`.

Matthew (@mmaciej2), this VAD is used in certain speaker ID and language ID scripts. Could you see how this change affects the examples in egs/sre08 and egs/sre10? By fixing this, some of the settings in the VAD are going to work differently, especially vad_frames_context (see http://kaldi.sourceforge.net/structkaldi_1_1VadEnergyOptions.html). If you get a degradation initially, you'll want to vary vad_frames_context, until it works as well or better than the original, bugged version. I recommend trying this (and possibly tuning the config parameters) first on egs/sre10/v1, and then using what works on the other examples.

**Comment by kkm000** [comment]
I assume that was all to the fix? Closing, let me know if incorrect.

**Comment by david-ryan-snyder** [comment]
Yes, this should be closed. Thanks!
