### ISSUE TITLE
Key imported successfully Import of key(s) didn't help, wrong key(s)?

### ISSUE THREAD

**Issue by fredjame** [kaldi-asr/kaldi#3837]
Mageia 7 64bit. Plasma desktop
Running "extras/install_mkl.sh", ran into GPG key errors ...
==============
extras/install_mkl.sh: Your system is using fedora-style package management.
+ dnf -y install 'dnf-command(config-manager)'
determining the fastest mirror (10 hosts).. done.                                   [   ===                                                                        ] ---  B/s |   0  B     --:-- ETA
Mageia 7 - x86_64                                                                                                                                                    583 kB/s |  35 MB     01:02    
determining the fastest mirror (5 hosts).. done.                               100% [==============================================================================] 2.1 kB/s | 750  B     00:00 ETA
Mageia 7 - x86_64 - Updates                                                                                                                                          569 kB/s |  16 MB     00:28    
Last metadata expiration check: 0:00:25 ago on Sat 11 Jan 2020 02:48:41 PM EST.
Package dnf-plugins-core-4.0.7-1.mga7.noarch is already installed.
Dependencies resolved.
Nothing to do.
Complete!
+ dnf config-manager --add-repo https://yum.repos.intel.com/mkl/setup/intel-mkl.repo
Adding repo from: https://yum.repos.intel.com/mkl/setup/intel-mkl.repo
+ dnf -y install intel-mkl-64bit-2019.2-057
Intel(R) Math Kernel Library                                                                                                                                         368  B/s | 287  B     00:00    
Intel(R) Math Kernel Library                                                                                                                                         2.8 kB/s | 939  B     00:00    
Importing GPG key 0x7E6C5DBE:
 Userid     : "Intel(R) Software Development Products"
 Fingerprint: 52AB D6E8 7E42 1793 9718 73FF ACFA 9FC5 7E6C 5DBE
 From       : https://yum.repos.intel.com/mkl/setup/PUBLIC_KEY.PUB
Intel(R) Math Kernel Library                                                                                                                                         355 kB/s | 857 kB     00:02    
Last metadata expiration check: 0:00:01 ago on Sat 11 Jan 2020 02:49:12 PM EST.
Dependencies resolved.
=====================================================================================================================================================================================================
 Package                                                                             Architecture                   Version                             Repository                              Size
=====================================================================================================================================================================================================
Installing:
 intel-mkl-64bit-2019.2-057                                                          x86_64                         2019.2-057                          intel-mkl-repo                         5.0 k
Installing dependencies:
 intel-comp-l-all-vars-19.0.2-187                                                    noarch                         19.0.2-187                          intel-mkl-repo                          12 k
 intel-comp-nomcu-vars-19.0.2-187                                                    noarch                         19.0.2-187                          intel-mkl-repo                         8.8 k
 intel-conda-index-tool-19.0.2-187                                                   x86_64                         19.0.2-187                          intel-mkl-repo                          13 M
 intel-conda-intel-openmp-linux-64-shadow-package-2019.2-187                         x86_64                         2019.2-187                          intel-mkl-repo                          10 k
 intel-conda-mkl-devel-linux-64-shadow-package-2019.2-187                            x86_64                         2019.2-187                          intel-mkl-repo                          10 k
 intel-conda-mkl-include-linux-64-shadow-package-2019.2-187                          x86_64                         2019.2-187                          intel-mkl-repo                          11 k
 intel-conda-mkl-linux-64-shadow-package-2019.2-187                                  x86_64                         2019.2-187                          intel-mkl-repo                          11 k
 intel-conda-mkl-static-linux-64-shadow-package-2019.2-187                           x86_64                         2019.2-187                          intel-mkl-repo                          11 k
 intel-conda-tbb-linux-64-shadow-package-2019.2-187                                  x86_64                         2019.2-187                          intel-mkl-repo                          10 k
 intel-mkl-cluster-2019.2-187                                                        x86_64                         2019.2-187                          intel-mkl-repo                         7.5 M
 intel-mkl-cluster-c-2019.2-187                                                      noarch                         2019.2-187                          intel-mkl-repo                         2.1 k
 intel-mkl-cluster-f-2019.2-187                                                      noarch                         2019.2-187                          intel-mkl-repo                         2.1 k
 intel-mkl-cluster-rt-2019.2-187                                                     x86_64                         2019.2-187                          intel-mkl-repo                         6.3 M
 intel-mkl-common-2019.2-187                                                         noarch                         2019.2-187                          intel-mkl-repo                         101 k
 intel-mkl-common-c-2019.2-187                                                       noarch                         2019.2-187                          intel-mkl-repo                         1.8 M
 intel-mkl-common-c-ps-2019.2-187                                                    noarch                         2019.2-187                          intel-mkl-repo                          72 k
 intel-mkl-common-f-2019.2-187                                                       noarch                         2019.2-187                          intel-mkl-repo                         2.1 M
 intel-mkl-common-ps-2019.2-187                                                      noarch                         2019.2-187                          intel-mkl-repo                          81 k
 intel-mkl-core-2019.2-187                                                           x86_64                         2019.2-187                          intel-mkl-repo                         217 M
 intel-mkl-core-c-2019.2-187                                                         x86_64                         2019.2-187                          intel-mkl-repo                         2.2 k
 intel-mkl-core-f-2019.2-187                                                         x86_64                         2019.2-187                          intel-mkl-repo                         2.2 k
 intel-mkl-core-ps-2019.2-187                                                        x86_64                         2019.2-187                          intel-mkl-repo                          10 M
 intel-mkl-core-rt-2019.2-187                                                        x86_64                         2019.2-187                          intel-mkl-repo                         210 M
 intel-mkl-doc-2019                                                                  noarch                         2019.5-281                          intel-mkl-repo                          13 k
 intel-mkl-doc-ps-2019                                                               noarch                         2019.5-281                          intel-mkl-repo                         213 k
 intel-mkl-f95-2019.2-187                                                            x86_64                         2019.2-187                          intel-mkl-repo                         4.9 M
 intel-mkl-f95-common-2019.2-187                                                     noarch                         2019.2-187                          intel-mkl-repo                         410 k
 intel-mkl-gnu-2019.2-187                                                            x86_64                         2019.2-187                          intel-mkl-repo                         8.0 M
 intel-mkl-gnu-c-2019.2-187                                                          x86_64                         2019.2-187                          intel-mkl-repo                         2.2 k
 intel-mkl-gnu-f-2019.2-187                                                          x86_64                         2019.2-187                          intel-mkl-repo                         5.2 M
 intel-mkl-gnu-f-rt-2019.2-187                                                       x86_64                         2019.2-187                          intel-mkl-repo                         4.9 M
 intel-mkl-gnu-rt-2019.2-187                                                         x86_64                         2019.2-187                          intel-mkl-repo                         7.3 M
 intel-mkl-pgi-2019.2-187                                                            x86_64                         2019.2-187                          intel-mkl-repo                          13 M
 intel-mkl-pgi-c-2019.2-187                                                          x86_64                         2019.2-187                          intel-mkl-repo                         2.2 k
 intel-mkl-pgi-rt-2019.2-187                                                         x86_64                         2019.2-187                          intel-mkl-repo                          11 M
 intel-mkl-psxe-2019.2-057                                                           noarch                         2019.2-057                          intel-mkl-repo                         3.6 k
 intel-mkl-tbb-2019.2-187                                                            x86_64                         2019.2-187                          intel-mkl-repo                         9.5 M
 intel-mkl-tbb-rt-2019.2-187                                                         x86_64                         2019.2-187                          intel-mkl-repo                         8.2 M
 intel-openmp-19.0.2-187                                                             x86_64                         19.0.2-187                          intel-mkl-repo                         2.5 M
 intel-psxe-common-2019.2-057                                                        noarch                         2019.2-057                          intel-mkl-repo                         8.0 k
 intel-psxe-common-doc-2019                                                          noarch                         2019.5-075                          intel-mkl-repo                         6.9 k
 intel-tbb-libs-2019.2-187                                                           x86_64                         2019.2-187                          intel-mkl-repo                         2.6 M

Transaction Summary
=====================================================================================================================================================================================================
Install  43 Packages

Total download size: 545 M
Installed size: 1.8 G
Downloading Packages:
(1/43): intel-comp-nomcu-vars-19.0.2-187-19.0.2-187.noarch.rpm                                                                                                       8.8 kB/s | 8.8 kB     00:01    
(2/43): intel-comp-l-all-vars-19.0.2-187-19.0.2-187.noarch.rpm                                                                                                        12 kB/s |  12 kB     00:01    
(3/43): intel-conda-intel-openmp-linux-64-shadow-package-2019.2-187-2019.2-187.x86_64.rpm                                                                             19 kB/s |  10 kB     00:00    
(4/43): intel-conda-mkl-devel-linux-64-shadow-package-2019.2-187-2019.2-187.x86_64.rpm                                                                                19 kB/s |  10 kB     00:00    
(5/43): intel-conda-mkl-include-linux-64-shadow-package-2019.2-187-2019.2-187.x86_64.rpm                                                                              20 kB/s |  11 kB     00:00    
(6/43): intel-conda-mkl-linux-64-shadow-package-2019.2-187-2019.2-187.x86_64.rpm                                                                                      19 kB/s |  11 kB     00:00    
(7/43): intel-conda-mkl-static-linux-64-shadow-package-2019.2-187-2019.2-187.x86_64.rpm                                                                               20 kB/s |  11 kB     00:00    
(8/43): intel-conda-tbb-linux-64-shadow-package-2019.2-187-2019.2-187.x86_64.rpm                                                                                      17 kB/s |  10 kB     00:00    
(9/43): intel-mkl-64bit-2019.2-057-2019.2-057.x86_64.rpm                                                                                                             7.8 kB/s | 5.0 kB     00:00    
(10/43): intel-mkl-cluster-c-2019.2-187-2019.2-187.noarch.rpm                                                                                                        3.6 kB/s | 2.1 kB     00:00    
(11/43): intel-mkl-cluster-f-2019.2-187-2019.2-187.noarch.rpm                                                                                                        3.6 kB/s | 2.1 kB     00:00    
(12/43): intel-mkl-cluster-2019.2-187-2019.2-187.x86_64.rpm                                                                                                          234 kB/s | 7.5 MB     00:32    
(13/43): intel-mkl-cluster-rt-2019.2-187-2019.2-187.x86_64.rpm                                                                                                       200 kB/s | 6.3 MB     00:32    
(14/43): intel-mkl-common-2019.2-187-2019.2-187.noarch.rpm                                                                                                            73 kB/s | 101 kB     00:01    
(15/43): intel-mkl-common-c-ps-2019.2-187-2019.2-187.noarch.rpm                                                                                                      100 kB/s |  72 kB     00:00    
(16/43): intel-mkl-common-c-2019.2-187-2019.2-187.noarch.rpm                                                                                                         200 kB/s | 1.8 MB     00:09    
(17/43): intel-mkl-common-ps-2019.2-187-2019.2-187.noarch.rpm                                                                                                         58 kB/s |  81 kB     00:01    
(18/43): intel-mkl-common-f-2019.2-187-2019.2-187.noarch.rpm                                                                                                         212 kB/s | 2.1 MB     00:10    
(19/43): intel-mkl-core-c-2019.2-187-2019.2-187.x86_64.rpm                                                                                                           4.2 kB/s | 2.2 kB     00:00    
(20/43): intel-mkl-core-f-2019.2-187-2019.2-187.x86_64.rpm                                                                                                           3.9 kB/s | 2.2 kB     00:00    
(21/43): intel-conda-index-tool-19.0.2-187-19.0.2-187.x86_64.rpm                                                                                                     223 kB/s |  13 MB     00:57    
(22/43): intel-mkl-core-ps-2019.2-187-2019.2-187.x86_64.rpm                                                                                                          208 kB/s |  10 MB     00:51    
(23/43): intel-mkl-doc-2019-2019.5-281.noarch.rpm                                                                                                                     25 kB/s |  13 kB     00:00    
(24/43): intel-mkl-doc-ps-2019-2019.5-281.noarch.rpm                                                                                                                 132 kB/s | 213 kB     00:01    
(25/43): intel-mkl-f95-2019.2-187-2019.2-187.x86_64.rpm                                                                                                              203 kB/s | 4.9 MB     00:24    
(26/43): intel-mkl-f95-common-2019.2-187-2019.2-187.noarch.rpm                                                                                                       158 kB/s | 410 kB     00:02    
(27/43): intel-mkl-gnu-2019.2-187-2019.2-187.x86_64.rpm                                                                                                              204 kB/s | 8.0 MB     00:40    
(28/43): intel-mkl-gnu-c-2019.2-187-2019.2-187.x86_64.rpm                                                                                                            3.9 kB/s | 2.2 kB     00:00    
(29/43): intel-mkl-gnu-f-2019.2-187-2019.2-187.x86_64.rpm                                                                                                            203 kB/s | 5.2 MB     00:26    
(30/43): intel-mkl-gnu-f-rt-2019.2-187-2019.2-187.x86_64.rpm                                                                                                         200 kB/s | 4.9 MB     00:25    
(31/43): intel-mkl-gnu-rt-2019.2-187-2019.2-187.x86_64.rpm                                                                                                           200 kB/s | 7.3 MB     00:37    
(32/43): intel-mkl-pgi-2019.2-187-2019.2-187.x86_64.rpm                                                                                                              204 kB/s |  13 MB     01:03    
(33/43): intel-mkl-pgi-c-2019.2-187-2019.2-187.x86_64.rpm                                                                                                            2.4 kB/s | 2.2 kB     00:00    
(34/43): intel-mkl-pgi-rt-2019.2-187-2019.2-187.x86_64.rpm                                                                                                           204 kB/s |  11 MB     00:53    
(35/43): intel-mkl-psxe-2019.2-057-2019.2-057.noarch.rpm                                                                                                             4.6 kB/s | 3.6 kB     00:00    
(36/43): intel-mkl-tbb-2019.2-187-2019.2-187.x86_64.rpm                                                                                                              205 kB/s | 9.5 MB     00:47    
(37/43): intel-mkl-tbb-rt-2019.2-187-2019.2-187.x86_64.rpm                                                                                                           204 kB/s | 8.2 MB     00:41    
(38/43): intel-openmp-19.0.2-187-19.0.2-187.x86_64.rpm                                                                                                               196 kB/s | 2.5 MB     00:13    
(39/43): intel-psxe-common-2019.2-057-2019.2-057.noarch.rpm                                                                                                          9.8 kB/s | 8.0 kB     00:00    
(40/43): intel-psxe-common-doc-2019-2019.5-075.noarch.rpm                                                                                                             14 kB/s | 6.9 kB     00:00    
(41/43): intel-tbb-libs-2019.2-187-2019.2-187.x86_64.rpm                                                                                                             197 kB/s | 2.6 MB     00:13    
(42/43): intel-mkl-core-rt-2019.2-187-2019.2-187.x86_64.rpm                                                                                                          257 kB/s | 210 MB     13:56    
(43/43): intel-mkl-core-2019.2-187-2019.2-187.x86_64.rpm                                                                                                             261 kB/s | 217 MB     14:12    
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Total                                                                                                                                                                620 kB/s | 545 MB     15:00     
warning: /var/cache/dnf/intel-mkl-repo-92b021b91e7ff902/packages/intel-comp-l-all-vars-19.0.2-187-19.0.2-187.noarch.rpm: Header V4 RSA/SHA256 Signature, key ID 1911e097: NOKEY
Intel(R) Math Kernel Library                                                                                                                                         1.8 kB/s | 939  B     00:00    
Importing GPG key 0x7E6C5DBE:
 Userid     : "Intel(R) Software Development Products"
 Fingerprint: 52AB D6E8 7E42 1793 9718 73FF ACFA 9FC5 7E6C 5DBE
 From       : https://yum.repos.intel.com/mkl/setup/PUBLIC_KEY.PUB
Key imported successfully
Import of key(s) didn't help, wrong key(s)?
Public key for intel-comp-l-all-vars-19.0.2-187-19.0.2-187.noarch.rpm is not installed. Failing package is: intel-comp-l-all-vars-19.0.2-187-19.0.2-187.noarch
 GPG Keys are configured as: https://yum.repos.intel.com/mkl/setup/PUBLIC_KEY.PUB
Public key for intel-comp-nomcu-vars-19.0.2-187-19.0.2-187.noarch.rpm is not installed. Failing package is: intel-comp-nomcu-vars-19.0.2-187-19.0.2-187.noarch
 GPG Keys are configured as: https://yum.repos.intel.com/mkl/setup/PUBLIC_KEY.PUB
Public key for intel-conda-index-tool-19.0.2-187-19.0.2-187.x86_64.rpm is not installed. Failing package is: intel-conda-index-tool-19.0.2-187-19.0.2-187.x86_64
 GPG Keys are configured as: https://yum.repos.intel.com/mkl/setup/PUBLIC_KEY.PUB
Public key for intel-conda-intel-openmp-linux-64-shadow-package-2019.2-187-2019.2-187.x86_64.rpm is not installed. Failing package is: intel-conda-intel-openmp-linux-64-shadow-package-2019.2-187-2019.2-187.x86_64
 GPG Keys are configured as: https://yum.repos.intel.com/mkl/setup/PUBLIC_KEY.PUB
Public key for intel-conda-mkl-devel-linux-64-shadow-package-2019.2-187-2019.2-187.x86_64.rpm is not installed. Failing package is: intel-conda-mkl-devel-linux-64-shadow-package-2019.2-187-2019.2-187.x86_64
 GPG Keys are configured as: https://yum.repos.intel.com/mkl/setup/PUBLIC_KEY.PUB
Public key for intel-conda-mkl-include-linux-64-shadow-package-2019.2-187-2019.2-187.x86_64.rpm is not installed. Failing package is: intel-conda-mkl-include-linux-64-shadow-package-2019.2-187-2019.2-187.x86_64
 GPG Keys are configured as: https://yum.repos.intel.com/mkl/setup/PUBLIC_KEY.PUB
Public key for intel-conda-mkl-linux-64-shadow-package-2019.2-187-2019.2-187.x86_64.rpm is not installed. Failing package is: intel-conda-mkl-linux-64-shadow-package-2019.2-187-2019.2-187.x86_64
 GPG Keys are configured as: https://yum.repos.intel.com/mkl/setup/PUBLIC_KEY.PUB
Public key for intel-conda-mkl-static-linux-64-shadow-package-2019.2-187-2019.2-187.x86_64.rpm is not installed. Failing package is: intel-conda-mkl-static-linux-64-shadow-package-2019.2-187-2019.2-187.x86_64
 GPG Keys are configured as: https://yum.repos.intel.com/mkl/setup/PUBLIC_KEY.PUB
Public key for intel-conda-tbb-linux-64-shadow-package-2019.2-187-2019.2-187.x86_64.rpm is not installed. Failing package is: intel-conda-tbb-linux-64-shadow-package-2019.2-187-2019.2-187.x86_64
 GPG Keys are configured as: https://yum.repos.intel.com/mkl/setup/PUBLIC_KEY.PUB
Public key for intel-mkl-64bit-2019.2-057-2019.2-057.x86_64.rpm is not installed. Failing package is: intel-mkl-64bit-2019.2-057-2019.2-057.x86_64
 GPG Keys are configured as: https://yum.repos.intel.com/mkl/setup/PUBLIC_KEY.PUB
Public key for intel-mkl-cluster-2019.2-187-2019.2-187.x86_64.rpm is not installed. Failing package is: intel-mkl-cluster-2019.2-187-2019.2-187.x86_64
 GPG Keys are configured as: https://yum.repos.intel.com/mkl/setup/PUBLIC_KEY.PUB
Public key for intel-mkl-cluster-c-2019.2-187-2019.2-187.noarch.rpm is not installed. Failing package is: intel-mkl-cluster-c-2019.2-187-2019.2-187.noarch
 GPG Keys are configured as: https://yum.repos.intel.com/mkl/setup/PUBLIC_KEY.PUB
Public key for intel-mkl-cluster-f-2019.2-187-2019.2-187.noarch.rpm is not installed. Failing package is: intel-mkl-cluster-f-2019.2-187-2019.2-187.noarch
 GPG Keys are configured as: https://yum.repos.intel.com/mkl/setup/PUBLIC_KEY.PUB
Public key for intel-mkl-cluster-rt-2019.2-187-2019.2-187.x86_64.rpm is not installed. Failing package is: intel-mkl-cluster-rt-2019.2-187-2019.2-187.x86_64
 GPG Keys are configured as: https://yum.repos.intel.com/mkl/setup/PUBLIC_KEY.PUB
Public key for intel-mkl-common-2019.2-187-2019.2-187.noarch.rpm is not installed. Failing package is: intel-mkl-common-2019.2-187-2019.2-187.noarch
 GPG Keys are configured as: https://yum.repos.intel.com/mkl/setup/PUBLIC_KEY.PUB
Public key for intel-mkl-common-c-2019.2-187-2019.2-187.noarch.rpm is not installed. Failing package is: intel-mkl-common-c-2019.2-187-2019.2-187.noarch
 GPG Keys are configured as: https://yum.repos.intel.com/mkl/setup/PUBLIC_KEY.PUB
Public key for intel-mkl-common-c-ps-2019.2-187-2019.2-187.noarch.rpm is not installed. Failing package is: intel-mkl-common-c-ps-2019.2-187-2019.2-187.noarch
 GPG Keys are configured as: https://yum.repos.intel.com/mkl/setup/PUBLIC_KEY.PUB
Public key for intel-mkl-common-f-2019.2-187-2019.2-187.noarch.rpm is not installed. Failing package is: intel-mkl-common-f-2019.2-187-2019.2-187.noarch
 GPG Keys are configured as: https://yum.repos.intel.com/mkl/setup/PUBLIC_KEY.PUB
Public key for intel-mkl-common-ps-2019.2-187-2019.2-187.noarch.rpm is not installed. Failing package is: intel-mkl-common-ps-2019.2-187-2019.2-187.noarch
 GPG Keys are configured as: https://yum.repos.intel.com/mkl/setup/PUBLIC_KEY.PUB
Public key for intel-mkl-core-2019.2-187-2019.2-187.x86_64.rpm is not installed. Failing package is: intel-mkl-core-2019.2-187-2019.2-187.x86_64
 GPG Keys are configured as: https://yum.repos.intel.com/mkl/setup/PUBLIC_KEY.PUB
Public key for intel-mkl-core-c-2019.2-187-2019.2-187.x86_64.rpm is not installed. Failing package is: intel-mkl-core-c-2019.2-187-2019.2-187.x86_64
 GPG Keys are configured as: https://yum.repos.intel.com/mkl/setup/PUBLIC_KEY.PUB
Public key for intel-mkl-core-f-2019.2-187-2019.2-187.x86_64.rpm is not installed. Failing package is: intel-mkl-core-f-2019.2-187-2019.2-187.x86_64
 GPG Keys are configured as: https://yum.repos.intel.com/mkl/setup/PUBLIC_KEY.PUB
Public key for intel-mkl-core-ps-2019.2-187-2019.2-187.x86_64.rpm is not installed. Failing package is: intel-mkl-core-ps-2019.2-187-2019.2-187.x86_64
 GPG Keys are configured as: https://yum.repos.intel.com/mkl/setup/PUBLIC_KEY.PUB
Public key for intel-mkl-core-rt-2019.2-187-2019.2-187.x86_64.rpm is not installed. Failing package is: intel-mkl-core-rt-2019.2-187-2019.2-187.x86_64
 GPG Keys are configured as: https://yum.repos.intel.com/mkl/setup/PUBLIC_KEY.PUB
Public key for intel-mkl-doc-2019-2019.5-281.noarch.rpm is not installed. Failing package is: intel-mkl-doc-2019-2019.5-281.noarch
 GPG Keys are configured as: https://yum.repos.intel.com/mkl/setup/PUBLIC_KEY.PUB
Public key for intel-mkl-doc-ps-2019-2019.5-281.noarch.rpm is not installed. Failing package is: intel-mkl-doc-ps-2019-2019.5-281.noarch
 GPG Keys are configured as: https://yum.repos.intel.com/mkl/setup/PUBLIC_KEY.PUB
Public key for intel-mkl-f95-2019.2-187-2019.2-187.x86_64.rpm is not installed. Failing package is: intel-mkl-f95-2019.2-187-2019.2-187.x86_64
 GPG Keys are configured as: https://yum.repos.intel.com/mkl/setup/PUBLIC_KEY.PUB
Public key for intel-mkl-f95-common-2019.2-187-2019.2-187.noarch.rpm is not installed. Failing package is: intel-mkl-f95-common-2019.2-187-2019.2-187.noarch
 GPG Keys are configured as: https://yum.repos.intel.com/mkl/setup/PUBLIC_KEY.PUB
Public key for intel-mkl-gnu-2019.2-187-2019.2-187.x86_64.rpm is not installed. Failing package is: intel-mkl-gnu-2019.2-187-2019.2-187.x86_64
 GPG Keys are configured as: https://yum.repos.intel.com/mkl/setup/PUBLIC_KEY.PUB
Public key for intel-mkl-gnu-c-2019.2-187-2019.2-187.x86_64.rpm is not installed. Failing package is: intel-mkl-gnu-c-2019.2-187-2019.2-187.x86_64
 GPG Keys are configured as: https://yum.repos.intel.com/mkl/setup/PUBLIC_KEY.PUB
Public key for intel-mkl-gnu-f-2019.2-187-2019.2-187.x86_64.rpm is not installed. Failing package is: intel-mkl-gnu-f-2019.2-187-2019.2-187.x86_64
 GPG Keys are configured as: https://yum.repos.intel.com/mkl/setup/PUBLIC_KEY.PUB
Public key for intel-mkl-gnu-f-rt-2019.2-187-2019.2-187.x86_64.rpm is not installed. Failing package is: intel-mkl-gnu-f-rt-2019.2-187-2019.2-187.x86_64
 GPG Keys are configured as: https://yum.repos.intel.com/mkl/setup/PUBLIC_KEY.PUB
Public key for intel-mkl-gnu-rt-2019.2-187-2019.2-187.x86_64.rpm is not installed. Failing package is: intel-mkl-gnu-rt-2019.2-187-2019.2-187.x86_64
 GPG Keys are configured as: https://yum.repos.intel.com/mkl/setup/PUBLIC_KEY.PUB
Public key for intel-mkl-pgi-2019.2-187-2019.2-187.x86_64.rpm is not installed. Failing package is: intel-mkl-pgi-2019.2-187-2019.2-187.x86_64
 GPG Keys are configured as: https://yum.repos.intel.com/mkl/setup/PUBLIC_KEY.PUB
Public key for intel-mkl-pgi-c-2019.2-187-2019.2-187.x86_64.rpm is not installed. Failing package is: intel-mkl-pgi-c-2019.2-187-2019.2-187.x86_64
 GPG Keys are configured as: https://yum.repos.intel.com/mkl/setup/PUBLIC_KEY.PUB
Public key for intel-mkl-pgi-rt-2019.2-187-2019.2-187.x86_64.rpm is not installed. Failing package is: intel-mkl-pgi-rt-2019.2-187-2019.2-187.x86_64
 GPG Keys are configured as: https://yum.repos.intel.com/mkl/setup/PUBLIC_KEY.PUB
Public key for intel-mkl-psxe-2019.2-057-2019.2-057.noarch.rpm is not installed. Failing package is: intel-mkl-psxe-2019.2-057-2019.2-057.noarch
 GPG Keys are configured as: https://yum.repos.intel.com/mkl/setup/PUBLIC_KEY.PUB
Public key for intel-mkl-tbb-2019.2-187-2019.2-187.x86_64.rpm is not installed. Failing package is: intel-mkl-tbb-2019.2-187-2019.2-187.x86_64
 GPG Keys are configured as: https://yum.repos.intel.com/mkl/setup/PUBLIC_KEY.PUB
Public key for intel-mkl-tbb-rt-2019.2-187-2019.2-187.x86_64.rpm is not installed. Failing package is: intel-mkl-tbb-rt-2019.2-187-2019.2-187.x86_64
 GPG Keys are configured as: https://yum.repos.intel.com/mkl/setup/PUBLIC_KEY.PUB
Public key for intel-openmp-19.0.2-187-19.0.2-187.x86_64.rpm is not installed. Failing package is: intel-openmp-19.0.2-187-19.0.2-187.x86_64
 GPG Keys are configured as: https://yum.repos.intel.com/mkl/setup/PUBLIC_KEY.PUB
Public key for intel-psxe-common-2019.2-057-2019.2-057.noarch.rpm is not installed. Failing package is: intel-psxe-common-2019.2-057-2019.2-057.noarch
 GPG Keys are configured as: https://yum.repos.intel.com/mkl/setup/PUBLIC_KEY.PUB
Public key for intel-psxe-common-doc-2019-2019.5-075.noarch.rpm is not installed. Failing package is: intel-psxe-common-doc-2019-2019.5-075.noarch
 GPG Keys are configured as: https://yum.repos.intel.com/mkl/setup/PUBLIC_KEY.PUB
Public key for intel-tbb-libs-2019.2-187-2019.2-187.x86_64.rpm is not installed. Failing package is: intel-tbb-libs-2019.2-187-2019.2-187.x86_64
 GPG Keys are configured as: https://yum.repos.intel.com/mkl/setup/PUBLIC_KEY.PUB
The downloaded packages were saved in cache until the next successful transaction.
You can remove cached packages by executing 'dnf clean packages'.
Error: GPG check FAILED
extras/install_mkl.sh: MKL package intel-mkl-64bit-2019.2-057 installation FAILED.

Please open an issue with us at https://github.com/kaldi-asr/kaldi/ if you
believe this is a bug.

**Comment by danpovey** [comment]
I am getting very frustrated with these issues, because this is an Intel bug, and Intel should be fixing it.  Intel is a highly profitable international corporation, and Kaldi is a volunteer-supported open source project, so I don't really see it as our job to fix their screw-ups.

But from here
https://software.intel.com/en-us/forums/intel-math-kernel-library/topic/821365
right at the end, someone suggests this:
```
sudo apt-key del 1911E097
wget -O- https://apt.repos.intel.com/intel-gpg-keys/GPG-PUB-KEY-INTEL-SW-PRODUCTS-2019.PUB | sudo apt-key add -
```
--




```

**Comment by fredjame** [comment]
Daniel Povey wrote:
>
> I am getting very frustrated with these issues, because this is an 
> Intel bug, and Intel should be fixing it. Intel is a highly profitable 
> international corporation, and Kaldi is a volunteer-supported open 
> source project, so I don't really see it as our job to fix their 
> screw-ups.
>
> But from here
> https://software.intel.com/en-us/forums/intel-math-kernel-library/topic/821365
> right at the end, someone suggests this:
>
> |sudo apt-key del 1911E097 wget 
> -O- https://apt.repos.intel.com/intel-gpg-keys/GPG-PUB-KEY-INTEL-SW-PRODUCTS-2019.PUB | sudo apt-key 
> add - |
>
> --
>
Thank you
Regards
Fred James

**Comment by aadps** [comment]
@fredjame I got a quick fix here. Can you try it out and let me know whether it works as intended? It is indeed an issue on the side of Intel. https://gist.github.com/aadps/d168de69d232794b2c8ad80974234ad4

**Comment by aadps** [comment]
#3839

**Comment by fredjame** [comment]
Thank you aadps ... worked very well (successfully installed intel_mkl_2020.0.088 with some files from 202.0.166, as it happened.  If being the newer version does not cause a problem, then I am off and running ... we shall see.  Thanks again.

**Comment by fredjame** [comment]
Thanks all, for your help

**Comment by aadps** [comment]
You're welcome.
