### ISSUE TITLE
Not sure if it is a bug or my problem - About calling copy-vector via scp file

### ISSUE THREAD

**Issue by underdogliu** [kaldi-asr/kaldi#3844]
Dear Dan & all,

Hey, I am running into a trouble on calling `copy-vector`. I have a file `ivector.scp` which looks like below:
```
a10 exp/infer/a10.ark
b7 exp/infer/b7.ark
b92 exp/infer/b92.ark
r86 exp/infer/r86.ark
......
```
when I call single ark file contained in the 2nd column of that scp file, `copy-vector` worked:
```
$ copy-vector ark:exp/infer/n44.ark ark,t:-
copy-vector ark:exp/infer/n44.ark ark,t:- 
n44  [ -5.857756e-05 1.69777 -0.5954993 -0.2163115 7.491659e-05 -0.000174443 0.3236308 0.1083593 0.3076224 0.2899188 0.6977482 -8.652792e-05 -0.7657671 0.8777006 -7.547576e-06 9.663134e-05 -3.642416e-05 
-0.0008078996 -4.823043e-05 0.1050148 0.4616246 
...
]
LOG (copy-vector[5.5.689-94cd]:main():copy-vector.cc:90) Copied 1 vectors.
```
But when calling such scp file, it got errors like below:
```
$ copy-vector scp:exp/infer/ivector.scp ark,t:-
copy-vector scp:exp/infer/ivector.scp ark,t:- 
ERROR (copy-vector[5.5.689-94cd]:Read():kaldi-vector.cc:1224) Failed to read vector from stream.  Expected "[" but got a10 File position at start is 0, currently 4
......
```
Theoretically such scp file should work as I believe it is in right format of `$utt $file_path`. so not sure if it is a bug or my own problem. Please help. Thank you!

**Comment by danpovey** [comment]
Just because the archive file is a valid archive file does not mean your scp file is a valid scp file: the archive file will start with the utterance-id, which invalidates the scp file.
You should write to `ark,scp` if you want to create a valid scp file for your ark files.

**Comment by underdogliu** [comment]
@danpovey Thanks for such prompt reply! Just after I posted I got the solution for my problem - like you said, I need to write to `ark,scp`, towards which I put multiple vectors into a single ark file. Not sure if it's the ideal solution but it solved my problem. Thanks for the hint!
