### ISSUE TITLE
How do I avoid  the error on "tar  sctk-2.4.10" command in "make" of kaldi build; 

### ISSUE THREAD

**Issue by sekigh** [kaldi-asr/kaldi#3867]
I git clone kaldi and do "./INSTALL" and also "make" for build. When I came to "make", it produced the following error ;

tar: sctk-2.4.10/src/hubscr/test1-sastt.base/sastt-case1.sys.rttm.filt.alignments/ICSI_20011030-1030_d*_NONE_1.html: open Fail: Protocol error

which is caused by the command in make;

tar xojf sctk-2.4.10-20151007-1312Z.tar.bz2 || \
tar --exclude '*NONE*html' -xvojf sctk-2.4.10-20151007-1312Z.tar.bz2

How do I avoid this error?

My environment;
NAME="Ubuntu"
VERSION="18.04.3 LTS (Bionic Beaver)"
Linux version 4.15.0-74-generic (buildd@lcy01-amd64-022) (gcc version 7.4.0 (Ubuntu 7.4.0-1ubuntu1~18.04.1)) #84-Ubuntu SMP Thu Dec 19 08:06:28 UTC 2019
g++ (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0

[log.txt](https://github.com/kaldi-asr/kaldi/files/4095219/log.txt)

**Comment by sekigh** [comment]
One additional information:
I followed ./INSTALLATION and make under .../kaldi/tools but not touched anything under .../kaldi/src.

**Comment by danpovey** [comment]
For future reference, it is likely a windows-share issue, discussed here previouly:  https://groups.google.com/forum/#!msg/kaldi-help/703POkAikiA/IWy4Gy83BAAJ

**Comment by sekigh** [comment]
Thank you for your response!  I followed the document you suggested.
First, I checked with another compress/uncompress tool the contents of sctk-2.4.10-20151007-1312Z.tar.bz2 created by make and found there is indeed an erroneous file with an asterisk. But I could not succeed in executing even manually;
        tar  --exclude '*NONE*html' -xvojf sctk-2.4.10-20151007-1312Z.tar.bz2 . 
It always fails with "file can not open". Luckily enough,  I confirmed that an uncompressed sctk-2.4.10 folder is created without that erroneous file somehow. 
Therefore, I manually execute   
        ln -s sctk-2.4.10 sctk
before I commented out in Makefile;
       #tar xojf sctk-$(SCTK_VERSION).tar.bz2 || \
        #tar --exclude *_NONE_1.html -xvojf sctk-$(SCTK_VERSION).tar.bz2
        #rm -rf sctk && ln -s sctk-$(SCTK_VERSION_PARTIAL) sctk 
and run that make.   
But I got  the following error message upon ln execution;
ln: symbolic link ' failed to create 'sctk': Read-only file
sctk-2.4.10 folder attribute is as follows;

drwxrwxrwx 1 root root    4096 10  7  2015 sctk-2.4.10/

No sctk is created yet in ..../ tools folder.
What is wrong with this?

**Comment by sekigh** [comment]
Sorry, this issue is still open!!

**Comment by danpovey** [comment]
the basic solution is, don't use a windows share...

**Comment by danpovey** [comment]
or if you do, ensure that soft links are enabled.  They may have a different name, like shortcuts or something.

**Comment by sekigh** [comment]
Sorry, I am confusing. I use a folder share between Windows10(Host OS) and Ubuntu(Guest OS) via VirtualBox for a few years. Is this what you call windows share ? I have not encountered any issue similar to this case. If possible, let me understand what is happening here?

**Comment by sekigh** [comment]
What I did in terms of command-line-InterfaceCLI) is only on ubuntu not on Windows.

**Comment by jtrmal** [comment]
Windows do not like some filename patterns i.e. when you try to store the
files on the share, they will reject to create the file (and return error).
I think this also relates to all files starting with . (dot) but I don't
recall exactly.
y.

**Comment by sekigh** [comment]
Thank you for clarifying the Windows issue. That is my first hearing. Windows10 sits behind ubuntu via Virtualbox in the case. I manipulate the input to the screen on only ubuntu.  But that action manipulates files on the shared folder between Ubuntu and Windows10. Is this case affected by issues you are talking about?

**Comment by sekigh** [comment]
Duplicate of #3867

**Comment by jtrmal** [comment]
I would probably just start manually testing what is the issue (i.e. tried to create the symbolic link manually)

**Comment by sekigh** [comment]
@jtrmal

Thank you for your help. I am looking forward to hearing from you.

sekigh

**Comment by jtrmal** [comment]
I was suggesting you should try to do it, not me :)
y.

**Comment by sekigh** [comment]
@ jtrmal,

 

As mentioned in the message a few days ago, which I retyped below, I already manually tried to link and failed;

“But I got the following error message upon ln execution;


ln: symbolic link ' failed to create 'sctk': Read-only file


And sctk-2.4.10 folder attribute is as follows;

drwxrwxrwx 1 root root 4096 10 7 2015 sctk-2.4.10/

No sctk is created yet in ..../ tools folder.”

So I am puzzled.

 

sekigh

**Comment by jtrmal** [comment]
If you cannot do the steps manually (I'd try to remove all sctk artifacts
and unpack it manually. Symlink does not have to be symolink, you can just
hard-copy everything) then it's hardly kaldi's fault, isn't it? I don't
have any idea what would be the problem if it doesn't work -but in that
case it's something with your setup. Perhaps try to create a disk volume
instead of windows share
Y.

**Comment by sekigh** [comment]
Thank you for your comments. I copied sctk from sctk-2.4.10 manually and started with "make" with a proper tweak in the makefile. Then it is now running. I am waiting for it to complete.

**Comment by sekigh** [comment]
@jtrmal,
There were two more link statements in the Makefile, which failed.  So I moved to a pure ubuntu machine and I executed "make" there, finding that no failure occurred. You are right!

**Comment by sekigh** [comment]
This issue is closed! Thank you a lot!
