### ISSUE TITLE
installing kaldi facing issue.

### ISSUE THREAD

**Issue by NarasimmanSaravana1994** [kaldi-asr/kaldi#3870]
While running make command .. I'm getting error ..

                                          ^
# --error 0x1 --
Makefile:32: recipe for target 'cu-kernels.o' failed
make[1]: *** [cu-kernels.o] Error 1
make[1]: Leaving directory '/home/administrator/kaldi/src/cudamatrix'
Makefile:136: recipe for target 'cudamatrix' failed
make: *** [cudamatrix] Error 2

My system using CUDA version 10.0 . Is there any issue in that or any other way ot install CUDA 10 supported installation step......

Thanks

**Comment by danpovey** [comment]
PR #3871 seems to be responsible for this.  I reverted it.  Through my email I'm seeing other comments in this PR but they don't appear here... github email can sometimes be unreliable.
