### ISSUE TITLE
Recipe for target 'cudafeat' failed

### ISSUE THREAD

**Issue by OhmVikrant** [kaldi-asr/kaldi#3879]
When I tried to build kaldi, I got the error: 

Makefile:136: recipe for target 'cudafeat' failed
make: *** [cudafeat] Error 2

There were also some warnings like: 

feature-online-cmvn-cuda.cu(90): warning: type qualifier is meaningless on cast type
feature-online-cmvn-cuda.cu(103): warning: type qualifier is meaningless on cast type

**Comment by danpovey** [comment]
Make sure your repo is up to date, last night there was a problem.
If it is up to date you need to show more of the output, the error is now
shown in what you pasted.

**Comment by OhmVikrant** [comment]
![Screenshot from 2020-01-26 12-32-40](https://user-images.githubusercontent.com/46784336/73131834-0259b080-4038-11ea-8598-c59c4a61c8b1.png)

**Comment by OhmVikrant** [comment]
My repo is up-to-date. I just updated it this morning before building again.

**Comment by danpovey** [comment]
Still not there.

**Comment by OhmVikrant** [comment]
What more do I need to show?

**Comment by jtrmal** [comment]
Those warnings will not cause the makefile failure. There was an error
before these..
Y.

**Comment by popcornell** [comment]
I have been able to reproduce the issue. 
Compiling fails for me for current version of master `1dcb70d`
 but everything is fine if i checkout to `fdb2d57 `. 

I am using CUDA 10.2 and I am on Ubuntu 18.04. 
I have attached the full logs for the installation process for `1dcb70d` below, hope it can be helpful:

[log_check_dependencies.log](https://github.com/kaldi-asr/kaldi/files/4116654/log_check_dependencies.log)
[make_tools.log](https://github.com/kaldi-asr/kaldi/files/4116657/make_tools.log)
[configure.log](https://github.com/kaldi-asr/kaldi/files/4116658/configure.log)
[make_depend.log](https://github.com/kaldi-asr/kaldi/files/4116659/make_depend.log)
[make.log](https://github.com/kaldi-asr/kaldi/files/4116660/make.log)

**Comment by jtrmal** [comment]
just run 'make' instead of 'make -j' or 'make -j 4' in src... Doing so,
the error should show at the end of the output
y.

**Comment by jtrmal** [comment]
oh and do not forget to redirect stderr...
y.

**Comment by jtrmal** [comment]
I was actually able to reproduce it, too -- to make it compile, use this
patch (i.e. just delete the last two o files from Makefile

diff --git a/src/cudafeat/Makefile b/src/cudafeat/Makefile
index 87fe172..a033579 100644
--- a/src/cudafeat/Makefile
+++ b/src/cudafeat/Makefile
@@ -10,8 +10,7 @@ TESTFILES =
 ifeq ($(CUDA), true)
   OBJFILES +=  feature-window-cuda.o feature-spectral-cuda.o
feature-online-cmvn-cuda.o \

 online-ivector-feature-cuda-kernels.o online-ivector-feature-cuda.o \
-
 online-cuda-feature-pipeline.o
src/cudafeat/feature-online-batched-cmvn-cuda.o \
-
 src/cudafeat/feature-online-batched-cmvn-cuda-kernels.o
+
 online-cuda-feature-pipeline.o
 endif

**Comment by danpovey** [comment]
@jtrmal I suspect the issue is the `src/cudafeat/` part of those filenames.  Can you please deal with this?  I am flying tonight.

**Comment by jtrmal** [comment]
Good catch, I didn't even realize they have path-names
y.

**Comment by popcornell** [comment]
thx Yenda, I've run with make as suggested, I doubt it would be helpful at this point if you have already been able to reproduce this issue, but i am gonna attach the logs just in case:

[make.stderr.log](https://github.com/kaldi-asr/kaldi/files/4117210/make.stderr.log)
[make_depend.stderr.log](https://github.com/kaldi-asr/kaldi/files/4117213/make_depend.stderr.log)

[make.stdout.log](https://github.com/kaldi-asr/kaldi/files/4117207/make.stdout.log)
[make_depend.stdout.log](https://github.com/kaldi-asr/kaldi/files/4117203/make_depend.stdout.log)

**Comment by jtrmal** [comment]
It's useful to confirm you have the same issue as I do -- thanks!
y.

**Comment by jtrmal** [comment]
Should be resolved now by #3883

**Comment by marthayifiru** [comment]
I am trying to compile kaldi using g++-7, cuda-10.0 on Ubuntu 18.04.2. I have got the following error:
feature-online-cmvn-cuda.cu(90): warning: type qualifier is meaningless on cast type
feature-online-cmvn-cuda.cu(103): warning: type qualifier is meaningless on cast type
...
and
cuda-decoder.cc: In destructor ‘virtual kaldi::cuda_decoder::CudaDecoder::~CudaDecoder()’:
../cudadecoder/cuda-decoder-common.h:125:39: warning: throw will always call terminate() [-Wterminate]
                                  false);                                  \
                                       ^
cuda-decoder.cc:305:3: note: in expansion of macro ‘KALDI_DECODER_CUDA_API_CHECK_ERROR’
   KALDI_DECODER_CUDA_API_CHECK_ERROR(cudaFreeHost(h_channels_counters_));
   ^
../cudadecoder/cuda-decoder-common.h:125:39: note: in C++11 destructors default to noexcept
                                  false);                                  \
                                       ^
cuda-decoder.cc:305:3: note: in expansion of macro ‘KALDI_DECODER_CUDA_API_CHECK_ERROR’
   KALDI_DECODER_CUDA_API_CHECK_ERROR(cudaFreeHost(h_channels_counters_));
   ^
../cudadecoder/cuda-decoder-common.h:125:39: warning: throw will always call terminate() [-Wterminate]
                                  false);                                  \
                                       ^
cuda-decoder.cc:306:3: note: in expansion of macro ‘KALDI_DECODER_CUDA_API_CHECK_ERROR’
   KALDI_DECODER_CUDA_API_CHECK_ERROR(
   ^
../cudadecoder/cuda-decoder-common.h:125:39: note: in C++11 destructors default to noexcept
                                  false);                                  \
                                       ^
cuda-decoder.cc:306:3: note: in expansion of macro ‘KALDI_DECODER_CUDA_API_CHECK_ERROR’
   KALDI_DECODER_CUDA_API_CHECK_ERROR(
   ^
../cudadecoder/cuda-decoder-common.h:125:39: warning: throw will always call terminate() [-Wterminate]
                                  false);                                  \
                                       ^
cuda-decoder.cc:308:3: note: in expansion of macro ‘KALDI_DECODER_CUDA_API_CHECK_ERROR’
   KALDI_DECODER_CUDA_API_CHECK_ERROR(cudaFreeHost(h_acoustic_cost_concat_));
   ^
../cudadecoder/cuda-decoder-common.h:125:39: note: in C++11 destructors default to noexcept
                                  false);                                  \
                                       ^
cuda-decoder.cc:308:3: note: in expansion of macro ‘KALDI_DECODER_CUDA_API_CHECK_ERROR’
   KALDI_DECODER_CUDA_API_CHECK_ERROR(cudaFreeHost(h_acoustic_cost_concat_));
   ^
../cudadecoder/cuda-decoder-common.h:125:39: warning: throw will always call terminate() [-Wterminate]
                                  false);                                  \
                                       ^
cuda-decoder.cc:309:3: note: in expansion of macro ‘KALDI_DECODER_CUDA_API_CHECK_ERROR’
   KALDI_DECODER_CUDA_API_CHECK_ERROR(cudaFreeHost(h_extra_prev_tokens_concat_));
   ^
../cudadecoder/cuda-decoder-common.h:125:39: note: in C++11 destructors default to noexcept
                                  false);                                  \
                                       ^
cuda-decoder.cc:309:3: note: in expansion of macro ‘KALDI_DECODER_CUDA_API_CHECK_ERROR’
   KALDI_DECODER_CUDA_API_CHECK_ERROR(cudaFreeHost(h_extra_prev_tokens_concat_));
   ^
../cudadecoder/cuda-decoder-common.h:125:39: warning: throw will always call terminate() [-Wterminate]
                                  false);                                  \
                                       ^
cuda-decoder.cc:310:3: note: in expansion of macro ‘KALDI_DECODER_CUDA_API_CHECK_ERROR’
   KALDI_DECODER_CUDA_API_CHECK_ERROR(cudaFreeHost(h_infotoken_concat_));
   ^
../cudadecoder/cuda-decoder-common.h:125:39: note: in C++11 destructors default to noexcept
                                  false);                                  \
                                       ^
cuda-decoder.cc:310:3: note: in expansion of macro ‘KALDI_DECODER_CUDA_API_CHECK_ERROR’
   KALDI_DECODER_CUDA_API_CHECK_ERROR(cudaFreeHost(h_infotoken_concat_));
   ^
../cudadecoder/cuda-decoder-common.h:125:39: warning: throw will always call terminate() [-Wterminate]
                                  false);                                  \
                                       ^
cuda-decoder.cc:311:3: note: in expansion of macro ‘KALDI_DECODER_CUDA_API_CHECK_ERROR’
   KALDI_DECODER_CUDA_API_CHECK_ERROR(
   ^
../cudadecoder/cuda-decoder-common.h:125:39: note: in C++11 destructors default to noexcept
                                  false);                                  \
                                       ^
cuda-decoder.cc:311:3: note: in expansion of macro ‘KALDI_DECODER_CUDA_API_CHECK_ERROR’
   KALDI_DECODER_CUDA_API_CHECK_ERROR(
   ^
../cudadecoder/cuda-decoder-common.h:125:39: warning: throw will always call terminate() [-Wterminate]
                                  false);                                  \
                                       ^
cuda-decoder.cc:313:3: note: in expansion of macro ‘KALDI_DECODER_CUDA_API_CHECK_ERROR’
   KALDI_DECODER_CUDA_API_CHECK_ERROR(cudaFreeHost(h_acoustic_cost_concat_tmp_));
   ^
../cudadecoder/cuda-decoder-common.h:125:39: note: in C++11 destructors default to noexcept
                                  false);                                  \
                                       ^
cuda-decoder.cc:313:3: note: in expansion of macro ‘KALDI_DECODER_CUDA_API_CHECK_ERROR’
   KALDI_DECODER_CUDA_API_CHECK_ERROR(cudaFreeHost(h_acoustic_cost_concat_tmp_));
   ^
../cudadecoder/cuda-decoder-common.h:125:39: warning: throw will always call terminate() [-Wterminate]
                                  false);                                  \
                                       ^
cuda-decoder.cc:314:3: note: in expansion of macro ‘KALDI_DECODER_CUDA_API_CHECK_ERROR’
   KALDI_DECODER_CUDA_API_CHECK_ERROR(
   ^
../cudadecoder/cuda-decoder-common.h:125:39: note: in C++11 destructors default to noexcept
                                  false);                                  \
                                       ^
cuda-decoder.cc:314:3: note: in expansion of macro ‘KALDI_DECODER_CUDA_API_CHECK_ERROR’
   KALDI_DECODER_CUDA_API_CHECK_ERROR(
   ^
../cudadecoder/cuda-decoder-common.h:125:39: warning: throw will always call terminate() [-Wterminate]
                                  false);                                  \
                                       ^
cuda-decoder.cc:316:3: note: in expansion of macro ‘KALDI_DECODER_CUDA_API_CHECK_ERROR’
   KALDI_DECODER_CUDA_API_CHECK_ERROR(cudaFreeHost(h_infotoken_concat_tmp_));
   ^
../cudadecoder/cuda-decoder-common.h:125:39: note: in C++11 destructors default to noexcept
                                  false);                                  \
                                       ^
cuda-decoder.cc:316:3: note: in expansion of macro ‘KALDI_DECODER_CUDA_API_CHECK_ERROR’
   KALDI_DECODER_CUDA_API_CHECK_ERROR(cudaFreeHost(h_infotoken_concat_tmp_));
   ^
../cudadecoder/cuda-decoder-common.h:125:39: warning: throw will always call terminate() [-Wterminate]
                                  false);                                  \
                                       ^
cuda-decoder.cc:318:3: note: in expansion of macro ‘KALDI_DECODER_CUDA_API_CHECK_ERROR’
   KALDI_DECODER_CUDA_API_CHECK_ERROR(cudaEventDestroy(nnet3_done_evt_));
   ^
../cudadecoder/cuda-decoder-common.h:125:39: note: in C++11 destructors default to noexcept
                                  false);                                  \
                                       ^
cuda-decoder.cc:318:3: note: in expansion of macro ‘KALDI_DECODER_CUDA_API_CHECK_ERROR’
   KALDI_DECODER_CUDA_API_CHECK_ERROR(cudaEventDestroy(nnet3_done_evt_));
   ^
../cudadecoder/cuda-decoder-common.h:125:39: warning: throw will always call terminate() [-Wterminate]
                                  false);                                  \
                                       ^
cuda-decoder.cc:319:3: note: in expansion of macro ‘KALDI_DECODER_CUDA_API_CHECK_ERROR’
   KALDI_DECODER_CUDA_API_CHECK_ERROR(cudaEventDestroy(d2h_copy_acoustic_evt_));
   ^
../cudadecoder/cuda-decoder-common.h:125:39: note: in C++11 destructors default to noexcept
                                  false);                                  \
                                       ^
cuda-decoder.cc:319:3: note: in expansion of macro ‘KALDI_DECODER_CUDA_API_CHECK_ERROR’
   KALDI_DECODER_CUDA_API_CHECK_ERROR(cudaEventDestroy(d2h_copy_acoustic_evt_));
   ^
../cudadecoder/cuda-decoder-common.h:125:39: warning: throw will always call terminate() [-Wterminate]
                                  false);                                  \
                                       ^
cuda-decoder.cc:320:3: note: in expansion of macro ‘KALDI_DECODER_CUDA_API_CHECK_ERROR’
   KALDI_DECODER_CUDA_API_CHECK_ERROR(cudaEventDestroy(d2h_copy_infotoken_evt_));
   ^
../cudadecoder/cuda-decoder-common.h:125:39: note: in C++11 destructors default to noexcept
                                  false);                                  \
                                       ^
cuda-decoder.cc:320:3: note: in expansion of macro ‘KALDI_DECODER_CUDA_API_CHECK_ERROR’
   KALDI_DECODER_CUDA_API_CHECK_ERROR(cudaEventDestroy(d2h_copy_infotoken_evt_));
   ^
../cudadecoder/cuda-decoder-common.h:125:39: warning: throw will always call terminate() [-Wterminate]
                                  false);                                  \
                                       ^
cuda-decoder.cc:321:3: note: in expansion of macro ‘KALDI_DECODER_CUDA_API_CHECK_ERROR’
   KALDI_DECODER_CUDA_API_CHECK_ERROR(
   ^
../cudadecoder/cuda-decoder-common.h:125:39: note: in C++11 destructors default to noexcept
                                  false);                                  \
                                       ^
cuda-decoder.cc:321:3: note: in expansion of macro ‘KALDI_DECODER_CUDA_API_CHECK_ERROR’
   KALDI_DECODER_CUDA_API_CHECK_ERROR(
   ^
../cudadecoder/cuda-decoder-common.h:125:39: warning: throw will always call terminate() [-Wterminate]
                                  false);                                  \
                                       ^
cuda-decoder.cc:323:3: note: in expansion of macro ‘KALDI_DECODER_CUDA_API_CHECK_ERROR’
   KALDI_DECODER_CUDA_API_CHECK_ERROR(
   ^
../cudadecoder/cuda-decoder-common.h:125:39: note: in C++11 destructors default to noexcept
                                  false);                                  \
                                       ^
cuda-decoder.cc:323:3: note: in expansion of macro ‘KALDI_DECODER_CUDA_API_CHECK_ERROR’
   KALDI_DECODER_CUDA_API_CHECK_ERROR(
   ^
../cudadecoder/cuda-decoder-common.h:125:39: warning: throw will always call terminate() [-Wterminate]
                                  false);                                  \
                                       ^
cuda-decoder.cc:325:3: note: in expansion of macro ‘KALDI_DECODER_CUDA_API_CHECK_ERROR’
   KALDI_DECODER_CUDA_API_CHECK_ERROR(cudaEventDestroy(lane_offsets_ready_evt_));
   ^
../cudadecoder/cuda-decoder-common.h:125:39: note: in C++11 destructors default to noexcept
                                  false);                                  \
                                       ^
cuda-decoder.cc:325:3: note: in expansion of macro ‘KALDI_DECODER_CUDA_API_CHECK_ERROR’
   KALDI_DECODER_CUDA_API_CHECK_ERROR(cudaEventDestroy(lane_offsets_ready_evt_));

I have tried what you have recommended above, that is commenting the last two o files from the make file, but it does not hep. I cloned kaldi on May 01, 2020.

Would you please help.
Best regards,

**Comment by jtrmal** [comment]
those are all just warnings, I think.
y.
