### ISSUE TITLE
Unable to compile the kaldi project with windows environment

### ISSUE THREAD

**Issue by Raman99444** [kaldi-asr/kaldi#3887]
Hi guys,

I have check out this repo for my learning purpose. But, I'm not able to compile all the projects. Some of the projects (nearly 13 projects) failed with the below error message. It would be nice someone gives me a direction on this.

![image](https://user-images.githubusercontent.com/7310263/73279492-3c32de80-4213-11ea-9355-d11694e2c290.png)

Thank you.

**Comment by jtrmal** [comment]
the portaudio missing is definitely OK (in the sense of being expected that
it fails)
For the other symbols, it seems the tests are not linked with some library
(but it actually looks like two libraries depending on what test)... try to
grep for the functions and then make sure the tests link against them, the
message logger might be kaldibase, but I'm not sure.
y.
