### ISSUE TITLE
Potential bug in the back propagation implementation of DropoutComponent

### ISSUE THREAD

**Issue by csukuangfj** [kaldi-asr/kaldi#3890]
The common approach to implement the back propagation of dropout is 
(1) keep a mask filled with 1s and 0s during the forward stage
(2) during the backward stage
```
if mask[i, j] == 1 then
  in_deriv[i, j] = out_deriv[i, j] ( multiplied by a scale depending on the forward stage)
else
  in_deriv[i, j] = 0
fi
```

But kaldi does not use a mask, it compares the output value against the input value to compute the `in_deriv`
```
if in_value[i, j] == 0 then
  in_deriv[i, j] = out_deriv[i, j]
else
  in_deriv[i, j] = out_value[i, j] / in_value[i, j] * out_deriv[i, j]
fi
```

The problem with kaldi's approach is that if `in_value[i, j] == 0` and it is dropped out,
its derivative `in_deriv[i, j]` is not zeroed out but is set to `out_deriv[i, j]`.

**Comment by danpovey** [comment]
That's perhaps not ideal but it's not really a practical concern or something that would affect the training of any network topology that I can imagine.  And it saves memory in some situations.  Closing the issue as I don't see it as a practical issue.
