### ISSUE TITLE
Recipe for target 'cudafeat' failed

### ISSUE THREAD

**Issue by DhruvaBansal00** [kaldi-asr/kaldi#3899]
I am receiving "recipe for target 'cudafeat' failed' but probably for reasons different than #3879. I have attached screenshots of where I think the error is being generated.
![Screenshot from 2020-01-31 18-23-46](https://user-images.githubusercontent.com/26373935/73581709-23ffd100-4458-11ea-9eac-214ec77bbd0e.png)
![Screenshot from 2020-01-31 18-23-11](https://user-images.githubusercontent.com/26373935/73581712-282bee80-4458-11ea-9740-01a321af99d8.png)

**Comment by DhruvaBansal00** [comment]
I was using g++ version 5.5. I tried using 4.8.5 and 4.9.4. It failed using those as well.

**Comment by DhruvaBansal00** [comment]
I tried changing to Intel MKL but that didn't help either.

**Comment by danpovey** [comment]
Please attach or paste the full output from compilation.  Your screenshot
has too little output.

**Comment by DhruvaBansal00** [comment]
#3669  has the same error as me. Hence, I degraded to 4.9 and tried building it again. This time it errored while building tools. Here is the output  - 
[toolsErr.txt](https://github.com/kaldi-asr/kaldi/files/4142106/toolsErr.txt)

**Comment by danpovey** [comment]
The error while building tools/ is probably due to not cleaning up before rebuilding.. `make` typically won't keep track of dependencies on the configuration.  Might need to remove the openfst dir.

@jtrmal what do you think about making cudafeat and cudafeatbin optional, since they are are a rarely used feature anyway?  They are causing a disproportionate amount of problems with compilation, i.e. disproportionate to how frequently they are used.  I think we should do that.

**Comment by danpovey** [comment]
@luitjens  might want to comment on this too.. I am concerned that other dirs may later depend on cudafeat/.

**Comment by DhruvaBansal00** [comment]
Tools built successfully this time :). However, I have a new error while building source. Here is the output - 
[srcError.txt](https://github.com/kaldi-asr/kaldi/files/4142113/srcError.txt)

**Comment by danpovey** [comment]
OK, I think this should be something that's fixable on our end.  Probably we need to change our operator + for float2 to be __host__ __device__ from just being __device__.  See if you can locate it, you could make a PR with the fix.  Or @luitjens or one of the other NVidia guys might be able to fix it.
```
thread/thread_operators.cuh(115): error: calling a __device__ function("operator+") from a __host__ __device__ function("operator()") is not allowed
          detected during:
            instantiation of "T cub::Sum::operator()(const T &, const T &) const [with T=float2]" 
```

**Comment by danpovey** [comment]
It's these lines, you may need to add __host__:
```
cudafeat/feature-online-batched-cmvn-cuda-kernels.cu:__device__ inline float2 operator-(const float2 &a, const float2 &b) {
cudafeat/feature-online-batched-cmvn-cuda-kernels.cu:__device__ inline float2 operator+(const float2 &a, const float2 &b) {
```

**Comment by DhruvaBansal00** [comment]
Think that worked for the feature-online-batched-cmvn-cuda-kernels.cu file. Now I am getting recipe for target 'feature-online-batched-ivector-cuda.o' failed. Here is the output: 
[srcError.txt](https://github.com/kaldi-asr/kaldi/files/4142123/srcError.txt)

**Comment by danpovey** [comment]
OK, the error is:
`feature-online-batched-ivector-cuda.cc:312:75: error: ‘cublasGemmStridedBatchedEx’ was not declared in this scope`
I imagine this could be to do with CUBLAS/Cuda toolkit versions.  But still, @jtrmal , I think we should make the compilation of all the CUDA decoding stuff optional and not done by default, since this is tripping up too many people.

**Comment by danpovey** [comment]
@DhruvaBansal00 please make a pull request with the __host__ fix!  If you can't, please let me know and I will have someone else do it.

**Comment by jtrmal** [comment]
I'll look into it this today or tomorrow.
Y.

**Comment by DhruvaBansal00** [comment]
Sure I'll make the pr asap

**Comment by luitjens** [comment]
We probably need a compiler guard for newer toolkit versions for this
code.  We already error out if you are not 9.2 or newer.  I’ll look at what
toolkit is required for gems strided and add a guard around those calls.

**Comment by danpovey** [comment]
Thanks!

**Comment by luitjens** [comment]
This should be fixed now.  Can you update and verify?

**Comment by DhruvaBansal00** [comment]
I tried building again. Here is the output - 
[src_output.txt](https://github.com/kaldi-asr/kaldi/files/4143682/src_output.txt)

I did see 
make[1]: *** [compute-online-feats-batched-cuda.o] Error 1
make[1]: Leaving directory '/home/thad/kaldi/src/cudafeatbin'
Makefile:136: recipe for target 'cudafeatbin' failed
make: *** [cudafeatbin] Error 2
in the middle. But nothing at the end. Is this alright?

**Comment by luitjens** [comment]
Ok I see the issue.  Will fix soon.  At some point you may want to upgrade
your cuda version.

**Comment by luitjens** [comment]
Please test this:

https://github.com/kaldi-asr/kaldi/pull/3903

**Comment by DhruvaBansal00** [comment]
Sorry about the delay. I'll check tonight!

**Comment by DhruvaBansal00** [comment]
I was able to install kaldi this time. Thanks!

**Comment by kli017** [comment]
![image](https://user-images.githubusercontent.com/14877573/73710483-1344a900-473f-11ea-97dd-7e232054c13b.png)

I have update the breach and still get the same problem. @luitjens

**Comment by luitjens** [comment]
This is not the same problem.  Please include full output of build.  Also
include cuda version you have.

**Comment by luitjens** [comment]
See here:
https://github.com/kaldi-asr/kaldi/issues/3669

**Comment by kli017** [comment]
my cuda version is 9.2 and here is the output of building src
[src_make_log.txt](https://github.com/kaldi-asr/kaldi/files/4151361/src_make_log.txt)

**Comment by luitjens** [comment]
See the bug I pointed at in the last email.  This is an mkl and gtc
compatibility issue. Can you upgrade or downgrade gcc?

**Comment by danpovey** [comment]
@jtrmal we should definitely make the cudafeat stuff optional... too many people are getting tripped up on this.

**Comment by jtrmal** [comment]
Yes.. i Will work on it today. I thought it got resolved by last patches,
so I  thought it's not necessary.
Y.

**Comment by kli017** [comment]
@luitjens  Thanks, upgrade gcc to 7 and build successfully

**Comment by luitjens** [comment]
Kai's issue wasn't with cudafeat directly but more a side effect of certain
includes.  The problem their was an incompatibility between gcc/icc/mkl.
The earlier issues were issues with supporting older toolkits that don't
have correct functionality.  What should probably be done is we don't
compile/make depend on cuda directories if cuda is not enabled.

**Comment by jtrmal** [comment]
OK, let me experiment with this.
Shouldn;'t be that hard --  but I'm flying tomorrow, so I will be quiet for
some time.
y.

**Comment by jtrmal** [comment]
I think this was resolved in parallel discussion, I'm closing this.
