### ISSUE TITLE
Functionality needed for sparse-matrix in nnet3

### ISSUE THREAD

**Issue by danpovey** [kaldi-asr/kaldi#39]
@chenguoguo   - doing this via issue request rather than email so we can track it better.
Could you add a couple of sparse-matrix things, please?  I need these for the nnet3 outer training code- they should be done for both CUDA and CPU based versions.
First, methods 
Real SparseMatrix::Sum() const;
and
Real SparseVector::Sum() const;
[we won't likely be using the SparseVector::Sum() in the CUDA version, so you don't have to implement that].
Secondly, you'll see a function declaration

template<typename Real>
Real TraceMatSmat(const CuMatrixBase<Real> &A,
                  const CuSparseMatrix<Real> &B,
                  MatrixTransposeType trans = kNoTrans);
in cu-sparse-matrix.h.  I'm going to need this implemented for the nnet3 training.  It's the kTrans case that I'll actually need (of course, implementing both is better if you have time).
Dan

**Comment by danpovey** [comment]
BTW, I recommend that in both cases you use a temporary CuVector whose size is the number of MatrixElements in the CuSparseMatrix.
The Sum() method of CuVector handles a bunch of logic, and it would be a hassle to have to replicate this.

**Comment by chenguoguo** [comment]
Got this one. I'm flying back to Baltimore tonight, will arrive tomorrow
noon. I may have to work on this after my arrival. I also have couple of
nnet3 things on my list that I haven't finished, I'll also finish those
asap.

Guoguo
--

**Comment by danpovey** [comment]
BTW, I have finished the nnet training code (nnet3bin/nnet-train) but its compilation fails with a linking errors right now due to these things not being implemented.

**Comment by chenguoguo** [comment]
OK thanks for the note.. Boarding in a few of minutes, I'll fix those
tomorrow.

Guoguo
