### ISSUE TITLE
ERROR (nnet3-chain-train[5.5.600~1-f1969]:AddVecVec():cu-vector.cc:572) cudaError_t 98 : "invalid device function" returned from 'cudaGetLastError()'

### ISSUE THREAD

**Issue by computervisionlearner** [kaldi-asr/kaldi#3920]
Dear Dan:
     I am an beginer of the kaldi, and starting learning the project "librispeech" in egs. But, when I go to the last step(local/chain/run_tdnn.sh), I got a error:
```
cudaError_t 98 : "invalid device function" returned from 'cudaGetLastError()'
```
I found the relevant answer, but it doesn't seem to work for me：
https://groups.google.com/forum/#!searchin/kaldi-help/%22invalid$20device$20function%22$20returned$20from$20$27cudaGetLastError()$27|sort:date/kaldi-help/QOj9mZroZI4/4d8V4nX0CQAJ。
I  run the program via queue.pl, with Driver Version: 440.33.01    CUDA Version: 10.2.
#### Error log
```
WARNING (nnet3-chain-train[5.5.600~1-f1969]:SelectGpuId():cu-device.cc:214) Waited 0 seconds before creating CUDA context
LOG (nnet3-chain-train[5.5.600~1-f1969]:SelectGpuId():cu-device.cc:223) CUDA setup operating under Compute Exclusive Mode.
LOG (nnet3-chain-train[5.5.600~1-f1969]:FinalizeActiveGpu():cu-device.cc:308) The active GPU is [0]: Tesla V100-PCIE-16GB       free:15563M, used:597M, total:16160M, free/total:0.963039 version 7.0
nnet3-copy '--edits=set-dropout-proportion name=* proportion=0.0' - -
nnet3-am-copy --raw=true --learning-rate=0.00045 --scale=1.0 exp/chain_cleaned/tdnn_1d_sp/0.mdl -
LOG (nnet3-am-copy[5.5.600~1-f1969]:main():nnet3-am-copy.cc:153) Copied neural net from exp/chain_cleaned/tdnn_1d_sp/0.mdl to raw format as -
LOG (nnet3-copy[5.5.600~1-f1969]:ReadEditConfig():nnet-utils.cc:1397) Set dropout proportions for 17 components.
ERROR (nnet3-chain-train[5.5.600~1-f1969]:AddVecVec():cu-vector.cc:572) cudaError_t 98 : "invalid device function" returned from 'cudaGetLastError()'

[ Stack-Trace: ]
/opt/Git/kaldi/src/lib/libkaldi-base.so(kaldi::MessageLogger::LogMessage() const+0x82c) [0x2ad3dc3702da]
nnet3-chain-train(kaldi::MessageLogger::LogAndThrow::operator=(kaldi::MessageLogger const&)+0x21) [0x411611]
/opt/Git/kaldi/src/lib/libkaldi-cudamatrix.so(kaldi::CuVectorBase<double>::AddVecVec(double, kaldi::CuVectorBase<double> const&, kaldi::CuVectorBase<double> const&, double)+0x1f7) [0x2ad3daa65313]
/opt/Git/kaldi/src/lib/libkaldi-nnet3.so(kaldi::nnet3::BatchNormComponent::Read(std::istream&, bool)+0x1bb) [0x2ad3da5d4a2d]
/opt/Git/kaldi/src/lib/libkaldi-nnet3.so(kaldi::nnet3::Component::ReadNew(std::istream&, bool)+0x117) [0x2ad3da59caab]
/opt/Git/kaldi/src/lib/libkaldi-nnet3.so(kaldi::nnet3::Nnet::Read(std::istream&, bool)+0xb61) [0x2ad3da6214a9]
nnet3-chain-train(main+0x5c8) [0x4101ae]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf0) [0x2ad3dd545830]
nnet3-chain-train(_start+0x29) [0x40fb19]

WARNING (nnet3-chain-train[5.5.600~1-f1969]:Close():kaldi-io.cc:515) Pipe nnet3-am-copy --raw=true --learning-rate=0.00045 --scale=1.0 exp/chain_cleaned/tdnn_1d_sp/0.mdl - |nnet3-copy --edits='set-dropout-proportion name=* proportion=0.0' - - | had nonzero return status 36096
kaldi::KaldiFatalError
```
#### kaldi.mk
         - # CUDA configuration
              CUDA = true
              CUDATKDIR = /usr/local/cuda
               CUDA_ARCH = -gencode arch=compute_30,code=sm_30 -gencode 
               arch=compute_35,code=sm_35 -gencode arch=compute_50,code=sm_50 -gencode 
               arch=compute_52,code=sm_52 -gencode arch=compute_60,code=sm_60 -gencode 
               arch=compute_61,code=sm_61 -gencode arch=compute_70,code=sm_70 -gencode 
               arch=compute_75,code=sm_75
#### Version of Kaldi:
        - Date:   Tue Dec 17 17:38:15 2019 -0800

Thank you !

**Comment by danpovey** [comment]
OK, that's odd because normally it would be an issue with the compute capability, but 7.0 (sm_70) is one of the values it's configured with.  (Of course, make sure that the code was compiled more recently than kaldi.mk was created... wouldn't be an issue with a fresh checkout).
Other than that, it might be a driver issue...have you successfully run other software with that GPU?

**Comment by computervisionlearner** [comment]
Thank you for your kind reply.&nbsp;&nbsp;
The reason for this problem is that I do not make clean before recompiling kaldi(the first time I compiled by using cuda&nbsp;7.5 ).&nbsp;


In addition, I find a very useful trick to check if the cuda is compatible with kaldi.&nbsp;
``` cd kaldi/src/nnet3bin
&nbsp; &nbsp; then, execute ./cuda-gpu-available
```

---Original---
