### ISSUE TITLE
I am now testing incremental decoder. A segment fault happens when using enable endpoint detection.

### ISSUE THREAD

**Issue by wenzhe15** [kaldi-asr/kaldi#3929]

**Comment by danpovey** [comment]
Bug fixes are good but you need to show a complete command line.  Preferably, of course, a test case with files is ideal, but at least show the command line.
I didn't realize there was an incremental decoder with endpoint detection.

**Comment by wenzhe15** [comment]
Maybe the end part of  LatticeIncrementalOnlineDecoderTpl<FST>::BestPathEnd() should be 
if (final_cost_out)
    *final_cost_out = best_final_cost; 
More than 
if (final_cost_out == NULL)
    *final_cost_out = best_final_cost;

**Comment by danpovey** [comment]
Yes, I just discussed that bug with someone on the list yesterday.
The same bug is in lattice-incremental-decoder.cc.
I asked some people at JHU to fix it but you could make a PR right now.

**Comment by wenzhe15** [comment]
People at JHU may fix it with lattice-incremental-decoder.cc together.

**Comment by naxingyu** [comment]
I found this yesterday and made #3927

**Comment by wenzhe15** [comment]
Great. I pulled the modified source.

**Comment by kkm000** [comment]
Fixed in #3927
