### ISSUE TITLE
nnet3 configuration scripts: log-softmax layer option

### ISSUE THREAD

**Issue by danpovey** [kaldi-asr/kaldi#393]
I'd like an option added so that when generating the nnet3 configs, we can add something like
 --include-log-softmax=false
to the python script's args, and it won't add that final layer.
This is for use in the 'chain' models, in which that final layer is not necessary.

@tomkocse, can you please work on this and have @vijayaditya check it?

**Comment by tomkocse** [comment]
OK, I am looking at it now

**Comment by tomkocse** [comment]
@vijayaditya , when the final layer is not added, is the output node still needed ?

**Comment by vijayaditya** [comment]
Yes the node would always have an output layer. Just set it to the final
affine component.

Vijay

**Comment by danpovey** [comment]
closing since done.
