### ISSUE TITLE
"ImportError: No module named concurrent.futures"

### ISSUE THREAD

**Issue by 13256701918** [kaldi-asr/kaldi#3931]
ImportError: No module named concurrent.futures

I can not solve this question, I installed concurrent and futures ,but it didn't work

**Comment by danpovey** [comment]
I don't find that anywhere in the Kaldi codebase.  You need to say what you
were doing, with what repo (presumably not Kaldi master).  We are not
magicians!

**Comment by 13256701918** [comment]
Sorry for my simple description        The envrionment is Centos 7,I have read your readme and download all neccessary packpages,but I still can not  run it successfully.

![image](https://user-images.githubusercontent.com/34874738/74512349-08f68c00-4f43-11ea-9fa7-0c51cc11df40.png)

It seems that I need download concurrent or futures ,however concurrent or futures have existed

![image](https://user-images.githubusercontent.com/34874738/74512518-6db1e680-4f43-11ea-8ffb-27031b5b69fb.png)
![image](https://user-images.githubusercontent.com/34874738/74512644-b2d61880-4f43-11ea-8d5a-6c7517b66d23.png)

**Comment by danpovey** [comment]
gstreamer is a separate project that I think has its own repo.  You need to
ask there.

**Comment by 13256701918** [comment]
sorry ,,,,
