### ISSUE TITLE
vector-sum --average option doesn't work

### ISSUE THREAD

**Issue by iiscleap** [kaldi-asr/kaldi#3941]
In the kaldi function vector-sum, there is an option --average which is supposed to output the average rather than sum. But even is the --average flag is set to true, it still computes the sum rather than average. Here's a sample output.

`$ echo '[ 1 2 3 ]'|copy-vector --binary=true - a.vec`
`copy-vector --binary=true - a.vec`
`LOG (copy-vector[5.5.490~1-b2f64]:main():copy-vector.cc:80) Copied vector to a.vec`

`$ echo '[ 4 5 6 ]'|copy-vector --binary=true - b.vec`
`copy-vector --binary=true - b.vec`
`LOG (copy-vector[5.5.490~1-b2f64]:main():copy-vector.cc:80) Copied vector to b.vec`

`$ vector-sum --average=true a.vec b.vec -`
` [ 5 7 9 ] `
`LOG (vector-sum[5.5.490~1-b2f64]:TypeThreeUsage():vector-sum.cc:175) Summed 2 vectors; wrote sum to standard output`

`$ vector-sum --average=false a.vec b.vec -`
` [ 5 7 9 ] `
`LOG (vector-sum[5.5.490~1-b2f64]:TypeThreeUsage():vector-sum.cc:175) Summed 2 vectors; wrote sum to standard output`

`$ vector-sum a.vec b.vec -`
` [ 5 7 9 ] `
`LOG (vector-sum[5.5.490~1-b2f64]:TypeThreeUsage():vector-sum.cc:175) Summed 2 vectors; wrote sum to standard output`

**Comment by danpovey** [comment]
The --average option may not have any effect when not dealing with
archives.  You could add that support and make a PR if you need it.
