### ISSUE TITLE
Bug in `ApproxEqual` used while testing

### ISSUE THREAD

**Issue by akshaysubr** [kaldi-asr/kaldi#3949]
The `ApproxEqual(float a, float b, float relative_tolerance = 0.001)` function used in testing, especially in `cudamatrix/cu-math-test` doesn't handle the case when `a` or `b` are exactly `0`. In such a case, the test will always fail even with machine epsilon level round off error:
```
predicted_objf_change= [ 0 0 0 0 0 ], measured_objf_change= [ -9.53674e-07 0 0 0 0 ]
```

Some way of regularizing this close to `0` would have less false negatives maybe? This scikit-learn PR has some good suggestions: https://github.com/scikit-learn/scikit-learn/pull/15007

**Comment by danpovey** [comment]
The way I handle this is to design tests such that both things would never naturally be zero.
Or explicitly code in a limit in the calling code.   It's hard to know what magnitude limit
to impose as we test things with a huge range of magnitudes.
Closing the issue as the function does what it
say it does... let me know if there is any specific testing code that needs to be changed.
