### ISSUE TITLE
Generate SHARED libraries?

### ISSUE THREAD

**Issue by jiapei100** [kaldi-asr/kaldi#3956]
Why **ONLY** **static** libraries are generated, instead of **dynamic** ones?
How to generate **SHARED** libraries instead?

I mean, is it better to let **cmake/gen_cmake_skeleton.py** generate **SHARED** libraries?

**Comment by danpovey** [comment]
OK, you are asking about the CMake build, I assume, not the normal build (based on `configure` then `make`).  @cloudhan perhaps you could comment?  I'm not a CMake expert.

**Comment by csukuangfj** [comment]
@jiapei100

You can use

```
cmake -DBUILD_SHARED_LIBS=ON  <with your current other options>
```

That is, add `-DBUILD_SHARED_LIBS=ON` while invoking `cmake`.

**Comment by danpovey** [comment]
Actually this is explained in cmake/INSTALL.md (which you should have read).

**Comment by jiapei100** [comment]
Should **-fPIC** be enabled by default for all packages?

```console
➜  build git:(master) ccmake -DBUILD_SHARED_LIBS=ON ../
➜  build git:(master) make -j8
...
/usr/bin/ld: CMakeFiles/sparse-matrix-test.dir/sparse-matrix-test.cc.o: relocation R_X86_64_PC32 against symbol `_ZNSt6vectorIN5kaldi12SparseVectorIfEESaIS2_EED1Ev' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: final link failed: Bad value
collect2: error: ld returned 1 exit status
src/matrix/CMakeFiles/sparse-matrix-test.dir/build.make:109: recipe for target 'src/matrix/sparse-matrix-test' failed
make[2]: *** [src/matrix/sparse-matrix-test] Error 1
make[2]: Leaving directory '....../Kaldi/kaldi/build_18.04'
CMakeFiles/Makefile2:2451: recipe for target 'src/matrix/CMakeFiles/sparse-matrix-test.dir/all' failed
make[1]: *** [src/matrix/CMakeFiles/sparse-matrix-test.dir/all] Error 2
```

**Comment by cloudhan** [comment]
https://github.com/kaldi-asr/kaldi/blob/88e7b85e2cc0c4822114850cb851d36e9ed5bc5a/CMakeLists.txt#L28

This line should have effect.

Have you cleaned you build directory (I assume first built static libraries an then switched to shared ones)?

**Comment by jiapei100** [comment]
Problem solved... Yes, you are right... I've got to rebuild everything from scratch by removing static cache...

**Comment by cloudhan** [comment]
I'd suggest you use ninja when applicable, `make` will fail to detect changes in some cases.

**Comment by danpovey** [comment]
@cloudhan unless there are instructions for that, people likely won't be
able to use it.
Feel free to add instructions in cmake/INSTALL.md, just make sure it's
clearly structured so it's
clear that it's an alternative to the make-based build.
