### ISSUE TITLE
Error in training xvector

### ISSUE THREAD

**Issue by youjilin** [kaldi-asr/kaldi#3977]
Hi Dan,
I got an error as below when I try to train the xvector. Do you know why this happens? Thanks!

./src/nnet3bin/nnet3-xvector-compute --use-gpu=no --min-chunk-size=25 --chunk-size=10000 --cache-capacity=64 xvector_tmp1 ark:xvector_tmp3 ark,scp:exp/xvector_nnet_1a/xvectors_voxceleb1_test/xvector.1.ark,exp/xvector_nnet_1a/xvectors_voxceleb1_test/xvector.scp
ERROR (nnet3-xvector-compute[5.5]:ExpectToken():io-funcs.cc:200) Failed to read token [started at file position -1], expected <Nnet3>

Regards,
Jim

**Comment by danpovey** [comment]
I'm sure that isn't all the error.
Likely either one of the inputs is empty, or you are accessing that data
from the wrong directory and there were relative pathnames in your scp
file, or it was moved.

**Comment by csukuangfj** [comment]
What is the output of

```
nnet3-am-info xvector_tmp1
```

Is `xvector_tmp1` a valid nnet3 model?

**Comment by youjilin** [comment]
Thanks for your reply. I'll check it. Thanks!

**Comment by youjilin** [comment]
./src/nnet3bin/nnet3-copy --nnet-config=exp/xvector_nnet_1a/extract.config exp/xvector_nnet_1a/final.raw - > xvector_tmp1
std::bad_alloc

I found a mistake on previous processing. The xvector_tmp1 is an empty file.

**Comment by youjilin** [comment]
I'm trying to fix the error. Thanks!

**Comment by youjilin** [comment]
Is this an out of memory error message?

**Comment by danpovey** [comment]
Yes.  I'm surprised that that command would generate such an error.  You
should get a stack trace using:

 gdb --args. <program> <args>
 (gdb) r
[wait for error]
 (gdb) bt
