### ISSUE TITLE
Failed to compile OpenFst

### ISSUE THREAD

**Issue by Arafat4341** [kaldi-asr/kaldi#3987]
Kaldi installation fails when OpenFst compilation starts. I get these errors:
`g++: internal compiler error: Killed (program cc1plus)

Makefile:518: recipe for target 'determinize.lo' failed
make[3]: *** [determinize.lo] Error 1
make[3]: Leaving directory '/home/ubuntu/espnet/kaldi/tools/openfst-1.6.7/src/script'

Makefile:358: recipe for target 'install-recursive' failed
make[2]: *** [install-recursive] Error 1
make[2]: Leaving directory '/home/ubuntu/espnet/kaldi/tools/openfst-1.6.7/src'

Makefile:414: recipe for target 'install-recursive' failed
make[1]: *** [install-recursive] Error 1
make[1]: Leaving directory '/home/ubuntu/espnet/kaldi/tools/openfst-1.6.7'
Makefile:71: recipe for target 'openfst_compiled' failed
make: *** [openfst_compiled] Error 2`

Please help! Thanks in advance!

**Comment by danpovey** [comment]
Probably too little memory.  Remove the "-j" option if you invoked make that way.  Otherwise use a larger machine.

**Comment by Arafat4341** [comment]
@danpovey Thanks a lot for responding. 
I didn't use -j
I used only `make` . And I am using an AWS EC2 instance with a single CPU.
So can you please tell me what to do now?

**Comment by csukuangfj** [comment]
What is the RAM size of you EC2 instance? Maybe it is too small.

**Comment by Arafat4341** [comment]
@csukuangfj It is a 1GB  t2.micro instance

**Comment by Arafat4341** [comment]
@csukuangfj @danpovey 
Is it too small for the task?
Please help!

**Comment by csukuangfj** [comment]
I am compiling it on my EC2 instance with 991 MB RAM. I remember it was compiled successfully.

**Comment by Arafat4341** [comment]
One more thing I'd like to bring to your notice, I found the following headers missing:
iostream
ostream
fstream
iomanip
map
list
vector
set
sstream

Like:
`checking for iostream usability: no
checking for iostream presence: no
checking for iostream : no
..................
..................

`

**Comment by Arafat4341** [comment]
@csukuangfj With a single CPU?

Please have a look to this: [](https://slack-files.com/TLL87418R-FV2EMHFA9-4997846310)

Would you kindly suggest me what should I do now?

**Comment by csukuangfj** [comment]
Please switch to a more powerful machine, both in CPU and RAM.

**Comment by Arafat4341** [comment]
@danpovey 
As @csukuangfj said he also used an ec2 instance with similar memory and successfully setup kaldi. So my machine seems fine. I mentioned other problems package usability issues. This is just an image: https://slack-files.com/TLL87418R-FV2EMHFA9-4997846310
Can you tell me where is the problem?

Would you kindly suggest me any way out?! I am struck in this problem for a week now!

**Comment by danpovey** [comment]
Please don't ask any more, you should get help from someone local.  This is not what our github issues are for and we are busy.

**Comment by Arafat4341** [comment]
@danpovey I am sorry for your troubles!

**Comment by RoxanaTapia** [comment]
Hi, removing the -j option worked for me. In the tools Makefile I'm using `OPENFST_VERSION ?= 1.4.1` and had to change the `SCTK_GITHASH = 2.4.10-20151007-1312Z` and obtain it from `https://www.openslr.org/resources/4/sctk-2.4.10-20151007-1312Z.tar.bz2`  because the git link is broken... Note that SCTK_GITHASH can be renamed because it doesn't call Github anymore also it's necessary to modify the sctk make commands. I'm using the gpu image `nvidia/cuda:10.0-cudnn7-devel-ubuntu16.04` . My modified SCTK make commands (lines 129-143): `sctk: sctk-$(SCTK_GITHASH).tar.bz2
	tar --exclude '*NONE*html' -xmaf sctk-$(SCTK_GITHASH).tar.bz2
	# rm -rf sctk-$(SCTK_GITHASH) sctk
	rm -rf sctk-$(SCTK_GITHASH).tar.bz2
	mv sctk-2.4.10 sctk-$(SCTK_GITHASH)
	ln -s sctk-$(SCTK_GITHASH) sctk
	# touch sctk-$(SCTK_GITHASH).tar.gz


sctk-$(SCTK_GITHASH).tar.bz2:
	if [ -d "$(DOWNLOAD_DIR)" ]; then \
	  cp -p "$(DOWNLOAD_DIR)/sctk-$(SCTK_GITHASH).tar.bz2" .; \
	else \
	  $(WGET) -nv -T 10 -t 3 -c https://www.openslr.org/resources/4/sctk-$(SCTK_GITHASH).tar.bz2; \
	fi`

**Comment by Naveenravi07** [comment]
@Arafat4341  Did you find any solutions ?

**Comment by danpovey** [comment]
@Naveenravi07 you need to be more specific what your problem was, it might not be the same.
