### ISSUE TITLE
wav-reverberate WaveData  output issue

### ISSUE THREAD

**Issue by CAIQT** [kaldi-asr/kaldi#3992]
In [wav-reverberate.cc](https://github.com/kaldi-asr/kaldi/blob/344cdcb060b7d563d86ba22ffa0a5b8a80659482/src/featbin/wav-reverberate.cc#L373), when preparing Output ko for out_wave,
`Output ko(output_wave_file, false);`
may be changed into:
`Output ko(output_wave_file, true, false);`
to write without header.

Without this,  suppose we read a wav file without doing any changes and save to another position, then the contents of the saved file and the original file will not be the same because of the extra header.

**Comment by danpovey** [comment]
I think you might be right... can you try changing it and verify that it doesn't break a recipe that uses it?  I am looking at the code and I am having a hard time seeing how it worked in the first place.

**Comment by danpovey** [comment]
... and also could you make a PR?  Let me know if you won't be able to do this and I can ask someone else.
