### ISSUE TITLE
4 gigs of Memory runs out

### ISSUE THREAD

**Issue by Arafat4341** [kaldi-asr/kaldi#3997]
I tried to install the docker image (for CPU) on a virtual machine locally. I gave my machine 4 gigs of RAM. The installation was going on for quite a long almost 3 and a half hours. But at last I get this:

`Error processing tar file(exit status 1): write /var/lib/apt/lists/deb.debian.org_debian_dists_stretch_main_binary-amd64_Packages.lz4:
no space left on device`

How much memory exactly Kaldi needs?

**Comment by danpovey** [comment]
It's disk space you need, not memory.

**Comment by Arafat4341** [comment]
@danpovey I gave 40 gbs of memory to it :( 
Do you have any recommendation?
Thanks for your response!
