### ISSUE TITLE
How to convert a .wav file to a .ark file? By MFCC or other algorithms?

### ISSUE THREAD

**Issue by mingmingtasd** [kaldi-asr/kaldi#4002]

**Comment by csukuangfj** [comment]
```bash
$ compute-mfcc-feats
compute-mfcc-feats

Create MFCC feature files.
Usage:  compute-mfcc-feats [options...] <wav-rspecifier> <feats-wspecifier>
```

The input is a `wav-rspecifier`. So you have to first create a script file from wavs.

For example, create a `wav.scp`:

```
hello /path/to/your/filename.wav
```

then you can use

```
compute-mfcc-feats scp:wav.scp ark,scp:feats.ark,feats.scp
```

----

I would recommend you using 
https://github.com/kaldi-asr/kaldi/blob/master/egs/wsj/s5/steps/make_mfcc.sh

**Comment by qindazhu** [comment]
BTW, instead of opening an issue, it's better if you could ask those questions on [kaldi-help](https://groups.google.com/forum/#!forum/kaldi-help)

**Comment by mingmingtasd** [comment]
OK, thank you very much!

**Comment by mingmingtasd** [comment]
Hi, I find that we usually keep 20~40 cepstrum coefficients as mcff features. But there is a [dev93_10.ark](https://download.01.org/openvinotoolkit/models_contrib/speech/kaldi/wsj_dnn5b_smbr/dev93_10.ark) in which saved a feature data matrix with 440 columns. The feature data with 440 columns can match the [model wsj_dnn5b_smbr](https://download.01.org/openvinotoolkit/models_contrib/speech/kaldi/wsj_dnn5b_smbr/)'s input shape (1*440). So how can I get the feature data with sepcific matrix column number? May I need to modify the options of compute-mfcc-feats?

**Comment by csukuangfj** [comment]
NO.

Please have a look at https://github.com/kaldi-asr/kaldi/blob/master/src/featbin/splice-feats.cc

**Comment by mingmingtasd** [comment]
Thanks for your support! I have tried successfully! And sorry to bother you with these naive questions  because I am really not familiar with kaldi and speech recognition. Thanks!
