### ISSUE TITLE
sclite compilation failed

### ISSUE THREAD

**Issue by ugrozkr** [kaldi-asr/kaldi#4011]
I try to compile 2.4.10 version of sctk on ubuntu 18 operating system. When make config part finished and make second part started then terminal shows following error:

make[2]: Leaving directory '/home/ugur/kaldi/tools/sctk-2.4.10/src'
make[1]: Leaving directory '/home/ugur/kaldi/tools/sctk-2.4.10'
touch sctk/.configured
cd sctk;
make CC="cc" CXX="g++" all && make install && make doc
make[1]: Entering directory '/home/ugur/kaldi/tools/sctk-2.4.10'
(mkdir -p bin)
(cd src; make all)
make[2]: Entering directory '/home/ugur/kaldi/tools/sctk-2.4.10/src'
(cd asclite; make all)
make[3]: Entering directory '/home/ugur/kaldi/tools/sctk-2.4.10/src/asclite'
(cd core; make all)
make[4]: Entering directory '/home/ugur/kaldi/tools/sctk-2.4.10/src/asclite/core'
make[4]: Nothing to be done for 'all'.
make[4]: Leaving directory '/home/ugur/kaldi/tools/sctk-2.4.10/src/asclite/core'
(cd test; make all)
make[4]: Entering directory '/home/ugur/kaldi/tools/sctk-2.4.10/src/asclite/test'
make[4]: Nothing to be done for 'all'.
make[4]: Leaving directory '/home/ugur/kaldi/tools/sctk-2.4.10/src/asclite/test'
make[3]: Leaving directory '/home/ugur/kaldi/tools/sctk-2.4.10/src/asclite'
(cd sclite; make all)
make[3]: Entering directory '/home/ugur/kaldi/tools/sctk-2.4.10/src/sclite'
make[3]: Nothing to be done for 'all'.
make[3]: Leaving directory '/home/ugur/kaldi/tools/sctk-2.4.10/src/sclite'
(cd rfilter1; make all)
make[3]: Entering directory '/home/ugur/kaldi/tools/sctk-2.4.10/src/rfilter1'
make[3]: Nothing to be done for 'all'.
make[3]: Leaving directory '/home/ugur/kaldi/tools/sctk-2.4.10/src/rfilter1'
(cd csrfilt; make all)
make[3]: Entering directory '/home/ugur/kaldi/tools/sctk-2.4.10/src/csrfilt'
make[3]: Nothing to be done for 'all'.
make[3]: Leaving directory '/home/ugur/kaldi/tools/sctk-2.4.10/src/csrfilt'
(cd chfilt; make all)
make[3]: Entering directory '/home/ugur/kaldi/tools/sctk-2.4.10/src/chfilt'
make[3]: Nothing to be done for 'all'.
make[3]: Leaving directory '/home/ugur/kaldi/tools/sctk-2.4.10/src/chfilt'
(cd hamzaNorm; make all)
make[3]: Entering directory '/home/ugur/kaldi/tools/sctk-2.4.10/src/hamzaNorm'
make[3]: Nothing to be done for 'all'.
make[3]: Leaving directory '/home/ugur/kaldi/tools/sctk-2.4.10/src/hamzaNorm'
(cd tanweenFilt; make all)
make[3]: Entering directory '/home/ugur/kaldi/tools/sctk-2.4.10/src/tanweenFilt'
make[3]: Nothing to be done for 'all'.
make[3]: Leaving directory '/home/ugur/kaldi/tools/sctk-2.4.10/src/tanweenFilt'
(cd acomp; make all)
make[3]: Entering directory '/home/ugur/kaldi/tools/sctk-2.4.10/src/acomp'
make[3]: Nothing to be done for 'all'.
make[3]: Leaving directory '/home/ugur/kaldi/tools/sctk-2.4.10/src/acomp'
(cd def_art; make all)
make[3]: Entering directory '/home/ugur/kaldi/tools/sctk-2.4.10/src/def_art'
make[3]: Nothing to be done for 'all'.
make[3]: Leaving directory '/home/ugur/kaldi/tools/sctk-2.4.10/src/def_art'
(cd hubscr; make all)
make[3]: Entering directory '/home/ugur/kaldi/tools/sctk-2.4.10/src/hubscr'
make[3]: Nothing to be done for 'all'.
make[3]: Leaving directory '/home/ugur/kaldi/tools/sctk-2.4.10/src/hubscr'
(cd utf_filt; make all)
make[3]: Entering directory '/home/ugur/kaldi/tools/sctk-2.4.10/src/utf_filt'
make[3]: Nothing to be done for 'all'.
make[3]: Leaving directory '/home/ugur/kaldi/tools/sctk-2.4.10/src/utf_filt'
(cd rttmSort; make all)
make[3]: Entering directory '/home/ugur/kaldi/tools/sctk-2.4.10/src/rttmSort'
make[3]: Nothing to be done for 'all'.
make[3]: Leaving directory '/home/ugur/kaldi/tools/sctk-2.4.10/src/rttmSort'
(cd rttm2ctm; make all)
make[3]: Entering directory '/home/ugur/kaldi/tools/sctk-2.4.10/src/rttm2ctm'
make[3]: Nothing to be done for 'all'.
make[3]: Leaving directory '/home/ugur/kaldi/tools/sctk-2.4.10/src/rttm2ctm'
(cd rttmSmooth; make all)
make[3]: Entering directory '/home/ugur/kaldi/tools/sctk-2.4.10/src/rttmSmooth'
make[3]: Nothing to be done for 'all'.
make[3]: Leaving directory '/home/ugur/kaldi/tools/sctk-2.4.10/src/rttmSmooth'
(cd spkr2sad; make all)
make[3]: Entering directory '/home/ugur/kaldi/tools/sctk-2.4.10/src/spkr2sad'
make[3]: Nothing to be done for 'all'.
make[3]: Leaving directory '/home/ugur/kaldi/tools/sctk-2.4.10/src/spkr2sad'
(cd mergectm2rttm; make all)
make[3]: Entering directory '/home/ugur/kaldi/tools/sctk-2.4.10/src/mergectm2rttm'
make[3]: Nothing to be done for 'all'.
make[3]: Leaving directory '/home/ugur/kaldi/tools/sctk-2.4.10/src/mergectm2rttm'
(cd align2html; make all)
make[3]: Entering directory '/home/ugur/kaldi/tools/sctk-2.4.10/src/align2html'
make[3]: Nothing to be done for 'all'.
make[3]: Leaving directory '/home/ugur/kaldi/tools/sctk-2.4.10/src/align2html'
(cd md-eval; make all)
make[3]: Entering directory '/home/ugur/kaldi/tools/sctk-2.4.10/src/md-eval'
make[3]: Nothing to be done for 'all'.
make[3]: Leaving directory '/home/ugur/kaldi/tools/sctk-2.4.10/src/md-eval'
(cd stm2rttm; make all)
make[3]: Entering directory '/home/ugur/kaldi/tools/sctk-2.4.10/src/stm2rttm'
make[3]: Nothing to be done for 'all'.
make[3]: Leaving directory '/home/ugur/kaldi/tools/sctk-2.4.10/src/stm2rttm'
(cd stmValidator; make all)
make[3]: Entering directory '/home/ugur/kaldi/tools/sctk-2.4.10/src/stmValidator'
perl buildInstallVersion.pl > stmValidator.pl
chmod +x stmValidator.pl
make[3]: Leaving directory '/home/ugur/kaldi/tools/sctk-2.4.10/src/stmValidator'
(cd rttmValidator; make all)
make[3]: Entering directory '/home/ugur/kaldi/tools/sctk-2.4.10/src/rttmValidator'
make[3]: Nothing to be done for 'all'.
make[3]: Leaving directory '/home/ugur/kaldi/tools/sctk-2.4.10/src/rttmValidator'
(cd ctmValidator; make all)
make[3]: Entering directory '/home/ugur/kaldi/tools/sctk-2.4.10/src/ctmValidator'
make[3]: Nothing to be done for 'all'.
make[3]: Leaving directory '/home/ugur/kaldi/tools/sctk-2.4.10/src/ctmValidator'
(cd slatreport; make all)
make[3]: Entering directory '/home/ugur/kaldi/tools/sctk-2.4.10/src/slatreport'
make[3]: Nothing to be done for 'all'.
make[3]: Leaving directory '/home/ugur/kaldi/tools/sctk-2.4.10/src/slatreport'
make[2]: Leaving directory '/home/ugur/kaldi/tools/sctk-2.4.10/src'
make[1]: Leaving directory '/home/ugur/kaldi/tools/sctk-2.4.10'
make[1]: Entering directory '/home/ugur/kaldi/tools/sctk-2.4.10'
(mkdir -p bin)
(cd src; make install)
make[2]: Entering directory '/home/ugur/kaldi/tools/sctk-2.4.10/src'
(cd asclite; make install)
make[3]: Entering directory '/home/ugur/kaldi/tools/sctk-2.4.10/src/asclite'
(cd core; make install)
make[4]: Entering directory '/home/ugur/kaldi/tools/sctk-2.4.10/src/asclite/core'
for p in asclite; do
/usr/bin/install $p /home/ugur/kaldi/tools/sctk/bin/$p;
done
make[4]: Leaving directory '/home/ugur/kaldi/tools/sctk-2.4.10/src/asclite/core'
(cd test; make install)
make[4]: Entering directory '/home/ugur/kaldi/tools/sctk-2.4.10/src/asclite/test'
make[4]: Nothing to be done for 'install'.
make[4]: Leaving directory '/home/ugur/kaldi/tools/sctk-2.4.10/src/asclite/test'
make[3]: Leaving directory '/home/ugur/kaldi/tools/sctk-2.4.10/src/asclite'
(cd sclite; make install)
make[3]: Entering directory '/home/ugur/kaldi/tools/sctk-2.4.10/src/sclite'
/bin/sh: 5: Syntax error: end of file unexpected (expecting "done")
makefile:171: recipe for target 'testinstalldirs' failed
make[3]: [testinstalldirs] Error 2 (ignored)
for p in sclite sc_stats rover sctkUnit; do
/usr/bin/install $p -prefi/home/ugur/kaldi/tools/sctk/bin/$p;
done
/usr/bin/install: geçersiz seçenek -- r
Try '/usr/bin/install --help' for more information.
/usr/bin/install: geçersiz seçenek -- r
Try '/usr/bin/install --help' for more information.
/usr/bin/install: geçersiz seçenek -- r
Try '/usr/bin/install --help' for more information.
/usr/bin/install: geçersiz seçenek -- r
Try '/usr/bin/install --help' for more information.
makefile:160: recipe for target 'install' failed
make[3]: *** [install] Error 1
make[3]: Leaving directory '/home/ugur/kaldi/tools/sctk-2.4.10/src/sclite'
makefile:12: recipe for target 'install' failed
make[2]: *** [install] Error 2
make[2]: Leaving directory '/home/ugur/kaldi/tools/sctk-2.4.10/src'
makefile:19: recipe for target 'install' failed
make[1]: *** [install] Error 2
make[1]: Leaving directory '/home/ugur/kaldi/tools/sctk-2.4.10'
Makefile:108: recipe for target 'sclite_compiled' failed
make: *** [sclite_compiled] Error 2

**Comment by jtrmal** [comment]
is it in virtual machine or on NFS?

**Comment by rtxm** [comment]
Same here, while compiling on my workstation :
```
make[3]: Leaving directory '/opt/kaldi/tools/sctk-2.4.10/src/asclite'
(cd sclite; make install)
make[3]: Entering directory '/opt/kaldi/tools/sctk-2.4.10/src/sclite'
/bin/sh: 5: Syntax error: end of file unexpected (expecting "done")
make[3]: [makefile:171: testinstalldirs] Error 2 (ignored)
for p in sclite sc_stats rover sctkUnit; do \
  /usr/bin/install $p /opt/kaldi/tools/sctk/bin/$p; \
done
make[3]: Leaving directory '/opt/kaldi/tools/sctk-2.4.10/src/sclite'
```

**Comment by danpovey** [comment]
Try making with -v for verbose, it may show more useful output.  Looks like
a variable is set wrong in a makefile

**Comment by kkm000** [comment]
> /usr/bin/install: geçersiz seçenek -- r

I suspect some of the programs did not like a UTF8 string. Try setting LC_ALL=C before running make.

FWIW, on Ubuntu you can instead `apt install sctk`, and add `/usr/lib/sctk/bin` to the PATH if you want to access the original tools, or copy them over. The Ubuntu version comes with an added top-level script `/usr/bin/sctk` which runs SCTK commands as subcommands, and which is not in the original NIST distribution. I think it was a bad packaging idea, but it it what it is.

```
$ dpkg -L sctk
/.
/usr
/usr/bin
/usr/bin/sctk  <== Non-standard script.
/usr/lib
/usr/lib/sctk
/usr/lib/sctk/bin <== All binaries are here.
/usr/lib/sctk/bin/acomp.pl
/usr/lib/sctk/bin/align2html.pl
/usr/lib/sctk/bin/asclite
 . . . 
$ sctk

sctk - frontend to the SCTK toolkit

USAGE:
       sctk [ command ] [ command_options ]
       sctk help [ command ]

EXAMPLES:
       sctk help
          Print a brief descriprion of the available
          commands.
       sctk help <command>
          Print help for <command>.
       sctk <command> [ command_options ]
          Executes <command> with the given options.
```

**Comment by kkm000** [comment]
I am closing this ticket for now. If you believe that your issue has not been addressed, please feel free to ping me, and I'll reopen it.
