### ISSUE TITLE
Can't compile Kaldi with most recent OpenBLAS version (v0.3.9, 1 march 2020)

### ISSUE THREAD

**Issue by bmilde** [kaldi-asr/kaldi#4013]
OpenBLAS released a new stable version 3 weeks ago (https://github.com/xianyi/OpenBLAS/archive/v0.3.9.tar.gz) that doesn't seem to be compatible with Kaldi anymore. I am using the newest Kaldi version on Ubuntu 18.04. I can compile Kaldi with a previous versionof OpenBLAS (0.3.8), but 0.3.9 gives this compilation error:

[... many more lines of the same... ]

/usr/include/c++/7/complex:1831:3: error: template with C linkage
   template<typename _Tp>
   ^~~~~~~~
/usr/include/c++/7/complex:1904:3: note: previous declaration ‘__complex__ float std::__complex_proj(__complex__ float)’
   __complex_proj(__complex__ float __z)
   ^~~~~~~~~~~~~~
/usr/include/c++/7/complex:1844:3: error: template with C linkage
   template<typename _Tp>
   ^~~~~~~~
/usr/include/c++/7/complex: At global scope:
/usr/include/c++/7/complex:1915:3: error: template with C linkage
   template<typename _Tp>
   ^~~~~~~~
/usr/include/c++/7/complex:1849:3: error: template with C linkage
   template<typename _Tp>
   ^~~~~~~~
/usr/include/c++/7/complex:1857:3: error: template with C linkage
   template<typename _Tp>
   ^~~~~~~~
/usr/include/c++/7/complex:1862:3: error: template with C linkage
   template<typename _Tp, typename _Up>
   ^~~~~~~~
/usr/include/c++/7/complex:1926:3: error: template with C linkage
   template<typename _Tp>
   ^~~~~~~~
/usr/include/c++/7/complex:1870:3: error: template with C linkage
   template<typename _Tp, typename _Up>
   ^~~~~~~~
/usr/include/c++/7/complex:1934:3: error: template with C linkage
   template<typename _Tp>
   ^~~~~~~~
/usr/include/c++/7/complex:1878:3: error: template with C linkage
   template<typename _Tp, typename _Up>
   ^~~~~~~~
/usr/include/c++/7/complex:1889:3: error: template with C linkage
   template<typename _Tp> std::complex<_Tp> proj(const std::complex<_Tp>&);
   ^~~~~~~~
/usr/include/c++/7/complex:1891:3: error: template with C linkage
   template<typename _Tp>
   ^~~~~~~~
/usr/include/c++/7/complex: In function ‘__complex__ double std::__complex_proj(__complex__ double)’:
/usr/include/c++/7/complex:1908:3: error: conflicting declaration of C function ‘__complex__ double std::__complex_proj(__complex__ double)’
   __complex_proj(__complex__ double __z)
   ^~~~~~~~~~~~~~
/usr/include/c++/7/complex:1904:3: note: previous declaration ‘__complex__ float std::__complex_proj(__complex__ float)’
   __complex_proj(__complex__ float __z)
   ^~~~~~~~~~~~~~
/usr/include/c++/7/complex: In function ‘__complex__ long double std::__complex_proj(const __complex__ long double&)’:
/usr/include/c++/7/complex:1912:3: error: conflicting declaration of C function ‘__complex__ long double std::__complex_proj(const __complex__ long double&)’
   __complex_proj(const __complex__ long double& __z)
   ^~~~~~~~~~~~~~
/usr/include/c++/7/complex:1908:3: note: previous declaration ‘__complex__ double std::__complex_proj(__complex__ double)’
   __complex_proj(__complex__ double __z)
   ^~~~~~~~~~~~~~
/usr/include/c++/7/complex:1912:3: error: conflicting declaration of C function ‘__complex__ long double std::__complex_proj(const __complex__ long double&)’
   __complex_proj(const __complex__ long double& __z)
   ^~~~~~~~~~~~~~
/usr/include/c++/7/complex:1904:3: note: previous declaration ‘__complex__ float std::__complex_proj(__complex__ float)’
   __complex_proj(__complex__ float __z)
   ^~~~~~~~~~~~~~
/usr/include/c++/7/complex: At global scope:
/usr/include/c++/7/complex:1915:3: error: template with C linkage
   template<typename _Tp>
   ^~~~~~~~
/usr/include/c++/7/complex:1926:3: error: template with C linkage
   template<typename _Tp>
   ^~~~~~~~
/usr/include/c++/7/complex:1934:3: error: template with C linkage
   template<typename _Tp>
   ^~~~~~~~
<builtin>: recipe for target 'qr.o' failed
make[1]: *** [qr.o] Error 1
make[1]: *** Waiting for unfinished jobs....
<builtin>: recipe for target 'tp-matrix.o' failed
make[1]: *** [tp-matrix.o] Error 1
<builtin>: recipe for target 'packed-matrix.o' failed
make[1]: *** [packed-matrix.o] Error 1
<builtin>: recipe for target 'sp-matrix.o' failed
make[1]: *** [sp-matrix.o] Error 1
<builtin>: recipe for target 'kaldi-vector.o' failed
make[1]: *** [kaldi-vector.o] Error 1
<builtin>: recipe for target 'kaldi-matrix.o' failed
make[1]: *** [kaldi-matrix.o] Error 1
make[1]: Leaving directory '/raid/milde/kaldi/src/matrix'
Makefile:136: recipe for target 'matrix' failed
make: *** [matrix] Error 2

I've uploaded the complete output off "make -j clean depend; make -j 32" to https://speech.tools/output_openblas_fail.txt

**Comment by entn-at** [comment]
Please try the change in https://github.com/kaldi-asr/kaldi/pull/4015. For me, it seemed to have fixed the compilation issue for OpenBLAS v0.3.9 and also works for v0.3.7.

**Comment by bmilde** [comment]
Cool, thanks for the quick response! Yes this also fixed it for me.
