### ISSUE TITLE
steps/online/nnet3/decode.sh

### ISSUE THREAD

**Issue by 313024351** [kaldi-asr/kaldi#4027]
When i using steps/nnet3/decode.sh,the result are very good.
But when i using steps/online/nnet3/decode.sh,the result are very bad.
The same problem as steps/nnet2/online/decode.sh
It's n-gram's (3-Gram LM) problem? or Config wrong? My code as follow (100 ivector and 20 mfcc):
```
steps/online/nnet3/prepare_online_decoding.sh data/lang asr/extractor asr/dnn asr/dnn_online
steps/online/nnet3/decode.sh  asr/tri1/graph asr/audio asr/dnn_online/decode
```
The config are all default.
Thanks.

**Comment by danpovey** [comment]
Depends what you mean by "very bad" and "very good".  Bear in mind that steps/online/nnet3/prepare_online_decoding.sh requires options to set the mfcc config.

**Comment by kkm000** [comment]
I am closing this ticket for now. If you believe that your issue has not been addressed, please feel free to ping me, and I'll reopen it.
