### ISSUE TITLE
The extra_cost could be -infinity which leads to wrong pruning

### ISSUE THREAD

**Issue by sipida** [kaldi-asr/kaldi#4030]
https://github.com/kaldi-asr/kaldi/blob/fa95730beb189e1f389f93e1139339cab5246db3/src/decoder/lattice-faster-decoder.cc#L417

as the code reference above, the final_best_cost could be infinity if no tokens can be final from ComputeFinalCost(...) call. So in that case, all extra_cost should be set to zero.

 ComputeFinalCosts(&final_costs_, &final_relative_cost_, &final_best_cost_);
...

      BaseFloat tok_extra_cost = tok->tot_cost + final_cost - final_best_cost_;

**Comment by danpovey** [comment]
final_best_cost_ will never be infinity.
Read the documentation of ComputeFinalCosts() more carefully.  Admittedly it is not as clear as it should be  and should probably be reformatted, I would welcome a PR for that.
