### ISSUE TITLE
GCC 9 build problem

### ISSUE THREAD

**Issue by a-andreyev** [kaldi-asr/kaldi#4035]
Hello!
Thank you for the project!
I'm building it for the first time, so I could be wrong with my approach, feel free to close the issue.

I'm using manjaro with gcc from the repos (gcc `9.3.0`) and [kaldi-openfst](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=kaldi-openfst) is building fine from aur package, while [kaldi](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=kaldi) itself is [hardcoded](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=kaldi#n39) for gcc7 (it's not related directly to the issue, just the details about my build env)

I'm trying to build the package with gcc7 and gcc9 (changing `g++-7` cli variable to `CXX=g++`) and getting the same error:

```bash
g++ -std=c++11 -I.. -isystem /opt/kaldi/tools/openfst-1.6.7/include -O1  -Wall -Wno-sign-compare -Wno-unused-local-typedefs -Wno-deprecated-declarations -Winit-self -DKALDI_DOUBLEPRECISION=0 -DHAVE_EXECINFO_H=1 -DHAVE_CXXABI_H -DHAVE_CLAPACK -I../../tools/CLAPACK -msse -msse2 -pthread -g -fPIC -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -fno-plt -D_FORTIFY_SOURCE=2  -c -o nnet-fix.o nnet-fix.cc
g++ -std=c++11 -I.. -isystem /opt/kaldi/tools/openfst-1.6.7/include -O1  -Wall -Wno-sign-compare -Wno-unused-local-typedefs -Wno-deprecated-declarations -Winit-self -DKALDI_DOUBLEPRECISION=0 -DHAVE_EXECINFO_H=1 -DHAVE_CXXABI_H -DHAVE_CLAPACK -I../../tools/CLAPACK -msse -msse2 -pthread -g -fPIC -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -fno-plt -D_FORTIFY_SOURCE=2  -c -o nnet-stats.o nnet-stats.cc
g++ -std=c++11 -I.. -isystem /opt/kaldi/tools/openfst-1.6.7/include -O1  -Wall -Wno-sign-compare -Wno-unused-local-typedefs -Wno-deprecated-declarations -Winit-self -DKALDI_DOUBLEPRECISION=0 -DHAVE_EXECINFO_H=1 -DHAVE_CXXABI_H -DHAVE_CLAPACK -I../../tools/CLAPACK -msse -msse2 -pthread -g -fPIC -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -fno-plt -D_FORTIFY_SOURCE=2  -c -o rescale-nnet.o rescale-nnet.cc
{standard input}: Assembler messages:
{standard input}:14669: Warning: end of file not at end of a line; newline inserted
{standard input}:14877: Error: number of operands mismatch for `movq'
{standard input}: Error: open CFI at the end of file; missing .cfi_endproc directive
g++: fatal error: Killed signal terminated program cc1plus
compilation terminated.
make[1]: *** [<builtin>: chain-supervision.o] Error 1
make[1]: *** Waiting for unfinished jobs....
```

While the same package is building fine if I replace the compiler to clang (`CXX=clang++`, clang from the repos is `9.0.1`).

It could be my build environment. And I have no problems with clang, just curious. Any hint on what to check twice?

**Comment by danpovey** [comment]
Looks to me like being out of memory was the real problem.  Maybe build
with fewer jobs (e.g. remove -j option), or use more memory in your VM.

**Comment by jtrmal** [comment]
Btw, just FYI, cuda does not support 9.x GCC yet, afaik.
Y.

**Comment by a-andreyev** [comment]
Thank you for the fast reply!
Yep, I'm building it without cuda support:
```bash
WARNING: CUDA will not be used! If you have already installed cuda drivers
         and CUDA toolkit, try using the --cudatk-dir= option. A GPU and CUDA
         are required to run neural net experiments in a realistic time.
```

and it looks like building with fewer jibs helps. Changing it from (nproc+1) 13 to 6 passed the mentioned error, so it definitely was my machine and configuration problem.

Thank you again and sorry to bother!
