### ISSUE TITLE
./install_mkl.sh: MKL package intel-mkl-64bit-2020.0-088 installation FAILED.

### ISSUE THREAD

**Issue by 200987299** [kaldi-asr/kaldi#4036]
Run the above sudo command now? [Y/n]:y
+ exec sudo ./install_mkl.sh -sp debian intel-mkl-64bit-2020.0-088
+ apt-get update
Get:1 http://security.ubuntu.com/ubuntu bionic-security InRelease [88.7 kB]
Hit:2 http://cn.archive.ubuntu.com/ubuntu bionic InRelease                     
Ign:3 http://ppa.launchpad.net/fcitx-team/nightly/ubuntu bionic InRelease          
Err:4 http://ppa.launchpad.net/fcitx-team/nightly/ubuntu bionic Release
  404  Not Found [IP: 91.189.95.83 80]
Reading package lists... Done                             
E: The repository 'http://ppa.launchpad.net/fcitx-team/nightly/ubuntu bionic Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
./install_mkl.sh: MKL package intel-mkl-64bit-2020.0-088 installation FAILED.

**Comment by 200987299** [comment]
sorry, it's the internet connection issue and the sudo apt-get update won't work. if anyone from China has the same problem, visit: https://blog.csdn.net/nbxuwentao/article/details/90524349

**Comment by 200987299** [comment]
sorry, it's not a bug, but something else. https://www.cnblogs.com/wenzheshen/p/6599636.html

**Comment by EmreOzkose** [comment]
Hi @200987299 , how did you solve that problem? Can you share hints?

**Comment by EmreOzkose** [comment]
Anyone who faces that problem can look there: https://github.com/nodesource/distributions/issues/541

It is about PPA file. Some of links are broken. In my case: 
In /etc/apt/sources.list.d/webupd8team-ubuntu-java-focal.list -> deb http://ppa.launchpad.net/webupd8team/java/ubuntu focal main
I commented this line, and every thing works well.
