### ISSUE TITLE
Error in steps/decode.sh. Not showing what can be a problem

### ISSUE THREAD

**Issue by chaoticz044** [kaldi-asr/kaldi#4037]
I tried running a simple script using the "kaldi for dummies" that I edit using my own data. In the decoding part in both mono and tri1 there is no WER displayed.

> WARNING: the --mono, --left-biphone and --quinphone options are now deprecated and ignored.
> utils/mkgraph.sh: exp/mono/graph/HCLG.fst is up to date.
> steps/decode.sh --config conf/decode.config --nj 4 --cmd run.pl --num-threads 3 exp/mono/graph data/test exp/mono/decode
> decode.sh: feature type is delta
> steps/diagnostic/analyze_lats.sh --cmd run.pl exp/mono/graph exp/mono/decode
> analyze_phone_length_stats.py: WARNING: optional-silence sil is seen only 70.0149925037% of the time at utterance begin.  This may not be optimal.
> analyze_phone_length_stats.py: WARNING: optional-silence sil is seen only 65.8170914543% of the time at utterance end.  This may not be optimal.
> steps/diagnostic/analyze_lats.sh: see stats in exp/mono/decode/log/analyze_alignments.log
> Overall, lattice depth (10,50,90-percentile)=(2,511,5776) and mean=2046.3
> steps/diagnostic/analyze_lats.sh: see stats in exp/mono/decode/log/analyze_lattice_depth_stats.log
> local/score.sh --cmd run.pl data/test exp/mono/graph exp/mono/decode
> local/lattice_to_ctm.sh --cmd run.pl --word-ins-penalty 0.5 --min-lmwt 8 --max-lmwt 12 --model exp/mono/final.mdl data/test exp/mono/graph exp/mono/decode
> local/lattice_to_ctm.sh: expecting file data/test/segments to exist
> steps/decode.sh: Error: scoring failed. (ignore by '--skip-scoring true')

I tried to check the exp/mono/decode/logs/* and see WARNINGS like this:

> WARNING (gmm-latgen-faster-parallel[5.5.671~1-e5a5a]:CheckMemoryUsage():determinize-lattice-pruned.cc:320) Did not reach requested beam in determinize-lattice: size exceeds maximum 50000000 bytes; (repo,arcs,elems) = (32720224,628064,16665984), after rebuilding, repo size was 23395200, effective beam was 9.73998 vs. requested beam 13

and another like this:

> WARNING (gmm-latgen-faster-parallel[5.5.671~1-e5a5a]:operator()():decoder-wrappers.cc:102) Determinization finished earlier than the beam for utterance vivos-VIVOSDEV09_159

Please help me since I don't know what to do now. Thank you.

**Comment by jtrmal** [comment]
it actually does show what is the problem:

local/lattice_to_ctm.sh: expecting file data/test/segments to exist
Either use the script steps/score_kaldi.sh for scoring (by symlinking) or
create that file
y.
