### ISSUE TITLE
I use thchs30 project. How do I train and recognize 8kHZ speech. Instead of 16kHZ

### ISSUE THREAD

**Issue by CHzhiwei** [kaldi-asr/kaldi#4040]
I use thchs30 project. How do I train and recognize 8kHZ speech. Instead of 16kHZ

**Comment by danpovey** [comment]
In conf/mfcc.conf and conf/mfcc_hires.conf you can add the lines
```
--sample-frequency=8000 
--allow-downsample=true
```

**Comment by CHzhiwei** [comment]
> ```在conf / mfcc.conf和conf / mfcc_hires.conf中，您可以添加以下行

```
--sample-frequency=8000 
--allow-downsample=true
```

I have changed the conf file, but when I run online-wav-gmm-decode-faster to recognize 8khz, Sample rates other than 16kHz are not supported!

**Comment by danpovey** [comment]
You shouldn't be asking questions like this on github, but on the list (and
anyway, search first).
You'd have to train the model for the right sampling rate first.

**Comment by CHzhiwei** [comment]
> You shouldn't be asking questions like this on github, but on the list (and anyway, search first). You'd have to train the model for the right sampling rate first.

Sorry, I searched but the problem is not solved。I describe my problem in detail, I am using thchs30 to train and test speech recognition, and now I am modified
--sample-frequency = 8000
--allow-downsample = true
  In the conf / mfcc.conf file. I have got the model, but when testing. When using online-wav-gmm-decode-faster, the following error appears: "Sample rates other than 16kHz are not supported!" An error occurred while decoding, not during training. In addition, there is no original /mfcc_hires.conf in the conf file. I added it, and the test cannot decode 8khz voice files.
Thank you

**Comment by danpovey** [comment]
Ah.  that's a very old decoding program that we don't really use any more.
And the thchs30 setup also hasn't
been updated in a very long time.  I advise to use a different example
setup, e.g. aishell2.

**Comment by CHzhiwei** [comment]
> e.g. aishell2.

Thank you very much for your answer,
 I will try e.g. aishell2.

**Comment by naxingyu** [comment]
multi_cn is the most up-to-date Mandarin ASR example.
