### ISSUE TITLE
Low latency acoustic modeling using temporal convolution and LSTMs example

### ISSUE THREAD

**Issue by witeksosnowski** [kaldi-asr/kaldi#4043]
Hi,

I am trying to build a real time asr and just came across this publication: https://danielpovey.com/files/2017_spl_tdnnlstm.pdf
Is there any existing example in kaldi that makes use of this architecture? I was looking at the egs/ami and egs/swbd but could not find any simmiliar example.

Thanks in advance

**Comment by jtrmal** [comment]
temporal convolution is tdnn, if that's what are you asking

**Comment by witeksosnowski** [comment]
I meant architecture based on tdnn and lstm that has low latency. It is described in publication I gave.
Can you please take a look at it?

**Comment by jtrmal** [comment]
I'm sorry I don't have time to look for it and it might be well possible
the scripts didn't make it to trunk at all (usually we optimize only WER).
If you are interested in minimizing latency, you could try what was
proposed here:
https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/kaldi-help/cjJ8-RWWcao/vZ4i2R0jDAAJ

y.

**Comment by jtrmal** [comment]
And if you have more questions or follow up questions on this, please use
the kaldi-help mailing list
y.
