### ISSUE TITLE
About a small issue in multi_cn - $cd

### ISSUE THREAD

**Issue by underdogliu** [kaldi-asr/kaldi#4049]
Dear all, 

I am trying with `multi_cn` egg and found that `local/aishell_download_and_untar.sh` did not work on my side. After some tweaking I found that after downloading when untar-ing waves, seems like after $cd (line 74 and 91), the script did not return to previous directory, which shall be the case according to what I observed. By adding `cd -` after corresponding process (for example, add it after line 86 and 95 like below) it worked. However, I am not sure if it is actually a bug or it just happened to me. If so, similar issues needs to be fixed for all `*download_and_untar.sh` scripts. @naxingyu 

Regards

```
......
cd $data

if ! tar -xvzf $part.tgz; then
  echo "$0: error un-tarring archive $data/$part.tgz"
  exit 1;
fi
cd -

touch $data/$part/.complete

if [ $part == "data_aishell" ]; then
  cd $data/$part/wav
  for wav in ./*.tar.gz; do
    echo "Extracting wav from $wav"
    tar -zxf $wav && rm $wav
  done
  cd -
fi
.......
```

**Comment by naxingyu** [comment]
The script should work presuming that the $data path is absolute, as it is called in run.sh.

**Comment by underdogliu** [comment]
ok then I got no problem. Thanks for specifying. But still maybe it will be safe to call `cd -` in case anybody would like to modify script outside or happen to specify the source audio directory to be a relative one? Or we can add some comments at `run.sh`. I know using full path is sort of common practice but sometimes there are users who does not have access to like `/mnt/` and they have to download data to their own home space on server.

**Comment by naxingyu** [comment]
Thanks for the solution. I think add comments is enough, since the scripts
in local are bound to respective example, not generally utilized. Would you
mind do this?

**Comment by alex-ht** [comment]
`pushd` and `popd` are good stuff

**Comment by underdogliu** [comment]
@naxingyu OK I think I will do it and make PR.

@alex-ht Just out of curiosity, is there any difference between `pushd/popd` to `cd/cd -`? Because I used to see `pushd`, but for most of the cases it was used in docker execution scripts ad function blocks in bash.

**Comment by alex-ht** [comment]
every script should avoid changing working dir, then it can be easily integrated with others. If necessary, using `pushd/popd` structure instead of `cd` can keep traceability. that's why this bug happened. just my opinion

**Comment by underdogliu** [comment]
@alex-ht that's right. But for each `download_and_untar.sh` script we never goes deeper than single-pass of working directory change - it's always `cd` followed by `cd -`. I kinda hold the sense that `pushd` and `popd` are for more complicated tasks (such as docker deployment script, for example). Besides, I tried `pushd $dir` and `popd` but it did not work well under `#!/bin/bash` shebang - I don't know if I did anything wrong though. So I may go for `cd` ops for now but if `pushd` happen to be a better practice which is working for more cases, please feel free to make sharp comments and correct me.

**Comment by alex-ht** [comment]
how about removing all `cd`?
we can define output location by add "--directory-prefix=$data" after `wget`, and add `--directory=$data/$part/wav` after `tar`

**Comment by danpovey** [comment]
Guys, you are overthinking this.  Just do either cd - or popd/pushd and
call it a day.  I'm happy to merge any fix.
