### ISSUE TITLE
README.md for mobvoi and snips

### ISSUE THREAD

**Issue by framsc** [kaldi-asr/kaldi#4051]
The mobvoi and snips egs work well after some modification.  However, I cannot find the README.md anywhere.  Are there any references for these egs? especially for the e2e part.

**Comment by freewym** [comment]
@framsc Thanks for being interested in the wake word recipes! I will push a README shortly. I am also wondering what do you want to know about the recipes from README, besides the dataset descriptions and e2e LF-MMI stuff?

**Comment by framsc** [comment]
@freewym Thanks for replying and thanks for sharing such great work too. A file like egs/swahili/README.txt is enough. The file gives me clues about what to google.

Say something more
1. The recipe name explains the dataset a little bit. Thought the structure and contents of the dataset need to be guessed by the data preparing script.

2. I am impressed by the preparation of data/lang/lm/fst.txt using
0 1 $id_sil $id_sil
0 4 $id_sil $id_sil 7.0
1 4 $id_freetext $id_freetext 0.0
4 0 $id_sil $id_sil
1 2 $id_word $id_word 1.1
2 0 $id_sil $id_sil

I use something like this
\1-grams:
-1	KEYWORD
-99 <s>
-1 </s>

Novel ideas like this are distributed in the recipe. Is there a summary in the published paper or blog link that can be referred to?

Thanks again. BRs.

**Comment by freewym** [comment]
OK. I am creating  #4052 for this.

There is no published paper yet. I am working on one describing it.

**Comment by framsc** [comment]
hope to hear from you soon.
