### ISSUE TITLE
faster-decoder not support grammar fst?

### ISSUE THREAD

**Issue by Duum** [kaldi-asr/kaldi#4081]
i find the faster-decoder code not support template parameter, does faster decoder not support grammar fst?

**Comment by danpovey** [comment]
No, grammar FST has its own decoder.

**Comment by Duum** [comment]
thank danpovey. can i change the faster-decoder code to support grammar fst? or it  is not necessary for this?

**Comment by Duum** [comment]
i see grammar fst demo is for oov?   Can it use to strengthen some specific grammar pattern  by changing the g.fst to more complex one ? thanks for replying.

**Comment by danpovey** [comment]
Not just for OOV.  There are 2 demos in there.  questions like this should be web-search or kaldi-help, not here, please.
