### ISSUE TITLE
Data augmentation doesn't achieve better DER results.

### ISSUE THREAD

**Issue by BLack-yzf** [kaldi-asr/kaldi#4082]
I used the kaldi/egs/dihard_2018/v2 recipe to make front-end processing,and get the MFCC feature for training X-vector model. Then I reproduce the code of training x-vector on pytorch, the x-vector model is totally same as the kaldi version. The PLDA and AHC procedure  also never change.  Then I used the trained x-vector model of pytorch version to test Diarization performance, and get the following resluts.
The first doesn't use the data augmentation, then get DER=27.38% on dihard_2018_dev. 
Another version use the  data augmentation(same as the v2 recipe),and only get DER=27.60%.
Theoretically, using data augmentation will improve performance, but the results are terrible.  I don't know which part caused the problem,I need help.  
Thanks sincerely! @

**Comment by kkm000** [comment]
Questions like this have a better chance to be answered in the kaldi-help Google Group: https://groups.google.com/forum/#!forum/kaldi-help. I'll close this for now; if you believe this is a bug in Kaldi please reply with a better explanation what exactly you believe is broken, and I'll reopen this.
