### ISSUE TITLE
official docker image does not support cmake build

### ISSUE THREAD

**Issue by unixnme** [kaldi-asr/kaldi#4085]
Hello,

This is basically a duplicate of #3859, which doesn't seem to have been resolved yet.
The following is commands run on official docker image:

```
apt-get update && apt-get install cmake -y
mkdir build && cd build
export MKLROOT=/opt/intel/mkl
cmake .. -DMATHLIB=MKL
...
CMake Error at /usr/share/cmake-3.7/Modules/FindPackageHandleStandardArgs.cmake:138 (message):
  Could NOT find BLAS (missing: BLAS_LIBRARIES)
Call Stack (most recent call first):
  /usr/share/cmake-3.7/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  cmake/FindBLAS.cmake:806 (find_package_handle_standard_args)
  cmake/FindLAPACK.cmake:193 (find_package)
  CMakeLists.txt:69 (find_package)

```

I prefer to work with cmake build because that's what my IDE supports natively.
Thanks.

**Comment by danpovey** [comment]
Perhaps @cloudhan who created the CMake setup or @mdoulaty who created the docker image could help with this?

**Comment by mdoulaty** [comment]
I'll have a look into this - the current Docker images are not really tested with `CMake` and will be good to support it as well

**Comment by unixnme** [comment]
@mdoulaty this was on cpu pre-built image
`docker run -it kaldiasr/kaldi:latest bash`

**Comment by chuanma** [comment]
I had the same issue while building kaldi under ubuntu 18.04, and fixed it by removing `cmake/FindBLAS.cmake` from kaldi and using a latest version of `cmake` (3.17.3). 

Maybe the included `cmake/FindBLAS.cmake` is outdated?

**Comment by cloudhan** [comment]
@chuanma not all user can upgrade cmake at will, the included version should be pretty recent. The problem might be due to MKL update https://gitlab.kitware.com/cmake/cmake/-/commit/6bd9cee63885f1a2029faf0756c1dd4277cf7766
