### ISSUE TITLE
RepeatedAffineComponent

### ISSUE THREAD

**Issue by danpovey** [kaldi-asr/kaldi#409]
There are some experiments I want to do with learned many-to-many nonlinearities, for which I need an affine component that repeatedly acts on its input, so it's basically a block-diagonal matrix with all the blocks the same, and the bias term repeated also.  [we don't have to bother with natural-gradient on this, as the dims will be quite small.]

The configuration line will be something like:

component name=affine-repeated-0 type=RepeatedAffineComponent input-dim=500 output-dim=1000  num-repeats=20

where the num-repeats must divide the input-dim and output-dim.  The GPU implementation can use AddMatMatBatched, similar to the convolutional components.  The parameters would be the same as an AffineComponent with input-dim=500/20 and output-dim=1000/20, in this case.
AffineComponent would be a reasonable starting point for the code (but don't inherit from AffineComponent; copy and modify; and you likely won't need the Update() functions for now; just do the update directly inside the backprop, inside an if-statement).

@xiaohui-zhang, do you have time for this?

Dan

**Comment by danpovey** [comment]
@naxingyu , do you have time for this?  @xiaohui-zhang is busy in the next couple of weeks.

**Comment by naxingyu** [comment]
I have limited time recently. May I ask @zhichaowang to co-work on this one?

**Comment by danpovey** [comment]
Sure, that's great, but make sure you're satisfied with the patch before
asking me to review it.
Dan

**Comment by galv** [comment]
@naxingyu, if you are busy I could take this off your hands; I am not very busy right now. @danpovey, Vijay suggested this wouldn't be unreasonable for me to get familiar with the neet3 code base. Could I tackle this?

**Comment by danpovey** [comment]
I have something else that needs to be done that I can create an issue
for-- this current TODO is very similar to code that @naxingyu wrote, so it
will be easier for him to supervise that guy, who he knows.  I'll create
the other issue right now.

**Comment by galv** [comment]
Sure thing.

**Comment by danpovey** [comment]
@galv, since you did a good job on the other issue, and I haven't heard from @zhichaowang or @naxingyu in the last couple of days, if you have time today or to-morrow to work on the RepeatedAffineComponent it would be nice.  I do need this for something.  @zhichaowang or @naxingyu - if you have already started work on this, let us know.

**Comment by naxingyu** [comment]
Hi Dan,
Sorry for the delay. We were discussing the functionality of this 
component. If the affine transform is repeated, why not just copy the 
output for several times? And we won't need the AddMatMatBatch kernel 
for this. In the example, the actual input should be, say 256 x 25 and 
repeated 20 times, forming a 256 x 500 repeated input, then the output 
is 256 x 1000, which is actually a stack of 256 x 50 identical outputs, 
that should be doable with a simple AddMatMat and copy, right?
Xingyu

在 2015/12/27 5:05, Daniel Povey 写道:

**Comment by danpovey** [comment]
> Sorry for the delay. We were discussing the functionality of this
> component. If the affine transform is repeated, why not just copy the
> output for several times?


The parameters repeated like a block-diagonal matrix, so the inputs would
differ.


> And we won't need the AddMatMatBatch kernel
> for this. In the example, the actual input should be, say 256 x 25 and
> repeated 20 times, forming a 256 x 500 repeated input, then the output
> is 256 x 1000, which is actually a stack of 256 x 50 identical outputs,
> that should be doable with a simple AddMatMat and copy, right?
>

I think you might misunderstand something.  The input and output dims are
interpreted as blocks.  For example, suppose we have 100 blocks, and the
input-dim is 100 * 12 and the output-dim is 100 * 20.
The linear matrix of parameters would be 20 * 12, with 20 bias components.

Dan

**Comment by naxingyu** [comment]
If I say "the linear parameters (and bias) repeatedly act on contiguous 
blocks of the input", is that correct?
X.

在 2015/12/27 10:52, Daniel Povey 写道:

**Comment by danpovey** [comment]
I suppose so.
Dan

**Comment by zhichaowang** [comment]
Sorry for the delay. Now I almost finish the RepeatedAffineComponent. There is one thing, should I rewrite the  FixedAffineComponent to RepeatedFixedAffineComponent or ignore CollapseWithNext functions now?



wangzhichao
 
From: Daniel Povey
Date: 2015-12-27 11:05
To: kaldi-asr/kaldi
CC: ZhichaoWang
Subject: Re: [kaldi] RepeatedAffineComponent (#409)
I suppose so.
Dan

**Comment by danpovey** [comment]
Ignore CollapseWithNext and basically all of those 'special' functions not
in the interface [except Init()].
Please submit a pull request even if the work is not finished- I need this
ASAP.
Dan
