### ISSUE TITLE
If I can use mfcc for training gmm but using fbank for training chain model 

### ISSUE THREAD

**Issue by panxin801** [kaldi-asr/kaldi#4093]
Hi, I want to ask If  I can use mfcc for training GMM parts and using fbank for training Chain model. And what else should I change for reaching this propose ? Thank you for the help

**Comment by danpovey** [comment]
Should ask this kind of thing on kaldi-help... look for a setup with idct-layer in it using `git grep`.  We generally dump the features as full-rank MFCCs and then convert back to mel filterbanks in the network, since Kaldi's feature compression method works better with less-correlated features.

**Comment by panxin801** [comment]
Thank you Dan, I don't  think about this part so carefully. Thanks
