### ISSUE TITLE
Undeclared identifier when compile on Windows with MKL

### ISSUE THREAD

**Issue by pavel-esir** [kaldi-asr/kaldi#4099]
Dear Kaldi developers, I was trying to build Kaldi on Windows with MKL as mathlib. I specified MKLROOT environment variable. Then in a subfolder I run
>cmake -G "Visual Studio 15 2017 Win64" -DMATHLIB=MKL ..\

and it successfully generates solution. But when I run cmake --build .\ it throws the following error
>kaldi\src\matrix\sp-matrix.cc(939): error C2065: 'num_rows_': undeclared identifier
kaldi\src\matrix\sp-matrix.cc(940): error C2065: 'data_': undeclared identifier 

while I found declaration in packed-matrix.h 
On Linux it builds without any problems when I use openblas as mathlib.
Could you please take a look to this problem?

**Comment by danpovey** [comment]
Possibly this older copy of VS is more picky about using base-name
qualifications, likely this->num_rows_ or PackedMatrix::num_rows_ would
have worked.
We generally prefer this->num_rows_.
You can make a PR if you want.

**Comment by pavel-esir** [comment]
Thanks for your answer! I installed VS 2019 and in worked perfectly. So no need to make a PR.
