### ISSUE TITLE
data/test: Is a directory----error when running make_mfcc.sh

### ISSUE THREAD

**Issue by littlered111** [kaldi-asr/kaldi#4100]
Hi, I am using egs sprakbanken_swe in Kaldi  and the following error occurs when running the shell command _**steps/make_mfcc.sh --nj 10 --cmd $train_cmd data/test exp/make_mfcc/test test mfcc**_

Anyone have suggestion for this? 
Thank for your help!

_yihan@LAPTOP-2K33DHO6:/mnt/e/kaldi/egs/sprakbanken_swe/s5_$ steps/make_mfcc.sh --nj 10 --cmd $train_cmd data/test exp/make_mfcc/test test mfcc
steps/make_mfcc.sh --nj 10 --cmd data/test exp/make_mfcc/test test mfcc
utils/validate_data_dir.sh: Successfully validated data-directory exp/make_mfcc/test
steps/make_mfcc.sh: [info]: no segments file exists: assuming wav.scp indexed by utterance.
steps/make_mfcc.sh: line 138: data/test: Is a directory

**Comment by danpovey** [comment]
Or you edited make_mfcc.sh while running it.
