### ISSUE TITLE
Braces for dictionary instead of brackets in perl

### ISSUE THREAD

**Issue by johnjosephmorgan** [kaldi-asr/kaldi#4106]
In the file sre16/v2/local/make_mx6_calls.pl a variable is initialized as a dictionary on line 32. Brackets instead of braces are used with this variable later in the script. Was this on purpose?

**Comment by danpovey** [comment]
I actually didn't even know that you could index a perl dictionary with braces instead of brackets.  I think most people use brackets for that; certainly, I do.  Closing the issue because I doubt we'll be changing this kind of thing.  Thanks though.
