### ISSUE TITLE
MacOS Catalina Unable to find Zlib

### ISSUE THREAD

**Issue by Sruthik22** [kaldi-asr/kaldi#4109]
I am getting: 
```
extras/check_dependencies.sh: zlib is not installed.
extras/check_dependencies.sh: The following prerequisites are missing; install them first:
   zlib1g-dev
```

I have downloaded and installed the command line tools for Xcode directly from the Apple website according to some suggestions online. Nothing I have done has helped Kaldi find zlib on my computer.

**Comment by danpovey** [comment]
From here
https://stackoverflow.com/questions/23749530/brew-install-zlib-devel-on-mac-os-x-mavericks
you should be able to install with:
xcode-select --install

**Comment by Sruthik22** [comment]
I have tried to run this command, and directly download the command line tools - but they have not helped. I have also tried to build zlib directly from source and I get the message:
`./configure
Checking for gcc...
Checking for shared library support...
No shared library support.
Building static library libz.a version 1.2.11 with gcc.
Checking for size_t... No.
Checking for long long... Yes.
Failed to find a pointer-size integer type.
** ./configure aborting.`

**Comment by danpovey** [comment]
Try just ignoring the issue.  zlib may not really be needed except for IRSTLM, which is only used in a few recipes now.

**Comment by danpovey** [comment]
Or try `brew install zlib`

**Comment by Sruthik22** [comment]
I got it to work! However, when I run make I am getting the same exact issue described here: https://github.com/kaldi-asr/kaldi/issues/4078

**Comment by danpovey** [comment]
Many issues are described there, you need to be more specific.
I think that guy's problems disappeared when he reinstalled Catalina.

**Comment by Sruthik22** [comment]
I have the same error message when running the `make` command. I did not do the rest of the things he outlined afterward, and I am not sure I have the time to start from scratch and reinstall Catalina.

**Comment by SofijaErkin** [comment]
@Sruthik22

 just use "brew info zlib" to check the version of zlib on mac.

If don't have it, then just use"brew search zlib" to know whether has it or not.

If really didn't have that, then just use "brew install zlib" to install zlib.

Finally, use "brew search zlib" to know whether has it or not, 

And use "brew info zlib" to check the version of zlib.

**Comment by danpovey** [comment]
When I type `make` in tools on Catalina, I get this:
```
mac:tools: extras/check_dependencies.sh
extras/check_dependencies.sh: Intel MKL does not seem to be installed.
 ... Download the installer package for your system from:
 ...   https://software.intel.com/mkl/choose-download
 ... You can also use other matrix algebra libraries. For information, see:
 ...   http://kaldi-asr.org/doc/matrixwrap.html
```
... however, `make` continues.    It could be that is OK.
It does not say anything about zlib.
I'm guessing the zlib headers are installed by XCode, and if you have not updated your XCode, you may have a problem.

**Comment by jtrmal** [comment]
I think Mac has the accelerate framework that includes BLAS/cBLAS. Not sure
of it's performance w.r.t. MKL or if the error should exist or what would
happen afterwards :)
y
