### ISSUE TITLE
mini_librispeech run.sh does not reach the end and gives no error message

### ISSUE THREAD

**Issue by FBorgeat** [kaldi-asr/kaldi#4113]
I'm trying to run mini_librispeech with my own data but run.sh ends with:
steps/lmrescore_const_arpa.sh --cmd run.pl --mem 4G data/lang_nosp_test_tgsmall data/lang_nosp_test_tglarge data/dev_clean_2 exp/tri1/decode_nosp_tgsmall_dev_clean_2 exp/tri1/decode_nosp_tglarge_dev_clean_2

It gives no error message, the data is 1 speaker with one file in test and 9 in train, i put nj 1 in the whole script, I have the corpus and data folder included.

[corpus_data.zip](https://github.com/kaldi-asr/kaldi/files/4795777/corpus_data.zip)

**Comment by danpovey** [comment]
That part is backgrounded.  Likely it was working.  Look at RESULTS for how
to get results

**Comment by FBorgeat** [comment]
Running RESULTS gives:
%WER 100.00 [ 3 / 3, 0 ins, 3 del, 0 sub ] xp/mono/decode_nosp_tgsmall_dev_clean_2/wer_10_0.0
%WER 100.00 [ 3 / 3, 0 ins, 3 del, 0 sub ] exp/tri1/decode_nosp_tglarge_dev_clean_2/wer_10_0.0
%WER 100.00 [ 3 / 3, 0 ins, 3 del, 0 sub ] exp/tri1/decode_nosp_tgmed_dev_clean_2/wer_10_0.0
%WER 100.00 [ 3 / 3, 0 ins, 3 del, 0 sub ] exp/tri1/decode_nosp_tgsmall_dev_clean_2/wer_10_0.0

but running run_tdnn_1j.sh afterwards gives:
local/nnet3/run_ivector_common.sh: expected file exp/tri3b/final.mdl to exist
