### ISSUE TITLE
linux extension to sed in tools Makefile

### ISSUE THREAD

**Issue by johnjosephmorgan** [kaldi-asr/kaldi#4124]
I'm trying to run make in the tools directory on MacOSX. The run is failing because sed is using a linux extension, namely the -i option.

**Comment by kkm000** [comment]
Huh, I thought we got rid of them all. Can you pinpoint where, what is being built? tools/Makefile downloads a few programs, so it may not be as easy.

**Comment by kkm000** [comment]
Introduced in 57bc88acf #4117

**Comment by johnjosephmorgan** [comment]
tools/Makefile lines 92 and 93

**Comment by johnjosephmorgan** [comment]
misc/fix_cpplint.sh and misc/fix_bash.sh

**Comment by kkm000** [comment]
Sure, but the latter two are maintainer scripts, and not important. The Makefile one is a recent change, and the one that needs to be fixed. Gimme a few hours, I'll get to it.

**Comment by johnjosephmorgan** [comment]
The -d option is also a linux extension that is not in bsd.

**Comment by songmeixu** [comment]
Hi, the patch was introduced by me. And I have made a PR in #4135. Instead of reverting it, it will be much appreciated if someone could help review it. 🤝

**Comment by songmeixu** [comment]
Sorry, @kkm000. I just read the #4133. Now, let me explain why I committed this patch there.
