### ISSUE TITLE
Validate data dir, wrong variable

### ISSUE THREAD

**Issue by Fhrozen** [kaldi-asr/kaldi#4141]
On lines 
https://github.com/kaldi-asr/kaldi/blob/d8082de893cc5c835a3150f5fd910d9b373e619e/egs/wsj/s5/utils/validate_data_dir.sh#L39-L40

it is written as `--no-spk-short`. Should not it be `--no-spk-sort`. 

Tested with CHiME6 track 2, preparation of the segmentation part.

**Comment by kkm000** [comment]
Fixed in #4163, thanks.
