### ISSUE TITLE
Squash nasty little bug, dash instead of underscore

### ISSUE THREAD

**Issue by johnjosephmorgan** [kaldi-asr/kaldi#4147]
BLUF: line 163 of aspire/s5/local/run_asr_segmentation.sh:
Change from:
steps/segmentation/copy_targets_dir.sh --utt-prefix "rev${i}_" \
to:
    steps/segmentation/copy_targets_dir.sh --utt-prefix "rev${i}-" \
Change the undrscore to a dash.

I am trying to build an SAD with the aspire recipe.
The recipe fails in stage 6 of local/segmentation/tuning/train_stats_asr_sad_1a.sh.
To get the examples to train the neural network, the program nnet3-get-egs-dense-targets is invoked.
The second argument to that program should be a list of matrices with the targets.
That list is empty.
This list is produced by the script utils/filter_scp.pl.
That script takes 2 files as its arguments.
The reverberate script writes one of those files.
The other file is written by the local/run_asr_segmentation.sh script in stage 6.
Identifiers are written by the reverberate script with a prefix followed by a dash.
The identifiers written in the run_asr_segmentation.sh script are written with a prefix followed by an underscore.
This is why the list of targets is empty.

**Comment by kkm000** [comment]
Do you have time to make a PR for it?

**Comment by johnjosephmorgan** [comment]
I'll try to make a pr this morning.

**Comment by kkm000** [comment]
Thanks!
