### ISSUE TITLE
online2-tcp-nnet3-decode-faster memory leak?

### ISSUE THREAD

**Issue by kli017** [kaldi-asr/kaldi#4149]
Hello, I was wondering if the online2-tcp-nnet3-decode-faster has memory leak problem. I set 50 PID with different port on the server and test with microphone. When I monitor the memory and cpu usage I found that the memeroy usage is growing slowly.
The usage at begining is 87G and grow to 91G after around 30min later.  Is this normal?

![ccPic20200701182931](https://user-images.githubusercontent.com/14877573/86233979-d7681f80-bbc8-11ea-9b66-8f56ff178120.jpg)
![ccPic20200701182914](https://user-images.githubusercontent.com/14877573/86233982-d931e300-bbc8-11ea-8968-bb0a71b717d9.jpg)

**Comment by danpovey** [comment]
it would be expected to grow a bit since I think malloc+free doesn't return
memory to the systme.
it shouldn't grow without limit though.
valgrind may tell you about specific leaks.

**Comment by nshmyrev** [comment]
It is not a memory leak, it simply stores too much data as it decodes. We have implemented a reset after 20 minutes of decoding to fix that in vosk recently:

https://github.com/alphacep/vosk-api/commit/7f3f25e17009b7a4c6809f48e1847cd780c85856
