### ISSUE TITLE
set default cmd to run.pl instead of queue.pl

### ISSUE THREAD

**Issue by johnjosephmorgan** [kaldi-asr/kaldi#4150]
The cmd variable in the script steps/segmentation/detect_speech_activity.sh is set to queue.pl. Could we set the default to run.pl instead?

**Comment by danpovey** [comment]
Agree.  Hopefully @kkm can get to it at some point.

**Comment by johnjosephmorgan** [comment]
Do you want me to make a pr for this?

**Comment by danpovey** [comment]
If you could it would be great!  @kkm can merge.
