### ISSUE TITLE
Installing Kaldi through Docker brings to a 14 gb image

### ISSUE THREAD

**Issue by simonefrancia** [kaldi-asr/kaldi#4151]
Hi, 
is it normal that installing kaldi from scratch through Docker, at the end of installing Docker Image is 14 GB? 
How can I make this image smaller? I am not able to pull the image from Hub because I would like to install Kaldi in an existing Dockerfile. My original Image Docker is 6gb and adding kaldi installation, it becomes 20 GB!! 
Can you help me? 
Thanks

**Comment by danpovey** [comment]
It might be smaller if you configure with shared libraries (--shared to
"configure" in src/)... not sure what that image does.

**Comment by jtrmal** [comment]
plus make sure the *o files are removed  after compilation
another issue might be that the Dockerfile has too many steps (you might
want to compress those) -- I didn't look inside the Dockerfile.
y.

**Comment by simonefrancia** [comment]
Running a container, I found a lot of files both in `src/` and `tools` like these.
```
./tools/sctk-2.4.10/src/sclite/arcseq1.o
./tools/sctk-2.4.10/src/sclite/stm2ctm.o
./tools/sctk-2.4.10/src/sclite/net_dp.o
./tools/sctk-2.4.10/src/sclite/scores.o
./tools/sctk-2.4.10/src/sclite/rank.o
./src/bin/copy-post.o
.....
./src/bin/cluster-phones.o
./src/bin/build-pfile-from-ali.o
./src/bin/copy-int-vector.o
./src/bin/copy-vector.o
```
Can I delete them?
Thanks

**Comment by jtrmal** [comment]
Yes

**Comment by simonefrancia** [comment]
I tried to enter inside a container and delete all these files. Then I went out , stopped the container and commit it as Docker image but nothing changed in terms of size. 
Are MKL necessary if I want to use kaldi in cpu version?
Entering in my `/opt` folder, I have this:
<img width="412" alt="Schermata 2020-07-02 alle 19 28 10" src="https://user-images.githubusercontent.com/7140210/86391614-5e38fd00-bc9a-11ea-8fcf-0e26004a0d73.png">
Thanks

**Comment by ognjentodic** [comment]
MKL is necessary, it's a BLAS library, and kaldi needs one. As Yanda mentioned, when you compile linux binaries depending on how things are setup, you may end up with a lot of object files (which are safe to remove); if you compile with static flag each binary will be linked against bunch of kaldi object files (that's why Dan suggested compiling it with shared flag)... 

You can also dive into different directories under kaldi to see which of those take up space... This is what I get on an OS X box with static flag and before removing .o files).

```
du -hs kaldi/*
 12K	kaldi/CMakeLists.txt
 20K	kaldi/COPYING
4.0K	kaldi/INSTALL
4.0K	kaldi/README.md
100K	kaldi/cmake
 12K	kaldi/docker
2.5G	kaldi/egs
1.4M	kaldi/misc
196K	kaldi/scripts
7.0G	kaldi/src
1.6G	kaldi/tools
112K	kaldi/windows
```
(ignore the size of the egs directory, which has some additional data not relevant to this discussion)

Compiling with --shared will make src directory much smaller... 

Kaldi forum is much better/preferable for these types of questions. Also, getting some local unix system admin help (if possible) will be beneficial, as most of these questions are not kaldi related.

**Comment by nshmyrev** [comment]
> Are MKL necessary if I want to use kaldi in cpu version?

MKL is not really necessary, we are mostly using openblas:

If you just need a kaldi decoder, you do not need kaldi binaries at all, you can compile your binary and delete everything else. Compiled and stripped Kaldi binaries for decoding are just 2Mb, the rest is operating system. You can check our Kaldi docker here for details:

https://github.com/alphacep/vosk-server/blob/master/docker/Dockerfile.kaldi-vosk-server

https://hub.docker.com/repository/docker/alphacep/kaldi-vosk-server/tags

It is just 300Mb, it could be even less if you remove installed g++ and squash the image.

**Comment by simonefrancia** [comment]
@nshmyrev thank you very much for your response! 
The fact is that my code uses some script like ... that are located in `tools/` or `src/` dir. 
And if I do `rm-rf /opt/kaldi/`, those files are not found.
How can I face that?
Thanks

**Comment by nshmyrev** [comment]
> And if I do rm-rf /opt/kaldi/, those files are not found.

Leave the files you need? Copy them to some other place and strip the binaries? It should be pretty straightforward.

**Comment by kkm000** [comment]
@simonefrancia 
> I tried to enter inside a container and delete all these files. Then I went out , stopped the container and commit it as Docker image but nothing changed in terms of size.

Docker works by layering images. So when you bootstrapped a container and deleted files, Docker added another layer, with an indication that these files were removed. This can only increase image size, if only by a little, but cannot decrease it.

The only way to really get rid of files is delete them at the same Dockerfile that creates the image. Another option is make a build, then add another FROM clause that starts from a base image, and copy only what is necessary. Depends on [how far do you want to go](https://github.com/burrmill/burrmill/blob/master/lib/build/kaldi/build_kaldi.sh)—note that this thing runs in a container, but then packages Kaldi, its .so libraries and OpenFST all in one tarball to be rolled out on a machine where its dependencies are already present. So the image built here is not for running Kaldi in it.

This is how I install [MKL](https://github.com/burrmill/burrmill/blob/master/lib/build/mkl/build_mkl.sh) and [CUDA](https://github.com/burrmill/burrmill/blob/master/lib/build/cuda/build_cuda.sh) in Docker. Each of the directories has its own Dockerfile. Note these are non-runnable "drone" images, that are [layered over another, runnable one](https://github.com/burrmill/burrmill/blob/master/lib/build/kaldi/builder/Dockerfile.cudamkl), containing the toolchain and compile-time dependencies for build only, and only unpacked like archives at deployment time, again to hardware, not into a container. But you will probably benefit from that trick: maintain them independently and add to your image separately, so you may avoid rebuilding a huge image in one step (like downloading MKL, even if trimmed down, downloading CUDA, running installers for them). Also, you can pre-build an image with Kaldi tools and dependencies. This can help modularize and speed up the build, even if you create a runnable container in the end. Use the previously linked Dockerfile as an example when bootstrapping the build. The image named `cxx`, referred by it, [contains all the tools and dependencies required to compile Kaldi](https://github.com/burrmill/burrmill/blob/master/lib/build/cxx/Dockerfile) _except_ CUDA and MKL. You can also prebuild a starting image like this, and then start with these 3 images, which will improve repetitive long installs; all that remains is pull and compile Kaldi. As long as you have them cached on your machine, they are instantly accessible.

For MKL, you need only 4 debs, and 3 more which are listed as dependencies, but their version is not known and extracted from the 4 initial deb control files, so there is some grepping required. Good thing you can use this script nearly wholesale. This slashes close to 1G. dpkg cries its heart out with warnings about missing dependent packages, but they are not really required for either build or run time. Not tested with MKL 2020. 

How much of CUDA I save I do not remember, but you certainly do not want all the Eclipse add-ons in your image. The `rm` near the end does it. 

Also (and I forgot to do that in the CUDA script, but [the one for cxx that I already linked above has it](https://github.com/burrmill/burrmill/blob/master/lib/build/cxx/Dockerfile)), whenever you use `apt update`, do `rm -rf /var/lib/apt/lists/*` at the end: this saves another 200MB.

When you build Kaldi with `--shared`, there also .*.la files in addition to *.o that you can kill. When statically, both *.la and really huge *.a archives. To go even leaner, you can delete source files, the .git/ directory (150MB), and uninstall gcc, binutils, autoconf, automake, and maybe lib*-dev packages with headers that you won't need at runtime, but these are comparatively small.

I'd say if you make an image under 5-7G, considering Kaldi, CUDA and MKL, that's normal. Statically compiled Kaldi binaries only weigh over 10G, shared are much smaller.

NVMe, although expensive, pay for themselves if you do stuff like that on your machine. If you use SATA SSDs, better get two smaller ones and RAID0 them (striping) than one large drive.

**Comment by kkm000** [comment]
@nshmyrev:
> strip the binaries

When Kaldi binaries fail on a KALDI_ASSERT, they print a symbolic backtrace, which is always helpful. It's important to keep in mind that image stripping costs a feature, so this is a balancing act.
