### ISSUE TITLE
Cuda 11 support?

### ISSUE THREAD

**Issue by proycon** [kaldi-asr/kaldi#4152]
It seems cuda 11 is currently not supported yet. The configure script fails with the following error:

```
Unsupported CUDA_VERSION (CUDA_VERSION=11_0), please report it to Kaldi mailing list, together with 'nvcc -h' or 'ptxas -h' which lists allowed -gencode values...
```

**Comment by jtrmal** [comment]
:)
have you read the error message?

**Comment by kkm000** [comment]
We do not support CUDA 11 yet. If you have a very latest GPU, you can rely on load-time PTX compilation , it's not that bad  (under a second, probably), compared to total executable's runtime.

I'm closing this. If you have hardware that would benefit from it for Kaldi specifically (keep in mind we only use 32-bit floats), feel free to comment, @-mention me please, and I'll try to figure out what a roadmap would be.

**Comment by nshmyrev** [comment]
For information, CUDA 11 supported enabled in commit c0ac791ceb on October 17, 2022

**Comment by loretoparisi** [comment]
@nshmyrev I do not find any kaldi container with CUDA 11 support. I'm getting on Sagemaker this error
```bash
nnet3-align-compiled: error while loading shared libraries: libcudart.so.10.0: cannot open shared object file: No such file or directory
```
because sagemaker comes wtih CUDA >=11.7:
```bash
sh-4.2$ ls /usr/local/cuda
cuda/      cuda-11.7/ cuda-11.8/ cuda-12.0/ cuda-12.1/ cuda-12.2/ 
sh-4.2$ ls /usr/local/cuda
```
