### ISSUE TITLE
the different returns with the "ComputeFeatures"

### ISSUE THREAD

**Issue by AliceAndIron** [kaldi-asr/kaldi#4165]
hi, dear
 I write a online service with the kaldi dynamic lib； I find a very strange question, sometimes, I use  the same audio and atrributes, call the ComputeFeatures twice to get mfcc features, it returns the different results. The two requests are absolutely independent. it's rarely

**Comment by danpovey** [comment]
Could be to do with dithering, setting --dither=0.0 may fix it (in that
case set --energy-floor to a nonzero value, like 0.1)

**Comment by AliceAndIron** [comment]
thanks, it solved my problem.
