### ISSUE TITLE
Installation on openSUSE : dependency checks : zypper

### ISSUE THREAD

**Issue by colbec** [kaldi-asr/kaldi#417]
I'm running openSUSE Leap 42.1 with Gnome.
When I run the dependency check in tools I am told to go to apt-get to fetch packages for atlas.
I think I already have atlas development libraries (~3.10.2) installed.
If I ignore the message and run make then kaldi goes to source and fetches an earlier version.
Of course this might be deliberate...
When I look at the code for dependency check I'm puzzled by the order of events.
I have apt-get installed so the if at line 66 gets a true, but the references to zypper look like they are deactivated, or don't get a chance to see that I have the libs.
If I can help provide library details for opensuse to get the check working by all means ping back.

**Comment by danpovey** [comment]
If you are using apt-get then it looks for atlas libraries with these names:
 if ! dpkg -l | grep -E 'libatlas3gf|libatlas3-base' >/dev/null; then
Perhaps yours have different names?  What are your atlas libraries named
as?  Provide fuller details.
The 'going to source' is just for the headers- more convenient to get them
directly, as different systems put them in different places
Dan





On Thu, Dec 24, 2015 at 10:55 AM, Colin Beckingham <notifications@github.com

**Comment by colbec** [comment]
@danpovey Thx for response.
On my system apt-get is installed as part of some compatibility packages, however `dpkg -l` returns empty, so grep won't find anything.

>\> zypper se libatlas3
Loading repository data...
Reading installed packages...
S | Name            | Summary                                     | Type      
--+-----------------+---------------------------------------------+-----------
  | libatlas3       | Automatically Tuned Linear Algebra Software | srcpackage
i | libatlas3       | Automatically Tuned Linear Algebra Software | package   
i | libatlas3-devel | Development libraries for ATLAS             | package   

From file list:
>libatlas3 - Automatically Tuned Linear Algebra Software
/etc/ld.so.conf.d/atlas-x86_64.conf
/usr/lib64/atlas
/usr/lib64/atlas/libsatlas.so.3
/usr/lib64/atlas/libsatlas.so.3.0
/usr/lib64/atlas/libtatlas.so.3
/usr/lib64/atlas/libtatlas.so.3.0

From line 109:
> zypper search -i | grep -E 'libatlas3|libatlas3-devel'
i | libatlas3    | Automatically Tuned Linear Algebra Software  | package
i | libatlas3-devel     | Development libraries for ATLAS           | package

**Comment by danpovey** [comment]
check_dependencies.sh is really mostly for informational purposes, to help
the user.
If you think the kind of situation where apt-get is installed by zypper is
the primary installer is common, then it would be possible to change the
checks for `which apt-get` to `which apt-get && ! which zypper`
You could submit a pull request for this after checking.
Dan


On Fri, Dec 25, 2015 at 12:09 AM, Colin Beckingham <notifications@github.com

**Comment by colbec** [comment]
@danpovey Good suggestion. I modified the suggested change to enclose it in parentheses otherwise the script generates a spurious comment "/usr/bin/apt-get".
> kaldi/tools/extras> ./check_dependencies.sh
./check_dependencies.sh: all OK.

As to whether the zypper+apt-get is a common feature on openSUSE, apt-get appears in two packages in Leap: bash-completion and zypper-aptitude. The former seems to be an important collection of functions and does not want to go away without complaint; I'm taking this as a hint that it will be part of all openSUSE Leap installs. However I also run a server with openSUSE 12.3 and there is no apt-get on that machine. Leap is pretty recent (November 2015). So my situation might be unusual, and as you say the check is just trying to be helpful.

The only remaining thing is that when make runs and gets the headers it finds a different version 3.8.3 which is not the same as the existing libraries. Make runs fine for tools and src, just something to bear in mind if one day the build cannot find a reference from the headers. Maybe things should stay as they are.

**Comment by danpovey** [comment]
OK, thanks.
I'll commit a change for this soon.
Yes, it's not ideal that the ATLAS headers are older, but the interface is
very stable- they wouldn't change existing functions, to avoid breaking
binary compatibility; they would just add new ones.  It's way easier to get
them than to go poking around for the system headers.
Dan

**Comment by danpovey** [comment]
Fixed- closing issue.
