### ISSUE TITLE
Cudadecoder compile error with gcc 4.8

### ISSUE THREAD

**Issue by QIU-Shuo** [kaldi-asr/kaldi#4173]
In line [851](https://github.com/kaldi-asr/kaldi/blob/f58364b3b939f8d38c6d330b29a8f46335e21004/src/cudadecoder/cuda-decoder.h#L851), 852 in cuda-decoder.h, compiling with gcc 4.8 will raise the following error:
``Error: ‘atomic_uint64_t’ in namespace ‘std’ does not name a type``

According to this [thread](https://stackoverflow.com/questions/41541283/atomic-uint32-t-in-namespace-std-does-not-name-a-type-error), ``atomic_uint64_t`` seems not introduced until gcc 7. Fixed by changing to ``std::atomic<std::uint32_t>``

**Comment by kkm000** [comment]
Could you please send a PR? I do not think I'll find gcc4.8 anywhere around. Only please use `std::atomic<std::uint64_t>` to match the missing typedef (that's 64, not 32).

**Comment by QIU-Shuo** [comment]
Sure.

**Comment by QIU-Shuo** [comment]
Correction: I made a mistake in my previous post during copy-pasting. The original type is ``atomic_uint32_t``. So the corresponding type should be ``std::atomic<std::uint32_t>``.
