### ISSUE TITLE
Worse results after RNNLM rescoring

### ISSUE THREAD

**Issue by sazhok** [kaldi-asr/kaldi#4174]
After src/cudadecoderbin/batched-wav-nnet3-cuda2 decoding I rescored with larger n-gram that showed some improvement. 
Further rescoring with an RNNLM made results worsen. 
In similar issue in https://groups.google.com/g/kaldi-help/c/eeUJ0ZEhwek/m/3xmyKRUEAgAJ
it was found a bug related to how the rescoring algorithm treats non-deterministic input.
It would be helpful for me to know if the bug have been fixed, as well as other suggestions.

**Comment by kkm000** [comment]
@sazhok, please add the exact commands that you used.

@danpovey, do you remember if that has been taken care of?

**Comment by sazhok** [comment]
@kkm000, after rescoring with RNNLM got `lat.gz` and scored it with:
```
lattice-scale --inv-acoustic-scale=$scale "ark:zcat PATH/TO/lat.gz|" ark:- |
lattice-add-penalty --word-ins-penalty=$wip ark:- ark:- |
lattice-best-path ark:- "ark,t:|int2sym.pl -f 2- PATH/TO/words.txt > hyp.txt"
```
and, to get a ctm-file, also tried:
```
lattice-add-penalty --word-ins-penalty=$wip "ark:zcat PATH/TO/lat.gz |" ark:- | 
lattice-1best --lm_scale=$scale ark:- ark:- | 
lattice-align-words PATH/TO/word_boundary.int PATH/TO/final.mdl ark:- ark:- |  
nbest-to-ctm ark:- - > hyp.ctm
```

**Comment by danpovey** [comment]
We would have fixed it although I don't have time to check for the specific
PR.

There's lots of reasons why it might not be better, or course.  Maybe the
LM itself was worse.

**Comment by sazhok** [comment]
The summary below may help to figure out the reason.

LMs
Name | Source | Params
-- | -- | --
o3_p7 | Text Corpus 1 | -o 3 -prune 3e-7
o5 | Text Corpus 1 | -o 5
RNNLM | Text Corpus 1 | egs/tedlium/s5_r2/local/rnnlm/tuning/run_lstm_tdnn.sh


Decoding/rescoring

Exp | Module, params | LM (and lattice) inputs | Output Lattice | Best WER
-- | -- | -- | -- | --
Exp1 | CPU based |   |   |  
Exp1-1 | nnet3bin/nnet3-latgen-faster-parallel (-acwt 1.0 --post-decode-acwt 10.0) | o3_p7 | lat1 | 27.1
Exp1-2 | egs/wsj/s5/steps/lmrescore_const_arpa.sh | o5, lat1 | lat2 | 26.0
Exp1-3 | scripts/rnnlm/lmrescore_pruned.sh --max_ngram_order 5 --lattice_prune_beam 4 | RNNLM, lat2 | lat3 | 25.0
Exp2 | GPU decoding + CPU rescoring |   |   |  
Exp2-1 | cudadecoderbin/batched-wav-nnet3-cuda2 --extra-left-context 200 | o3_p7 | lat4 | 27.4
Exp2-2 | egs/wsj/s5/steps/lmrescore_const_arpa.sh | o5, lat4 | lat5 | 26.1
Exp2-3 | scripts/rnnlm/lmrescore_pruned.sh --max_ngram_order 5 --lattice_prune_beam 4 | RNNLM, lat5 | lat6 | 41.3

AM of TDNN_LSTM type is the same for both Exp1 and Exp2 and LMs are shared between experiments in accordance with names.

Rescoring a lattice, received after CPU based `nnet3-latgen-faster-parallel` (Exp1-2), improves WER using the mentioned RNNLM (Exp1-3). Whereas, after `batched-wav-nnet3-cuda2`, WER gets worse when rescoring with same RNNLM (Exp2-3).

**Comment by kkm000** [comment]
@sazhok, thanks, the table is very helpful! Nearly doubling the WER is ridiculous, something is very wrong. Could you please repeat the decode Exp2-3 with:

 1. `--normalize true`.
 2. `--acwt 1.0`
 3. Both of the above together.

When changing acwt, take care of `--inv-acoustic-scale` to `lattice-scale`.

I suspect that something is wrong with acoustic weights on the output of `batched-wav-nnet3-cuda2`: they are either scaled differently (not multiplied by 10), or do not add up close to 1 as in the case nnet3-latgen-faster-parallel.

I do not really know if egs/wsj/s5/steps/lmrescore_const_arpa.sh sensitive to acoustic weight. For the sake of experiment, let's assume it's not. In Exp1-2 it sees scaled AM weights, in Exp2-2 the weights out of the CUDA decoder, which I also do not remember if scaled or not, but I think not.

**Comment by kkm000** [comment]
First of all, double-check if you are not rescaling AM weights twice.

**Comment by sazhok** [comment]
The solution came with your advice 2. The produced lattice grew twice comparing to Exp1-3 and 2-3, so hypotheses populated sufficiently :) Item 1 took pretty much time, however, showed no improvement. 1 and 2 together took twice more time comparing to 1 and showed WER comparable to 2.
Many thanks for your assistance!

**Comment by v-yunbin** [comment]
RNNLM really had  a bad prefomence
**decode:**
%WER 50.37 [ 3031 / 6018, 315 ins, 1078 del, 1638 sub ] offline_test/result_tdnn_augmentation//cer_9_1.0
%WER offline_test/result_tdnn_augmentation//cer_10_0.0:%SER 99.54 [ 216 / 217 ]

**trigram rescore**
%WER 47.91 [ 2883 / 6018, 293 ins, 1103 del, 1487 sub ] offline_test/rescore_result_tdnn_augmentation//cer_10_0.5
%WER offline_test/rescore_result_tdnn_augmentation//cer_10_0.0:%SER 99.54 [ 216 / 217 ]

**RNNlM rescore**
%WER 51.76 [ 3115 / 6018, 291 ins, 1143 del, 1681 sub ] offline_test/rescore_rnnlm_result//cer_7_0.5
%WER offline_test/rescore_rnnlm_result//cer_10_0.0:%SER 99.54 [ 216 / 217 ]
