### ISSUE TITLE
make depend error: cblas.h not found

### ISSUE THREAD

**Issue by abavisani** [kaldi-asr/kaldi#4175]
In src/ I used the following config:

`./configure --shared --openblas-root=/home/name/.conda/envs/mypython/`

to provide the location of OpenBLAS where I have access. But then when I run `make depend`, I get several fatal errors. Here is the first one:

```
g++ -M -std=c++11 -I.. -isystem /home/aliabavi/kaldi/tools/openfst-1.6.7/include -O1  -Wall -Wno-sign-compare -Wno-unused-local-typedefs -Wno-deprecated-declarations -Winit-self -DKALDI_DOUBLEPRECISION=0 -DHAVE_EXECINFO_H=1 -DHAVE_CXXABI_H -DHAVE_OPENBLAS -I/usr/include -m64 -maltivec -mcpu=power8 -mtune=power8 -mpower8-vector -mvsx -pthread -g -fPIC -DHAVE_CUDA -I/usr/local/cuda/include -fPIC -pthread -isystem /home/aliabavi/kaldi/tools/openfst-1.6.7/include mle-diag-gmm.cc model-test-common.cc mle-am-diag-gmm.cc full-gmm-test.cc diag-gmm-normal.cc decodable-am-diag-gmm.cc ebw-diag-gmm-test.cc model-common.cc full-gmm-normal.cc diag-gmm.cc indirect-diff-diag-gmm.cc am-diag-gmm-test.cc full-gmm.cc mle-diag-gmm-test.cc ebw-diag-gmm.cc mle-full-gmm.cc mle-full-gmm-test.cc diag-gmm-test.cc mle-am-diag-gmm-test.cc am-diag-gmm.cc >> .depend.mk
In file included from ../matrix/cblas-wrappers.h:29:0,
                 from matrix-lib-test.cc:31:
../matrix/kaldi-blas.h:99:21: fatal error: cblas.h: No such file or directory
   #include "cblas.h"
                     ^
compilation terminated.

```
when I search for `cblas.h`, I found one in `/home/name/.conda/envs/mypython/lib/python3.6/site-packages/torch/include/caffe2/utils/` but I am not sure if it is related to what Kaldi wants. 

How can I fix this?

**Comment by kkm000** [comment]
Looks like you misunderstood the purpose of the switch. It's not where configure/make _will put_ OpenBLAS. It's where you _already_ have it installed.

We have a script `tools/extras/install_openblas.sh`. It downloads and compiles the library for your CPU, which is usually more performant than a prepackaged one which you install with yum or apt or whatever package manager you have.

If you want to use a system OpenBLAS, if it's already installed as a package, use `--mathlib=OPENBLAS` instead. We'll use system include and lib paths to locate it.

Consider MKL if you can install it. It has a better performance, and is the default. The helper script is `tools/extras/install_mkl.sh`

---

I am closing this issue for now. If you believe that your issue has not been addressed, please feel free to ping me, and I'll reopen it. @-mention me for a faster response!

**Comment by abavisani** [comment]
Problem is I don't have root privilege on this system and cannot do `sudo`. So most of the scripts you provided as install*.sh will not work for me.

I know that the admin installed OpenBlas on the system. Now when I do `./configure --shared --mathlib=OPENBLAS` here is the outcome:

```
Backing up kaldi.mk to kaldi.mk.bak ...
Checking compiler g++ ...
Checking OpenFst library in /home/aliabavi/kaldi/tools/openfst-1.6.7 ...
Checking cub library in /home/aliabavi/kaldi/tools/cub-1.8.0 ...
Doing OS specific configurations ...
On Linux: Checking for linear algebra header files ...
./configure: FATAL: OpenBLAS not found in '../tools/OpenBLAS/install'.
```

> --mathlib=OPENBLAS

**Comment by nshmyrev** [comment]
> Problem is I don't have root privilege on this system and cannot do sudo. So most of the scripts you provided as install*.sh will not work for me.

Kaldi installation does not require sudo. Run `extras/install_openblas.sh` from tools folder, it will compile openblas for you.
