### ISSUE TITLE
egs/aspire audio file naming mismatch

### ISSUE THREAD

**Issue by ZimingY** [kaldi-asr/kaldi#4186]
in aspire, the names inside the file $targets_dir/targets.scp are start with "rvb1_", while others are using "rvb1-",
Then in steps/nnet3/train_raw_rnn.py, when we create the dev and val dataset, it can not find the target matrix because of the name mismatch. 

currently i add two lines before steps/nnet3/train_raw_rnn.py
`mv $targets_dir/targets.scp $targets_dir/targets_tmp.scp`
 `sed 's/./-/5' $targets_dir/targets_tmp.scp > $targets_dir/targets.scp`
to avoid this problem. 

But it would be nice if this can be fixed when creating it 

> steps/nnet3/get_egs_targets.sh: feature type is raw
> steps/nnet3/get_egs_targets.sh: working out number of frames of training data
> steps/nnet3/get_egs_targets.sh: working out feature dim
> steps/nnet3/get_egs_targets.sh: creating 568 archives, each with 19938 egs, with
> steps/nnet3/get_egs_targets.sh:   20 labels per example, and (left,right) context = (103,67)
> steps/nnet3/get_egs_targets.sh:   ... and (left-context-initial,right-context-final) = (24,46)
> steps/nnet3/get_egs_targets.sh: Getting validation and training subset examples.
> run.pl: job failed, log is in exp/segmentation_1a/tdnn_stats_asr_sad_1a/egs/log/create_train_subset.log
> run.pl: job failed, log is in exp/segmentation_1a/tdnn_stats_asr_sad_1a/egs/log/create_valid_subset.log
> Error detected while creating train/valid egs
> Traceback (most recent call last):

**Comment by kkm000** [comment]
We just committed a change which seems to fix the same issue. Please update Kaldi, check and let us know if this was it: https://github.com/kaldi-asr/kaldi/pull/4169/files

**Comment by ZimingY** [comment]
> We just committed a change which seems to fix the same issue. Please update Kaldi, check and let us know if this was it: https://github.com/kaldi-asr/kaldi/pull/4169/files

Thanks! yes this solve the problem 👍
