### ISSUE TITLE
CUDA version 11.0 request

### ISSUE THREAD

**Issue by integerblue** [kaldi-asr/kaldi#4190]
CUDA version 11.0 is not supported now in kaldi/src/configure
I am using kaldi of ngc container, which supports 11.0 but not up-to-date.
It seems that nvidia changed some code to support 11.0.

If CUDA 11.0 is supported, I would be very appreciated.
Thanks.

**Comment by kkm000** [comment]
Sure, we eventually will. I am not sure I understand your motivation, tho, to prioritize this. Are there not a container with CUDA 10.2 on NGC? Or are you using a specific device that requires 11.0? PTX still works with the 11.0 runtime.

**Comment by integerblue** [comment]
I thought all ngc containers are working on CUDA 11.0, but they weren't. I am now trying on 20.03 ver, which works on CUDA 10.2. Thank you for suggesting other options.
