### ISSUE TITLE
Installation problem while running Make file in SRC

### ISSUE THREAD

**Issue by devilsboy** [kaldi-asr/kaldi#4194]
I'm new to Kaldi and was installing it according to the documentation and Install file. While in running the `make depend -j 8` command I get the following error:
make[1]: Leaving directory '/home/devilsboy/kaldi/kaldi/src/cudadecoderbin'
make[1]: Leaving directory '/home/devilsboy/kaldi/kaldi/src/nnet3'
make[1]: Leaving directory '/home/devilsboy/kaldi/kaldi/src/cudadecoder'
make[1]: Leaving directory '/home/devilsboy/kaldi/kaldi/src/rnnlmbin'
make[1]: Leaving directory '/home/devilsboy/kaldi/kaldi/src/latbin'
make[1]: Leaving directory '/home/devilsboy/kaldi/kaldi/src/nnet3bin'
make[1]: Leaving directory '/home/devilsboy/kaldi/kaldi/src/chainbin'
make[1]: Leaving directory '/home/devilsboy/kaldi/kaldi/src/nnet2bin'

Also attached below is the screenshot of the output I got:
![Screenshot from 2020-07-28 00-25-27](https://user-images.githubusercontent.com/44058062/88580177-e4155180-d068-11ea-9a30-aa73c47aeb94.png)

**Any help ASAP in resolving this would be really appreciated.**
Thanks

**Comment by jtrmal** [comment]
it's not an error -- all looks fine
y.

**Comment by danpovey** [comment]
and please  dont open github issues on these kinds of things!
