### ISSUE TITLE
Parallelization in Kaldi

### ISSUE THREAD

**Issue by Momina12** [kaldi-asr/kaldi#4197]
Hi,

Hope you are doing well.

Sir I am running training on a server with 64 processors and 125.5 GB memory. I want parallization, so in cmd.sh script, I have set --mem equals to 110 GB and --no-of-jobs=62 in order to train my model. But unfortunately, I can't see the efficient parallization in System Monitor.

Am I doing somthing wrong? If yes, then please tell me how to speed up training process? 

Kind Regards,

**Comment by danpovey** [comment]
this kind of q. should be on kaldi-help, but it's a little vague.  not on github.
