### ISSUE TITLE
Pybind make test core dumped

### ISSUE THREAD

**Issue by LeonWlw** [kaldi-asr/kaldi#4199]
I got recipe from https://github.com/kaldi-asr/kaldi/tree/pybind11,then begin to make. When I cd into src/pybind, make is done, but make test error.

python3 ./dlpack_pybind_test_gpu.py
LOG ([5.5.1049-e0347]:SelectGpuDevice():cu-device.cc:172) Select gpu id 0 out of 7 (starting from 0)
LOG ([5.5.1049-e0347]:SelectGpuDevice():cu-device.cc:184) CUDA setup operating under Compute Exclusive Mode.
LOG ([5.5.1049-e0347]:FinalizeActiveGpu():cu-device.cc:358) The active GPU is [0]: Unknown GPU  free:0M, used:0M, total:0M, free/total:-nan version 7.0
make[1]: *** [test] Floating point exception (core dumped)
make[1]: Leaving directory `/data/code/kaldi-pybind11/src/pybind/dlpack'
make: *** [test] Error 1

Is pybind11 not ready for test? Or what does this error relate to?? Can someone please help me fix this?

**Comment by danpovey** [comment]
not ready
