### ISSUE TITLE
internal compiler error 

### ISSUE THREAD

**Issue by deeshantk** [kaldi-asr/kaldi#4212]
I am using ubuntu 20.04. While following kaldi INSTALL instructions in src, "make" it gives the error 
![Screenshot from 2020-08-06 19-46-14](https://user-images.githubusercontent.com/44977226/89542668-97c2d200-d81d-11ea-94ef-065dd2fe89f7.png)

My g++ version 
![Screenshot from 2020-08-06 19-47-59](https://user-images.githubusercontent.com/44977226/89542810-cb9df780-d81d-11ea-83b0-c4fbad306891.png)

I have followed all previous instructions from tools and src directories with success. 

Thanks

**Comment by danpovey** [comment]
Probably a bug in that specific compiler version, try upgrading the compiler.
