### ISSUE TITLE
Need unique file names in egs/babel/s5d/local/prepare_stm.pl 

### ISSUE THREAD

**Issue by ssarfjoo** [kaldi-asr/kaldi#4213]
The `egs/babel/s5d/local/prepare_stm.pl` code expects to have unique wav filenames.  E.g., If the content of `reco2file_and_channel` file in data folder is like
```
fldr1_name fldr1_name 1
fldr2_name fldr2_name 1
``` 
Where both `fldr1_name` and `fldr2_name` are used as reco and file name. The content of wav.scp file is like:
```
fldr1_name fldr1/name.wav
fldr2_name fldr2/name.wav
``` 

This code updates the `reco2file_and_channel` to:
```
fldr1_name name 1
fldr2_name name 1
```
In addition, it updates the `stm` and `char.stm` by using `name` as the filename. This will cause to choose the wrong file for decoding when the wav file names are not unique. Please investigate this problem.

Best regards,
Saeed

**Comment by danpovey** [comment]
Scripts in local/ are specific to a database (BABEL in this case), they are not intended to be generic.  Unless something is going wrong with BABEL data, thsi is not a bug.
