### ISSUE TITLE
install_openblas.sh fails with JSONDecodeError (and uses the wrong python version?)

### ISSUE THREAD

**Issue by Patronics** [kaldi-asr/kaldi#4215]
I'm Attempting to install Kaldi (on an admittedly non-standard system, a [Picroft](https://mycroft-ai.gitbook.io/docs/using-mycroft-ai/get-mycroft/picroft) installation on a Raspberry Pi 3 B+), after following the instructions of check_dependencies.sh to install the prerequisite dependencies with apt-get, the installation of openblas is failing with the error
```
/usr/bin/gfortran
Traceback (most recent call last): 
   File "<string>", line 1 in <module>
   File "/usr/lib/python3.7/json/__init__.py", line 296 in load
       parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
   File "/user/lib/python3.7/json/decoder.py" , line 337, in loads
       returm _default_decoder.decode(s)
   File "/usr/lib/python3.7/json/decoder.py". line 355, in raw_decode
       raise JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```
Apologies for any typos in the above error log, I'm posing this from a different device, so it's typed by hand. 

I noticed a previous step in the install process said it was putting a symlink for python 2.7 higher up in the PATH than the default for Python 3.6. Given that the above traceback uses python3.7 libraries, I assume that didn't work? Also what was the command it gave to reverse that if needed? it's beyond my scrollback history, and I can't find it in the documentation.

**Comment by Patronics** [comment]
I was able to work around this issue by using `apt-get install libopenblas-dev`, though it's unclear if the apparent python version mismatch will cause issues later on (or why the instructions don't suggest just using apt for libopenblas)?

**Comment by danpovey** [comment]
Maybe packages weren't widely available when we started using OpenBLAS.
Sometimes system packages aren't too fast though, as they are not always
well specialized to the hardware.

**Comment by kkm000** [comment]
@Patronics, you did the right thing. The Raspberry sports a tiny CPU, and compiling OpenBLAS on it is time-consuming, and may run our of RAM (if you have 512MB, you cannot parallelize make even if you have 4 physical cores). Do not do premature optimization. Later, if, and only if you identify the packaged OpenBLAS as the culprit for not meeting your performance goal, then download OpenBLAS sources and cross-compile it for your specific CPU on your normal desktop.

---
I am closing this issue for now. If you believe that your issue has not been addressed, please feel free to ping me, and I'll reopen it. @-mention me for a faster response!
