### ISSUE TITLE
i run thchs30 tri4b error

### ISSUE THREAD

**Issue by Mryangkaitong** [kaldi-asr/kaldi#4224]
steps/align_fmllr.sh --nj 2 --cmd run.pl data/mfcc/train data/lang exp/tri4b exp/tri4b_ali
steps/align_fmllr.sh: feature type is lda
tree-info exp/tri4b/tree 
tree-info exp/tri4b/tree 
steps/align_fmllr.sh: compiling training graphs
make-h-transducer --disambig-syms-out=exp/tri4b/graph_word/disambig_tid.int --transition-scale=1.0 data/graph/lang/tmp/ilabels_3_1 exp/tri4b/tree exp/tri4b/final.mdl 
fsttablecompose exp/tri4b/graph_word/Ha.fst data/graph/lang/tmp/CLG_3_1.fst 
fstminimizeencoded 
fstrmepslocal 
fstrmsymbols exp/tri4b/graph_word/disambig_tid.int 
fstdeterminizestar --use-log=true 
steps/align_fmllr.sh: aligning data in data/mfcc/train using exp/tri4b/final.alimdl and speaker-independent features.
steps/align_fmllr.sh: computing fMLLR transforms
ERROR: VectorFst::Read: Read failed: <unspecified>
ERROR (fstdeterminizestar[5.5.766~1-f01a43]:ReadFstKaldi():kaldi-fst-io.cc:40) Could not read fst from standard input

[ Stack-Trace: ]
fstdeterminizestar(kaldi::MessageLogger::LogMessage() const+0xb1a) [0x55b4bac24cc4]
fstdeterminizestar(kaldi::MessageLogger::LogAndThrow::operator=(kaldi::MessageLogger const&)+0x21) [0x55b4bab820bb]
fstdeterminizestar(fst::ReadFstKaldi(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)+0x470) [0x55b4babac54e]
fstdeterminizestar(main+0x2c1) [0x55b4bab802a3]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xe7) [0x7f30251a2b97]
fstdeterminizestar(_start+0x2a) [0x55b4bab7fefa]

kaldi::KaldiFatalErrorERROR: FstHeader::Read: Bad FST header: -
ERROR (fstrmsymbols[5.5.766~1-f01a43]:ReadFstKaldiGeneric():kaldi-fst-io.cc:59) Reading FST: error reading FST header from standard input

[ Stack-Trace: ]
fstrmsymbols(kaldi::MessageLogger::LogMessage() const+0xb1a) [0x55da78dabfb8]
fstrmsymbols(kaldi::MessageLogger::LogAndThrow::operator=(kaldi::MessageLogger const&)+0x21) [0x55da78d259fd]
fstrmsymbols(fst::ReadFstKaldiGeneric(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool)+0x1c2) [0x55da78d2c4e2]
fstrmsymbols(main+0x3bb) [0x55da78d24cc5]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xe7) [0x7f9300116b97]
fstrmsymbols(_start+0x2a) [0x55da78d2482a]

kaldi::KaldiFatalErrorERROR: FstHeader::Read: Bad FST header: -
ERROR (fstrmepslocal[5.5.766~1-f01a43]:ReadFstKaldi():kaldi-fst-io.cc:35) Reading FST: error reading FST header from standard input

[ Stack-Trace: ]
fstrmepslocal(kaldi::MessageLogger::LogMessage() const+0xb1a) [0x555a7f8f9aae]
fstrmepslocal(kaldi::MessageLogger::LogAndThrow::operator=(kaldi::MessageLogger const&)+0x21) [0x555a7f88015b]
fstrmepslocal(fst::ReadFstKaldi(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)+0x1ba) [0x555a7f87f32a]
fstrmepslocal(main+0x1fc) [0x555a7f86a2e6]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xe7) [0x7f10f0cdab97]
fstrmepslocal(_start+0x2a) [0x555a7f86a00a]

kaldi::KaldiFatalErrorERROR: FstHeader::Read: Bad FST header: -
ERROR (fstminimizeencoded[5.5.766~1-f01a43]:ReadFstKaldi():kaldi-fst-io.cc:35) Reading FST: error reading FST header from standard input

[ Stack-Trace: ]
fstminimizeencoded(kaldi::MessageLogger::LogMessage() const+0xb1a) [0x55a8064b1fba]
fstminimizeencoded(kaldi::MessageLogger::LogAndThrow::operator=(kaldi::MessageLogger const&)+0x21) [0x55a80643538f]
fstminimizeencoded(fst::ReadFstKaldi(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)+0x1ba) [0x55a806433c93]
fstminimizeencoded(main+0x171) [0x55a80641dceb]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xe7) [0x7f5ff790ab97]
fstminimizeencoded(_start+0x2a) [0x55a80641da9a]

**Comment by danpovey** [comment]
likely the mkgraph.sh script failed due to not enough memory.  search google for similar errors / discussion
