### ISSUE TITLE
Docker images no longer built

### ISSUE THREAD

**Issue by kir4h** [kaldi-asr/kaldi#4228]
While checking https://hub.docker.com/r/kaldiasr/kaldi/tags, I noticed Docker images haven't been updated in the latest 3 months.

I was trying to understand what is broken and ended up in https://github.com/kaldi-asr/kaldi/issues/3284 where the Docker discussion started and there is a link to https://github.com/mdoulaty/kaldi-image-builder that I guess has been used for pushing those images.

From that conversation, [it seems](https://github.com/kaldi-asr/kaldi/issues/3284#issuecomment-499549272) @mdoulaty is running this on his account, but I'm not sure if this is automated or just a manual trigger from his side. So I guess maybe @mdoulaty can shed some light on what is the current status (as maybe the reason is that there was an automatic procedure that is now stopped, or there was a manual procedure that is no longer done to trigger the builds)

Thank you!

**Comment by kir4h** [comment]
> @kir4h, @mdoulaty, since you guys automate the process, could you please continue work on reducing the image size? Here's an easy 1G catch for ya).
> 
> ```
> $ du -hc $(find /opt/intel -name '*.a') | tail -1
> 936M    total
> $ du -hs ~/work/kaldi/.git
> 139M    /home/kkm/work/kaldi/.git
> ```
> 
> If you want to go a bit bolder and shave another 350MB, you can remove MKL kernels for pre-AVX CPUs (Pentium 4 and early Core/Core 2) CPUs, and Knight Landing MIC accelerators (hardly anyone has them, they were sparklingly unsuccessful, and very likely won't virtualize in Docker anyway). It's also safe to remove threading layer libraries and the iLP64 interface, since we link against the sequential layer only (libmkl_sequential.so, does not have `_thread` in file name) and LP64:
> 
> ```
> $ du -hc $(find /opt/intel -type f -regex '.*\(_mc.?\|_mic\|_thread\|_ilp64\)\.so') | tail -1
> 352M    total
> ```
> 
> This and the *.a removes more than half of MKL disk space use.

These are straightforward, if ok I will create the PR straight away

> Also, it often happens that latest commits break stuff. I'd release a week-old code, because it would be more stable. You may need some Git-fu for this; to get the SHA of the latest 1-week-old commit, use `git rev-list`, e. g.
> 
> ```
> $ git rev-list --first-parent -n1 --until=1week master
> 8eb569178d6926b979726df6b1a8b99c0784a52d
> $ git -c advice.detachedHead=false checkout $(git rev-list --first-parent -n1 --until=1week master)
> HEAD is now at 8eb569178 [scripts] Extend run.pl with more flexibility to repeat failed tasks (#4219)
> ```
> 
> You cannot do that from a shallow clone, of course. Setting the option `-c advice.detachedHead=false` only suppresses a whole page of useless chatter, not essential.

Indeed, the fact of not having versioning/releases brings this kind of fun to the table. I'd say we can focus on this later, once we have a leaner image.

> Debian 9 is quite old. You can easily go with `FROM debian:buster-slim` (the "slim" versions do not have manpages and other nonessential stuff, no difference otherwise). Also, I would not really use the minor tag on it. Buster feels pretty dated already: I'm using it as my work distro, and installing a few things from the backport feed already. Unlike Ubuntu, Debian is extremely conservative, so pulling the latest certainly won't cause problems.

Agreed. My only concern is how to ensure nothing is broken (once the build passes)

> Another thing to consider is building with '-O2' and '-mavx'. I do not think anyone could have any luck finding a non-AVX-capable CPU these days. All FST stuff works significantly faster with it.
> 
> ```
> export CXXFLAGS='-mavx -O2 -fuse-ld=gold -fdiagnostics-color=always'
> ```
> 
> does the trick for Kaldi, but in `tools/`, it's required to pass it to make explicitly (it's our flop, AFAICR):
> 
> ```
> make CXXFLAGS="$CXXFLAGS" OPENFST_CONFIGURE="--disable-dependency-tracking"
> ```
> 
> `ld-gold` shaves a bit of build time v. the default classic `ld`, as does `--disable-dependency-tracking` for OpenFST.

Not really familiar with this, I can bilndly follow your recommendations =)

**Comment by kkm000** [comment]
@mdoulaty, @kir4h, so this is done? Tag me if you want to reopen.

**Comment by mdoulaty** [comment]
@kkm000 no, it's not done
I'm still trying to figure out where/how to resume building the images...

**Comment by kir4h** [comment]
@kkm000 let's keep it open until the automated building of images is back.

@mdoulaty Since this might take a while, could we manually build/push current version? So that we can start taking advantage of the reduced image size (asking because you have the required push permissions)

**Comment by mdoulaty** [comment]
sure, just pushed the latest CPU image based on the updated Docker file to dockerhub

**Comment by kir4h** [comment]
> sure, just pushed the latest CPU image based on the updated Docker file to dockerhub

Thanks!

**Comment by kkm000** [comment]
@mdoulaty, @kir4h, thanks for the feedback, I'll keep this open then.

**Comment by jtrmal** [comment]
resolved, the docker images were updated and now will be updated on weekly schedule automatically
