### ISSUE TITLE
Do the  compile options -O1 and -O3 influence the decoding performance? 

### ISSUE THREAD

**Issue by lonelybeansprouts** [kaldi-asr/kaldi#4235]
I tried both -O1 and -O3 , but didn't see a big difference of decoding performace.

**Comment by danpovey** [comment]
They should make a fairly big difference to the decoder code itself, but not to the neural net code (which goes to BLAS mostly).  Of course you'd need to "make clean" and then make, as dependencies on the Makefile aren't tracked.  Questions like this are better to kaldi-help.
