### ISSUE TITLE
Add std:: to vector to compile under g++ 5.4.0

### ISSUE THREAD

**Issue by 4321louis** [kaldi-asr/kaldi#4236]
I just want to preface this with I don't have too much coding experience but I saw a pull req #1479 and I have the same problem with a different file
![image](https://user-images.githubusercontent.com/31239298/91251640-39936a00-e79f-11ea-8861-d87e095cac16.png)
I probably should submit a pull request for this but I have no idea what Im doing so I don't know how to that.
Basically the changes:
In src/online2bin/online2-wav-nnet3-wake-word-decoder-faster.cc:223
change "static_cast<vector<int32> *>(0)," to "static_cast<std::vector<int32> *>(0),"
In src/online2bin/online2-wav-nnet3-wake-word-decoder-faster.cc:242
change "static_cast<vector<int32> *>(0)," to "static_cast<std::vector<int32> *>(0),"

making this change fixed the compilation error for me. Any tips on how to properly format this post is appreciated

**Comment by danpovey** [comment]
Thanks... please try to make a pull request!
You would first have to make sure you've checked out Kaldi after cloning it
to your own GitHub account.
You'd then do something like:

  git clone <kaldi from your github>
 edit the file
 git add <files you edited>
  git commit -m "Fix compilation error on gcc 5.4.0, vector->std::vector"
 git push origin HEAD:std_vector_fix

(assuming your remote is "origin", which I think it is by default).
Then open the URL it shows on the screen to make a pull request, of if you
dont see one, go to your repo or Kaldi's on the
"Pull Requests" tab and create a pull request to kaldi's master from your
branch std_vector_fix.

Dan

**Comment by 4321louis** [comment]
Thanks Dan,
Turns out the easy way to submit a pull req for something this small is clicking the edit button on the file on github.com and then it will prompt you to either directly merge or submit a pull req after you have edited. I still need to learn what checking out is as well lol.
