### ISSUE TITLE
build error with cu-common.cc

### ISSUE THREAD

**Issue by rkdanrud1342** [kaldi-asr/kaldi#4243]
error with this changes while building kaldi.

cu-common.cc: In function 'const char* kaldi::cusparseGetStatusString(cusparseStatus_t)': cu-common.cc:122:10: error: 'CUSPARSE_STATUS_NOT_SUPPORTED' was not declared in this scope case CUSPARSE_STATUS_NOT_SUPPORTED: return "CUSPARSE_STATUS_NOT_SUPPORTED"; ^ cu-common.cc:123:10: error: 'CUSPARSE_STATUS_INSUFFICIENT_RESOURCES' was not declared in this scope case CUSPARSE_STATUS_INSUFFICIENT_RESOURCES: return "CUSPARSE_STATUS_INSUFFICIENT_RESOURCES";

**Comment by rkdanrud1342** [comment]
I commented that lines and try to build.

It works.

commented lines : cu-common.cc 122, 123 line

**Comment by danpovey** [comment]
thx, I reverted the commit that caused the problem.
