### ISSUE TITLE
Breaks when CUDA isn't found

### ISSUE THREAD

**Issue by yurivict** [kaldi-asr/kaldi#4251]
```
CUDA_TOOLKIT_ROOT_DIR not found or specified
-- Could NOT find CUDA (missing: CUDA_TOOLKIT_ROOT_DIR CUDA_NVCC_EXECUTABLE CUDA_INCLUDE_DIRS CUDA_CUDART_LIBRARY) 
fatal: not a git repository (or any of the parent directories): .git
fatal: not a git repository (or any of the parent directories): .git
CMake Error at cmake/VersionHelper.cmake:11 (string):
  string sub-command STRIP requires two arguments.
Call Stack (most recent call first):
  CMakeLists.txt:157 (get_version)
```

CUDA is not available on my platform (FreeBSD).

**Comment by kkm000** [comment]
Turn off CUDA support explicitly. I do not know the variable name (CMake build is unsupported), but `cmake -L` will list all variables.

**Comment by kkm000** [comment]
This has not been reported or reproduced elsewhere.

I am closing this issue for now. If you believe that your issue has not been addressed, please feel free to ping me, and I'll reopen it. @-mention me for a faster response!
