### ISSUE TITLE
nnet3 nvidia-smi -c 3

### ISSUE THREAD

**Issue by Liujingxiu23** [kaldi-asr/kaldi#4255]
ERROR (nnet3-train[5.5]:AllocateNewRegion():cu-allocator.cc:519) Failed to allocate a memory region of 8088715264 bytes.  Possibly this is due to sharing the GPU.  Try switching the GPUs to exclusive mode (nvidia-smi -c 3) and using the option --use-gpu=wait to scripts like steps/nnet3/chain/train.py.  Memory info: free:15426M, used:17053M, total:32480M, free/total:0.474948 CUDA error: 'out of memory'

I have no sudo authority to set nvidia-smi to -c=3. I change the init-jobs and final-jobs equal to 1, but the same error happens. 

How can  I train the nnet3 with gpu with default setting?

**Comment by wbgxx333** [comment]
you can see this:
http://kaldi-asr.org/forums.html?place=msg%2Fkaldi-help%2FIckTczEIZ-k%2FO7xhk-5KDAAJ

**Comment by Liujingxiu23** [comment]
It works！Thanks! @wbgxx333

**Comment by AlexandderGorodetski** [comment]
It seams that upper mentioned link is not available. Could you please write here what is the solution. Thanks a lot.
