### ISSUE TITLE
GoP Scoring for unspoken audio

### ISSUE THREAD

**Issue by saireddy12** [kaldi-asr/kaldi#4259]
I am trying to get GoP scores I used Script in egs/gop/s5/run.sh I am getting the scores but the problem is when the audio spoken is only half of the given transcript even then I am getting phoneme scores of the words that are not even spoken in the audio 
Here are the detailed steps I used  :- 
```
# Compute Log-likelihoods
  steps/nnet3/compute_output.sh --cmd "$cmd" --nj $nj \
    --online-ivector-dir $ivector data/$data $model exp/probs_$data

#align transcripts 
  steps/nnet3/align.sh --cmd "$cmd" --nj $nj --use_gpu false \
    --online_ivector_dir $ivector data/$data $lang $model $dir

  # make a map which converts phones to "pure-phones"
  # "pure-phone" means the phone whose stress and pos-in-word markers are ignored
  # eg. AE1_B --> AE, EH2_S --> EH, SIL --> SIL
  local/remove_phone_markers.pl $lang/phones.txt $dir/phones-pure.txt \
    $dir/phone-to-pure-phone.int

  # Convert transition-id to pure-phone id
  $cmd JOB=1:$nj $dir/log/ali_to_phones.JOB.log \
    ali-to-phones --per-frame=true $model/final.mdl "ark,t:gunzip -c $dir/ali.JOB.gz|" \
      "ark,t:-" \| utils/apply_map.pl -f 2- $dir/phone-to-pure-phone.int \| \
      gzip -c \>$dir/ali-pure-phone.JOB.gz   || exit 1;
fi

  # The outputs of the binary compute-gop are the GOPs and the phone-level features.
 
  $cmd JOB=1:$nj $dir/log/compute_gop.JOB.log \
    compute-gop --phone-map=$dir/phone-to-pure-phone.int $model/final.mdl \
      "ark,t:gunzip -c $dir/ali-pure-phone.JOB.gz|" \
      "ark:exp/probs_$data/output.JOB.ark" \
      "ark,t:/output/gop.JOB.txt" "ark,t:$dir/phonefeat.JOB.txt"   || exit 1;
```

explanation:
transcript:-"HELLO GOOD MORNING HOW ARE YOU "
Audio:-content spoken "Hello GOOD"
I am getting gop values of other four words phones also that to there are not miss-pronunciations, scores are good.

**Comment by danpovey** [comment]
You'd have to create the supervision as an FSA that allowed those deletions at the start and end, e.g. could enter sentences anywhere and leave anywhere.  The code the compiles the training graph can accept FSAs as input (compile-train-graphs-fsas).  This will of course require some changes to the existing scripts.
See steps/cleanup/find_bad_utts.sh  as an example of a script that creates decoding graphs specific to the utterance.
