### ISSUE TITLE
small change in nnet-chain-example.cc

### ISSUE THREAD

**Issue by wjyiwjyi** [kaldi-asr/kaldi#4260]
In GetChainComputationRequest, there is a line
`if (node_index == -1 &&
         !nnet.IsOutputNode(node_index))
       KALDI_ERR << "Nnet example has output named '" << name
                 << "', but no such output node is in the network.";`
I think && here should be changed into ||.

**Comment by danpovey** [comment]
You are right.  Can you make a PR?

**Comment by wjyiwjyi** [comment]
Finished.
