### ISSUE TITLE
configure / make fail to find MKL on Ubuntu 20.04

### ISSUE THREAD

**Issue by 4gra** [kaldi-asr/kaldi#4262]
Steps to reproduce:

```
$ cat /etc/os-release 
NAME="Ubuntu"
VERSION="20.04.1 LTS (Focal Fossa)"
[...]
$ sudo apt install intel-mkl-full gfortran libsox-dev [...etc]
$ git clone https://github.com/kaldi-asr/kaldi.git
$ ls -l /usr/lib/x86_64-linux-gnu/libmkl_*
$ ls -l /usr/include/mkl/
  (i.e. they exist)
$ cd tools
$ extras/check_dependencies.sh
./extras/check_dependencies.sh: Intel MKL is not installed. Run extras/install_mkl.sh to install it.
 [...]
```

I realised the approval of check_dependencies wasn't required to actually make it work, so I just went ahead and made the tools, which worked fine.  But then MKL hit a snag again on building kaldi proper:

```
$ cd ../src
$ ./configure --shared
    (doesn't work)
$ ./configure --shared --mkl-libdir=/usr/lib/x86_64-linux-gnu
   (also doesn't work)
$ CXXFLAGS="-I/usr/include/mkl/" ./configure --shared --mkl-libdir=/usr/lib/x86_64-linux-gnu
MKL configured libs: -L/usr/lib/x86_64-linux-gnu -Wl,-rpath=/usr/lib/x86_64-linux-gnu -lmkl_intel_lp64 -lmkl_core -lmkl_sequential -ldl -lpthread -lm
MKL include directory: -I/usr/lib/x86_64-linux-gnu/../../include
Using Intel MKL as the linear algebra library.
mkl-test.cc:21:10: fatal error: mkl.h: No such file or directory
   21 | #include <mkl.h>
      |          ^~~~~~~
compilation terminated.
***configure failed: Cannot validate the MKL switches ***
```

so, I patched `./configure`:

```diff
diff --git a/src/configure b/src/configure
index e0ac02115..da1253e26 100755
--- a/src/configure
+++ b/src/configure
@@ -266,6 +266,8 @@ configure_mkl_includes() {
   local mklroot=$1 mkllibdir=$2
   if [[ -d $mklroot/include ]]; then
     echo "-I$1/include"
+  elif [[ -d /usr/include/mkl ]]; then
+    echo "-I/usr/include/mkl"
   elif [[ -d $mkllibdir/../../include ]]; then
     echo "-I$mkllibdir/../../include"
   else

```

Now `configure` succeeds:
```
$ CXXFLAGS="-I/usr/include/mkl" ./configure --shared --mkl-libdir=/usr/lib/x86_64-linux-gnu
Configuring KALDI to use MKL.
 [...]
MKL configured libs: -L/usr/lib/x86_64-linux-gnu -Wl,-rpath=/usr/lib/x86_64-linux-gnu -lmkl_intel_lp64 -lmkl_core -lmkl_sequential -ldl -lpthread -lm
MKL include directory: -I/usr/include/mkl
Using Intel MKL as the linear algebra library.
Intel(R) Math Kernel Library Version 2020.0.0 Product Build 20191122 for Intel(R) 64 architecture applications
 [...]
```

but `make` then failed as it passed in a mandatory reference to an include directory "$(MKLROOT)/include".  So, I must confess at this point I lost patience and patched `kaldi.mk` rather than figure out how it's made:

```diff
--- src/kaldi.mk        2020-09-08 20:50:00.000000001 +0100
+++ src/kaldi.mk        2020-09-08 20:51:00.903004252 +0100
@@ -49,17 +49,12 @@
 ifndef OPENFSTLIBS
 $(error OPENFSTLIBS not defined.)
 endif
-ifndef MKLROOT
-$(error MKLROOT not defined.)
-endif
-
-MKLLIB ?= $(MKLROOT)/lib/intel64
 
 CXXFLAGS = -std=c++11 -I.. -isystem $(OPENFSTINC) -O1 $(EXTRA_CXXFLAGS) \
            -Wall -Wno-sign-compare -Wno-unused-local-typedefs \
            -Wno-deprecated-declarations -Winit-self \
            -DKALDI_DOUBLEPRECISION=$(DOUBLE_PRECISION) \
-           -DHAVE_EXECINFO_H=1 -DHAVE_CXXABI_H -DHAVE_MKL -I$(MKLROOT)/include \
+           -DHAVE_EXECINFO_H=1 -DHAVE_CXXABI_H -DHAVE_MKL -I/usr/include/mkl \
            -m64 -msse -msse2 -pthread \
            -g
```

having done this, `make` finally succeeded and kaldi appears to have been built completely successfully.

So at the least, the auto-detection is broken, and at worst the build process simply can't cope with the include/library structure imposed by an upstream Ubuntu install of intel-mkl.

**Comment by danpovey** [comment]
Thanks a lot!
The script doesn't seem to have a separate variable for the MKL include
dir.  But that setup still seems to fit the pattern, where
MKLROOT=/usr and MKLLIBDIR=/usr/lib/x86_64-linux-gnu.
@kkm is there any chance you could take a look at this at some point? We
should make it automatically work for Ubuntu.

**Comment by danpovey** [comment]
@kkm000  any time to work on this?

**Comment by kkm000** [comment]
Sorry, misstated the ticket. Yes, will fix.

**Comment by kkm000** [comment]
@4gra, is it critical to use the repackaged MKL that comes with Ubuntu? It is much better to remove the `intel-mkl-full` Ubuntu package, and use our script extra/install_mkl.sh from Intel repository.

**Comment by 4gra** [comment]
It's not _crucial_, but I administer a large system which deploys these packages across many machines and it would make my life significantly easier if all the packages get along. If not I'd have to distribute the MKL twice on those systems, which is obviously not great.

**Comment by kkm000** [comment]
My huge problem with Ubuntu has always been that they distribute a deluge
of updates, the system literally changes daily. Installing just *an* MKL
version might not cut it. I understand that a responsible cluster admin
would 'apt-mark hold' it, but don't expect that of an average user.

On the other hand, MKL is very stable and backward-compatible, and I do not
remember any issues from upgrading it (not that I do that often). Let me
see how Ubuntu has actually repackaged it.

**Comment by 4gra** [comment]
@kkm000 (slightly off-topic but I somewhat agree. The deluge of updates for their own sake can be counterproductive and we hold many packages, MKL included, for a stable environment. We intend to stick to 20.04 LTS for some time, I hope its rate of churn will reduce over time.)

**Comment by kkm000** [comment]
Not until 22.04 LTS is released, in my sour experience. Then they trickle
down to security updates only.

I remember about your issue, just busy with other stuff. It would be great
to install MKL as a package without the need for an additional script, I
only need to figure out their packaging. I think the " intel-mkl-full" is a
"virtual" package with no files, but "Depends:" on the next version with a
strict equality, forcing the version upgrade. They upgrade it every time
new MKL packages hit their feed. I'm guessing, but it;s the same thing as
e.g. linux-image pseudo-package. At the least, a better idea would be to
install a specific version instead. You never know when Ubuntu decides to
upgrade your MKL..

I'd recommend the same with the kernel, because you never know if DKMS
would be able to compile the NVIDIA driver for the suddenly updated kernel.
Been there, done that. Security updates are important, but
just-because-it's-the-latest aren't much. The downside is that the removal
of the old package versions (those with the version in the name, like
"linux-image-5.8.0-0.bpo.2-amd64" becomes your responsibility.

**Comment by 4gra** [comment]
Thanks for your careful consideration.

**Comment by kkm000** [comment]
Sure. Did it work for you?

**Comment by 4gra** [comment]
I'll be doing a slew of software updates in the next week or so, so I'll get back to you.
