### ISSUE TITLE
[documentation] detail clarification in dummy tutorial

### ISSUE THREAD

**Issue by JohnoverBoard** [kaldi-asr/kaldi#4272]
Hey, brand new to Kaldi - was going through the dummy tutorial and realized that the mentioned 'digits' folder is non-existent now - i am guessing in the time thus far it has been updated. I was hoping the maintainer keeps track of this matter. 

https://kaldi-asr.org/doc/kaldi_for_dummies.html#kaldi_for_dummies_audio

**Comment by nshmyrev** [comment]
You are supposed to create it:

> **Your first task**
> Something to begin with - create a folder digits in kaldi/egs/ directory. This is a place where you will put all the stuff related to your project.

**Comment by JohnoverBoard** [comment]
oh my bad. Wow that's record speed by the way. Sorry and thank you!
