### ISSUE TITLE
provide a way to silence kaldi LOGS

### ISSUE THREAD

**Issue by mohamedAlaaK** [kaldi-asr/kaldi#4284]
using this function https://github.com/kaldi-asr/kaldi/blob/master/src/base/kaldi-error.h#L64

we can set verbosity of kaldi output. we can silence kaldi warnings and errors.

but we can't silence the kaldi normal logs itself.

we use kaldi as a library and it would be nice to have a way of to setting the verbosity to 0 for example so that kaldi doesn't print anything to the stderr.

**Comment by nshmyrev** [comment]
You can change log handler with SetLogHandler to empty method:

https://github.com/kaldi-asr/kaldi/blob/76a97983a1250818cc25aeaa1500fb5256df63b2/src/base/kaldi-error.h#L220

**Comment by mohamedAlaaK** [comment]
that makes sense. thank you.
we will try that and if it is working fine i will close this issue.
