### ISSUE TITLE
intel-mkl-64bit-2020.0-088 installation FAILED

### ISSUE THREAD

**Issue by somum** [kaldi-asr/kaldi#4286]
Last modification reported: Wed, 02 Sep 2020 19:11:02 +0000
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
extras/install_mkl.sh: MKL package intel-mkl-64bit-2020.0-088 installation FAILED

What is the reason here ?

**Comment by danpovey** [comment]
there will have been output before that.  please search google for it.  it's a known issue I think.

**Comment by somum** [comment]
> there will have been output before that. please search google for it. it's a known issue I think.

Do you think I issued here without googling? Tried different options like "sudo tools/extras/install_mkl.sh -sp debian intel-mkl-64bit-2020.0-088" etc etc. But every time its showing error.

**Comment by danpovey** [comment]
A lot of people do ask without googling.
There just isn't enough to go on there.  If that was really all the output
the script produced, then perhaps you could add some kind of verbose option
to the invocation of apt-get.  See if it has such an option.
