### ISSUE TITLE
Train custom model on Indian accent

### ISSUE THREAD

**Issue by pallav11** [kaldi-asr/kaldi#4293]
Hi,

I have audio & transcribe data for Indian accent, Kindly suggest from where i can get the data for creating 'language' directories (lexicons, phones etc).

**Comment by danpovey** [comment]
You could use CMUDict.  Look at what the mini_librispeech and librispeech recipes do, I think they use that.

**Comment by pallav11** [comment]
Thanks for the guidance, however mini_librispeech and librispeech does provide the "librispeech-lexicon.txt" and "librispeech-vocab.txt" which is of US english accent and not of Indian English accent.

**Comment by danpovey** [comment]
We don't normally use accent-specific lexicons, partly because they're not
generally available, and partly because it doesn't make so much difference.
