### ISSUE TITLE
How to convert *.ark file in egs to a text file?

### ISSUE THREAD

**Issue by eggplant95** [kaldi-asr/kaldi#4294]
I have trained a chain model with the script "./steps/nnet3/chain/train.py" which generates  some  files in the directory of "egs".
However,  when I try to convert the "ark" files in "egs" by using "copy-feats", I couldn't get the text file as I expected, the informations are as follows:

`copy-feats ark:exp/chain_baseline/tdnn_sp/egs/lat_special.1.ark ark,t:1.txt
copy-feats ark:exp/chain_baseline/tdnn_sp/egs/lat_special.1.ark ark,t:1.txt 
WARNING (copy-feats[5.5]:Open():util/kaldi-table-inl.h:513) Failed to open stream exp/chain_baseline/tdnn_sp/egs/lat_special.1.ark
ERROR (copy-feats[5.5]:SequentialTableReader():util/kaldi-table-inl.h:860) Error constructing TableReader: rspecifier is ark:exp/chain_baseline/tdnn_sp/egs/lat_special.1.ark
`
What should I do if I want to get the information in these ark files？
 I'd be most grateful for your help.

**Comment by danpovey** [comment]
Those files are lattices, you'd use lattice-copy to copy them.

**Comment by eggplant95** [comment]
Thank you very much :)
