### ISSUE TITLE
Kaldi install fails to install openFST

### ISSUE THREAD

**Issue by Jeevesh8** [kaldi-asr/kaldi#4299]
When I tried to install Kaldi, I get the following error, when trying to run ```./configure``` in ```src``` directory :
```
Configuring KALDI to use OPENBLAS.
Checking compiler g++ ...
Checking OpenFst library in  ...
***configure failed: Could not find file /include/fst/fst.h:
  you may not have installed OpenFst. See ../tools/INSTALL ***
```

To reproduce : [Colab Notebook]( https://colab.research.google.com/drive/1atM7UpsPIBt8EVdUi8u-PUJi0s4RqcsW?usp=sharing) .
I was reading ```kaldi/tools/Makefile``` which had ```$FSTROOT``` as ```../tools/openfst``` , but running ```make``` in ```tools/``` didn't make any directory by the name of ```openfst```.

**Comment by jtrmal** [comment]
there might have been some error reported during running the make in tools/
go to kaldi/tools and run just "make" and check for errors
y.

**Comment by isdanni** [comment]
Had the same error when running `./configure --openblas-root=../tools/OpenBLAS/install --use-cuda=no`. The environment is Py2 Conda and I was having a hard time install `zlib1g-dev`. Was wondering if anyone knows how to solve this?

(NOT a root user and have to use anaconda)

**Comment by Jeevesh8** [comment]
My error got solved. It was something with colab that was troubling, I guess. The same script I provided earlier, ran fine later on. Earlier, no OpenFST was getting installed, but later on when I ran again, it ran fine. @isdanni you should run 
```sudo apt-get install zlib1g-dev``` , as the output suggests. I don't think it can be done from within anaconda. You should ask your admin to install it, if possible.

**Comment by isdanni** [comment]
> My error got solved. It was something with colab that was troubling, I guess. The same script I provided earlier, ran fine later on. Earlier, no OpenFST was getting installed, but later on when I ran again, it ran fine. @isdanni you should run
> `sudo apt-get install zlib1g-dev` , as the output suggests. I don't think it can be done from within anaconda. You should ask your admin to install it, if possible.

I see. Thanks!

**Comment by kkm000** [comment]
I am closing this issue for now. If you believe that your issue has not been addressed, please feel free to ping me, and I'll reopen it. @-mention me for a faster response!

**Comment by mhybritz** [comment]
`
Configuring KALDI to use MKL.
Checking compiler g++ ...
Checking OpenFst library in  ...
***configure failed: Could not find file /include/fst/fst.h:
  you may not have installed OpenFst. See ../tools/INSTALL ***
`

Still not working in Colab

**Comment by oshindow** [comment]
> `Configuring KALDI to use MKL. Checking compiler g++ ... Checking OpenFst library in ... ***configure failed: Could not find file /include/fst/fst.h: you may not have installed OpenFst. See ../tools/INSTALL ***`
> 
> Still not working in Colab

Same isssue when the openfst was not installed completely.

**Comment by Naveenravi07** [comment]
@oshindow @mhybritz  Did you find any fixes ?  I am also having  same error

**Comment by simonepalomba** [comment]
installed fst 1.6.9 manually 

then ./configure --fst-root=/usr/local/ --fst-version=1.6.9

**Comment by Jasmin-Palakkonil** [comment]
I am trying to install kaldi-ctc. But failing while configuring openfst-1.8.4. 

./configure --mathlib=OPENBLAS --fst-root=/home/user/kaldi/tools/openfst-1.8.4
Configuring ...
Checking OpenFST library in /home/user/kaldi/tools/openfst-1.8.4 ...
Checking OpenFst library was patched.
**  ERROR  **
** /home/user/kaldi/tools/openfst-1.8.4/include/fst/minimize.h seems not to be patched:
patch not applied?  FST tools will not work in our recipe.


This is the error I am getting. I have patch the minimize.h file and cleaned and installed openfst again. But still not working. It is repeating the error. Can anyone help me regarding this?
