### ISSUE TITLE
steps/diagnostic/analyze_lattice_depth_stats.py raise typeerror at line 92: byte-like object is required, not str

### ISSUE THREAD

**Issue by xingchensong** [kaldi-asr/kaldi#4307]
Hi , I found that at [steps/diagnostic/analyze_lattice_depth_stats.py:line92](https://github.com/kaldi-asr/kaldi/blob/edf6963c3f79a5da49bcf547ab8c53b002ea0fe4/egs/wsj/s5/steps/diagnostic/analyze_lattice_depth_stats.py#L92):
```py
for line in gzip.open(args.ali_per_frame):
   uttid, ali = line.split(" ", 1)
   ali_per_frame[uttid] = ali
```
`line` is a byte-like object by default, it should be decoded to utf-8 before split:
```py
for line in gzip.open(args.ali_per_frame):
   uttid, ali = line.decode('utf-8').split(" ", 1)
   ali_per_frame[uttid] = ali
```
I can get correct lattice analysis after change this.

**Comment by danpovey** [comment]
What is your Python version (python -v)?  I'm surprised `line` is a bytes object because 'open' would normally give you strings in python3.  Perhaps a locale issue?   Did you change any locale settings, e.g. in path.sh did you override `export LC_ALL=C` ?    (I'm not sure what difference this would make, but I just want to get all info on the table).
Normally we prefer the shebang to say `#!/usr/bin/env python3`, so we know which version is used, not `python`.  That may be the right fix.

**Comment by xingchensong** [comment]
`python --version` gives me `Python 3.8.3` and i create `.use_default_python` in `kaldi/tools/python` to avoid using python2.x, i didn't change locale settings in path.sh. I encountered this when I run timit recipe, I have not tested on other recipes, perhaps it is just a locale issue caused by some other environment settings. I will close this issue since this workaround is enough for me on my local machine.

**Comment by danpovey** [comment]
It looks like `mode` defaults to 'rb'.  Perhaps changing the `open` to
`gzip.open(args.ali_per_frame, encoding='utf-8'):`
would be the right fix.  Could you please try that?

**Comment by danpovey** [comment]
.. and also if you change the shebang from python to python3 that would be
good.

**Comment by xingchensong** [comment]
I change the shebang from python to python3 and add two configurations in `gzip.open` like this:
```py
for line in gzip.open(args.ali_per_frame, mode='rt', encoding='utf-8'):
    uttid, ali = line.split(" ", 1)
    ali_per_frame[uttid] = ali
```
This works well, many THX!

**Comment by danpovey** [comment]
I think you don't need 'mode' if you set 'encoding'.  Can you please make a PR with the change?

**Comment by xingchensong** [comment]
> I think you don't need 'mode' if you set 'encoding'. Can you please make a PR with the change?

Hi dan, I tried only set the `encoding`, however it will raise `valueerror: argument 'encoding' not supported in binary mode`, I think this may be caused by the default `mode` (which is set to 'rb'), thus I explicitly specified it.

Sure, I will make a PR for this.

**Comment by danpovey** [comment]
OK thanks.
In some other utilities, 'mode' is deprecated, but I guess not for gzip.

**Comment by xingchensong** [comment]
done.
