### ISSUE TITLE
compilation error 

### ISSUE THREAD

**Issue by bin-chen-techlabs** [kaldi-asr/kaldi#4312]
I have this error when trying to compile the latest kaldi today. 
This happens when I run make -j 8 in the src directory, after run the make in the tools directory.

#$ cudafe++ --c++14 --gnu_version=70500 --allow_managed  --m64 --parse_templates --gen_c_file_name "/tmp/tmpxft_0000309b_00000000-5_batched-static-nnet3-kernels.compute_75.cudafe1.cpp" --stub_file_name "tmpxft_0000309b_00000000-5_batched-static-nnet3-kernels.compute_75.cudafe1.stub.c" --module_id_file_name "/tmp/tmpxft_0000309b_00000000-3_batched-static-nnet3-kernels.module_id" "/tmp/tmpxft_0000309b_00000000-4_batched-static-nnet3-kernels.cpp4.ii" 
In file included from batched-threaded-nnet3-cuda-pipeline2.cc:23:0:
../cudadecoder/batched-threaded-nnet3-cuda-pipeline2.h: In member function ‘void kaldi::cuda_decoder::BatchedThreadedNnet3CudaPipeline2::SetSymbolTable(fst::SymbolTable*)’:
../cudadecoder/batched-threaded-nnet3-cuda-pipeline2.h:261:51: error: no matching function for call to ‘kaldi::cuda_decoder::BatchedThreadedNnet3CudaOnlinePipeline::SetSymbolTable(fst::SymbolTable*&)’
     cuda_online_pipeline_.SetSymbolTable(word_syms);
                                                   ^
In file included from ../cudadecoder/batched-threaded-nnet3-cuda-pipeline2.h:28:0,
                 from batched-threaded-nnet3-cuda-pipeline2.cc:23:
../cudadecoder/batched-threaded-nnet3-cuda-online-pipeline.h:219:8: note: candidate: void kaldi::cuda_decoder::BatchedThreadedNnet3CudaOnlinePipeline::SetSymbolTable(const fst::SymbolTable&)
   void SetSymbolTable(const fst::SymbolTable &word_syms) {
        ^~~~~~~~~~~~~~
../cudadecoder/batched-threaded-nnet3-cuda-online-pipeline.h:219:8: note:   no known conversion for argument 1 from ‘fst::SymbolTable*’ to ‘const fst::SymbolTable&’
#$ g++ -std=c++14 -D__CUDA_ARCH__=750 -c -x c++  -DCUDA_DOUBLE_MATH_FUNCTIONS -fPIC -I"/usr/local/cuda/include" -I"/home/ubuntu/work/kaldi/tools/cub-1.8.0" -I".." -I"../" -I"/home/ubuntu/work/kaldi/tools/openfst-1.6.7/include" "-I/usr/local/cuda/bin/../targets/x86_64-linux/include"   -isystem "/home/ubuntu/work/kaldi/tools/openfst-1.6.7/include" -m64 "/tmp/tmpxft_0000309b_00000000-5_batched-static-nnet3-kernels.compute_75.cudafe1.cpp" -o "batched-static-nnet3-kernels.o" 
#$ ptxas -arch=sm_30 -m64  --generate-line-info "/tmp/tmpxft_00003091_00000000-12_cuda-decoder-kernels.compute_30.ptx"  -o "/tmp/tmpxft_00003091_00000000-15_cuda-decoder-kernels.compute_30.cubin"

**Comment by danpovey** [comment]
I think I fixed it via #4313, please try now.

**Comment by bin-chen-techlabs** [comment]
I tried to compile it again. It works! Thanks a lot!
