### ISSUE TITLE
How would include-log-softmax affect chain model performance

### ISSUE THREAD

**Issue by housebaby** [kaldi-asr/kaldi#4316]
Hello @danpovey 
It is  obeserved from chain model output that the "output probability" is kind of flat, compared to CTC sharp peak .
I wonder how include-log-softmax=true  would affect model performance , and why it is not used in the default config.
If we add softmax , is it possible to improve the decoding speed, as the output probability will be more discriminative so that more unlikely paths will be pruned? 
Thank you.

**Comment by danpovey** [comment]
> Hello @danpovey <https://github.com/danpovey>
> It is obeserved from chain model output that the "output probability" is
> kind of flat, compared to CTC sharp peak .
>
Yes, this is expected...

> I wonder how include-log-softmax would affect model performance , and why
> it is not used in the default config.
>

This wouldn't make a difference as the objective function is invariant to
it.
Dan

**Comment by housebaby** [comment]
> This wouldn't make a difference as the objective function is invariant to it. Dan
If include-log-softmax=true won't make any difference, then which part can be tuned to make the probability more discrimitive in chain model?
Thank you very much.

**Comment by danpovey** [comment]
"discriminative" is not well defined here.. it depends what your purpose
is.

**Comment by housebaby** [comment]
Sorry for the  ambiguity.
I mean,  is it possible to make output probability in chain more sharp and less flat ( like CTC) , so that more unlikely paths will be pruned in decoding, thus making the decoding process faster?
I wonder whether it is reasonable to think in this way

**Comment by danpovey** [comment]
It would be necessary to train with CTC as part of the objective.  Not easy
with current code, partly because of the interaction with
context-dependency which makes it a little non-trivial to do it in a
sensible way.

Dan

**Comment by kkm000** [comment]
I am closing this issue. As it stands, it's not easily doable.
