### ISSUE TITLE
 long words in data preparation part of Language recognition task

### ISSUE THREAD

**Issue by ASR2020Guru** [kaldi-asr/kaldi#4318]
Hi there,

When I doing Language recognition task, I have 4 languages, 400 speakers and 100000 sentence in total. so the data preparation files such as spk2utt have long words.

When I doing feature exaction part I get error as below:

```
sid/compute_vad_decision.sh --nj 10 --cmd run.pl data/mfcc/train data/mfcc/train/log data/mfcc/train/data
**Warning it seems not all of the speakers got VAD output (103672 != 103674);
**validate_data_dir.sh will fail; you might want to use fix_data_dir.sh
Created VAD output for train
awk: program limit exceeded: maximum number of fields size=32767
        FILENAME="-" FNR=1 NR=1
```

I know I can install gawk to avoid this error.

I would like to know is it okey to run experiment in such data size(2500 sentences for each speaker, 100000 sentence for each language)?

Thanks

**Comment by kkm000** [comment]
Nothing wrong in principle. I think LibriSpeech has a lot of utterances per speaker, in the same ballpark. If you can use gawk, by all means do. If you cannot, you can split your batches of speaker sentences into more palatable chunks. I do not think you'd get any different results if you make 5 speakers out of every real one and assign 500 sentences to each. 

I am closing this issue for now. If you believe that your issue has not been addressed, please feel free to ping me, and I'll reopen it. @-mention me for a faster response!
