### ISSUE TITLE
how to set parameters for sid/nnet3/xvector/allocate_egs.py(or get_egs.sh) based on my own dataset scenario?

### ISSUE THREAD

**Issue by ASR2020Guru** [kaldi-asr/kaldi#4319]
Hi @tzyll ,

How are you doing
I could not open an issue(enquire) in your GitHub repo, so I open it in here.

I was learning to use your code to do the x-vector based language identification task. [https://github.com/tzyll/kaldi/tree/caser/egs/cslt_cases/olr19](https://github.com/tzyll/kaldi/tree/caser/egs/cslt_cases/olr19) 

I used my own dataset.(4 languages, 4000 speakers, 20 sentences for each speaker, each sentences last 30 seconds)

However, I got `code error: length > utt-length` error at the stage 3.

I tried different parament settings for 

> -num-repeats --min-frames-per-chunk --max-frames-per-chunk --frames-per-iter --num-archives --num-jobs

 . but still get error. 
`sid/nnet3/xvector/get_egs.sh --cmd run.pl --nj 8 --stage 0 --frames-per-iter 1000000000 --frames-per-iter-diagnostic 100000 --min-frames-per-chunk 50 --max-frames-per-chunk 300 --num-diagnostic-archives 3 --num-repeats 5000 data/fbank/train_no_sil exp/xvect/egs
feat-to-dim scp:data/fbank/train_no_sil/feats.scp -
sid/nnet3/xvector/get_egs.sh: Preparing train and validation lists
sid/nnet3/xvector/get_egs.sh: Producing 271 archives for training
sid/nnet3/xvector/get_egs.sh: Allocating training examples
run.pl: job failed, log is in exp/xvect/egs/log/allocate_examples_train.log`

`python sid/nnet3/xvector/allocate_egs.py --num-repeats=5 --min-frames-per-chunk=100 --max-frames-per-chunk=400 --frames-per-iter=1000000000 --num-archives=40 --num-jobs=4 --utt2len-filename=exp/xvect/egs/temp/utt2num_frames.train --utt2int-filename=exp/xvect/egs/temp/utt2int.train --egs-dir=exp/xvect/egs`

![image](https://user-images.githubusercontent.com/71591338/98108952-a9417600-1f01-11eb-9f8b-b6aa790f1808.png)

Based on the above screenshot, my `exp/xvect/egs/temp/ranges.*` files seems not generate enough rows for x-vector training.

Then I tried use other dataset (4 languages, 4000 speakers, 1 sentences for each speaker, each sentences last 10 mins), and used your default parameters settings for `sid/nnet3/xvector/allocate_egs.py`. 
And it worked, but the final test accuracy was lower than 70%.

So I am confused about how should I modify your default parameters settings for `sid/nnet3/xvector/allocate_egs.py` to works 30 seconds sentences.

One more question is : is the deep learning technique such as x-vector embeddings works for only 4-languages language identification task? or 4 languages is not enough for deep learning?

Thanks in advance

**Comment by danpovey** [comment]
@desh2608 do you have time to try to fix this?  Looks like the get_random_utt function is ignoring the min_length parameter, that's the problem I think.  You could come up with an un-tested fix and we cah have @ASR2020Guru test it.

**Comment by tzyll** [comment]
As Dan says, it's the problem of get_random_utt. 

In my own repo, I kept rand until getting utt_len >= length.
https://github.com/tzyll/kaldi/blob/5a3d43250c23cbf54e810b9d9a9db2bb9c8648fc/egs/sre08/v1/sid/nnet3/xvector/allocate_egs.py#L261-L263

**Comment by desh2608** [comment]
This solution seems reasonable to me. We can remove the `length` argument to `get_random_utt`  and instead run a loop until we find an utterance with length > min_length.
@tzyll could you create a PR with this change if @danpovey agrees?

**Comment by tzyll** [comment]
Sure. @desh2608

**Comment by ASR2020Guru** [comment]
Thanks

> As Dan says, it's the problem of get_random_utt.
> 
> In my own repo, I kept rand until getting utt_len >= length.
> https://github.com/tzyll/kaldi/blob/5a3d43250c23cbf54e810b9d9a9db2bb9c8648fc/egs/sre08/v1/sid/nnet3/xvector/allocate_egs.py#L261-L263
> 
> To avoid abandoning too many short utts, you can set args.max_frames_per_chunk smaller.

**Comment by danpovey** [comment]
Only if you can convince yourself somehow that it's not going to loop for
an unreasonable amount of time (or make it warn in a nice but not too
verbose way if it does).
