### ISSUE TITLE
change linux path to windows path

### ISSUE THREAD

**Issue by linzhongzi** [kaldi-asr/kaldi#4326]
When I use vs2017 in win64, I found the problem: "Failed to open table for writing with wspecifier";
By my debugging, i found the solution to fix It.
Just Change linux path to windows path，like:
/C/kaldi/egs/...    to C:/Kaldi/egs/...
So I changed the source code:
\Kaldi\kaldi-5.4\src\util\kaldi-io.cc

`#ifdef KALDI_CYGWIN_COMPAT
#include "util/kaldi-cygwin-io-inl.h"
#define MapOsPath(x) MapCygwinPath(x)
#else  // KALDI_CYGWIN_COMPAT
#if defined(WIN32) 
#define MapOsPath(x) kaldi::MapWindowsPath(x)
#endif
#endif  // KALDI_CYGWIN_COMPAT`
`namespace kaldi {

std::string MapWindowsPath(std::string path) {
	if (path.size() < 3) return path; //at least like: "/c/"
#define max_path 4096
	char resolved_path[max_path] = { 0 };
	if (path.at(0) == '/' && path.at(2) == '/') {
		if ((path.at(1) >= 'a' && path.at(1) <= 'z') ||
			(path.at(1) >= 'A' && path.at(1) <= 'Z')) {
			strcpy(resolved_path, path.c_str());
			resolved_path[0] = resolved_path[1];
			resolved_path[1] = ':';	// /c/... to c:/...
		}
	}
	else {
		_fullpath(resolved_path, path.c_str(), max_path);//#include<stdlib.h>
	}
	return resolved_path;
}
}`

**Comment by danpovey** [comment]
@kkm what do you think about this?  Should we ask for a pull request?

**Comment by kkm000** [comment]
I do not understand where the path of the form `/C/something` is coming from in the first place. @linzhongzi, please explain what you are doing and why.

**Comment by jtrmal** [comment]
looks like a cygwin path

**Comment by kkm000** [comment]
Not really. In Cygwin, Windows drive letters are mounted under /cygdrive or something like that, so it would be /cygdrive/c. MSyS uses /c, /d etc. No Windows Unix-like software that I'm aware of uses /C, with capitalization, by default.

@linzhongzi, when you build Kaldi as you do (not w/ Cygwin), you should use normal Windows paths. I suspect this is a path you specified somewhere, not that Kaldi generated it somehow. To track this down, I need more information.

**Comment by linzhongzi** [comment]
just a little of falt， 
#if defined(WIN32) 
should replace with
#if defined(_MSC_VER)

**Comment by kkm000** [comment]
@linzhongzi, please explain _what_ you are doing and _why_ are you doing that. We need a repro. Not what should we do, rather what you are doing.

**Comment by linzhongzi** [comment]
> @linzhongzi, please explain _what_ you are doing and _why_ are you doing that. We need a repro. Not what _we_ should do, rather what _you_ are doing.

Sorry, I cancel this bug. As there is another problem when the full path is "/dev/null".
Maybe there are a lot of other problems. So I consider to modify the script files.
