### ISSUE TITLE
Documentation (website)

### ISSUE THREAD

**Issue by SylvainVerdy** [kaldi-asr/kaldi#4327]
The website get a connection timed out. Do you have any information about this?

Thanks, :-)

Sylvain

**Comment by SylvainVerdy** [comment]
The website take too much time to display something...

**Comment by jtrmal** [comment]
I'm looking at it.
y.

**Comment by jtrmal** [comment]
should/might be fixed
y.

**Comment by SylvainVerdy** [comment]
yes thank you !
