### ISSUE TITLE
Selection of time-step in tdnn acoustic model (subsampling layer)

### ISSUE THREAD

**Issue by Nian-Chen** [kaldi-asr/kaldi#4338]
Hello @danpovey 
Is there any recipe in kaldi which can help me train the efficient tdnn-model?
I wonder how can I set the time-step in each tdnn layer?
Thank you

**Comment by danpovey** [comment]
Questions like this should go to kaldi-help,
Follow the run.sh in mini_librispeech/s5, that is a fairly typical example.
