### ISSUE TITLE
frame_labels2posterior_mx() takes 1 positional argument but 2 were given

### ISSUE THREAD

**Issue by RuslanSel** [kaldi-asr/kaldi#4340]
I've got an error
TypeError: frame_labels2posterior_mx() takes 1 positional argument but 2 were given

In callhome_diarization/v1/diarization/VB_resegmentation.py
# Initialize the posterior of each speaker based on the clustering result.
   if args.initialize:
	   q = VB_diarization.frame_labels2posterior_mx(init_ref_voiced, args.max_speakers)
   else:
	   q = None

In callhome_diarization/v1/diarization/VB_diarization.py
def frame_labels2posterior_mx(labels):

Thanks in advance.

**Comment by desh2608** [comment]
Hi, can you try replacing the function `frame_labels2posterior_mx(labels)` in  diarization/VB_diarization.py with this, and see if it solves your problem? If it does, could you please open a PR with this change?

```
def frame_labels2posterior_mx(labels, maxSpeakers):
    #initialize from reference
    pmx = np.zeros((len(labels), maxSpeakers))
    pmx[np.arange(len(labels)), labels] = 1
    return pmx
```

**Comment by RuslanSel** [comment]
I tried, but then I had another error, so I just switched to the old code.

**Comment by desh2608** [comment]
Do you remember what the error was? It would be helpful for debugging. Most likely there were minor argument issues introduced in the new version of the `VB_diarization.py`.

**Comment by RuslanSel** [comment]
The errors like
VB_diarization() got an unexpected keyword argument 'VtiEV'
