### ISSUE TITLE
Hang in DDP

### ISSUE THREAD

**Issue by cding-nv** [kaldi-asr/kaldi#4351]
I have filed 2 questions. Thanks for the answer. It's helpful.
    https://github.com/kaldi-asr/kaldi/issues/4346
    https://github.com/kaldi-asr/kaldi/issues/4347
Now, I would like to enable **multiple machines**.

**Test one machine one work size is OK** using the below command.

CUDA_VISIBLE_DEVICES=0 SGE_TASK_ID=1 python3 ./chain/train.py \
--bottleneck-dim 128 \
--checkpoint=exp/chain_pybind/tdnn_sp/train/best_model.pt \
--dir exp/chain_pybind/tdnn_sp/train \
--feat-dim 40 \
--hidden-dim 1024 \
--is-training true \
--ivector-dim 0 \
--kernel-size-list "3, 3, 3, 1, 3, 3, 3, 3, 3, 3, 3, 3" \
--log-level debug \
--output-dim 3424 \
--prefinal-bottleneck-dim 256 \
--subsampling-factor-list "1, 1, 1, 3, 1, 1, 1, 1, 1, 1, 1, 1" \
--train.cegs-dir exp/chain_pybind/tdnn_sp/egs_chain2_for_training \
--train.ddp.init-method tcp://11.238.201.7:7275 \
--train.ddp.multiple-machine false \
--train.ddp.world-size 1 \
--train.den-fst exp/chain_pybind/tdnn_sp/den_fsts/default.den.fst \
--train.dropout-schedule 0,0@0.20,0.5@0.50,0 \
--train.egs-left-context 29 \
--train.egs-right-context 29 \
--train.l2-regularize 5e-5 \
--train.leaky-hmm-coefficient 0.1 \
--train.lr 1e-3 \
--train.num-epochs 1 \
--train.use-ddp true \
--train.valid-cegs-scp exp/chain_pybind/tdnn_sp/processed_egs/train_subset.scp \
--train.xent-regularize 0.1

**Then, I enable multiple machines.**
**First machine, ip is '11.238.201.7 ',**

CUDA_VISIBLE_DEVICES=0 SGE_TASK_ID=1 python3 ./chain/train.py \
--bottleneck-dim 128 \
--checkpoint=exp/chain_pybind/tdnn_sp/train/best_model.pt \
--dir exp/chain_pybind/tdnn_sp/train \
--feat-dim 40 \
--hidden-dim 1024 \
--is-training true \
--ivector-dim 0 \
--kernel-size-list "3, 3, 3, 1, 3, 3, 3, 3, 3, 3, 3, 3" \
--log-level debug \
--output-dim 3424 \
--prefinal-bottleneck-dim 256 \
--subsampling-factor-list "1, 1, 1, 3, 1, 1, 1, 1, 1, 1, 1, 1" \
--train.cegs-dir exp/chain_pybind/tdnn_sp/egs_chain2_for_training \
--train.ddp.init-method tcp://11.238.201.7:7275 \
--train.ddp.multiple-machine true \
--train.ddp.world-size 2 \
--train.den-fst exp/chain_pybind/tdnn_sp/den_fsts/default.den.fst \
--train.dropout-schedule 0,0@0.20,0.5@0.50,0 \
--train.egs-left-context 29 \
--train.egs-right-context 29 \
--train.l2-regularize 5e-5 \
--train.leaky-hmm-coefficient 0.1 \
--train.lr 1e-3 \
--train.num-epochs 1 \
--train.use-ddp true \
--train.valid-cegs-scp exp/chain_pybind/tdnn_sp/processed_egs/train_subset.scp \
--train.xent-regularize 0.1

**second machine, IP is "11.238.201.4"**

CUDA_VISIBLE_DEVICES=0 SGE_TASK_ID=2 python3 ./chain/train.py \
--bottleneck-dim 128 \
--checkpoint=exp/chain_pybind/tdnn_sp/train/best_model.pt \
--dir exp/chain_pybind/tdnn_sp/train \
--feat-dim 40 \
--hidden-dim 1024 \
--is-training true \
--ivector-dim 0 \
--kernel-size-list "3, 3, 3, 1, 3, 3, 3, 3, 3, 3, 3, 3" \
--log-level debug \
--output-dim 3424 \
--prefinal-bottleneck-dim 256 \
--subsampling-factor-list "1, 1, 1, 3, 1, 1, 1, 1, 1, 1, 1, 1" \
--train.cegs-dir exp/chain_pybind/tdnn_sp/egs_chain2_for_training \
--train.ddp.init-method tcp://11.238.201.7:7275 \
--train.ddp.multiple-machine true \
--train.ddp.world-size 2 \
--train.den-fst exp/chain_pybind/tdnn_sp/den_fsts/default.den.fst \
--train.dropout-schedule 0,0@0.20,0.5@0.50,0 \
--train.egs-left-context 29 \
--train.egs-right-context 29 \
--train.l2-regularize 5e-5 \
--train.leaky-hmm-coefficient 0.1 \
--train.lr 1e-3 \
--train.num-epochs 1 \
--train.use-ddp true \
--train.valid-cegs-scp exp/chain_pybind/tdnn_sp/processed_egs/train_subset.scp \
--train.xent-regularize 0.1

**Check port 7275 is ESTABLISHED**
 > tcp        0      0 11.238.201.4:43604      11.238.201.7:7275       ESTABLISHED

**But both machines hang in  DDP**,
` process_job() -> DDP(model, device_ids=[device_id])`

Can you help why it hangs? Thanks.

**Comment by cding-nv** [comment]
This setting  NCCL_SOCKET_IFNAME=bond0 can fix the problem. Thanks.

**Comment by qindazhu** [comment]
Great! BTW, in our original example scripts, I used a shared file as the init_method to support collective communications. Of course this requires that you local cluster support shared file system. I didn't try the tcp approach on differenct machines (one of the reason if the network bandwidth on our cluster is relatively slow, even for internal communication)
https://github.com/kaldi-asr/kaldi/blob/1c573b39899acd90a3d4cf4e8b5284f3a5deb6ef/egs/aishell/s10/local/run_chain.sh#L258

**Comment by kkm000** [comment]
I am closing this issue, as it seems resolved. If you believe that your issue has not been addressed, please feel free to ping me, and I'll reopen it. @-mention me for a faster response!

**Comment by danpovey** [comment]
Mm.    I wonder if nccl is used even if we're not training with GPUs?  Is the communication method configurable?

**Comment by kkm000** [comment]
Apparently, yes and yes, with `--use-ddp`. `'nccl'` backend is hardcoded.
https://github.com/kaldi-asr/kaldi/blob/1c573b39899acd90a3d4cf4e8b5284f3a5deb6ef/egs/aishell/s10/chain/train.py#L234-L239
