### ISSUE TITLE
Makefile does not make contents of kaldi/src/lmbin

### ISSUE THREAD

**Issue by OscarVanL** [kaldi-asr/kaldi#4356]
Hi,

I've been trying to use Kaldi following the [mini-librispeech example](https://medium.com/@qianhwan/understanding-kaldi-recipes-with-mini-librispeech-example-part-1-hmm-models-472a7f4a0488).

First I compiled Kaldi tools 

```
cd tools
extras/check_dependencies.sh
make -j 8
```

Then src:

```
cd src
./configure
make depend -j 8
make -j 8
```

When I get to the stage where I run:
```
utils/prepare_lang.sh data/local/dict_nosp \
  "<UNK>" data/local/lang_tmp_nosp data/lang_nosp
```

It fails with the error:
```
Formatting pruned arpa LMs
local/format_lms.sh: line 53: arpa2fst: command not found
```

As it turns out, the folder where arpa2fst source reside (`kaldi/src/lmbin`) is not compiled by the src makefile.

The fix is simple, to `cd src/lmbin` then `make`.

It seems the src makefile omits compiling lmbin for some reason, maybe this should be added to avoid others experiencing the same issue.

**Comment by OscarVanL** [comment]
I also noticed the same problem for `klaldi/src/latbin` later during this example. Is this intended or have I missed a setup step?

**Comment by jtrmal** [comment]
yeah, there is not a good reason (nor intent) to have this directory be
skipped.
Not sure how to help
y.

**Comment by OscarVanL** [comment]
Maybe it's just omitted from the makefile in `kaldi/src` and needs to be added?

**Comment by jtrmal** [comment]
I just tested it not on kaldi main branch  and seems to work as expected --
can anyone else please check?
y

**Comment by kkm000** [comment]
@OscarVanL, both directories are there. You can see it in the Makefile, as transparent as this
```
SUBDIRS = ... \
          ... \
          bin ...
. . .
all: $(SUBDIRS) matrix/test
    -echo Done
. . .
$(SUBDIRS) : checkversion kaldi.mk mklibdir
    $(MAKE) -C $@
```
If you can repro the issue, please post exact `configure` switches and the details of your OS.

**Comment by OscarVanL** [comment]
I did the whole process again on a new clone of the repo and it worked fine, all those folders were correctly built. How strange...
