### ISSUE TITLE
Errors for submitting SGE tasks

### ISSUE THREAD

**Issue by v-yunbin** [kaldi-asr/kaldi#4358]
I have set up a SGE cluster with only two execution nodes and a nfs system wiht same account and id
When i run conmmands on master ：`queue.pl  JOB=1:2  test.JOB.log echo "hell job JOB"` ，met errors：
```
12/01/2020 22:46:24|worker|master|W|job 84.1 failed on host ubuntu general opening input/output file because: 12/02/2020 11:46:22 [1006:5837]: error: can't open output file "/home/ybZhang/changcheng_asr_ch/./q/test.log": Permission denied
12/01/2020 22:46:24|worker|master|W|rescheduling job 84.1
12/01/2020 22:46:24|worker|master|W|job 84.2 failed on host ubuntu general opening input/output file because: 12/02/2020 11:46:22 [1006:5838]: error: can't open output file "/home/ybZhang/changcheng_asr_ch/./q/test.log": Permission denied
12/01/2020 22:46:24|worker|master|W|rescheduling job 84.2
```
I think the variable ”JOB“ not get  the value from ”1：2“，the right out log should be ”test.1.log，test.2.log“ but not "test.log"

anyone can help me? or met same problem?

**Comment by jtrmal** [comment]
it's a queue submission log it's trying to create, not the task logs --
make sure you can write into that directory (especially if the directory
exists, if you are running queue.pl by hand)
y.
