### ISSUE TITLE
Errors for submitting SGE tasks

### ISSUE THREAD

**Issue by v-yunbin** [kaldi-asr/kaldi#4359]
I have set up a SGE cluster with only two execution nodes and a nfs system wiht same account and id
When i run conmmands on master ：`queue.pl JOB=1:2 test.JOB.log echo "hell job JOB"` ，met errors：

```
12/01/2020 22:46:24|worker|master|W|job 84.1 failed on host ubuntu general opening input/output file because: 12/02/2020 11:46:22 [1006:5837]: error: can't open output file "/home/ybZhang/changcheng_asr_ch/./q/test.log": Permission denied
12/01/2020 22:46:24|worker|master|W|rescheduling job 84.1
12/01/2020 22:46:24|worker|master|W|job 84.2 failed on host ubuntu general opening input/output file because: 12/02/2020 11:46:22 [1006:5838]: error: can't open output file "/home/ybZhang/changcheng_asr_ch/./q/test.log": Permission denied
12/01/2020 22:46:24|worker|master|W|rescheduling job 84.2
```

I think the variable ”JOB“ not get the value from ”1：2“，the right out log should be ”test.1.log，test.2.log“ but not "test.log"
anyone can help me? or met same problem?

**Comment by v-yunbin** [comment]
Do anyone can give some advises?
I can sumit throught "qsub commad" successfully except using "queue.pl"

**Comment by danpovey** [comment]
That is not the normal log, it's a log file where the queue output goes.
Why not read queue.pl?  
It could be a problem with your umask or something.  You need to undertsand UNIX permissions to solve it.  At the very least, `ls -l` that directory.  Ask someone local who knows about UNIX.

**Comment by v-yunbin** [comment]
I‘m sorry for that，I have confirmed that it not the UNIX permissions。

solved，thx
