### ISSUE TITLE
batched-wav-nnet3-cuda2 the audio tail doesn't recognized

### ISSUE THREAD

**Issue by dgxlsir** [kaldi-asr/kaldi#4364]
when I run my script(use batched-wav-nnet3-cuda2 to decode my chain_model), some audio tail doesn't recognized,(1 char or 2 chars lose). I tried to adjust '--max-count',but got no results!
Best regards!

**Comment by danpovey** [comment]
I assume you know about #4365..  (closing duplicate, please use that issue, which has more details).
