### ISSUE TITLE
Wrong argument in kaldi hand-on document - config option

### ISSUE THREAD

**Issue by a2d8a4v** [kaldi-asr/kaldi#4368]
Hello, I found a wrong description when I read this document

[Example of configuring grid software with new-style options](https://kaldi-asr.org/doc/queue.html#parallelization_common_new_example)

the `queue.pl -config conf/no_k20.conf –allow-k20 ` has a wrong argument `-config`, which should be revised as `--config`

Thank you for time to reading

**Comment by danpovey** [comment]
mm, would be  nice if you could make a pull request to fix that.  source is
in src/doc/.

**Comment by a2d8a4v** [comment]
Thank you! @danpovey 
And we support you, don't give up!

**Comment by danpovey** [comment]
Thanks!!

**Comment by kkm000** [comment]
Fixed in #4369.
