### ISSUE TITLE
Make the CUDA device name/memory check to call the CUDA driver API consistently instead of dlopen() just for name/memory checks

### ISSUE THREAD

**Issue by achimnol** [kaldi-asr/kaldi#4370]
I have encountered an issue that the following lines of codes causes some weird library-related errors:

* https://github.com/kaldi-asr/kaldi/blob/6a95a60/src/cudamatrix/cu-device.cc#L539-L564
* https://github.com/kaldi-asr/kaldi/blob/6a95a60/src/cudamatrix/cu-allocator.cc#L285-L326

It seems that there are NO other cases that use this specific `dlopen()` calls in the entire codebase.
With a minimal C++ program with the same mechanism to get the device name and memory information, I confirmed that replacing them with the normal CUDA driver API calls eliminates my problem. (Just like the `_MSC_VER` branch in the codes)

Technically using the CUDA driver APIs consistently will prevent any future potential library issues like me, so I'd suggest to change the above codes.

**Comment by danpovey** [comment]
Mm.  Yeah I think you can make a PR, if you have time, to change that.
This was done so that we could run without the CUDA library on machines
that didn't have it, but I think we can't do that now
for other reasons, so there is probably no point in this.
