### ISSUE TITLE
What is the differece between `egs_left_context` and `left_context` ?

### ISSUE THREAD

**Issue by eggplant95** [kaldi-asr/kaldi#4373]
Hi, I don't quite understand the design of egs in training for chain model, the specific codes are as follows:
`steps/nnet3/chain/train.py`
```shell
egs_left_context = left_context + args.frame_subsampling_factor // 2
    egs_right_context = right_context + args.frame_subsampling_factor // 2
    # note: the '+ args.frame_subsampling_factor / 2' is to allow for the
    # fact that we'll be shifting the data slightly during training to give
    # variety to the training data.
    egs_left_context_initial = (left_context_initial +
                                args.frame_subsampling_factor // 2 if
                                left_context_initial >= 0 else -1)
    egs_right_context_final = (right_context_final +
                               args.frame_subsampling_factor // 2 if
                               right_context_final >= 0 else -1)
```
I am confused about why egs_context equals to model_context plus frame_subsampling_factor // 2, and what is meaning of context_initial? I would be grateful if some one could elaborate on the question. Thank you for your time.

**Comment by danpovey** [comment]
frame_subsampling_factor//2 is to account for frame-shifting that we do for perturbation (shift by -1,0,1 for factor==3).
initial left context: we have less "extra left context" / padding of left-context frames at the start of the utterance (sometimes 0) because it's not necessary but this has to be specified.
