### ISSUE TITLE
nnet3-chain-train2: --out-of-range-regularize=0.01: command not found

### ISSUE THREAD

**Issue by OscarVanL** [kaldi-asr/kaldi#4383]
I'm trying to run the mini_librispeech example. Shortly after the initial acoustic model training begins, the training crashes.

Here's some of the last output lines of `run.sh`.
```
local/chain2/run_tdnn.sh: Preparing initial acoustic model
local/chain2/run_tdnn.sh: about to train model
steps/chain2/train.sh --stage -10 --cmd run.pl --gpu 1 --use-gpu=wait --xent-regularize 0.1 --leaky-hmm-coefficient 0.1 --max-param-change 2.0 --num-jobs-initial 2 --num-jobs-final 5 --minibatch-size 256,128,64 exp/chain2/tdnn1a_sp/egs exp/chain2/tdnn1a_sp
steps/chain2/validate_randomized_egs.sh: sucessfully validated randomized egs in exp/chain2/tdnn1a_sp/egs
steps/chain2/train.sh: Generating training schedule
['steps/chain2/internal/get_train_schedule.py', '--frame-subsampling-factor=3', '--num-jobs-initial=2', '--num-jobs-final=5', '--num-epochs=4.0', '--dropout-schedule=', '--num-scp-files=2', '--frame-subsampling-factor=3', '--initial-effective-lrate=0.001', '--final-effective-lrate=0.0001', '--schedule-out=exp/chain2/tdnn1a_sp/schedule.txt']
steps/chain2/train.sh: will train for 4.0 epochs = 6 iterations
steps/chain2/train.sh: Copying transition model
steps/chain2/train.sh: Num langs is 1
steps/chain2/train.sh: training, iteration 0 of 6, num-jobs is 2
run.pl: job failed, log is in nnet3-chain-train2
run.pl: job failed, log is in nnet3-chain-train2
steps/chain2/train.sh: error detected training on iteration 0
```

`nnet-chain-train2` log:
```
# --out-of-range-regularize=0.01 --write-cache=exp/chain2/tdnn1a_sp/cache.1 --use-gpu=yes --apply-deriv-weights=false --leaky-hmm-coefficient=0.1 --xent-regularize=0.1 --print-interval=10 --max-param-change=2.0 --momentum=0.0 --l2-regularize-factor=0.5 --srand=0 "nnet3-copy --learning-rate=0.002 exp/chain2/tdnn1a_sp/0.raw - |" exp/chain2/tdnn1a_sp/egs/misc "ark:nnet3-chain-copy-egs  --frame-shift=1 scp:exp/chain2/tdnn1a_sp/egs/train.1.scp ark:- | nnet3-chain-shuffle-egs --buffer-size=1000 --srand=0 ark:- ark:- | nnet3-chain-merge-egs  --minibatch-size=256,128,64 ark:- ark:-|" exp/chain2/tdnn1a_sp/1.1.raw
# Started at Fri Dec 11 01:35:01 GMT 2020
#
bash: line 1: --out-of-range-regularize=0.01: command not found
bash: line 1: --out-of-range-regularize=0.01: command not found
# Accounting: time=0 threads=1
# Ended (code 127) at Fri Dec 11 01:35:01 GMT 2020, elapsed time 0 seconds
# Accounting: time=0 threads=1
# Ended (code 127) at Fri Dec 11 01:35:01 GMT 2020, elapsed time 0 seconds
```

It looks like it's trying to run --out-of-range-regularize as an executable when it looks like it's meant to be an argument for something.

Any ideas what might be causing this?

**Comment by OscarVanL** [comment]
It looks like something in these lines might be responsible:
https://github.com/kaldi-asr/kaldi/blob/1e5749b31bcb6bf4eccde94c4d3b73575130f715/egs/wsj/s5/steps/nnet3/chain2/train.sh#L222-L236

To give further details, I have ran `git pull` to get the latest version, then recompiled as follows:
```
cd tools
./extras/check_dependencies.sh
make -j 8

cd ../src
./configure
make depend -j 8; make -j 8
```
The error occurs on the latest version.

**Comment by danpovey** [comment]
Looks like your $cmd variable may be empty.  Look at your path.sh.

**Comment by OscarVanL** [comment]
I'm just using the example `mini_librispeech` script, I've not changed anything at all, except `cmd.sh`, which now says:

```
export train_cmd="run.pl --mem 2G"
export decode_cmd="run.pl --mem 4G"
export mkgraph_cmd="run.pl --mem 8G"
export cuda_cmd="run.pl --gpu 1 --use-gpu=wait"
```


The content of `path.sh` is this:
https://github.com/kaldi-asr/kaldi/blob/1e5749b31bcb6bf4eccde94c4d3b73575130f715/egs/mini_librispeech/s5/path.sh#L1-L9

**Comment by danpovey** [comment]
You're right, those lines have spaces after the backslash, which negates the line-continuation effect.  Can you make a PR?

**Comment by rrwang05** [comment]
> I'm just using the example `mini_librispeech` script, I've not changed anything at all, except `cmd.sh`, which now says:
> 
> ```
> export train_cmd="run.pl --mem 2G"
> export decode_cmd="run.pl --mem 4G"
> export mkgraph_cmd="run.pl --mem 8G"
> export cuda_cmd="run.pl --gpu 1 --use-gpu=wait"
> ```
> 
> The content of `path.sh` is this:
> https://github.com/kaldi-asr/kaldi/blob/1e5749b31bcb6bf4eccde94c4d3b73575130f715/egs/mini_librispeech/s5/path.sh#L1-L9
Hi OscarVanL,
I also encountered the same problem, do you solve it now ?

**Comment by danpovey** [comment]
@msrikanth <msrikanth@idiap.ch> perhaps you could look at this?
I notice it's using $cmd in a slightly nonstandard way, it's taking --cmd
"$cuda_cmd"... I'd prefer to have it add the --gpu 1 flag because it's a
kind of
pattern... the idea is that $cmd is just the base command.  Also a few
commands called from chain2/train.sh do not actually use the GPU.

I notice a commented out line saying something doesn't work at Idiap...

The --use-gpu=wait flag is not correct to be given to run.pl, that's an
option you would give to nnet3-chain-train2.sh.

**Comment by OscarVanL** [comment]
I see, I'll try removing the `--use-gpu=wait` arg from run.pl and modify `/egs/wsj/s5/steps/nnet3/chain2/train.sh`.

I'll instead change this line to wait
https://github.com/kaldi-asr/kaldi/blob/1e5749b31bcb6bf4eccde94c4d3b73575130f715/egs/wsj/s5/steps/nnet3/chain2/train.sh#L22

(I wasn't quite sure where I was supposed to put `--use-gpu=wait` when it was recommended when I had OOM errors, so thanks for explaining this.)

**Comment by mrsrikanth** [comment]
I'm making a PR removing the comment and uncommenting the line to add gpu_cmd_opt (similar to the behavior of ``chain/train.py``), but I don't see a trailing whitespace in the code.

@danpovey Do you want me to remove ``--gpu 1`` from cmd.sh as well?

**Comment by danpovey** [comment]
I'd prefer if you just used $cmd or $train_cmd, and no $cuda_cmd; and added
the "--gpu 1" inside train.sh, because the whole idea of these wrappers is
to translate a generic form like "--gpu 1" into system-specific ones.

**Comment by mrsrikanth** [comment]
I think you can just mention the problem here. If there is anything that needs to be changed in train.sh, I would add it to the PR I'm creating now.

**Comment by OscarVanL** [comment]
OK, the error is:

```
steps/chain2/train.sh --stage -10 --cmd run.pl --gpu 1 --xent-regularize 0.1 --leaky-hmm-coefficient 0.1 --max-para                                                                                                                          m-change 2.0 --num-jobs-initial 2 --num-jobs-final 5 --minibatch-size 256,128,64 exp/chain2/tdnn1a_sp/egs exp/chain                                                                                                                          2/tdnn1a_sp
steps/chain2/validate_randomized_egs.sh: sucessfully validated randomized egs in exp/chain2/tdnn1a_sp/egs
steps/chain2/train.sh: Generating training schedule
['steps/chain2/internal/get_train_schedule.py', '--frame-subsampling-factor=3', '--num-jobs-initial=2', '--num-jobs                                                                                                                          -final=5', '--num-epochs=4.0', '--dropout-schedule=', '--num-scp-files=2', '--frame-subsampling-factor=3', '--initi                                                                                                                          al-effective-lrate=0.001', '--final-effective-lrate=0.0001', '--schedule-out=exp/chain2/tdnn1a_sp/schedule.txt']
steps/chain2/train.sh: will train for 4.0 epochs = 6 iterations
steps/chain2/train.sh: Copying transition model
steps/chain2/train.sh: Num langs is 1
steps/chain2/train.sh: training, iteration 0 of 6, num-jobs is 2
steps/chain2/train.sh: training, iteration 1 of 6, num-jobs is 3
steps/chain2/train.sh: training, iteration 2 of 6, num-jobs is 3
steps/chain2/train.sh: training, iteration 3 of 6, num-jobs is 4
steps/chain2/train.sh: training, iteration 4 of 6, num-jobs is 4
steps/chain2/train.sh: training, iteration 5 of 6, num-jobs is 5
steps/chain2/train.sh: doing model combination
nnet3-copy '--edits=rename-node old-name=output new-name=output-dummy; rename-node old-name=output-default new-name                                                                                                                          =output' exp/chain2/tdnn1a_sp/final.raw -
nnet3-am-init exp/chain2/tdnn1a_sp/0_trans.mdl - exp/chain2/tdnn1a_sp/final.mdl
LOG (nnet3-copy[5.5.851~1-088e9]:main():nnet3-copy.cc:123) Copied raw neural net from exp/chain2/tdnn1a_sp/final.ra                                                                                                                          w to -
LOG (nnet3-am-init[5.5.851~1-088e9]:main():nnet3-am-init.cc:96) Initialized am-nnet (neural net acoustic model) and                                                                                                                           wrote to exp/chain2/tdnn1a_sp/final.mdl
steps/chain2/train.sh: exp/chain2/tdnn1a_sp/final.mdl does not exist.
```

**Comment by mrsrikanth** [comment]
Can you confirm that you are using the latest Kaldi?

**Comment by OscarVanL** [comment]
I pulled and recompiled it yesterday, so it has all commits up to Dec 10, 2020

**Comment by OscarVanL** [comment]
I also cleaned the working directory, so there shouldn't be any old files leftover from previous runs:

```
cd egs/mini_librispeech/s5
git clean -f -x -d --exclude="corpus" --exclude="cmd.sh" --exclude="run.sh"
```

**Comment by mrsrikanth** [comment]
I created #4385 . Can you please check if it fixes your error?

**Comment by OscarVanL** [comment]
Sure, I'll just switch to that branch. Out of curiosity, if we're getting rid of `cuda_cmd`, where should I set `--gpu 1` instead? This is normally set in `cuda_cmd` for the mini_librispeech example.

https://github.com/kaldi-asr/kaldi/blob/ece1cd7642e15c1001b8759d0a7fd92b7f96aa2c/egs/mini_librispeech/s5/cmd.sh#L16

**Comment by mrsrikanth** [comment]
I believe in ``train_cmd``. Thanks for testing, btw.

**Comment by OscarVanL** [comment]
I'm very happy to test, thanks for fixing! I'll let you know

**Comment by jtrmal** [comment]
it should be used for very specific cases where you will need the gpu...
i.e. inside in the script there should be something like

$cmd --gpu 1 JOB=1:10 blahblahblah....

i.e. it should be script author's(Srikanth's) job, not user's (OscarVanL)
job

**Comment by jtrmal** [comment]
to expand -- if you make it a part of train_cmd, then every command will
need gpu, without regard whether it uses it or not...
y.

**Comment by OscarVanL** [comment]
I see, thank you for explaining this.

**Comment by OscarVanL** [comment]
OK, using your PR @mrsrikanth, the run.sh script has finished and the last outputs were:

```
[info]: final HCLG is not stochastic.
steps/nnet3/decode.sh --acwt 1.0 --post-decode-acwt 10.0 --extra-left-context 22 --extra-right-context 16 --extra-left-context-initial 0 --extra-right-context-final 0 --frames-per-chunk 140 --nj 38 --cmd run.pl --mem 4G --num-threads 4 $
steps/nnet2/check_ivectors_compatible.sh: WARNING: One of the directories do not contain iVector ID.
steps/nnet2/check_ivectors_compatible.sh: WARNING: That means it's you who's reponsible for keeping
steps/nnet2/check_ivectors_compatible.sh: WARNING: the directories compatible
steps/nnet3/decode.sh: feature type is raw
steps/diagnostic/analyze_lats.sh --cmd run.pl --mem 4G --iter final exp/chain2/tree_sp/graph_tgsmall exp/chain2/tdnn1a_sp/decode_tgsmall_dev_clean_2
steps/diagnostic/analyze_lats.sh: see stats in exp/chain2/tdnn1a_sp/decode_tgsmall_dev_clean_2/log/analyze_alignments.log
Overall, lattice depth (10,50,90-percentile)=(2,12,105) and mean=42.4
steps/diagnostic/analyze_lats.sh: see stats in exp/chain2/tdnn1a_sp/decode_tgsmall_dev_clean_2/log/analyze_lattice_depth_stats.log
score best paths
score confidence and timing with sclite
Decoding done.
steps/lmrescore_const_arpa.sh --cmd run.pl --mem 4G data/lang_test_tgsmall data/lang_test_tglarge data/dev_clean_2_hires exp/chain2/tdnn1a_sp/decode_tgsmall_dev_clean_2 exp/chain2/tdnn1a_sp/decode_tglarge_dev_clean_2
```

I assume this means it's completed successfully?

The error is gone by the look of it :)

**Comment by mrsrikanth** [comment]
Again, thanks for testing!

**Comment by OscarVanL** [comment]
Ok, since your PR is merged I'll close this issue. Thanks!
