### ISSUE TITLE
internal compiler error: Segmentation fault on executing make in src folder (lat/word-align-lattice-lexicon.cc)

### ISSUE THREAD

**Issue by puneetbawa** [kaldi-asr/kaldi#4384]
make -C hmm
make[1]: Entering directory '/home/dell/kaldi-workspace/kaldi/src/hmm'
g++ -std=c++11 -I.. -isystem /home/dell/kaldi-workspace/kaldi/tools/openfst-1.6.7/include -O1 -Wall -Wno-sign-compare -Wno-unused-local-typedefs -Wno-deprecated-declarations -Winit-self -DKALDI_DOUBLEPRECISION=0 -DHAVE_EXECINFO_H=1 -DHAVE_CXXABI_H -DHAVE_MKL -I/opt/intel/mkl/include -m64 -msse -msse2 -pthread -g    -c -o hmm-topology.o hmm-topology.cc
g++ -std=c++11 -I.. -isystem /home/dell/kaldi-workspace/kaldi/tools/openfst-1.6.7/include -O1 -Wall -Wno-sign-compare -Wno-unused-local-typedefs -Wno-deprecated-declarations -Winit-self -DKALDI_DOUBLEPRECISION=0 -DHAVE_EXECINFO_H=1 -DHAVE_CXXABI_H -DHAVE_MKL -I/opt/intel/mkl/include -m64 -msse -msse2 -pthread -g    -c -o transition-model.o transition-model.cc
g++ -std=c++11 -I.. -isystem /home/dell/kaldi-workspace/kaldi/tools/openfst-1.6.7/include -O1 -Wall -Wno-sign-compare -Wno-unused-local-typedefs -Wno-deprecated-declarations -Winit-self -DKALDI_DOUBLEPRECISION=0 -DHAVE_EXECINFO_H=1 -DHAVE_CXXABI_H -DHAVE_MKL -I/opt/intel/mkl/include -m64 -msse -msse2 -pthread -g    -c -o hmm-utils.o hmm-utils.cc
g++ -std=c++11 -I.. -isystem /home/dell/kaldi-workspace/kaldi/tools/openfst-1.6.7/include -O1 -Wall -Wno-sign-compare -Wno-unused-local-typedefs -Wno-deprecated-declarations -Winit-self -DKALDI_DOUBLEPRECISION=0 -DHAVE_EXECINFO_H=1 -DHAVE_CXXABI_H -DHAVE_MKL -I/opt/intel/mkl/include -m64 -msse -msse2 -pthread -g    -c -o tree-accu.o tree-accu.cc
g++ -std=c++11 -I.. -isystem /home/dell/kaldi-workspace/kaldi/tools/openfst-1.6.7/include -O1 -Wall -Wno-sign-compare -Wno-unused-local-typedefs -Wno-deprecated-declarations -Winit-self -DKALDI_DOUBLEPRECISION=0 -DHAVE_EXECINFO_H=1 -DHAVE_CXXABI_H -DHAVE_MKL -I/opt/intel/mkl/include -m64 -msse -msse2 -pthread -g    -c -o posterior.o posterior.cc
g++ -std=c++11 -I.. -isystem /home/dell/kaldi-workspace/kaldi/tools/openfst-1.6.7/include -O1 -Wall -Wno-sign-compare -Wno-unused-local-typedefs -Wno-deprecated-declarations -Winit-self -DKALDI_DOUBLEPRECISION=0 -DHAVE_EXECINFO_H=1 -DHAVE_CXXABI_H -DHAVE_MKL -I/opt/intel/mkl/include -m64 -msse -msse2 -pthread -g    -c -o hmm-test-utils.o hmm-test-utils.cc
ar -cr kaldi-hmm.a hmm-topology.o transition-model.o hmm-utils.o tree-accu.o posterior.o hmm-test-utils.o
ranlib kaldi-hmm.a
make[1]: Leaving directory '/home/dell/kaldi-workspace/kaldi/src/hmm'
make -C lat
make[1]: Entering directory '/home/dell/kaldi-workspace/kaldi/src/lat'
g++ -std=c++11 -I.. -isystem /home/dell/kaldi-workspace/kaldi/tools/openfst-1.6.7/include -O1 -Wall -Wno-sign-compare -Wno-unused-local-typedefs -Wno-deprecated-declarations -Winit-self -DKALDI_DOUBLEPRECISION=0 -DHAVE_EXECINFO_H=1 -DHAVE_CXXABI_H -DHAVE_MKL -I/opt/intel/mkl/include -m64 -msse -msse2 -pthread -g -Wno-sign-compare   -c -o kaldi-lattice.o kaldi-lattice.cc
g++ -std=c++11 -I.. -isystem /home/dell/kaldi-workspace/kaldi/tools/openfst-1.6.7/include -O1 -Wall -Wno-sign-compare -Wno-unused-local-typedefs -Wno-deprecated-declarations -Winit-self -DKALDI_DOUBLEPRECISION=0 -DHAVE_EXECINFO_H=1 -DHAVE_CXXABI_H -DHAVE_MKL -I/opt/intel/mkl/include -m64 -msse -msse2 -pthread -g -Wno-sign-compare   -c -o lattice-functions.o lattice-functions.cc
g++ -std=c++11 -I.. -isystem /home/dell/kaldi-workspace/kaldi/tools/openfst-1.6.7/include -O1 -Wall -Wno-sign-compare -Wno-unused-local-typedefs -Wno-deprecated-declarations -Winit-self -DKALDI_DOUBLEPRECISION=0 -DHAVE_EXECINFO_H=1 -DHAVE_CXXABI_H -DHAVE_MKL -I/opt/intel/mkl/include -m64 -msse -msse2 -pthread -g -Wno-sign-compare   -c -o word-align-lattice.o word-align-lattice.cc
g++ -std=c++11 -I.. -isystem /home/dell/kaldi-workspace/kaldi/tools/openfst-1.6.7/include -O1 -Wall -Wno-sign-compare -Wno-unused-local-typedefs -Wno-deprecated-declarations -Winit-self -DKALDI_DOUBLEPRECISION=0 -DHAVE_EXECINFO_H=1 -DHAVE_CXXABI_H -DHAVE_MKL -I/opt/intel/mkl/include -m64 -msse -msse2 -pthread -g -Wno-sign-compare   -c -o phone-align-lattice.o phone-align-lattice.cc
g++ -std=c++11 -I.. -isystem /home/dell/kaldi-workspace/kaldi/tools/openfst-1.6.7/include -O1 -Wall -Wno-sign-compare -Wno-unused-local-typedefs -Wno-deprecated-declarations -Winit-self -DKALDI_DOUBLEPRECISION=0 -DHAVE_EXECINFO_H=1 -DHAVE_CXXABI_H -DHAVE_MKL -I/opt/intel/mkl/include -m64 -msse -msse2 -pthread -g -Wno-sign-compare   -c -o word-align-lattice-lexicon.o word-align-lattice-lexicon.cc
word-align-lattice-lexicon.cc:1067:1: internal compiler error: Segmentation fault
 }  // namespace kaldi
 ^
Please submit a full bug report,
with preprocessed source if appropriate.

![Screenshot from 2020-12-11 14-17-05](https://user-images.githubusercontent.com/12969314/101882246-a1898700-3bbb-11eb-9cb5-3c82de86c8b7.png)

**Comment by prgarg007** [comment]
Tried with GCC version 7.5.0. The same is working fine on Ubuntu 18.04.1 
Can you check for the GCC version on your system, might be the issue in compiler's version ?

**Comment by jtrmal** [comment]
it's definitely a compiler error

**Comment by puneetbawa** [comment]
The issue was with my version of clang(6.0.0). Have updated the libraries corresponding to gcc version 7.5.0. 
Now it's working fine. Thanks @prgarg007 and @jtrmal.
