### ISSUE TITLE
Problem in log for batched-wav-nnet3-cuda2 cuda decoder source code 

### ISSUE THREAD

**Issue by manu51188** [kaldi-asr/kaldi#4390]
Hi, 

I am currently working on measuring performance of batched-wav-nnet3-cuda2 decoder in which I see a log like this :

KALDI_LOG << "Overall likelihood per frame was " << (tot_like / num_frames)
              << " per frame over " << num_frames << " frames.";

In this log, we are not actually computing the num_frames and total_likelihood and both of these variables are initialised to 0 while declaring them. While running this code, I see that Overall likelihood per frame was coming to be "-nan" which sometimes can be misleading. Do we have any plans to correct this log or remove it altogether ?

Thanks and Regards,
Mohit

**Comment by kkm000** [comment]
No, we do not. What's wrong with it? Why `num_frames` would be 0 in your case?

**Comment by manu51188** [comment]
The **num_frames** are 0 because batched-wav-nnet3-cuda2 main() function initialises it to 0 and this value is never being set through out the whole program. Similar is the result for variable **double tot_like = 0.0**.
Actually if I compare batched-wav-nnet3-cuda2 vs batched-wav-nnet3-cuda , there is a function void GetDiagnosticsAndPrintOutput defined here : https://github.com/kaldi-asr/kaldi/blob/master/src/cudadecoderbin/batched-wav-nnet3-cuda.cc#L42 which computes the number of frames and total likelihood. 

But in batched-wav-nnet3-cuda2 , this function is not defined. So, either we can define the same function in batched-wav-nnet3-cuda2 or completely remove the log for num_frames and total likelihood since it doesn't serve any pupose.

**Comment by hugovbraun** [comment]
You're right, those variables are not updated in the "2" version. I'll fix that

**Comment by manu51188** [comment]
Great !! Thanks for checking.

**Comment by hugovbraun** [comment]
We should close this one, the PR has been merged

**Comment by danpovey** [comment]
@hugovbraun at some point it would be nice if you could look at https://github.com/k2-fsa/k2.
We can decode on GPU at about 300x real time (will get faster as we optimize).  As you'll see, everything
is much more "generic".

**Comment by danpovey** [comment]
.. just FYI.
