### ISSUE TITLE
Make failed while installing kaldi

### ISSUE THREAD

**Issue by horizon-hardyzl** [kaldi-asr/kaldi#4397]
I executed the "make" command in /src , and  some error information  came out . The instalI steps are followed by http://jrmeyer.github.io/asr/2016/01/26/Installing-Kaldi.html . But it went wrong and I can't find solutions.  The error message is as follows:

...
g++ -Wl,-rpath=/storage3/zhenglin/tools/kaldi-trunk/tools/openfst-1.6.7/lib -rdynamic  -L/usr/local/cuda/lib64 -Wl,-rpath,/usr/local/cuda/lib64 -L/usr/local/cuda/lib -Wl,-rpath,/usr/local/cuda/lib  lattice-reverse.o ../rnnlm/kaldi-rnnlm.a ../nnet3/kaldi-nnet3.a ../cudamatrix/kaldi-cudamatrix.a ../lat/kaldi-lat.a ../lm/kaldi-lm.a ../fstext/kaldi-fstext.a ../hmm/kaldi-hmm.a ../tree/kaldi-tree.a ../util/kaldi-util.a ../matrix/kaldi-matrix.a ../base/kaldi-base.a   /storage3/zhenglin/tools/kaldi-trunk/tools/openfst-1.6.7/lib/libfst.so -L/opt/intel/mkl/lib/intel64 -Wl,-rpath=/opt/intel/mkl/lib/intel64 -l:libmkl_intel_lp64.so -l:libmkl_core.so -l:libmkl_sequential.so -ldl -lpthread -lm -lm -lpthread -ldl -lcublas -lcusparse -lcudart -lcurand -lcufft -lnvToolsExt  -lcusolver -o lattice-reverse
../cudamatrix/kaldi-cudamatrix.a(cu-device.o): In function `kaldi::CuDevice::DeviceGetName(char*, int, int)':
/storage3/zhenglin/tools/kaldi-trunk/src/cudamatrix/cu-device.cc:580: undefined reference to `cuDeviceGetName'
../cudamatrix/kaldi-cudamatrix.a(cu-allocator.o): In function `kaldi::GetFreeGpuMemory[abi:cxx11](long*, long*)':
/storage3/zhenglin/tools/kaldi-trunk/src/cudamatrix/cu-allocator.cc:287: undefined reference to `cuMemGetInfo_v2'
collect2: error: ld returned 1 exit status
<builtin>: recipe for target 'lattice-lmrescore-kaldi-rnnlm' failed
make[1]: *** [lattice-lmrescore-kaldi-rnnlm] Error 1
make[1]: *** Waiting for unfinished jobs....
../cudamatrix/kaldi-cudamatrix.a(cu-device.o): In function `kaldi::CuDevice::DeviceGetName(char*, int, int)':
/storage3/zhenglin/tools/kaldi-trunk/src/cudamatrix/cu-device.cc:580: undefined reference to `cuDeviceGetName'
../cudamatrix/kaldi-cudamatrix.a(cu-allocator.o): In function `kaldi::GetFreeGpuMemory[abi:cxx11](long*, long*)':
/storage3/zhenglin/tools/kaldi-trunk/src/cudamatrix/cu-allocator.cc:287: undefined reference to `cuMemGetInfo_v2'
collect2: error: ld returned 1 exit status
<builtin>: recipe for target 'lattice-lmrescore-kaldi-rnnlm-pruned' failed
make[1]: *** [lattice-lmrescore-kaldi-rnnlm-pruned] Error 1
make[1]: Leaving directory '/storage3/zhenglin/tools/kaldi-trunk/src/latbin'
Makefile:136: recipe for target 'latbin' failed
make: *** [latbin] Error 2

**Comment by danpovey** [comment]
I just merged a fix for this, please do `git pull` and try again.
