### ISSUE TITLE
Conversion from RepeatedAffineComponent or NaturalGradientRepeatedAffineComponent to BlockAffineComponent

### ISSUE THREAD

**Issue by danpovey** [kaldi-asr/kaldi#440]
This is to be done in the 'chain' branch.  @galv, if you have time you could do this.

Note: there is currently no NaturalGradient version of BlockAffineComponent because it would be hard to implement efficiently on GPU.
In situations where I have tried to train from the start with BlockAffineComponent in place of RepeatedAffineComponent, I haven't had great results in terms of either train or valid objf values [this is in the Jesus layer, in 'jesus' branch in my personal repo.]  But the number of parameters was not that large, so I don't think it was an overtraining issue, and I think we could still get something out of BlockAffineComponent if the first epoch or so of training were done with RepeatedAffineComponent, and then we converted to block.  So we need a way to initialize BlockAffineComponent with RepeatedAffineComponent.  This can be done via a friend declaration, and a new constructor.
In order to actually apply this from the command line, some new things are needed.
The basic idea will be to add a boolean option --convert-repeated-to-block to nnet3-am-copy.cc.  This will call a function in nnet-utils.h, like
 void ConvertRepeatedToBlockAffine(Nnet *nnet);
You will have go inside any CompositeComponents while doing this, as the components in question are expected to be nested inside a CompositeComponent, which represents a sequence of components (more memory efficient than putting the sequence in the nnet).  Using a queue inside ConvertRepeatedToBlockAffine will make it easier to do so recursively, for completeness.  You'll have to add the following functions to the interface of class CompositeComponent in order to get access to its members:
   int32 NumComponents() const;
   const Component* GetComponent(int32 c) const;
   void SetComponent(int32 c, Component *component);
[Be sure to document that this function takes ownership of 'component'].

When testing the types of components, please initially use Type(), and then once you know the type, use dynamic_cast to get access to class-specific members [and assert that the result of dynamic_cast is not NULL].

**Comment by galv** [comment]
Alright, taken.

On Thu, Jan 7, 2016 at 4:25 PM, Daniel Povey <notifications@github.com>
wrote:

> This is to be done in the 'chain' branch @galv <https://github.com/galv>,
> if you have time you could do this
>
> Note: there is currently no NaturalGradient version of
> BlockAffineComponent because it would be hard to implement efficiently on
> GPU
> In situations where I have tried to train from the start with
> BlockAffineComponent in place of RepeatedAffineComponent, I haven't had
> great results in terms of either train or valid objf values [this is in the
> Jesus layer, in 'jesus' branch in my personal repo] But the number of
> parameters was not that large, so I don't think it was an overtraining
> issue, and I think we could still get something out of BlockAffineComponent
> if the first epoch or so of training were done with
> RepeatedAffineComponent, and then we converted to block So we need a way to
> initialize BlockAffineComponent with RepeatedAffineComponent This can be
> done via a friend declaration, and a new constructor
> In order to actually apply this from the command line, some new things are
> needed
> The basic idea will be to add a boolean option --convert-repeated-to-block
> to nnet3-am-copycc This will call a function in nnet-utilsh, like
> void ConvertRepeatedToBlockAffine(Nnet
>
>
> *nnet); You will have go inside any CompositeComponents while doing this,
> as the components in question are expected to be nested inside a
> CompositeComponent, which represents a sequence of components (more memory
> efficient than putting the sequence in the nnet) Using a queue inside
> ConvertRepeatedToBlockAffine will make it easier to do so recursively, for
> completeness You'll have to add the following functions to the interface of
> class CompositeComponent in order to get access to its members: int32
> NumComponents() const; const Component* GetComponent(int32 c) const;
> void SetComponent(int32 c, Component *component);
> [Be sure to document that this function takes ownership of 'component']
>
> When testing the types of components, please initially use Type(), and
> then once you know the type, use dynamic_cast to get access to
> class-specific members [and assert that the result of dynamic_cast is not
> NULL]
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kaldi-asr/kaldi/issues/440>.
>



-- 
Daniel Galvez
danieltgalvez.com

**Comment by galv** [comment]
Do you anticipate CompositeComponent being able to contain a CompositeComponent? I don't see why it'd be useful (just make **max_rows_process_** smaller in the first CompositeComponent), but nothing in the code prevents it.

If you don't expect this case, I personally don't see a need for a queue (which I presume you proposed for some kind of breadth first search while doing the conversion).

**Comment by danpovey** [comment]
I don't anticipate this happening, no - in fact, the current config-file
mechanism couldn't parse it - but it's not hard to support the general
case.  not a big deal though.
Dan

**Comment by galv** [comment]
You need to be more specific than "no big deal". I think the general case shouldn't be supported. If someone is using nested CompositeComponents, when instead one could be used, why not consider this an error? Perhaps you understand something I don't.

**Comment by galv** [comment]
When I say "you need to be more specific", I mean: could you say in particular if you want me to do things in the most general way possible?

**Comment by danpovey** [comment]
I just saw no reason not to support the general case- supporting
combinations that don't make sense is a valid thing to do.  But if you want
to just assert that CompositeComponent is not supported, it's fine with me.
Dan

**Comment by galv** [comment]
Okay, I will probably assert nested CompositeComponents is not okay with a message explaining why. I want to minimize room for error in the "search" code to iterate over all of the components.

**Comment by kkm000** [comment]
Is this complete? Can the issue be closed?

**Comment by galv** [comment]
Yep, handled by #451.

**Comment by kkm000** [comment]
Thanks!
