### ISSUE TITLE
run.pl: you are trying to run a parallel job but you are putting the output into just one log file (exp/mono/log/update.1.log)

### ISSUE THREAD

**Issue by OscarVanL** [kaldi-asr/kaldi#4407]
I'm trying to speed up processing using parallelisation, I have tried fiddling with the `nj` arguments, yet many processes still use just one processor hyper thread on my 12-thread i7 processor despite this being set.

As an attempt to fix this, I've tried setting the `JOB=1:12` argument for run.pl

My `cmd.sh` file looks like this:

```
export train_cmd="run.pl JOB=1:12 --mem 2G --gpu 1"
export decode_cmd="run.pl JOB=1:12 --mem 4G"
export mkgraph_cmd="run.pl JOB=1:12 --mem 8G"
export cuda_cmd="run.pl --gpu 1"
```

When my run.sh script reaches train_mono.sh, I get the following error:

```
steps/train_mono.sh --boost-silence 1.25 --nj 12 --cmd run.pl JOB=1:12 --mem 2G --gpu 1 data/train_500short data/lang_nosp exp/mono
steps/train_mono.sh: Initializing monophone system.
steps/train_mono.sh: Compiling training graphs
steps/train_mono.sh: Aligning data equally (pass 0)
steps/train_mono.sh: Pass 1
steps/train_mono.sh: Aligning data
run.pl: you are trying to run a parallel job but you are putting the output into just one log file (exp/mono/log/update.1.log)
```

I presume this is not desired behaviour, or does this process not support parallelisation?

Is it worth configuring GridEngine so I don't have to use run.pl if I'm just training on one machine?

**Comment by kkm000** [comment]
You are doing it wrong. Some loads are sharded by Kaldi scripts, and this is where you normally see the `--nj` switch used. These scripts invoke `$cmd` with an appropriate `JOB=1:N` specification (it's not always even `JOB`). If you find those which can be parallelized but aren't, please rework them and send a PR. Simply adding the number of jobs you want does not and cannot work: the workload has to be explicitly split in a corresponding number of shards. Some simply cannot be parallelized.

Never add a job spec or `--nj` to the definition of `cmd` itself, it will break everything, as you've already seen.

I am closing this issue for now. If you believe that your issue has not been addressed, please feel free to ping me, and I'll reopen it. @-mention me for a faster response!

**Comment by OscarVanL** [comment]
Thank you for the explanation!
