### ISSUE TITLE
Missing default_trans.mdl

### ISSUE THREAD

**Issue by hangtingchen** [kaldi-asr/kaldi#4412]
https://github.com/kaldi-asr/kaldi/blob/785ecf7f4749519f6a66e8ef0908030dfe9aad69/egs/wsj/s5/local/chain2/tuning/run_tdnn_1i.sh#L242-L246

Is there should copy the model if it does not exist?
`if [ ! -f $dir/init/default_trans.mdl ]; then`

**Comment by danpovey** [comment]
yes, should be ! -f ... please make pr.

**Comment by hangtingchen** [comment]
A pr was created
https://github.com/kaldi-asr/kaldi/pull/4413#issue-552248823
