### ISSUE TITLE
compile error:undefined reference to `cuDeviceGetName' and undefined reference to `cuMemGetInfo_v2'

### ISSUE THREAD

**Issue by sty1992928** [kaldi-asr/kaldi#4417]
I was trying to compile kaldi in a docker container. The cuda version is release '10.1, V10.1.168' and gcc version is '8.3.0 (Debian 8.3.0-6)'. But something wrong happend:

`/usr/bin/ld: ../cudamatrix/kaldi-cudamatrix.a(cu-device.o): in function kaldi::CuDevice::DeviceGetName(char*, int, int)':`
`/kaldi-master/src/cudamatrix/cu-device.cc:580: undefined reference to cuDeviceGetName'`
`/usr/bin/ld: ../cudamatrix/kaldi-cudamatrix.a(cu-allocator.o): in function kaldi::GetFreeGpuMemory[abi:cxx11](long*, long*)':`
`/kaldi-master/src/cudamatrix/cu-allocator.cc:287: undefined reference to cuMemGetInfo_v2'
collect2: error: ld returned 1 exit status`

I tried the solution of [https://github.com/kaldi-asr/kaldi/issues/4391](url) and I added '-lcuda' to Makefile, but another error says "/usr/bin/ld: cannot find -lcuda".

Anyone can help, please?

**Comment by danpovey** [comment]
Is your Kaldi fully up to date?  I reverted a change a couple weeks ago about this, that had caused this type of error (removing some dlopen stuff).

**Comment by sty1992928** [comment]
I see your Commits on Dec 18, 2020. My kaldi is pulled on Dec 15, 2020. Thanks, I will try again.
