### ISSUE TITLE
matched pairs significance test (not urgent).

### ISSUE THREAD

**Issue by danpovey** [kaldi-asr/kaldi#442]
It would be good to implement the matched-pairs significance test for Kaldi scoring.  This will require someone reading up about it and thinking carefully.  I think it would require comparing the alignments, because we need to identify for each error whether both systems, or just one, make that error.  Probably @jtrmal should be involved as he knows the scoring/alignment code best.
Dan

**Comment by jtrmal** [comment]
In the past, I used to use Wilcoxon signed rank test on per-utterance WER
sets which kinda worked but the p-values were usually quite bad (I think
there wasn't any significance to speak about unless the overall WER
difference was at least 3 %), so I slowly abandoned it.
I'm not saying it was the best way how to do the test, but it was perhaps
the most obvious way.  I don't follow how the alignment would be used to do
this - I'm probably  preconditioned differently by the past work :)
y.

**Comment by danpovey** [comment]
You'll tend to get very bad significance values unless you take into
account the similarity between the outputs.
Larry Gillick had a paper on this a long time ago, it seems to be described
here:

http://www.icsi.berkeley.edu/ftp/pub/speech/papers/wikipapers/nist_mapsswe.html

**Comment by jtrmal** [comment]
Great,  thanks,  I'll  look at the papers
Y.

**Comment by vijayaditya** [comment]
I would like to pick this up. @jtrmal Did you make any progress on this ?

**Comment by jtrmal** [comment]
This went completely off my radar... Feel free to pick it up, I'd be
grateful.
Y.
