### ISSUE TITLE
chain model training with data without speaker info

### ISSUE THREAD

**Issue by zhouyong64** [kaldi-asr/kaldi#4420]
I have a large ASR dataset without speaker information. For training chain models with ivector (like aishell2 recipe does), how should I prepare speaker information, since I believe both spk2utt and ivector extraction depend on speaker label.

**Comment by danpovey** [comment]
you can just have the utt2spk be a one-to-one map, one speaker per utterance.

**Comment by danpovey** [comment]
.. could have found this with a web search I think.
