### ISSUE TITLE
Is it possible to make lattice-to-ctm-conf.cc multithreaded ?

### ISSUE THREAD

**Issue by kvishnivetsky** [kaldi-asr/kaldi#4424]
Hi there!

Tehre is a code snippet in **lattice-to-ctm-conf.cc** :

```
    for (; !clat_reader.Done(); clat_reader.Next()) {
      std::string key = clat_reader.Key();
      CompactLattice clat = clat_reader.Value();
      clat_reader.FreeCurrent();

// Here run a new Thread to proceed clat hust readed

      fst::ScaleLattice(fst::LatticeScale(lm_scale, acoustic_scale), &clat);

```

Is it possible to start here a thread to make all job with **CompatLattice** just readed or there is a shared internal state of reader, which should not be changed until all job with current **CompactLattice** will be finnished?

**Comment by danpovey** [comment]
There should be no problem.  Look for programs with "parallel" in their
name to see how to convert code to be parallel.

**Comment by kvishnivetsky** [comment]
Thanks!
