### ISSUE TITLE
Why is it by default to augment speaker labels in speed perturbation?

### ISSUE THREAD

**Issue by underdogliu** [kaldi-asr/kaldi#4430]
Hi all! I am now running a recipe with data augmentation via speed perturbation. However even though I used to run it in previous experiments without any doubt, this time I found that it augments speaker labels as well as utterances. i.e. by default number of speakers became 3 times larger as well (by setting 0.9, 1.0, 1.1 as mapping parameter). I am wondering if this is necessary. If there is about on this feature, I can create a PR on disabling speaker augmentation by default. 

@danpovey @hhadian what do you think?

**Comment by danpovey** [comment]
It doesn't make sense to share CMVN stats between different speeds of the
same data, or to treat them as the same speaker for speaker adaptation.

**Comment by underdogliu** [comment]
@danpovey Thanks for the reply Dan! Well the thing is sometimes we use such scripts for something else than speaker adaptation in ASR. And for such "other-than-ASR" applications it may not be necessary to treat diff. speed-perturbed data belonging to pseudo-speakers.

Also I didn't find related "It doesn't make sense...." statements or practical supportive statements in the [original paper from Tom Ko.](https://www.danielpovey.com/files/2015_interspeech_augmentation.pdf) I know it would be too time-consuming to explain this trivial thing but any hint on justification would be helpful. Thanks!

**Comment by danpovey** [comment]
mm, there is a spk–prefix option or similar that you could remove.
it is not a natural transformation that we encounter in the wild.

**Comment by underdogliu** [comment]
yeah true. I am not making it totally different but offering an option actually. Will try some tests and make a PR later (it involves segments but I think it is irrelevant to this issue).
