### ISSUE TITLE
performance tunning: speaker recognition costs 5~7s 

### ISSUE THREAD

**Issue by himrlawrrence** [kaldi-asr/kaldi#4435]
Hi Dan,
the env: 2 CPU core
to recognise speaker usually cost 5~7s.
is there a way to speed up the speaker recognition? eg. using GPU? or concurrence? (but if concurrence is larger than cpu core, it could crash ).

Thanks a lot.

**Comment by danpovey** [comment]
Probably that's mostly model loading and preparation time, if you are invoking a binary.  You'd need to create a server program that would listen on a port.  This isn't the right place to ask, kaldi-help is, but questions like this have been asked before.
