### ISSUE TITLE
Compile fails with gcc-9.3: Missing namespace std::

### ISSUE THREAD

**Issue by wilhelmhagg** [kaldi-asr/kaldi#4436]
Compilation fails with gcc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0

The error is related to the missing std:: in front of string in these two files:
 src/cudadecoder/batched-threaded-nnet3-cuda-pipeline.cc
 src/cudadecoder/batched-threaded-nnet3-cuda-pipeline.h

Here is a tiny patch:
[patch.txt](https://github.com/kaldi-asr/kaldi/files/5880147/patch.txt)

**Comment by danpovey** [comment]
Thanks!!  There isn't any chance you could submit that as a pull request, is there?

**Comment by wilhelmhagg** [comment]
Sure, i did the following pull request (hope i did it right?):

Add std:: namespace to string variables Closes #4436

**Comment by kkm000** [comment]
Fixed in #4438.
