### ISSUE TITLE
Do we want to put small prefix on Librispeech speakers? And making text creation as optional

### ISSUE THREAD

**Issue by underdogliu** [kaldi-asr/kaldi#4437]
Hi all! So I am using a mixture of multiple datasets but found a problem when sorting out speakers with LibriSpeech and one of the SRE datasets. I found the reason was LibriSpeech use pure integer IDs for speakers. While for SRE datasets which are not completely free it looks not making too much trouble, I am wondering if we can add a small prefix at beginning of each speaker and utterance, for example `lbi-$spk_id` for speakers, `lbi-$spk_id-$chapter_id` for utterances.

Also, I am wondering if we can make text creation in LibriSpeech as optional since for tasks other than ASR we don't usually need text.

If the answer to both (or one of them) are yes, I can make a PR. For text creation by default we will still create them. Any thoughts or sharp comments?

**Comment by danpovey** [comment]
I guess it's OK with me.
