### ISSUE TITLE
speaker recognition

### ISSUE THREAD

**Issue by zoughi** [kaldi-asr/kaldi#4443]
Hi,
I use Voxceleb database and the kaldi recipe for speaker recognition.
now, I want to run this scrip on my own database.
I want to know, is there a kaldi recipe which received wave file (only one sentence) and its corresponding text file and give me the start and end of each word in that sentence.

best regards

**Comment by danpovey** [comment]
All Kaldi scripts do alignment at some point.    You should ask on kaldi-help, maybe someone will have time to explain how to do it for a single file.  steps/get_train_ctm.sh is relevant (but that is for doing it for a whole data directory, not file by file).
