### ISSUE TITLE
Support 128-dim log-mel filterbanks

### ISSUE THREAD

**Issue by okkteam** [kaldi-asr/kaldi#4444]
Hi，
To obtain 128-dim log-mel fbanks, I modified --num-mel-bins in fbank.conf and used make_fbank.sh to extract features, but it failed. Error display：“You may have set --num-mel-bins too large.” How to get 128-dim log-mel fbanks in kaldi?

**Comment by danpovey** [comment]
It is a feature not a bug, as Nickolay explained in kaldi-help.  The bins would be too narrow, some of them would not contain any features.
