### ISSUE TITLE
got some random error

### ISSUE THREAD

**Issue by lixx0105** [kaldi-asr/kaldi#4449]
Hi,

I got a random error message as below when i run the inference. I got the correct result after i re-run the same inference. May i have your suggestions? thanks.

ERROR ([5.5]:ApplyLog():matrix/kaldi-vector.cc:786) Trying to take log of a negative number.
terminate called after throwing an instance of 'kaldi::KaldiFatalError'
  what():  kaldi::KaldiFatalError

**Comment by danpovey** [comment]
You dion't provide enough details, e.g. were GPUs involved, what kind of topology.
could just be hardware problem.

**Comment by lixx0105** [comment]
Hi,
Inference is using CPU  (Intel(R) Xeon(R) CPU E5-2650 v4 @ 2.20GHz)
chain model is used.
thanks.

**Comment by lixx0105** [comment]
BTW, sometimes i got different inference results for the same audio file. i already set --dither =0.0

**Comment by danpovey** [comment]
Would need stack trace, which would have been printed.  Next time provide
all the information at the start.
