### ISSUE TITLE
Small logic error in wsj/s5/local/chain2/tuning/run_tdnn_1i.sh

### ISSUE THREAD

**Issue by huntingriver** [kaldi-asr/kaldi#4450]
https://github.com/kaldi-asr/kaldi/blob/3eea37dd09b55064e6362216f7e9a60641f29f09/egs/wsj/s5/local/chain2/tuning/run_tdnn_1i.sh#L242-L246
@songmeixu Line 242 is missing "!", eg if file NOT exists, then copy. It should be:
`if [ ! -f $dir/init/default_trans.mdl ]; then`

**Comment by danpovey** [comment]
mm can you please make a PR with a fix?  I believe this may have been fixed in other chain2 example scripts.

**Comment by huntingriver** [comment]
Indeed. This is fixed in babel and swbd. I've created the PR for wsj: https://github.com/kaldi-asr/kaldi/pull/4452

**Comment by csukuangfj** [comment]
Closing via #4452
