### ISSUE TITLE
Getting the recognized phonemes for each audio input

### ISSUE THREAD

**Issue by arm-on** [kaldi-asr/kaldi#4460]
Sometimes my Kaldi model outputs a word which not correct but very similar (in terms of the phonemes it has) to the correct word. I am not sure if the problem is with the acoustic part of the model or the language model which is embedded.

Is there a way to only get the phonemes that Kaldi has recognized inside an audio file? I mean I do not want Kaldi to combine the phonemes together to make a word. I want to see the output at the "phoneme level". Is that possible?

For instance, if the user says "bad", I want to see the output like this: "b", "a", "d"

**Comment by danijel3** [comment]
Kaldi writes output as lattices. You can use "lattice-to-phone-lattice" program get the phonemes. Refer to documentation for more details.

**Comment by kkm000** [comment]
I am closing this issue for now. If you believe that your issue has not been addressed, please feel free to ping me, and I'll reopen it. @-mention me for a faster response!
