### ISSUE TITLE
VB resegmentation gives dimension mismatch error due to improper use of coo_matrix

### ISSUE THREAD

**Issue by mdrpanwar** [kaldi-asr/kaldi#4462]
Hi all,
Thanks a lot for this wonderful toolkit. I want to bring to your notice an issue with the VB resegmentation code that I came across while working on speaker diarization. I used callhome dataset, extracted mfcc features using kaldi, and towards the end of my pipeline while performing resegmentation, I got the following error:

![Screenshot from 2021-02-12 01-52-20](https://user-images.githubusercontent.com/39766613/108947749-1df21900-7687-11eb-950b-445f7414eed2.png)

I was using linux and just to be sure, I tried to reproduce the same issue on Mac using [the official docker image](https://hub.docker.com/r/kaldiasr/kaldi). However, it executed perfectly on Mac without failing. Upon inspecting the files, I found that files `egs/callhome_diarization/v1/diarization/VB_resegmentation.py` and `egs/callhome_diarization/v1/diarization/VB_diarization.py` are different in the [git repository](https://github.com/kaldi-asr/kaldi) and the [docker image](https://hub.docker.com/r/kaldiasr/kaldi). The one in docker image is some previous version.
Even though a lot has changed and been renamed in these files, the significant change that led to this issue was in [lines 131-132 of VB_diarization.py](https://github.com/kaldi-asr/kaldi/blob/master/egs/callhome_diarization/v1/diarization/VB_diarization.py#L131-L132): 
`  F_s =coo_matrix((((X[zeta.row]-m[zeta.col])*zeta.data[:,np.newaxis]).flat,
                   (zeta.row.repeat(D), zeta.col.repeat(D)*D+np.tile(range(D), len(zeta.col)))))`

The `coo_matrix` must be sent a shape parameter as well (as in the docker image version of this file). If not, it infers the shape of output matrix from the index arrays passed, which will not always agree with the desired output shape and therefore result in a dimension mismatch during matrix multiplication. I changed the above to the following:
` F_s =coo_matrix((((X[zeta.row]-m[zeta.col])*zeta.data[:,np.newaxis]).flat,
                   (zeta.row.repeat(D), zeta.col.repeat(D)*D+np.tile(range(D), len(zeta.col)))), shape=(nframes, D*C))`

This rectified the error and gave the expected DER post execution. Therefore, I think this is a bug in the `VB_diarization.py` file and must be fixed (please correct me if this is not a bug and something else could have caused the dimension mismatch error). Please examine this and let me know. I will be more than happy to create a pull request for the same.

Thanks.

**Comment by danpovey** [comment]
Thanks!
I'm afraid our support for the Docker image is spotty, it may sometimes be behind the repo and is not updated all that frequently.
Thanks for filing the report, but I'm not going to leave the issue open as the requirement to keep the Docker image up to date is kind of a standing one, not specific to now.

**Comment by mdrpanwar** [comment]
Thanks, @danpovey. However, the issue I highlighted is for kaldi's git repository and not the docker image. In fact, the docker image works fine as I mentioned above. It's the code in the current kaldi repository that's failing and needs to be fixed. Sorry for the confusion.
