### ISSUE TITLE
fstcopy adds nodes?

### ISSUE THREAD

**Issue by jtrmal** [kaldi-asr/kaldi#449]
when working with fstcopy and an FST archive where the nodes number do not start from zero, i.e. for example:
KW303-04945
3       4       2       2       0.690246
3       4       3       3       0.696081
3       4       5       5       11.3045
3       4       0       0       20.7233
...

the fstcopy adds several nodes as to have the numbering starting from 0
KW303-04945
3       4       2       2       0.690246
3       4       3       3       0.696081
3       4       5       5       11.3045
3       4       0       0       20.7233
3       4       12024   12024   20.7233
3       4       4       4       20.7233
0       Infinity
1       Infinity
2       Infinity
...

I believe the first format is correct -- and I'm not sure the second format is right -- the extra nodes are probably fine, but I'm not sure about the weight "Infinity".
y.

**Comment by hainan-xv** [comment]
I think it's still equivalent to the original FST since Infinity would be the final-state cost, which is equivalent to saying 0,1,2 are not final states.
