### ISSUE TITLE
FAIL matrix-lib-test

### ISSUE THREAD

**Issue by Tortoise17** [kaldi-asr/kaldi#4491]
i am facing this issue. 

Running matrix-lib-test ... 0s... FAIL matrix-lib-test
Running sparse-matrix-test ... 0s... FAIL sparse-matrix-test
Running numpy-array-test ... 0s... FAIL numpy-array-test
make[1]: *** [test] Error 1

while compiling. 
Earlier this was not the case with version before 20 March. Please guide me how to fix this issue.

**Comment by danpovey** [comment]
Run the tests individually and show the output, e.g.:
cd matrix
./matrix-lib-test

**Comment by Tortoise17** [comment]
This was great help. Finally with this log, I resolved the issue. Thank you
