### ISSUE TITLE
How can I implement TDNN-LSTM using kaldi?

### ISSUE THREAD

**Issue by laetokang** [kaldi-asr/kaldi#4497]
Hi, I'm interested in Speech Verification. So I have been modeling TDNN-LSTM using Pytorch.

There are many struggles to implement it. But I cannot make it.

So what I'm trying to say is how can I implement the model using kaldi? 

I wonder if there is a tutorial.

Thank You.

**Comment by laetokang** [comment]
+ Questions.
How can I implement the following things in TDNN-LSTM?

- delay: the delay to be used in the recurrence of LSTMs
- decay-time: an approximate maximum on how many frames can be remembered via summation into the cell contents c_t
- projection-dim: the output dimension of the recurrent-projection-matrix

**Comment by danpovey** [comment]
They are configs, do "git grep decay-time" for example to see examples of
how these things are used.
But I recommend to follow the speaker id examples, e.g. the voxceleb
recipe.  If we are not using LSTMs there it likely means they
did not work as well for us, in that application.
