### ISSUE TITLE
train_lda_mllt.sh error

### ISSUE THREAD

**Issue by lling-2021** [kaldi-asr/kaldi#4502]
bash:line1: 34853 Broken pipe      ali-to-post "ark:gunzip -c exp/tri3/2.mdl ark:- ark:-
                34856                       | weight-slience-post 0.0 1 exp/tri3/2.mdl ark:- ark:-
               34858 Killed              | gmm_acc_mllt --rand

**Comment by wangsheng0131** [comment]
> bash:line1: 34853 Broken pipe ali-to-post "ark:gunzip -c exp/tri3/2.mdl ark:- ark:-
> 34856 | weight-slience-post 0.0 1 exp/tri3/2.mdl ark:- ark:-
> 34858 Killed | gmm_acc_mllt --rand

Hello, I encountered the same problem as you, have you solved it？@lling-2021

**Comment by danpovey** [comment]
Out of memory -> use fewer jobs. (--nj)

**Comment by lling-2021** [comment]
use fewer jobs, --nj

**Comment by lling-2021** [comment]
> > bash:line1: 34853 Broken pipe ali-to-post "ark:gunzip -c exp/tri3/2.mdl ark:- ark:-
> > 34856 | weight-slience-post 0.0 1 exp/tri3/2.mdl ark:- ark:-
> > 34858 Killed | gmm_acc_mllt --rand
> 
> Hello, I encountered the same problem as you, have you solved it？@lling-2021

Reduce the number of jobs(--nj)

**Comment by kkm000** [comment]
I am closing this issue for now. If you believe that your issue has not been addressed, please feel free to ping me, and I'll reopen it. @-mention me for a faster response!
