### ISSUE TITLE
Error during ivector extraction

### ISSUE THREAD

**Issue by TPalawaT** [kaldi-asr/kaldi#4505]
I was trying to extract pretrained embeddings for voxceleb and I am getting an error which could probably signify feature mismatch. This is despite the fact I am using the same MFCC config used as specified in voxceleb MFCC config.
```
--sample-frequency=16000
--frame-length=25 # the default is 25
--low-freq=20 # the default.
--high-freq=7600 # the default is zero meaning use the Nyquist (8k in this case).
--num-mel-bins=30
--num-ceps=24
--snip-edges=false
```
The error that I am getting when extracting ivector is,
```
WARNING (transform-feats[5.5.1048~1-d211d]:main():transform-feats.cc:110) Transform matrix for utterance WSJ-F46a-46ac041d_1:0-10268 has bad dimension 200x401 versus feat dim 168
LOG (transform-feats[5.5.1048~1-d211d]:main():transform-feats.cc:161) Applied transform to 0 utterances; 1621 had errors.
WARNING (ivector-extract[5.5.1048~1-d211d]:RunPerSpeaker():ivector-extract.cc:123) No features present for utterance WSJ-F40h-40hc0201_1:0-1895
```
I am getting this warning for multiple utterances, this is just a sample.
`LOG (ivector-extract[5.5.1048~1-d211d]:RunPerSpeaker():ivector-extract.cc:190) Done 0 speakers; 12 with errors.  0 utterances were processed, 1621 with errors.`
This is the final log I get for ivector-extract binary.

Also, If this bit of information helps, I have tried to use both splice-feats (with left and right context as 3) and add-deltas (using standard voxceleb delta config)  but neither has worked and both threw errors. Please let me know if you need any further information, Thanks!

**Comment by danpovey** [comment]
That looks like a combination of hires (40-dim) vs. normal (13-diim) MFCCs
plus other configuration differences.
If it was just for some utterances, you likely combined directories that
had different MFCC dims.

**Comment by TPalawaT** [comment]
I actually have 24 feature coefficients. I did that because that is what has been specified in voxceleb's MFCC config as specified here. https://github.com/kaldi-asr/kaldi/blob/master/egs/voxceleb/v1/conf/mfcc.conf

And no, it does not point to different directories. As I mentioned in the query, I have shown error for only one utterance, but there are more utterances with a dfferent name, having the same problem.

**Comment by kkm000** [comment]
I'm closing this issue, because it does not appear a bug in Kaldi. Something is likely wrong in your setup. **We have a forum that is the best place to ask questions**, and getting answers and input from other users as well. We are hanging out there all the time, too. Here, in the issue tracker, we are just too few.

**Kaldi help forum**: https://groups.google.com/forum/#!forum/kaldi-help

**Instructions for joining**: http://kaldi-asr.org/forums.html

If you think it's really a bug in one of Kaldi binaries or scripts, please reply, and I'll reopen it.
