### ISSUE TITLE
GOP word alignment

### ISSUE THREAD

**Issue by lmpanda** [kaldi-asr/kaldi#4507]
Hi guys, I've been trying to check out the GOP feature and it works well on the phoneme level, but I can't align it to words for some reason. I don't care to invest some time to add a script for that to the GOP feature egs folder (i.e. to present word-level results nicely), but I need some help to understand what I'm missing.

I'm trying to use Kaldi alignment tools, but that getting me an error. Here's the script excerpt (assume it runs after GOP run.sh): 

$cmd JOB=1:$nj exp/ali_test/log/align_to_word.JOB.log \
  linear-to-nbest "ark,t:gunzip -c exp/ali_test/ali-phone.JOB.gz|" \
  "ark:sym2int.pl -f 2- data/lang_nosp/words.txt data/test/split1/1/text|" "" "" "ark:-" \| \
  lattice-align-words "$lang/phones/word_boundary.int" "$model/final.mdl" "ark:-" "ark,t:exp/ali_test_one/aligned_words.JOB" || exit 1;
  
The error I get from lattice-align-words is this:
Phone changed before final transition-id found [broken lattice or mismatched model or wrong --reorder option?]

Any ideas what might go wrong?

**Comment by danpovey** [comment]
That error would generally be some kind of mismatch between the .mdl file and the one that was used to generate the alignments.

**Comment by lmpanda** [comment]
Thanks for a quick response. This is not the case, though, as I understand. Exactly the same mdl is used in all cases (we don't even have another model in the testing env). Here's a more complete excerpt (trying to only provide the shortest relevant details):

$cmd JOB=1:$nj exp/ali_test1/log/mk_align_graph.JOB.log \
  compile-train-graphs-without-lexicon \
	--read-disambig-syms=data/lang_nosp/phones/disambig.int \
	$model/tree $model/final.mdl \
	"ark,t:data/test_one/split${nj}/JOB/text.int" \
	"ark,t:data/local/text-phone.int" \
	"ark:|gzip -c > exp/ali_test1/fsts.JOB.gz"   || exit 1;

steps/align_mapped.sh --cmd "$cmd" --nj $nj --graphs exp/ali_test1 \
	data/test_one exp/probs_test_one $lang $model exp/ali_test1

$cmd JOB=1:$nj exp/ali_test1/log/ali_to_phones.JOB.log \
  ali-to-phones --per-frame=true $model/final.mdl \
	"ark,t:gunzip -c exp/ali_test1/ali.JOB.gz|" \
	"ark,t:|gzip -c >exp/ali_test1/ali-phone.JOB.gz"   || exit 1;

$cmd JOB=1:$nj exp/ali_test1/log/align_to_word.JOB.log \
  linear-to-nbest "ark,t:gunzip -c exp/ali_test1/ali-phone.JOB.gz|" \
  "ark:sym2int.pl -f 2- data/lang_nosp/words.txt data/test_one/split1/1/text|" "" "" "ark:-" \| \
  lattice-align-words "$lang/phones/word_boundary.int" "$model/final.mdl" "ark:-" \
  "ark,t:exp/ali_test1/aligned_words.JOB" || exit 1;

**Comment by danpovey** [comment]
When did you compile Kaldi?
The only thing I'm suspicious of is #4503 in which we changed the compiler options from c++11 to c++14.

**Comment by danpovey** [comment]
Oh, forget that.  I see now that ali-phone.JOB.gz is not an alignment file, it is a sequence of phones (the output of ali-to-phones).

**Comment by lmpanda** [comment]
Oh, my bad. Many thanks for pointing this out.

**Comment by OlaAbdallahM** [comment]
Hello guys,
I have an issue with a similar part as you, while trying to run the bash file run.sh which calls the make_mfcc.sh, but it raises some issues for me.
while executing this piece of script :

$cmd JOB=1:$nj $logdir/make_mfcc_${name}.JOB.log \
    compute-mfcc-feats $vtln_opts $write_utt2dur_opt --verbose=2 \
      --config=$mfcc_config scp,p:$logdir/wav_${name}.JOB.scp ark:- \| \
    copy-feats $write_num_frames_opt --compress=$compress ark:- \
      ark,scp:$mfccdir/raw_mfcc_$name.JOB.ark,$mfccdir/raw_mfcc_$name.JOB.scp \
      || exit 1;
it raises an error that the cmd file receives no argument (ARGS) and it should be more than two args.

Is anyone can help? @danpovey @lmpanda
