### ISSUE TITLE
validate_data_dir.sh checks for empty variable which already exists in parent environment

### ISSUE THREAD

**Issue by Sentewolf** [kaldi-asr/kaldi#4511]
In #4094 a check is introduced in validate_data_dir.sh to see if $data is an empty string. This check always fails if validate_data_dir.sh is called by make_mfcc.sh

- make_mfcc.sh defines $data
- make_mfcc.sh calls validate_data_dir.sh
- the parent environment (with $data) is used to run validate_data_dir.sh
- $data is not an empty string in validate_data_dir.sh
- validate_data_dir.sh exits

It seems to me we should not check if $data is an empty string in validate_data_dir.sh.

Reverting a few lines in validate_data_dir.sh fixes the issue.

I tested this on RedHat and Debian. As far as I can tell, using the parent environment is the normal way for a shell to work so I expect this to fail in most environments.

Before I make a pull request to revert the changes made in #4094, I wanted to check why this extra validation was added, if it is needed in some other workflow, and if another way can be found to implement it.

**Comment by danpovey** [comment]
What is your OS and what is your shell?
Unless you do `export data`, it should not be available to the child process's shell.

**Comment by Sentewolf** [comment]
My apologies for wasting your time, you are completely right. It's shell scripts all the way down and somewhere up the chain was a "set -a" which I just learned exports variables.

I guess I'll have to try and fix a few other repositories (though the added check in validate_data_dirs.sh still seems a bit unnecessary).

**Comment by danpovey** [comment]
I think it was using that method to check for repeated command line
parameters.
