### ISSUE TITLE
step/nnet2/get_lda_block.sh gets stuck in an infinite loop

### ISSUE THREAD

**Issue by uzodiac** [kaldi-asr/kaldi#452]
I tried to run nnet_5b_gpu.sh setup but get struck in get_lda_block.sh. I believe it's in an infinite loop when writing the indexes but I'm new to kaldi so not sure what the correct fix should be.

[indexes.head.txt](https://github.com/kaldi-asr/kaldi/files/91368/indexes.head.txt)

**Comment by danpovey** [comment]
Can you be more specific about what happens any why you think it's stuck in
an infinite loop?  And which specific directory the script is in?
Regardless, I think that script is pretty outdated and probably not the
best example to focus on.

Dan

**Comment by uzodiac** [comment]
Hi Dan,
Sorry for the confusion, I mean I has tried to run the nnet2 script found in wsj recipe for my own data (base on run_5b_gpu.sh). After a couple of tries I keep get stuck in "Accumulating LDA statistics" for almost a week,  so I do a little research and found that the the current running script is get_lda_block.sh (steps/nnet2) and it keep update the "indexes" files but from line 8 the content is just the same. And a quick look at [get_lda_block.sh](https://github.com/kaldi-asr/kaldi/blob/master/egs/wsj/s5/steps/nnet2/get_lda_block.sh) the script is simple enough for me to understand, I believe the the script below is infinite loop, but I'm not sure what the correct behavior should be so I can't fix it myself.

in my case block_size=10; block_shift=5; feat_dim=40

```
cur_index=0
num_blocks=0
context_length=$[1+2*($splice_width)]

while [ $[$cur_index+$block_size] -le $feat_dim ]; do
  for n in `seq $cur_index $[cur_index+$block_size-1]`; do
    echo -n `seq $n $feat_dim $[$n+($feat_dim*($context_length-1))]` '' >> $dir/indexes
  done
  echo >> $dir/indexes
  num_blocks=$[$num_blocks+1]
  cur_index=$[$cur_index+$block_shift]
  if [ $[$cur_index+$block_size-1] -gt $feat_dim ]; then
    cur_index=$[$feat_dim-$block_size];
  fi
done
echo $num_blocks >$dir/num_blocks
```

I'm kind of new to kaldi so I just try to get a run through all the current setups to get a hang of it.

**Comment by danpovey** [comment]
I just pushed a fix for this.  Looks like the last commit was a
user-submitted change which seems to have been wrong.
Dan

**Comment by uzodiac** [comment]
Thanks Dan.
