### ISSUE TITLE
Where can I find an open source Chinese dictionary

### ISSUE THREAD

**Issue by double22a** [kaldi-asr/kaldi#4522]
help, where can I find an open source Chinese dictionary for ASR?

**Comment by danpovey** [comment]
Looks at
egs/multi_cn/s5/local/prepare_dict.sh
in Kaldi, it uses
http://www.mdbg.net/chindict/export/cedict/cedict_1_0_ts_utf-8_mdbg.txt.gz

**Comment by double22a** [comment]
Thanks
