### ISSUE TITLE
Can anyone help me? QAQ 'Echo Done but can't do "yesno" example correctly'

### ISSUE THREAD

**Issue by Abigail-li** [kaldi-asr/kaldi#4538]
local/prepare_data.sh: line 39: utils/utt2spk_to_spk2utt.pl: Not a directory
local/prepare_data.sh: line 39: utils/utt2spk_to_spk2utt.pl: Not a directory
Dictionary preparation succeeded
./run.sh: line 22: utils/prepare_lang.sh: Not a directory
Preparing language models for test
cp: cannot stat 'data/lang': No such file or directory
arpa2fst --disambig-symbol=#0 --read-symbol-table=data/lang_test_tg/words.txt input/task.arpabo data/lang_test_tg/G.fst 
ERROR (arpa2fst[5.5]:Input():kaldi-io.cc:756) Error opening input stream data/lang_test_tg/words.txt

[ Stack-Trace: ]
/home/cream/kaldi-master/kaldi-master/src/lib/libkaldi-base.so(kaldi::MessageLogger::LogMessage() const+0x793) [0x7fc8196921c3]
arpa2fst(kaldi::MessageLogger::LogAndThrow::operator=(kaldi::MessageLogger const&)+0x25) [0x55cd92874d21]
/home/cream/kaldi-master/kaldi-master/src/lib/libkaldi-util.so(kaldi::Input::Input(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool*)+0xbe) [0x7fc8196b7080]
arpa2fst(main+0x5cb) [0x55cd92873194]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf3) [0x7fc8191040b3]
arpa2fst(_start+0x2e) [0x55cd92872b0e]

kaldi::KaldiFatalErrorfstisstochastic data/lang_test_tg/G.fst 
ERROR (fstisstochastic[5.5]:Input():kaldi-io.cc:756) Error opening input stream data/lang_test_tg/G.fst

[ Stack-Trace: ]
/home/cream/kaldi-master/kaldi-master/src/lib/libkaldi-base.so(kaldi::MessageLogger::LogMessage() const+0x793) [0x7f5b3c8cd1c3]
fstisstochastic(kaldi::MessageLogger::LogAndThrow::operator=(kaldi::MessageLogger const&)+0x25) [0x556c2d8e4d65]
/home/cream/kaldi-master/kaldi-master/src/lib/libkaldi-util.so(kaldi::Input::Input(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool*)+0xbe) [0x7f5b3c8f2080]
/home/cream/kaldi-master/kaldi-master/src/lib/libkaldi-fstext.so(fst::ReadFstKaldiGeneric(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool)+0x52) [0x7f5b3c92e765]
fstisstochastic(main+0x1ca) [0x556c2d8e3cf3]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf3) [0x7f5b3c1f00b3]
fstisstochastic(_start+0x2e) [0x556c2d8e3a6e]

kaldi::KaldiFatalErrorERROR: SymbolTable::ReadText: Can't open file data/lang_test_tg/words.txt
ERROR: FstHeader::Read: Bad FST header: standard input
ERROR: FstHeader::Read: Bad FST header: standard input
ERROR: FstHeader::Read: Bad FST header: tmpdir.g/empty_words.fst
Succeeded in formatting data.
./run.sh: line 27: steps/make_mfcc.sh: Not a directory
./run.sh: line 28: steps/compute_cmvn_stats.sh: Not a directory
./run.sh: line 29: utils/fix_data_dir.sh: Not a directory
./run.sh: line 27: steps/make_mfcc.sh: Not a directory
./run.sh: line 28: steps/compute_cmvn_stats.sh: Not a directory
./run.sh: line 29: utils/fix_data_dir.sh: Not a directory
./run.sh: line 33: steps/train_mono.sh: Not a directory
./run.sh: line 38: utils/mkgraph.sh: Not a directory
./run.sh: line 41: steps/decode.sh: Not a directory
![__H}S@`}_0T)YZSR}4`{3XS](https://user-images.githubusercontent.com/52312989/119384681-a9fff500-bcf7-11eb-89f8-38c3d780687c.png)
![1)O)%6EN@8 @J9M$811)PJD](https://user-images.githubusercontent.com/52312989/119384694-b08e6c80-bcf7-11eb-9515-9c3827035bd8.png)

**Comment by danpovey** [comment]
steps/ and utils/ do not exist; likely you  need to create soft links.

**Comment by kkm000** [comment]
I'm closing this issue, because it is a question, not a feature proposal or a defect report. **We have a forum that is the best place to ask questions**, and getting answers and input from other users as well. We are hanging out there all the time, too. Here, in the issue tracker, we are just too few.

**Kaldi help forum**: https://groups.google.com/forum/#!forum/kaldi-help

**Instructions for joining**: http://kaldi-asr.org/forums.html

If you think I misunderstood your intention, please reply, and I'll reopen it.
