### ISSUE TITLE
steps/nnet3/align_lats.sh vs. steps/nnet3/chain/align_lats.sh

### ISSUE THREAD

**Issue by kkm000** [kaldi-asr/kaldi#4549]
From @vesis84 in #4543
> i just noticed there are 2 very similar files:
> steps/nnet3/align_lats.sh and steps/nnet3/chain/align_lats.sh

Check which of them, and how they are used (if used), and do we really need both. All it normally takes is `cd egs; git grep ...`.

**Comment by desh2608** [comment]
`git grep "steps/nnet3/chain/align_lats.sh"` did not return any matches. In any case, the only differences (from doing a `git diff`: [link](https://www.diffchecker.com/v8NvMLES)) are:
* The chain version has `post_decode_acwt=10.0` since we use `acwt=1.0` for decoding with chain models; so lattices are scaled by this factor after decoding.
* The regular version has an option for `--generate-ali-from-lats` which the chain version does not have.

**Comment by kkm000** [comment]
Yeah, I've always used the steps/nnet3/chain/align_lats.sh (non-"chain" version), but I never cared about scaling LM weight so that it's on the order of 10^1 rather than 10^0. Interesting that the non-chain version has it like 
```
  if [[ $frame_subsampling_factor -gt 1 ]]; then
    # Assume a chain system, check agrument sanity.
```
so they are related. Both are checking agrument sainty in a slightly different way.

@danpovey, your call:
1. Kill steps/nnet3/chain/align_lats.sh
2. Transplant the `post_decode_acwt` option into steps/nnet3/align_lats.sh and kill steps/nnet3/chain/align_lats.sh.

My personal preference is (1), but I dunno if that's important: I never cared about LM weight being 1.3 and not 13, and also am in the habit of using a small DNN for forced alignment of the training set. It's not better, the training is very forgiving of imprecise alignment;, but it's ×10 faster than a gmm.

We already have mindbogglingly too many scripts to I'm all for culling them.

**Comment by danpovey** [comment]
If we're not using steps/nnet3/chain/align_lats.sh I think we can just
remove it; if there are complaints we can deal with that later.

**Comment by kkm000** [comment]
Bingo!

**Comment by kkm000** [comment]
Awww, this was stuck on the tip of my tongue for 16 minutes, if I'm to trust GitHub timekeeping:

> I hate code and I want as little of it as possible in our product.

— Jack Diederich (@jackdied), in a 2012 PyCon tech talk.

**Comment by lalimili6** [comment]
> 2\. Transplant the `post_decode_acwt` option into steps/nnet3/align_lats.sh and kill steps/nnet3/chain/align_lats.sh.

@kkm000 why remove  `post_decode_acwt` option in steps/nnet3/align_lats.sh? Is it Ok or must add it to script?

**Comment by danpovey** [comment]
The option --post-decode-acwt was added when we went to the "chain" models because they are run with acoustic-scale 1.0, not 10.0 like the regular nnet3 models, and this causes problems with scoring scripts because we use integer LM scales; the --post-decode-acwt fixes that.
