### ISSUE TITLE
Assertion fail: "Frames must be accessed in order." when retrying decoding with DecodableNnetSimpleLooped

### ISSUE THREAD

**Issue by AlexVestin** [kaldi-asr/kaldi#4550]
Hi,

I'm trying to use [nnet3-align-compiled](https://github.com/kaldi-asr/kaldi/blob/master/src/nnet3bin/nnet3-align-compiled.cc), but having swapped the `DecodableAmNnetSimple` to a `DecodableNnetSimpleLooped`. This works well if the beam is large enough to decode first try, but if it [needs to retry](https://github.com/kaldi-asr/kaldi/blob/master/src/decoder/decoder-wrappers.cc#L615) it fails [this assertion](https://github.com/kaldi-asr/kaldi/blob/master/src/nnet3/decodable-simple-looped.h#L209) with:

```WARNING (nnet3-align-compiled[5.5.0~5-445a]:AlignUtteranceWrapper():decoder-wrappers.cc:617) Retrying utterance shutdown with beam 4000
ASSERTION_FAILED (nnet3-align-compiled[5.5.0~5-445a]:GetOutput():nnet3/decodable-simple-looped.h:210) Assertion failed: (subsampled_frame >= current_log_post_subsampled_offset_ && "Frames must be accessed in order.")

[ Stack-Trace: ]
nnet3-align-compiled(kaldi::MessageLogger::LogMessage() const+0x6ec) [0x5616da75351c]
nnet3-align-compiled(kaldi::KaldiAssertFailure_(char const*, char const*, int, char const*)+0x6e) [0x5616da753e3d]
nnet3-align-compiled(+0x1de366) [0x5616da51f366]
nnet3-align-compiled(kaldi::FasterDecoder::ProcessEmitting(kaldi::DecodableInterface*)+0x2b1) [0x5616da66a467]
nnet3-align-compiled(kaldi::FasterDecoder::AdvanceDecoding(kaldi::DecodableInterface*, int)+0x4f) [0x5616da66a839]
nnet3-align-compiled(kaldi::FasterDecoder::Decode(kaldi::DecodableInterface*)+0x21) [0x5616da66a8b3]
nnet3-align-compiled(kaldi::AlignUtteranceWrapper(kaldi::AlignConfig const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, float, fst::VectorFst<fst::ArcTpl<fst::TropicalWeightTpl<float> >, fst::VectorState<fst::ArcTpl<fst::TropicalWeightTpl<float> >, std::allocator<fst::ArcTpl<fst::TropicalWeightTpl<float> > > > >*, kaldi::DecodableInterface*, kaldi::TableWriter<kaldi::BasicVectorHolder<int> >*, kaldi::TableWriter<kaldi::BasicHolder<float> >*, int*, int*, int*, double*, long*, kaldi::TableWriter<kaldi::KaldiObjectHolder<kaldi::VectorBase<float> > >*)+0x376) [0x5616da5d6822]
nnet3-align-compiled(main+0x12a7) [0x5616da49c3d0]
/usr/lib/libc.so.6(__libc_start_main+0xd5) [0x7fbea6681b25]
nnet3-align-compiled(_start+0x2e) [0x5616da49b05e]
```

subsampled_frame was 0 and current_log_post_subsampled_offset_ ~7000 when logging, so
I'm guessing the DecodableNnetSimpleLooped needs some sort of reset.  I tried hacking together a reset of the `current_log_post_subsampled_offset_` and `encoded_chunks` variables, but that didn't do the trick.  Is there any way to make the `DecodableNnetSimpleLooped` work with retries?

**Comment by danpovey** [comment]
I don't think there is currently a way to do that with caching (other than
just recreating the decoder object, which would cause it to recompute
everything).

**Comment by AlexVestin** [comment]
Recreating the decoder object worked for my use-case, I really just wanted to avoid reloading the fst / models.
Thanks!
