### ISSUE TITLE
build with ndk error: xxx is incompatible with elf64-x86-64

### ISSUE THREAD

**Issue by zrct0** [kaldi-asr/kaldi#4559]
Iread the blog:https://raspberrypibeginner.wordpress.com/2020/08/23/how-to-build-kaldi-for-android-9-on-arm-v7/
and have a  problem.
This is the shell script I use

```
NDK_ROOT=/home/ubuntu1604/Downloads/android-ndk-r22b
MY_TOOLCHAIN=$NDK_ROOT/toolchains/llvm/prebuilt/linux-x86_64
NDK_INCLUDE=$MY_TOOLCHAIN/sysroot/usr/include

export PATH=$MY_TOOLCHAIN/bin:$PATH

CXX=clang++ \
./configure --static \
--use-cuda=no \
--fst-root=../tools/openfst/ --fst-version=1.7.2 \
--openblas-root=/home/ubuntu1604/Downloads/kaldi/OpenBLAS-develop/android-openblas/armv7a2 \
--android-incdir=$NDK_INCLUDE \
--host=arm-linux-androideabi

make depend clean

sed -i 's/-g # -O0 -DKALDI_PARANOID/-O3 -DNDEBUG/g' kaldi.mk

make clean -j

make depend -j

make -j 4
```

I find the compiled .o files are all elf64_x86_64.  Not ARM!
And I Have the same error when I compile openfst.

```
$ file openfst-1.7.2/src/lib/compat.o
openfst-1.7.2/src/lib/compat.o: ELF 64-bit LSB relocatable, x86-64, version 1 (SYSV), not stripped
```

**Comment by zrct0** [comment]
It seems like --host=arm-linux-androideabi didn't work

**Comment by jtrmal** [comment]
start with the basic check -- after

export PATH=$MY_TOOLCHAIN/bin:$PATH

you should do:

hash -r

which clang++

and check the clang++ has the correct path

y.

**Comment by zrct0** [comment]
I Have check my clang++ path many time. 
If the path of clang++ is wrong, the error is another, like this:configure failed: arm-linux-androideabi-clang++ is not installed

**Comment by kkm000** [comment]
I'm closing this issue, because it is a question, not a feature proposal or a defect report. **We have a forum that is the best place to ask questions**, and getting answers and input from other users as well. We are hanging out there all the time, too. Here, in the issue tracker, we are just too few.

**Kaldi help forum**: https://groups.google.com/forum/#!forum/kaldi-help

**Instructions for joining**: http://kaldi-asr.org/forums.html

If you think I misunderstood your intention, please reply, and I'll reopen it.

**Comment by EDLLT** [comment]
> Iread the blog:https://raspberrypibeginner.wordpress.com/2020/08/23/how-to-build-kaldi-for-android-9-on-arm-v7/ and have a problem. This is the shell script I use
> 
> ```
> NDK_ROOT=/home/ubuntu1604/Downloads/android-ndk-r22b
> MY_TOOLCHAIN=$NDK_ROOT/toolchains/llvm/prebuilt/linux-x86_64
> NDK_INCLUDE=$MY_TOOLCHAIN/sysroot/usr/include
> 
> export PATH=$MY_TOOLCHAIN/bin:$PATH
> 
> CXX=clang++ \
> ./configure --static \
> --use-cuda=no \
> --fst-root=../tools/openfst/ --fst-version=1.7.2 \
> --openblas-root=/home/ubuntu1604/Downloads/kaldi/OpenBLAS-develop/android-openblas/armv7a2 \
> --android-incdir=$NDK_INCLUDE \
> --host=arm-linux-androideabi
> 
> make depend clean
> 
> sed -i 's/-g # -O0 -DKALDI_PARANOID/-O3 -DNDEBUG/g' kaldi.mk
> 
> make clean -j
> 
> make depend -j
> 
> make -j 4
> ```
> 
> I find the compiled .o files are all elf64_x86_64. Not ARM! And I Have the same error when I compile openfst.
> 
> ```
> $ file openfst-1.7.2/src/lib/compat.o
> openfst-1.7.2/src/lib/compat.o: ELF 64-bit LSB relocatable, x86-64, version 1 (SYSV), not stripped
> ```

Did you ever find a solution for this?
I am facing a similar issue
