### ISSUE TITLE
Kaldi Windows built libs not linking into downstream projects

### ISSUE THREAD

**Issue by trias702** [kaldi-asr/kaldi#4572]
Hello,

I am trying to compile Gentle on Windows, which relies on Kaldi. I have successfully built Kaldi for Windows using the very detailed instructions in the github (thank you for that), and I do see that I have built nearly all of the executables for Windows as well as a large number of libs, which I assume I can use for static linking in downstream applications which want to statically link to Kaldi.

The Gentle package has a small C++ console application which relies on Kaldi. I am currently trying to build this console app in Visual Studio 2017. The C++ side compiles correctly, but I'm getting a ton of linker errors, it appears that it's not linking against any of the Kaldi libs which I generated when I built Kaldi for Windows.

Are there by any chance any special compiler or linker flags I need to be using in the console app so that it can correctly link against the Kaldi windows libs? I have pointed everything to the correct directories where the header and lib files are located, but the linker fails every time, against all symbols (so nothing is linking). I have analysed the symbols in the lib files using DUMPBIN /ALL and I do see the correct symbols inside, which match the mangled names I'm seeing in my linker errors in Visual Studio, but for some odd reason, the linking is just not happening.

Is there anything at all which might be causing this? When Kaldi for Windows builds, how does it statically link against the openfst lib, because I'm not even able to link against that either in my console app. Would greatly appreciate any help.

For reference, this is the downstream console app I'm trying to build with the linked in Kaldi Windows libs: https://github.com/lowerquality/gentle/blob/master/ext/k3.cc

**Comment by jtrmal** [comment]
Make sure the compile architectures are the same.  That can sometimes
generate surprises in vs
Y.

**Comment by trias702** [comment]
Everything is being compiled with Release x64, so am not sure that is the issue.

If it's not a great imposition, could I please trouble you to see if you're able to statically link against any of the Kaldi Windows libs in anything? Just create a simple "hello world" app and see if you can link it against any of the Kaldi windows libs? Or even try to build that same Gentle downstream app?

Am very curious to see if you can replicate the issue on your end.

**Comment by kkm000** [comment]
Also make sure that Debug/Release match everywhere. Microsoft ABIs for Debug  and Release often do not match (stdc++ library is only one of the offenders).

**Comment by jtrmal** [comment]
I apologize but I won't be able to help with compiling it myself -- I
don't have a windows machine ATM.
y.

**Comment by trias702** [comment]
No worries. Thank you both for the help, I managed to solve the issue in the end. The core issue was I needed to set the RuntimeLibrary flag on the downstream console app to MultiThreadedDLL, which seems a bit odd since it's a console app, but that and a few other little fixes and extra flags, and I was able to finally get everything linked together and it appears to be working. Thank you kindly for providing those Windows specific Kaldi build instructions, it was very helpful.

Just one quick question about those Windows Kaldi building instructions: in the readme.MD, you give instructions for downloading and compiling PortAudio, however, you don't seem to actually do anything with it. There are no instructions for integrating PortAudio into the main Kaldi Windows compile instructions. Looking at the vxcproj files for WinKaldi, I can see they depend on OpenFST and OpenBLAS, but the instructions don't say to do anything with PortAudio. Is there a missing instruction somewhere for what to do with PortAudio once it's compiled?

**Comment by kkm000** [comment]
Get Windows port of OpenFST here: https://github.com/kkm000/openfst/

Use MKL on Windows, forget OpenBLAS.

I do not think PortAudio for Window exists. You do not want to use it.

Instructions are outdated.

Do not compile whole Kaldi. Training on Windows is a PITA not worth it. You need a functional bash, for one. Select individual cc files that you need for inferencing (first take more, then use the linker's map to cull the herd). 

If you have no other option, use WSL2.

---

I am closing this issue for now. If you believe that your issue has not been addressed, please feel free to ping me, and I'll reopen it. @-mention me for a faster response!
