### ISSUE TITLE
Are the websites down?

### ISSUE THREAD

**Issue by m2kulkarni** [kaldi-asr/kaldi#4575]
Sorry for creating an issue here, but I haven't been able to access the webites, https://kaldi-asr.org/ as well as https://www.openslr.org/12. Running into this issue since ~22 hours (15:30 IST, 21st June), was working fine just before that.

Created this issue since I saw a similar one ~2yrs ago #2911

**Comment by jtrmal** [comment]
thanks for letting us know. Should work now -- sometimes users using smart
downloaders completely overload the computer.
y.

**Comment by m2kulkarni** [comment]
Thanks!, closing the issue
