### ISSUE TITLE
CPU runtime without CUDA drivers no longer working for CUDA build.

### ISSUE THREAD

**Issue by vesis84** [kaldi-asr/kaldi#4576]
Hello,
in the past kaldi built with CUDA worked on a machine without CUDA driver installed when running CPU only code.
This seems to be no longer the case since the adoption of this change :
https://github.com/kaldi-asr/kaldi/commit/2ad159073f0fb1e57b1b89b0e534ee9c91738367

Would it be possible to revert the change ? It is causing problems for our update of kaldi to the current version...

Best regards
Karel

**Comment by danpovey** [comment]
What happens when you try to use this version?

**Comment by galv** [comment]
Can you let me know how you are able to handle dependencies like libcufft, libcusparse, and libcublas? It would seem to me that you are going to run into linking issues for those if you build with cuda but try to run on a CPU-only machine. Are you statically linking them?

I'm also curious about what specific error you get, if you were to copy /usr/local/cuda/lib64/stubs/libcuda.so into your Dockerfile and add it to the LD_LIBRARY_PATH. I believe other libraries (like tensorflow) also use the dlopen() and dlsym() methods of loading libcuda.so as well, so I'm not opposed to your suggestion. I am just skeptical of making the change  unnecessarily without checking if the stub libraries have a non-broken enough fake implementation to make things work.

**Comment by vesis84** [comment]
we alredy found a workaround, but the original idea of calling certain functions from libcuda.so via dlopen
was to be able to recover from the situation when the libcuda.so was not available
(i.e. the CUDA driver was not installed on the machine where it was running)
but that was already years ago...

**Comment by vesis84** [comment]
> libcufft, libcusparse, and libcublas
all these come from the cuda toolkit. and they are not depending on libcuda.so.

it is easy to install cuda toolkit to machine without GPU, 
but installing cuda driver to machine without GPU, i had the idea that that is already big requirement...

**Comment by vesis84** [comment]
so, the new version should behave about the same ?
(but now with LD_LIBRARY_PATH=$(CUDATKDIR)/lib64/stubs if libcuda.so is missing)

aha, I tried it that way and it worked...

thanks!
