### ISSUE TITLE
Build error when downloading openfst from openslr.org

### ISSUE THREAD

**Issue by tjysdsg** [kaldi-asr/kaldi#4595]
When running make in `tools/`, the following error is raised:

```
https://www.openslr.org/resources/2/openfst-1.7.2.tar.gz:                                                                             
2021-07-22 10:43:23 ERROR 404: Not Found.                    
make: *** [openfst-1.7.2.tar.gz] Error 8
```

In [`tools/Makefile`](https://github.com/kaldi-asr/kaldi/blob/master/tools/Makefile#L10), the default openfst version used is 1.7.2, but there's no openfst 1.7.2 uploaded to openslr.org

**Comment by kkm000** [comment]
Thanks, we'll check. More interesting, the first download attempt is done from http://www.openfst.org/twiki/pub/FST/FstDownload/openfst-1.7.2.tar.gz -- do you have access to this site? I just downloaded it from there.

If all else fails, use https://github.com/kkm000/openfst/archive/refs/tags/orig/1.7.2.1.tar.gz. But you'll have to unpack it manually, and then rename the directory it unpacks into from `openfst-orig-1.7.2.1` to `openfst-1.7.2`.

**Comment by tjysdsg** [comment]
Thanks for the answer! It seems that the download from openfst.org timed out multiple times, therefore the second link (openslr.org) was used.

I did manually download the zip and solved the issue, but I thought I should remind you that the zip wasn't uploaded to openslr xD

**Comment by kkm000** [comment]
Yup, that's not right. It's notable that it has timed out. It hosted at Google. Probably has to to with some, ahem, unreliable network in between...

@danpovey or @jtrmal. I don't know who of you guys admins openslr contents, but could you please upload 1.7.2 and 1.7.9 (which is our target for upgrade, per https://github.com/kaldi-asr/kaldi/issues/4565#issuecomment-862039667)? Alternatively, I can hack tools/Makefile to OpenFST from my and @jtrmal repo: I'm always keeping a clean branch there (`original`) and tag it with their 4-cmponent tag.revision, although they no longer the revision.

**Comment by jtrmal** [comment]
I'm on it.
y.

**Comment by jtrmal** [comment]
should be done.
y.

**Comment by kkm000** [comment]
@jtrmal  thanks!
