### ISSUE TITLE
<builtin>: recipe for target 'word-align-lattice-lexicon.o' failed

### ISSUE THREAD

**Issue by realspacepen** [kaldi-asr/kaldi#4600]
Hello, I am trying to install Kaldi on Ubuntu 18.04 and Vmware Workstation16 from scratch. I have made files in /tools ,but failed to implement "make depend "in /src folder,it will be interrupted as follows:

make[1]: Leaving directory '/home/hjr/MyKaldi/kaldi/src/sgmm2'
g++ -std=c++14 -I.. -isystem /home/hjr/MyKaldi/kaldi/tools/openfst-1.7.2/include -O1 -Wall -Wno-sign-compare -Wno-unused-local-typedefs -Wno-deprecated-declarations -Winit-self -DKALDI_DOUBLEPRECISION=0 -DHAVE_EXECINFO_H=1 -DHAVE_CXXABI_H -DHAVE_MKL -I/opt/intel/mkl/include -m64 -msse -msse2 -pthread -g -Wno-sign-compare   -c -o word-align-lattice-lexicon.o word-align-lattice-lexicon.cc
g++ -std=c++14 -I.. -isystem /home/hjr/MyKaldi/kaldi/tools/openfst-1.7.2/include -O1 -Wall -Wno-sign-compare -Wno-unused-local-typedefs -Wno-deprecated-declarations -Winit-self -DKALDI_DOUBLEPRECISION=0 -DHAVE_EXECINFO_H=1 -DHAVE_CXXABI_H -DHAVE_MKL -I/opt/intel/mkl/include -m64 -msse -msse2 -pthread -g -Wno-sign-compare   -c -o sausages.o sausages.cc
g++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-7/README.Bugs> for instructions.
<builtin>: recipe for target 'word-align-lattice-lexicon.o' failed
make[1]: *** [word-align-lattice-lexicon.o] Error 4
make[1]: *** Waiting for unfinished jobs....
make[1]: Leaving directory '/home/hjr/MyKaldi/kaldi/src/lat'
Makefile:147: recipe for target 'lat' failed
make: *** [lat] Error 2

My gcc and g++ version are 7.5.0. I still have 40GB free disk to install. What should I do? Please help me, thanks!

**Comment by kkm000** [comment]
You ran out of memory. Decrease the parallelism value that you pass to `-j`. It should be normally at most the number of GB of free RAM you have divided by 2.

This is a message I've seen too many times, which is a 100% indication of compiler running OOM under Linux:
```
g++: internal compiler error: Killed (program cc1plus)
```
