### ISSUE TITLE
Input and output of training FSTs in E2E 

### ISSUE THREAD

**Issue by mohsen-goodarzi** [kaldi-asr/kaldi#4603]
If I understood currently, supervision FSTs are like decoding FSTs except that they are restricted to the true transcription, instead of whole language model (G.sft). So I expected that the output of them to be word indexes.

But, in the descriptive comment of [chain-generic-numerator.h](https://github.com/kaldi-asr/kaldi/blob/master/src/chain/chain-generic-numerator.h#L55) it is mentioned that:

> Of course, the end-to-end FST still has to be epsilon-free and have pdf_id+1
> on its input and output labels, just like the regular supervision FST.

Did I missed something or above quote is not correct?

**Comment by hhadian** [comment]
AFAIR it doesn't matter if the output labels are word id's or pdf-id's. The thing is for decoding FSTs we do need the word labels so we keep them. Here we don't need them.
Note that the loss function operates on senones (which are identified by pdf-id's).

**Comment by mohsen-goodarzi** [comment]
So, as we are treating the supervision FSTs as acceptors, the outputs don't matter to us.
Thank you!
