### ISSUE TITLE
#4560 breaks scripts

### ISSUE THREAD

**Issue by jtrmal** [kaldi-asr/kaldi#4604]
The following changeset  005627469eb89128a3 introduces changes in parameters accepted by the combine2 binary (namely --print-interval) -- which causes  the binary to crash when called from some scripts (they have that param hardcoded)
```
index e83553efd..b6c842b2e 100644
--- a/src/chainbin/nnet3-chain-combine2.cc
+++ b/src/chainbin/nnet3-chain-combine2.cc
@@ -111,6 +111,7 @@ int main(int argc, char *argv[]) {
         dropout_test_mode = true;
     std::string use_gpu = "yes";
     chain::ChainTrainingOptions chain_config;
+    NnetChainTraining2Options opts;

     ParseOptions po(usage);
     po.Register("binary", &binary_write, "Write output in binary mode");
@@ -129,6 +130,7 @@ int main(int argc, char *argv[]) {
                 "DropoutMaskComponents while evaluating objectives.");

     chain_config.Register(&po);
+    opts.Register(&po);

     po.Read(argc, argv);

```

**Comment by jtrmal** [comment]
@kkm000 it's your change but I don't see if it was overlooking or if it had another reason.
y.

**Comment by kkm000** [comment]
The parameter is really unused, so I'd prefer not accepting it just for the sake of accepting. Are there many scripts like that?

**Comment by jtrmal** [comment]
Well, I don't know because the chain2 stuff is not used very often, I have a report of just one issue. I guess fixing the script would be better then.

**Comment by kkm000** [comment]
Yup. Useless parameters are certainly confusing. Wanna send a PR?

**Comment by jtrmal** [comment]
yeah, I'll ask the other guy to prepare it. Might take some time, tho, it
will be his first.
y.

**Comment by kkm000** [comment]
Sure! 'git grep' is his best friend, FWIW :)

**Comment by jtrmal** [comment]
👍
