### ISSUE TITLE
Loading kaldi nnet3cuda2 gpu code in memory

### ISSUE THREAD

**Issue by nome2050** [kaldi-asr/kaldi#4608]
i am using batched-wav-nnet3-cuda2 to do inference on my data using gpu and it takes about 9 seconds to do inference as the time contains the model loading time

Is there any way i can load the model in memory with gpu batched-wav-nnet3-cuda2 code so i can just keep on taking transcriptions from the loaded model

**Comment by danpovey** [comment]
The intention is that you definitely load the model just once and do the infererence multiple times.
You'll have to build some kind of server/daemon type program that keeps it in memory.
You may be able to get inspiration from the program in the Kaldi repo that has 'tcp' in its name (search for it).
