### ISSUE TITLE
Portaudio Binary wget 404 | Breaks Install

### ISSUE THREAD

**Issue by Bug-Reaper** [kaldi-asr/kaldi#4615]
Pretty much just the title, portaudio.com has been down all day at least. Breaks install of kaldi like this:

```
****() Installing portaudio
Could not find portaudio tarball pa_stable_v19_20111121.tgz
Trying to download it via wget!
--2021-08-23 03:03:31--  http://www.portaudio.com/archives/pa_stable_v19_20111121.tgz
Resolving www.portaudio.com (www.portaudio.com)... 107.22.210.58
Connecting to www.portaudio.com (www.portaudio.com)|107.22.210.58|:80... failed: Connection timed out.
Retrying.

--2021-08-23 03:03:42--  (try: 2)  http://www.portaudio.com/archives/pa_stable_v19_20111121.tgz
Connecting to www.portaudio.com (www.portaudio.com)|107.22.210.58|:80... failed: Connection timed out.
Retrying.

--2021-08-23 03:03:54--  (try: 3)  http://www.portaudio.com/archives/pa_stable_v19_20111121.tgz
Connecting to www.portaudio.com (www.portaudio.com)|107.22.210.58|:80... failed: Connection timed out.
Giving up.

Download of pa_stable_v19_20111121.tgz - failed!
Aborting script. Please download and install port audio manually!
make: *** [Makefile:107: check_portaudio] Error 1
==> ERROR: A failure occurred in build().
    Aborting...
The command '/bin/sh -c makepkg' returned a non-zero code: 4
```

I'm going to check if this problem is specific to the AUR/Arch-Linux install script but I'd imagine this will break things for others. Does anyone have this tarball? Also where should I place it for the build to succeed? 

On a 1,000ft view is it time to look at alternative solutions to fill the role of port-audio? I'm not familiar at all to what extent/importance it's used, but perhaps there's an opportunity here. Alternatively, (license allowing) portaudio could be bundled with kaldi directly?

**Comment by Bug-Reaper** [comment]
Okay as far as I can tell looks like it fails mid flight when running `make` from most recent source.

**Comment by danpovey** [comment]
We should create a mirror of that on openslr.org in case that fails.  I am
hoping @kkm000 and/or @jtrmal could help with that.

**Comment by Bug-Reaper** [comment]
Hey there, so I think I fixed this by grabbing what I assume is the same version of portaudio from it's github releases page:
https://github.com/PortAudio/portaudio/releases/tag/pa_stable_v19_20111121_r1788

Here is  the fork where I changed the portaudio_install script to make it work:
https://github.com/Bug-Reaper/kaldi 

Open to cleaning this up a little for a PR. Really very little was changed.

**Comment by danpovey** [comment]
A verbatim version of that would be fine, I think.

**Comment by cansubmarinesswim** [comment]
I've added [pull request](https://github.com/kaldi-asr/kaldi/pull/4616) that falls back to downloading from git when portaudio.com is down - hopefully it will be back at some point.

**Comment by kkm000** [comment]
@jtrmal, I want the keys to the kingdom, no less!
