### ISSUE TITLE
Phonetisaurus G2P fail to run phonetisaurus-train in modern Ubuntu18/20

### ISSUE THREAD

**Issue by davidlin409** [kaldi-asr/kaldi#4619]
It has been a very long issue of Kaldi that, Kaldi is using tag "kaldi" to build Phonetisaurus-g2p. However, in modern OS (such as Ubuntu 18 or 20), original default of "python==python2" has already being changed to "python==python3", and also Python installed by Kaldi is named python2 without soft-link to python. This causes the python script `phonetisaurus-train` to raises exception due to Python-2 code running under Python-3. 

For this issue, Phonetisaurus-g2p has already has a version that fixes this issue and directly support Python-3. However, current "kaldi" tag in phonetisaurus-g2p is still in a commit that uses Python-2. Is it possible to push "kaldi" tag in phonetisaurus-g2p a little bit forward such that the line below does not raises exception, under the condition that "python==python3"?

```bash
#!/usr/bin/env python
```

For reference, one possible exception is the use of `ur"xxxxxxx"` syntax in `phonetisaurus-train`.

PS: I have searched issues and pull-request and seems that this issue has not being mentioned before. If it does, then this issue will not be necessary.

**Comment by jlalfonso21** [comment]
I faced this issue once and solve it changing the alternatives for the python executable. This [post shows](https://linuxhint.com/update_alternatives_ubuntu/) how to do it. Also you may face some dependencies broken if you do this since the new alternative may not contain all modules necesary for doing some tasks. Hope this helps you.

**Comment by kkm000** [comment]
> Is it possible to push "kaldi" tag in phonetisaurus-g2p a little bit forward

That would be a good idea, but where is the repository? Can you submit a PR with a fix there?

**Comment by AdolfVonKleist** [comment]
It's here: pull request is welcome
https://github.com/AdolfVonKleist/Phonetisaurus

2021年9月28日(火) 11:24 kkm000 ***@***.***>:

**Comment by davidlin409** [comment]
How do I update phonetisaurus tag using Github pull-request? 

I tries to make a pull request but I am stopped at code compare (there is no button to start pull-request).

My tag of "kaldi" for phonetisaurus is at
https://github.com/davidlin409/Phonetisaurus/releases/tag/kaldi

**Comment by AdolfVonKleist** [comment]
@davidlin409 I am pretty sure you cannot add the tag during the PR.  You can create the PR, basically following the same pattern you do for Kaldi, then I'll merge it into master, and update the tag in the parent repo.  In theory I think that should do the trick [assuming you have already tested everything you need to on the Kaldi side, which I think you have].

**Comment by davidlin409** [comment]
Since I did not change any code, I can not create pull-request ("kaldi" tag is not a branch). 

Therefore, I will create an issue inside "https://github.com/AdolfVonKleist/Phonetisaurus", to show how the tag is changed from which old commit to new one. And then the tag renew process might need to be done by author.

**Comment by AdolfVonKleist** [comment]
@davidlin409 ok.  if you create an issue with the exact instructions I can perform the update and also update the tag.  it may take me until the weekend to get to it.

**Comment by kkm000** [comment]
@davidlin409, @AdolfVonKleist, thank both of you guys! This is really helpful, given that python2 is officially dead. I'm closing this in favor of carrying over to AdolfVonKleist/Phonetisaurus#68.

**Comment by kkm000** [comment]
I'm wondering why do we need a tag for Kaldi at all. There is no special code for Kaldi, and the tag tags a random 4-yr-old commit f01a36495. The commentary from the tag itself explains the reasoning:

> We'll track and update this going forward so we can tie the kaldi scripts to single, stable reference location so that updates to this repo won't break things there going forward, and we can update the tag to the next stable release in the future.

This makes sense, until it does not: someone caring about 100% reproducibility may always refer to a commit by its ID. Git own submodules, as one example, always use target's SHA as a reference point. In fact, _moving_ the tag is going to do exactly the opposite to what it was crated for: break scripts referring to the tag (they are already broken by the expiration of Python 2, but).

And in fact the very next commit _after_ the `kaldi` tag is a bug fix from @jtrmal that affects Kaldi...

Maybe we should not use a special tag at all? @danpovey, @jtrmal, what do you think?

**Comment by jtrmal** [comment]
I have to spend my time reminding what was the purpose... Cannot provide
response right away.

**Comment by AdolfVonKleist** [comment]
I think that tag was added at that time as a request for the build actually. I guess it does not affect the python2/3 component of the suggestion.  It's also just generally a pretty old piece of software at this point.  In any case I'll update main as promised; but won't touch the tag for the moment.

**Comment by AdolfVonKleist** [comment]
I've done the following for now: 
 * Update the README info to python3.8, Ubuntu 20.04, and openfst 1.7.2 (which seems to be the current default in kaldi).
 * Update the `kaldi` tag to the latest master

* https://github.com/AdolfVonKleist/Phonetisaurus
* https://github.com/AdolfVonKleist/Phonetisaurus/releases/tag/kaldi

**Comment by kkm000** [comment]
@AdolfVonKleist, thank you!

@danpovey, do you think we in fact need this tag?

**Comment by danpovey** [comment]
I don't think we need the tag, not sure why it exists.
