### ISSUE TITLE
ERROR of sampling frequnecy when doing online decoding using online2-wav-nnet3-latgen-faster

### ISSUE THREAD

**Issue by ZihanLiao** [kaldi-asr/kaldi#4620]
I’m doing decoding using my trained CNN-TDNN acoustic model.
The sampling rate of my wave file is 16000 and I want to downsample it to 8000. I added `--sample-frequency=8000` and `--allow-downsample=true` to the config file. I successfully finished the offline decoding with this config but meet an ERROR during the online decoding.
**ERROR (online2-wav-nnet3-latgen-faster[5.5.759~1-fba1f]:MaybeCreateResampler():online-feature.cc:99) Sampling frequency mismatch, expected 8000, got 16000**
I went to check the online-feature.cc and find something strange. 
`((sampling_rate < expected_sampling_rate) &&
              computer_.GetFrameOptions().allow_downsample) ||
             ((sampling_rate > expected_sampling_rate) &&
              computer_.GetFrameOptions().allow_upsample))`
This judging part seems logically reversed. So, I changed my `--allow--downsample` to`--allow--upsample` and my model can successfully decode now. 
This issue seems to be a bug to me or I just did something wrong during previous steps.

**Comment by danpovey** [comment]
I think you are using an older version of the code, that bug was fixed in 2019 it looks like.
