### ISSUE TITLE
Kick portaudio install out of the main makefile

### ISSUE THREAD

**Issue by kkm000** [kaldi-asr/kaldi#4654]
We already have tools/extras/install_portaudio.sh.

If you need portaudio, install portaudio. Make dependencies are so messed up that portaudio is a dependency of `lmbin`. This makes no sense.

**Comment by Talos878** [comment]
On Ubuntu 20 and mac I have not been able to install without portaudio. Possibly it is still in there for this reason

**Comment by danpovey** [comment]
That may be because of Makefile issues.  I don't think we really need portaudio.

**Comment by jtrmal** [comment]
could you send some detail about the setup/kaldi version?
Plus the compile/configure output?
I just tested in mac and there wasn't any need for portaudio
y.

**Comment by kkm000** [comment]
I am closing this issue for now. If you believe that your issue has not been addressed, please feel free to ping me, and I'll reopen it. @-mention me for a faster response!
