### ISSUE TITLE
Can i use the trained tdnnf model to force aline the data/train . and use the new alignment to train the tdnn

### ISSUE THREAD

**Issue by yuhangear** [kaldi-asr/kaldi#4656]

**Comment by danpovey** [comment]
You can, but it rarely gives an improvement (except if the first TDNN model was trained with the "e2e" scripts).
You have to be careful with options, e.g. --alignment-subsampling-factor, to some of the scripts (if you get this wrong it will crash).  You can look for examples with the "e2e" scripts for how this is done.
