### ISSUE TITLE
data/local/tmp/G.txt in kaldi/egs/rm/s5/local/prepare_wsj_rm_lang.sh?

### ISSUE THREAD

**Issue by ziggy1209** [kaldi-asr/kaldi#4660]
I was adapting kaldi/egs/rm/s5/local/chain/tuning/run_tdnn_wsj_rm_1b.sh to my own data, and everything had been fine until in the last step of kaldi/egs/rm/s5/local/prepare_wsj_rm_lang.sh which is 
> #Generate new G.fst using updated words list with added <SPOKEN_NOISE>
>fstcompile --isymbols=$output_dir/words.txt --osymbols=$output_dir/words.txt --keep_isymbols=false \
>   -keep_osymbols=false data/local/tmp/G.txt | fstarcsort --sort_type=ilabel > $output_dir/G.fst || exit 1;

I got errors saying
>--> data/lang_cgn_jasmin/L.fst is olabel sorted
>--> data/lang_cgn_jasmin/L_disambig.fst is olabel sorted
>--> SUCCESS [validating lang directory data/lang_cgn_jasmin]
> fstcompile --isymbols=data/lang_cgn_jasmin/words.txt --osymbols=data/lang_cgn_jasmin/words.txt -->keep_isymbols=false -keep_osymbols=false data/local/tmp/G.txt
> fstarcsort --sort_type=ilabel
>ERROR: fstcompile: Open failed, file = data/local/tmp/G.txt
>ERROR: FstHeader::Read: Bad FST header: standard input

My FST is fine. I found that this data/local/tmp/G.txt just doesn't exist.... Is the G.txt here just a blank text file?

**Comment by puneetbawa** [comment]
Check that the OOVs are handled correctly, and please visit http://kaldi-asr.org/forums.html for the discussion part. 
I believe we can close this issue.

**Comment by puneetbawa** [comment]
> Check that the OOVs are handled correctly, and please visit http://kaldi-asr.org/forums.html for the discussion part. I believe we can close this issue.

@kkm000
