### ISSUE TITLE
compile kaldi android error: configure failed: aarch64-linux-android-clang++ is not installed [solved]

### ISSUE THREAD

**Issue by 731942771** [kaldi-asr/kaldi#4665]
I compiling for Android using Android NDK, learn from http://jcsilva.github.io/2017/03/18/compile-kaldi-android/
when i make kaldi.mk , erminal process discontinue: 
`***configure failed: aarch64-linux-android-clang++ is not installed.   You need GNU g++ >= 5.0, Apple clang >= 6.0 or LLVM clang >= 3.5. ***`
I don't know that what's wrong,
I created a question on  stackoverflow :
[https://stackoverflow.com/questions/70046819/compile-kaldi-android-error-configure-failed-aarch64-linux-android-clang-is](https://stackoverflow.com/questions/70046819/compile-kaldi-android-error-configure-failed-aarch64-linux-android-clang-is)
thanks for your help .
ps.
how to add  **help wanted**  label here?

**Comment by jtrmal** [comment]
maybe you don't set up the android NDK paths well? or they renamed the
compiler?
y.

**Comment by 731942771** [comment]
> Contributor

Thanks!
yeh, The NDK path is in env, but I used the built-in toolchains.
I rebuild it used make_standalone_toolchain.py today, make kaldi.mk well.
I don't know why, anyway, problem solved.

**Comment by jtrmal** [comment]
great, closing as it's resolved
