### ISSUE TITLE
extras/install_mkl.sh: MKL package intel-mkl-64bit-2020.0-088 installation FAILED.

### ISSUE THREAD

**Issue by 123srikanth** [kaldi-asr/kaldi#4671]
Hi there,

I'm installing the kaldi tool in my system while everything goes fine but I'm not able to install the MKL even after trying with multiple attempts. I will be thankful if someone help in this 

extras/install_mkl.sh: You must be root to install MKL.

Restart this script using the 'sudo' command, as:

  sudo extras/install_mkl.sh -sp debian intel-mkl-64bit-2020.0-088

We recommend adding the '-sp debian' options to skip the MKL and distro
detection, since this has already been done. This minimizes the number of
programs invoked with the root privileges to keep your system safe from
unexpected or erroneous changes. Also, if you are setting the CC environment
variable, sudo might not allow it to propagate to the command that it invokes.

Run the above sudo command now? [Y/n]:y
+ exec sudo extras/install_mkl.sh -sp debian intel-mkl-64bit-2020.0-088
+ apt-get update
Hit:1 https://repo.skype.com/deb stable InRelease
Hit:2 http://dl.google.com/linux/chrome/deb stable InRelease                                                                                 
Hit:3 http://packages.microsoft.com/repos/code stable InRelease                                                                              
Hit:4 http://archive.ubuntu.com/ubuntu bionic InRelease                                                                                      
Ign:5 https://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.6 InRelease                                                                   
Ign:6 https://repo.mongodb.org/apt/ubuntu bionic/mongodb-org/4.4 InRelease                                                                   
Hit:7 http://deb.anydesk.com all InRelease                                                                                                   
Ign:9 http://ppa.launchpad.net/lzh9102/qwinff/ubuntu bionic InRelease                                                                        
Hit:10 http://security.ubuntu.com/ubuntu bionic-security InRelease                                                                           
Hit:11 http://apt.postgresql.org/pub/repos/apt bionic-pgdg InRelease                                                                         
Ign:13 https://repo.mongodb.org/apt/ubuntu bionic/mongodb-org/5.0 InRelease                                                                  
Hit:14 https://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.6 Release                                                                    
Hit:15 https://repo.mongodb.org/apt/ubuntu bionic/mongodb-org/4.4 Release                                                                    
Hit:16 https://ftp.postgresql.org/pub/pgadmin/pgadmin4/apt/bionic pgadmin4 InRelease                                                         
Hit:17 http://ppa.launchpad.net/nilarimogard/webupd8/ubuntu bionic InRelease                                                                 
Hit:18 https://repo.mongodb.org/apt/ubuntu bionic/mongodb-org/5.0 Release                                                                    
Hit:8 https://packages.cloud.google.com/apt kubernetes-xenial InRelease                                                                      
Err:20 http://ppa.launchpad.net/lzh9102/qwinff/ubuntu bionic Release                                                                         
  404  Not Found [IP: 2001:67c:1560:8008::19 80]
Hit:12 http://ftp.harukasan.org/kali kali-rolling InRelease                                                                                  
Hit:21 https://packagecloud.io/slacktechnologies/slack/debian jessie InRelease                                                               
Get:19 https://packagecloud.io/shiftkey/desktop/any any InRelease [23.2 kB]
Err:19 https://packagecloud.io/shiftkey/desktop/any any InRelease
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY B7E65990E879472F
Reading package lists... Done 
E: The repository 'http://ppa.launchpad.net/lzh9102/qwinff/ubuntu bionic Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
W: GPG error: https://packagecloud.io/shiftkey/desktop/any any InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY B7E65990E879472F
E: The repository 'https://packagecloud.io/shiftkey/desktop/any any InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
extras/install_mkl.sh: MKL package intel-mkl-64bit-2020.0-088 installation FAILED.

Please open an issue with us at https://github.com/kaldi-asr/kaldi/ if you
believe this is a bug.

**Comment by kkm000** [comment]
Your apt configuration is thoroughly messed up. Remove all repos mentioned in messages starting with `E:`, at the least. A better practice is to keep only those that you actually need.

I am closing this issue for now. If you believe that your issue has not been addressed, please feel free to ping me, and I'll reopen it. @-mention me for a faster response!

**Comment by zxin4506** [comment]
> Your apt configuration is thoroughly messed up. Remove all repos mentioned in messages starting with `E:`, at the least. A better practice is to keep only those that you actually need.
> 
> I am closing this issue for now. If you believe that your issue has not been addressed, please feel free to ping me, and I'll reopen it. @-mention me for a faster response!

I encountered the same problem now,can you，Can you explain in detail how to solve it?
