### ISSUE TITLE
Is it OK to use nnet3-latgen-faster-batch instead of nnet3-latgen-faster in steps/nnet3/align_lats.sh

### ISSUE THREAD

**Issue by farisalasmary** [kaldi-asr/kaldi#4683]
Hi guys,
I wonder if I can replace `nnet3-latgen-faster` with `nnet3-latgen-faster-batch` in this script to leverage using GPU for lat generation?
https://github.com/kaldi-asr/kaldi/blob/054af6bda820a96dd8d026d144a5263314f31dd3/egs/wsj/s5/steps/nnet3/align_lats.sh#L141

**Comment by al-zatv** [comment]
also interested

**Comment by danpovey** [comment]
You would need to change the binary name, include --add-gpu=yes, and also you'd need to be careful about not allowing more jobs to run thatn you had GPUs.  E.g. add to the $cmd variable used right there, the options: `--gpu 1 --max-jobs-run 4` if you have 4 GPUs and no queueing software (just --gpu 1, if you are using queueing software).  You could add those options after $cmd on line 140.  At least, there's a chance that that might work.  Let me know.

**Comment by farisalasmary** [comment]
Hi @danpovey! 
Thanks for your response!

Unfortunately, I've tried it and it didn't work. Here is my initial debugging results:

in  `nnet3-latgen-faster` it accepts `<fst-in|fsts-rspecifier>` while  `nnet3-latgen-faster-batch` accepts ONLY `<fst-in>`.
I've tried to `gunzip -c my_data/fsts.1.gz > my_data/fsts.1.fst` and used `my_data/fsts.1.fst` as my input to `nnet3-latgen-faster-batch` but it didn't work. What I read and understood so far is that `nnet3-latgen-faster-batch` accpets a single fst but NOT a table of fsts which I didn't really get it.

Here are the lines that I think they are relevant to the problem:

https://github.com/kaldi-asr/kaldi/blob/df1e911bdf8a4ea400e4f52495024324a5d1a93e/src/nnet3bin/nnet3-latgen-faster.cc#L139

https://github.com/kaldi-asr/kaldi/blob/d366a93aad98127683b010fd01e145093c1e9e08/src/nnet3bin/nnet3-latgen-faster-batch.cc#L166


Any ideas or suggestions?

**Comment by danpovey** [comment]
Oh yeah.  Sorry I think it maybe can't be done.   But there may be a
version of nnet3-compute that you.can use to accelerate it.
Or modify the binary.

**Comment by farisalasmary** [comment]
Hi @danpovey @al-zatv,

Here is the best thing I did to get a faster execution:

1- I replaced `nnet3-latgen-faster` with `nnet3-latgen-faster-parallel` in the following line:
https://github.com/kaldi-asr/kaldi/blob/054af6bda820a96dd8d026d144a5263314f31dd3/egs/wsj/s5/steps/nnet3/align_lats.sh#L141

2- I set `--num-threads` argument to 100 threads

I've tried to replace  `nnet3-latgen-faster` with  `nnet3-latgen-faster-batch` by providing `nnet3-latgen-faster-batch` with a HCLG graph that I built using the training data that I wanted to align but I found that It consumed a huge amount of RAM and eventually the process was killed by the OS.
