### ISSUE TITLE
finetune_tdnn_1a.sh error assertion

### ISSUE THREAD

**Issue by peace20162** [kaldi-asr/kaldi#4695]
![image](https://user-images.githubusercontent.com/47591499/152696997-5507c633-16c5-4c47-9e30-dccce72cec61.png)
 I got this error when try to use model for fine-tuning using tdnn_online as source model. This is the reference code [aishell2/s5/local/nnet3/tuning/finetune_tdnn_1a.sh](https://github.com/kaldi-asr/kaldi/blob/master/egs/aishell2/s5/local/nnet3/tuning/finetune_tdnn_1a.sh)

**Comment by danpovey** [comment]
Hm, that script does not work so great anyway.
Can you see if you can adapt the setup in this PR
https://github.com/kaldi-asr/kaldi/pulls
to your problem?  It works better, and you could help test it.
