### ISSUE TITLE
steps/make_mfcc.sh: no such file conf/mfcc.conf kaldi ASR

### ISSUE THREAD

**Issue by hussainwali74** [kaldi-asr/kaldi#4703]
I am very new to kaldi this is probably my own mistake any help is very much appreciated. 

I am working with my own dataset. 
I have cloned voxforge setup and used my dataset. everything seems to work fine I get this error while running the run.sh from s5 folder. any pointers please

```
-1.66041e-07 -0.111651
*** Succeeded in formatting data.
steps/make_mfcc.sh --cmd run.pl --mem 2G --nj 2 data/train exp/make_mfcc/train /kaldi/egs/burushaski/s5/../../../egs/burushaski/s5/burushaski/mfcc
steps/make_mfcc.sh: no such file conf/mfcc.conf

```

*note: I have already done 
make depend clean 
make -j 4

**Comment by danpovey** [comment]
there should be a file egs/something/something/conf/mfcc.conf, create a directory conf/ and put the mfcc.conf from the voxforge recipe there.  (may have to change the sampling rate, usually 8k or 16k, but make sure to also change it in mfcc_hires.conf which will be neede later).

**Comment by hussainwali74** [comment]
@danpovey Sir I can't thank you enough.  Your comment has helped me in solving the issue and now the training is in process. I will inform you about the results, I am creating ASR for a spoken language(it doesn't have a written form) called Burushaski, it's an ancient language spoken in Gilgit Baltistan, Pakistan.
