### ISSUE TITLE
A bug in Kaldi AISHELL-1 run.sh annotation

### ISSUE THREAD

**Issue by HuangruiChu** [kaldi-asr/kaldi#4705]
In aishell/s5/run.sh, there is a bug in the annotation as in line 92 it says:

"# train and decode tri2b [LDA+MLLT]"

However, it only uses [delta+delta-deltas] to train tri2 as shown from line 81 to line 83.

# train tri2 [delta+delta-deltas]
steps/train_deltas.sh --cmd "$train_cmd" \
 2500 20000 data/train data/lang exp/tri1_ali exp/tri2 || exit 1;

This causes confusion when I try to understand the code.

Would you please fix this annotation?

**Comment by danpovey** [comment]
good catch, but it would be nice if you could make a pull request for this.

**Comment by HuangruiChu** [comment]
OK thank you for your suggestion! I have just created a pull request.
