### ISSUE TITLE
GOP: format of text.int and phone.int

### ISSUE THREAD

**Issue by jacksonliscombe** [kaldi-asr/kaldi#4711]
Hello, I am trying to run compile-train-graphs-without-lexicon and am getting an error saying that there is no lexical item for a label that matches my first wav file name. This makes me think that I have the formatting of my text.int and/or text-phone.int files wrong. However, I cannot find an example of any of these files anywhere. Could you please share examples?
Thanks.

**Comment by danpovey** [comment]
there is no text.int file that's a part of any generic Kaldi format, it may
be a part of some local script.  You'd have to look at the
logic of that script to find out, but it's probably just a temporary file.
If you have an error you need to give the actual error message and a bit
more context about what you are running.

**Comment by jacksonliscombe** [comment]
I was able to find an example text-phone file here:
https://github.com/jimbozhang/speechocean762/blob/master/resource/text-phone
There is no script I could find that creates this file according to this
format so I wrote one to do it myself and that made the text-phone.int file
correct down the line.

**Comment by kkm000** [comment]
I am closing this issue for now. If you believe that your issue has not been addressed, please feel free to ping me, and I'll reopen it. @-mention me for a faster response!
