### ISSUE TITLE
Install

### ISSUE THREAD

**Issue by HakkaTjakka** [kaldi-asr/kaldi#4728]
pacman@PACMAN-PC:~/video/kaldi/tools$ make
extras/check_dependencies.sh
extras/check_dependencies.sh: gfortran is not installed
extras/check_dependencies.sh: Some prerequisites are missing; install them using the command:
  sudo apt-get install gfortran
make: *** [Makefile:39: check_required_programs] Error 1
pacman@PACMAN-PC:~/video/kaldi/tools$ sudo apt-get install gfortran
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies.
 gfortran : Depends: gfortran-9 (>= 9.3.0-3~) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.

**Comment by kkm000** [comment]
Looks like your APT repository is broken. `gfortran` is a meta-package, usually referring to a specific version. There is a reference but the package itself is missing. Try `apt install gfortran-9` and see what happens. But this is not a Kaldi issue, and I cannot help much with it. If this does not work, your distro users' forum is a better place to ask.

I am closing this issue for now. If you believe that your issue has not been addressed, please feel free to ping me, and I'll reopen it. @-mention me for a faster response!
