### ISSUE TITLE
Remove use of `std::unary_function`

### ISSUE THREAD

**Issue by h-vetinari** [kaldi-asr/kaldi#4732]
This [facility](https://en.cppreference.com/w/cpp/utility/functional/unary_function) has been deprecated in C++11 and was removed in C++17. In particular, this means the code as-is currently doesn't compile with C++17, which can be problematic because that's often a necessary work-around for CUDA on windows, cf. e.g. https://github.com/microsoft/STL/issues/2020.

**Comment by danpovey** [comment]
Do you have time to try just removing the inheritance from std::unary_function, where it occurs, and seeing whether it affects compilation?  It may not even be necessary.
```
mac:kaldi: git grep unary_function
misc/maintenance/cpplint.py:    ('<functional>', ('unary_function', 'binary_function',
misc/maintenance/cpplint.py:                      'pointer_to_unary_function',
src/lm/arpa-lm-compiler.cc:  struct HashType : public std::unary_function<GeneralHistKey, size_t> {
src/lm/arpa-lm-compiler.cc:  struct HashType : public std::unary_function<OptimizedHistKey, size_t> {
src/nnet3/nnet-compile-utils-test.cc:struct ComparePair : public std::unary_function<std::pair<int32, int32>, bool>
src/nnet3/nnet-compile-utils-test.cc:    public std::unary_function<std::pair<int32, int32>, bool>
```
