### ISSUE TITLE
【help】kaldi tools make error 

### ISSUE THREAD

**Issue by cxyiris** [kaldi-asr/kaldi#4743]
make[3]: *** [fst.lo] 错误 1
make[3]: 离开目录“/root/data/lain/kaldi/tools/openfst-1.7.2/src/lib”
make[2]: *** [install-recursive] 错误 1
make[2]: 离开目录“/root/data/lain/kaldi/tools/openfst-1.7.2/src”
make[1]: *** [install-recursive] 错误 1
make[1]: 离开目录“/root/data/lain/kaldi/tools/openfst-1.7.2”
make: *** [openfst_compiled] 错误 2

**Comment by jtrmal** [comment]
there was some error before you didn't notice -- this is just a way make
finalizes when it encountered an error earlier
you will need to find the previous error. Just run make again with -j 1
y.

**Comment by cxyiris** [comment]
错误：对‘Weight fst::Power(const Weight&, size_t) [with Weight = fst::TropicalWeightTpl<float>; size_t = long unsigned int]’的重声明在‘constexpr’方面
this is error ，how can i do this

**Comment by jtrmal** [comment]
that might be part of the error but not whole of it.  Not easy to figure
out the issue from just one line -- Especially when the rest is Mandarin.
The fact it mentions constexpr might mean your gcc (compiler is too long)
I think you will have to find someone more experienced around you to get
local help.
y.

**Comment by csukuangfj** [comment]
> 错误：对‘Weight fst::Power(const Weight&, size_t) [with Weight = fst::TropicalWeightTpl<float>; size_t = long unsigned int]’的重声明在‘constexpr’方面
> 
> this is error ，how can i do this

You can post the whole error message, i.e., the output from running "make".

Also, please tell us your GCC version.

**Comment by jtrmal** [comment]
The fact it mentions constexpr might mean your gcc (compiler is too long)
->
The fact it mentions constexpr might mean your gcc (compiler) is too old.
Sorry, I don't know what I was thinking about.

**Comment by cxyiris** [comment]
./../include/fst/float-weight.h:389:53: 错误：对‘Weight fst::Power(const Weight&, size_t) [with Weight = fst::TropicalWeightTpl<float>; size_t = long unsigned int]’的重声明在‘constexpr’方面
     const TropicalWeightTpl<float> &weight, size_t n) {
                                                     ^
In file included from ./../include/fst/pair-weight.h:18:0,
                 from ./../include/fst/expectation-weight.h:24,
                 from ./../include/fst/arc.h:15,
                 from ./../include/fst/fst.h:26,
                 from fst.cc:6:
./../include/fst/weight.h:204:8: 错误：与先前的声明‘Weight fst::Power(const Weight&, size_t) [with Weight = fst::TropicalWeightTpl<float>; size_t = long unsigned int]’不同
 Weight Power(const Weight &weight, size_t n) {
        ^
In file included from ./../include/fst/arc.h:16:0,
                 from ./../include/fst/fst.h:26,
                 from fst.cc:6:
./../include/fst/float-weight.h:395:54: 错误：对‘Weight fst::Power(const Weight&, size_t) [with Weight = fst::TropicalWeightTpl<double>; size_t = long unsigned int]’的重声明在‘constexpr’方面
     const TropicalWeightTpl<double> &weight, size_t n) {
                                                      ^
In file included from ./../include/fst/pair-weight.h:18:0,
                 from ./../include/fst/expectation-weight.h:24,
                 from ./../include/fst/arc.h:15,
                 from ./../include/fst/fst.h:26,
                 from fst.cc:6:
./../include/fst/weight.h:204:8: 错误：与先前的声明‘Weight fst::Power(const Weight&, size_t) [with Weight = fst::TropicalWeightTpl<double>; size_t = long unsigned int]’不同
 Weight Power(const Weight &weight, size_t n) {
        ^
In file included from ./../include/fst/arc.h:16:0,
                 from ./../include/fst/fst.h:26,
                 from fst.cc:6:
./../include/fst/float-weight.h:573:48: 错误：对‘Weight fst::Power(const Weight&, size_t) [with Weight = fst::LogWeightTpl<float>; size_t = long unsigned int]’的重声明在‘constexpr’方面
     const LogWeightTpl<float> &weight, size_t n) {
                                                ^
In file included from ./../include/fst/pair-weight.h:18:0,
                 from ./../include/fst/expectation-weight.h:24,
                 from ./../include/fst/arc.h:15,
                 from ./../include/fst/fst.h:26,
                 from fst.cc:6:
./../include/fst/weight.h:204:8: 错误：与先前的声明‘Weight fst::Power(const Weight&, size_t) [with Weight = fst::LogWeightTpl<float>; size_t = long unsigned int]’不同
 Weight Power(const Weight &weight, size_t n) {
        ^
In file included from ./../include/fst/arc.h:16:0,
                 from ./../include/fst/fst.h:26,
                 from fst.cc:6:
./../include/fst/float-weight.h:579:49: 错误：对‘Weight fst::Power(const Weight&, size_t) [with Weight = fst::LogWeightTpl<double>; size_t = long unsigned int]’的重声明在‘constexpr’方面
     const LogWeightTpl<double> &weight, size_t n) {
                                                 ^
In file included from ./../include/fst/pair-weight.h:18:0,
                 from ./../include/fst/expectation-weight.h:24,
                 from ./../include/fst/arc.h:15,
                 from ./../include/fst/fst.h:26,
                 from fst.cc:6:
./../include/fst/weight.h:204:8: 错误：与先前的声明‘Weight fst::Power(const Weight&, size_t) [with Weight = fst::LogWeightTpl<double>; size_t = long unsigned int]’不同

gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-44)
Copyright © 2015 Free Software Foundation, Inc

it's my both error,my gcc version is 4.8.5.Thank you for everyone who reply me.

**Comment by jtrmal** [comment]
Hi, I think gcc 4.8.5 is unfortunately not fully C++11 compliant, so I
suggest trying out a higher version.
It's like 7 years old compiler.

y.

**Comment by jtrmal** [comment]
I'm not familiar with centos/redhat but there should be a way how to
install a newer version
y.

**Comment by waoooNiuBility** [comment]
I met the other error when using the "make" command .
c++: error: ../online2/libkaldi-online2.so: No such file or directory
<builtin>: recipe for target 'nnet3-init' failed
make[1]: *** [nnet3-init] Error 1
make[1]: Leaving directory '/opt/kaldi/src/nnet3bin'
Makefile:168: recipe for target 'nnet3bin' failed
make: *** [nnet3bin] Error 2

**Comment by jtrmal** [comment]
again, there was probably an error before this error, because the library
was not generated.
y.

**Comment by csukuangfj** [comment]
> I met the other error when using the "make" command . c++: error: ../online2/libkaldi-online2.so: No such file or directory : recipe for target 'nnet3-init' failed make[1]: *** [nnet3-init] Error 1 make[1]: Leaving directory '/opt/kaldi/src/nnet3bin' Makefile:168: recipe for target 'nnet3bin' failed make: *** [nnet3bin] Error 2

Please see https://github.com/kaldi-asr/kaldi/pull/4749
It should fix your issue.

**Comment by jtrmal** [comment]
I just merged the fix -- please update kaldi (git pull) and try again. Sorry for the complications

**Comment by jtrmal** [comment]
resolved, I think. Please reopen if there is still an issue

**Comment by nocoolsandwich** [comment]
For me,update gcc can't fix this
