### ISSUE TITLE
spaces in PATH environment

### ISSUE THREAD

**Issue by gchebanov** [kaldi-asr/kaldi#4750]
Fails when some path in PATH environment variable have space.

I fix it for me by adding double quotes just in "tools/config/common_path.sh:5" and "./s2/path.sh"
But when i grep whole repo unsafe PATH update, i see so many occurrences (almost all of them are unsafe).

**Comment by danpovey** [comment]
it may be best to fix this with a soft link on your side.  I'm not convinced that we could easily fix all the issues that would result from having spaces in the directory where you install and use Kaldi.
