### ISSUE TITLE
Como criar uma Ação no Kaldi

### ISSUE THREAD

**Issue by MR-ALLONE** [kaldi-asr/kaldi#4751]
Bom.. eu sou novo nessa área então por isso vim aqui pedir a ajudar de algum ADM ou outro Programador excepcional. minha dúvida é que eu não sei como eu crio uma ação para o meu exemplo de teste Reagir. Exemplo eu falar "Rosquinhas" e após ele entender a palavra ele vai reagir com algum ( IF ) que eu irei colocar... 

OBS: já tentei usar várias coisas para transformar o resultado final em STR e o Imprimir já usei até JSON mas, quando tento isso a palavra fica invisível. se existir outra forma ou eu estiver fazendo errado.. por favor me AJUDEM!!

R = json.dumps(Result)
if "blue" in rec.Result():
    print("blue")

+USEI ISTO E A PALAVRA TAMBÉM FICA INVISÍVEL

**Comment by ExarchD** [comment]
Voce vai encontrar mais ajuda se perguntar em ingles. Me diz como voce ta usando Kaldi? O resultado agora esta em qual forma? Tem um exemplo que voce ta seguindo?

**Comment by jtrmal** [comment]
the code doesn't look like it's from kaldi, so I'm closing it.
