### ISSUE TITLE
How to create an action in Kaldi?

### ISSUE THREAD

**Issue by MR-ALLONE** [kaldi-asr/kaldi#4759]
Well.. I'm new to this area so I came here to ask for the help of some administrator or other exceptional programmer. my question is that I don't know how to create an action for my React test example. For example I say "Donuts" and after he understands the word he will reveal himself with some (IF) that I will put...

OBS: I've tried using several things to transform the final result into STR and Print I've used JSON, but when I try the word is invisible. if there is another way or am i doing it wrong..please HELP me!!

R = json.dumps(Result)
if "blue" in rec.Result():
print("blue")

#I try to use JSON and the (print) as said above is invisible

**Comment by jtrmal** [comment]
Hi, I'm not really sure how to answer because your question doesn't even look related to Kaldi and no-one else answered anyway. You might have a better luck asking somewhere from where the library/code providing your 'Result' comes from.
Sorry!
