### ISSUE TITLE
extras/srilm.sh wont build on MacOS

### ISSUE THREAD

**Issue by sidgupta234** [kaldi-asr/kaldi#4762]
MacOS config: `Darwin Darwin Kernel Version 21.5.0 root:xnu-8020.121.3~4/RELEASE_ARM64_T8101 arm64 arm`
While attempting to run `extras/install_srilm.sh`, am getting the following error message:

```
 MACHINE_TYPE=macosx OPTION= MAKE_PIC= release-programs) || exit 1; \
	done
make[2]: Nothing to be done for `release-programs'.
make[2]: Nothing to be done for `release-programs'.
c++ -Wall -Wno-unused-variable -Wno-uninitialized -Wno-overloaded-virtual -DINSTANTIATE_TEMPLATES  -DHAVE_LIBLBFGS -I/Users/siddharthg/Github-dev/kaldi/tools/srilm/../liblbfgs-1.10/include -I/usr/include -I. -I../../include -DHAVE_ZOPEN  -L/Users/siddharthg/Github-dev/kaldi/tools/srilm/../liblbfgs-1.10/lib/ -Wl,-rpath -Wl,/Users/siddharthg/Github-dev/kaldi/tools/srilm/../liblbfgs-1.10/lib/ -u _matherr -L../../lib/macosx -L/Users/siddharthg/Github-dev/kaldi/tools/srilm/../liblbfgs-1.10/lib/ -Wl,-rpath -Wl,/Users/siddharthg/Github-dev/kaldi/tools/srilm/../liblbfgs-1.10/lib/  -g -O2 -fno-common -o ../bin/macosx/ngram ../obj/macosx/ngram.o ../obj/macosx/liboolm.a  ../../lib/macosx/libflm.a ../../lib/macosx/libdstruct.a ../../lib/macosx/libmisc.a ../../lib/macosx/libz.a -L/usr/lib -ltcl -lm -llbfgs -liconv 2>&1 | c++filt
ld: library not found for -llbfgs
clang: error: linker command failed with exit code 1 (use -v to see invocation)
test -f ../bin/macosx/ngram
make[2]: *** [../bin/macosx/ngram] Error 1
make[1]: *** [release-programs] Error 1
make: *** [World] Error 2
```

**Comment by jtrmal** [comment]
there was probably some error installing libBFGS...
try to run extras/install_liblbfgs.sh (being in tools/) and watch for errors
y.

**Comment by jtrmal** [comment]
hi, any feedback on this?

**Comment by sidgupta234** [comment]
Hi, no it didnt work out. I gave up on setting it up on Mac, and used my linux system instead for Kaldi related work.

**Comment by jtrmal** [comment]
Sorry to hear that. Linux is a better-solution for kaldi and ml/ai anyway
(in long term) because of cuda. Imo
Y.

**Comment by jtrmal** [comment]
also, seems it's related to Apple silicon (M1/M2)
y.

**Comment by kkm000** [comment]
I am closing this issue for now. If you believe that your issue has not been addressed, please feel free to ping me, and I'll reopen it. @-mention me for a faster response!

**Comment by jtrmal** [comment]
I'll keep opened this to make sure I will remember test this further
Y.

**Comment by bonrybon** [comment]
Hi, is there an update on this issue? I am encountering the same issue above:

`make[2]: Nothing to be done for `release-programs'.
c++ -Wall -Wno-unused-variable -Wno-uninitialized -Wno-overloaded-virtual -DINSTANTIATE_TEMPLATES  -DHAVE_LIBLBFGS -I/Users/bonry/kaldi/tools/srilm/../liblbfgs-1.10/include -I/usr/include -I. -I../../include -DHAVE_ZOPEN  -L/Users/bonry/kaldi/tools/srilm/../liblbfgs-1.10/lib/ -Wl,-rpath -Wl,/Users/bonry/kaldi/tools/srilm/../liblbfgs-1.10/lib/ -u _matherr -L../../lib/macosx -L/Users/bonry/kaldi/tools/srilm/../liblbfgs-1.10/lib/ -Wl,-rpath -Wl,/Users/bonry/kaldi/tools/srilm/../liblbfgs-1.10/lib/  -g -O2 -fno-common -o ../bin/macosx/ngram ../obj/macosx/ngram.o ../obj/macosx/liboolm.a  ../../lib/macosx/libflm.a ../../lib/macosx/libdstruct.a ../../lib/macosx/libmisc.a ../../lib/macosx/libz.a -L/usr/lib -ltcl -lm -llbfgs -liconv 2>&1 | c++filt
ld: library not found for -llbfgs
clang: error: linker command failed with exit code 1 (use -v to see invocation)
test -f ../bin/macosx/ngram
make[2]: *** [../bin/macosx/ngram] Error 1
make[1]: *** [release-programs] Error 1
make: *** [World] Error 2`

I tried to run extras/install_liblbfgs.sh  and this is the results.

`checking for a BSD-compatible install... /Users/bonry/kaldi/tools/srilm/install -c
checking whether build environment is sane... yes
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether to enable maintainer-specific portions of Makefiles... no
checking build system type... configure: error: /bin/sh ./config.sub -apple-darwin22.3.0 failed
make: *** No targets specified and no makefile found.  Stop.
make: Nothing to be done for `install'.
libLBFGS config is already in env.sh`

**Comment by nihavend** [comment]
I guess no body is interested in the subject anymore

I got  the same error while trying to `./install_srilm.sh `

```
ld: library 'lbfgs' not found
clang: error: linker command failed with exit code 1 (use -v to see invocation)
test -f ../bin/macosx/ngram
make[2]: *** [../bin/macosx/ngram] Error 1
make[1]: *** [release-programs] Error 1
make: *** [World] Error 2
```

I have the package install via `brew install  liblbfgs` the script can not get that one

I also get error while trying to `./install_liblbfgs.sh`

```
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether to enable maintainer-specific portions of Makefiles... no
checking build system type... configure: error: /bin/sh ./config.sub -apple-darwin23.4.0 failed
make: *** No targets specified and no makefile found.  Stop.
make: Nothing to be done for `install'.
libLBFGS config is already in env.sh
```
maybe someone cares...

**Comment by danpovey** [comment]
Is your Kaldi fully up to date?  About a week ago or less, I merged something about SRILM installation I think.

**Comment by nihavend** [comment]
I guess it is fresh new, I just cloned from github (master branch)
I changed  the blow to the local path and than got the installation completed.
Now the install script uses the one that I installed with brew not the one in repo

from
```
grep ADDITIONAL_LDFLAGS common/Makefile.machine.$mtype | \
    sed 's|$| -L$(SRILM)/../liblbfgs-1.10/lib/ -Wl,-rpath -Wl,$(SRILM)/../liblbfgs-1.10/lib/|' \
    >> common/Makefile.machine.$mtype
```

to
```
grep ADDITIONAL_LDFLAGS common/Makefile.machine.$mtype | \
    sed 's|$| -L/opt/homebrew/opt/liblbfgs/lib/ -Wl,-rpath -Wl,/opt/homebrew/opt/liblbfgs/lib/|' \
    >> common/Makefile.machine.$mtype
```
