### ISSUE TITLE
Option to retry training iteration automatically if failed

### ISSUE THREAD

**Issue by ma08** [kaldi-asr/kaldi#4767]
Hello,

I am running the TDNN training from [WSJ train.py](https://github.com/kaldi-asr/kaldi/blob/master/egs/wsj/s5/steps/nnet3/chain/train.py).

Due to a GPU issue, some of the iterations fail sometimes due to [an assertion error](https://github.com/kaldi-asr/kaldi/blob/9af2c5c16389e141f527ebde7ee432a0c1df9fb9/src/matrix/qr.cc#L123). However if I rerun from the failed iteration using the "stage" parameter, the iteration eventually succeeds and the training moves on to the next iteration. I am able to complete the whole training run using this rerun approach.

Right now, I am manually setting the "stage" parameter as the last failed iteration number and rerunning it till it succeeds.

Is there any option/configuration to do this automatically? If not, would you be interested in a PR that accomplishes this? I would like to work on it.

Regards,
Sourya

**Comment by jtrmal** [comment]
you could modify your cmd.sh to say (e.g.)
train_cmd="retry.pl queue.pl"
(the retry.pl is the important part)
that should try to run the task three times or until the tasks succeed.
Not sure if it's the right way to address your issues, tho
y.

**Comment by ma08** [comment]
Will give it a try. Thanks @jtrmal!

**Comment by ma08** [comment]
@jtrmal Does it work with run.pl (train_cmd="retry.pl run.pl") as well? I am using run.pl as I am using a single machine.

**Comment by jtrmal** [comment]
yeah, should work. It doesn't?
There are/there might be sanity checks outside the scope of the task
packages that are submitted via train_cmd.
If you crash because of one of these, then it won't help.
Show us the error and/or log file and I can have a look if it should help
or not
But I think the proper approach would be setting the training parameters to
have a more stable problem -- I think the qr issues are generally because
not enough data for the given size of NN or too aggressive LR or something
like that.
y.

**Comment by ma08** [comment]
Thanks for your response @jtrmal. I am new to kaldi and it wasn't clear if it would work when I read the documentation for retry.pl

I understand, I spent a lot of time debugging the error/crash and I couldn't figure out what's causing it. So I went ahead with retying it as that atleast made it work.

Thanks a lot for the offer! Can you please take a look at the [logs attached in this discussion](https://groups.google.com/g/kaldi-help/c/XZeUlLtkiog). Please let me know if you need any more information or logs.

Thanks again,
Sourya

**Comment by jtrmal** [comment]
yeah, those belong to stuff run by run.pl/queue.pl so it should work
y.

**Comment by ma08** [comment]
I tried the "retry.pl run.pl" command and it's working! Thanks @jtrmal. 

I am closing this thread. Please take a look at the logs linked above and see if you can pinpoint the cause. I would like to understand the exact root cause.

Thanks again!
