### ISSUE TITLE
compilation is super slow

### ISSUE THREAD

**Issue by malatini42** [kaldi-asr/kaldi#4768]
Hello, I am a noob, trying to use kaldi for diarization. I created my own docker container. I started your "getting started tutorial" https://kaldi-asr.org/doc/tutorial_setup.html. I did a "make" in the tool folder but the compilation is extremely slow (+15 minutes). Would you have a solution please ?

**Comment by jtrmal** [comment]
hi, unless you have superperformant machine, it will definitely take a
substantial amount of time to get everything compiled and ready.
As long as you see new messages, everything is progressing...
y.

**Comment by jtrmal** [comment]
Closing this as there wasn't any follow up.. @malatini42  please let us know if you succeeded or not
