### ISSUE TITLE
mkl install issue

### ISSUE THREAD

**Issue by helpinghandindia1** [kaldi-asr/kaldi#4784]
sh install_mkl.sh
install_mkl.sh: Your system is using redhat-style package management.
install_mkl.sh: line 211: syntax error near unexpected token `<'
install_mkl.sh: line 211: `  IFS=' .' builtin read _ apt_maj apt_min _ < <(apt-get --version)'

**Comment by kkm000** [comment]
`install_mkl.sh` requires bash 3.2 or higher. As does all the rest of Kaldi.

I am closing this issue for now. If you believe that your issue has not been addressed, please feel free to ping me, and I'll reopen it. @-mention me for a faster response!

**Comment by helpinghandindia1** [comment]
Thanks @kkm000 for your reply, current bash is 4.4

[root@localhost Log]# bash -version
GNU bash, version 4.4.19(1)-release (x86_64-redhat-linux-gnu)
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

**Comment by helpinghandindia1** [comment]
@kkm000 
We are trying to install kaldi because we need speech to text for disability education purpose.
we tried voice2json but still facing trouble.
kindly help to resolve issue.

**Comment by kkm000** [comment]
Remove `sh` from the command. In Debian, `sh` is `dash`, not `bash`. The script is executable, just run it. `./install_mkl.sh`.

**Comment by helpinghandindia1** [comment]
hello @kkm000 
Thanks for your guidance, Yes , error is now resolved.

M stuck now on next error

[root@10 tools]# make CXX=g++-4.8
extras/check_dependencies.sh
extras/check_dependencies.sh: Compiler 'g++-4.8' is not installed.
extras/check_dependencies.sh: You need g++ >= 4.8.3, Apple Xcode >= 5.0 or clang >= 3.3.
extras/check_dependencies.sh: Some prerequisites are missing; install them using the command:
  sudo yum install gcc-c++
make: *** [Makefile:39: check_required_programs] Error 1
[root@10 tools]# yum install gcc-c++
Last metadata expiration check: 0:42:34 ago on Fri 26 Aug 2022 03:01:12 PM IST.
Package gcc-c++-8.5.0-15.el8.x86_64 is already installed.
Dependencies resolved.
Nothing to do.
Complete!

**Comment by kkm000** [comment]
1. You _absolutely_ must read a minimum of documentation and follow the build directions: http://kaldi-asr.org/doc/tutorial.html
2. We have a mailing list kaldi-help for user questions. It's a good and helpful community. The issues here are for, well, issues with Kaldi. All pointers in one place are here: https://github.com/kaldi-asr/kaldi#kaldi-information-channels
3. Just type `make`. Add '-j N' if you have N CPUs and enough RAM. The very last message printed by `./configure` explains how to estimate available build parallelism from available CPU and RAM, you can re-run it at any time. The exact configure command is in a comment in one of the first lines of the file `kaldi.mk` created by configure, if you need to recall the exact switches that you gave it. Single-threaded build will take approximately forever. Remove the `CXX=...` part. I'm wondering why you're trying to specify CXX—is it somewhere in our documentation? Then it must be fixed, please give me a pointer. If you got it from someone else's instructions, notify them that they're wrong, please!
4. Maybe a matter of personal opinion, but working as a root won't end well. Kaldi is mostly self-contained w.r.t dependencies (notably excluding MKL, but the install script tries to take as much care of it as possible), as many of our users do not have sudo on school's computing clusters.

**Comment by helpinghandindia1** [comment]
Thanks for your support, 
I will see today
thanks
