### ISSUE TITLE
Installing kaldi on colab

### ISSUE THREAD

**Issue by Lazypanda278** [kaldi-asr/kaldi#4785]
I'm having issues installing kaldi on colab. I understand that the issue is due to colab not supporting symbolic links. Here is the trace.

ln -sf /content/drive/MyDrive/kaldi/src/base/libkaldi-base.so /content/drive/MyDrive/kaldi/src/lib/libkaldi-base.so
ln: failed to create symbolic link '/content/drive/MyDrive/kaldi/src/lib/libkaldi-base.so': Operation not supported
../makefiles/default_rules.mk:58: recipe for target 'libkaldi-base.so' failed
make[1]: *** [libkaldi-base.so] Error 1
make[1]: Leaving directory '/content/drive/MyDrive/kaldi/src/base'
Makefile:164: recipe for target 'base' failed
make: *** [base] Error 2

Any workaround for this ? Thanks.

**Comment by csukuangfj** [comment]
Do you have write permission to `/content/drive/MyDrive/kaldi/src/lib` ?

**Comment by Lazypanda278** [comment]
> Do you have write permission to `/content/drive/MyDrive/kaldi/src/lib` ?

Yes

**Comment by csukuangfj** [comment]
Can you replace `ln -sf` with `cp` ?

**Comment by Lazypanda278** [comment]
> Can you replace `ln -sf` with `cp` ?

Yes, it seems to work fine now. Thank you very much. 

For the reference of anyone facing the same issue, I changed "ln -sf" to "cp" in line 59 of src/makefiles/default_rules.mk. Please note that other lines with ln -sf work fine. There was a problem with only this particular instance for some reason. 

You can close this now. Thank you.
