### ISSUE TITLE
Possible memory leak

### ISSUE THREAD

**Issue by 406112767** [kaldi-asr/kaldi#4786]
use vosk
when I create multiple session kaldi always memory leak

logs:
WARNING (VoskAPI:~HashList():util/hash-list-inl.h:117) Possible memory leak: 17407 != 17408: you might have forgotten to call Delete on some Elems
ASSERTION_FAILED (VoskAPI:CuSubMatrix():cudamatrix/cu-matrix-inl.h:38) Assertion failed: (row_offset >= 0 && col_offset >= 0 && num_rows >= 0 && num_cols >= 0 && row_offset + num_rows <= mat.num_rows_ && col_offset + num_cols <= mat.num_cols_)

**Comment by kkm000** [comment]
This is probably a VOSK issue. At the very least, the warning comes from VoskAPI. Please open the issue there: https://github.com/alphacep/vosk.

I am closing this issue for now. If you believe that your issue has not been addressed, please feel free to ping me, and I'll reopen it. @-mention me for a faster response!

**Comment by nshmyrev** [comment]
@406112767 sorry, what do you mean by "multiple session kaldi" exactly?
