### ISSUE TITLE
Problem in 'create files for data/lang'

### ISSUE THREAD

**Issue by pixel-debug** [kaldi-asr/kaldi#4800]
I'm having the same problem for weeks and can't move on. The issue is, i can't run this comand :

wsj/s5/utils/prepare_lang.sh mycorpus/data/local/lang 'OOV' mycorpus/data/local/ data/lang

without this crash:

wsj/s5/utils/prepare_lang.sh: linha 466: fstcompile: comando não encontrado
wsj/s5/utils/prepare_lang.sh: linha 468: fstarcsort: comando não encontrado
Exception ignored in: <_io.TextIOWrapper name=1 mode='w' encoding='latin-1'>
BrokenPipeError: [Errno 32] Broken pipe

Don't know what to do. I'm running this in the egs directory, since i can't run it in egs/mycorpus without other terminal crash.

I have only one speaker and 14 voice lines (i'm just testing things out). Is that the problem?

**Comment by desh2608** [comment]
I can't read Spanish but I'm guessing that means "command not found". It is likely that you have either not compiled openfst or Kaldi, or don't have it in your path.

**Comment by pixel-debug** [comment]
I figured out where I went wrong, thanks!
