### ISSUE TITLE
openfst fails to compile on i686

### ISSUE THREAD

**Issue by JohnGebbie** [kaldi-asr/kaldi#4808]
Hello, I'm trying to package my [program](https://numenvoice.com) which uses [Vosk](https://github.com/alphacep/vosk-api) which is built upon Kaldi.
I also need to package openfst which is what is giving me trouble.

Openfst compiles just fine on my x86_64 machine, and even cross compiling to i686, but a test fails in the continuous integration when compiling i686 natively.

It is the float equality from the `./configure` file which runs during the install phase (it's run again during the check phase).

This is the output of the build system:
```
configure: error: Test float equality failed! Compile with -msse -mfpmath=sse if using g++.
See `config.log' for more details
=> ERROR: vosk-api-0.3.43_1: pre_build: './configure --host="${XBPS_TRIPLET}" ${CROSS_BUILD:+--host="${XBPS_CROSS_TRIPLET}"} --build="${XBPS_TRIPLET}" --prefix="${wrksrc}/kaldi-${_kaldi_commit}/tools/openfst" --enable-static --enable-shared --enable-far --enable-ngram-fsts --enable-lookahead-fsts --with-pic --disable-bin' exited with 1
=> ERROR:   in pre_build() at srcpkgs/vosk-api/template:57
```

I have tried adding the options it suggests and some, but I get the same error.

I think it passes when cross compiling because it's actually testing my x86_64.
That said, I'm concerned about the underlying float equality issue on i686, even if I skip the test when cross compiling.

I asked the Vosk developer here but didn't get anywhere:
https://github.com/alphacep/vosk-api/issues/1161

This is my build template for Void Linux:
https://github.com/void-linux/void-packages/pull/39015

This is someone elses build template for Alpine Linux:
https://gitlab.alpinelinux.org/alpine/aports/-/merge_requests/41097
I see they have had the same issue and limited the architectures to 64 bit.

I will only target 64 bit architectures if necessary, but I'd be shame, my program seems to work well on my old i686 laptop when cross compiled.

Any thoughts? Is this a build issue or are 32 bit architectures not supported?

Thank you. Sorry this is more an openfst issue than a kaldi one but I saw you had accepted similar issues, and openfst doesn't seem to have a good place for issues.

**Comment by nshmyrev** [comment]
As we discussed in the issue you linked, you can build for 32-bit but you need to cross-compile. And you need to disable runtime checks.

**Comment by JohnGebbie** [comment]
Sorry @nshmyrev, I was unsure because you said it was a technical limitation of memory space, but it does compile natively on i686 as long as I remove the float equality tests.
Do you think it's safe to patch out the float equality tests?

Only cross-compiling does not seem to be a template option in the xbps-src build system, and precompiled binaries are not accepted.

**Comment by JohnGebbie** [comment]
ping. Because of this the void linux and the upcoming alipine packages of vosk and [numen](https://numenvoice.com) are limited to x86_64 and aarch64.

**Comment by jtrmal** [comment]
yes, i think the float equality test can be removed
y.
