### ISSUE TITLE
libLBFGS download fails - wrong URL

### ISSUE THREAD

**Issue by idobenka** [kaldi-asr/kaldi#4849]
On this line it tries to download the libLBFGS package:
https://github.com/kaldi-asr/kaldi/blob/master/tools/extras/install_liblbfgs.sh#L11

And it fails with an error:
```
Installing libLBFGS library to support MaxEnt LMs
--2023-05-02 10:49:23--  https://github.com/downloads/chokkan/liblbfgs/liblbfgs-1.10.tar.gz
Resolving github.com (github.com)... 140.82.112.3
Connecting to github.com (github.com)|140.82.112.3|:443... connected.
HTTP request sent, awaiting response... 502 Bad Gateway
2023-05-02 10:49:24 ERROR 502: Bad Gateway.
```
where given URL: https://github.com/downloads/chokkan/liblbfgs/liblbfgs-1.10.tar.gz is not reachable.

**Comment by danpovey** [comment]
resolved.  hope it works now
