### ISSUE TITLE
make: *** [sph2pipe_v2.5/sph2pipe] Error

### ISSUE THREAD

**Issue by amxsa** [kaldi-asr/kaldi#4855]
/Library/Developer/CommandLineTools/usr/bin/make -C sph2pipe_v2.5
yes
checking for gcc option to accept ANSI C... cc -o sph2pipe -s -w -g -O2  file_headers.c shorten_x.c sph2pipe.c -lm
file_headers.c:100:17: error: call to undeclared library function 'strdup' with type 'char *(const char *)'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
            inporder = strdup( fldsval );
                       ^
file_headers.c:100:17: note: include the header <string.h> or explicitly provide a declaration for 'strdup'
1 error generated.
none needed
checking for main in -lm... yes
checking how to run the C preprocessor... sph2pipe.c:213:16: error: call to undeclared library function 'strdup' with type 'char *(const char *)'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
            hdrfile = strdup( optarg );
                      ^
sph2pipe.c:213:16: note: include the header <string.h> or explicitly provide a declaration for 'strdup'
1 error generated.
make[1]: *** [sph2pipe] Error 1
make: *** [sph2pipe_v2.5/sph2pipe] Error 2
make: *** Waiting for unfinished jobs....

**Comment by divyanx** [comment]
i am facing the same on mac

**Comment by bogdan0083** [comment]
Yeah, I have the same issue. It appeared after Mac OS to Sonoma and Xcode to version 15. Before that I had no issues.
