### ISSUE TITLE
g++: 错误：unrecognized command line option ‘-msse’; did you mean ‘-fdse’

### ISSUE THREAD

**Issue by wwh131** [kaldi-asr/kaldi#4858]
ARM64的机器
在src/上configure报错：
![image](https://github.com/kaldi-asr/kaldi/assets/134466725/47a09809-cd12-44e1-80eb-15ee9011d536)
是因为生成的kaldi.mk上有X86的指令，但是我不知道怎么修改，我删除后它还是自动生成。

**Comment by csukuangfj** [comment]
sse 这些指令，应该不能用于 arm.

**Comment by jtrmal** [comment]
closing -- I believe the issue is spanning from using intel arch flags on arm or some other architecture.
