### ISSUE TITLE
When the following situations occur, the memory will increase

### ISSUE THREAD

**Issue by Ryuk17** [kaldi-asr/kaldi#4877]
```
LOG ([5.5]:CheckMemoryUsage():lat/determinize-lattice-pruned.cc:304) Rebuilt repository in determinize-lattice: repository shrank from 570576 to 400320 bytes (approximately)
LOG ([5.5]:CheckMemoryUsage():lat/determinize-lattice-pruned.cc:320) Did not reach requested beam in determinize-lattice: size exceeds maximum 500000 bytes; (repo,arcs,elems) = (570576,180,89008), after rebuilding, repo size was 400320, effective beam was -3.14713e-05 vs. requested beam 7.5
```
When the following situations occur, the memory will increase. Is threre any solution to reduce the memory cost, when  determinizing lattice?

**Comment by danpovey** [comment]
there should be some kind of max-memory option or max-bytes, something like that, you can change that.
there must be something quite strange about your audio or your graph, to blow up in such a tiny beam (effective beam was -3.14713e-05 ).

**Comment by Ryuk17** [comment]
Hi dan, thanks for your reply. I make a graph for keyword spotting. There are some keywords path and garbage paths in TLG. When the input audio contains no keywords, sometimes，the effective beam is tiny, any suggestion to avoid this problem?

**Comment by danpovey** [comment]
I think most likely for a KWS search problem you would not really need lattice determinization, the  easiest fix may be to just skip that step and get the best path directly.  Some (maybe all) decoders have a function call where you can get the best path without requesting the lattice at all.
