### ISSUE TITLE
Request for prebuilt Android APK demonstrating capabilities

### ISSUE THREAD

**Issue by kmadsen** [kaldi-asr/kaldi#4878]
I'm searching this repository for an apk as I'm evaluating some of the open source options for realtime STT ASR solutions available on mobile devices.

Considering this blog has instructions for installing kaldi on android https://jcsilva.github.io/2017/03/18/compile-kaldi-android/. Is there an apk available for easy download? I can follow the instructions but I'm also unsure if they are out of date considering the post was from 2017.

Thanks for the efforts here!

**Comment by danpovey** [comment]
sorry there isn't one.  search for android on this page for "next-gen Kaldi":
https://github.com/k2-fsa
.. there is some support in "sherpa"

**Comment by csukuangfj** [comment]
@kmadsen 
Please find a list of Android APKs for streaming ASR at the following address for Next-gen Kaldi
https://github.com/k2-fsa/sherpa-onnx/releases

You can find the doc about how to build it at
https://k2-fsa.github.io/sherpa/onnx/android/index.html

You can try ASR with next-gen Kaldi from within you browser without installing anything by visiting
https://huggingface.co/spaces/k2-fsa/automatic-speech-recognition

---

If you are also interested in TTS, you can find a list of APKs at
https://k2-fsa.github.io/sherpa/onnx/tts/apk.html
