### ISSUE TITLE
Error while building docker image: install_mkl.sh

### ISSUE THREAD

**Issue by nbrahme** [kaldi-asr/kaldi#4899]
I run below command in the for docker image on Windows 11:
docker build -t "kaldi:Dockerfile" .

It fails at below point:
Dockerfile:34
--------------------
  33 |
  34 | >>> RUN git clone --depth 1 https://github.com/kaldi-asr/kaldi.git /opt/kaldi && \
  35 | >>>      cd /opt/kaldi/tools && \
  36 | >>>      extras/install_mkl.sh && make -j $(nproc) && \
  37 | >>>      cd /opt/kaldi/src && ./configure --shared && make depend -j $(nproc) && make -j $(nproc)
  38 |
--------------------
ERROR: failed to solve: process "/bin/sh -c git clone --depth 1 https://github.com/kaldi-asr/kaldi.git /opt/kaldi && \tcd /opt/kaldi/tools && \textras/install_mkl.sh && make -j $(nproc) && \tcd /opt/kaldi/src && ./configure --shared && make depend -j $(nproc) && make -j $(nproc)" did not complete successfully: exit code: 2

**Comment by jtrmal** [comment]
I believe docker on windows does not support linux images (unless nowadays run in WSL2)
However, I cannot glean what to issue was, but  I just verified the docker builds function well now.
Feel free to download images from https://hub.docker.com/repository/docker/kaldiasr/kaldi/
