### ISSUE TITLE
NO_PUBKEY on intell error

### ISSUE THREAD

**Issue by adamgallub22** [kaldi-asr/kaldi#4903]
After downlaoding kaldi and following the steps I came across a NO_PUBKEY error when trying to install mkl. I have an intel processor which may be the reason for this issue. The following lines are the screen display with my issue. I came here to find an answer.
 sudo ./install_mkl.sh
./install_mkl.sh: Your system is using debian-style package management.
+ apt-get update
Get:1 https://apt.repos.intel.com/mkl all InRelease [4438 B]
Err:1 https://apt.repos.intel.com/mkl all InRelease
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY BAC6F0C353D04109
Hit:2 https://ppa.launchpadcontent.net/deadsnakes/ppa/ubuntu jammy InRelease
Hit:3 http://archive.ubuntu.com/ubuntu jammy InRelease
Hit:4 http://archive.ubuntu.com/ubuntu jammy-updates InRelease
Hit:5 http://security.ubuntu.com/ubuntu jammy-security InRelease
Hit:6 http://archive.ubuntu.com/ubuntu jammy-backports InRelease
Reading package lists... Done
W: GPG error: https://apt.repos.intel.com/mkl all InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY BAC6F0C353D04109
E: The repository 'https://apt.repos.intel.com/mkl all InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
./install_mkl.sh: MKL package intel-mkl-64bit-2020.0-088 installation FAILED.

Please open an issue with us at https://github.com/kaldi-asr/kaldi/ if you
believe this is a bug.

**Comment by winlaic** [comment]
just remove the list in /etc/apt/sources.list.d/intel-mkl.list

**Comment by jtrmal** [comment]
I believe resolved, please reopen if the issue persists.
