### ISSUE TITLE
Integrate ZLUDA for AMD CUDA

### ISSUE THREAD

**Issue by GermanAizek** [kaldi-asr/kaldi#4906]
**Describe the feature**
@ceefour,
https://github.com/vosen/ZLUDA
it can give feature run CUDA program on amd video cards if cuda code is optimized, and speed up work on amd.

**Comment by jtrmal** [comment]
From FAQ:
Realistically, it's now abandoned and will only possibly receive updates to
run workloads I am personally interested in (DLSS).

**Comment by jtrmal** [comment]
ZLUDA was killed by AMD
