### ISSUE TITLE
issue with install_klm.sh

### ISSUE THREAD

**Issue by alexmplata16** [kaldi-asr/kaldi#4907]
I dont know ehat to do with this:

![Captura desde 2024-02-22 14-42-15](https://github.com/kaldi-asr/kaldi/assets/159952631/4c5cf655-53c5-4f0e-a6d4-422ea6ae2c8e)

**Comment by shrishtis7** [comment]
![Screenshot from 2024-04-03 16-28-33](https://github.com/kaldi-asr/kaldi/assets/104963951/37596d10-1624-4297-93eb-d613f2dfc75b)
I am facing the same issue.

**Comment by jtrmal** [comment]
Intel sometimes forgets to update the signing key in their repository. This is resolved now and we would not be able to fix it anyway :(
