### ISSUE TITLE
windows cuda 12.1 nvtools are no longer part of cuda installer

### ISSUE THREAD

**Issue by 3a1b2c3** [kaldi-asr/kaldi#4910]
As of windows cuda 12.1 nvtools are no longer part of cuda installer. people had some sucess getting them form 11.8 
https://discuss.pytorch.org/t/failed-to-find-nvtoolsext/179635/3
201>LINK : fatal error LNK1181: cannot open input file 'NvToolExt_LIBRARIES-NOTFOUND.lib'

**Comment by danpovey** [comment]
sorry, how does this bug manifest itself?  an error message?  does nvtools have a separate installer?  sorry I haven't developed on Windows for years.

**Comment by 3a1b2c3** [comment]
cmake fails for missing library
![e534b177747e78d4aa786936d04876f9c621b33d](https://github.com/kaldi-asr/kaldi/assets/74843139/517f5a31-706c-4b8e-83b3-d11b413e975b)

**Comment by danpovey** [comment]
do you have any idea what we are actually using from nvtools?
could it be just some boilerplate that got into the cmakefile?

**Comment by 3a1b2c3** [comment]
I was hoping you had the answer to that. Is it strictly required?

**Comment by 3a1b2c3** [comment]
Headers are actually there in 12.1
![image](https://github.com/kaldi-asr/kaldi/assets/74843139/8191680b-639f-44cb-a038-54e5dd38aafc)

**Comment by 3a1b2c3** [comment]
For anyone else wondering its "C:\Program Files\NVIDIA Corporation\NvToolsExt\lib\x64\nvToolsExt64_1.lib"
Sorry for the noise
