### ISSUE TITLE
fisher_callhome_spanish lexicon preparation

### ISSUE THREAD

**Issue by danpovey** [kaldi-asr/kaldi#494]
I just noticed that the script local/fsp_prepare_dict.sh in the fisher-callhome-spanish setup contains the line

if [ -f "/export/a04/gkumar/corpora/gigaword-spanish/bin/gigaword-lexicon.json" ]; then

..
fi

so it's not replicable off our grid.
@noisychannel, it would be good if you could help us fix this.  We could put the file on openslr.org if necessary.

**Comment by noisychannel** [comment]
I'll fix this. Will set this up so that the file is automatically downloaded from OpenSLR and used when running the recipe.

**Comment by jtrmal** [comment]
What is the file's origin -- i.e. are you allowed to distribute that file?
y.

**Comment by jtrmal** [comment]
I mean I know of LDC Spanish Gigaword and I'm quite sure we cannot let any
data from that be freely available.
y.

**Comment by noisychannel** [comment]
It is a list of the most common words in Spanish (64k words sorted by frequency). Even though these results were derived from the Spanish Gigaword corpus, there is no way in which the corpus can be recreated from these results. I don't see the difference between distributing something like this vs. distributing ASR results or lattices. Do you disagree?

**Comment by danpovey** [comment]
It's fine- I'm sure no-one will care about this.

**Comment by jtrmal** [comment]
I guess that's fine.  Perhaps name it in more self-explanatory way
Y.

**Comment by noisychannel** [comment]
Will do.
