### ISSUE TITLE
nnet3 realignment stage in training is broken

### ISSUE THREAD

**Issue by vijayaditya** [kaldi-asr/kaldi#495]
The realignment stage in nnet3 model training does not work. steps/nnet3/relabel_egs.sh is missing.
steps/nnet3/align.sh expects raw_trans* files in transform_dir which is assigned to be ali_dir which initialized as null.

**Comment by danpovey** [comment]
OK, well this is low priority since I don't think it ever gave us that much improvement.  @vimalmanohar, could you please put this on your TODO list to look at?

**Comment by vimalmanohar** [comment]
Ok. I will look into this.

**Comment by jtrmal** [comment]
BTW, from my experience, when you do re-alignment during training, the
frame accuracy jumps up, but there might be no WER improvement.  It
surprised me when I saw this but it makes sense when you realize what's
going on.
y.

**Comment by vijayaditya** [comment]
Abdel Rehman's ASRU'15 paper shows good improvements with realignment.

[image: Inline image 1]

http://research.microsoft.com/pubs/259236/windowed_lstm_asru_2015.pdf



--Vijay

**Comment by danpovey** [comment]
Can you or @vimalmanohar please add suitable options to
steps/nnet3/align.sh so we can realign LSTMs, or add a different script if
that's what you prefer?  I want to ask @hhadian to realign with the LSTM
model for AMI to retrain his duration models.

**Comment by vijayaditya** [comment]
OK, I will take care of this. In the spirit of reducing redundancy I will
make changes to the current script. We previously decided to stop
supporting LDA features in nnet3, should I support SAT features ?

--Vijay

**Comment by danpovey** [comment]
Any feature types/combinations that the training doesn't support, I suppose
it's OK to remove it from the decoding script too.

**Comment by vijayaditya** [comment]
I won't be working on this till mid-April. If someone else wants to take this up they are welcome.

**Comment by vijayaditya** [comment]
Even with the most recent realignment experiments in Babel we didn't see a lot of improvement with realignment (1-2% rel. improvement when reinitializing the model after each realignment). I am not going to work on this any more and I will also remove the code corresponding to this in `steps/nnet3/train_{dnn,rnn}.py`. I also think with chain models which have built-in tolerance option this feature would no longer be relevant.
