### ISSUE TITLE
Move to a newest Neural Networks from T-DNNf

### ISSUE THREAD

**Issue by asr-lord** [kaldi-asr/kaldi#4951]
I'm using a GMM model + [Time-Delay Neural Network factored (T-DNNf)](https://www.danielpovey.com/files/2015_interspeech_multisplice.pdf) + RNN language model (which architecture is composed of 2 LSTM layers with 200 cells, 1 tdnn layer and 1 Dense output layer)  The goal of this model is to build a better language model and can re-score the result obtained in the first pass decoding.

I have been using this arch during a long time and I wonder if there are new neural networks in Kaldi to use for Acoustic and/or Language model. 
Thanks in advance.

**Comment by jtrmal** [comment]
Kaldi is maintenance-only now, so there are no new features nor architectures -- checkout k2 and icefall for new architectures
