### ISSUE TITLE
ngram-context.cc:   ‘SplitString’ is not a member of ‘fst’

### ISSUE THREAD

**Issue by SaintE419** [kaldi-asr/kaldi#4965]
when i install ngram，the following error occurred:

ngram-context.cc:129:8: error: ‘SplitString’ is not a member of ‘fst’
  129 |   fst::SplitString(line, ":", &contexts, true);
      |        ^~~~~~~~~~~
ngram-context.cc:132:8: error: ‘SplitString’ is not a member of ‘fst’
  132 |   fst::SplitString(contexts[0], " ", &labels1, true);
      |        ^~~~~~~~~~~
ngram-context.cc:133:8: error: ‘SplitString’ is not a member of ‘fst’
  133 |   fst::SplitString(contexts[1], " ", &labels2, true);
      |        ^~~~~~~~~~~
ngram-context.cc: In static member function ‘static void ngram::NGramExtendedContext::ParseContextIntervals(const string&, int, std::vector<ngram::NGramContext>*)’:
ngram-context.cc:235:8: error: ‘SplitString’ is not a member of ‘fst’
  235 |   fst::SplitString(line.get(), ",", &context_patterns, true);
      |        ^~~~~~~~~~~

**Comment by danpovey** [comment]
probably FST version issue.  e.g. you may have OpenFST installed in system space with the "wrong" version.

**Comment by SaintE419** [comment]
I checked multiple FST versions（1.8.3/1.7.9/1.7.5/1.6.6） and none of them had "SplitString" member.
According to the README of ngram description, versions later than 1.6.6 can meet the requirements.
Can you tell me the correct version of FST？

**Comment by csukuangfj** [comment]
It is in 1.6.7.1

Please see
https://github.com/kkm000/openfst/blob/fe6ba70cdfaa75d5a39266fad4ee514bdc300571/src/include/fst/util.h#L268

<img width="1010" alt="Screenshot 2024-12-11 at 17 47 05" src="https://github.com/user-attachments/assets/a61cfb81-1ba9-4a12-84b9-7334aaff4248">


The implementation is in
https://github.com/kkm000/openfst/blob/fe6ba70cdfaa75d5a39266fad4ee514bdc300571/src/lib/util.cc#L22

Please see
<img width="1103" alt="Screenshot 2024-12-11 at 17 48 02" src="https://github.com/user-attachments/assets/e9f1835f-27ac-4d77-a61f-4220b0997f24">

**Comment by csukuangfj** [comment]
It turns out it exists in the following tags
- orig/1.6.7.1
- orig/1.6.8.1
- orig/1.6.9.1
- orig/1.6.0.1
- orig/1.7.0.1
- orig/1.7.0.1
- orig/1.7.0.1
- orig/1.7.0.1
- orig/1.7.0.1
- orig/1.7.0.1
- orig/1.7.0.1
