### ISSUE TITLE
Compile error on Raspberry Pi 2 Model B

### ISSUE THREAD

**Issue by vsilent** [kaldi-asr/kaldi#500]
pi@raspberrypi:~/kaldi-trunk/src $ uname -a
Linux raspberrypi 4.1.17-v7+ #834 SMP Mon Feb 1 15:17:54 GMT 2016 armv7l GNU/Linux
RAM: 1G

Last commit: 
commit 117c075076ff9c8b0589913d8cc8770901313ba9
Author: vesis84 <vesis84@gmail.com>
Date:   Thu Feb 11 17:39:46 2016 +0100

    nnet1: added the removal of frames with 0 confidence from mini-batches

./configure gives: 
only relevant for neural net experiments
Static=[false] Speex library not found: You can still build Kaldi without Speex.
g++: error: unrecognized command line option '-msse'
g++: error: unrecognized command line option '-msse2'
make: *** [exp-test] Error 1
./configure: line 212: ./exp-test: No such file or directory
SUCCESS

pi@raspberrypi:~/kaldi-trunk/src $ make
The version of configure script matches kaldi.mk version. Good.
test -d  || mkdir
make -C base
make[1]: Entering directory '/home/pi/kaldi-trunk/src/base'
g++ -msse -msse2 -Wall -I.. -pthread -DKALDI_DOUBLEPRECISION=0 -DHAVE_POSIX_MEMALIGN -Wno-sign-compare -Wno-unused-local-typedefs -Winit-self -DHAVE_EXECINFO_H=1 -rdynamic -DHAVE_CXXABI_H -DHAVE_ATLAS -I/home/pi/kaldi-trunk/tools/ATLAS/include -I/home/pi/kaldi-trunk/tools/openfst/include  -g    -c -o kaldi-math.o kaldi-math.cc
g++: error: unrecognized command line option '-msse'
g++: error: unrecognized command line option '-msse2'
<builtin>: recipe for target 'kaldi-math.o' failed
make[1]: *** [kaldi-math.o] Error 1
make[1]: Leaving directory '/home/pi/kaldi-trunk/src/base'
Makefile:137: recipe for target 'base' failed
make: *** [base] Error 2

make depend also gives an error 
make[1]: Entering directory '/home/pi/kaldi-trunk/src/chainbin'
g++ -M -msse -msse2 -Wall -I.. -pthread -DKALDI_DOUBLEPRECISION=0 -DHAVE_POSIX_MEMALIGN -Wno-sign-compare -Wno-unused-local-typedefs -Winit-self -DHAVE_EXECINFO_H=1 -rdynamic -DHAVE_CXXABI_H -DHAVE_ATLAS -I/home/pi/kaldi-trunk/tools/ATLAS/include -I/home/pi/kaldi-trunk/tools/openfst/include -Wno-sign-compare -g  *.cc > .depend.mk
g++: error: unrecognized command line option '-msse'
g++: error: unrecognized command line option '-msse2'
../makefiles/default_rules.mk:97: recipe for target 'depend' failed
make[1]: [depend] Error 1 (ignored)
make[1]: Leaving directory '/home/pi/kaldi-trunk/src/chainbin'

**Comment by danpovey** [comment]
I wouldn't expect to be able to compile Kaldi on such a tiny machine.  If
you wanted to do embedded work with Kaldi you'd probably compile the entire
toolkit on a bigger machine to train the models, then extract some small
subset of Kaldi just for decoding on the device.  But even that would be
problematic from a speed point of view- it would be very hard to optimize
it to be fast enough.  The most realistic thing is have the device just
extract the audio or features and send it to a remote server for
recognition.

Anyway, the simplest answer at the current time is that Kaldi does not
support embedded operation.  The reason for the specific error doesn't
matter as there will be many more problems after that.

Dan

**Comment by jtrmal** [comment]
Yes,  raspberry is an arm architecture that does not support this
instruction sets.
Simply removing the option could make things work.  I wouldn't expect most
of the  kaldi functionality will be usefull there there anyway.  It's too
limited on memory and CPU.
Y.

**Comment by vsilent** [comment]
Ok, thanks for fast reply. I got pocketsphinx and julius working fine on RPI so I was curious about kaldi on such device. So, no ARM support yet ?

**Comment by jtrmal** [comment]
We didn't try.  You might get it working. But pocketsphinx is designed to
be usable on small devices.  Kaldi is not -  that was never the purpose of
kaldi, so do not expect it will be usable for anything but toy problems.
Y.

**Comment by jtrmal** [comment]
@vsilent in case you decide to pursue this, please contact us on kaldi-help or kaldi-developers (see http://kaldi-asr.org/forums.html). This isn't probably the best place where to discuss in more details

**Comment by aisch** [comment]
@vsilent this should have been fixed by #926 in case you want to try again.
