### ISSUE TITLE
LDA and MLLT

### ISSUE THREAD

**Issue by Love-world** [kaldi-asr/kaldi#503]
Hi! In feature transform,can we only use MLLT without LDA?.Whether there is a script to complete this task? Thanks very much!

**Comment by Love-world** [comment]
Could you introduce me some paper about LDA in your program? Thanks very much!

**Comment by danpovey** [comment]
There is no example script to use MLLT without LDA.
I'm not sure if there is a paper about LDA in speech recognition - IBM
might have one - but it's so simple that it hardly requires one, the
general principles of LDA apply.  The classes are the pdf-ids (i.e. the
clustered states).
Dan

**Comment by Love-world** [comment]
Thank you !
Because of kaldi , you have become very famous in China.Many people worship you very much.

**Comment by danpovey** [comment]
hm.  I suppose that can only be a good thing...

**Comment by Love-world** [comment]
I'm sorry to bother you again.
In my task,I need to MLLT without LDA,so I want to know what is the output of est-lda? You  say it's LDA transformation matrix.Whether I can understand it is W which  can used to transform the original feature x .Namely,y=W*x.
How to show it(.mat).How to write it? 
Thank you!

**Comment by naxingyu** [comment]
在 2016/2/16 16:22, Love-world 写道:
>
> I'm sorry to bother you again.
> In my task,I need to MLLT without LDA,so I want to know what is the 
> output of est-lda?
>
A matrix, named 0.mat in the train_lda_mllt.sh(L101) recipe.
>
> You say it's LDA transformation matrix.Whether I can understand it is 
> W which can used to transform the original feature x .Namely,y=W*x.
>
Yes.
>
> How to show it(.mat).How to write it?
>
Use copy-matrix to show matrix.
>
> Thank you!
>
And this issue session is not a good choice for such A2A. Turn to 
kaldi-help@googlegroups.com for help.

**Comment by Love-world** [comment]
OK!Thank you very much! :)  :+1:

**Comment by jtrmal** [comment]
@Love-world , this is not a suitable place for discussion. See http://kaldi-asr.org/forums.html 
Closing this issue.
