### ISSUE TITLE
speaker-id: In SRE10 examples, use run.pl for all binaries and use "|| exit 1" for errors

### ISSUE THREAD

**Issue by david-ryan-snyder** [kaldi-asr/kaldi#504]
The current way of doing things is hiding informative error messages. 

From Dan on the forums:

> ```
> 
> "  ivector-compute-plda ark:$plda_data_dir/spk2utt \
> 
>     "ark:ivector-normalize-length scp:${plda_ivec_dir}/ivector.scp  ark:- |" \
> 
>       $plda_ivec_dir/plda 2>$plda_ivec_dir/log/plda.log
> ```
> 
> David, if you used run.pl here and did it '|| exit 1', instead of just redirecting the stderr, we'd get more informative error messages."

**Comment by danpovey** [comment]
@david-ryan-snyder, don't forget this..

**Comment by david-ryan-snyder** [comment]
@danpovey we should be able to close this issue now
