### ISSUE TITLE
How to solve the message "Please source the tools/env.sh in your path.sh to enable it"?

### ISSUE THREAD

**Issue by akita1987** [kaldi-asr/kaldi#515]
After I install IRSTLM, it shows "Please source the tools/env.sh in your path.sh to enable it", but there is no env.sh file under directory /kaldi/tools/. How to solve the problem? Or is it just ok if I ignore this message? Thank you !

**Comment by jtrmal** [comment]
How did you install the IRSTLM? Did it say something before this message?
Did you call it in the tools directory, like this:
$ extras/install_irstlm.sh?

y.

**Comment by jogrimst** [comment]
I can reproduce this (Debian 3.16.7-ckt25-2):

After installing (making) Kaldi, we're running the script for Wall Street Journal English:

cd egs/wsj/s5/
./run.sh

```
local/wsj_data_prep.sh: Error: the IRSTLM is not available or compiled
local/wsj_data_prep.sh: Error: We used to install it by default, but.
local/wsj_data_prep.sh: Error: this is no longer the case.
local/wsj_data_prep.sh: Error: To install it, go to /root/github/kaldi/egs/wsj/s5/../../../tools
local/wsj_data_prep.sh: Error: and run extras/install_irstlm.sh
```

kaldi/tools/extras/install_irstlm.sh
```
***() Installation of IRSTLM finished successfully
***() Please source the tools/env.sh in your path.sh to enable it
```

But there is no env.sh file in the fools folder. Any suggestions?

@BorjaArtamendi

**Comment by danpovey** [comment]
You can ignore the message, but we'll address it.

**Comment by cxy19941228** [comment]
oh,I have the same question,how do you solve it??
many thanks

**Comment by AlexWu1108** [comment]
Me too ! i don't what it means!

**Comment by danpovey** [comment]
to source a file foo.sh in UNIX (assuming it's in the current diretory)
means to do something like
. ./foo.sh
in BASH, although in other shells like C shell the syntax would be more
like "source ./foo.sh".
All the path.sh files currently do source env.sh, so you shouldn't have to
take any action.

**Comment by willendzw** [comment]
The env.sh is not under tools/extras/. It is under  tools/. So you just need to
source env.sh. It just add irstlm path. Eg:
export IRSTLM=/home/willen/Documents/kaldi/kaldi/tools/irstlm
export PATH=${PATH}:${IRSTLM}/bin

**Comment by Sujith-sunny** [comment]
> The env.sh is not under tools/extras/. It is under tools/. So you just need to
> source env.sh. It just add irstlm path. Eg:
> export IRSTLM=/home/willen/Documents/kaldi/kaldi/tools/irstlm
> export PATH=${PATH}:${IRSTLM}/bin

What exactly should we do in order to solve this issue sir, please guide me, i am new to linux

**Comment by hussainwali74** [comment]
if you open the  env.sh you'll see the variables have already been set, so you can just ignore these
