### ISSUE TITLE
Waiting for subprocesses in steps/nnet3/train_rnn.py

### ISSUE THREAD

**Issue by vijayaditya** [kaldi-asr/kaldi#520]
In the current [train_rnn.py](https://github.com/kaldi-asr/kaldi/blob/master/egs/wsj/s5/steps/nnet3/train_rnn.py) script I do not wait for the background processes (compute_{train,valid}_prob.sh and progress.sh) launched during training before exiting the job. 

A simple way to do this is to keep track of all the subprocess handles launched during training and wait for these to complete before the training script exits. There are two issues with this solution. I won't know if any of the subprocesses died due to an error until the end of the training and I would have to maintain the list. Is there a better way to do this ?

**Comment by vijayaditya** [comment]
I was looking into various ways to implement this functionality. I think the best thing to do is the following.

1. Create a <code>BackgroundProcessHandler</code> class which has object variable <code>process_queue</code>.
2. The  <code>BackgroundProcessHandler</code> will be instantiated by the top level training script and will be passed to <code>nnet3_train_lib.RunKaldiCommand</code> which will push the process_handles of all background process to <code>process_queue</code>.
3. The <code>BackgroundProcessHandler</code> which will be run on a parallel thread will periodically (every 10 minutes) check the state of all processes and print warnings in the logger if there are any errors in the processes.
4. The training script will wait for all background processes to complete before exiting.

**Comment by danpovey** [comment]
Seems reasonable.

**Comment by vijayaditya** [comment]
@vimalmanohar Another thing that needs to be addressed in case you have time. ( #1066 )
