### ISSUE TITLE
nbest-to-lattice and linear-to-nbest incompatibility.

### ISSUE THREAD

**Issue by qwertyuiop7370** [kaldi-asr/kaldi#536]
Hello
I have got the next problem:
nbest-to-lattice wants in 'nbest' file:
_utt_id_a-1, utt_id_a-2_
but linear-to-nbest create in 'nbest' file:
_utt_id_a_

and linear-to-nbest can not read file created by nbest-to-lattice.

**Comment by danpovey** [comment]
this is not the place to ask this, see kaldi-asr.org/forums.html
an 'nbest' is actually a lattice, just with one path-- so there is no need for linear-to-nbest, since there is just one path.
