### ISSUE TITLE
Job monitor in nnet3 python training scripts

### ISSUE THREAD

**Issue by vijayaditya** [kaldi-asr/kaldi#538]
I would like to add support for job monitoring in the python scripts. This monitoring functionality would do the following : 
- Relaunch training jobs which fail
- Monitor the average duration of jobs and send alerts to the user if there is a lot of deviation from the expected duration.This would normally be necessary when the jobs go into Eqw status or when the jobs run at 2 or 3 times the duration due to IO latency issues. These are issues I frequently see.

My current idea is to add these as features to the python training script. I am looking for any other requirements/suggestions that can be folded into this.

@danpovey @jtrmal Could you please tag this as an "enhancement"

**Comment by danpovey** [comment]
I'm a little bit cautious about making the python scripts too complicated.
But I'd be interested to see what you propose in more detail.
Dan

**Comment by vijayaditya** [comment]
I would create a seperate steps/nnet3/monitor.py module. This would have necessary methods to compute duration stats and monitor processes. 
I would modify the TrainNewModels functions in the train scripts to call the Monitor method in monitor module with the process_handles of the jobs launched (around [here](https://github.com/kaldi-asr/kaldi/blob/master/egs/wsj/s5/steps/nnet3/train_rnn.py#L379)). It would also pass a process_stats dictionary which the monitor module would use to store relevant stats across TrainNewModels calls.

Isolating this monitoring functionality into a separate module would ensure that we don't complicate the train*.py scripts and the code can be reused across train_rnn.py, train_dnn.py and chain/train.py.

**Comment by danpovey** [comment]
sounds reasonable.
if you print warnings they should go to the stderr or stdout as well as to
email (if set up).
Dan

**Comment by vijayaditya** [comment]
OK.

--Vijay

**Comment by jtrmal** [comment]
I added the tag.
