### ISSUE TITLE
Will kaldi support plda transform?

### ISSUE THREAD

**Issue by StevenLOL** [kaldi-asr/kaldi#547]
I saw the ivector-plda-scoring.cc mix the plda transform and scoring together, is it a good idea to have a standalone plda transformer ?

So much like the ivector-transform.cc

And can be called via

ivector-plda-transform plda_transform.mat ark:ivectors.ark ark:transformed_ivectors.ark

**Comment by danpovey** [comment]
see my response on the list.
There is a function
double TransformIvector(const PldaConfig &config,
                          const VectorBase<double> &ivector,
                          VectorBase<double> *transformed_ivector) const;

but PLDA is not like LDA in that it's just a question of transforming to a
certain space and then doing a dot product or whatever.  There is also a
within-class covariance that needs to be taken into account, and there is a
formula to apply.
So it's not clear to me how useful this functionality would be-- unless you
can enlighten us.
Dan

**Comment by StevenLOL** [comment]
Oh, thanks.
