### ISSUE TITLE
nnet3- small task

### ISSUE THREAD

**Issue by danpovey** [kaldi-asr/kaldi#55]
This task is for anyone who can do it and has free time.
If you check out the nnet3 branch of the code and build it, you'll notice that there is a test failure in nnet3-optimize-test:

LOG (UnitTestNnetOptimize():nnet-optimize-test.cc:111) Output sum (not optimized) is -33558.6
LOG (UnitTestNnetOptimize():nnet-optimize-test.cc:113) Output sum (optimized) is -34012.6
ERROR (UnitTestNnetOptimize():nnet-optimize-test.cc:115) Non-optimized and optimized versions of the computation give different outputs.
terminate called after throwing an instance of 'std::runtime_error'
  what():  ERROR (UnitTestNnetOptimize():nnet-optimize-test.cc:115) Non-optimized and optimized versions of the computation give different outputs.

[stack trace: ]
kaldi::KaldiGetStackTrace()
kaldi::KaldiErrorMessage::~KaldiErrorMessage()
kaldi::nnet3::UnitTestNnetOptimize()
./nnet-optimize-test(main+0xe3) [0x54903b]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xfd) [0x7f3de3f45ead]
./nnet-optimize-test() [0x547b69]

What needs to be done is a refactoring and change to  UnitTestNnetOptimize(), so that when it detects a mismatch like this, it will turn on the optimizations in the NnetOptimizeOptions config one by one and show the output-sum for each one separately, and hopefully, as a convenience, try to inform the user which of those optimizations seems to be the issue.
Vijay was going to do this but he is very busy right now and I thought it's the kind of thing we could find someone from the list to do.

Dan

**Comment by kkm000** [comment]
Taken.

**Comment by danpovey** [comment]
thanks..

**Comment by kkm000** [comment]
```
ERROR (UnitTestNnetOptimize():nnet-optimize-test.cc:189) Test failed with all optimizations enabled. Retried test with the following optimizations turned off:
  propagate_in_place   ... FAILURE
  backprop_in_place    ... FAILURE
  remove_assignments   ... SUCCESS
  initialize_undefined ... FAILURE
  move_sizing_commands ... FAILURE
```
PR in a sec.
