### ISSUE TITLE
Make ASpIRE's combine_ali_dirs.sh script more general

### ISSUE THREAD

**Issue by vijayaditya** [kaldi-asr/kaldi#553]
The [combine_ali_dirs.sh](https://github.com/kaldi-asr/kaldi/blob/master/egs/aspire/s5/local/multi_condition/combine_ali_dirs.sh) script in ASpIRE is failing when used for other recipes. This scripts makes some simple assumptions to have an efficient implementation, but even these seem to be violated in other recipes. @xiaohui-zhang is writing a more generic version which though expensive in terms of IO transfer makes no assumptions.

**Comment by xiaohui-zhang** [comment]
I'm done with that:-) Do you think I should commit to babel-kaldi only?

On Fri, Mar 4, 2016 at 4:31 PM, Vijayaditya Peddinti <
notifications@github.com> wrote:

> The combine_ali_dirs.sh
> <https://github.com/kaldi-asr/kaldi/blob/master/egs/aspire/s5/local/multi_condition/combine_ali_dirs.sh>
> script in ASpIRE is failing when used for other recipes. This scripts makes
> some simple assumptions to have an efficient implementation, but even these
> seem to be violated in other recipes. @xiaohui-zhang
> <https://github.com/xiaohui-zhang> is writing a more generic version
> which though expensive in terms of IO transfer makes no assumptions.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kaldi-asr/kaldi/issues/553>.
>



-- 
Xiao-hui

**Comment by danpovey** [comment]
An even simpler solution would be to, after speed-perturbing the data, just
align everything again, including the un-perturbed portion.  This would
also be compatible with the new, simpler interface to the data-pertubing
that I have in utils/data/perturb_data_dir_speed_3way.sh   (this is
currently only in the chain branch).

Dan

**Comment by vijayaditya** [comment]
This script is required for cases where realignment is not an option. e.g. reverberation+noise addition.
In many recipes the best thing is to use clean alignments even for noisy audio. So we create copies of the clean alignments for noisy data by modifying their utterance ids and combine these copies.

**Comment by vijayaditya** [comment]
@xiaohui-zhang Could you test it a bit more and submit it as a script in utils/.

**Comment by xiaohui-zhang** [comment]
sure.

**Comment by vimalmanohar** [comment]
This script seems unnecessarily complicated for what it seems to be doing. Isn't it easier to just write the clean alignment as ark,scp and then add the necessary utt-prefix to scp final and do the required splitting with split_scp.pl or filter_scp.pl and write compressed alignments if needed? I do something like that in my VAD setup.

**Comment by vijayaditya** [comment]
It needs to do that for 6000hrs of data. This means that it can't open all
the alignments at the same time.

**Comment by danpovey** [comment]
I think Vimal my be right here.
How about this: for each input ali-dir, copy all of the gzipped archives
temporarily to ark,scp.  Then merge-sort (sort -m) the scp files from the
individual input-dirs to a single scp file, and use utils/filter_scps.pl to
filter the scp file to appropriate chunks.  Then use copy-int-vector to
copy to individual gzipped archives.  Then remove the temporaries.



Dan

**Comment by vijayaditya** [comment]
@danpovey sorry I missed this comment. @xiaohui-zhang  Do you have time to implement this ? If not I will take this up in a month.

**Comment by xiaohui-zhang** [comment]
Don't worry. It's on me!

**Comment by vijayaditya** [comment]
@xiaohui-zhang  any updates ?

**Comment by xiaohui-zhang** [comment]
done! please review #725
