### ISSUE TITLE
how to read the source code of kaldi

### ISSUE THREAD

**Issue by dujiajiyi-xue** [kaldi-asr/kaldi#559]
I want to to something for accleration timit with GPU,but now I found that I can not how to read the source code,I even do not know where I should read it.
    I  would appreciate it if you could give me some suggestions.

**Comment by danpovey** [comment]
it's in src/ once you download Kaldi.

**Comment by dujiajiyi-xue** [comment]
i know it's in it,but how could i read it.are there some suggesstions that i could complie it on vs2010

**Comment by danpovey** [comment]
This is not the appropriate place to ask (see kaldi-asr.org/forums.html) but I strongly suggest that you do not attempt to use Kaldi, you obviously don't have the right background.
