### ISSUE TITLE
arpa2fst rewrite

### ISSUE THREAD

**Issue by danpovey** [kaldi-asr/kaldi#565]
rewrite arpa2fst to use @kkm000's new code.

**Comment by naxingyu** [comment]
Then I won't commit the --bos-sym and --eos-sym options...

在 2016/3/9 5:10, Daniel Povey 写道:

**Comment by danpovey** [comment]
it's OK if you do, it won't hurt- I was just saying if you have more time
you could attempt the replacement.

**Comment by kkm000** [comment]
Looks like I am working on the same thing. @naxingyu, I'll integrate your work--I have not started on the utility itself yet. Let's coordinate the efforts in any case. See #579.

**Comment by danpovey** [comment]
Kirill, he just added a couple lines to arpa2fst.cc to pass in the options.
Dan


On Fri, Mar 11, 2016 at 3:05 PM, Kirill Katsnelson <notifications@github.com

**Comment by kkm000** [comment]
Sure, I seen it, a change very much inline with what I am doing, and thank you @naxingyu for it. I just wanted to avoid duplicating a possible bigger piece of work.

**Comment by naxingyu** [comment]
I just made a minor change on the old binary. But I'm happy to 
coordinate on anything if you need.

在 2016/3/12 5:12, Kirill Katsnelson 写道:
