### ISSUE TITLE
Error in `ngram': munmap_chunk()

### ISSUE THREAD

**Issue by yingzha** [kaldi-asr/kaldi#571]
Hi all,

When I'm trying to convert n-gram model to G.fst for swbd, I'm okay with 1-gram/2-gram. However, for 3-gram/4-gram, I had such problem 
*** Error in `ngram': munmap_chunk(): invalid pointer: 0x00007f78a1911e10 ***
Aborted (core dumped)
I checked through the internet, there is no much solution for this issue. Could you tell me how to deal this this problem?

**Comment by jtrmal** [comment]
This is not the right place to ask this kind of questions -- please see
http://kaldi-asr.org/forums.html
Also, please be careful and provide as many details as possible, for example

if it's in ngram, then it relates probably more to the srilm toolkit.
Which version you have? Did you install it using the provided script?
It can be a bug in srillm or in gcc/glibc. What versions you have?
Are you using the default swbd recipe?

y.

**Comment by danpovey** [comment]
BTW, for memory errors like this it's generally helpful to run it in
valgrind, e.g.
valgrind (program) (args).
it will show more detailed errors.
If a Kaldi program is crashing, like arpa2fst, show us the full command
line and the valgrind errors.  And make sure your Kaldi is up to date (do
`git pull` and recompile in src/).
Dan

**Comment by yingzha** [comment]
Thanks a lot!
