### ISSUE TITLE
rename --l2-regularize option in chain binaries and scripts

### ISSUE THREAD

**Issue by vijayaditya** [kaldi-asr/kaldi#578]
It has happened a few times that people assumed <code>--l2-regularize</code> was regularization on neural network weights. This is understandable as this regularization is typically used on weights. Renaming this option to <code>--l2-regularize-outputs</code> could remove this confusion.

**Comment by danpovey** [comment]
For now I'd rather just update comments and usage strings etc.-- it's one
more thing that could go wrong, and it's not clear to me that this
confusion is consequential at all, because there's no implication for how
you tune it.
Dan

**Comment by danpovey** [comment]
Actually, it's OK with me to do this, as long as you update all the scripts that might be using the option.

**Comment by vijayaditya** [comment]
OK, I will do this after Interspeech. I don't want to mess with people's experiments with unnecessary merge conflicts now.

**Comment by vijayaditya** [comment]
I am swamped and this is not critical, so just ignoring this issue.
