### ISSUE TITLE
how to fuse the outputs of cnn and dnn as input feature

### ISSUE THREAD

**Issue by colingogo** [kaldi-asr/kaldi#586]
I'm new in Kaldi, I want to construct a network with both CNN and DNN as feature extractors, then the outputs need to be concatenated, but I can't find any script or bin file to do this. Is there any existed scripts for help or If I have to modified the source code, may someone give me a  clue how to do it, thank you very much.

**Comment by vijayaditya** [comment]
Please specify the version of nnet you are using.

--Vijay

**Comment by colingogo** [comment]
I'm working with the nnetbin file, I need to concatenate the output from one convolution layer and the output from a 2-hidden-layer fully-connected layer, may I have your suggestions? @vijayaditya

**Comment by vijayaditya** [comment]
I am not very familiar with nnet1 code. I think Karel/Harish might be of
help.

--Vijay

**Comment by colingogo** [comment]
Does the nnet2 or nnet3 have similar functions? Would you please guide me, I will check this code. Thank you very much. @vijayaditya

**Comment by vijayaditya** [comment]
@tomkocse recently committed a CNN recipe which combines CNN outputs with ivectors processed by a fully connected layer. You can take a look at [this recipe](https://github.com/kaldi-asr/kaldi/blob/5e15b8cb32a839a0ec0422d33ca47f627f7a8d2a/egs/swbd/s5c/local/nnet3/run_tdnn.sh).

I am closing this issue as things like this should be discussed in the mailing list. You can make your further enquiries about this topic in the kaldi-help@googlegroups.com mailing list.
