### ISSUE TITLE
How to Run the sample program .?

### ISSUE THREAD

**Issue by BalajiChinna** [kaldi-asr/kaldi#588]
Hi all, Thanks.

   I am builded Kaldi in Ubuntu machine. I searched a lot and there are lot of library and binaries are builded in the directory. I ran the sample program from "egs/voxforge/online_demo" using run.sh file. This script file has pointed two mode "Live" and "wav".Run.sh file is pointing the method "online-wav-gmm-decode-faster" from "src/onlinebin" for "wav" mode. Onlinebin folder has four type of method. I tried "online-server-gmm-decode-faster" method and got some server error. 

Two question I had,
1. Which one from "src/onlinebin"  sample executable  of Kaldi .?

2.How to improve Indian Voice recognition.?

**Comment by kronos-cm** [comment]
Hi,

First of all, manners like this should be discussed in the mailing list. You can make your further enquiries about this topic in the kaldi-help@googlegroups.com mailing list.

Kaldi is a toolkit so the bunch of binaries you send on the bin folders in src are the individual tools kaldi uses to build speech recognisers. I would suggest you to go through the tutorial: http://kaldi-asr.org/doc/tutorial.html

Concerning your second question:
I am not an expert on accent adaptation but there are some pretty good papers on the subject both for traditional GMM and DNN based systems

**Comment by jtrmal** [comment]
As Angel mentioned, this is not the place to discuss these issues.
