### ISSUE TITLE
error C2011: 'timespec': 'struct' type redefinition, in Visual Studio 2015

### ISSUE THREAD

**Issue by ceefour** [kaldi-asr/kaldi#595]
Environment: Visual Studio Community 2015 Update 1
- on Windows 10 Pro 64-bit, Intel MKL.

```
error C2011: 'timespec': 'struct' type redefinition
```

e.g. 

```
1>C:\RVKaldiDevelopment\kaldi\tools\pthreads\Pre-built.2\include\pthread.h(320): error C2011: 'timespec': 'struct' type redefinition
1>  C:\Program Files (x86)\Windows Kits\10\Include\10.0.10240.0\ucrt\time.h(39): note: see declaration of 'timespec'
```

Workaround:
Adding `HAVE_STRUCT_TIMESPEC` to `kaldiwin.props` made the projects build.

Original thread: https://groups.google.com/d/msg/kaldi-help/GSOr3AWnuWM/Ri4WcElkBgAJ

**Comment by kkm000** [comment]
I had to add `HAVE_STRUCT_TIMESPEC` to compile with VS2015 or Intel XE 2016 as well. I think this is a VS2015 change not really related to MKL. Many packages have a `config.h` but we do not IIRC and set the `HAVE_*` in kaldi.mk, and there is no similar place for VS. Do not know what would be the least ugly fix be (short of `#if !HAVE_STRUCT_TIMESPEC || (defined(_MSC_VER) && _MSC_VER < 1900)` but that's offensive to good taste :)  ).

**Comment by jtrmal** [comment]
I forgot about this. It compiled well for me anyways -- but I could had already done the define and forgot about it. I will leave it opened until I verify or fix the issue.

**Comment by jtrmal** [comment]
I'm closing this, as under 2017 this problem does not exhibit itself either. So either it was fixed or it was some mess-up.

**Comment by SirMarbles** [comment]
> I'm closing this, as under 2017 this problem does not exhibit itself either. So either it was fixed or it was some mess-up.

this still happens
