### ISSUE TITLE
The queue in lat/word-align-lattice.cc is actually a stack

### ISSUE THREAD

**Issue by kkm000** [kaldi-asr/kaldi#603]
I cannot claim any understanding of code in lat/word-align-lattice.cc, but something stands out as strange: the vector `queue_`, a container of computations in progress, is used as a LIFO, a stack, with `push_back()` and `pop_back()`. It seems that it is either used incorrectly or misnamed. From the logic of the code how I understand it, I am afraid the former might rather be true--but then I cannot understand how it works really.

**Comment by danpovey** [comment]
It's one of those situations where you can use any queue discipline (LIFO,
FIFO, etc.) and it would still be correct, but a it happens we choose LIFO.


Dan

**Comment by kkm000** [comment]
Including even an unordered bag? I'm just trying to grok the code.

**Comment by danpovey** [comment]
I got the concept from OpenFst code, but I think it stems from a
computer-science notion of queue.
E.g. see here
https://en.wikipedia.org/wiki/Queueing_theory
the section on 'Service disciplines'.
Dan


On Sun, Mar 20, 2016 at 1:21 AM, Kirill Katsnelson <notifications@github.com

**Comment by kkm000** [comment]
I think I got it, thank you Dan. This queue can actually be processed in any order, and the strategy only affects the order of graph traversal, so LIFO makes it depth-first, and FIFO breadth-first. Can be a random bogobag as well.

So I am closing this ticket. No issue here.
