### ISSUE TITLE
valid_uttlist creation in chain/get_egs.sh does not check for length of utterances

### ISSUE THREAD

**Issue by vijayaditya** [kaldi-asr/kaldi#605]
The valid_uttlist when being created does not check for the length of the utterances. However the functions in nnet3-chain-get-egs binary return false if feature length is not less than frames_per_eg. This is a problem when several short utterances are sampled. The error raised is not informative as the code does not print any warning message when it reaches this branch.

<pre><code>
99        if (num_feature_frames_subsampled < frames_per_eg_subsampled)
100         return false;
</code></pre>

I will select valid utts from the pool of eligible utterances. I add a warning message even for the above case.

**Comment by danpovey** [comment]
sounds reasonable.

**Comment by vijayaditya** [comment]
Addresssed in #607

**Comment by vijayaditya** [comment]
Solution in #607 does not work for data directories which are generated by steps/cleanup/combine_short_segments.sh, as it does not create segments file. As combine_short_segments.sh is usually done to eliminate the problem of short segments, this check is redundant. 

I think feat-to-len can be used in case get_uttdur.sh fails.

**Comment by vijayaditya** [comment]
I think the best way to tackle this problem is to ensure that the steps/cleanup/combine_short_segments.sh creates an utt2dur file. @tomkocse could you please take care of this. When creating the new utterances, you would have to create a corresponding utt2dur file.

**Comment by danpovey** [comment]
Vijay- it does work; get_utt2dur.sh works in all cases, it backs off to the
wav files or the features if there is no segments file.
Dan

**Comment by vijayaditya** [comment]
Sorry I should have mentioned that steps/cleanup/combine_short_segments.sh does not even have wav.scp. Even if it does the durations would be computated at recording level and not utterance level, when there is a fall back.

**Comment by danpovey** [comment]
OK, you're right; yes, create_short_segments.sh should create an utt2dur
file

**Comment by vijayaditya** [comment]
We have to modify the utils/data/get_utt2dur.sh to exit if utt2dur already exists, this will ensure that the outputs of combine*.sh script can be used with existing chain/get_egs.sh script.

**Comment by danpovey** [comment]
Agreed- that's what the comment in the script says it does, but it doesn't
do that.

**Comment by vijayaditya** [comment]
see #609 .
