### ISSUE TITLE
Issues with combine_short_segments.sh output

### ISSUE THREAD

**Issue by vijayaditya** [kaldi-asr/kaldi#615]
The combine_short_segments.sh script does not process the utt2uniq file.

Using fix_data_dir.sh on the top of combine_data_segments.sh eliminates all the segments.

**Comment by vijayaditya** [comment]
There is another issue with the current algorithm used for combining segments. There is an initial search in forward direction and then a search in backward direction, around the segment. As the search is not global I am ending up with utterances which are 15 secs long though I just need 1.5 sec long utterances. 

I am rewriting this method to do a simultaneous search in both directions and come up with a segment combination which has length closest to the required length.

**Comment by danpovey** [comment]
Hm.  It seems to me like it's not that hard a problem- we don't need a
solution that's optimum in any way.  But fix it.
Dan

**Comment by vimalmanohar** [comment]
After the combining of short segments, utt2uniq may not be defined as different utterances might be combined for different speed perturbations. So utt2uniq will just be the utt-id on both columns?

**Comment by vijayaditya** [comment]
But if we do that the cross-validation accuracies are going to be really
high, which is the current case.

**Comment by danpovey** [comment]
You could just have utt2uniq map to the utt2uniq of the first of the
combined  utterances - won't be exact but better than nothing.
Another approach would be to combine short segments prior to speed
perturbing (might have to use a slightly smaller cutoff in that case).
Dan

**Comment by vijayaditya** [comment]
Addressed in #618 

We cannot do speed perturbation after combine_short_segments.sh as it does not combine the actual wave segments it just combines the feats. So there would be no wave.scp or segments file in the output directory.

I addressed the problem as follows:
<pre><code>
            combined_uniqs = []
            for utt in combined_utt_list:
                combined_uniqs.append(utt2uniq.pop(utt))
            # utt2uniq file is used to map perturbed data to original unperturbed
            # versions so that the training cross validation sets can avoid overlap
            # of data however if perturbation changes the length of the utterance
            # (e.g. speed perturbation) the utterance combinations in each
            # perturbation of the original recording can be very different. So there
            # is no good way to find the utt2uniq mappinng so that we can avoid
            # overlap.
            utt2uniq[new_utt_name] = combined_uniqs[0]
</code></pre> (from [here](https://github.com/vijayaditya/kaldi/blob/temp3/egs/wsj/s5/steps/cleanup/combine_short_segments.py#L219))
