### ISSUE TITLE
Small fluctuation in lattice acoustic weights between multiple decodes of same wave bits

### ISSUE THREAD

**Issue by kkm000** [kaldi-asr/kaldi#617]
When I run a wave file through nnet2 online decoder multiple times, I am getting subtly different final acoustic weights, e. .g  on 3 decodes it was -1615.492, -1616.649, -1618.301. The sequence of weights is reproduced every time the program restarts, so it looks like some state is carried over between decodes. Am I doing something wrong, or is this expected, or indicative of a problem somewhere? Here's what my code is doing:

Once at the beginning, loading or initializing: the HCLG graph. TransitionModel;  ContextDependency
nnet2::AmNnet, OnlineNnet2FeaturePipelineInfo. Indeed, the latter incorporates the state of the i-vector extractor. I made sure I access these reused objects only through const (pointers or references).

Then, multiple times:
- Create OnlineNnet2FeaturePipeline
- Copy initial adaptation state into it from ivector_extractor_info (and I never read it back -- loop is open!)
- Create new LatticeFasterOnlineDecoder and initialize decoding
- Push frames into the pipeline, AdvanceDecoding on each
- FinalizeDecoding, GetRawLattice, DeterminizeLatticePhonePruned.
- Delete the decoder and the pipeline, rinse, repeat.

Does this look sane? The fluctuation is small, on the order of units, but I do not like sudden unexplained variability. Is this something I may dismiss, or should rather try diagnosing further?

Built on Windows, with MKL and without CUDA.

**Comment by danpovey** [comment]
It's expected-- there is dithering prior to the FFT to avoid zero fourier
components.
Dan


On Thu, Mar 24, 2016 at 9:34 PM, Kirill Katsnelson <notifications@github.com

**Comment by kkm000** [comment]
I see. Do you think there is an easy way to check if this is *the only* source of randomness?

**Comment by danpovey** [comment]
There is a dither value in the MFCC config that you could set to 0 (set
--dither 0 --energy-floor 1); or you could call srand(0) before processing
each utterance.


On Fri, Mar 25, 2016 at 1:25 AM, Kirill Katsnelson <notifications@github.com

**Comment by kkm000** [comment]
Ok, will do tomorrow to make sure this is the only affecting parameter, thanks!
