### ISSUE TITLE
nnet3- add binary nnet3-show-progress

### ISSUE THREAD

**Issue by danpovey** [kaldi-asr/kaldi#62]
This is for anyone who has the time.
Look at how nnet3-average differs from nnet-am-average to see how you should modify nnet-show-progress to make nnet3-show-progress.  It may be necessary to add functions to nnet-utils.h.
The program should read the "raw" nnet format.

**Comment by naxingyu** [comment]
It requires a ComputeNnetGradient counterpart and I imagine it wouldn't be a nnet-util. I see two option. 1) Update nnet-diagnostics, add a ComputeGradient function, and 2) Add a ComputeGradient function in nnet-compute.h, and the implementation can be copied from nnet-derivative-test.cc. Which one is more of nnet3 spirit? What's your suggestion?

**Comment by danpovey** [comment]
I think what you need already exists in class NnetComputeProb: see the
GetDeriv() function.
Dan
