### ISSUE TITLE
analyze-counts

### ISSUE THREAD

**Issue by danpovey** [kaldi-asr/kaldi#621]
Someone needs to do a thorough style check on analyze-counts.cc, there are problems on almost every line.
Some issues that you might not notice:
  - it does not check for negative inputs on the alignments, which if it happened would cause memory corruption.
  - there is a place where a vector is resized, where kCopyData would avoid a few lines of code.

**Comment by danpovey** [comment]
... and the comments need to be in a more normal style and in proper sentences.

**Comment by danpovey** [comment]
@jtrmal, newbies would be hard-pressed to do this as they don't know the style.
@tomkocse, do you have time?

**Comment by tomkocse** [comment]
@danpovey , i would love to do this, but i will be on a trip from 28/3 to 1/4 . Is this urgent ?

**Comment by danpovey** [comment]
Not urgent at all, it can wait.
