### ISSUE TITLE
feature wrong,please help

### ISSUE THREAD

**Issue by liumengzhu** [kaldi-asr/kaldi#628]
extract-segments scp,p:data/train/wav.scp exp/make_fbank/train/segments.1 ark:- 
sh: /data/home/neu_3/LDC2005S15/audio/train/A2_0.wav: cannot execute binary file: Exec format error
copy-feats --compress=true ark:- ark,scp:/data/home/neu_3/eesen-master/asr_egs/hkust/v1/fbank/raw_fbank_train.1.ark,/data/home/neu_3/eesen-master/asr_egs/hkust/v1/fbank/raw_fbank_train.1.scp 
ERROR (extract-segments:Read4ByteTag():wave-reader.cc:74) WaveData: expected 4-byte chunk-name, got read errror
WARNING (extract-segments:Read():feat/wave-reader.h:149) Exception caught in WaveHolder object (reading).
WARNING (extract-segments:HasKeyInternal():util/kaldi-table-inl.h:1370) RandomAccessTableReader: error reading object from stream '/data/home/neu_3/LDC2005S15/audio/train/A2_0.wav |'
WARNING (extract-segments:main():extract-segments.cc:125) Could not find recording A2_0-A2_0, skipping segment A2_0-A2_0-000010-000100
LOG (extract-segments:main():extract-segments.cc:193) Successfully processed 0 lines out of 1 in the segments file. 
WARNING (extract-segments:Close():kaldi-io.cc:446) Pipe /data/home/neu_3/LDC2005S15/audio/train/A2_0.wav | had nonzero return status 32256
compute-fbank-feats --verbose=2 --config=conf/fbank.conf ark:- ark:- 
LOG (compute-fbank-feats:main():compute-fbank-feats.cc:178)  Done 0 out of 0 utterances.
LOG (copy-feats:main():copy-feats.cc:100) Copied 0 feature matrices.
# Accounting: time=0 threads=1
# Ended (code 1) at Tue Mar 29 10:59:04 CST 2016, elapsed time 0 seconds

**Comment by danpovey** [comment]
Looks like there is an error in your file data/train/wav.scp: it has the
pipe symbol at the end of the line and it shouldn't be there.
Dan
