### ISSUE TITLE
MERCHANTABLITY [sic]

### ISSUE THREAD

**Issue by kkm000** [kaldi-asr/kaldi#648]
6 source files have MERCHANTABILITY in their license statement, and 1237 MERCHANTABLITY. Despite the overwhelming majority, I'd rather go with the former.

**Comment by kkm000** [comment]
I can run a single command to fix, but I think I should do a mass fix after interspeech and when the chain branch is merged. Provided that needs fixin'. A google search reveals hundreds of files (not related to Kaldi) with the same exact license with the typo..

**Comment by danpovey** [comment]
Makes sense.

**Comment by danpovey** [comment]
I think I'd rather leave this mistake there... fixing it would make the history of files harder to understand, and I don't think anyone is very likely to notice the typo.
