### ISSUE TITLE
Building kaldi with CUDA 7.0

### ISSUE THREAD

**Issue by Saurabhbhati** [kaldi-asr/kaldi#67]
Makefile in src/cudamatrix/ doesn't check for CUDA 7.0. It shows an error while building as the compute capabilities of CUDA 7.0 and previous versions are different.
I changed the makefile to check for CUDA 7.0. I got no errors while building. Is it the right way to add CUDA 7.0? Could you please add support for CUDA 7.0?

**Comment by jtrmal** [comment]
I can assure you I have no problems building kaldi with cuda 7.0.
The problems you mention might be something specific to your setup.  You
will,  however,  have to be more careful in describing what you did,  what
was the error  and so on.  Otherwise we cannot help you.

**Comment by danpovey** [comment]
You are possibly using a very outdated version of Kaldi.  Note that Kaldi
is now located on github (however, the latest Sourceforge version should
not have behaved like this either).
Dan

**Comment by Saurabhbhati** [comment]
Thank you for the reply. I'll try with the latest version. 

This makefile doesn't check for CUDA 7.0 and line 51 will make sure that compute_13, sm_13 and compute_10, sm_10 are being appended to CUDA_ARCH. According to CUDA 7.0 documentation ARCH option in CUDA 7.0 doesn't accept compute_13,sm_13 or compute_10,sm_10. I was getting an error because of this so I modified Makefile a bit.

https://github.com/kaldi-asr/kaldi/blob/master/src/cudamatrix/Makefile
http://docs.nvidia.com/cuda/cuda-compiler-driver-nvcc/index.html#supported-host-compilers

**Comment by danpovey** [comment]
For toolkit 6.0 or newer, that Makefile adds compute_50:

  #For toolkit 6.0 or newer, add the compute capability 5.0


  CUDA_VER_GT_6_0 := $(shell [ $(CUDA_VERSION) -ge 60 ] && echo true)
  ifeq ($(CUDA_VER_GT_6_0), true)
    CUDA_ARCH += -gencode arch=compute_50,code=sm_50
  endif

If you follow up, please specify what flags were generated by the Makefile,
which Kaldi version you are using, and what the output of nvcc -V was for
you.

Dan
