### ISSUE TITLE
local/score.sh: invalid option --iter

### ISSUE THREAD

**Issue by realill** [kaldi-asr/kaldi#672]
I get this, running nnet3 decoding with --iter param
 
steps/nnet3/decode.sh --acwt 1.0 --post-decode-acwt 10.0 --cmd queue.pl --iter 200 --nj 16 exp/chain/tdnn_2o_4/graph/ data/test_hires/ exp/chain/tdnn_2o_4/decode-200/
steps/nnet3/decode.sh: feature type is raw
score best paths
local/score.sh: invalid option --iter

Should be easy to fix.

**Comment by danpovey** [comment]
The scoring scripts are in local/, so they have to be fixed locally.

**Comment by realill** [comment]
Yeah, wsj version does not have this problem. Closing.
