### ISSUE TITLE
utils/mkgraph.sh, read context from the tree?

### ISSUE THREAD

**Issue by francisr** [kaldi-asr/kaldi#676]
In utils/mkgraph.sh we have to specify what context we are going to use to build the graph (with --mono, --quinphone, otherwise triphone by default). If the option selected doesn't correspond to the tree it complains, so for me there is no point in asking the user to specify this when we know this information from the tree.

**Comment by danpovey** [comment]
Yes, this information could be extracted from `tree-info`, and a warning
could be printed if any user-specified flags (present for back
compatibility) differ from the info from the tree.
Do you want to submit a pull request?  Or make an issue?
Dan

**Comment by francisr** [comment]
I can make a pull request on Monday if nobody does it by then.

**Comment by kkm000** [comment]
Fixed in  ef48b26, #683.
