### ISSUE TITLE
onlinebin no longer compiled ?

### ISSUE THREAD

**Issue by Waxo** [kaldi-asr/kaldi#68]
Hi,

I know that online's methods are outdated and online2 replace it.
I just wanted to know if onlinebin is no longer compilated volontary (or not).

Thanks

**Comment by vdp** [comment]
You should be able to compile the 'old' online code by executing 'make ext' in src/.
Also, I would suggest to use the [help mailing list](http://www.kaldi-asr.org/forums.html), instead of abusing the GH issues, that are meant for reporting problems.
