### ISSUE TITLE
Sorting of G.fst in babel recipes

### ISSUE THREAD

**Issue by kkm000** [kaldi-asr/kaldi#680]
https://github.com/kaldi-asr/kaldi/blob/master/egs/babel/s5b/local/arpa2G_syllables.sh#L47 does not arcsort the G.fst (but the respective scripts in both babel/s5 and babel/s5c do).

https://github.com/kaldi-asr/kaldi/blob/master/egs/babel/s5b/local/arpa2G.sh#L108 olabel-sorts the G.fst (as does one in s5c).

Is this not on purpose? Is sorting irrelevant in this recipe?

**Comment by danpovey** [comment]
That set of scripts was written a while ago.
I think the arc-sorting may just be an efficiency issue.  Certainly there's
never a reason not to sort them; and sorting them is always recommended.
Dan


On Sun, Apr 10, 2016 at 3:37 PM, Kirill Katsnelson <notifications@github.com

**Comment by kkm000** [comment]
I remember _something_ complained, I think it might have been `fst::Compose()`, but maybe it was  our language directory validation script. New scripts certainly require both L and G be sorted on the composing side.

**Comment by danpovey** [comment]
Yes, I think you are right, they do, and they didn't always.

On Sun, Apr 10, 2016 at 6:08 PM, Kirill Katsnelson <notifications@github.com

**Comment by kkm000** [comment]
I remember now, that was `TableCompose()`. First [a warning](https://github.com/kaldi-asr/kaldi/blob/master/src/fstbin/fsttablecompose.cc#L128 and then [an assertion failure](https://github.com/kaldi-asr/kaldi/blob/master/src/fstext/table-matcher.h#L78)

**Comment by jtrmal** [comment]
I remember running some benchmark and IIRC I was talking with Dan about removing it, because during L*G composition, the G is getting ilabel sorted before running compose?
But I might not remember it correctly. Might be just an overlooking on my side -- I don't remember if I was actually planning to commit it and if the change was because of the benchmark. The speed difference was just minor.
y.

**Comment by kkm000** [comment]
@jtrmal: G is not sorted in `wsj/s5/utils/mkgraph.sh` before fsttablecompose, and it would bomb out if the machines were not sorted (unlike fstcompose that does not strictly require ordering, IIRC). There are many fsttablecompose calls in local scripts though, I do not know about these. It makes the most sense to sort it once when saving, since this is the only arc order requirement ever imposed on G, so I do not think it should ever be sorted before use.

**Comment by jtrmal** [comment]
I agree with you. It's better when it's sorted.
y.

On Wed, Apr 13, 2016 at 6:30 PM, Kirill Katsnelson <notifications@github.com
