### ISSUE TITLE
lattice-copy bugs

### ISSUE THREAD

**Issue by danpovey** [kaldi-asr/kaldi#687]
I saw the message
LOG (lattice-copy:CopySubsetLattices():lattice-copy.cc:104) The utterance 20000907_0930_1030_rfi_fm_dga-0093333-0093857 is larger than the last key in the include list. Not reading further.
from the command:
gunzip -c decode_nosp_dev_tgpr/lat.2.gz| lattice-copy --include=foo ark:- ark:- 
This is not right in general, as unless the ",s" option is included in the rspecifier, we cannot assume the lattices are sorted [they are typically sorted in practice, per archive, but the framework is supposed to be general].

Also I see the code includes the line
  if (include && lattice_reader->Key() > *(subset_list.rbegin())) {
with no check for whether subset_list is empty.. this could segfault.
Making an issue rather than fixing it myself, so someone else can help.

**Comment by danpovey** [comment]
@LvHang, this is another relatively straightforward issue that you could help with.
The easiest way to fix this is to simplify th

**Comment by LvHang** [comment]
@danpovey 
get it
Hang
