### ISSUE TITLE
CMVN in KALDI

### ISSUE THREAD

**Issue by cometome** [kaldi-asr/kaldi#689]
In my experiment, i am using cmvn feature for speech recognition. All the recipe had implemented the cmvn in an sequential steps. There is no problem of following the method.

But, in my experiment, when i am implementing cmvn on static features externally using kaldi scripts and then providing it for recognition, it creating problem. I have also re-calculated the cmvn stats on compensated feature but not getting result as earlier.  

it is like,

Normal:
within script,
wav file ------> feature---> cmvn ----> decoding ::::: Getting expected result

experiment:
wav file -----> feature ----->cmvn -----> modify the cmvn stats
next,
within script,
feature------> decoding.

Can you provide any suggestion?

Thanks
Biswajit

**Comment by danpovey** [comment]
I don't really understand your question.  Anyway this is not the right place to ask- see kaldi-asr.org/forums.html.
You need to be much more specific.

Dan
