### ISSUE TITLE
bn_music_speech Example

### ISSUE THREAD

**Issue by thomaspreece** [kaldi-asr/kaldi#690]
I'm having trouble with the bn_music_speech example code. I've obtained the musan dataset and the LDC98S71, LDC98T28 (1997 English Broadcast News) datasets as instructed on the example README (and in the code) but the LDC datasets are refusing to process correctly using the make_bn.sh script. 
Comparing what the make_annotations_bn.py is looking for and the transcripts I have seems to show that the transcript format is different to what is expected. 
As an example an LDC98T28 transcript includes the following:
```
<section type=filler startTime=5.042 endTime=91.863>
```
which is different to the S_Time, E_Time and Type that the script is looking for.
Am I using the correct datasets?

**Comment by danpovey** [comment]
Hm.
On our grid the data looks like what you say:

 /export/corpora/LDC/LDC98T28/hub4e97_trans_980217/transcrp/ew970708.sgml

...<turn speaker=Gary_Blonston spkrtype=male startTime=112.755
endTime=122.769>

<time sec=112.755>

 I think it'll be fascinating. {lipsmack} {breath} %um

<time sec=115.984>

 ^D'Amato is at once a vulnerable candidate and

Please be more specific about how it's "refusing to process correctly",
i.e. what are the error messages or unexpected outputs?
Dan

**Comment by david-ryan-snyder** [comment]
Thomas,

This is 100% my fault. The README contains the wrong LDC number. It should really be LDC97S66 and LDC97T22, which corresponds to the 1996 Broadcast News. I'm fixing the incorrect comments in the examples now. I'm sorry that you had to acquire the wrong corpus to detect this mistake.

**Comment by danpovey** [comment]
If you did actually pay for the wrong corpus, the LDC people are pretty
flexible on pricing and they may be willing to deduct the cost of any
mistakenly acquired corpus.
Dan

**Comment by david-ryan-snyder** [comment]
I believe the correct speech corpus is LDC97S44, but it will be better to wait a bit until I can be completely certain. I'll update here ASAP.

**Comment by david-ryan-snyder** [comment]
I can confirm that LDC97S44 and LDC97T22 are the correct datasets.

**Comment by kkm000** [comment]
Fixed in eb5b32cf78648392caa339eb266cbd6ae3b41d02
