### ISSUE TITLE
PortAudio failed to open the default stream in online-demo

### ISSUE THREAD

**Issue by MatteoBotta** [kaldi-asr/kaldi#691]
Hello,
I have a problem with online-demo example. 
If I execute the script run.sh in simulated mode Kaldi works correctly, but if I execute run.sh in live mode the system shows this error:
"PortAudio failed to open the default stream"

I installed portaudio with the script "install_portaudio.sh" in Kaldi suite.

if I work with gstreaming it transcribes in real time without error.

What am I doing wrong?

Thx In Advance

MB

**Comment by danpovey** [comment]
Likely it's a PortAudio installation problem.  I am not continuing to
support that code as it's distraction from the core speech recognition
aspects of Kaldi.  From now, online decoding (in online2*) is being
supplied as a C++ library without network-transport or audio-capture
elements.


Dan
