### ISSUE TITLE
Enhancements to wav-reverberate command

### ISSUE THREAD

**Issue by vijayaditya** [kaldi-asr/kaldi#716]
We are updating the wav-reverberate command to support a new data reverberation script (See PR #706 ). For this script we need to update the C++ binary to have the following command line format. (This issue is based on requirements in #552) 

<pre><code>
wav-reverberate --inpulse-response=&ltrir-wav&gt \
--additive-signals='&ltisotropic-noise-wav&gt, "wav-reverberate --duration &ltt&gt --impulse-response=&ltpoint-source1-rir-wav&gt &ltpoint-source1-noise-wav&gt - |", "wav-reverberate --duration  &ltt2&gt --impulse-response=&ltpoint-source2-rir-wav&gt &ltpoint-source2-noise-wav&gt - |"' \
  --snrs=' &ltisotropic-snr-db&gt ,&ltpoint-source1-snr-db&gt,&ltpoint-source2-snr-db&gt' \
  --start-times='&lt s0,s1,s2 &gt' '  &ltinput&gt  &ltoutput&gt

</code></pre>

**Comment by danpovey** [comment]
I think the following is better / easier to deal with internally:

--additive-signals='<isotropic-noise-wav>,wav-reverberate --duration
<t> --impulse-response=<point-source1-rir-wav>
<point-source1-noise-wav> - |,wav-reverberate --duration  <t2>
--impulse-response=<point-source2-rir-wav> <point-source2-noise-wav> -
|'

**Comment by vijayaditya** [comment]
FYI @tomkocse has picked this issue.
