### ISSUE TITLE
Instructions for designing new recipes

### ISSUE THREAD

**Issue by vijayaditya** [kaldi-asr/kaldi#718]
In cases where new a recipe is being written, it would be convenient to have guidelines :  
1. To figure out the priority list of hyper-parameters to tune: It is preferable to have a list of hyper-parameters and if possible suggested values for various data sizes at various stages in the recipe.
2. For new databases without segments file it would be preferable to have a boot strap model (available on openslr.org) + example scripts to perform the initial segmentation. If possible it would be good to have scripts used for preparing the Librispeech recipe.
3. If the corpus designer is also able to collect data it is preferable to have suggested minimum data sizes.

**Comment by danpovey** [comment]
I agree that we should single out commonly-tuned hyperparameters.  One
possibility is to add variables for them (and just them) in the run*.sh
scripts.
For long unsegmented data with a bootstrapping problem, it might be easier
to release the segments file than the entire model (less issues with
version compatibility, etc.).
I don't think there can ever be hard limits RE data sizes.  And trying to
help the kinds of people who lack the common knowledge of ASR people will
be hard, as they won't understand many concepts referred to in our scripts
etc.

Dan

**Comment by danpovey** [comment]
RE: "If possible it would be good to have scripts used for preparing the
Librispeech recipe".
I don't think Vassil plans to release them as open source.  However, I have
a general plan to have someone work on this problem in the next few months
and create something that we can use in this type of scenario.  Probably
we'd do some kind of phone-level alignment based on a phone recognition to
get an initial candidate segmentation, and then apply Vimal's cleanup
scripts, that he is working on, to get rid of bad segments.  This means
that we can re-use Vimal's data-cleanup work and will need minimal extra
work to handle the long-audio-segmentation problem.

Dan
