### ISSUE TITLE
Tool to generate word-level soft counts from lattices

### ISSUE THREAD

**Issue by vijayaditya** [kaldi-asr/kaldi#719]
Sanjeev has a new requirement : 
He would like a tool which processes lattices to figure out the soft counts for different words. The output of this tool would be used for generating things like word clouds by higher level scripts.

**Comment by danpovey** [comment]
Lattice-arc-post will do this.
We even have a way to get soft n-gram counts.  You have to do
lattice-expand-ngram, and then... then I forget the next stage.  David, did
we check this in?  Just curious.
Dan

**Comment by david-ryan-snyder** [comment]
It looks like we never checked in the second binary. 

I can probably dig it up, and send a pull request for it.

**Comment by danpovey** [comment]
Not urgent at all.  I'm not even sure if I want to check it in right, now,
but we shouldn't lose track of it completely.




On Tue, Apr 19, 2016 at 7:14 PM, david-ryan-snyder <notifications@github.com

**Comment by david-ryan-snyder** [comment]
No problem.

If this is needed at some point, the relevant code can still be found on SVN. The binary at https://svn.code.sf.net/p/kaldi/code/sandbox/language_id/src/latbin/lattice-to-ngram-counts.cc and the function ComputeSoftNgramCounts at https://svn.code.sf.net/p/kaldi/code/sandbox/language_id/src/lat/lattice-functions.cc.

**Comment by danpovey** [comment]
Closing issue as lattice-arc-post exists now.
