### ISSUE TITLE
Conversion of recipes written for evaluations to build production systems

### ISSUE THREAD

**Issue by vijayaditya** [kaldi-asr/kaldi#724]
Usually recipes built for winning evaluations have large number of parameters to ensure we have the best system. However people using models from these recipes to build production systems do not care about the 1-2% WER gains and would rather have a fast system. So if possible it would be good to add notes in the RESULTS file specifying the performance loss when parameters have been reduced. I don't know if we would want to explicitly run experiments to satisfy this requirement, but it would be good to report the numbers when available.

In nnet2/nnet3 we have always ensured that the recipes can be used for building production systems. However this was definitely not enforced. 

[This part of a wish list from our corporate users]

**Comment by sikoried** [comment]
I think this makes sense for a few recipes, but not for the challenges and recipes originating from large-scale projects:  Keep in mind though that the data sets for most evaluations are released under a non-commercial research-only license, explicitly prohibiting commercial use. While LDC often releases parts of the datasets months/years later and thus, depending on membership type, allow for commercial use, many of the data sets (Babel, RATS, Chime, Aspire, ...) are not available for commercial use.

I know that many people are either unaware of the licensing situation, or just don't care, but maybe including a note that points to this issue for research-only data sets makes sense.

**Comment by vijayaditya** [comment]
The actual decision of whether models can be used would be outside the purview of this issue. I think it would be good to always record performance of smaller sized models, when such information is available.

It might be good to add a note in the recipes about the expected usage, but I don't know who would have the necessary info to do that.

**Comment by jtrmal** [comment]
Perhaps the most straightforward way would be  to start providing decoding
time for each entry (or at least to some) in the results file.  Would not
include training time,  though.
Y.

**Comment by vijayaditya** [comment]
I am asking developers submitting PRs to add training time in the RESULTS
file in the newer PRs. I will start asking them to add the realtime factor
from the decode logs too.

**Comment by jtrmal** [comment]
Btw,  there is elementary infrastructure for this in kaldi already (I have
added it for babel).  Grepping for #Accounting line in the logs will give
you elapsed time in seconds for that given subtasks.
Y.
On Apr 20, 2016 9:13 PM, "Vijayaditya Peddinti" <notifications@github.com>
wrote:

I am asking developers submitting PRs to add training time in the RESULTS
file in the newer PRs. I will start asking them to add the realtime factor
from the decode logs too.


On Wed, Apr 20, 2016 at 9:09 PM, jtrmal <notifications@github.com> wrote:

> Perhaps the most straightforward way would be to start providing decoding
> time for each entry (or at least to some) in the results file. Would not
> include training time, though.
> Y.
> On Apr 20, 2016 9:01 PM, "Vijayaditya Peddinti" <notifications@github.com>
> wrote:
>
> > The actual decision of whether models can be used would be outside the
> > purview of this issue. I think it would be good to always record
> > performance of smaller sized models, when such information is available.
> >
> > It might be good to add a note in the recipes about the expected usage,
> > but I don't know who would have the necessary info to do that.
> >
> > —
> > You are receiving this because you are subscribed to this thread.
> > Reply to this email directly or view it on GitHub
> > <https://github.com/kaldi-asr/kaldi/issues/724#issuecomment-212676122>
>
> >
>
> —
> You are receiving this because you authored the thread.

> Reply to this email directly or view it on GitHub
> <https://github.com/kaldi-asr/kaldi/issues/724#issuecomment-212678411>
>

—
You are receiving this because you commented.

Reply to this email directly or view it on GitHub
<https://github.com/kaldi-asr/kaldi/issues/724#issuecomment-212679088>

**Comment by vijayaditya** [comment]
#766 is relevant to this discussion (This link is being provided for future reference).
