### ISSUE TITLE
update to validate_dict_dir.pl to check for ^M

### ISSUE THREAD

**Issue by danpovey** [kaldi-asr/kaldi#729]
We need to update validate_dict_dir.pl so that it detects when any user-supplied input files contain ^M characters, and fails if they do.  (make it user's responsibility to remove them).
Dan

**Comment by pranavj** [comment]
Does it need to give multiple warnings "File contains CRLF endings at line $_" or just one?

**Comment by danpovey** [comment]
Probably just one as it would tend to be repeated many times.  Make sure it
triggers it to (eventually) exit with error status.  But not super critical.

**Comment by danpovey** [comment]
resolved by #764
