### ISSUE TITLE
Does --exclude-silphones in egs/wsj/s5/steps/nnet/train_mpe.sh work as expected?

### ISSUE THREAD

**Issue by giuliopaci** [kaldi-asr/kaldi#736]
A colleague of mine gave to me an old recipe (~1.5 years) and I tried to run it.

At some point the recipe called ```egs/wsj/s5/steps/nnet/train_mpe.sh``` with the option ```--use-silphones true```. This command was failing reporting an invalid option.

So I had a look at the ```egs/wsj/s5/steps/nnet/train_mpe.sh``` log, trying to figure out what happened and I found this commit 3f89fab71ad3fe34411caff10c6166239b1593f6. From this commit I evince that ```--use-silphones true``` should be replaced by ```--exclude-silphones true```... And it seems to me like an error either in the new code or in the old one.

Unfortunately the log message is not very informative, so I am not able to understand what is the correct behaviour. Any ideas?

**Comment by danpovey** [comment]
cc'ing Karel since this is an nnet1 question.

**Comment by giuliopaci** [comment]
By looking at his emails, my colleague found a message from Karel where he said that he 

>  renamed '--use-silphones true' to '--exclude-silphones true', in fact it is excluding the silphone frames from the sMBR FW-BW.

so it seems the current behaviour is the correct one.

I am closing the issue.

**Comment by vesis84** [comment]
Yes, '--use-silphones' was renamed to '--exclude-silphones', because it was more self-explanatory. It causes the exclusion of silence-frames from contributing to the approximate accuracies in the sMBR Forward-Backward algorithm (silence frames become always correct)...
