### ISSUE TITLE
ReadBasicFileType will confound EOF with unsigned char length

### ISSUE THREAD

**Issue by sdrobert** [kaldi-asr/kaldi#739]
Hi there,

In `io-funcs-inl.h`, `WriteBasicFileType()` writes a length byte, but uses its sign to determine the signedness of the value. However, `ReadBasicFileType()` will error if it reads in -1, which could either mean an EOF (as per c++ ref) or an unsigned char.

Best,
Sean

**Comment by danpovey** [comment]
I expect that istream::get() returns either -1 for EOF, or an unsigned char cast to an int otherwise.  The C++ docs don't state this, but no other way would make sense.  So the Kaldi code would not be vulnerable to this problem.

**Comment by sdrobert** [comment]
Sorry, I don't quite understand. If the length byte is assumed to be unsigned, wouldn't that mean that the negative lengths, corresponding to unsigned integers (unsigned char, uint16, uint32, uint64 being -1, -2, -4, -8 resp) be interpreted as their unsigned two's complement? I apologise if I'm misunderstanding.

**Comment by danpovey** [comment]
you misread the code.

**Comment by danpovey** [comment]
it's cast to char after checking for -1.

**Comment by sdrobert** [comment]
Oh, I think I understand. The extra zeros are cropped when cast and the char basically overflows back to its correct value.

Thanks very much. That's a very strange aspect of streams I was unaware of.
