### ISSUE TITLE
--iter option to score script

### ISSUE THREAD

**Issue by danpovey** [kaldi-asr/kaldi#747]
Avoid giving the --iter option to the score scripts when it would have the default value ('final').
due to the following email on help list from vince62:
--
Hi,

At one point of time the run_nnet2_ms.sh script calls the steps/nnet2/decode.sh script

the latter, at stage 2 calls local/score.sh with option --iter $iter

in Tedlium (have not checked others) score.sh is linked to score_sclite.sh which does not take --iter as an option.

Am I wrong ?

thanks.

**Comment by jtrmal** [comment]
I see this already resolved in steps/nnet2/decode.sh in the latest master -- is there more scripts to be fixed or can this be closed?
