### ISSUE TITLE
Unfolded RNN implementation in nnet3

### ISSUE THREAD

**Issue by vijayaditya** [kaldi-asr/kaldi#751]
We would like to get an unfolded RNN ([1]) recipe implementation in nnet3. The effort involves
1. Writing a config generator similar to steps/nnet3/tdnn/make_configs.py
2. Writing a recipe similar to swbd/s5c/local/chain/run_tdnn_6z.sh

Requirements : Knowledge of python, bash
Learning: Author will gain experience in using nnet3 toolkit and writing a DNN recipe in Kaldi

[1] [Saon, George, et al. "Unfolded recurrent neural networks for speech recognition." INTERSPEECH. 2014](http://mazsola.iit.uni-miskolc.hu/~czap/letoltes/IS14/IS2014/PDF/AUTHOR/IS141054.PDF)

**Comment by galv** [comment]
You can prod me about this around May 20th if no one else wants to pick this up by then.

**Comment by vijayaditya** [comment]
being addressed in #848
