### ISSUE TITLE
utils/lang/check_g_properties.pl not right

### ISSUE THREAD

**Issue by danpovey** [kaldi-asr/kaldi#753]
These lines don't look right:
close(O);  # tell 'fstcompile | fstinfo' pipeline that its input is done.
while (<I>) {
  if (m/cyclic\s+/) {
    print "$0: validating $lang: error: G.fst has cycles containing only disambig symbols and epsilons.  Would cause determinization failure\n";
    exit(1);
  }
}

O seems to be the output and I the input of the open2 command, so it never gets into the while loop. It should be printing into I and read from <O>. 

The issue I have when I do this is that it triggers the error message, with a G.fst that went through the HCLG creation fine.
[from remi francis)

**Comment by francisr** [comment]
This has been fixed in #756.
