### ISSUE TITLE
WSJ script, change in path to transform-dir, [minor issue]

### ISSUE THREAD

**Issue by pranavj** [kaldi-asr/kaldi#761]
It seems to me that if one follows WSJ script,
  the location of transform-dirs in `egs/wsj/s5/local/run_mmi_tri4b.sh`
should be `exp/tri4b/decode_tgpr_dev93` instead of `exp/tri3b/decode_tgpr_dev93`

Similarly all other transform-dirs in this script should come from `tri4b` instead of `tri3b`, otherwise it gives an error that "expected */trans.1 file"

**Comment by danpovey** [comment]
I just pushed a fix for this.

**Comment by pranavj** [comment]
thanks. Line 35 needs to be changed too

**Comment by danpovey** [comment]
ok fixed
