### ISSUE TITLE
librispeech multisplice results

### ISSUE THREAD

**Issue by dxyzab** [kaldi-asr/kaldi#765]
From librispeech results

```online-nnet2 results with a model trained on all(960h) of the training data
Note: these results are now superseded by the multi-splice (_ms_) results below.
Be careful when comparing, as the _ms_ results don't yet have the _fglarge tests.```

If you have these results handy, could you please update 
https://github.com/kaldi-asr/kaldi/blob/master/egs/librispeech/s5/RESULTS

The results for the tg LM are missing for the test sets and if the fg results are available that would be great.

**Comment by danpovey** [comment]
@freewym, do you have these numbers?  Perhaps you could update the RESULTS
file with them?
Dan

**Comment by freewym** [comment]
I don't have these results since I didn't run local/online/run_nnet2_ms.sh. But I can run it.
Yiming

**Comment by vijayaditya** [comment]
@freewym Any progress ?

**Comment by freewym** [comment]
The experiment is still running.

On Wednesday, May 11, 2016, Vijayaditya Peddinti <notifications@github.com>
wrote:

> @freewym <https://github.com/freewym> Any progress ?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/kaldi-asr/kaldi/issues/765#issuecomment-218358584>
>


-- 
Sent from my iPhone
