### ISSUE TITLE
Left biphone chain models

### ISSUE THREAD

**Issue by vijayaditya** [kaldi-asr/kaldi#766]
In  the current chain recipes we use a tri-phone LM. We would like to test out left-biphone LM in its place. @keli78 has tested these LMs in RM recipe and found them helpful. We would like to test it out for larger setups e.g. swbd.

@naxingyu Are you interested in taking this up ?

For more info see [this mail thread](https://groups.google.com/forum/#!msg/kaldi-developers/aJNsm7guScQ/TGoHvnRNBwAJ)

**Comment by naxingyu** [comment]
Sure, I'll take it.

在 2016/5/8 3:45, Vijayaditya Peddinti 写道:

**Comment by naxingyu** [comment]
@keli78 Did you tested it on tdnns or blstms? How did you tune the variables, such as context, lm-states, tree-states, etc.? And would you ming point me to the location of your scripts in the clsp network so that I can check? Thanks.

**Comment by danpovey** [comment]
It was TDNNs, and nothing was changed except possibly the number of
tree-states slightly reduced.

**Comment by keli78** [comment]
The location is here: /export/a16/keli1/kaldi-chain/egs/rm/s5_left-biphone

**Comment by danpovey** [comment]
I think Xingyu doesn't have an account on the cluster, show him if there
were configuration changes.

**Comment by keli78** [comment]
Ok. The number of tree leaves is 900 instead of 1800. The relu-dim I used is 400. The ivector-dim is 50 considering rm is relatively small. I didn't change other parameters much.

**Comment by naxingyu** [comment]
Thanks!

在 2016/5/9 11:00, Ke Li 写道:

**Comment by naxingyu** [comment]
Maybe I can access it using clspfriends account?

在 2016/5/9 10:42, Daniel Povey 写道:
> I think Xingyu doesn't have an account on the cluster, show him if there
> were configuration changes.
>

**Comment by vijayaditya** [comment]
@naxingyu found that left-biphone models were as good as the triphone models on SWBD task. He will work on this further and create a recipe for swbd. This discussion can be followed in kaldi-developers mailing list ([here](https://groups.google.com/d/topic/kaldi-developers/NNx2xVoYctU/discussion))
