### ISSUE TITLE
Left-biphone recipe for Librispeech

### ISSUE THREAD

**Issue by vijayaditya** [kaldi-asr/kaldi#776]
This issue is related to #766. @naxingyu has developed a left biphone chain recipe for swbd (see #774 ). We need to test out this model even in Librispeech setting.

**Comment by vijayaditya** [comment]
@freewym Could you please add the latest cleanup code and left-biphone models to the librispeech recipe. You can see tedlium/s5_r2/run.sh for guidance in using cleanup stage.

**Comment by freewym** [comment]
OK

**Comment by vijayaditya** [comment]
Addressed in #991 .
