### ISSUE TITLE
Modify how the --per-utt option works in split_data.sh

### ISSUE THREAD

**Issue by danpovey** [kaldi-asr/kaldi#778]
There is a conceptual problem in how the --per-utt option is used when we split data.
It's that the split data goes to the same place regardless of whether we split it per utterance or per speaker, and there is caching, so if someone has used --per-utt in the past and then tries to use the per-speaker splitting, they'll get the wrong thing (and this can cause crashes in some scripts that assume the speakers are kept separate).

The fix is to name the subdirectory differently if --per-utt is used, e.g. to split${numsplit}utt instead of split${numsplit}.

This requires changes to split_data.sh, and also to all the scripts that call split_data.sh with the --per-utt option.  In those cases, it will typically be a change of the '$sdata' shell variable that is required, but also check for the string 'split$nj/' or in those scripts, in case we sometimes construct that directory-name bypassing the $sdata shell variable.

Dan

**Comment by francisr** [comment]
I have a slightly similar issue: when I train on a lot of data, I use a quite large number of splits for some steps (multiple thousands) to ensure that each job is not too long (less than an hour).
However it can take more than a day to split the data with --utt2spk, so I was thinking that I could split the data per utt before hand. With the proposed chan

**Comment by danpovey** [comment]
Try changing
$changed = 1
to
$changed = 0
and see if it makes the splitting faster in your case.

**Comment by danpovey** [comment]
I had look through the script, and I think I found why it's slow.  I made a data-structure change and committed it-- see if it makes it fast now.  If it doesn't make a difference, try the '$changed = 0' change.

**Comment by francisr** [comment]
It seems that my intuition was wrong, split_scp.pl was fine, it's filter_scps.pl that takes a lot of time.
It goes over the whole input file for each split, even with when I use a hundred splits it takes more than 30 minutes a single scp file.

**Comment by danpovey** [comment]
OK, the speed issue is fixed now.
(the original issue still remains).

**Comment by danpovey** [comment]
@vijayaditya, this issue keeps coming up.. it would be nice to have this fixed at some point.

**Comment by vijayaditya** [comment]
OK, I will keep track of this. I will try to assign this to someone or get
this done myself in 10 days.

--Vijay

**Comment by danpovey** [comment]
OK, resolved by commit 5efac249696233c56a6c18e48fabbb06d219460e
