### ISSUE TITLE
Test failures and Travis CI

### ISSUE THREAD

**Issue by kkm000** [kaldi-asr/kaldi#78]
When a test fails under CI, all I get is a failure message like (see [this Travis run](https://travis-ci.org/workflow-demo-org/kaldi/builds/76063707))

```
Running matrix-lib-test ...... FAIL matrix-lib-test
Running kaldi-gpsr-test ...... FAIL kaldi-gpsr-test

make[1]: *** [test] Error 1
make[1]: Leaving directory `/home/travis/build/workflow-demo-org/kaldi/src/matrix'
make: *** [matrix/test] Error 2

The command "cd tools && make openfst CC=gcc-4.9 CXX=g++-4.9 CFLAGS="-g -march=native" CXXFLAGS="-g -march=native" -j2 && cd ../src && ./configure --use-cuda=no  --mathlib=OPENBLAS --openblas-root=/usr && make     -j2 CC=g++-4.9 CXX=g++-4.9 EXTRA_CXXFLAGS="-I ~/xroot/usr/include -g -march=native" EXTRA_LDLIBS="-llapack -L ~/xroot/usr/lib -L /usr/lib/openblas-base" && make test    CC=g++-4.9 CXX=g++-4.9 EXTRA_CXXFLAGS="-I ~/xroot/usr/include -g -march=native" EXTRA_LDLIBS="-llapack -L ~/xroot/usr/lib -L /usr/lib/openblas-base"" exited with 2.
```

Travis does not easily support uploading logs. After the build/test script completes, the worker VM and all files are irreversibly gone. So we need a way to print an error log of a failed build to the same console, which is captured. I am thinking of this:

 1. Save test output to a known log file when test runs (e. g. `foo-bar-test.testlog`, matching the executable name
 2. When a test succeeds, delete the log.
 3. Print all available failure logs before exiting the test driver script.

(3) should certainly be limited to running under CI, as some of the logs are enormously large.

I also think maybe (1) and (2) should _not_ be gated by the same setting, so log output is available without rerunning a test when it fails locally.

What do you think?

**Comment by jtrmal** [comment]
it makes sense to me -- and it should be easily doable in the Makefile
(instead of redirecting the output to /dev/null, we can redirect it to the
given file).

y.

On Tue, Aug 18, 2015 at 5:01 AM, Kirill Katsnelson <notifications@github.com

**Comment by kkm000** [comment]
Ok, I'll do (1) and (2) always, so that log files of failed runs stay around. (3) will be done in a separate Travis `after_failure` event script.

**Comment by kkm000** [comment]
Done in #79  (except printing a backtrace from core dump does not work thanks to travis-ci/travis-ci#3754).

**Comment by naxingyu** [comment]
Does Travis CI run full builds all the time?

在 2015/8/18 17:01, Kirill Katsnelson 写道:

**Comment by kkm000** [comment]
@naxingyu: 
> Does Travis CI run full builds all the time?

Yes, when you open a PR against the main Kaldi repo's master branch, and then every time you update the PR. Another run is done on every push to the repo, including the merge of a PR. So we are all covered. :)

A run takes ~40 minutes to complete. I thought of speeding it up by caching OpenFST build, but it's a minor share (maybe 5 minutes or less), so I decided not to increase the complexity of the setup.

**Comment by naxingyu** [comment]
Is it possible to skip the build if only 'egs' is updated?

X.

**Comment by danpovey** [comment]
In that case we can just ignore the check.

**Comment by kkm000** [comment]
@naxingyu: but this is a good idea anyways. I'll see what can be done.
