### ISSUE TITLE
Copy-int-vector ark to ark,scp fails

### ISSUE THREAD

**Issue by AntreasAntoniou** [kaldi-asr/kaldi#785]
Dear Kaldi Authors,

I have run into an issue that seems to be giving me quite a lot of trouble so I thought I might ask you. I run the following:

`copy-vector ark,t:test_ark.ark ark,scp:kaldi.ivectors.ark,kaldi.ivectors.scp`

and I get:

ERROR (copy-vector:main():copy-vector.cc:67) Cannot mix archives with regular files (copying vectors)

ERROR (copy-vector:main():copy-vector.cc:67) Cannot mix archives with regular files (copying vectors)

[stack trace: ]
kaldi::KaldiGetStackTrace()
kaldi::KaldiErrorMessage::~KaldiErrorMessage()
copy-vector(main+0x1dd) [0x412b7d]
/lib64/libc.so.6(__libc_start_main+0xfd) [0x7fbb7fd6cd5d]
copy-vector(__gxx_personality_v0+0x1c1) [0x412829]

The ark,t file works when I run:
`copy-vector ark,t:test_ark.ark ark:kaldi.ivectors.ark``

I am trying to get the scp file. What is going on here?

**Comment by danpovey** [comment]
It looks to me like your problem is due to a bug which was fixed in 2013!!

**Comment by danpovey** [comment]
Wrong usage.  It depends on the context.
