### ISSUE TITLE
undefined reference to `FLAGS_v' when make src

### ISSUE THREAD

**Issue by jmloveyj** [kaldi-asr/kaldi#795]
make operation in /src failed: (ubuntu 14.04)
./fstext/kaldi-fstext.a(kaldi-fst-io.o): In function `fst::SymbolTable::SymbolTable(fst::SymbolTableImpl*)':
/media/psf/Home/Downloads/kaldi-trunk/tools/openfst/include/fst/symbol-table.h:409: undefined reference to `vtable for fst::SymbolTable'
../fstext/kaldi-fstext.a(kaldi-fst-io.o): In function `fst::FstImpl<fst::ArcTpl<fst::TropicalWeightTpl<float> > >::ReadHeader(std::istream&, fst::FstReadOptions const&, int, fst::FstHeader*)':
/media/psf/Home/Downloads/kaldi-trunk/tools/openfst/include/fst/fst.h:784: undefined reference to `fst::FstHeader::Read(std::istream&, std::string const&, bool)'
/media/psf/Home/Downloads/kaldi-trunk/tools/openfst/include/fst/fst.h:787: undefined reference to `FLAGS_v'
collect2: error: ld returned 1 exit status
make[1]: *** [align-equal] Error 1
make[1]: Leaving directory `/media/psf/Home/Downloads/kaldi-trunk/src/bin'
make: *** [bin] Error 2

**Comment by danpovey** [comment]
Is it possible that you have installed OpenFst in system space?  In that
case there could be some kind of version clash.

Do dpkg -l | grep openfst

Best to uninstall any system OpenFst, then redo 'make depend' and possibly
'make clean'.

Dan
