### ISSUE TITLE
Make combine_data.sh able to combine data with and without segments files.

### ISSUE THREAD

**Issue by danpovey** [kaldi-asr/kaldi#797]
... probably by adding segments with "0 -1" as timings.

**Comment by jfainberg** [comment]
Happy to do this unless somebody else is already working on it. Assuming utterance and recording IDs are the same for data directories that didn't have segments, so "uttid uttid 0 -1"? (So "awk '{ print $1" "$1" 0 -1" }' $f/utt2spk")

**Comment by danpovey** [comment]
Yes they are the same.
Dan

**Comment by danpovey** [comment]
I haven't looked at your PR yet, but I just realized that there is something else that needs to be done in order for these combined data dirs to later be usable by get_utt2dur.sh.  I don't want the -1's in the segments file because it will be hard to handle in get_utt2dur.sh, plus it could be potentially confusing for many scripts to have to deal with this. Instead, you should work out the durations by calling get_utt2dur.sh on the input directories that lack segments files, and use those to fill out "proper values" in the segments files.

I'm thinking of changing validate_data_dir.sh also, to disallow the -1's in the segments file.

**Comment by jfainberg** [comment]
That makes sense, thanks! I'll make my PR a WIP and have a go at using get_utt2dur.sh over the next few days.
