### ISSUE TITLE
what the LogProbs label means in HMM topology

### ISSUE THREAD

**Issue by hjchen2** [kaldi-asr/kaldi#798]
I tried to train a monophone GMM using train_mono.sh. In the model I found a label named LogProbs. 
Who can tell me the meaning of LogProbs in HMM topology? Any reply will be welcome, thx

**Comment by danpovey** [comment]
see kaldi-asr.org/forums.html.  But easier to grep in the code.

**Comment by hjchen2** [comment]
thanks very deeply. I have understood this method to define the transition probably. This is different from HTK in which transition probably is defined with HMM topology. Thanks again.
