### ISSUE TITLE
[documentation] Wit Zelinsky tutorial- add to docs

### ISSUE THREAD

**Issue by danpovey** [kaldi-asr/kaldi#802]
We should put the Wit Zelinsky tutorial in the docs somehow.

**Comment by danpovey** [comment]
More specifics on this: an updated version of Wit's tutorial is here
 https://groups.google.com/forum/#!msg/kaldi-help/tzyCwt7zgMQ/wvCLpVVpBgAJ
It is in Markdown.  The first thing we should try is whether we can just include it with a markdown filename extension, e.g.  src/doc/kaldi_for_dummies.md, and change MARKDOWN_SUPPORT = NO to YES in src/Doxyfile.  Something would have to be added to mainpage.dox to link to the page.  I vaguely recall that we set it to NO for a reason.  Please generate the HTML with both NO and YES and see how it differs.  Cd to src and do . doc/README to compile the documentation (if you're not me, transferring it to kaldi-asr.org will fail).

**Comment by akreal** [comment]
Hi! I tried to generate the HTML with `MARKDOWN_SUPPORT = YES` and noticed that multiplication sign (`*`) in some equations gets interpreted as italics mark.

**Comment by danpovey** [comment]
That must be why we disabled it.  I can't find a way to enable it only for
some files.  It might be necessary to format the tutorial as regular
doxygen.
