### ISSUE TITLE
something wrong when i build the kaldi

### ISSUE THREAD

**Issue by allesover** [kaldi-asr/kaldi#816]
my machine information：Linux gs01 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt25-1 (2016-03-06) x86_64 GNU/Linux . And my gpu is Tesla K80 (16 cores), cuda-7.5, nvidia-driver 364.19.

After I compiled the kaldi and run the training, there shows the error information:
     "run_multisplice.sh: line 12: cuda-compiled: command not found 
This script is intended to be used with GPUs but you have not compiled Kaldi with CUDA  
If you want to use GPUs (and have them), go to src/, and configure and make on a machine
where "nvcc" is installed.  Otherwise, call this script with --use-gpu false"

I'm sure the cuda toolkit is installed and the "nvcc" is available.

what's the most probable problem?

**Comment by danpovey** [comment]
There is no 'run_multisplice.sh' in the current version of Kaldi (see
kaldi-asr.org/doc/install.html).
Dan

**Comment by allesover** [comment]
sorry,the "run_multisplice.sh" is the script that i modified for tdnn 
training.

Also,there exists memory leakage when i train the tdnn using the cuda6.5 
and nvidia-driver 361.28.

And i wonder what version of cuda and nvidia-driver you use for kaldi:)


在 2016/5/29 2:13, Daniel Povey 写道:

**Comment by danpovey** [comment]
> sorry,the "run_multisplice.sh" is the script that i modified for tdnn

training.
>

It may be a path issue.  Perhaps you forgot to do
. ./path.sh

Also,there exists memory leakage when i train the tdnn using the cuda6.5
> and nvidia-driver 361.28.
>
> And i wonder what version of cuda and nvidia-driver you use for kaldi:)


We use 7.[something] here.  I think some versions of the 7.[something]
drivers have the bug too (probably depends on the hardware- we never had
the problem here).  But recent ones may be fixed.

Dan
