### ISSUE TITLE
Bug in DivRowsVec

### ISSUE THREAD

**Issue by danpovey** [kaldi-asr/kaldi#819]
@kangshiyin : @hhadian just noticed a problem in the code for DivRowsVec.  It looks like I may have changed the code that invokes it without noticing that the kernel had special requirements.

In https://github.com/kaldi-asr/kaldi/blob/master/src/cudamatrix/cu-kernels.cu#L474, there is an array of dimension 16 (it looks like the kernel assumes it's called on a 16x16 array), but we call it with arbitrary sizes.  The easiest fix may be to just always call it on a 16x16 block.  Please have a look.

**Comment by danpovey** [comment]
... and please make sure it's adequately tested.

**Comment by kangshiyin** [comment]
The shared memory seems not required.  I can make a PR on this later.
