### ISSUE TITLE
K80 is even slower than K20

### ISSUE THREAD

**Issue by allesover** [kaldi-asr/kaldi#824]
Hi Povey,
        I run the same training on the K20 and K80, the CUDA version and nvidia driver version are the same. But I found that the K80 is even slower than the K20 .each iteration for K20 is about 2mins using 5 K20 gpu cards and 5 jobs,but the same iteration for K80 is still 2mins using 15 K80 gpu cards and 15 jobs.
       I also did the experiment on one K80 card, the time for one iteration is even as long as ten or more minutes.
       On your point of view, what results in this strange phenomenon ? my configuration , hardware or the Debian sys ?

My sys info:
K80: Linux gs01 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt25-1 (2016-03-06) x86_64 GNU/Linux
K20: Linux b02 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt25-1 (2016-03-06) x86_64 GNU/Linux

both machines using CUDA-7.5 and Nvidia 364.19

key info of trainging scripts:

  parallel_opts="-l gpu=1" 
  num_threads=1
  minibatch_size=512
if [ ! -f $dir/final.mdl ]; then
  steps/nnet2/train_multisplice_accel2.sh --stage $train_stage \
  	--splice-indexes "layer0/-2:-1:0:1:2 layer1/-1:2 layer2/-3:4 layer3/-7:2 layer4/0" \
    --num-hidden-layers 5 \
    --cleanup false \
    --feat-type raw \
    --io-opts "-tc 5" \
    --cmvn-opts "--norm-means=false --norm-vars=false" \
    --num-threads "$num_threads" \
    --minibatch-size "$minibatch_size" \
    --parallel-opts "$parallel_opts" \
    --num-jobs-initial 5 --num-jobs-final 5 \
    --num-epochs 12 \
    --add-layers-period 1 \
    --mix-up 0 \
    --initial-effective-lrate 0.005 --final-effective-lrate 0.0005 \
    --cmd "$decode_cmd" \
    --pnorm-input-dim 3000 \
    --pnorm-output-dim 300 \
    data/train data/lang_nopp_tg exp/nnet4d__ali $dir  || exit 1;
fi

**Comment by danpovey** [comment]
When you increase the number of jobs the iteration isn't supposed to go
faster.  Instead there would be fewer iterations.
So you're saying the time is unchanged at 2 minutes.  That means the K80 is
not faster than the K20.  I'm not sure if it is even supposed to be faster;
but if it is, it could be you're limited by I/O speed

**Comment by allesover** [comment]
Hi Povey, when I using the gridengine on the cluster of gpu server ,do I need to time-synchronize the servers of the clusters? When I typing "date" on different machines, the time showing is slightly different, will it affect the training?

**Comment by danpovey** [comment]
It won't matter.

**Comment by allesover** [comment]
thx...

**Comment by drTonyRobinson** [comment]
Kaldi/gridEngine uses NFS and it used to be the case that having 
different clocks confused NFS.   I've no idea if this is still the case, 
enabling nntpd is straightforward nowadays and is the safe option.  
Sorry to sound like a worrier if there is no issue.


Tony

On 02/06/16 03:30, Daniel Povey wrote:
> It won't matter.
>
> On Wed, Jun 1, 2016 at 10:29 PM, allesover <notifications@github.com> 
> wrote:
>
> > Hi Povey, when I using the gridengine on the cluster of gpu server ,do I
> > need to time-synchronize the servers of the clusters? When I typing 
> "date"
> > on different machines, the time showing is slightly different, will it
> > affect the training?
> >
> > —
> > You are receiving this because you commented.
> > Reply to this email directly, view it on GitHub
> > <https://github.com/kaldi-asr/kaldi/issues/824#issuecomment-223179638>,
> > or mute the thread
> > 
> <https://github.com/notifications/unsubscribe/ADJVuySUdXl2XMLBj-8pIMFprhUPdNe9ks5qHj_wgaJpZM4IsH3n>
> > .
> >
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub 
> <https://github.com/kaldi-asr/kaldi/issues/824#issuecomment-223179743>, or 
> mute the thread 
> <https://github.com/notifications/unsubscribe/APfMj9RvtIyzbaG58cxWxEvw-8Numz38ks5qHkAugaJpZM4IsH3n>.
>


-- 
Speechmatics is a trading name of Cantab Research Limited
We are hiring: www.speechmatics.com/careers 
<https://www.speechmatics.com/careers>
Dr A J Robinson, Founder, Cantab Research Ltd
Phone direct: 01223 794096, office: 01223 794497
Company reg no GB 05697423, VAT reg no 925606030
51 Canterbury Street, Cambridge, CB4 3QG, UK
