### ISSUE TITLE
how to select specific GE queue to run kaldi？

### ISSUE THREAD

**Issue by allesover** [kaldi-asr/kaldi#827]
Hi Povey , now I have to run the kaldi on the same SGE but using different SGE.q. I have declared two different queues: all.q and eval.q . Now I have to run the kaldi on the eval.q but not the all.q.

Can I realise my aim by modifiing the " export train_cmd="queue.pl -l arch=*64 --mem 2G" " to 
" export train_cmd="queue.pl -q eval.q -l arch=*64 --mem 2G" " in the cmd.sh ?

Thx

**Comment by danpovey** [comment]
That would work, however the recommended way to do it is to create the file
conf/queue.conf and edit the command.

Do this:
cat >conf/queue.conf <<EOF
command qsub -v PATH -cwd -S /bin/bash -j y -l arch=*64*
option mem=* -l mem_free=$0,ram_free=$0
option mem=0          # Do not add anything to qsub_opts
option num_threads=* -pe smp $0
option num_threads=1  # Do not add anything to qsub_opts
option max_jobs_run=* -tc $0
default gpu=0
option gpu=0
EOF
which gives you the default queue.conf,
and then edit conf/queue.conf by adding the option -q eval.q to the
'command' line.

**Comment by allesover** [comment]
ok, thx for detailed guidance.
