### ISSUE TITLE
./configure --shared compile error

### ISSUE THREAD

**Issue by wonkyuml** [kaldi-asr/kaldi#830]
I tried to compile with shared library. 

./configure --shared
make depend
make

got error like below:

g++ -shared -o libkaldi-nnet.so -Wl,--no-undefined -Wl,--as-needed  -Wl,-soname=libkaldi-nnet.so,--whole-archive kaldi-nnet.a -Wl,--no-whole-archive  -rdynamic -Wl,-rpath=/local/kaldi/tools/openfst/lib  -Wl,-rpath=/local/kaldi/src/lib -L.  -L../cudamatrix/   -L../matrix/   -L../util/   -L../thread/   -L../base/   ../cudamatrix//libkaldi-cudamatrix.so   ../matrix//libkaldi-matrix.so   ../util//libkaldi-util.so   ../thread//libkaldi-thread.so   ../base//libkaldi-base.so   -L/local/kaldi/tools/openfst/lib -lfst /usr/lib/libatlas.so.3 /usr/lib/libf77blas.so.3 /usr/lib/libcblas.so.3 /usr/lib/liblapack_atlas.so.3 -lm -lpthread -ldl   -lkaldi-cudamatrix   -lkaldi-matrix   -lkaldi-util   -lkaldi-thread   -lkaldi-base
kaldi-nnet.a(nnet-loss.o): In function `void kaldi::nnet1::PosteriorToMatrix<float>(std::vector<std::vector<std::pair<int, float>, std::allocator<std::pair<int, float> > >, std::allocator<std::vector<std::pair<int, float>, std::allocator<std::pair<int, float> > > > > const&, int, kaldi::CuMatrix<float>*)':
/local/kaldi/src/nnet/../nnet/nnet-utils.h:295: undefined reference to `void kaldi::PosteriorToMatrix<float>(std::vector<std::vector<std::pair<int, float>, std::allocator<std::pair<int, float> > >, std::allocator<std::vector<std::pair<int, float>, std::allocator<std::pair<int, float> > > > > const&, int, kaldi::Matrix<float>*)'
collect2: error: ld returned 1 exit status
make[1]: *** [libkaldi-nnet.so] Error 1

**Comment by danpovey** [comment]
You need to make clean first.

**Comment by wonkyuml** [comment]
Actually it was clean install.

**Comment by danpovey** [comment]
Looks like it was a missing dependency in nnet/Makefile, I'll push a fix
right now.

**Comment by wonkyuml** [comment]
Thanks @danpovey

**Comment by wonkyuml** [comment]
It works now.
