### ISSUE TITLE
my doubt about the result of force-align

### ISSUE THREAD

**Issue by hjchen2** [kaldi-asr/kaldi#831]
I tried to understand the details of building decision trees in kaldi recently. When debugging the acc-tree-stat, I find a problem with the alignment. For example, a alignment may be {3, 1, 1, ...}. As my thought, frame 1 is aligned to transition 3  which  is mapping the transition from state 0 to state 2 of the phone sil , and frame 2 is aligned to transition 1 which is mapping the transition from state 0 to state 0 of the phone sil.
My doubt is that how state 0 can loop back in frame 2 for that state 0 has transformed to state 2 in frame 1. Shouldn't it transform from state 2 in frame 2, rather than state 0?

Thanks.

**Comment by francisr** [comment]
The graph may have been built with self loop reordering, this has the effect of moving the self loops of the an HMM state to next state in the topology.

**Comment by hjchen2** [comment]
@francisr Move to next state? I think I need to learn more about how reordering works on the graph. Thanks for your answer.

**Comment by danpovey** [comment]
See http://kaldi-asr.org/doc/hmm.html#hmm_reorder
