### ISSUE TITLE
Error in "egs/sre10/v2/run.sh"

### ISSUE THREAD

**Issue by bajibabu** [kaldi-asr/kaldi#846]
Hi,

I thinks in run.sh file at line 191 instead of "ivectors_sre_test_sup_gmm" it should be "ivectors_sre_sup_gmm"?

"# Create a gender independent PLDA model and do scoring with the sup-GMM system.
local/plda_scoring.sh data/sre data/sre10_train data/sre10_test \
  **exp/ivectors_sre_test_sup_gmm** exp/ivectors_sre10_train_sup_gmm \
   exp/ivectors_sre10_test_sup_gmm $trials local/scores_sup_gmm_ind_pooled"

"# Create a gender independent PLDA model and do scoring with the sup-GMM system.
local/plda_scoring.sh data/sre data/sre10_train data/sre10_test \
  **exp/ivectors_sre_sup_gmm** exp/ivectors_sre10_train_sup_gmm \
   exp/ivectors_sre10_test_sup_gmm $trials local/scores_sup_gmm_ind_pooled"

**Comment by david-ryan-snyder** [comment]
Yes, it looks that way. Can you fix that locally until we push a fix? Also, please let me know if you see anything else that doesn't look right.

**Comment by david-ryan-snyder** [comment]
@danpovey you can close this issue, it got fixed in the last commit.
