### ISSUE TITLE
BLSTM layer in steps/nnet3/components.py

### ISSUE THREAD

**Issue by vijayaditya** [kaldi-asr/kaldi#854]
It would be convenient to have an AddBlstmLayer() function similar to AddLstmLayer().
BLSTMs are right not supported in steps/nnet3/lstm/make_configs.py, which supports a linear LSTM+FullyConnectedLayer network. However for users who desire to add this node to more complicated graphs a function to add BLSTM layers would be very useful.

@freewym  This would just require a minor modification of code as you would move code from steps/nnet3/lstm/make_configs.py to steps/nnet3/components.py. Please let me know if you can pick  this up. 

priority : low
complexity : low

**Comment by freewym** [comment]
OK. Will do it later.
