### ISSUE TITLE
misleading-indentation of src/fstext/determinize-star-inl.h

### ISSUE THREAD

**Issue by EnochLiou** [kaldi-asr/kaldi#859]
# Brief:
The for-loop at src/fstext/determinize-star-inl.h:58~59, containing two operation without having a pair of brace to convey the second assigning operation, which makes the "factor" variable unchanged during the whole loop.

# Compiler warning message:

```
../fstext/determinize-star-inl.h:58:7: warning: this ‘for’ clause does not guard... [-Wmisleading-indentation]
       for (typename vector<Label>::const_iterator it = vec->begin(); it != vec->end(); it++)
       ^~~
../fstext/determinize-star-inl.h:59:31: note: ...this statement, but the latter is misleadingly indented as if it is guarded by the ‘for’
         hash += factor*(*it); factor*=103333;  // just an arbitrary prime number.
                               ^~~~~~
```
## respective source code
```cpp
  53   class VectorKey { // Hash function object.
  54    public:
  55     size_t operator()(const vector<Label> *vec) const {
  56       assert(vec != NULL);
> 57       size_t hash = 0, factor = 1;
> 58       for (typename vector<Label>::const_iterator it = vec->begin(); it != vec->end(); it++)
> 59         hash += factor*(*it); factor*=103333;  // just an arbitrary prime number.
  60       return hash;
  61     }
  62   };
```

# Question
If the `factor` is fixed to 103333, then it can be initialized at line 57. 
The current code would render the hash as the sum of each element in the vector, and the variable `factor` didn't play effective role in this for-loop -- because it is fixed to 1.

However, since `*=` under for-loop is usually a pattern used to change value during for-loop, this make the following code more reasonable:

```cpp
> 57       size_t hash = 0, factor = 1;
> 58       for (typename vector<Label>::const_iterator it = vec->begin(); it != vec->end(); it++) {
> 59         hash += factor*(*it); 
             factor*=103333;  // just an arbitrary prime number.
           }
  60       return hash;
```
However, this might raise another question: since `factor` will be increased exponentially in such a high rate, the overflow of `hash` is quite possible. Although the wrap-around might also be a feature of this kind of algorithm, is this intended design?

# Environment:
* kaldi base on commit d4853c98fd0e69c225cd09f9f1c5126e49a9ddf9
* gcc 6.1.1
* x86_64
* openfst 1.4.1

**Comment by danpovey** [comment]
Thanks for finding this-- I'll fix it.  This might improve graph
compilation speed.  Yes, the wraparound is intended.
