### ISSUE TITLE
[Discussion] Kaldi Product Perspective

### ISSUE THREAD

**Issue by cookiengineer** [kaldi-asr/kaldi#866]
Hey guys,

First I have to say that kaldi is by far the most awesome open source speech recognition software out there. It uses modern approaches, is very accurate and incomparable in terms of developer documentation. The documentation from the developer-side rocks hard.

I really like the project and I think this project could have huge impact if gone into the right way. I wanted to share my thoughts and maybe someone likes the ideas or wants to help taking Kaldi to the next level.

First things first: I'm kind of a nodejs / npm / ES7 botnet guy and obviously am working at the moment to getting Kaldi to run for end-users as an easy self-hosted web service. My experience in C++ is kernel-level, but I'm meanwhile focussing on automating software with [lychee.js](https://lychee.js.org) and I desperately want my computer to be usable in an easier manner. I really think that what the Kaldi project currently covers (as a software) is not all what users need. I'm kind of taking the role of an end-user right now that is sitting on his computer and wants to command it to do things.

**1. Product Perspective**

What is the goal of the project? Being a voice recognition kit that can be used by third-party developers or being a software recognition software for end-users? By software for end-users I mean something like either running `kaldi --mic=1 en-us` with zero configuration overhead. Everything else that is tweakable or configurable is good, but not necessary from an MVP (Minimum viable product) perspective and complicates things and introduces overhead for third-party developers using your software.

**2. Gaining proper training data**

I hate to say it, but [VoxForge](http://www.voxforge.org/home/read) is not good. It's a website from the 90s that is unusable in any means of UX and UI. Requiring a java applet which works only on an outdated Windows XP is basically a total fail as the internet evolved meanwhile to something more HTML5 and mobile.

Today, somebody at /r/opensource posted an [idea of creating an alternative](https://www.reddit.com/r/opensource/comments/4q05xr/open_voice_project/). How's the project maintainers' opinion on this? Good/Bad/Why? What kind of training data does _your_ project need to get into the state of an easy to use software (to say, cover 90% with default configuration)?

**3. Downstream packaging**

What I also think kaldi needs is something like a downstream packaging project that ships everything as bundles. Something like "kaldi-core" and "kaldi-language-en_us" so that people can easily use it without having to compile everything themselves and to have successes in first-time usage.

**4. The website**

The website currently seemingly is focussed on developers. That's good and it has plenty of documentation. Not sure if it's the right way for the project though. To get more developers to use it, kaldi needs either a downstream project or a better website that is focussing on end-user audience. By end-user I mean newcoming developers that try out your stuff and don't want to compile something. I would love to help this project to cover Debian/Ubuntu packages and help getting into upstream Raspbian and/or Debian. I'm kind of a Debian guy, but I would also be able to dig into Arch Linux support via an AUR.

**5. Project Funding and Marketing Ideas**

From an end-user perspective I want to have something that I can start, enter my name, my language, maybe my dialect and that's it. I want to command the software to do something. If that's an impossible goal to reach it helps understand what we need to do to get closer to there. If we focus on text input, we need at least a demo where people can start "text-reading-demo.exe" and say something into the microphone and the app detects it.

My personal experience is all things mobile and cross-platform and/or web. So I would also love to get a simple demo up and running that looks nice for people, so they can try out kaldi and figure things out in the code.

**~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~**

So what are your ideas on the above topics? Good/Bad/Unreasonable?

I really want to help this project and get voice recognition in a state where not only University people are able to use it. And I think chances are really high that Kaldi can succeed and maybe even can get a little funding via downloadable apps for some small bucks. I really think that voice recognition is what people want and need (Google proved that already), but the how is currently totally proprietary. With the right libre ideas, we can heavily influence the desktop (if not even the web) world.

**Comment by sikoried** [comment]
Hi there, I'm sure Dan will comment on this in a few minutes, but here are a few quick thoughts:

Re. 1: It's primarily a research toolkit. In particular, any integration towards front-end (like audio integration) would make it less portable. There's both established (large) companies using it, as well as a bunch of startups.
Re. 2: Most research sites have access to LDC's corpora. Companies often license this data commercially, and add their own data.  Unfortunately, this is "gold", and less likely to be opensourced.
Re. 3: Packaging is hard. I know of at least one docker repo that packages the binaries, Dan maintains some voxforge based models on his page. You won't find other models packaged, since either licensing prohibits it or companies guard it as their secret sauce.
Re. 4+5: Sorry, but it just won't be a commodity such as apache/node in the near future. If you need easy access to speech tech, use APIs like Google or IBM Watson.

**Comment by jtrmal** [comment]
you are right in your observation that kaldi does not cover what a common
computer user needs. You, however, are mistaken in the assumption kaldi
aims to cater their needs. The target audience are speech research teams
and ASR developers.
2) voxforge is not affiliated with kaldi in any way. There is a site
http://openslr.org where we mirror some of the important freely available
resources and we continuously add more.  I don't have any strong feeling
about voxforge or replacing voxforge. Posting somewhere that something
should be done just does not change things. Talking/posting is easy.
Changing things usually need a person with a strong drive who just goes and
starts doing or changing things in which he/she believes.
3) there is not much to do for people who do not want to compile things.
The primary intention is not provide an easy-to-use library for speech
recognition. The primary intention is to provide to speech research
framework. Sometimes these two objectives are aligned (which is great and
in that case we take that into account), sometimes they are not.
4) there is a an example in the egs directory (apiai_decode) that was
provided by a company that provides (to some extent) what you want.

y.

**Comment by danpovey** [comment]
You have to understand that Kaldi is not an ASR system, it is a system for building ASR systems.
Closing this issues-- these kinds of discussions should go on the forums, see kaldi-asr.org/forums.html
