### ISSUE TITLE
Checkout CMUdict using version number in local/fisher_prepare_dict.sh

### ISSUE THREAD

**Issue by vijayaditya** [kaldi-asr/kaldi#867]
`local/fisher_prepare_dict.sh`  used in fisher_english, fisher_swbd and aspire recipes is not using svn checkout with a version number. This can affect reproducibility. (See issue #717). We faced this issue previously in ASpIRE recipe.

```bash
 svn co  https://svn.code.sf.net/p/cmusphinx/code/trunk/cmudict  $dir/cmudict
```

**Comment by naxingyu** [comment]
I'll check it out.


在 2016/6/27 22:28, Vijayaditya Peddinti 写道:
