### ISSUE TITLE
Wave{Reader,Writer} changes

### ISSUE THREAD

**Issue by kkm000** [kaldi-asr/kaldi#88]
For tracking required changes (Discussed in #76)
- [ ] WaveWriter should not crash on out of range data, rather print a warning and continue (rather urgent)
- [ ] ~~Read and write 8 and 32 bit formats correctly.~~ drop support for 8 and 32 bits (see discussion). Scale all internal data to 2‐15×[-1,1] floats.
- [ ] Explain why this range in Docs

**Comment by danpovey** [comment]
> For tracking required changes
> [ ] WaveWriter should not crash on out of range data, rather print a
> warning and continue (rather urgent)
>
Agreed.

> [ ] Read and write 8 and 32 bit formats correctly. Scale all internal data
> to 2‐15×[-1,1] floats.
>

My understanding of the discussion was that we would simply discontinue
support for 8-bit and 32-bit.  But if you are able to get it working
correctly in those cases, I don't object.


> [ ] Explain why this range in Docs
>

Yes- just do it above the class definition in a /** ... */ comment, and
above class member-function declarations in /// comments.  It's not just
about the range-- general documentation of those classes is lacking IIRC.

Dan

**Comment by kkm000** [comment]
Re 8 and 32: you found one example in the wild of a Kaldi user asking abut a 8 bit file, so I thought you wanted to fix it. But I am all for dropping it; 8 and 32 bit files are in the "grey area" where one would play with sox first to make sure the format is chewable. And then at this point, why not use sox anyway.

So, drop?

**Comment by danpovey** [comment]
We later determined that the 8-bit code was definitely broken, so likely
no-one was ever using it successfully.   And also that 32-bit PCM files are
very rare.  So my vote is to drop it.
Dan

**Comment by kkm000** [comment]
@dpovey: ok to rename `wave-reader` => `wave-io`?

**Comment by danpovey** [comment]
Yes, but there is something we need to do with the Makefile when we make
these types of changes, some kind of "ar d" command.  @jtrmal would know.
Dan

**Comment by jtrmal** [comment]
Yes, the makefile in the src/feat dir might need a custom make rule  adding
the "ar -d wave-reader.o"
This is to prevent duplication of the objects.
BTW: this is just to reduce the people that the "kaldi won't build" after
updating -- but make clean && make depend would solve this as well
y.

**Comment by kkm000** [comment]
@jtrmal: so you think it would **not** be ok just skip adding the `ar d` command? The immediate question then is how long should be maintained.

**Comment by danpovey** [comment]
Probably it should be maintained a few months.  the command should be after
a "-", IIRC, so that Make ignores the return status.  We do want that
command there, because it regularly causes installation problems when this
happens.
Dan


On Mon, Aug 24, 2015 at 2:15 PM, Kirill Katsnelson <notifications@github.com

**Comment by danpovey** [comment]
I believe this issue has been addressed.

**Comment by kkm000** [comment]
Well, not entirely. I did not remove the 8 and 32 bit support yet, and still want to finish tests and docs. May I keep it open and assigned to me for a while? Not a high priority, but I do not want it slipping off my radar entirely.

**Comment by danpovey** [comment]
Sure - go ahead and re-open it.

On Sun, Aug 30, 2015 at 3:49 AM, Kirill Katsnelson <notifications@github.com

**Comment by danpovey** [comment]
On this WaveReader issue, it would also be good to support streaming data, i.e. data in which the header is just max(int32) and there are multiple data chunks.

**Comment by kkm000** [comment]
@danpovey: Do such files exist in the wild? I'll do a bit of research but if you have any pointers, I'd appreciate.

**Comment by danpovey** [comment]
Someone reported this on a list:

" have been trying to use ffmpeg in kaldi to work directly with any kind of
file that ffmpeg can convert to wav. So I tried to set it up in the wav.scp
file, e.g.


*SAMPLE ffmpeg -y -i SAMPLE.mp4 -ar 16000 -ac 1 -f wav - |*
*"*

This program seems to produce streaming-mode output, even if piped through
sox, and the header size gives either max(int32) or 0.  BTW, Minhua is
working on this, you'll see a pull request.

Dan


On Tue, Nov 17, 2015 at 9:50 PM, Kirill Katsnelson <notifications@github.com

**Comment by kkm000** [comment]
Interesting, thanks. Never seen such a format.
