### ISSUE TITLE
compiling error

### ISSUE THREAD

**Issue by cadretedata** [kaldi-asr/kaldi#882]
Hi I have this error since I updated code from git (origin/master) and recompiled. I also tried to download complete but same error:

paste-post.cc:91: error: no matching function for call to 'kaldi::RandomAccessTableReader<kaldi::PosteriorHolder>::RandomAccessTableReader(kaldi::RandomAccessTableReader<kaldi::PosteriorHolder>)'
/usr/lib/gcc/x86_64-redhat-linux/4.1.2/../../../../include/c++/4.1.2/bits/stl_vector.h:215: error: in passing argument 2 of 'std::vector<_Tp, _Alloc>::vector(size_t, const _Tp&, const _Alloc&) [with _Tp = kaldi::RandomAccessTableReader<kaldi::PosteriorHolder>, _Alloc = std::allocator<kaldi::RandomAccessTableReader<kaldi::PosteriorHolder> >]'

Thanks, best regards, 
  Antonio

**Comment by danpovey** [comment]
It was an issue where we had the 'explicit' keyword in a self-constructor
in Table code where we shouldn't.  I just fixed it.  Probably this hit you
because you have an unusual or very fresh compiler.
Dan

**Comment by cadretedata** [comment]
Thank you!

The compiler was too old. I was using the default in a cluster (4.1).
After fixing that error I had this one:
nnet1-to-raw-nnet.cc:55: error: no matching function for call to 'kaldi::nnet2::AffineComponent::AffineComponent(kaldi::nnet2::AffineComponent)'

But after compiling with the 4.4 version everything was fine.

Thanks, best regards,
   Antonio
