### ISSUE TITLE
Add steps/cleanup/combine_short_segments.py  stage in chain recipes involving fisher data

### ISSUE THREAD

**Issue by vijayaditya** [kaldi-asr/kaldi#890]
I saw that 30% of the utterances in fisher data were discarded as they were less than the required length.  We have to use steps/cleanup/combine_short_segments.py stage in the chain recipe. For example see stage 12 of ami/s5/local/chain/run_chain_common.sh. It might be better to make this a common stage in all chain recipes, as it might not hurt the performance even in recipes where a lot of data is not being discarded.

(@naxingyu, @freewym, @vimalmanohar, @galv, @pegahgh Please test this stage in the chain recipes you have been working on. )

**Comment by naxingyu** [comment]
Why are alis re-generated when only the alignments in lattice form are used [here](https://github.com/kaldi-asr/kaldi/blob/master/egs/ami/s5/local/chain/run_chain_common.sh#L114)?

**Comment by vijayaditya** [comment]
They are being regenerated to provide the graphs for find_bad_utts.sh
script below
<https://github.com/kaldi-asr/kaldi/blob/master/egs/ami/s5/local/chain/run_chain_common.sh#L134>
.

--Vijay

**Comment by danpovey** [comment]
I think it's actually the fMLLR transforms that find_bad_utts.sh needs.
When we check in Vimal's data-cleanup stuff (which I'm working on right
now, refactoring etc.), the pipeline will change a bit.  We'll do cleanup
with resegmentation, and provide a new data directory.  I'm working on the
interaction with the chain scripts right now.

**Comment by vijayaditya** [comment]
@naxingyu any updates ?

**Comment by naxingyu** [comment]
In the middle of running the decoding part with --max-wer option.


在 2016/7/27 22:55, Vijayaditya Peddinti 写道:

**Comment by vijayaditya** [comment]
@naxingyu Any updates ?

**Comment by danpovey** [comment]
This should now be done with utils/data/combine_short_segments.sh, not with the script in local/.

**Comment by naxingyu** [comment]
In the middle of training. No update yet.


在 2016/8/20 5:35, Vijayaditya Peddinti 写道:

**Comment by naxingyu** [comment]
Exps with sp on fisher_swbd are too expensive. So I removed the sp part, then applied both combine_short_segment and max_wer.
%WER 12.6 | 4459 42989 | 89.2 7.0 3.8 1.8 12.6 51.2 | exp/chain/blstm_6h/decode_eval2000_fsh_sw1_fg/score_8_0.0/eval2000_hires.ctm.filt.sys
%WER 13.8 | 4459 42989 | 87.9 8.1 4.0 1.7 13.8 51.1 | exp/chain/tdnn_7b/decode_eval2000_fsh_sw1_fg/score_8_0.0/eval2000_hires.ctm.filt.sys
%WER 12.2 | 8420 76157 | 89.3 6.6 4.0 1.5 12.2 44.0 | exp/chain/blstm_6h/decode_rt03_fsh_sw1_fg/score_8_0.0/rt03_hires.ctm.filt.sys
%WER 12.7 | 8420 76157 | 88.6 7.2 4.2 1.3 12.7 42.8 | exp/chain/tdnn_7b/decode_rt03_fsh_sw1_fg/score_9_0.0/rt03_hires.ctm.filt.sys
It's hard to say whether it helps or not, due to too many variables involved.

**Comment by danpovey** [comment]
Perhaps you could make a PR for the change and we can try it on our grid at
some point.

**Comment by naxingyu** [comment]
BTW, I rerun the nnet3 exps without sp. And the results seems promising.
%WER 13.7 | 4459 42989 | 87.7 8.5 3.8 1.5 13.7 51.5 | exp/nnet3/lstm/decode_eval2000_fsh_sw1_fg/score_8_0.0/eval2000_hires.ctm.filt.sys
%WER 15.9 | 4459 42989 | 86.0 9.9 4.1 1.9 15.9 52.2 | exp/nnet3/tdnn/decode_eval2000_fsh_sw1_fg/score_10_0.0/eval2000_hires.ctm.filt.sys
%WER 12.9 | 8420 76157 | 88.2 7.6 4.2 1.1 12.9 44.8 | exp/nnet3/lstm/decode_rt03_fsh_sw1_fg/score_10_0.0/rt03_hires.ctm.filt.sys
%WER 14.8 | 8420 76157 | 86.7 9.0 4.3 1.5 14.8 45.9 | exp/nnet3/tdnn/decode_rt03_fsh_sw1_fg/score_11_0.0/rt03_hires.ctm.filt.sys

**Comment by danpovey** [comment]
So that's the baseline for the with-combine-short-segment stuff above, I
guess.

**Comment by naxingyu** [comment]
Yes.


在 2016/8/22 12:12, Daniel Povey 写道:

**Comment by danpovey** [comment]
great-- please make a PR for this change!

**Comment by vijayaditya** [comment]
@naxingyu did you manage to create a PR ? If yes could you link it here ? I am unable to find it.

**Comment by naxingyu** [comment]
I ran it w/o SP, submitted the base results in #990 but closed. I can commit the scripts but the results will not be improved.

**Comment by vijayaditya** [comment]
OK, in that case I will close this issue. Also, @danpovey might recommend using the new cleanup scripts so he might be the correct person to decide if the new scripts have to be merged.
