### ISSUE TITLE
Reg. random seed control for nnet3 experiments

### ISSUE THREAD

**Issue by vijayaditya** [kaldi-asr/kaldi#891]
@freewym You recently wrote some code to change the random seed in nnet3 scripts (for model initialization and egs shuffling) for PR #803. Could you please submit a PR to have this as a feature in `steps/nnet3/train_rnn.py`, `steps/nnet3/train_dnn.py` and `steps/nnet3/chain/train.py`.

**Comment by freewym** [comment]
ok

On Sunday, July 10, 2016, Vijayaditya Peddinti <notifications@github.com>
wrote:

> @freewym <https://github.com/freewym> You recently wrote some code to
> change the random seed in nnet3 scripts (for model initialization and egs
> shuffling) for PR #803 <https://github.com/kaldi-asr/kaldi/pull/803>.
> Could you please submit a PR to have this as a feature in
> steps/nnet3/train_rnn.py, steps/nnet3/train_dnn.py and
> steps/nnet3/chain/train.py.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/kaldi-asr/kaldi/issues/891>, or mute the thread
> <https://github.com/notifications/unsubscribe/ADWAkimw6vLiMzp_aFw-7wgxvZeihxDtks5qUTk3gaJpZM4JI40u>
> .
>


-- 
Sent from my iPhone
