### ISSUE TITLE
nnet3 model manipulation tools

### ISSUE THREAD

**Issue by vijayaditya** [kaldi-asr/kaldi#893]
After looking at some recent discussions in the mailing list and at the CLSP workshop, where people are using `nnet3` models, it seems that complex model manipulation is a frequently needed functionality. It would be convenient to have easy **script level** access for some complex manipulations, as this is intended for novice users. I do not know if it is good design to duplicate C++ functionality in python, but as we do not want to complicate the build process by creating python wrappers, we would have to duplicate some graph manipulation code in python. Of course this code would just enable very basic manipulations and would still rely on the c++ binaries for doing things like testing sanity of the created models.

The process would look like this
1. Convert the model to text
2. Parse the text model into a python object
3. Do all the manipulations on the model graph object 
4. Convert the python object into a text model

TODO:
1. Nnet3 text model parser in python
2.  Python methods for graph traversal, name based identification of nodes, deletion of nodes, addition of nodes, substitution of parameters, manipulation of parameter matrices

Requires : understanding of python, simple graph traversal algorithms, some c++ knowledge to write any c++ binaries required.

**Comment by danpovey** [comment]
This type of thing can be accomplished via the nnet3 editing mechanism I'm introducing in PR #1064.  I'd rather not leave this issue up, as I think it's not realistic that anyone is going to handle it, and I'm not sure I even agree it's the right direction -> closing it.
