### ISSUE TITLE
Packaging of models for upload to kaldi-asr.org

### ISSUE THREAD

**Issue by maxhawkins** [kaldi-asr/kaldi#894]
I'm using the nnet2 online decoding recipe [outlined in the docs](http://www.danielpovey.com/kaldi-docs/online_decoding.html) along with prebuilt models from kaldi-asr.

The second step in the documentation (involving sed) is a little cumbersome for my use case. Instead, I'd like to be able to change the location of the models (and quickly swap them out) without updating all the config files to reference the new model location.

I'd like to allow file paths to be specified relative to the config file. This would allow config files in a downloaded model archive to reference each other without updates.

I would like to implement a new option type in `parse-options.h`

``` c++
void RegisterPath(const std::string &name, std::string *ptr, const std::string &doc);
```

Functions that require a file path option such as OnlineNNet2FeaturePipeline's `ivector-extraction-config` would use this function instead of `Register()`:

``` c++
opts->RegisterPath("ivector-extraction-config", &ivector_extraction_config, // ...
```

The function would convert all relative paths to absolute ones.

If the registration happens from a `--config` file and the `ReadConfigFile()` function then relative paths would be resolved relative to the config file's directory. Otherwise they would be resolved relative to the current executable's path.

This would allow model directories to be moved freely as all model files are specified relative to the config file.

Before I begin, is a change like this likely to be merged?

**Comment by danpovey** [comment]
I'm a little concerned about the implications for back-compatibility from
this change.
To my knowledge (and I might be wrong), we don't always write pathnames as
absolute pathnames in config files, so they'd be relative to the
experimental directory (e.g. s5).
If your change were merged, it would have the effect that programs these
config files would now be looking for the wrong path.


Dan

**Comment by maxhawkins** [comment]
Yes, I think the librispeech config uses paths relative to the experimental directory so this change would break compatibility with that model.

Maybe we could fall back to the old behavior if the file is not found?

**Comment by danpovey** [comment]
That's not really possible in general because the config file just gives
you a string, it may be passed around arbitrarily until it's actually
used.  And there is no flag that says 'this is a filename'.

**Comment by maxhawkins** [comment]
I should give some more context about why I'm interested in this.

I'm coming from the perspective of a user of the online decoding/transcription part of Kaldi rather than a speech researcher. I have an application using Kaldi running as a statically compiled binary outside of the source tree to avoid installing all of Kaldi on every server.

I'd like to try out other people's models on my code, but this is rarely as easy as --config=new-model. I usually spend a couple of minutes moving around files before Kaldi can find them. Kaldi-asr.org models and those distributed with other kaldi-based projects want their [files](http://kaldi-asr.org/downloads/build/8/trunk/egs/fisher_english/s5/exp/nnet2_online/nnet_a_online/conf/online_nnet2_decoding.conf) [in](https://github.com/lowerquality/gentle/blob/master/ext/standard_kaldi.cc#L33) [different](https://github.com/alumae/kaldi-gstreamer-server/blob/master/sample_english_nnet2.yaml#L8) [places](https://github.com/api-ai/asr-server/blob/master/src/OnlineDecoder.cc#L81) even though most use the same decoder pipeline.

It seems like allowing config files to specify relative paths would make it easier to write hermetic, easily distributed models. All you need to specify is one config file and all the dependent files could be found from there. Each model could have its own unique structure internally but be integrated into software with a config file structured the same way. I believe this would make it easier to share work and reduce fragmentation in the community.

**Comment by maxhawkins** [comment]
I think this change will be possible, though I don't fully understand your comment about the config being passed around arbitrarily. Please tell me more.

What I was planning to do was define a new `RegisterPath` function that can be used whenever a file is required in code. The absolute path resolution would take place at the same point in the code as conversion from string to integer happens in the `Register(string name, int32 *value)` option.

**Comment by sikoried** [comment]
To a certain extent, you can use relative filenames already;  they'd  have to be relative to the path you're executing in.  Depending on your OS, you can use symlinks to fudge "real" relative paths.

(In our case for example, we're dockerizing services anyways, so the current path is easy to set.)

**Comment by danpovey** [comment]
The models at kaldi-asr.org are not being updated right now and I know
they're not very easy to use or very well supported.

I don't think I want to put effort into making the downloadable models
easier to use right now.  It's a question of whether Kaldi is an upstream
or a downstream project.  Right now we're having a lot of impact by being
an upstream source of speech recognition, dealing only with other speech
researchers and capable speech recognition groups.  And I think the
technology is still moving too fast for it to make sense to try to
crystallize it and make it easier to use by people with less expertise and
resources.  I.e. at the moment we'd rather deal with the kinds of people
who would want to build their own models on their own cluster.  Right now
these kinds of groups are, I think, the only ones who can realistically
benefit from the technology in its current state anyway.   Pre-packaged
models aren't good enough for most applications as they don't benefit from
domain-specific training data or language models.  Maybe in future we can
make it easier to use by others, but for now, anything that attracts too
many downstream users that will occupy too much of our time, while
producing relatively less value.


One problem with your approach is that if all paths are relative to the
config file, the meaning of all the existing config files changes.  So it's
a back compatibility problem.  Also, Kaldi is a speech recognition toolkit,
it's not a UNIX shell or an operating system, and I think doing stuff like
this is a mistake in terms of project scope.

What you are asking for could be accomplished by having an installation
script that modifies the config file- you could transfer files with some
kind of pattern in that a search-and-replace command could replace with
that actual absolute pathname.  This isn't really that hard.



Dan

**Comment by maxhawkins** [comment]
Thanks Dan, this helps a lot.

I think the relative paths could easily be made backward compatible by first checking whether the file exists and then falling back on the old behavior. However, your point about scope creep is a good one. I think this change might not be worth the added complexity.

However, I'd like to push back on your point about general models not being useful. For people doing work on user interfaces and other downstream applications of this technology off-the-shelf models are dramatically better than existing solutions (Sphinx). Even poorly-adapted models make some previously-infeasible speech user interfaces possible.

I think I misunderstood the purpose of the kaldi-asr.org files, which is why I opened this issue. If it's not something that's intended to be well-supported that's OK. In that case this is probably a better discussion to have with downstream library authors (@alumae, @api-ai) about how to share models rather than trying to develop a solution at the Kaldi level and slowing down researchers.

From the perspective of someone using lattices rather than tweaking decoding pipelines, it would be great to have a standard way to mix and match models and an ecosystem that encourages people to share new models. That way my effort, for instance, to train a model on Arabic speech recognition could seamlessly be used by someone doing forced alignment on Arabic radio broadcasts or an Arabic chat bot. Things like requiring the files to be in a specific (non-standardized) directory structure introduce friction that makes it less easy to collaborate on models.

The solution might be to define some guidelines about where in a directory structure an uploaded model can expect to live. Maybe every model could define a `model.conf` in the same place relative to the model's root. That way models could be dropped in without having to write a custom configure script for each unique directory structure. All a downstream library author would have to do is change the cwd to the model's root and read the `model.conf`.

**Comment by danpovey** [comment]
Changing the title of this issue to "Packaging of models for upload to kaldi-asr.org".  I haven't forgotten about this and I will get to it soon..

**Comment by maxhawkins** [comment]
Thanks Dan!

**Comment by danpovey** [comment]
@maxhawkins, although we did this, I'll leave this issue up a bit as I think it's not 100% finalized.
