### ISSUE TITLE
Issues relating to RNNLM

### ISSUE THREAD

**Issue by elfring** [kaldi-asr/kaldi#90]
Would you like to add more error handling for return values from functions like the following?
- [fopen](http://pubs.opengroup.org/onlinepubs/9699919799/functions/fopen.html "Open a stream.") ⇒ [TrainModelThread](https://github.com/kaldi-asr/kaldi/blob/1a59ece8f53e904d10cfce1758222a258e9a148e/tools/rnnlm-hs-0.1b/rnnlm.c#L410)
- [fscanf](http://pubs.opengroup.org/onlinepubs/9699919799/functions/fscanf.html "Convert formatted input.") ⇒ [ReadVocab](https://github.com/kaldi-asr/kaldi/blob/1a59ece8f53e904d10cfce1758222a258e9a148e/tools/rnnlm-hs-0.1b/rnnlm.c#L333)

**Comment by danpovey** [comment]
Ilya Edrenkin (cc'd) is responsible for this RNNLM training code; it is not
part of Kaldi proper.
But I don't see any reason why not to do it; if you submit a patch I would
likely approve it.

Dan

**Comment by ilya-edrenkin** [comment]
Hi, 

I think it is a good idea.

Furthermore, @akhti has completely rewritten the rnnlm code and published it at https://github.com/yandex/faster-rnnlm
It is (almost) identical to rnnlm-hs-0.1b in terms of modeling capability, but also it:
1) is nearly 3 times faster;
2) supports NCE in addition to HS output;
3) greatly improved on style.
Probably we should replace the rnnlm in kaldi with this one since it is definitely better. Dan, what do you think about it?

**Comment by jtrmal** [comment]
Ilya, how different are the command switches?
y.

**Comment by ilya-edrenkin** [comment]
AFAIK Anton tried to make them 100% compatible (although there are some new switches, for example those that are used for NCE).

**Comment by danpovey** [comment]
If someone had the time to make the changes and test the associated
scripts, and submit a pull request, that would be great.  Ilya?
Dan

**Comment by jtrmal** [comment]
Ok, in that case, the first step would be to add
extras/install_faster-rnnlm.sh script (ideally downloading the sources
directly from github). This way we could compare the behavior/compatibility.
y.

**Comment by jtrmal** [comment]
BTW, I cannot offer too much of my time -- I can review the script and help
with the issues you guys could run into, but not much else.
y.

**Comment by ilya-edrenkin** [comment]
Yes, sure, clearly we have to do it ourselves. I've asked @akhti to have a look here. I believe that he tested his models on kaldi librispeech recipes, so probably there is some existing code just to be merged in here.

**Comment by jtrmal** [comment]
I will mark this as resolved, as the referencing PR was merged in.

**Comment by v-yunbin** [comment]
> Ok, in that case, the first step would be to add
> extras/install_faster-rnnlm.sh script (ideally downloading the sources
> directly from github). This way we could compare the behavior/compatibility.
> y.
> 
> On Mon, Aug 24, 2015 at 4:32 PM, Ilya Edrenkin [notifications@github.com](mailto:notifications@github.com)
> wrote:
> 
> > AFAIK Anton tried to make them 100% compatible (although there are some
> > new switches, for example those that are used for NCE).
> > —
> > Reply to this email directly or view it on GitHub
> > [#90 (comment)](https://github.com/kaldi-asr/kaldi/issues/90#issuecomment-134370289).
whether to compare the behavior of faster rnnlm and arpa lm or have some compatibility results？
I compare faster rnnlm and arpa lm，but  the faster rnnlm perfomer badly
