### ISSUE TITLE
Error on speaker recognition examples

### ISSUE THREAD

**Issue by RobertoFont** [kaldi-asr/kaldi#901]
Hello,

I think I've found an error on sre scripts. When performing cosine scoring, for example

```
cat $trials | awk '{print $1, $2}' | \
 ivector-compute-dot-products - \
  scp:exp/ivectors_sre08_train_short2_female/spk_ivector.scp \
  scp:exp/ivectors_sre08_test_short3_female/ivector.scp \
   foo
```
speaker-level ivectors (spk_ivector.scp) are lenght-normalized, but utterance-level ivectors (ivector.scp) are not. This way, dot products are not actually cosine distance scores.

Test ivectors should be piped into ivector-normalize-length or ivector.scp replaced by spk_ivector.scp if each utterance corresponds to a different speaker as is usually the case in test set.

Let me know if I'm wrong.

Regards.

**Comment by danpovey** [comment]
@david-ryan-snyder, did this slip by you?

**Comment by david-ryan-snyder** [comment]
@danpovey, @RobertoFont,

Training some SRE08 models for this now. I'll apply the fix and update the inline comments with the results once that's done.

**Comment by david-ryan-snyder** [comment]
Since the fix is in Kaldi now, you can close this, @danpovey.

@RobertoFont, FYI
