### ISSUE TITLE
Bi-LSTM with three layers

### ISSUE THREAD

**Issue by baylor0118** [kaldi-asr/kaldi#911]
Hi,

For Bi-LSTM, with adding the projection layers, when the number of layer reach
to three layers, the training will get terrible. what might account for this strange 
phenomenon?

All the best.

**Comment by danpovey** [comment]
The BLSTMs are subject to gradient explosions which can sometimes cause
training to fail.  If it's this that's the problem, you can grep for
'clipped-proportion' in the progress logs for later iterations and you
should see values much greater than zero (e.g. approaching 1).
We recently added a mechanism to try to control this, search for
self_repair_scale_clipgradient in steps/nnet3/lstm/make_configs.py.  If it
isn't there, you have an older version of Kaldi that doesn't have this.

Dan

**Comment by baylor0118** [comment]
It's nnet3. But I use nnet1.

**Comment by danpovey** [comment]
Oh.  The nnet1 BLSTMs actually don't work that well even when they are
training stably, as far as I know.
Dan

**Comment by vijayaditya** [comment]
@vesis84 / @mallidi  Could either of you respond to this query ?
