### ISSUE TITLE
rnnlm

### ISSUE THREAD

**Issue by vladbataev** [kaldi-asr/kaldi#912]
Hello. I saw rnnlm and faster-rnnlm toolkits which could be used for building language models. But these toolkits only produce neural network weights. How can I use them for creating my own language model?

**Comment by danpovey** [comment]
RNNLM toolkit produce RNNLM language models, which can be interpreted by
those toolkits to produce probabilities.  If you want an ARPA-format
models, you shouldn't use those toolkits.

Dan

**Comment by vladbataev** [comment]
So, kaldi provides a conversion of these probabilities into a grammar wfst, doesn't it?

**Comment by danpovey** [comment]
No, and it's not possible even in principle
Dan

**Comment by vladbataev** [comment]
Then, I understand how rnnlm and n - gram approaches can be combined together or only rnnlm can be used: give n-gram sequence to the neural network and it will produce the probabilities of the next word. After that, it can be used in wsft, but it's constraint of rnnlm, because it doesn't use all history of the previous context. Is it possible to use rnnlm directly?

**Comment by jtrmal** [comment]
It's probably not possible for any real-size lattice.  The current
rescoring expands the lattice to get unique 8gram(?, not sure completely of
the degree) histories. I think Dan or Guoguo tried higher degree, but it
didn't lead to any significant difference. You could, in theory, modify the
source code of the rnnlm rescoring to give you higher n-gram contexts. I
think it might be even quite easy, provided you are able to read and
understand the code. But, In that case, you should be also able to
understand why it's not generally reasonable thing to do.
Other approach is to generate n-best paths list and rescore the list.
There is/was a script for that. I think the finding was the limited n-gram
histories worked better than limiting alternatives.

Also, I'm closing this issue. This is not a place to seek this kind of help.
y.

**Comment by vladbataev** [comment]
Thanks a lot for your help.
