### ISSUE TITLE
SDM data prep in AMI may be wrong

### ISSUE THREAD

**Issue by danpovey** [kaldi-asr/kaldi#917]
It looks like in sdm_ami_data_prep.sh, it's supposed to create an utt2spk that uses the session (meeting) to adapt on:
```
# Assumtion, for sdm we adapt to the session only                                                                                                            
awk '{print $1}' $dir/segments | \
  perl -ane '$_ =~ m:^(\S+)([FM][A-Z]{0,2}[0-9]{3}[A-Z]*)(\S+)$: || die "bad label $_";                                                                      
          print "$1$2$3 $1\n";' | sort > $dir/utt2spk || exit 1;

```
It's not clear what the intention of this regexp was... the segments file looks like this
```
AMI_EN2001a_SDM_FEO065_0021133_0021442 AMI_EN2001a_SDM 211.33 214.42
```
and the speaker labels end up looking like `AMI_EN2001a_SDM_`
I'm sure the intention was not to have the speaker name end in an underscore.  That regexp is really nasty too- I can't figure out what was the thinking behind it.

not a big priority but we should fix it at some point.  There are 135 speakers in the SDM data-prep after this... I don't know if this was what was desired.

AMI SDM may be a good test bed for diarization once we get to it.  Maybe Vimal can do it once he gets back-- he is good at getting started on new problems.

**Comment by vijayaditya** [comment]
(+ @pswietojanski  as he most probably wrote the data prep scripts.)

**Comment by danpovey** [comment]
BTW, I'm pretty sure what would be better than assigning the entire meeting to one speaker, is to assign roughly one-minute chunks of meetings to different speakers.
Of course the same would have to be done in test time.

**Comment by danpovey** [comment]
I think I'll address this along with a rewrite and simplification of the AMI scripts.  I'm testing it now.
Not sure whether to replace the current setup or make s5b.. probably s5b.

**Comment by pswietojanski** [comment]
Hi Dan and Vijay, thanks for adding me to this discussion. That was exactly the motivation of this particular regex -- map all utterances within the given meeting to a single label (which happen to be the whole meeting). We thought that assuming known speaker labels (or even the number of different speakers) is rather unrealistic. Of course, there are many options starting from fully unsupervised diarisation to, for example, SNR based speaker clustering (as through the meeting speakers and mics have fixed locations). Each of those assume different priors you put on data.  We though at that time that we did was a reasonable baseline on top of which one can do more, if willing to.

I do agree, when I look at those scripts right know, that some regex expressions are over-complicated in this recipe.
