### ISSUE TITLE
CUDA interface change and new function

### ISSUE THREAD

**Issue by danpovey** [kaldi-asr/kaldi#94]
@naxingyu, it would be great if you could help with this because you have been working on similar code recently.  This is something I need for my work on CTC (which I am working on currently in my personal fork of Kaldi).  I'll add you to the paper if you can help with this.

The following code currently exists in cu-matrix.h:

    // This function, adds a list of MatrixElements (scaled by alpha) to corresponding locations to                                                                    
    // (*this).                                                                                                                                                        
    void AddElements(Real alpha, const std::vector<MatrixElement<Real> >& input);
    
    // This function resizes the output to indexes.size(), and for each element of                                                                                     
    // "indexes" it interprets it as a (row, column) index into *this, and puts                                                                                        
    // (*this)(row, column) into the corresponding element of "output".                                                                                                
    void Lookup(const std::vector<Int32Pair> &indexes,
                std::vector<Real> *output) const;

What I would like is (1) to change the interface of the existing Lookup to take a Real* pointer instead of a std::vector, for greater flexibility, (2) add a version of Lookup that takes CuArray<Int32Pair> instead, that would be called internally by the existing function in cases where CUDA is being used; and (3) add a version of AddElements that is more compatible with the Lookup interface, as follows (we can add an alpha to its interface later if it becomes necessary).

     /// For each i, with indexes[i] = (j, k), does (*this)(j, k) += input[i].  Requires, but does
     /// not check, that the vector of indexes does not contain repeated elements.  'input'
     /// is the start of an array of length equal to indexes.Dim().
     void AddElements(const CuArray<Int32Pair> &indexes, const Real *input);

**Comment by naxingyu** [comment]
Sure. Your instructions are quite straightforward. I'll take it.

X.

**Comment by naxingyu** [comment]
Should I update all the calls to the new interface?

**Comment by danpovey** [comment]
Yes.
