### ISSUE TITLE
GridEngine flush_time in http://kaldi-asr.org/doc/queue.html

### ISSUE THREAD

**Issue by Invisibility** [kaldi-asr/kaldi#958]
Hi folks,

I followed the instruction in the kaldi documentation at http://kaldi-asr.org/doc/queue.html and changed the flush_time (part of the attribute of the reporting_params key in qconf -mconf), but I noticed that it doesn't help much with the turnaround time for submitting jobs. 

I looked up online and found that flush_time controls the reporting flush interval.

What I found improve the turnaround time for submitting jobs is the qconf -msconf, within which has the schedule_interval which defaults to 15 seconds. After changing it to a smaller value, the turnaround time improve. 

Maybe the kaldi documentation should be updated.

Thanks!

**Comment by danpovey** [comment]
Thanks-- I'm updating the documentation (compiling now).
