### ISSUE TITLE
Storing ivector extractor ID in ivector directories and nnet3 model directories

### ISSUE THREAD

**Issue by vijayaditya** [kaldi-asr/kaldi#965]
Mismatch between iVector extractors used for training and decoding is a frequent user error. We should probably assign a unique ID to each iVector extractor and store this information in all related directories which use the output of this extractor e.g. iVector directories and nnet3 model directories. When the decode scripts, or similar scripts, are used with an nnet3 model and an iVector directory whose unique extractor ids do not match they should raise an error.

**Comment by danpovey** [comment]
Good idea.
The extractor IDs can be assigned by the training script, as a file
'extractor_id'.. a space-free form of the date and time it was written
would be suitable.
Dan

**Comment by vijayaditya** [comment]
OK

**Comment by vijayaditya** [comment]
Being addressed in #967

**Comment by jtrmal** [comment]
currently being addressed in #1395

**Comment by david-ryan-snyder** [comment]
@jtrmal, isn't this issue resolved in #1395?

**Comment by jtrmal** [comment]
yes, resolved. Thanks for noticing. Closing.
