### ISSUE TITLE
why rnnlm tool doesn't have parameter for syn0 --> hidden

### ISSUE THREAD

**Issue by fedorajzf** [kaldi-asr/kaldi#97]

**Comment by danpovey** [comment]
Ilya edrenkin wrote the RNNLM tool.  I don't understand what the question
means.
Ilya, if you could get a github account it would be helpful.
Dan

**Comment by ilya-edrenkin** [comment]
Here I am.
However I also don't get the question, frankly. syn0 matrix is used for word embeddings, they are just learned. What do you mean by a parameter in this context?

**Comment by danpovey** [comment]
This is more of a discussion than a real issue; closing the issue.

**Comment by fedorajzf** [comment]
hi, ilya
in rnnlm.c，hidden value is stored in neu1,  neu1[t] = sigmoid(synRec * neu1[t-1] + syn0)
should it be neu1[t] = sigmoid(synRec * neu1[t-1] + syn0 * U) ,  here U is another parameter for syn0 to hidden layer.

**Comment by ilya-edrenkin** [comment]
It might be the case that carefully choosing this U would improve convergence; however I'd expect from the training procedure to learn the optimal scale for syn0 without making it a parameter.

**Comment by fedorajzf** [comment]
if not use U,  hidden layer dimension must equal embedding dimension, maybe this is a problem
