### ISSUE TITLE
[BUG]  cu-matrix.cc AddMatMatElements KALDI ASSERT

### ISSUE THREAD

**Issue by lomizandtyd** [kaldi-asr/kaldi#974]
Need to check col number and row number in [cu-matrix.cc: 1258 : AddMatMatElements](https://github.com/kaldi-asr/kaldi/blob/master/src/cudamatrix/cu-matrix.cc) ...

-------------------------------
Other information about the bug..

I create a new component in src/nnet like [`nnet-lstm-projected.h`](https://github.com/kaldi-asr/kaldi/blob/master/src/nnet/nnet-lstm-projected.h)
But I wrote a wrong backpropagate function..
The component I implemented is a projected GRU..

-----

**BEGIN** introduction to my projected gru

-----

if `h_t` is the output of a regular gru layer,
`m_t = h_t * w_m_h_ ` is the projected output of a projected gru, like above projected lstm.

`h_t = (1-z) .* h_tm1 + z .* c_t`

So when do backpropagate.
I should write diff of the update gate `z` as follow:
`dz_t = dh_t .* c_t - dh_t .* h_tm1`
I wrote something like this:
`dz_t = dh_t .* c_t - dh_t .* m_tm1`

-----

**END**   introduction to my projected gru

-----

Code is:
```
      d_z[t]->AddMatMatElements(-1.0, *d_h[t], *y_h[t-1], 0.0);
      d_z[t]->AddMatMatElements(1.0, *d_h[t], *y_c[t], 1.0);
      d_z[t]->DiffSigmoid(*y_z[t], *d_z[t]);
```
But I made a mistake, and my wrong code is :
```
      d_z[t]->AddMatMatElements(-1.0, *d_h[t], *y_m[t-1], 0.0);

      // while the y_m[t-1]->NumCols() == output_dim
      //               d_h[t]->NumCols() == cell_dim 
      // In a projected component,   cell_dim != output_dim  (I use cell_dim = 1024, output_dim=384)
      // this is the place I found the bug..

      d_z[t]->AddMatMatElements(1.0, *d_h[t], *y_c[t], 1.0);
      d_z[t]->DiffSigmoid(*y_z[t], *d_z[t]);
```

However, the code successfully run, and get same performance in my task. 
It's strange because I only trained the first 384 cells for keeping memory...
Maybe 384 cells is enough for my data..
I couldn't show my code for some reason.

**Comment by danpovey** [comment]
@freewym, could you please add an assert for this?  [use SameDim()].

**Comment by danpovey** [comment]
Actually, @freewym, forget that, I know you're busy with other stuff...  @kangshiyin, can you please do this?

**Comment by danpovey** [comment]
Thanks.
BTW, @freewym has been working with GRUs too, and IIRC, also projected GRUs.
As far as I know he has not got quite the same results as BLSTMs yet, but it's quite close, and slightly faster.  You can talk to him at freewym@gmail.com.
