### ISSUE TITLE
Better testing of divergent strides

### ISSUE THREAD

**Issue by danpovey** [kaldi-asr/kaldi#987]
@kangshiyin, I think it would be useful, for the purpose of testing code, if you could implement a mechanism in CuDevice where with some probability, when a matrix is allocated with `MallocPitch()`, it will have unexpected stride.  [e.g. if the mode is set to true, then with probability 0.5, add 128 to the requested `row_bytes`]  Best not to modify the CuAllocator code, as it's complicated; do it at the CuDevice level.

```
/// Call this with true
class CuDevice {
  ...
  /// Call SetRandomStrideMode(true) to activate a mode where calls
  /// to MallocPitch will purposely allocate arrays with randomized pitch
  /// (inconsistent between calls).  This is only useful testing code.
  ///This function returns the previous mode, where true means randomized
  /// pitch.  Note that you cannot ever rely on the strides from MallocPitch() being
  /// consistent for the same request, but in practice they tend to be consistent
  /// unless you are close to running out of memory.
  bool SetRandomStrideMode(bool mode)
```

... and then set this mode to true in the testing programs, but not in the speed-test programs.
I'm hoping that it will detect more bugs like what we found recently.

BTW (unrelated),  I read recently that when setting the block size [num-threads], it's best where possible to set it to a multiple of the threads-per-warp (16).  I imagine this prevents the compiler having to insert conditional code into the kernels [because probably, at a hardware level, the real threads-per-block is always a multiple of 16.]  You might want to look over the kernels and see if there is any opportunity for optimization there.

Another unrelated note: in general the documentation for the CUDA kernels needs to be improved, i.e. document what the kernels do, what the arguments represent, and what they expect in terms of block and grid sizes.  The original code had very little documentation but I think that is not a good pattern to follow.

**Comment by kangshiyin** [comment]
For issue 1
I think we have to modify `CuMemoryAllocator`. My current idea is to
1) modify `CuMemoryAllocator::MallocPitch` to disable cache lookup in `RandomStrideMode` so we have the chance to change stride; and 
2) modify `CuMemoryAllocator::MallocPitchInternal` to return a random pitch/stride while keeping input `row_bytes` and `num_rows` unchanged.
Any better idea?

For issue 2
You are right that the real threads-per-block is always a multiple of thread-per-warp.
Generally a multiple of thread-per-warp (32) should be better. 16 is size of half-warp. It's recommended for old devices(CC1.x and CC2.x) and sometimes it's better than 32 for `double` data type. 
I've taken this into consideration for the kernels I've modified. For example in tree reduction, you always reduce from 256 threads instead of the length of the array to avoid warp divergence.

For issue 3
Ideally I think it would be better to set block and grid size just before launching the kernel (the line with `<<<...>>>`), in cu-kernerls.cu, and hide the block/grid configuration from the kernel caller `CuMatrixBase`. It would be easier to read the kernel implementation while checking the block/grid configuration in a single file. But this may lead to huge code and kernel API modification.
Currently the comments in cu-matrix.h can explain what the kernels do in most cases.  But we need more explanation on the block/grid configuration part. I think we can either make more comments before setting block/grid dim like this
```
    // 2D blocks: each (8x32) block sums up (32x32) elements.
    // 2D grid: try to cover all the matrix A unless it is too big.
    // Kernel will reduce to ~256 elements with good performance,
    // if the matrix is not in a very bad shape.
    // (wider or taller than 32x8192)
    // CPU will then reduce to 1 element.
    const int kWarpSize = 32;
    dim3 dimBlock(kWarpSize, CU1DBLOCK / kWarpSize);
    dim3 dimGrid(n_blocks(A.NumCols(), kWarpSize),
        n_blocks(A.NumRows(), kWarpSize));
```
or put this in front of the "__global__" kernel function. What do you think?

**Comment by danpovey** [comment]
>
> For issue 1
> I think we have to modify CuMemoryAllocator. My current idea is to
> 1) modify CuMemoryAllocator::MallocPitch to disable cache lookup in
> RandomStrideMode so we have the chance to change stride; and
> 2) modify CuMemoryAllocator::MallocPitchInternal to return a random
> pitch/stride while keeping input row_bytes and num_rows unchanged.
> Any better idea?
>

I didn't want to modify CuMemoryAllocator because it's already quite
complicated.  What I was suggesting is that when CuDevice's MallocPitch()
function calls CuMemoryAllocator, it can randomly add something to the
bytes_per_row.  It won't matter that more memory is being returned than
requested.


> Ideally I think it would be better to set block and grid size just before
> launching the kernel (the line with <<<...>>>), in cu-kernerls.cu, and
> hide the block/grid configuration from the kernel caller CuMatrixBase. It
> would be easier to read the kernel implementation while checking the
> block/grid configuration in a single file. But this may lead to huge code
> and kernel API modification.
>

I'd rather not risk bugs by making this change for existing code.

> Currently the comments in cu-matrix.h can explain what the kernels do in
> most cases. But we need more explanation on the block/grid configuration
> part. I think we can either make more comments before setting block/grid
> dim like this
>
>     // 2D blocks: each (8x32) block sums up (32x32) elements.
>     // 2D grid: try to cover all the matrix A unless it is too big.
>     // Kernel will reduce to ~256 elements with good performance,
>     // if the matrix is not in a very bad shape.
>     // (wider or taller than 32x8192)
>     // CPU will then reduce to 1 element.
>     const int kWarpSize = 32;
>     dim3 dimBlock(kWarpSize, CU1DBLOCK / kWarpSize);
>     dim3 dimGrid(n_blocks(A.NumCols(), kWarpSize),
>         n_blocks(A.NumRows(), kWarpSize));
>
> or put this in front of the "*global*" kernel function. What do you think?
>

I'd say both; but different kinds of documentation.  Next to the kernel,
any not-completely-obvious *requirements* of what the block/grid pattern
should be need to be spelled out.  Next to the invocation, a clarification
of what we are doing may be helpful, if it's not completely obvious from
the code or if it is related to some non-obvious requirement of the kernel.

Also I don't think it's sufficient to rely on the documentation of the
calling function in CuMatrix, as that requires going up many levels of
function invocations-- IMO, each function needs to document what it does
and what its interface, locally.  And this isn't just a question of the
dimBlock and dimGrid, there are other issues like:  what does the kernel
do?  What are the dimensions and strides of its matrix arguments?  What is
the relationship between the block and grid indexes and the matrix
indexes?  What are the assumptions of the kernel about the block and grid
sizes it's called with?  Are there any additional assumptions, such as that
certain pairs of arguments do not refer to the same matrix, or that the
strides are identical?  Some of this is possible to work out from the code
but it can be painful.


For example the function:
```
template<typename Real>
__global__
static void _copy_low_upp(Real* A, MatrixDim dimA) {
  int i = blockIdx.x * blockDim.x + threadIdx.x;
  int j = blockIdx.y * blockDim.y + threadIdx.y;
  if (i <= j || i >= dimA.rows) return;
  int index_1 = i * dimA.stride + j;
  int index_2 = j * dimA.stride + i;
  A[index_2] = A[index_1];
}
```
... here is some sample documentation.  Note: don't add little columns of
stars like some of the existing code in that file does; that's against the
normal pattern for Kaldi code.

```
/*
  This kernel copies the lower triangle to the upper triangle of matrix A
with
  dimension dimA.  We require that dimA.rows == dimA.cols.
  Only half of the threads actually do something (copying one
  element); the other half do nothing.  The row the of source element (in
the
  lower triangle) is worked out from the x [thread,block] index and the
  column of the source element is worked out from the y [thread,block]
index.
/*
```

The documentation above is imprecise about how the row index is worked
out from the [thread,block] indexes but it's easy to work out from the code
so
I'm not bothering specifying.  But if things are less obvious it might be
worthwhile to spell it out.  For instance, sometimes a matrix argument will
have a num-rows and num-cols given by, say, dimA, but a stride given by a
variable like 'src_stride', and that needs to be made explicit.

The current code is very inconsistent about using (i,j) for (rows,cols)
versus (cols,rows).  I prefer (rows,cols) for new code but if changes are
made to existing code we should probably test it for a while before
committing.

Also, we should try to keep mostly to the 80-char-per-line limit required
by the
rest of Kaldi, which the CUDA code is very out of compliance with.



Dan

**Comment by contributeyourvoice** [comment]
On Tue, Aug 23, 2016 at 3:39 AM, Daniel Povey <notifications@github.com> wrote:
>
> >
> > For issue 1
> > I think we have to modify CuMemoryAllocator. My current idea is to
> > 1) modify CuMemoryAllocator::MallocPitch to disable cache lookup in
> > RandomStrideMode so we have the chance to change stride; and
> > 2) modify CuMemoryAllocator::MallocPitchInternal to return a random
> > pitch/stride while keeping input row_bytes and num_rows unchanged.
> > Any better idea?
> >
>
> I didn't want to modify CuMemoryAllocator because it's already quite
> complicated. What I was suggesting is that when CuDevice's MallocPitch()
> function calls CuMemoryAllocator, it can randomly add something to the
> bytes_per_row. It won't matter that more memory is being returned than
> requested.
>
Please see #997 for this.


>
> > Ideally I think it would be better to set block and grid size just before
> > launching the kernel (the line with <<<...>>>), in cu-kernerls.cu, and
> > hide the block/grid configuration from the kernel caller CuMatrixBase. It
> > would be easier to read the kernel implementation while checking the
> > block/grid configuration in a single file. But this may lead to huge code
> > and kernel API modification.
> >
>
> I'd rather not risk bugs by making this change for existing code.
>
I agree with you.


> > Currently the comments in cu-matrix.h can explain what the kernels do in
> > most cases. But we need more explanation on the block/grid configuration
> > part. I think we can either make more comments before setting block/grid
> > dim like this
> >
> > // 2D blocks: each (8x32) block sums up (32x32) elements.
> > // 2D grid: try to cover all the matrix A unless it is too big.
> > // Kernel will reduce to ~256 elements with good performance,
> > // if the matrix is not in a very bad shape.
> > // (wider or taller than 32x8192)
> > // CPU will then reduce to 1 element.
> > const int kWarpSize = 32;
> > dim3 dimBlock(kWarpSize, CU1DBLOCK / kWarpSize);
> > dim3 dimGrid(n_blocks(A.NumCols(), kWarpSize),
> > n_blocks(A.NumRows(), kWarpSize));
> >
> > or put this in front of the "*global*" kernel function. What do you think?
> >
>
> I'd say both; but different kinds of documentation. Next to the kernel,
> any not-completely-obvious *requirements* of what the block/grid pattern
> should be need to be spelled out. Next to the invocation, a clarification
> of what we are doing may be helpful, if it's not completely obvious from
> the code or if it is related to some non-obvious requirement of the kernel.
>
> Also I don't think it's sufficient to rely on the documentation of the
> calling function in CuMatrix, as that requires going up many levels of
> function invocations-- IMO, each function needs to document what it does
> and what its interface, locally. And this isn't just a question of the
> dimBlock and dimGrid, there are other issues like: what does the kernel
> do? What are the dimensions and strides of its matrix arguments? What is
> the relationship between the block and grid indexes and the matrix
> indexes? What are the assumptions of the kernel about the block and grid
> sizes it's called with? Are there any additional assumptions, such as that
> certain pairs of arguments do not refer to the same matrix, or that the
> strides are identical? Some of this is possible to work out from the code
> but it can be painful.
>
>
> For example the function:
> ```
> template<typename Real>
> __global__
> static void _copy_low_upp(Real* A, MatrixDim dimA) {
> int i = blockIdx.x * blockDim.x + threadIdx.x;
> int j = blockIdx.y * blockDim.y + threadIdx.y;
> if (i <= j || i >= dimA.rows) return;
> int index_1 = i * dimA.stride + j;
> int index_2 = j * dimA.stride + i;
> A[index_2] = A[index_1];
> }
> ```
> ... here is some sample documentation. Note: don't add little columns of
> stars like some of the existing code in that file does; that's against the
> normal pattern for Kaldi code.
>
> ```
> /*
> This kernel copies the lower triangle to the upper triangle of matrix A
> with
> dimension dimA. We require that dimA.rows == dimA.cols.
> Only half of the threads actually do something (copying one
> element); the other half do nothing. The row the of source element (in
> the
> lower triangle) is worked out from the x [thread,block] index and the
> column of the source element is worked out from the y [thread,block]
> index.
> /*
> ```
>
> The documentation above is imprecise about how the row index is worked
> out from the [thread,block] indexes but it's easy to work out from the code
> so
> I'm not bothering specifying. But if things are less obvious it might be
> worthwhile to spell it out. For instance, sometimes a matrix argument will
> have a num-rows and num-cols given by, say, dimA, but a stride given by a
> variable like 'src_stride', and that needs to be made explicit.
>
Another solution could be to use better variable names like `x_stride`
for input arrary `x`, instead of `src_stride`.


> The current code is very inconsistent about using (i,j) for (rows,cols)
> versus (cols,rows). I prefer (rows,cols) for new code but if changes are
> made to existing code we should probably test it for a while before
> committing.
Do you mean (i,j) refers to i-th row and j-th column? I prefer this
way but old code use the other.
We could change the existing code very slowly, while adding the documents.
Another thing is (threadIdx.x, threadIdx.y). As generally `.x` should
be along the leading dimension of the matrix,
it should be `threadIdx.x`-th column and `threadIdx.y`-th row, for
simple 2D block/grid arrangement.

>
> Also, we should try to keep mostly to the 80-char-per-line limit required
> by the
> rest of Kaldi, which the CUDA code is very out of compliance with.
>
I will make a separate PR on this. It should be quick.

**Comment by kangshiyin** [comment]
Sorry, it was me. I used a wrong email account to reply.
